INTERFACE
SUBROUTINE EC_RANK_REORDER(KCOMM, KNEWCOMM)
USE PARKIND1 ,ONLY : JPIM
INTEGER(KIND=JPIM), INTENT(IN)  :: KCOMM
INTEGER(KIND=JPIM), INTENT(OUT) :: KNEWCOMM
END SUBROUTINE EC_RANK_REORDER
END INTERFACE
