SUBROUTINE INVERTCOL(ITAB,KX,KY)
IMPLICIT NONE 
INTEGER,                  INTENT(IN)   :: KX,KY
INTEGER,DIMENSION(KX,KY), INTENT(INOUT)::ITAB

ITAB(:,2:KY:2) = ITAB(KX:1:-1,2:KY:2)

END SUBROUTINE INVERTCOL

