INTERFACE
SUBROUTINE DILAT(KM,KNSMAX,KNSMIN,KDGNH,PNM,PMAPP,PRPNM,PALPHA,PBETA)  
!     ------------------------------------------------------------------
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
!     ------------------------------------------------------------------
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)    :: KM 
INTEGER(KIND=JPIM),INTENT(IN)    :: KNSMAX 
INTEGER(KIND=JPIM),INTENT(IN)    :: KNSMIN 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDGNH 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNM(2*KDGNH,KNSMIN-KM+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMAPP(2*KDGNH) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRPNM(KDGNH,KNSMAX-KM+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PALPHA(KNSMAX-KM+1,KNSMIN-KM+1)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PBETA(KNSMAX-KM+1,KNSMIN-KM+1)
!     ------------------------------------------------------------------
END SUBROUTINE DILAT
END INTERFACE
