INTERFACE
SUBROUTINE EBALFESTAT(KFLEV,KSMAX,KNMSMAX,KLEN,KMVALUE,KNVALUE,PVOR,PDIV,PT,PSP, &
 & PQ,PQB,PDIVB,PTB,PSPB,PQBPB,PQBDIVU,PQBTPSU,PTBPB,PTBDIVU,PSPBPB,PSPBDIVU, &
 & PFACT1,PSQ,PSDIV,PSTPS) 
USE PARKIND1  ,ONLY : JPIM     ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV, KSMAX, KNMSMAX, KLEN
INTEGER(KIND=JPIM), INTENT(IN) :: KMVALUE(KLEN), KNVALUE(KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PVOR(KFLEV,KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PDIV(KFLEV,KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PT(KFLEV,KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PSP(KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PQ(KFLEV,KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PFACT1(KLEN)
REAL(KIND=JPRB),    INTENT(IN) :: PSQ(KFLEV,3*KFLEV+1,0:KSMAX)
REAL(KIND=JPRB),    INTENT(IN) :: PSDIV(KFLEV,KFLEV,0:KSMAX)
REAL(KIND=JPRB),    INTENT(IN) :: PSTPS(KFLEV+1,2*KFLEV,0:KSMAX)
REAL(KIND=JPRB), INTENT(OUT) :: PDIVB(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PQB(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PTB(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PSPB(KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PQBPB(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PTBPB(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PSPBPB(KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PQBDIVU(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PTBDIVU(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PQBTPSU(KFLEV,KLEN)
REAL(KIND=JPRB), INTENT(OUT) :: PSPBDIVU(KLEN)
END SUBROUTINE EBALFESTAT
END INTERFACE
