INTERFACE
SUBROUTINE ECALCOV(NFLEV,NSMAX,NMSMAX,NSPEC2,KMVALUE,KNVALUE,PDJKSTAR, &
 & STPS,SQ,SDIV,FACT1,LDBAL,ELON1,ELAT1,ELON2,ELAT2,ELON0,ELAT0,NDGL,NDLON, &
 & NDGUX,NDLUX,CDOUTCVT,CDOUTCVU,PPL,KLOGMAX,KSTART,KHOUR)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT(IN) :: NFLEV, NSMAX, NMSMAX, NSPEC2
INTEGER(KIND=JPIM), INTENT(IN) :: KMVALUE(NSPEC2), KNVALUE(NSPEC2)
REAL(KIND=JPRB),    INTENT(IN) :: PDJKSTAR
REAL(KIND=JPRB),    INTENT(IN) :: STPS(NFLEV+1,2*NFLEV  ,0:NSMAX)
REAL(KIND=JPRB),    INTENT(IN) :: SQ(  NFLEV  ,3*NFLEV+1,0:NSMAX)
REAL(KIND=JPRB),    INTENT(IN) :: SDIV(NFLEV,    NFLEV,  0:NSMAX)
REAL(KIND=JPRB),    INTENT(IN) :: FACT1(NSPEC2)
LOGICAL,            INTENT(IN) :: LDBAL
REAL(KIND=JPRB),    INTENT(IN) :: ELON1,ELAT1,ELON2,ELAT2,ELON0,ELAT0
INTEGER(KIND=JPIM), INTENT(IN) :: NDGL,NDLON,NDGUX,NDLUX
CHARACTER(LEN=*),   INTENT(IN) :: CDOUTCVT,CDOUTCVU
REAL(KIND=JPRB),    INTENT(IN) :: PPL
INTEGER(KIND=JPIM), INTENT(IN) :: KLOGMAX
INTEGER(KIND=JPIM), INTENT(IN) :: KSTART,KHOUR
END SUBROUTINE ECALCOV
END INTERFACE
