INTERFACE
SUBROUTINE GATHKSPEC(KFLEV,KSPEC2,KCASE,PSPVOR,PSPDIV,PSPT,PSPQ,PSPSP,PSPUB,PSPVB,PSPO3)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE MPL_MODULE
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV,KSPEC2,KCASE
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPVOR(KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPDIV(KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPT (KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPQ (KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPSP (KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPUB(KFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPVB(KFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPO3 (KFLEV,KSPEC2)
END SUBROUTINE GATHKSPEC
END INTERFACE
