INTERFACE
SUBROUTINE SUBIASPEC(NFLEV,NSMAX,LDUVBAL,LDOZONE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: NFLEV, NSMAX
LOGICAL, INTENT(IN) :: LDUVBAL
LOGICAL, INTENT(IN) :: LDOZONE
END SUBROUTINE SUBIASPEC
END INTERFACE
