INTERFACE
SUBROUTINE SUDIL(KNSMAX,KNSMIN,KNSLIM,KDGLG,KPROC,KMYPROC,KOUTENV,PSTRET,&
 & LDIMST,KNIMES,KFACTM,KTAG,LDOPT_NSLIM,KTEST,KTESTIO,LDIOPNM,KMBX)
!     ------------------------------------------------------------------
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE PARKIND2  ,ONLY : JPRH
USE MPL_MODULE
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
!     ------------------------------------------------------------------
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN) :: KNSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KNSMIN
INTEGER(KIND=JPIM),INTENT(IN) :: KNSLIM
INTEGER(KIND=JPIM),INTENT(IN) :: KDGLG
INTEGER(KIND=JPIM),INTENT(IN) :: KPROC
INTEGER(KIND=JPIM),INTENT(IN) :: KMYPROC
INTEGER(KIND=JPIM),INTENT(IN) :: KOUTENV(6)
REAL(KIND=JPRB),   INTENT(IN) :: PSTRET
LOGICAL,           INTENT(IN) :: LDIMST
INTEGER(KIND=JPIM),INTENT(IN) :: KNIMES
INTEGER(KIND=JPIM),INTENT(IN) :: KFACTM
INTEGER(KIND=JPIM),INTENT(IN) :: KTAG
LOGICAL,           INTENT(IN) :: LDOPT_NSLIM
INTEGER(KIND=JPIM),INTENT(IN) :: KTEST
INTEGER(KIND=JPIM),INTENT(IN) :: KTESTIO
LOGICAL,           INTENT(IN) :: LDIOPNM
INTEGER(KIND=JPIM),INTENT(IN) :: KMBX

!     ------------------------------------------------------------------
END SUBROUTINE SUDIL
END INTERFACE
