INTERFACE
SUBROUTINE SUFESPECA(NFLEV,NSMAX,KSPEC2,KCASE,LDSCATTER,PSPVOR,PSPDIV,PSPT,PSPQ,PSPSP,&
 & PSPUB,PSPVB,PSPO3)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: NFLEV,NSMAX,KSPEC2
INTEGER(KIND=JPIM), INTENT(IN) :: KCASE
LOGICAL,            INTENT(IN), OPTIONAL :: LDSCATTER
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPVOR(NFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPDIV(NFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPT (NFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPQ (NFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPSP (KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPUB(NFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPVB(NFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPO3(NFLEV,KSPEC2)
END SUBROUTINE SUFESPECA
END INTERFACE
