INTERFACE
SUBROUTINE SUMP_DILA(KDGLG,KDGNH,KPROC,KMYPROC,KOUTENV,&
 & KDGNHX,KDGNHL0,KDGNHL,KDGLL,KPROCGL,KGLG,KGLG0)
!     ------------------------------------------------------------------
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
!     ------------------------------------------------------------------
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)   :: KDGLG
INTEGER(KIND=JPIM),INTENT(IN)   :: KDGNH
INTEGER(KIND=JPIM),INTENT(IN)   :: KPROC
INTEGER(KIND=JPIM),INTENT(IN)   :: KMYPROC
INTEGER(KIND=JPIM),INTENT(IN)   :: KOUTENV(4)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KDGNHX
INTEGER(KIND=JPIM),INTENT(OUT)  :: KDGNHL0(KPROC)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KDGNHL
INTEGER(KIND=JPIM),INTENT(OUT)  :: KDGLL
INTEGER(KIND=JPIM),INTENT(OUT)  :: KPROCGL(KDGLG)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KGLG(KDGLG)
INTEGER(KIND=JPIM),INTENT(OUT)  :: KGLG0(KDGLG,KPROC)
!     ------------------------------------------------------------------
END SUBROUTINE SUMP_DILA
END INTERFACE
