INTERFACE
SUBROUTINE TRLTOM_DIL(KDGLG,KDGLL,KNSMIN,KPROC,KMYPROC,KNUMP,KTYP,&
 & KPNM,KPNML,KTAG,KRDEB,KNPROCM,KMYMS,KGLG,KGLG0,KDGNHL0,LD_PERLAT,&
 & PTAB_IN,PTAB_OUT)
!     ------------------------------------------------------------------
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE MPL_MODULE
!     ------------------------------------------------------------------
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN)  :: KDGLG
INTEGER(KIND=JPIM),INTENT(IN)  :: KDGLL
INTEGER(KIND=JPIM),INTENT(IN)  :: KNSMIN
INTEGER(KIND=JPIM),INTENT(IN)  :: KPROC
INTEGER(KIND=JPIM),INTENT(IN)  :: KMYPROC
INTEGER(KIND=JPIM),INTENT(IN)  :: KNUMP
INTEGER(KIND=JPIM),INTENT(IN)  :: KTYP
INTEGER(KIND=JPIM),INTENT(IN)  :: KPNM
INTEGER(KIND=JPIM),INTENT(IN)  :: KPNML
INTEGER(KIND=JPIM),INTENT(IN)  :: KTAG
INTEGER(KIND=JPIM),INTENT(IN)  :: KRDEB(0:KNSMIN+1)
INTEGER(KIND=JPIM),INTENT(IN)  :: KNPROCM(0:KNSMIN)
INTEGER(KIND=JPIM),INTENT(IN)  :: KMYMS(KNSMIN+1)
INTEGER(KIND=JPIM),INTENT(IN)  :: KGLG(KDGLG*(3-KTYP))
INTEGER(KIND=JPIM),INTENT(IN)  :: KGLG0(KDGLG*(3-KTYP),KPROC)
INTEGER(KIND=JPIM),INTENT(IN)  :: KDGNHL0(KPROC)
LOGICAL           ,INTENT(IN)  :: LD_PERLAT
REAL(KIND=JPRB)   ,INTENT(IN)  :: PTAB_IN(KDGLL,KPNM)
REAL(KIND=JPRB)   ,INTENT(OUT) :: PTAB_OUT(KDGLG,KPNML)
!     ------------------------------------------------------------------
END SUBROUTINE TRLTOM_DIL
END INTERFACE
