INTERFACE
SUBROUTINE UNBIASPEC(KFLEV,KSPEC2,PSPVOR,PSPDIV,PSPT,PSPQ,PSPSP,PSPUB,PSPVB,PSPO3)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KSPEC2
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPVOR(KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPDIV(KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPT (KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPQ (KFLEV,KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPSP (KSPEC2)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPUB(KFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPVB(KFLEV)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PSPO3 (KFLEV,KSPEC2)
END SUBROUTINE UNBIASPEC
END INTERFACE
