INTERFACE
SUBROUTINE ATLAS_READ(KUNIT,CDFILE,KIOMASTER,GRID_ATLAS,LDABORT)
USE PARKIND1 , ONLY : JPIM,   JPRB
USE YOMEMIS  , ONLY : ATLAS_GRIDDEF
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT(IN)  :: KUNIT
CHARACTER(LEN=*), INTENT(IN)    :: CDFILE
INTEGER(KIND=JPIM), INTENT(IN)  :: KIOMASTER
LOGICAL, INTENT(IN)             :: LDABORT
TYPE(ATLAS_GRIDDEF), INTENT(INOUT)  :: GRID_ATLAS
END SUBROUTINE
END INTERFACE
