INTERFACE
SUBROUTINE ATLAS_INTERPOLATE (PLAT,PLON,PTOLERANCE,ATLAS,E_RET, &
  NFOUND,NMIN_INDEX,NCOL_OFFSET,NCOL_STEP)
USE PARKIND1  ,ONLY : JPIM     ,JPRB 
USE YOMEMIS , ONLY : ATLAS_GRIDDEF
IMPLICIT NONE
REAL(KIND=JPRB), INTENT(IN)     :: PLAT
REAL(KIND=JPRB), INTENT(IN)     :: PLON
REAL(KIND=JPRB), INTENT(IN)     :: PTOLERANCE
TYPE(ATLAS_GRIDDEF), INTENT(IN) :: ATLAS
REAL(KIND=JPRB), INTENT(OUT)    :: E_RET(:)
INTEGER(KIND=JPIM), INTENT(OUT) :: NFOUND
INTEGER(KIND=JPIM), INTENT(OUT) :: NMIN_INDEX
INTEGER(KIND=JPIM), INTENT(IN),OPTIONAL :: NCOL_OFFSET
INTEGER(KIND=JPIM), INTENT(IN),OPTIONAL :: NCOL_STEP
END SUBROUTINE
END INTERFACE
