INTERFACE
SUBROUTINE LAND_SURF_TYPE (PLAT,PLON,PBATS_VEG)
USE PARKIND1  ,ONLY : JPIM     ,JPRB 
IMPLICIT NONE
REAL(KIND=JPRB), INTENT(IN)  :: PLAT
REAL(KIND=JPRB), INTENT(IN)  :: PLON
REAL(KIND=JPRB), INTENT(OUT) :: PBATS_VEG
END SUBROUTINE
END INTERFACE
