INTERFACE
SUBROUTINE LAND_IASI(PLAT,PLON,PE_IASI)
USE PARKIND1  ,ONLY : JPIM     ,JPRB 
IMPLICIT NONE
REAL(KIND=JPRB), INTENT(IN)   :: PLAT
REAL(KIND=JPRB), INTENT(IN)   :: PLON
REAL(KIND=JPRB), INTENT(OUT)  :: PE_IASI(:)
END SUBROUTINE
END INTERFACE
