INTERFACE
      SUBROUTINE RTTOV_HDF_LOAD( ERR, F, PATH, PROFILE, PROFILES, OPTIONS, CHANPROF, &
        & EMISSIVITY, REFLECTANCE, COEF, SCCLDCOEF, SCAERCOEF, OPTP, MFASISLUTCLD, MFASISLUTAER, &
        & PCCOEF, OPT_PARAM, I0, R0, RM0, C0, PL1, PR1, PRM1, PR2, PRM2, PR3, PRM3, PR4, PRM4,&
        & PIT1, PIT2, PIT3, PIS1, PIS2, PIS3, PIS4, PI1, PI2, PI3, PIL1,&
        & SNAME, LBL )
      USE PARKIND1
      USE RTTOV_TYPES
      IMPLICIT NONE
      CHARACTER(LEN=*),    INTENT(IN)  :: F
      CHARACTER(LEN=*),    INTENT(IN)  :: PATH
      INTEGER(KIND=JPIM),  INTENT(OUT) :: ERR
      TYPE(RTTOV_PROFILE), INTENT(OUT), OPTIONAL :: PROFILE
      TYPE(RTTOV_PROFILE), POINTER, OPTIONAL     :: PROFILES(:)
      TYPE(RTTOV_OPTIONS), INTENT(OUT), OPTIONAL :: OPTIONS
      TYPE(RTTOV_CHANPROF), POINTER, OPTIONAL    :: CHANPROF(:)
      TYPE(RTTOV_EMISSIVITY),  POINTER, OPTIONAL :: EMISSIVITY(:)
      TYPE(RTTOV_REFLECTANCE), POINTER, OPTIONAL :: REFLECTANCE(:)
      TYPE(RTTOV_COEF), OPTIONAL                 :: COEF
      TYPE(RTTOV_COEF_SCATT_IR), OPTIONAL        :: SCCLDCOEF
      TYPE(RTTOV_COEF_SCATT_IR), OPTIONAL        :: SCAERCOEF
      TYPE(RTTOV_OPTPAR_IR),     OPTIONAL        :: OPTP
      TYPE(RTTOV_COEF_MFASIS),   OPTIONAL        :: MFASISLUTCLD
      TYPE(RTTOV_COEF_MFASIS),   OPTIONAL        :: MFASISLUTAER
      TYPE(RTTOV_COEF_PCCOMP),   OPTIONAL        :: PCCOEF
      TYPE(RTTOV_OPT_PARAM),     OPTIONAL        :: OPT_PARAM
      INTEGER(KIND=JPIM),       OPTIONAL :: I0
      REAL(KIND=JPRB),          OPTIONAL :: R0
      REAL(KIND=JPRM),          OPTIONAL :: RM0
      CHARACTER(LEN=*),         OPTIONAL :: C0
      INTEGER(KIND=JPIT),     POINTER , OPTIONAL :: PIT1(:)
      INTEGER(KIND=JPIT),     POINTER , OPTIONAL :: PIT2(:,:)
      INTEGER(KIND=JPIT),     POINTER , OPTIONAL :: PIT3(:,:,:)
      INTEGER(KIND=JPIS),     POINTER , OPTIONAL :: PIS1(:)
      INTEGER(KIND=JPIS),     POINTER , OPTIONAL :: PIS2(:,:)
      INTEGER(KIND=JPIS),     POINTER , OPTIONAL :: PIS3(:,:,:)
      INTEGER(KIND=JPIS),     POINTER , OPTIONAL :: PIS4(:,:,:,:)
      INTEGER(KIND=JPIM),     POINTER , OPTIONAL :: PI1(:)
      INTEGER(KIND=JPIM),     POINTER , OPTIONAL :: PI2(:,:)
      INTEGER(KIND=JPIM),     POINTER , OPTIONAL :: PI3(:,:,:)
      INTEGER(KIND=JPIB),     POINTER , OPTIONAL :: PIL1(:)
      REAL(KIND=JPRB),        POINTER , OPTIONAL :: PR1(:)
      REAL(KIND=JPRB),        POINTER , OPTIONAL :: PR2(:,:)
      REAL(KIND=JPRB),        POINTER , OPTIONAL :: PR3(:,:,:)
      REAL(KIND=JPRB),        POINTER , OPTIONAL :: PR4(:,:,:,:)
      REAL(KIND=JPRM),        POINTER , OPTIONAL :: PRM1(:)
      REAL(KIND=JPRM),        POINTER , OPTIONAL :: PRM2(:,:)
      REAL(KIND=JPRM),        POINTER , OPTIONAL :: PRM3(:,:,:)
      REAL(KIND=JPRM),        POINTER , OPTIONAL :: PRM4(:,:,:,:)
      LOGICAL,                POINTER , OPTIONAL :: PL1(:)
      CHARACTER(LEN=*),       OPTIONAL :: SNAME
      LOGICAL,                OPTIONAL :: LBL
END SUBROUTINE
END INTERFACE
