SUBROUTINE MAGICS_DUMMY_ABORT(CDNAME)
IMPLICIT NONE
CHARACTER(LEN=*), INTENT(IN) :: CDNAME
CHARACTER(LEN=*), PARAMETER  :: CLMSG = &
#ifdef NEW_MAGICS
& '***ERROR: The program has not been linked with the proper MAGICS++ library. This is a dummy version of routine '
#else
& '***ERROR: The program has not been linked with the proper MAGICS library. This is a dummy version of routine '
#endif
WRITE(0,'(1x,a)') CLMSG//CDNAME
!CALL ABOR1(CLMSG//CDNAME)
END SUBROUTINE MAGICS_DUMMY_ABORT
#ifndef HAS_MAGICS
SUBROUTINE POPEN
!!CALL MAGICS_DUMMY_ABORT('POPEN')
END SUBROUTINE POPEN
SUBROUTINE PSETC
!!CALL MAGICS_DUMMY_ABORT('PSETC')
END SUBROUTINE PSETC
SUBROUTINE PSETR
!!CALL MAGICS_DUMMY_ABORT('PSETR')
END SUBROUTINE PSETR
SUBROUTINE PSETI
!!CALL MAGICS_DUMMY_ABORT('PSETI')
END SUBROUTINE PSETI
SUBROUTINE PTEXT
!!CALL MAGICS_DUMMY_ABORT('PTEXT')
END SUBROUTINE PTEXT
SUBROUTINE PNEW
!!CALL MAGICS_DUMMY_ABORT('PNEW')
END SUBROUTINE PNEW
SUBROUTINE PSET1C
!!CALL MAGICS_DUMMY_ABORT('PSET1C')
END SUBROUTINE PSET1C
SUBROUTINE PAXIS
!!CALL MAGICS_DUMMY_ABORT('PAXIS')
END SUBROUTINE PAXIS
SUBROUTINE PSET1R
!!CALL MAGICS_DUMMY_ABORT('PSET1R')
END SUBROUTINE PSET1R
SUBROUTINE PGRAPH
!!CALL MAGICS_DUMMY_ABORT('PGRAPH')
END SUBROUTINE PGRAPH
SUBROUTINE PENQC
!!CALL MAGICS_DUMMY_ABORT('PENQC')
END SUBROUTINE PENQC
SUBROUTINE PCLOSE
CALL MAGICS_DUMMY_ABORT('PCLOSE')
END SUBROUTINE PCLOSE
SUBROUTINE PRESET
!!CALL MAGICS_DUMMY_ABORT('PRESET')
END SUBROUTINE PRESET
SUBROUTINE PSET2R
!!CALL MAGICS_DUMMY_ABORT('PSET2R')
END SUBROUTINE PSET2R
SUBROUTINE PSET1I
!!CALL MAGICS_DUMMY_ABORT('PSET1I')
END SUBROUTINE PSET1I
SUBROUTINE PCOAST
!!CALL MAGICS_DUMMY_ABORT('PCOAST')
END SUBROUTINE PCOAST
SUBROUTINE PCONT
!!CALL MAGICS_DUMMY_ABORT('PCONT')
END SUBROUTINE PCONT
SUBROUTINE PWIND
!!CALL MAGICS_DUMMY_ABORT('PWIND')
END SUBROUTINE PWIND
SUBROUTINE PSYMB
!!CALL MAGICS_DUMMY_ABORT('PSYMB')
END SUBROUTINE PSYMB
#endif
