INTERFACE
INTEGER(KIND=JPIM) FUNCTION MO_GET_SPC_NDX(YGFL, CDSPC_NAME )
USE PARKIND1  ,ONLY : JPIM
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) , INTENT(IN):: YGFL
CHARACTER(LEN=*), INTENT(IN) :: CDSPC_NAME
END FUNCTION MO_GET_SPC_NDX
END INTERFACE
