
!*    NAMELIST NACTAN - ANALYSIS AREA DEFINITION FOR CANARI


!      NAME                 MEANING                       DEFAULT
!      ----                 -------                       -------

!     LANMASK  .T. PARTIAL ANALYSIS OVER THE GRID            .F.

!     ALATNB   NORTHERN BOUNDARY OF ANALYSIS AREA            90. (ELAT2)
!     ALATSB   SOUTHERN BOUNDARY OF ANALYSIS AREA           -90. (ELAT1)
!     ALONWB   WESTERN BOUNDARY OF ANALYSIS AREA           -180. (ELON1)
!     ALONEB   EASTERN BOUNDARY OF ANALYSIS AREA            180. (ELON2)


NAMELIST / NACTAN / LANMASK , ALATNB , ALATSB , ALONWB , ALONEB
