!     -----------------------------------------------------------------
NAMELIST/NAEPHY/&
 &      LEPHYS, LSLPHY, LECOND, LECUMF, LEDCLD, LEEVAP &
 &,     LEGWDG, LEOZOC, LEQNGT, LERADI, LERADS &
 &,     LESICE, LESURF, LEGWWMS &
 &,     LEVDIF&
 &,     LEVGEN, LESSRO, LELAIV, LESN09, LECTESSEL, LESNML &
 &,     LEAGS , RLAIINT, LEFLAKE, LSPCRM &
 &,     LEPCLD, LAGPHY ,LEO3CH, LO3CH_OLDVER, LO3CH_BMS, LO3CH_HLO, CO3CHEM, LO3CH_SAFE &
 &,     LECO2DIU, LNEEONLINE, LBFASCO2 &
 &,     NCO2CLIMYY1, NCO2CLIMYY2, NCO2CLIMN1, NCO2CLIMN2, NCO2CLIMFRQ &
 &,     LWCOU  ,LWCOU2W, LWCUR, LWSTOKES, LBUD23, LPPTILES, LBUDCYCLE, LEMETHOX, LERAIN &
 &,     LVDFTRAC,LMFTRAC,LMFSCAV,LEOCWA,LEOCCO,LEOCML,LEOCLAKE,LEOBC &
 &,     LEOBCICE,LEOLAKESST,LOCMLTKE,LEOCSA,LEOCLA,LEOBCMAX,REOBCMAX, &
 &      NSTPW,RSOUTW ,RNORTW ,RDEGREW &
 &,     LECURR &
 &,     LESURFTRAJ &
 &,     RTHRFRTI &
 &,     RCLDTOPP &
 &,     LEMWAVE, LECLIPQT0, LECLIPCLDT0, LDUCTDIA &
 &,     LEGBRAD, NPRACCL, LERAINGG, LESMOS &
 &,     RNORTHML,RSOUTHML,REASTML,RWESTML,INVML &
 &,     RCIMIN, LELIGHT, NLIMODE, LRAD_CLOUD_INHOMOG, LDIAGTURB_EC, NSNMLWS &
 &,     NALBEDOSCHEME, NEMISSSCHEME, RALFMINPSN
!     -----------------------------------------------------------------


