NAMELIST / NAMCOMPO / AERO_SCHEME, LCO2SFC, LCH4SFC, LAEROSFC, LFIRE, LINJ, LINJ_CHEM, LINJ_GHG, LCHEM_DIA, LCHEM_DDFLX,&
& LCOMPO_DDFLX_DIR,LGHG_ACCO2,LCOMPO_DCDD,LCOMPO_DCBB,LCOMPO_DCVOC,LCOMPO_DCANT,LANT_HIGH, & 
& LCHEM_TROPO,LVOLC_ALTI,LAERNITRATE,LAERSOA,LAERRESUSPENSION, LAERNUCL
