NAMELIST/NAMCFU/ LCUMFU &
 &,LSTRD  ,LSTRC  ,LSTRT  ,LFPLC  ,LFPLCG ,LFPLCH ,LFPLS  ,LFPLSG ,LFPLSH &
 &,LFR    ,LAMIP  ,LFRRC  ,LRAYS  ,LNEBTT ,LFSF   ,LFSOIL ,LNEBPAR,LTSTRD &
 &,LTSTRC ,LTSTRT ,LTFPLC ,LTFPLS ,LTFR   ,LTNEB  ,NFRCFU ,NCFUTS ,LFDUTP &
 &,LMOON  ,LRAYD ,LFLASH ,NMTFLASH ,CALFLASH1 ,CALFLASH2
