NAMELIST /NAMCLDP/ &
& NAERCLD, NAECLBC, NAECLDU, NAECLOM, NAECLSS, NAECLSU, &
& RCCNOM, RCCNSS, RCCNSU, RVICE, RCLDIFF, RKCONV, RCLDIFF_CONVI, &
& LCLOUD_INHOMOG, RCL_INHOMOGAUT, RCL_INHOMOGACC, RCL_OVERLAPLIQICE, &
& RCL_EFFRIME, RKOOPTAU, RLCRITSNOW, RTAUMEL, RDEPLIQREFDEPTH, RDEPLIQREFRATE, &
& LCLDBUDC, LCLDBUDL, LCLDBUDI, LCLDBUDT, LCLDBUD_VERTINT, LCLDBUD_TIMEINT
