
! ***************** NAMELIST NAMDFI  ***************************

NAMELIST /NAMDFI/ LADIFH, &
&NTPDFI,TAUS,TAUC,NEDFI,RTDFI,RTDFIA,NSTDFI,&
&NOFFSETDFI,RDFIS, &
& QNORM_ADJUST_VOR, QNORM_ADJUST_DIV, QNORM_ADJUST_T, QNORM_ADJUST_Q, &
& QNORM_ADJUST_LNSP
