!     ------------------------------------------------------------------
NAMELIST/NAMDYNA/LGWADV,NGWADVSI,NPDVAR,NVDVAR,LRDBBC,&
 & LSLHD_W,LSLHD_T,LSLHD_SPD,LSLHD_SVD,LSLHD_GFL,LSLHD_OLD,LSLHD_STATIC, &
 & SLHDKMIN,SLHDKREF,SLHDKMAX,SLHDEPSH,SLHDEPSV,LSLHDVER,ND4SYS, &
 & LSLDIA,L3DTURB,LGRADSP,LGRADGP,&
 & LAPRXPK,NDLNPR,RHYDR0,LHOISLT,HOISLTV,HOISLTH,LSLTVWENO,LRHSVWENO,LDRY_ECMWF,L_RDRY_VD,&
 & LRALTVDISP,LRPRSLTRJ,&
 & LSETTLST,LSETTLSV,LSETTLS,LELTRA,LNESCT,LNESCV,LNESC,LPC_FULL,LPC_CHEAP,LPC_CHEAP2,LRUBC, &
 & LCOMADH,LCOMADV,LCOMAD_W,LCOMAD_T,LCOMAD_SPD,LCOMAD_SVD,LCOMAD_SP,LCOMAD_GFL,LNHQE_SIHYD,LSI_NHEE, &
 & LNHEE_SVDLAPL_FIRST, LMIXETTLS,LMIXETTLS_PRINT,RMIXNL_TRH, &
 & REXP_VRAT,LNHEE_REFINE_SILAPL,LVEREGINT,LNHEE_REFINE_GRP,LNHEE_REFINE_PREH_BBC
!     ------------------------------------------------------------------
