 NAMELIST/NAMEMIS_CONF/&
  &LATLAS_AMSU,LATLAS_PARAM_AMSU,LDYN_AMSU,LSKIN_AMSU,&
  &LATLAS_SSMI,LDYN_SSMI,&
    &LSKIN_SSMI,&
  &LATLAS_SSMIS,LDYN_SSMIS,&
    &LSKIN_SSMIS,&
  &LATLAS_TMI,LDYN_TMI,&
    &LSKIN_TMI,&
  &LATLAS_AMSRE,LDYN_AMSRE,&
    &LSKIN_AMSRE, &
  &LATLAS_ATMS,LDYN_ATMS,&
    &LSKIN_ATMS, &
  &LATLAS_MWTS2,LDYN_MWTS2, &
    &LSKIN_MWTS2, LICE_MWTS2,&
  &LATLAS_MWHS2,LDYN_MWHS2, &
    &LSKIN_MWHS2, LICE_MWHS2,&
  &LATLAS_AMSR2,LDYN_AMSR2,&
    &LSKIN_AMSR2, LICE_AMSR2,&
  &LATLAS_MTVZAGY,LDYN_MTVZAGY,&
    &LSKIN_MTVZAGY, LICE_MTVZAGY,&
  &LATLAS_MWRI,LDYN_MWRI,&
    &LSKIN_MWRI,&
  &LATLAS_SAPHIR,LDYN_SAPHIR,&
    &LSKIN_SAPHIR, &
  &LATLAS_GMI,LDYN_GMI,&
    &LSKIN_GMI, &
  &MEMIS_CHAN, MTSKIN_CHAN,&
  &LATLAS_EMIS, LDYN_EMIS,&
   &LDYN_TSKIN, LDYN_ICE, &
   &LUSE_DYN_TSKIN, &
  &LICE_AMSU, LICE_SSMI, &
   &LICE_SSMIS, LICE_TMI, &
   &LICE_AMSRE, LICE_WINDSAT, &
   &LICE_ATMS,  LICE_SAPHIR, &
   &LICE_GMI, &
  &LCHECK_DYNEMIS, &
  &LATLAS_SEV, LSKIN_SEV, LDYN_SEV, &
  &LUSE_TELSEM
