NAMELIST/NAMGRIB/NLOCGRB,NENSFNB,NTOTENS,NWINOFF,NWINOFF_4V,&
                &NJDIAG,NJDOMAI,NJITER,NSTREAM,NSYSTEM,NMETHOD,&
                &NREFERENCE,NCONSENSUS,NDWD,NMFR,NNCEP,NUKM,&
                &NLEG,NCYCLE,CFCLASS,CTYPE,&
                &NBITSSHLNSP,LFORCEZ,LFORCELNSP

