!     ------------------------------------------------------------
NAMELIST/NAMMCC/&
  &LCURR,LGELATO,LMCC01_MSE,LMCC01,LMCC02,LMCC03,LMCC04,LMCC05,LMCCEC,LMCCIEC, &
  &LMCCICEIC,N923,NOACOMM,NFRCPL,LNEMOCOUP,LNEMOFLUXNC,LNEMO1WAY, &
  &LMCCDYNSEAICE,LNEMOLIMGET,LNEMOLIMPUT,LNEMOLIMALB,LNEMOLIMTEMP, &
  &LNEMOLIMTHK,LMULTIYR,LMCC_COMPO,LNEMOATMFLDS,LNEMOIFSLOG,NSSTICEOP,&
  &LNEMOSSTFREEZ,LNEMOLIMTLVL,LNEMOOCEICEMIX,LNEMOQNSICEFILT,LNEMOSICOUP,&
  &LNEMOGRIBFLDS,LNEMOPARTCOUP,LNEMOPARTMASK,RNPARTRAMPSTART,RNPARTRAMPLEN,&
  &RNPARTLAT,RNPARTLATSPREAD,LNEMOPARTMASKFILE,CDNPARTMASKFILE,LNEMOGRIB3D,&
  &NNEMO3DLEVS,LNEMOGRIBMASK
