NAMELIST/NAMMODERR/NTYPE_MODERR, LFGMODERR, NORDER_MODERR, &
                 & WEAK4D_INTERV, TSTEP_ERR, ALPHAQ, NSERR, &
                 & LJQVCOR, LJQHCOR, LJQZERO, NLEVERR0, NLEVERR1, &
                 & ALPHAQ_T, ALPHAQ_D, ALPHAQ_V, ALPHAQ_Q, ALPHAQ_O, &
                 & NPRTMODERR, LTAPERERR, TAPERERR_INI, TAPERERR_END 
