
!     ------------------------------------------------------------
NAMELIST/NAMNUD/&
 & LNUDG,  NFNUDG, NTNUDG, NFRNUDG &
 & ,XNUDDI, XNUDLP, XNUDRM, XNUDSD, XNUDSH, XNUDSM, XNUDST &
 & ,XNUDSV, XNUDTE, XNUDVO &
 & ,LNDRIV &
 & ,XNUDTG, XNUDQG, XNUDUG, XNUDVG, XNUDPG, XNUVERT  &
 & ,LNUDTG, LNUDQG, LNUDUG, LNUDVG, LNUDPG, LWNUDG &
 & ,LNUDDI, LNUDLP, LNUDRM, LNUDSD, LNUDSH &
 & ,LNUDSM, LNUDST, LNUDSV, LNUDTE, LNUDVO &
 & ,NSPNU1, NSPNU2
