! CONTROLS LHNUDG TERM
!     ------------------------------------------------------------------
NAMELIST/NAMNUDGLH/&
&LNUDGLH, LNUDGLHCOMPT, LNUDGLHREAD, LNUDGLHSTEPH, &
&LNUDGLHCLIM, LNUDGLHENVI, LNUDGLHSUBSAT, &
&TTAUNUDGLH, TSTARTNUDGLH, &
&TSTOPNUDGLH, TINTNUDGLH, RDAMPNUDGLH, &
&NTOPNUDGLH, NBOTTOMNUDGLH,RPRTOPSNUDGLH, &
&RPRTOPCNUDGLH,RPRTOPTNUDGLH,RPRTOPWNUDGLH,&
&RPRTOPSTABNUDGLH,RFACNUDGLH, &
&RPRMAXSNUDGLH,RPRMAXCNUDGLH,RPRMAXTNUDGLH,&
&RPRMAXWNUDGLH,RPRBOTTOMSNUDGLH, &
&RPRBOTTOMCNUDGLH,RPRBOTTOMTNUDGLH,&
&RPRBOTTOMWNUDGLH,RPRBOTTOMSTABNUDGLH, &
&RHEATSNUDGLH,RHEATANUDGLH,RHEATBNUDGLH,&
&RHEATCNUDGLH,RHEATDNUDGLH,RHEATTNUDGLH,&
&RHEATWNUDGLH,RHEATSTABNUDGLH, &
&RAMPLIFY,RMAXNUDGLH,RMINNUDGLH,RORONUDGLH, &
&RALPHANUDGLH,REPSILONNUDGLH,NTIMESPLITNUDGLH
!     ------------------------------------------------------------------
