
!     NAMELIST DISCRIPTION OF PHYSICS FIELDS SETUP

NAMELIST/NAMPHYDS/&
                  &CEXTRP,  CVEXTRA,    CVEXRAD,  CVEXTR2, &
                  &NEXTRPGB, NVEXTRAGB, NVEXRADGB,NVEXTR2GB, &
                  &EXTRPDF,  VEXTRADF,  VEXRADDF, VEXTR2DF, &
                  &NSFORC, NSFLUX, NVEXTRDIGB, CVEXTRDI, &
		  &NPPVCLIX,&
                  &VEXTRDI,LREQIN_VEXTRDI, LREQOUT_VEXTRDI
