
!     ------------------------------------------------------------
NAMELIST/NAMRLX/&
 & LRLXG, NFRLXG &
 & , LRLXVO, LRLXDI, LRLXTE, LRLXQ, LRLXLP &
 & ,LRLXQI,LRLXQL,LRLXQC,LRLXO3 &
 & , XRLXVO, XRLXDI, XRLXTE,XRLXQ, XRLXO3, XRLXLP &
 & , ALATRLX1, ALATRLX2, ALONRLX1, ALONRLX2 &
 & , NRLXLMIN, NRLXLMAX, NRLXLMINU, NRLXLMAXU, AXRLX ,AYRLX ,AZRLX &
 & , NRLXSMAX
