NAMELIST /NAMSPP/ LSPP, LPERT_CFM &
                &,LPERT_TOFDC, LPERT_HSDT &
                &,LPERT_VDEXC_LEN_STABLE_BL &
                &,LPERT_ENTRORG, LPERT_ENTSHALP, LPERT_DETRPEN, LPERT_RPRCON, LPERT_RTAU, LPERT_CUDUDV &
                &,LPERT_RAMID, LPERT_RCLDIFF, LPERT_RCLCRIT, LPERT_RLCRITSNOW &
                &,LPERT_RAINEVAP, LPERT_SNOWSUBLIM, LPERT_QSATVERVEL &
                &,LPERT_ZDECORR, LPERT_ZSIGQCW, LPERT_ZRADEFF, LPERT_ZRADEFF2  &
                &,LPERT_PHR, LPERT_ZHS_VDAERO, LPERT_DELTA_AERO &
                &,LLNN_MEAN1, LLNN_MEAN1_CFM, LLNN_MEAN1_TOFDC, LLNN_MEAN1_HSDT &
                &,LLNN_MEAN1_VDEXC_LEN_STABLE_BL, LLNN_MEAN1_ENTRORG, LLNN_MEAN1_ENTSHALP, LLNN_MEAN1_DETRPEN &
                &,LLNN_MEAN1_RPRCON, LLNN_MEAN1_CUDUDV, LLNN_MEAN1_RTAU, LLNN_MEAN1_RAMID, LLNN_MEAN1_RCLDIFF &
                &,LLNN_MEAN1_RCLCRIT, LLNN_MEAN1_RLCRITSNOW &
                &,LLNN_MEAN1_RAINEVAP, LLNN_MEAN1_SNOWSUBLIM, LLNN_MEAN1_QSATVERVEL &
                &,LLNN_MEAN1_ZDECORR, LLNN_MEAN1_ZSIGQCW, LLNN_MEAN1_ZRADEFFLP, LLNN_MEAN1_ZRADEFFIP &
                &,LLNN_MEAN1_PHRLW, LLNN_MEAN1_PHRSW, LLNN_MEAN1_ZHS_VDAERO, LLNN_MEAN1_DELTA_AERO &   
                &,LRAMIDLIMIT1, LUSE_SETRAN, LNSEED_OFFS0, CLSIGN &
                &,CMPERTOC, CMPERTLA, CMPERTTOFD, SDPERTSO, CMPERTLENBL &
                &,CMPERT_ENTRORG, CMPERT_ENTSHALP, CMPERT_DETRPEN, CMPERT_RPRCON, CMPERT_RTAU, CMPERT_CUDU, CMPERT_CUDV &
                &,CMPERT_RAMID, CMPERT_RCLDIFF, CMPERT_RCLCRIT_SEA,  CMPERT_RCLCRIT_LAND, CMPERT_RLCRITSNOW &
                &,CMPERT_RAINEVAP, CMPERT_SNOWSUBLIM, CMPERT_QSATVERVEL &
                &,CMPERT_ZDECORR, CMPERT_ZSIGQCW, CMPERT_ZRADEFFLP, CMPERT_ZRADEFFIP &
                &,CMPERT_PHRLW_ST, CMPERT_PHRLW_TR, CMPERT_PHRSW_ST, CMPERT_PHRSW_TR, CMPERT_ZHS_VDAERO, CMPERT_DELTA_AERO &
                &,XPRESS_PHR_ST, TAU, SDEV, XLCOR, NSEEDFAC &
                &,LRDPATINIT,LWRPATTRUN,NWRPATTRUN,NHOUR_PATTRUN,NSTEP_PATTRUN,LRESETSEED,LABSTIMSEED,RESETSEEDFRQ &
                &,SPP_RDPATINIT,SPP_WRPATTRUN, NPATFR, SHIFTSEED &
                &,LPERT_PSIGQSAT,LLNN_MEAN1_PSIGQSAT,LUNIFORM_PSIGQSAT,UNIFORM_OFFSET_PSIGQSAT,CMPERT_PSIGQSAT,CLIP_PSIGQSAT &
                &,LPERT_CLDDPTH,LLNN_MEAN1_CLDDPTH,LUNIFORM_CLDDPTH,UNIFORM_OFFSET_CLDDPTH,CMPERT_CLDDPTH,CLIP_CLDDPTH &
                &,LPERT_CLDDPTHDP,LLNN_MEAN1_CLDDPTHDP,LUNIFORM_CLDDPTHDP,UNIFORM_OFFSET_CLDDPTHDP,CMPERT_CLDDPTHDP,CLIP_CLDDPTHDP &
                &,LPERT_ICE_CLD_WGT,LLNN_MEAN1_ICE_CLD_WGT,LUNIFORM_ICE_CLD_WGT,UNIFORM_OFFSET_ICE_CLD_WGT,CMPERT_ICE_CLD_WGT,CLIP_ICE_CLD_WGT &
                &,LPERT_ICENU,LLNN_MEAN1_ICENU,LUNIFORM_ICENU,UNIFORM_OFFSET_ICENU,CMPERT_ICENU,CLIP_ICENU &
                &,LPERT_KGN_ACON,LLNN_MEAN1_KGN_ACON,LUNIFORM_KGN_ACON,UNIFORM_OFFSET_KGN_ACON,CMPERT_KGN_ACON,CLIP_KGN_ACON &
                &,LPERT_KGN_SBGR,LLNN_MEAN1_KGN_SBGR,LUNIFORM_KGN_SBGR,UNIFORM_OFFSET_KGN_SBGR,CMPERT_KGN_SBGR,CLIP_KGN_SBGR &
                &,LPERT_RADGR,LLNN_MEAN1_RADGR,LUNIFORM_RADGR,UNIFORM_OFFSET_RADGR,CMPERT_RADGR,CLIP_RADGR &
                &,LPERT_RADSN,LLNN_MEAN1_RADSN,LUNIFORM_RADSN,UNIFORM_OFFSET_RADSN,CMPERT_RADSN,CLIP_RADSN &
                &,LPERT_RFAC_TWOC,LLNN_MEAN1_RFAC_TWOC,LUNIFORM_RFAC_TWOC,UNIFORM_OFFSET_RFAC_TWOC,CMPERT_RFAC_TWOC,CLIP_RFAC_TWOC &
                &,LPERT_RZC_H,LLNN_MEAN1_RZC_H,LUNIFORM_RZC_H,UNIFORM_OFFSET_RZC_H,CMPERT_RZC_H,CLIP_RZC_H &
                &,LPERT_RZL_INF,LLNN_MEAN1_RZL_INF,LUNIFORM_RZL_INF,UNIFORM_OFFSET_RZL_INF,CMPERT_RZL_INF,CLIP_RZL_INF &
                &,LPERT_RSWINHF,LLNN_MEAN1_RSWINHF,LUNIFORM_RSWINHF,UNIFORM_OFFSET_RSWINHF,CMPERT_RSWINHF,CLIP_RSWINHF &
                &,LPERT_RLWINHF,LLNN_MEAN1_RLWINHF,LUNIFORM_RLWINHF,UNIFORM_OFFSET_RLWINHF,CMPERT_RLWINHF,CLIP_RLWINHF &
                &,LCORR_RZL_INF &
                &,ISIGNARO,IEZDIAG_POS,NPATFR &
                &,LSPG_SPP,SPGMU,SPGLAMBDA,SPGSIGMA,SPGQ,SPGADTMIN,SPGADTMAX
