!     ------------------------------------------------------------------
NAMELIST/NAMVAR/ &
! logical:
            &LTEST,LZOWA,&
            &LJC,LJCDFI,LUSEJCDFI,&
            &LGRASCAL,LWRIBVEC,LWRIBVEC_FULL,LREABVEC,LWRIEVEC,LWRISIGB,LWRISIGA,&
            &LWRISIGF,LEVECCNTL,LEVECGRIB,&
            &L_CHECK_CONVERGENCE,LBGTRUNC,LBGOBS,LBGM,LANOBS,&
            &LAVCGL, LMPCGL, LINITCV, LENSCV, LTOVSCV, LTOVSREP, LSLADREP, LGCV,&
            &LWREINI, LN1CG1, LCONGRAD, L3DFGAT, LVECADIN, &
            &LAMV_REASSIGN_PASSIVE, LSKIPMIN, LREPRO4DVAR,LREO3_BCOR,LCH4_BCOR, &
            &LAEOLUSAMD, L_ABS_CONVERGENCE, L_INFO_CONVERGENCE, &
            &L_GUESS_RUNTIME, &
            &L_INFO_CONTENT,LMODERR, LSTATMERR, LVARBC, LPERTMRPAS, &
            &LPROPTL, LCLDSINK, L_CHECK_GRADIENT,LBGPERT,&
            &LBACKGE, LBACKGECV,LBACKGERENORM,LUSEWAVRENORM,LCONSTANTZFCE, &
            &LWRISB_VPROF, &
            &LJBIMPACT, LJCIMPACT, LFCOBS, LFCOBSTEST, LREFINC, LENDA, LMONITOR_FCDEPAR, &
            &LTOY42, LSUSPQLIM, LSPINT, LDIAG_LCT, LFAMEMBERS, &
            &LJBZERO, LJPZERO, LJHZERO, LJLZERO, LJTZERO, &
            &LCHRESINCR, LINC_TOVSCV, LUSE_EDA_SKT, LACV, L_FGNOTBG, LWRICV, &
! integer:
            &NBGTRUNC, NITER ,NITER_MIN, NSIMU ,NINFRA,NMIMP,NFRREF, NREFTS,&
            &NFRANA,NANATS,NFRGRA,NGRATS,&
            &NUPTRA, MUPTRA, NPCVECS, NBGVECS, NFGFCLEN, NWRIEVEC,&
            &NSAVEEV, NSAVEPC, NITERGCV, N1IMP, NPRECO, NSELECT,&
            &N_INFO_CONTENT_METHOD, N_INFO_CONTENT_SEED,&
            &N_DIAGS_CONVERGENCE, N_DIAGS_EIGENVECS,N_COUPLED_WINDOWS,DATE_TIME_WINDOW_END,&
            &NITER_GUESS_RUNTIME, NFREQ_GUESS_RUNTIME, NMEM_GUESS_RUNTIME, NUPTRA_RANGE,&
! real:
            &RCVGE, RDX, ALPHAG, ALPHAV, RXMIN,  &
            &R_NORM_REDUCTION_ABORT_LEVEL, R_MAX_CNUM_PC,&
            &ZEPSNEG, RTOL_CHECK_GRADIENT, FILTERFACTOR, FILTEREXPO, DELTA, &
            &FILTERRESOL, CTOPBGE , CAMTBGE , &
! character:
            &CFNSIGB, CFNSIGA, CFNSIGF, CFNPCV

!     ------------------------------------------------------------------
