NAMELIST/NAMXFU/   LXFU     ,NFRXFU  ,NXFUTS ,NFRRAZ ,NRAZTS ,N1RAZ   &
 &,LXTRD  ,LXTRC  ,LXTRT    ,LXPLC   ,LXPLCG ,LXPLCH ,LXPLS  ,LXPLSG  &
 &,LXPLSH ,LXR    ,LXNEBTT  ,LXNEBPA ,LXCLS  ,LXTTCLS,LXHHCLS,LXQCLS  &
 &,LXSOIL ,LTXTRD ,LTXTRC   ,LTXTRT  ,LTXR   ,LTXNEB ,LTXQICE,LTXQLI  &
 &,LXICV  ,LXCLP  ,LXTGST   ,LXXGST  ,LXXGST2,LXTHW  ,LXXDIAGH,LXMWINDCLS     &
 &,LXNUVCLS,MEANPERIOD,NXGSTPERIOD,NXGSTPERIOD2,LXVEIN,LXMRT,LXCTOP &
 &,LXVISI, LXVISI2,NVISIPERIOD,NVISIPERIOD2,LXTPWCLS,LXPRECIPS1, LXPRECIPS2
