MODULE ARRAY_FIELD_WRAPPER_MOD



USE FIELD_MODULE
USE FIELD_REGISTRY_MOD

IMPLICIT NONE


TYPE ARRAY_2D
  TYPE (FIELD_2D), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_ARRAY_2D
  PROCEDURE :: FINAL => FINAL_ARRAY_2D
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_ARRAY_2D
END TYPE

TYPE ARRAY_3D
  TYPE (FIELD_3D), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_ARRAY_3D
  PROCEDURE :: FINAL => FINAL_ARRAY_3D
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_ARRAY_3D
END TYPE

TYPE ARRAY_4D
  TYPE (FIELD_4D), POINTER :: F_P => NULL ()
  REAL(KIND=JPRB), POINTER :: P (:,:,:) => NULL()
CONTAINS
  PROCEDURE :: INIT => INIT_ARRAY_4D
  PROCEDURE :: FINAL => FINAL_ARRAY_4D
  PROCEDURE :: UPDATE_VIEW => UPDATE_VIEW_ARRAY_4D
END TYPE


CONTAINS

SUBROUTINE INIT_ARRAY_2D (SELF, P, LBOUNDS)

CLASS (ARRAY_2D) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

SELF%F_P => CREATE_FIELD_WRAP (P, PERSISTENT=.TRUE., LBOUNDS=LBOUNDS)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_ARRAY_2D (SELF, BLOCK_INDEX)
CLASS (ARRAY_2D) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_P)) THEN
  SELF%P => SELF%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

END SUBROUTINE

SUBROUTINE FINAL_ARRAY_2D (SELF)
CLASS (ARRAY_2D) :: SELF

IF (ASSOCIATED (SELF%F_P)) THEN
  CALL DELETE_TEMPORARY (SELF%F_P)
  SELF%F_P => NULL ()
  SELF%P => NULL ()
ENDIF

END SUBROUTINE

SUBROUTINE INIT_ARRAY_3D (SELF, P, LBOUNDS)

CLASS (ARRAY_3D) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (3)

SELF%F_P => CREATE_FIELD_WRAP (P, PERSISTENT=.TRUE., LBOUNDS=LBOUNDS)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_ARRAY_3D (SELF, BLOCK_INDEX)
CLASS (ARRAY_3D) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_P)) THEN
  SELF%P => SELF%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

END SUBROUTINE

SUBROUTINE FINAL_ARRAY_3D (SELF)
CLASS (ARRAY_3D) :: SELF

IF (ASSOCIATED (SELF%F_P)) THEN
  CALL DELETE_TEMPORARY (SELF%F_P)
  SELF%F_P => NULL ()
  SELF%P => NULL ()
ENDIF

END SUBROUTINE

SUBROUTINE INIT_ARRAY_4D (SELF, P, LBOUNDS)

CLASS (ARRAY_4D) :: SELF
REAL(KIND=JPRB), INTENT (IN), TARGET :: P (:,:,:,:)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (4)

SELF%F_P => CREATE_FIELD_WRAP (P, PERSISTENT=.TRUE., LBOUNDS=LBOUNDS)

END SUBROUTINE

SUBROUTINE UPDATE_VIEW_ARRAY_4D (SELF, BLOCK_INDEX)
CLASS (ARRAY_4D) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_P)) THEN
  SELF%P => SELF%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

END SUBROUTINE

SUBROUTINE FINAL_ARRAY_4D (SELF)
CLASS (ARRAY_4D) :: SELF

IF (ASSOCIATED (SELF%F_P)) THEN
  CALL DELETE_TEMPORARY (SELF%F_P)
  SELF%F_P => NULL ()
  SELF%P => NULL ()
ENDIF

END SUBROUTINE


END MODULE
