MODULE YOMCFU_TYPE

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK

USE TYPE_FLUXES, ONLY : FLUXES_DESCRIPTOR
USE PTRGFU, ONLY : TCFUPTR
USE FIELD_MODULE
USE FIELD_REGISTRY_MOD

IMPLICIT NONE

SAVE


!     ------------------------------------------------------------

!*    Contains variables to control activation of cumulated fluxes.

INTEGER(KIND=JPIM), PARAMETER :: JPFUST=40    ! maximum number of timesteps where CFU can be activated

TYPE :: TCFU_KEYS

LOGICAL :: LCUMFU  = .FALSE.                  ! controls switch on/off all CFU
LOGICAL :: LSTRD   = .FALSE.                  ! activates gravity wave drag momentum CFU if .T.
LOGICAL :: LSTRC   = .FALSE.                  ! activates contribution of convection to U, V, q and (cp T) CFU if .T.
LOGICAL :: LSTRT   = .FALSE.                  ! activates contribution of turbulence to U, V, q and (cp T) CFU if .T.
LOGICAL :: LFPLC   = .FALSE.                  ! activates convective precipitation CFU if .T.
LOGICAL :: LFPLCG  = .FALSE.                  ! activates convective graupels CFU if .T.
LOGICAL :: LFPLCH  = .FALSE.                  ! activates convective hail CFU if .T.
LOGICAL :: LFPLS   = .FALSE.                  ! activates stratiform precipitation CFU if .T.
LOGICAL :: LFPLSG  = .FALSE.                  ! activates stratiform graupels CFU if .T.
LOGICAL :: LFPLSH  = .FALSE.                  ! activates stratiform hail CFU if .T.
LOGICAL :: LFR     = .FALSE.                  ! activates radiation CFU if .T.
LOGICAL :: LAMIP   = .FALSE.                  ! activates AMIP output if .T.
LOGICAL :: LRAYS   = .FALSE.                  ! activates more radiative CFU if .T.
LOGICAL :: LRAYD   = .FALSE.                  ! activates downwards surface radiative CFU if .T.
LOGICAL :: LNEBTT  = .FALSE.                  ! activates total cloudiness CFU if .T.
LOGICAL :: LFSF    = .FALSE.                  ! activates surface CFU if .T.
LOGICAL :: LFSOIL  = .FALSE.                  ! activates soil CFU if .T.
LOGICAL :: LNEBPAR = .FALSE.                  ! activates partial cloudiness CFU if .T.
LOGICAL :: LTSTRD  = .FALSE.                  ! activates gravity wave drag momentum CFU at all levels if .T.
LOGICAL :: LTSTRC  = .FALSE.                  ! activates contribution of convection to U, V, q and (cp T) CFU at all levels if .T.
LOGICAL :: LTSTRT  = .FALSE.                  ! activates contribution of turbulence to U, V, q and (cp T) CFU at all levels if .T.
LOGICAL :: LTFPLC  = .FALSE.                  ! activates convective precipitation CFU at all levels if .T.
LOGICAL :: LTFPLS  = .FALSE.                  ! activates stratiform precipitation CFU at all levels if .T.
LOGICAL :: LTFR    = .FALSE.                  ! activates radiation CFU at all levels if .T.
LOGICAL :: LTNEB   = .FALSE.                  ! activates cloudiness CFU at all levels if .T.
LOGICAL :: LFDUTP  = .FALSE.                  ! activates filtered duration of total precipitations CFU if .T.
LOGICAL :: LMOON   = .FALSE.                  ! activates moon radiation CFU if .T.
LOGICAL :: LFRRC   = .FALSE.                  ! activates clear sky radiation calculation if .T.
LOGICAL :: LFLASH  = .FALSE.                  ! activates diagnostics of lightning

END TYPE TCFU_KEYS

TYPE, EXTENDS(TCFU_KEYS) :: TCFU

INTEGER(KIND=JPIM) :: NCFUTS(0:JPFUST)        ! array containing flux accumulation write-up steps
INTEGER(KIND=JPIM) :: NFRRC                   ! frequency for clear sky radiation calculation
INTEGER(KIND=JPIM) :: NFRCFU                  ! frequency of write up of flux diagnostics
INTEGER(KIND=JPIM) :: NFDCFU                  ! total number of fields in buffer
INTEGER(KIND=JPIM) :: NTYPCFU                 ! number of fluxes types in buffer
INTEGER(KIND=JPIM) :: NMTFLASH                ! method used to compute lightening density
REAL(KIND=JPRB) :: CALFLASH1,CALFLASH2        ! calibration factor for lightening density


LOGICAL :: LREACFU = .FALSE.                  ! read first input on historic file if .T.

TYPE(FLUXES_DESCRIPTOR), ALLOCATABLE :: TYPE_CFU(:)  ! contains the fluxes descriptor for the CFU

TYPE(TCFUPTR) :: YCFUPT

REAL (KIND=JPRB), POINTER :: CFUBUF_B (:,:,:)   => NULL () ! Buffer for cumulative diagnostics

! liquid condensation due to convection
REAL (KIND=JPRB), POINTER :: FCCQL (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FCCQL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCCQL

! solid condensation due to convection
REAL (KIND=JPRB), POINTER :: FCCQN (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FCCQN => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCCQN

! heat in soil
REAL (KIND=JPRB), POINTER :: FCHSP (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FCHSP => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCHSP

! latent heat
REAL (KIND=JPRB), POINTER :: FCL (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FCL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCL

! liquid latent heat
REAL (KIND=JPRB), POINTER :: FCLL (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FCLL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCLL

! solid latent heat
REAL (KIND=JPRB), POINTER :: FCLN (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FCLN => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCLN

! large scale liquid condensation
REAL (KIND=JPRB), POINTER :: FCSQL (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FCSQL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCSQL

! large scale solid condensation
REAL (KIND=JPRB), POINTER :: FCSQN (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FCSQN => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCSQN

! sensible heat
REAL (KIND=JPRB), POINTER :: FCS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FCS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFCS

! contribution of convection to q
REAL (KIND=JPRB), POINTER :: FDICQ (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FDICQ => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFDICQ

! contribution of convection to (cp T)
REAL (KIND=JPRB), POINTER :: FDICS (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FDICS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFDICS

! surface enthalpy (due to the dissipation of kinetic energy)
REAL (KIND=JPRB), POINTER :: FDISH (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FDISH => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFDISH

! contribution of turbulence to T
REAL (KIND=JPRB), POINTER :: FDITQ (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FDITQ => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFDITQ

! contribution of turbulence to (cp T)
REAL (KIND=JPRB), POINTER :: FDITS (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FDITS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFDITS

! filtered duration of total precipitations
REAL (KIND=JPRB), POINTER :: FDUTP (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FDUTP => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFDUTP

! liquid evaporation
REAL (KIND=JPRB), POINTER :: FEVL (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FEVL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFEVL

! snow evaporation
REAL (KIND=JPRB), POINTER :: FEVN (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FEVN => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFEVN

! evapotranspiration
REAL (KIND=JPRB), POINTER :: FEVV (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FEVV => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFEVV

! deep frost
REAL (KIND=JPRB), POINTER :: FGEL (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FGEL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFGEL

! surface frost
REAL (KIND=JPRB), POINTER :: FGELS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FGELS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFGELS

! cumulative lighntning diagnotics
REAL (KIND=JPRB), POINTER :: FLASH (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FLASH => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFLASH

! water in soil
REAL (KIND=JPRB), POINTER :: FLWSP (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FLWSP => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFLWSP

! cloud cover
REAL (KIND=JPRB), POINTER :: FNEB (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FNEB => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFNEB

! total cloudiness
REAL (KIND=JPRB), POINTER :: FNEBT (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FNEBT => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFNEBT

! melt snow
REAL (KIND=JPRB), POINTER :: FONTE (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FONTE => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFONTE

! convective graupel fall
REAL (KIND=JPRB), POINTER :: FPLCG (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLCG => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLCG

! convective hail fall
REAL (KIND=JPRB), POINTER :: FPLCH (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLCH => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLCH

! convective precipitation
REAL (KIND=JPRB), POINTER :: FPLCL (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLCL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLCL

! convective snow fall
REAL (KIND=JPRB), POINTER :: FPLCN (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLCN => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLCN

! large scale graupel fall (stratiform)
REAL (KIND=JPRB), POINTER :: FPLSG (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLSG => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLSG

! large scale hail fall (stratiform)
REAL (KIND=JPRB), POINTER :: FPLSH (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLSH => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLSH

! large scale precipitation (stratiform)
REAL (KIND=JPRB), POINTER :: FPLSL (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLSL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLSL

! large scale snow fall (stratiform)
REAL (KIND=JPRB), POINTER :: FPLSN (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FPLSN => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFPLSN

! surface direct normal irradiance
REAL (KIND=JPRB), POINTER :: FRSDNI (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSDNI => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSDNI

! surface global normal irradiance
REAL (KIND=JPRB), POINTER :: FRSGNI (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSGNI => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSGNI

! top clear sky shortwave radiative
REAL (KIND=JPRB), POINTER :: FRSOC0 (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSOC0 => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSOC0

! surface clear sky shortwave radiative
REAL (KIND=JPRB), POINTER :: FRSOC1 (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSOC1 => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSOC1

! surface down solar
REAL (KIND=JPRB), POINTER :: FRSODS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSODS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSODS

! surface downward moon radiation
REAL (KIND=JPRB), POINTER :: FRSOLU (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSOLU => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSOLU

! surface parallel solar
REAL (KIND=JPRB), POINTER :: FRSOPS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSOPS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSOPS

! top parallel solar
REAL (KIND=JPRB), POINTER :: FRSOPT (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRSOPT => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSOPT

! solar radiation
REAL (KIND=JPRB), POINTER :: FRSO (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FRSO => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRSO

! top clear sky longwave radiative
REAL (KIND=JPRB), POINTER :: FRTHC0 (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRTHC0 => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRTHC0

! surface clear sky longwave radiative
REAL (KIND=JPRB), POINTER :: FRTHC1 (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRTHC1 => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRTHC1

! surface down thermic
REAL (KIND=JPRB), POINTER :: FRTHDS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FRTHDS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRTHDS

! surface radiation
REAL (KIND=JPRB), POINTER :: FRTH (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_FRTH => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFRTH

! top mesospheric enthalpy (+ dissipation)
REAL (KIND=JPRB), POINTER :: FTOPH (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FTOPH => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFTOPH

! transpiration
REAL (KIND=JPRB), POINTER :: FTR (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_FTR => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YFTR

! low cloud cover
REAL (KIND=JPRB), POINTER :: NEBBAS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_NEBBAS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YNEBBAS

! convective cloud cover
REAL (KIND=JPRB), POINTER :: NEBCON (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_NEBCON => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YNEBCON

! high cloud cover
REAL (KIND=JPRB), POINTER :: NEBHAU (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_NEBHAU => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YNEBHAU

! medium cloud cover
REAL (KIND=JPRB), POINTER :: NEBMOY (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_NEBMOY => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YNEBMOY

! total ozone
REAL (KIND=JPRB), POINTER :: OZONT (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_OZONT => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YOZONT

! solid specific moisture
REAL (KIND=JPRB), POINTER :: QICE (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_QICE => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YQICE

! liquid specific moisture
REAL (KIND=JPRB), POINTER :: QLI (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_QLI => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YQLI

! total precipitable water
REAL (KIND=JPRB), POINTER :: QTOT (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_QTOT => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YQTOT

! interception soil layer runoff
REAL (KIND=JPRB), POINTER :: RUISL (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_RUISL => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YRUISL

! deep soil runoff
REAL (KIND=JPRB), POINTER :: RUISP (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_RUISP => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YRUISP

! surface soil runoff
REAL (KIND=JPRB), POINTER :: RUISS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_RUISS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YRUISS

! snow mass
REAL (KIND=JPRB), POINTER :: SNS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_SNS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSNS

! surface pressure
REAL (KIND=JPRB), POINTER :: SPRES (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_SPRES => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSPRES

! contribution of convection to U
REAL (KIND=JPRB), POINTER :: STRCU (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_STRCU => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSTRCU

! contribution of convection to V
REAL (KIND=JPRB), POINTER :: STRCV (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_STRCV => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSTRCV

! U-wind gravity wave stress
REAL (KIND=JPRB), POINTER :: STRDU (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_STRDU => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSTRDU

! V-wind gravity wave stress
REAL (KIND=JPRB), POINTER :: STRDV (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_STRDV => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSTRDV

! contribution of turbulence to U
REAL (KIND=JPRB), POINTER :: STRTU (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_STRTU => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSTRTU

! contribution of turbulence to V
REAL (KIND=JPRB), POINTER :: STRTV (:,:) => NULL ()
TYPE (FIELD_3D), POINTER :: F_STRTV => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YSTRTV

! soil moisture
REAL (KIND=JPRB), POINTER :: WS (:) => NULL ()
TYPE (FIELD_2D), POINTER :: F_WS => NULL ()
TYPE (FLUXES_DESCRIPTOR) :: YWS


CONTAINS
  PROCEDURE :: INIT => TCFU_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => TCFU_TYPE_UPDATE_VIEW
  PROCEDURE :: FINAL => TCFU_TYPE_FINAL
END TYPE TCFU

CONTAINS

SUBROUTINE TCFU_TYPE_INIT (SELF)

CLASS (TCFU), INTENT (INOUT) :: SELF

INTEGER (KIND=JPIM) :: ILEV, IOFF

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TCFU_TYPE_INIT', 0, ZHOOK_HANDLE)

IOFF = SELF%YCFUPT%MFCCQL
IF (IOFF > 0) THEN
  ILEV = SELF%YFCCQL%ILEV
  SELF%F_FCCQL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCCQN
IF (IOFF > 0) THEN
  ILEV = SELF%YFCCQN%ILEV
  SELF%F_FCCQN => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCHSP
IF (IOFF > 0) THEN
  SELF%F_FCHSP => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCL
IF (IOFF > 0) THEN
  SELF%F_FCL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCLL
IF (IOFF > 0) THEN
  SELF%F_FCLL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCLN
IF (IOFF > 0) THEN
  SELF%F_FCLN => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCSQL
IF (IOFF > 0) THEN
  ILEV = SELF%YFCSQL%ILEV
  SELF%F_FCSQL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCSQN
IF (IOFF > 0) THEN
  ILEV = SELF%YFCSQN%ILEV
  SELF%F_FCSQN => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFCS
IF (IOFF > 0) THEN
  SELF%F_FCS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFDICQ
IF (IOFF > 0) THEN
  ILEV = SELF%YFDICQ%ILEV
  SELF%F_FDICQ => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFDICS
IF (IOFF > 0) THEN
  ILEV = SELF%YFDICS%ILEV
  SELF%F_FDICS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFDISH
IF (IOFF > 0) THEN
  SELF%F_FDISH => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFDITQ
IF (IOFF > 0) THEN
  ILEV = SELF%YFDITQ%ILEV
  SELF%F_FDITQ => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFDITS
IF (IOFF > 0) THEN
  ILEV = SELF%YFDITS%ILEV
  SELF%F_FDITS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFDUTP
IF (IOFF > 0) THEN
  SELF%F_FDUTP => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFEVL
IF (IOFF > 0) THEN
  SELF%F_FEVL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFEVN
IF (IOFF > 0) THEN
  SELF%F_FEVN => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFEVV
IF (IOFF > 0) THEN
  SELF%F_FEVV => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFGEL
IF (IOFF > 0) THEN
  SELF%F_FGEL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFGELS
IF (IOFF > 0) THEN
  SELF%F_FGELS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFLASH
IF (IOFF > 0) THEN
  SELF%F_FLASH => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFLWSP
IF (IOFF > 0) THEN
  SELF%F_FLWSP => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFNEB
IF (IOFF > 0) THEN
  ILEV = SELF%YFNEB%ILEV
  SELF%F_FNEB => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFNEBT
IF (IOFF > 0) THEN
  SELF%F_FNEBT => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFONTE
IF (IOFF > 0) THEN
  SELF%F_FONTE => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLCG
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLCG%ILEV
  SELF%F_FPLCG => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLCH
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLCH%ILEV
  SELF%F_FPLCH => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLCL
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLCL%ILEV
  SELF%F_FPLCL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLCN
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLCN%ILEV
  SELF%F_FPLCN => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLSG
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLSG%ILEV
  SELF%F_FPLSG => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLSH
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLSH%ILEV
  SELF%F_FPLSH => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLSL
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLSL%ILEV
  SELF%F_FPLSL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFPLSN
IF (IOFF > 0) THEN
  ILEV = SELF%YFPLSN%ILEV
  SELF%F_FPLSN => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSDNI
IF (IOFF > 0) THEN
  SELF%F_FRSDNI => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSGNI
IF (IOFF > 0) THEN
  SELF%F_FRSGNI => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSOC0
IF (IOFF > 0) THEN
  SELF%F_FRSOC0 => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSOC1
IF (IOFF > 0) THEN
  SELF%F_FRSOC1 => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSODS
IF (IOFF > 0) THEN
  SELF%F_FRSODS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSOLU
IF (IOFF > 0) THEN
  SELF%F_FRSOLU => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSOPS
IF (IOFF > 0) THEN
  SELF%F_FRSOPS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSOPT
IF (IOFF > 0) THEN
  SELF%F_FRSOPT => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRSO
IF (IOFF > 0) THEN
  ILEV = SELF%YFRSO%ILEV
  SELF%F_FRSO => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRTHC0
IF (IOFF > 0) THEN
  SELF%F_FRTHC0 => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRTHC1
IF (IOFF > 0) THEN
  SELF%F_FRTHC1 => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRTHDS
IF (IOFF > 0) THEN
  SELF%F_FRTHDS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFRTH
IF (IOFF > 0) THEN
  ILEV = SELF%YFRTH%ILEV
  SELF%F_FRTH => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFTOPH
IF (IOFF > 0) THEN
  SELF%F_FTOPH => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MFTR
IF (IOFF > 0) THEN
  SELF%F_FTR => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MNEBBAS
IF (IOFF > 0) THEN
  SELF%F_NEBBAS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MNEBCON
IF (IOFF > 0) THEN
  SELF%F_NEBCON => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MNEBHAU
IF (IOFF > 0) THEN
  SELF%F_NEBHAU => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MNEBMOY
IF (IOFF > 0) THEN
  SELF%F_NEBMOY => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MOZONT
IF (IOFF > 0) THEN
  SELF%F_OZONT => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MQICE
IF (IOFF > 0) THEN
  SELF%F_QICE => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MQLI
IF (IOFF > 0) THEN
  SELF%F_QLI => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MQTOT
IF (IOFF > 0) THEN
  SELF%F_QTOT => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MRUISL
IF (IOFF > 0) THEN
  SELF%F_RUISL => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MRUISP
IF (IOFF > 0) THEN
  SELF%F_RUISP => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MRUISS
IF (IOFF > 0) THEN
  SELF%F_RUISS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSNS
IF (IOFF > 0) THEN
  SELF%F_SNS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSPRES
IF (IOFF > 0) THEN
  SELF%F_SPRES => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSTRCU
IF (IOFF > 0) THEN
  ILEV = SELF%YSTRCU%ILEV
  SELF%F_STRCU => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSTRCV
IF (IOFF > 0) THEN
  ILEV = SELF%YSTRCV%ILEV
  SELF%F_STRCV => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSTRDU
IF (IOFF > 0) THEN
  ILEV = SELF%YSTRDU%ILEV
  SELF%F_STRDU => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSTRDV
IF (IOFF > 0) THEN
  ILEV = SELF%YSTRDV%ILEV
  SELF%F_STRDV => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSTRTU
IF (IOFF > 0) THEN
  ILEV = SELF%YSTRTU%ILEV
  SELF%F_STRTU => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MSTRTV
IF (IOFF > 0) THEN
  ILEV = SELF%YSTRTV%ILEV
  SELF%F_STRTV => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF:IOFF+ILEV-1, :), PERSISTENT=.TRUE.)
ENDIF

IOFF = SELF%YCFUPT%MWS
IF (IOFF > 0) THEN
  SELF%F_WS => CREATE_FIELD_WRAP (SELF%CFUBUF_B (:, IOFF, :), PERSISTENT=.TRUE.)
ENDIF


IF (LHOOK) CALL DR_HOOK('TCFU_TYPE_INIT', 1, ZHOOK_HANDLE)

END SUBROUTINE TCFU_TYPE_INIT

SUBROUTINE TCFU_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)

CLASS (TCFU), INTENT (INOUT) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: BLOCK_INDEX

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TCFU_TYPE_UPDATE_VIEW', 0, ZHOOK_HANDLE)

IF (ASSOCIATED (SELF%F_FCCQL)) THEN
  SELF%FCCQL => SELF%F_FCCQL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCCQN)) THEN
  SELF%FCCQN => SELF%F_FCCQN%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCHSP)) THEN
  SELF%FCHSP => SELF%F_FCHSP%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCL)) THEN
  SELF%FCL => SELF%F_FCL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCLL)) THEN
  SELF%FCLL => SELF%F_FCLL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCLN)) THEN
  SELF%FCLN => SELF%F_FCLN%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCSQL)) THEN
  SELF%FCSQL => SELF%F_FCSQL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCSQN)) THEN
  SELF%FCSQN => SELF%F_FCSQN%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FCS)) THEN
  SELF%FCS => SELF%F_FCS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FDICQ)) THEN
  SELF%FDICQ => SELF%F_FDICQ%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FDICS)) THEN
  SELF%FDICS => SELF%F_FDICS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FDISH)) THEN
  SELF%FDISH => SELF%F_FDISH%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FDITQ)) THEN
  SELF%FDITQ => SELF%F_FDITQ%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FDITS)) THEN
  SELF%FDITS => SELF%F_FDITS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FDUTP)) THEN
  SELF%FDUTP => SELF%F_FDUTP%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FEVL)) THEN
  SELF%FEVL => SELF%F_FEVL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FEVN)) THEN
  SELF%FEVN => SELF%F_FEVN%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FEVV)) THEN
  SELF%FEVV => SELF%F_FEVV%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FGEL)) THEN
  SELF%FGEL => SELF%F_FGEL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FGELS)) THEN
  SELF%FGELS => SELF%F_FGELS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FLASH)) THEN
  SELF%FLASH => SELF%F_FLASH%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FLWSP)) THEN
  SELF%FLWSP => SELF%F_FLWSP%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FNEB)) THEN
  SELF%FNEB => SELF%F_FNEB%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FNEBT)) THEN
  SELF%FNEBT => SELF%F_FNEBT%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FONTE)) THEN
  SELF%FONTE => SELF%F_FONTE%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLCG)) THEN
  SELF%FPLCG => SELF%F_FPLCG%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLCH)) THEN
  SELF%FPLCH => SELF%F_FPLCH%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLCL)) THEN
  SELF%FPLCL => SELF%F_FPLCL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLCN)) THEN
  SELF%FPLCN => SELF%F_FPLCN%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLSG)) THEN
  SELF%FPLSG => SELF%F_FPLSG%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLSH)) THEN
  SELF%FPLSH => SELF%F_FPLSH%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLSL)) THEN
  SELF%FPLSL => SELF%F_FPLSL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FPLSN)) THEN
  SELF%FPLSN => SELF%F_FPLSN%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSDNI)) THEN
  SELF%FRSDNI => SELF%F_FRSDNI%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSGNI)) THEN
  SELF%FRSGNI => SELF%F_FRSGNI%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSOC0)) THEN
  SELF%FRSOC0 => SELF%F_FRSOC0%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSOC1)) THEN
  SELF%FRSOC1 => SELF%F_FRSOC1%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSODS)) THEN
  SELF%FRSODS => SELF%F_FRSODS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSOLU)) THEN
  SELF%FRSOLU => SELF%F_FRSOLU%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSOPS)) THEN
  SELF%FRSOPS => SELF%F_FRSOPS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSOPT)) THEN
  SELF%FRSOPT => SELF%F_FRSOPT%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRSO)) THEN
  SELF%FRSO => SELF%F_FRSO%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRTHC0)) THEN
  SELF%FRTHC0 => SELF%F_FRTHC0%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRTHC1)) THEN
  SELF%FRTHC1 => SELF%F_FRTHC1%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRTHDS)) THEN
  SELF%FRTHDS => SELF%F_FRTHDS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FRTH)) THEN
  SELF%FRTH => SELF%F_FRTH%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FTOPH)) THEN
  SELF%FTOPH => SELF%F_FTOPH%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_FTR)) THEN
  SELF%FTR => SELF%F_FTR%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_NEBBAS)) THEN
  SELF%NEBBAS => SELF%F_NEBBAS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_NEBCON)) THEN
  SELF%NEBCON => SELF%F_NEBCON%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_NEBHAU)) THEN
  SELF%NEBHAU => SELF%F_NEBHAU%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_NEBMOY)) THEN
  SELF%NEBMOY => SELF%F_NEBMOY%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_OZONT)) THEN
  SELF%OZONT => SELF%F_OZONT%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_QICE)) THEN
  SELF%QICE => SELF%F_QICE%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_QLI)) THEN
  SELF%QLI => SELF%F_QLI%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_QTOT)) THEN
  SELF%QTOT => SELF%F_QTOT%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_RUISL)) THEN
  SELF%RUISL => SELF%F_RUISL%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_RUISP)) THEN
  SELF%RUISP => SELF%F_RUISP%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_RUISS)) THEN
  SELF%RUISS => SELF%F_RUISS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_SNS)) THEN
  SELF%SNS => SELF%F_SNS%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_SPRES)) THEN
  SELF%SPRES => SELF%F_SPRES%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_STRCU)) THEN
  SELF%STRCU => SELF%F_STRCU%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_STRCV)) THEN
  SELF%STRCV => SELF%F_STRCV%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_STRDU)) THEN
  SELF%STRDU => SELF%F_STRDU%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_STRDV)) THEN
  SELF%STRDV => SELF%F_STRDV%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_STRTU)) THEN
  SELF%STRTU => SELF%F_STRTU%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_STRTV)) THEN
  SELF%STRTV => SELF%F_STRTV%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_WS)) THEN
  SELF%WS => SELF%F_WS%GET_VIEW (BLOCK_INDEX)
ENDIF


IF (LHOOK) CALL DR_HOOK('TCFU_TYPE_UPDATE_VIEW', 1, ZHOOK_HANDLE)

END SUBROUTINE TCFU_TYPE_UPDATE_VIEW

SUBROUTINE TCFU_TYPE_FINAL (SELF)

CLASS (TCFU), INTENT (INOUT) :: SELF

REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TCFU_TYPE_FINAL', 0, ZHOOK_HANDLE)

IF (ASSOCIATED (SELF%F_FCCQL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCCQL)
  SELF%F_FCCQL => NULL () 
  SELF%FCCQL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCCQN)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCCQN)
  SELF%F_FCCQN => NULL () 
  SELF%FCCQN => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCHSP)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCHSP)
  SELF%F_FCHSP => NULL () 
  SELF%FCHSP => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCL)
  SELF%F_FCL => NULL () 
  SELF%FCL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCLL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCLL)
  SELF%F_FCLL => NULL () 
  SELF%FCLL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCLN)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCLN)
  SELF%F_FCLN => NULL () 
  SELF%FCLN => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCSQL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCSQL)
  SELF%F_FCSQL => NULL () 
  SELF%FCSQL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCSQN)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCSQN)
  SELF%F_FCSQN => NULL () 
  SELF%FCSQN => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FCS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FCS)
  SELF%F_FCS => NULL () 
  SELF%FCS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FDICQ)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FDICQ)
  SELF%F_FDICQ => NULL () 
  SELF%FDICQ => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FDICS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FDICS)
  SELF%F_FDICS => NULL () 
  SELF%FDICS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FDISH)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FDISH)
  SELF%F_FDISH => NULL () 
  SELF%FDISH => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FDITQ)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FDITQ)
  SELF%F_FDITQ => NULL () 
  SELF%FDITQ => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FDITS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FDITS)
  SELF%F_FDITS => NULL () 
  SELF%FDITS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FDUTP)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FDUTP)
  SELF%F_FDUTP => NULL () 
  SELF%FDUTP => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FEVL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FEVL)
  SELF%F_FEVL => NULL () 
  SELF%FEVL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FEVN)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FEVN)
  SELF%F_FEVN => NULL () 
  SELF%FEVN => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FEVV)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FEVV)
  SELF%F_FEVV => NULL () 
  SELF%FEVV => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FGEL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FGEL)
  SELF%F_FGEL => NULL () 
  SELF%FGEL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FGELS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FGELS)
  SELF%F_FGELS => NULL () 
  SELF%FGELS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FLASH)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FLASH)
  SELF%F_FLASH => NULL () 
  SELF%FLASH => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FLWSP)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FLWSP)
  SELF%F_FLWSP => NULL () 
  SELF%FLWSP => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FNEB)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FNEB)
  SELF%F_FNEB => NULL () 
  SELF%FNEB => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FNEBT)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FNEBT)
  SELF%F_FNEBT => NULL () 
  SELF%FNEBT => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FONTE)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FONTE)
  SELF%F_FONTE => NULL () 
  SELF%FONTE => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLCG)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLCG)
  SELF%F_FPLCG => NULL () 
  SELF%FPLCG => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLCH)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLCH)
  SELF%F_FPLCH => NULL () 
  SELF%FPLCH => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLCL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLCL)
  SELF%F_FPLCL => NULL () 
  SELF%FPLCL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLCN)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLCN)
  SELF%F_FPLCN => NULL () 
  SELF%FPLCN => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLSG)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLSG)
  SELF%F_FPLSG => NULL () 
  SELF%FPLSG => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLSH)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLSH)
  SELF%F_FPLSH => NULL () 
  SELF%FPLSH => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLSL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLSL)
  SELF%F_FPLSL => NULL () 
  SELF%FPLSL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FPLSN)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FPLSN)
  SELF%F_FPLSN => NULL () 
  SELF%FPLSN => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSDNI)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSDNI)
  SELF%F_FRSDNI => NULL () 
  SELF%FRSDNI => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSGNI)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSGNI)
  SELF%F_FRSGNI => NULL () 
  SELF%FRSGNI => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSOC0)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSOC0)
  SELF%F_FRSOC0 => NULL () 
  SELF%FRSOC0 => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSOC1)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSOC1)
  SELF%F_FRSOC1 => NULL () 
  SELF%FRSOC1 => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSODS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSODS)
  SELF%F_FRSODS => NULL () 
  SELF%FRSODS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSOLU)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSOLU)
  SELF%F_FRSOLU => NULL () 
  SELF%FRSOLU => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSOPS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSOPS)
  SELF%F_FRSOPS => NULL () 
  SELF%FRSOPS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSOPT)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSOPT)
  SELF%F_FRSOPT => NULL () 
  SELF%FRSOPT => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRSO)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRSO)
  SELF%F_FRSO => NULL () 
  SELF%FRSO => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRTHC0)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRTHC0)
  SELF%F_FRTHC0 => NULL () 
  SELF%FRTHC0 => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRTHC1)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRTHC1)
  SELF%F_FRTHC1 => NULL () 
  SELF%FRTHC1 => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRTHDS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRTHDS)
  SELF%F_FRTHDS => NULL () 
  SELF%FRTHDS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FRTH)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FRTH)
  SELF%F_FRTH => NULL () 
  SELF%FRTH => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FTOPH)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FTOPH)
  SELF%F_FTOPH => NULL () 
  SELF%FTOPH => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_FTR)) THEN
  CALL DELETE_TEMPORARY (SELF%F_FTR)
  SELF%F_FTR => NULL () 
  SELF%FTR => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_NEBBAS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_NEBBAS)
  SELF%F_NEBBAS => NULL () 
  SELF%NEBBAS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_NEBCON)) THEN
  CALL DELETE_TEMPORARY (SELF%F_NEBCON)
  SELF%F_NEBCON => NULL () 
  SELF%NEBCON => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_NEBHAU)) THEN
  CALL DELETE_TEMPORARY (SELF%F_NEBHAU)
  SELF%F_NEBHAU => NULL () 
  SELF%NEBHAU => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_NEBMOY)) THEN
  CALL DELETE_TEMPORARY (SELF%F_NEBMOY)
  SELF%F_NEBMOY => NULL () 
  SELF%NEBMOY => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_OZONT)) THEN
  CALL DELETE_TEMPORARY (SELF%F_OZONT)
  SELF%F_OZONT => NULL () 
  SELF%OZONT => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_QICE)) THEN
  CALL DELETE_TEMPORARY (SELF%F_QICE)
  SELF%F_QICE => NULL () 
  SELF%QICE => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_QLI)) THEN
  CALL DELETE_TEMPORARY (SELF%F_QLI)
  SELF%F_QLI => NULL () 
  SELF%QLI => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_QTOT)) THEN
  CALL DELETE_TEMPORARY (SELF%F_QTOT)
  SELF%F_QTOT => NULL () 
  SELF%QTOT => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_RUISL)) THEN
  CALL DELETE_TEMPORARY (SELF%F_RUISL)
  SELF%F_RUISL => NULL () 
  SELF%RUISL => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_RUISP)) THEN
  CALL DELETE_TEMPORARY (SELF%F_RUISP)
  SELF%F_RUISP => NULL () 
  SELF%RUISP => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_RUISS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_RUISS)
  SELF%F_RUISS => NULL () 
  SELF%RUISS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_SNS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_SNS)
  SELF%F_SNS => NULL () 
  SELF%SNS => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_SPRES)) THEN
  CALL DELETE_TEMPORARY (SELF%F_SPRES)
  SELF%F_SPRES => NULL () 
  SELF%SPRES => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_STRCU)) THEN
  CALL DELETE_TEMPORARY (SELF%F_STRCU)
  SELF%F_STRCU => NULL () 
  SELF%STRCU => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_STRCV)) THEN
  CALL DELETE_TEMPORARY (SELF%F_STRCV)
  SELF%F_STRCV => NULL () 
  SELF%STRCV => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_STRDU)) THEN
  CALL DELETE_TEMPORARY (SELF%F_STRDU)
  SELF%F_STRDU => NULL () 
  SELF%STRDU => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_STRDV)) THEN
  CALL DELETE_TEMPORARY (SELF%F_STRDV)
  SELF%F_STRDV => NULL () 
  SELF%STRDV => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_STRTU)) THEN
  CALL DELETE_TEMPORARY (SELF%F_STRTU)
  SELF%F_STRTU => NULL () 
  SELF%STRTU => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_STRTV)) THEN
  CALL DELETE_TEMPORARY (SELF%F_STRTV)
  SELF%F_STRTV => NULL () 
  SELF%STRTV => NULL ()
ENDIF

IF (ASSOCIATED (SELF%F_WS)) THEN
  CALL DELETE_TEMPORARY (SELF%F_WS)
  SELF%F_WS => NULL () 
  SELF%WS => NULL ()
ENDIF


IF (LHOOK) CALL DR_HOOK('TCFU_TYPE_FINAL', 1, ZHOOK_HANDLE)

END SUBROUTINE TCFU_TYPE_FINAL

END MODULE YOMCFU_TYPE
