INTERFACE
 SUBROUTINE BLACKBOX( &
&     KOUT, KATEGORY, KPRINT, &
&     KTEST_MDI, KFILL_FBVECTOR, &
&     KCMBLI, ZCMCCC, &
&     KFEEDBACK, KFEEDBACK_SIZE, &
&     ZDATA, KDATA)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM), INTENT(IN)  :: KOUT, KATEGORY, KPRINT, KTEST_MDI, KFILL_FBVECTOR
INTEGER(KIND=JPIM), INTENT(OUT) :: KCMBLI
REAL(KIND=JPRB),    INTENT(OUT) :: ZCMCCC
INTEGER(KIND=JPIM), INTENT(IN)  :: KFEEDBACK_SIZE, KDATA
INTEGER(KIND=JPIM), INTENT(OUT) :: KFEEDBACK(0:KFEEDBACK_SIZE)
REAL(KIND=JPRB), INTENT(IN)     :: ZDATA(KDATA)
END SUBROUTINE BLACKBOX
END INTERFACE
