!depfile:close_file_asc.F90
MODULE MODI_CLOSE_FILE_ASC
INTERFACE
      SUBROUTINE CLOSE_FILE_ASC(HPROGRAM,KUNIT )
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KUNIT    ! logical unit of file
END SUBROUTINE CLOSE_FILE_ASC

END INTERFACE
END MODULE MODI_CLOSE_FILE_ASC
