!depfile:get_bld_confn.F90
MODULE MODI_GET_BLD_CONF_n 
INTERFACE
      SUBROUTINE GET_BLD_CONF_n (BDD, DTT, &
                                 ODATA_BLDTYPE, ODATA_BLD_AGE, ODATA_USETYPE, &
                KDESC_ROOF_LAYER, KDESC_ROAD_LAYER, KDESC_WALL_LAYER, &
                KDESC_FLOOR_LAYER, KDESC_CODE, KDESC_USE, KDESC_AGE, KDESC_BLD)  
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
TYPE(DATA_TEB_t), INTENT(INOUT) :: DTT
LOGICAL, INTENT(OUT) :: ODATA_BLDTYPE
LOGICAL, INTENT(OUT) :: ODATA_BLD_AGE
LOGICAL, INTENT(OUT) :: ODATA_USETYPE
INTEGER, INTENT(OUT) :: KDESC_ROOF_LAYER
INTEGER, INTENT(OUT) :: KDESC_ROAD_LAYER
INTEGER, INTENT(OUT) :: KDESC_WALL_LAYER
INTEGER, INTENT(OUT) :: KDESC_FLOOR_LAYER
INTEGER, INTENT(OUT) :: KDESC_CODE
INTEGER, INTENT(OUT) :: KDESC_USE
INTEGER, INTENT(OUT) :: KDESC_AGE
INTEGER, INTENT(OUT) :: KDESC_BLD
END SUBROUTINE GET_BLD_CONF_n

END INTERFACE
END MODULE MODI_GET_BLD_CONF_n 
