!depfile:open_file_ol.F90
MODULE MODI_OPEN_FILE_OL
INTERFACE
      SUBROUTINE OPEN_FILE_OL(KUNIT,HFILE,HFORM,HACTION,HACCESS,KRECL)
INTEGER,           INTENT(OUT):: KUNIT    ! logical unit
 CHARACTER(LEN=28), INTENT(IN) :: HFILE    ! file to open
 CHARACTER(LEN=11), INTENT(IN) :: HFORM    ! type of file
 CHARACTER(LEN=9),  INTENT(IN) :: HACTION  ! action
 CHARACTER(LEN=6),  INTENT(IN) :: HACCESS  ! access type
INTEGER,           INTENT(IN) :: KRECL    ! record length
END SUBROUTINE OPEN_FILE_OL

END INTERFACE
END MODULE MODI_OPEN_FILE_OL
