!depfile:uncompress_field.F90
MODULE MODI_UNCOMPRESS_FIELD
INTERFACE
SUBROUTINE UNCOMPRESS_FIELD(KLONG,PSEUIL,PFIELD_IN,PFIELD_OUT)
INTEGER*4, INTENT(IN) :: KLONG
REAL, INTENT(IN) :: PSEUIL
REAL, DIMENSION(:), INTENT(IN) :: PFIELD_IN
REAL, DIMENSION(:), INTENT(OUT) :: PFIELD_OUT
END SUBROUTINE UNCOMPRESS_FIELD

END INTERFACE
END MODULE MODI_UNCOMPRESS_FIELD
