!depfile:read_namelists_isban.F90
MODULE MODI_READ_NAMELISTS_ISBA_n 
INTERFACE
SUBROUTINE READ_NAMELISTS_ISBA_n (IM, HPROGRAM, HINIT)
USE MODD_SURFEX_n, ONLY : ISBA_MODEL_t
TYPE(ISBA_MODEL_t), INTENT(INOUT) :: IM
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HINIT     ! choice of fields to initialize
END SUBROUTINE READ_NAMELISTS_ISBA_n

END INTERFACE
END MODULE MODI_READ_NAMELISTS_ISBA_n 
