!depfile:writesurf_ch_emisn.F90
MODULE MODI_WRITESURF_CH_EMIS_n 
INTERFACE
      SUBROUTINE WRITESURF_CH_EMIS_n (HSELECT, CHE, HPROGRAM)
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE WRITESURF_CH_EMIS_n

END INTERFACE
END MODULE MODI_WRITESURF_CH_EMIS_n 
