!depfile:prep_sbl.F90
MODULE MODI_PREP_SBL 
INTERFACE
SUBROUTINE PREP_SBL (KDIM, SB)
USE MODD_CANOPY_n, ONLY : CANOPY_t
INTEGER, INTENT(IN) :: KDIM
TYPE(CANOPY_t), INTENT(INOUT) :: SB
END SUBROUTINE PREP_SBL

END INTERFACE
END MODULE MODI_PREP_SBL 
