!depfile:sst_update.F90
MODULE MODI_SST_UPDATE 
INTERFACE
    SUBROUTINE SST_UPDATE (DTS, S, PSST)
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
TYPE(DATA_SEAFLUX_t), INTENT(INOUT) :: DTS
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
REAL,   DIMENSION(:), INTENT(INOUT) :: PSST    ! sst
END SUBROUTINE SST_UPDATE

END INTERFACE
END MODULE MODI_SST_UPDATE 
