!depfile:update_data_cover.F90
MODULE MODI_UPDATE_DATA_COVER 
INTERFACE
      SUBROUTINE UPDATE_DATA_COVER (DTCO, DTV, KDIM, KPATCH, OMEB_PATCH, &
                                    KYEAR)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
INTEGER, INTENT(IN) :: KDIM
LOGICAL, DIMENSION(:), POINTER :: OMEB_PATCH
INTEGER, INTENT(IN) :: KPATCH
INTEGER,             INTENT(IN)    :: KYEAR        ! new year
END SUBROUTINE UPDATE_DATA_COVER

END INTERFACE
END MODULE MODI_UPDATE_DATA_COVER 
