!depfile:read_watflux_confn.F90
MODULE MODI_READ_WATFLUX_CONF_n 
INTERFACE
      SUBROUTINE READ_WATFLUX_CONF_n (CHW, DGO, W, HPROGRAM)
USE MODD_CH_WATFLUX_n, ONLY : CH_WATFLUX_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(CH_WATFLUX_t), INTENT(INOUT) :: CHW
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(WATFLUX_t), INTENT(INOUT) :: W
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling ISBA
END SUBROUTINE READ_WATFLUX_CONF_n

END INTERFACE
END MODULE MODI_READ_WATFLUX_CONF_n 
