!depfile:ch_emission_to_atmn.F90
MODULE MODI_CH_EMISSION_TO_ATM_n 
INTERFACE
      SUBROUTINE CH_EMISSION_TO_ATM_n (CHN, SV, &
                                       PSFSV,PRHOA)
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_TYPE_EFUTIL
TYPE(CH_EMIS_SNAP_t), INTENT(INOUT) :: CHN
TYPE(SV_t), INTENT(INOUT) :: SV
REAL,             DIMENSION(:,:),INTENT(INOUT):: PSFSV  ! flux of     atmospheric scalar var.   (Mol/m2/s)
REAL,             DIMENSION(:),  INTENT(IN)   :: PRHOA  ! Air density (kg/m3)
END SUBROUTINE CH_EMISSION_TO_ATM_n

END INTERFACE
END MODULE MODI_CH_EMISSION_TO_ATM_n 
