!depfile:local_slope_param.F90
MODULE MODI_LOCAL_SLOPE_PARAM
INTERFACE
SUBROUTINE LOCAL_SLOPE_PARAM(JPINDX1,JPINDX2)
INTEGER,INTENT(IN)::JPINDX1,JPINDX2
END SUBROUTINE LOCAL_SLOPE_PARAM

END INTERFACE
END MODULE MODI_LOCAL_SLOPE_PARAM
