!depfile:init_outfn_tebn.F90
MODULE MODI_INIT_OUTFN_TEB_n 
INTERFACE
       SUBROUTINE INIT_OUTFN_TEB_n (TM, GDM, GRM, UG, U, HSELECT, HPROGRAM, KLUOUT)
USE MODD_SURFEX_n, ONLY : TEB_MODEL_t, TEB_GARDEN_MODEL_t, TEB_GREENROOF_MODEL_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(TEB_MODEL_t), INTENT(IN) :: TM
TYPE(TEB_GARDEN_MODEL_t), INTENT(IN) :: GDM
TYPE(TEB_GREENROOF_MODEL_t), INTENT(IN) :: GRM
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM
INTEGER,           INTENT(IN) :: KLUOUT
END SUBROUTINE INIT_OUTFN_TEB_n

END INTERFACE
END MODULE MODI_INIT_OUTFN_TEB_n 
