!depfile:diag_misc_isban.F90
MODULE MODI_DIAG_MISC_ISBA_n 
INTERFACE
SUBROUTINE DIAG_MISC_ISBA_n (DMK, KK, PK, PEK, AGK, IO, OSURF_MISC_BUDGET, &
                             OVOLUMETRIC_SNOWLIQ, PTSTEP, OAGRIP, PTIME, KSIZE , PSLOPECOS )  
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_AGRI_n, ONLY : AGRI_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_TYPE_SNOW
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMK
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(AGRI_t), INTENT(INOUT) :: AGK
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
LOGICAL, INTENT(IN) :: OSURF_MISC_BUDGET
LOGICAL, INTENT(IN) :: OVOLUMETRIC_SNOWLIQ
REAL,               INTENT(IN)    :: PTSTEP        ! timestep for  accumulated values 
LOGICAL, INTENT(IN)               :: OAGRIP
REAL,    INTENT(IN)               :: PTIME   ! current time since midnight
INTEGER, INTENT(IN) :: KSIZE
REAL, DIMENSION(:),  INTENT(IN) :: PSLOPECOS ! cosine of the slope for Crocus
END SUBROUTINE DIAG_MISC_ISBA_n

END INTERFACE
END MODULE MODI_DIAG_MISC_ISBA_n 
