!depfile:read_ideal_flux_conf.F90
MODULE MODI_READ_IDEAL_FLUX_CONF
INTERFACE
      SUBROUTINE READ_IDEAL_FLUX_CONF(HPROGRAM)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling GROUND
END SUBROUTINE READ_IDEAL_FLUX_CONF

END INTERFACE
END MODULE MODI_READ_IDEAL_FLUX_CONF
