!depfile:prep_ver_isba.F90
MODULE MODI_PREP_VER_ISBA 
INTERFACE
SUBROUTINE PREP_VER_ISBA (IO, NPE, PZS, NP)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_NP_t, ISBA_NPE_t, ISBA_P_t, ISBA_PE_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_NPE_t), INTENT(INOUT) :: NPE
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
REAL, DIMENSION(:), INTENT(IN) :: PZS
END SUBROUTINE PREP_VER_ISBA

END INTERFACE
END MODULE MODI_PREP_VER_ISBA 
