!depfile:dealloc_inland_watern.F90
MODULE MODI_DEALLOC_INLAND_WATER_n 
INTERFACE
SUBROUTINE DEALLOC_INLAND_WATER_n ( WM, FM, U)
USE MODD_SURFEX_n, ONLY : FLAKE_MODEL_t, WATFLUX_MODEL_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(WATFLUX_MODEL_t), INTENT(INOUT) :: WM
TYPE(FLAKE_MODEL_t), INTENT(INOUT) :: FM
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
END SUBROUTINE DEALLOC_INLAND_WATER_n

END INTERFACE
END MODULE MODI_DEALLOC_INLAND_WATER_n 
