!depfile:write_lcover.F90
MODULE MODI_WRITE_LCOVER
INTERFACE
      SUBROUTINE WRITE_LCOVER(HSELECT,HPROGRAM,OCOVER)
USE MODD_DATA_COVER_PAR, ONLY : JPCOVER
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
LOGICAL, DIMENSION(JPCOVER)    :: OCOVER   ! list of covers
END SUBROUTINE WRITE_LCOVER

END INTERFACE
END MODULE MODI_WRITE_LCOVER
