!depfile:read_from_surfex_file.F90
MODULE MODI_READ_FROM_SURFEX_FILE 
INTERFACE
SUBROUTINE READ_FROM_SURFEX_FILE (DTCO, U, &
                                  HFTYP,HFNAM,HMASK,HSCHEME,PFIELD,HNAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6), INTENT(IN) :: HFTYP
 CHARACTER(LEN=28), INTENT(IN) :: HFNAM
 CHARACTER(LEN=6), INTENT(IN) :: HMASK
 CHARACTER(LEN=6), INTENT(IN) :: HSCHEME
REAL, DIMENSION(:), INTENT(OUT) :: PFIELD
 CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: HNAM
END SUBROUTINE READ_FROM_SURFEX_FILE

END INTERFACE
END MODULE MODI_READ_FROM_SURFEX_FILE 
