!depfile:sfx_oasis_prep_ol.F90
MODULE MODI_SFX_OASIS_PREP_OL 
INTERFACE
SUBROUTINE SFX_OASIS_PREP_OL (IO, S, UG, U, HPROGRAM,HALG_MPI)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_S_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM   ! program calling surf. schemes
CHARACTER(LEN=4),   INTENT(IN)  :: HALG_MPI   ! decomposition algorithm
END SUBROUTINE SFX_OASIS_PREP_OL

END INTERFACE
END MODULE MODI_SFX_OASIS_PREP_OL 
