!depfile:read_default_surf_atmn.F90
MODULE MODI_READ_DEFAULT_SURF_ATM_n 
INTERFACE
      SUBROUTINE READ_DEFAULT_SURF_ATM_n (CHU, DGO, USS, HPROGRAM)
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_SSO_n, ONLY : SSO_t
TYPE(CH_SURF_t), INTENT(INOUT) :: CHU
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling GROUND
END SUBROUTINE READ_DEFAULT_SURF_ATM_n

END INTERFACE
END MODULE MODI_READ_DEFAULT_SURF_ATM_n 
