!depfile:control_temp_func.F90
MODULE MODI_CONTROL_TEMP_FUNC 
INTERFACE
FUNCTION CONTROL_TEMP_FUNC (PTEMP_IN) RESULT (PTEMPFUNC_RESULT)
REAL, DIMENSION(:), INTENT(IN)  :: PTEMP_IN ! temperature (K)
REAL, DIMENSION(SIZE(PTEMP_IN)) :: PTEMPFUNC_RESULT ! temperature control factor
END FUNCTION CONTROL_TEMP_FUNC

END INTERFACE
END MODULE MODI_CONTROL_TEMP_FUNC 
