!depfile:read_sbln.F90
MODULE MODI_READ_SBL_n 
INTERFACE
      SUBROUTINE READ_SBL_n (DTCO, U, SB, OSBL, HPROGRAM, HSURF)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_CANOPY_n, ONLY : CANOPY_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(CANOPY_t), INTENT(INOUT) :: SB
LOGICAL, INTENT(INOUT) :: OSBL
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM ! calling program
 CHARACTER(LEN=6), INTENT(IN) :: HSURF
END SUBROUTINE READ_SBL_n

END INTERFACE
END MODULE MODI_READ_SBL_n 
