!depfile:diag_inline_oceann.F90
MODULE MODI_DIAG_INLINE_OCEAN_n 
INTERFACE
       SUBROUTINE DIAG_INLINE_OCEAN_n (DGO, O, PSEABATHY) 
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DGO
TYPE(OCEAN_t), INTENT(INOUT) :: O
REAL, DIMENSION(:), INTENT(IN) :: PSEABATHY
END SUBROUTINE DIAG_INLINE_OCEAN_n

END INTERFACE
END MODULE MODI_DIAG_INLINE_OCEAN_n 
