!depfile:horibl_surf_value.F90
MODULE MODI_HORIBL_SURF_VALUE
INTERFACE
    SUBROUTINE HORIBL_SURF_VALUE(KILEN,KOLEN,PAROUT,OINTERP,PARIN,KLSMIN,&
                                 POLO,POLA,PLA,PLOP,&
                                 KMASKIN,KLSMOUT )  
INTEGER,                   INTENT(IN)  :: KILEN
INTEGER,                   INTENT(IN)  :: KOLEN   ! size of output array
REAL,    DIMENSION(:), INTENT(OUT) :: PAROUT  ! output array
LOGICAL, DIMENSION(:), INTENT(IN)  :: OINTERP ! .true. where physical value is needed
REAL, DIMENSION(:,:), INTENT(IN) :: PARIN
INTEGER, DIMENSION(:,:), INTENT(IN) :: KLSMIN
REAL, DIMENSION(:), INTENT(IN) :: POLO, POLA
REAL, DIMENSION(:,:), INTENT(IN) :: PLA
REAL, DIMENSION(:,:), INTENT(IN) :: PLOP
INTEGER, DIMENSION(:), INTENT(IN), OPTIONAL  :: KMASKIN  ! input land/sea mask
INTEGER, DIMENSION(:), INTENT(IN), OPTIONAL  :: KLSMOUT ! output land/sea mask
END SUBROUTINE HORIBL_SURF_VALUE

END INTERFACE
END MODULE MODI_HORIBL_SURF_VALUE
