!depfile:pgd_ecoclimap2_data.F90
MODULE MODI_PGD_ECOCLIMAP2_DATA 
INTERFACE
      SUBROUTINE PGD_ECOCLIMAP2_DATA (KYEAR, PDATA_VEGTYPE, &
                                      HPROGRAM)
INTEGER, INTENT(INOUT) :: KYEAR
REAL, DIMENSION(:,:), INTENt(IN) :: PDATA_VEGTYPE
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
END SUBROUTINE PGD_ECOCLIMAP2_DATA

END INTERFACE
END MODULE MODI_PGD_ECOCLIMAP2_DATA 
