!depfile:pack_pgd_seaflux.F90
MODULE MODI_PACK_PGD_SEAFLUX 
INTERFACE
      SUBROUTINE PACK_PGD_SEAFLUX (DTCO, KDIM, S, U, HPROGRAM,PSEABATHY)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
INTEGER, INTENT(INOUT) :: KDIM
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),        INTENT(IN) :: HPROGRAM  ! Type of program
REAL,    DIMENSION(:),   INTENT(IN) :: PSEABATHY ! bathymetry
END SUBROUTINE PACK_PGD_SEAFLUX

END INTERFACE
END MODULE MODI_PACK_PGD_SEAFLUX 
