!depfile:prep_ctrl_isba.F90
MODULE MODI_PREP_CTRL_ISBA
INTERFACE
SUBROUTINE PREP_CTRL_ISBA(DGO,OSURF_EVAP_BUDGET,OSURF_MISC_BUDGET,OSURF_MISC_DIF,KLUOUT )  
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
LOGICAL,  INTENT(INOUT) :: OSURF_EVAP_BUDGET  ! flag for surface evaporation budget
LOGICAL,  INTENT(INOUT) :: OSURF_MISC_BUDGET  ! flag for surface miscellaneous budget
LOGICAL,  INTENT(INOUT) :: OSURF_MISC_DIF     ! flag for surface miscellaneous dif variables
INTEGER,  INTENT(IN)    :: KLUOUT             ! unit number
END SUBROUTINE PREP_CTRL_ISBA

END INTERFACE
END MODULE MODI_PREP_CTRL_ISBA
