!depfile:get_surf_undef.F90
MODULE MODI_GET_SURF_UNDEF
INTERFACE
      SUBROUTINE GET_SURF_UNDEF(PUNDEF)
REAL, INTENT(OUT) :: PUNDEF
END SUBROUTINE GET_SURF_UNDEF

END INTERFACE
END MODULE MODI_GET_SURF_UNDEF
