!depfile:prep_ctrl_surf_atm.F90
MODULE MODI_PREP_CTRL_SURF_ATM
INTERFACE
      SUBROUTINE PREP_CTRL_SURF_ATM(DGO,ONOWRITE_TEXFILE,KLUOUT)  
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
LOGICAL,  INTENT(INOUT) :: ONOWRITE_TEXFILE    ! flag for surface variables
INTEGER,  INTENT(IN)    :: KLUOUT        ! unit number
END SUBROUTINE PREP_CTRL_SURF_ATM

END INTERFACE
END MODULE MODI_PREP_CTRL_SURF_ATM
