!depfile:close_aux_io_surf_nc.F90
MODULE MODI_CLOSE_AUX_IO_SURF_NC
INTERFACE
      SUBROUTINE CLOSE_AUX_IO_SURF_NC(HFILE,HFILETYPE)
 CHARACTER(LEN=28), INTENT(IN)  :: HFILE     ! file name
 CHARACTER(LEN=6),  INTENT(IN)  :: HFILETYPE ! main program
END SUBROUTINE CLOSE_AUX_IO_SURF_NC

END INTERFACE
END MODULE MODI_CLOSE_AUX_IO_SURF_NC
