!depfile:set_surfex_file_name_nc.F90
MODULE MODI_SET_SURFEX_FILE_NAME_NC
INTERFACE
SUBROUTINE SET_SURFEX_FILE_NAME_NC(HNAME_IN,HNAME_OUT)
 CHARACTER(LEN=28), OPTIONAL, INTENT(IN)     :: HNAME_IN
 CHARACTER(LEN=28), OPTIONAL, INTENT(OUT)    :: HNAME_OUT
END SUBROUTINE SET_SURFEX_FILE_NAME_NC

END INTERFACE
END MODULE MODI_SET_SURFEX_FILE_NAME_NC
