!depfile:get_sson.F90
MODULE MODI_GET_SSO_n 
INTERFACE
      SUBROUTINE GET_SSO_n (USS, &
                            HPROGRAM,KI,PSSO_SLOPE, PSSO_DIR)
USE MODD_SSO_n, ONLY : SSO_t
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
INTEGER,             INTENT(IN)  :: KI          ! horizontal dim. of cover
REAL, DIMENSION(KI), INTENT(OUT) :: PSSO_SLOPE  ! subgrid slope
REAL, DIMENSION(KI), INTENT(OUT) :: PSSO_DIR
END SUBROUTINE GET_SSO_n

END INTERFACE
END MODULE MODI_GET_SSO_n 
