!depfile:get_lcovern.F90
MODULE MODI_GET_LCOVER_n 
INTERFACE
      SUBROUTINE GET_LCOVER_n (U,HPROGRAM,KCOVER,OCOVER)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),           INTENT(IN)  :: HPROGRAM
INTEGER,                    INTENT(IN)  :: KCOVER  ! number of covers
LOGICAL, DIMENSION(KCOVER), INTENT(OUT) :: OCOVER  ! cover types
END SUBROUTINE GET_LCOVER_n

END INTERFACE
END MODULE MODI_GET_LCOVER_n 
