!depfile:albedo_ta96.F90
MODULE MODI_ALBEDO_TA96
INTERFACE
      FUNCTION ALBEDO_TA96(PZENITH) RESULT(PDIR_ALB)
REAL, DIMENSION(:), INTENT(IN)  :: PZENITH     ! zenithal angle (radian)
REAL, DIMENSION(SIZE(PZENITH))  :: PDIR_ALB    ! direct albedo on water
END FUNCTION ALBEDO_TA96

END INTERFACE
END MODULE MODI_ALBEDO_TA96
