!depfile:ol_read_atm_netcdf.F90
MODULE MODI_OL_READ_ATM_NETCDF 
INTERFACE
SUBROUTINE OL_READ_ATM_NETCDF (HSURF_FILETYPE,                            &
                               PTA,PQA,PWIND,PDIR_SW,PSCA_SW,PLW,PSNOW,   &
                               PRAIN,PPS,PCO2,PIMPWET,PIMPDRY,PO3,PAE,PDIR )  
REAL, DIMENSION(:,:),INTENT(OUT) :: PTA
REAL, DIMENSION(:,:),INTENT(OUT) :: PQA
REAL, DIMENSION(:,:),INTENT(OUT) :: PWIND
REAL, DIMENSION(:,:),INTENT(OUT) :: PDIR_SW
REAL, DIMENSION(:,:),INTENT(OUT) :: PSCA_SW
REAL, DIMENSION(:,:),INTENT(OUT) :: PLW
REAL, DIMENSION(:,:),INTENT(OUT) :: PSNOW
REAL, DIMENSION(:,:),INTENT(OUT) :: PRAIN
REAL, DIMENSION(:,:),INTENT(OUT) :: PPS
REAL, DIMENSION(:,:),INTENT(OUT) :: PCO2
REAL, DIMENSION(:,:),INTENT(OUT) :: PO3
REAL, DIMENSION(:,:),INTENT(OUT) :: PAE
REAL, DIMENSION(:,:,:),INTENT(OUT) :: PIMPWET
REAL, DIMENSION(:,:,:),INTENT(OUT) :: PIMPDRY
REAL, DIMENSION(:,:),INTENT(OUT) :: PDIR
 CHARACTER(LEN=6)    ,INTENT(IN)  :: HSURF_FILETYPE
END SUBROUTINE OL_READ_ATM_NETCDF

END INTERFACE
END MODULE MODI_OL_READ_ATM_NETCDF 
