!depfile:writesurf_seaicen.F90
MODULE MODI_WRITESURF_SEAICE_n 
INTERFACE
      SUBROUTINE WRITESURF_SEAICE_n (HSELECT, S, HPROGRAM)
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
END SUBROUTINE WRITESURF_SEAICE_n

END INTERFACE
END MODULE MODI_WRITESURF_SEAICE_n 
