!depfile:read_dimlen.F90
MODULE MODI_READ_DIMLEN
INTERFACE
SUBROUTINE READ_DIMLEN(KLUOUT,HFILE,HVAR,KDIM,KDIMLEN)
INTEGER,          INTENT(IN)       :: KLUOUT
 CHARACTER(LEN=*), INTENT(IN)       :: HFILE
 CHARACTER(LEN=*), INTENT(IN)       :: HVAR
INTEGER,          INTENT(IN)       :: KDIM
INTEGER, DIMENSION(KDIM), INTENT(OUT) :: KDIMLEN
END SUBROUTINE READ_DIMLEN

END INTERFACE
END MODULE MODI_READ_DIMLEN
