!depfile:prep_ctrl_seaflux.F90
MODULE MODI_PREP_CTRL_SEAFLUX
INTERFACE
      SUBROUTINE PREP_CTRL_SEAFLUX(DGO,ODIAG_OCEAN,ODIAG_MISC_SEAICE,KLUOUT)  
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
LOGICAL, INTENT(INOUT) :: ODIAG_OCEAN
LOGICAL,  INTENT(INOUT) :: ODIAG_MISC_SEAICE       ! flag for seaice variables
INTEGER,  INTENT(IN)    :: KLUOUT             ! unit number
END SUBROUTINE PREP_CTRL_SEAFLUX

END INTERFACE
END MODULE MODI_PREP_CTRL_SEAFLUX
