!depfile:explicit_slope.F90
MODULE MODI_EXPLICIT_SLOPE 
INTERFACE
SUBROUTINE EXPLICIT_SLOPE (UG,KDIM_FULL, &
                           PZS,PSSO_SLOPE)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
INTEGER, INTENT(IN) :: KDIM_FULL
REAL,DIMENSION(:),INTENT(IN)::PZS ! resolved model orography
REAL,DIMENSION(:),INTENT(OUT)::PSSO_SLOPE ! resolved slope tangent
INTEGER, PARAMETER :: JPHEXT = 1 ! number of points around the physical domain
END SUBROUTINE EXPLICIT_SLOPE

END INTERFACE
END MODULE MODI_EXPLICIT_SLOPE 
