!depfile:read_nam_grid_conf_proj.F90
MODULE MODI_READ_NAM_GRID_CONF_PROJ
INTERFACE
      SUBROUTINE READ_NAM_GRID_CONF_PROJ(GCP,PGRID_FULL_PAR,KDIM_FULL,HPROGRAM,KGRID_PAR,KL,PGRID_PAR,HDIR)
USE MODD_GRID_CONF_PROJ_n, ONLY :GRID_CONF_PROJ_t
TYPE(GRID_CONF_PROJ_t),INTENT(INOUT) :: GCP
REAL, DIMENSION(:), POINTER :: PGRID_FULL_PAR
INTEGER, INTENT(IN) :: KDIM_FULL
 CHARACTER(LEN=6),           INTENT(IN)    :: HPROGRAM   ! calling program
INTEGER,                    INTENT(INOUT) :: KGRID_PAR  ! size of PGRID_PAR
INTEGER,                    INTENT(OUT)   :: KL         ! number of points
REAL, DIMENSION(KGRID_PAR), INTENT(OUT)   :: PGRID_PAR  ! parameters defining this grid
 CHARACTER(LEN=1), INTENT(IN) :: HDIR
END SUBROUTINE READ_NAM_GRID_CONF_PROJ

END INTERFACE
END MODULE MODI_READ_NAM_GRID_CONF_PROJ
