!depfile:flood_redistrib.F90
MODULE MODI_FLOOD_REDISTRIB 
INTERFACE
      SUBROUTINE FLOOD_REDISTRIB (TP, TPG,                              &
                                  KLON,KLAT,PTSTEP,PREAD,PSRCFLD,PRESIDU)  
USE MODD_TRIP, ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_t),      INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER, INTENT(IN)               :: KLON
INTEGER, INTENT(IN)               :: KLAT
REAL,    INTENT(IN)               :: PTSTEP
REAL, DIMENSION(:,:), INTENT(IN ) :: PREAD   ![kg/m2/s]
REAL, DIMENSION(:,:), INTENT(OUT) :: PSRCFLD ![kg/m2/s]
REAL, DIMENSION(:,:), INTENT(OUT) :: PRESIDU ![kg/m2/s]
END SUBROUTINE FLOOD_REDISTRIB

END INTERFACE
END MODULE MODI_FLOOD_REDISTRIB 
