!depfile:read_nam_trip_prep.F90
MODULE MODI_READ_NAM_TRIP_PREP
INTERFACE
SUBROUTINE READ_NAM_TRIP_PREP(KLISTING)
INTEGER, INTENT(IN) :: KLISTING
END SUBROUTINE READ_NAM_TRIP_PREP

END INTERFACE
END MODULE MODI_READ_NAM_TRIP_PREP
