!depfile:convert_patch_teb.F90
MODULE MODI_CONVERT_PATCH_TEB 
INTERFACE
      SUBROUTINE CONVERT_PATCH_TEB (BDD, DTB, DTCO, DTT, TOP, &
                                   PDEF_ROAD_DIR, T, B, TPN )
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_t
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
TYPE(DATA_BEM_t), INTENT(INOUT) :: DTB
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_TEB_t), INTENT(INOUT) :: DTT
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
REAL,                   INTENT(IN)    :: PDEF_ROAD_DIR ! default road direction
TYPE(TEB_t), INTENT(INOUT), OPTIONAL :: T
TYPE(BEM_t), INTENT(INOUT), OPTIONAL :: B
TYPE(TEB_PANEL_t), INTENT(INOUT), OPTIONAL :: TPN
END SUBROUTINE CONVERT_PATCH_TEB

END INTERFACE
END MODULE MODI_CONVERT_PATCH_TEB 
