!depfile:pgd_teb_par.F90
MODULE MODI_PGD_TEB_PAR 
INTERFACE
      SUBROUTINE PGD_TEB_PAR (DTCO, UG, U, USS, BDD, DTT, KDIM, &
                              HPROGRAM,OGARDEN,OGREENROOF,HBLD_ATYPE)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
USE MODD_DATA_TEB_n, ONLY : DATA_TEB_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
TYPE(DATA_TEB_t), INTENT(INOUT) :: DTT
INTEGER, INTENT(IN) :: KDIM
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
LOGICAL,             INTENT(IN)    :: OGARDEN      ! T if urban green areas
LOGICAL,             INTENT(IN)    :: OGREENROOF   ! T if greenroofs option is activated
 CHARACTER(LEN=3),    INTENT(OUT)   :: HBLD_ATYPE    ! Type of building averaging
INTEGER, PARAMETER :: NROOF_MAX  = 9
INTEGER, PARAMETER :: NROAD_MAX  = 9
INTEGER, PARAMETER :: NWALL_MAX  = 9
END SUBROUTINE PGD_TEB_PAR

END INTERFACE
END MODULE MODI_PGD_TEB_PAR 
