!depfile:allocate_physio.F90
MODULE MODI_ALLOCATE_PHYSIO 
INTERFACE
    SUBROUTINE ALLOCATE_PHYSIO (IO, KK, PK, PEK, KVEGTYPE )
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_TYPE_DATE_SURF
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
INTEGER, INTENT(IN) :: KVEGTYPE
END SUBROUTINE ALLOCATE_PHYSIO

END INTERFACE
END MODULE MODI_ALLOCATE_PHYSIO 
