!depfile:read_pgd_isba_parn.F90
MODULE MODI_READ_PGD_ISBA_PAR_n 
INTERFACE
      SUBROUTINE READ_PGD_ISBA_PAR_n (DTCO, U, GCP, DTI, KDIM, IO, HPROGRAM,KSIZE,OLAND_USE, TPDATE_BEG, TPDATE_END, HDIR)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_GRID_CONF_PROJ_n, ONLY : GRID_CONF_PROJ_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_TYPE_DATE_SURF, ONLY : DATE
USE MODD_DATA_COVER_PAR, ONLY : NVEGTYPE, NVEGTYPE_OLD, NVEGTYPE_ECOSG
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(GRID_CONF_PROJ_t),INTENT(INOUT) :: GCP
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTI
INTEGER, INTENT(IN) :: KDIM
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
INTEGER,           INTENT(IN)  :: KSIZE
LOGICAL,           INTENT(IN)  :: OLAND_USE ! 
TYPE(DATE), INTENT(IN) :: TPDATE_BEG
TYPE(DATE), INTENT(IN) :: TPDATE_END
CHARACTER(LEN=1),OPTIONAL,INTENT(IN)  :: HDIR       ! type of field :
END SUBROUTINE READ_PGD_ISBA_PAR_n

END INTERFACE
END MODULE MODI_READ_PGD_ISBA_PAR_n 
