!depfile:get_default_namn.F90
MODULE MODI_GET_DEFAULT_NAM_n
INTERFACE
      SUBROUTINE GET_DEFAULT_NAM_n(HPROGRAM,HACTION,KLUDES,ONAM_WRITTEN)
 CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM
 CHARACTER(LEN=5), INTENT(IN)  :: HACTION ! 'READ ', 'WRITE'
INTEGER, INTENT(OUT) :: KLUDES ! logical unit of .des file
LOGICAL, INTENT(INOUT), OPTIONAL :: ONAM_WRITTEN
END SUBROUTINE GET_DEFAULT_NAM_n

END INTERFACE
END MODULE MODI_GET_DEFAULT_NAM_n
