!depfile:isba_emis_meb.F90
MODULE MODI_ISBA_EMIS_MEB
INTERFACE
      SUBROUTINE ISBA_EMIS_MEB(PPSN, PPSNA, PSIGMA_F, PSIGMA_FN,  &
                               PEMIS_N, PEMIS                     )
REAL, DIMENSION(:),   INTENT(IN)   :: PPSN, PPSNA
REAL, DIMENSION(:),   INTENT(IN)   :: PSIGMA_F, PSIGMA_FN, PEMIS_N
REAL, DIMENSION(:),   INTENT(OUT)  :: PEMIS
END SUBROUTINE ISBA_EMIS_MEB

END INTERFACE
END MODULE MODI_ISBA_EMIS_MEB
