!depfile:writesurf_sso_canopyn.F90
MODULE MODI_WRITESURF_SSO_CANOPY_n 
INTERFACE
      SUBROUTINE WRITESURF_SSO_CANOPY_n (HSELECT,SB,HPROGRAM,OWRITE)
USE MODD_CANOPY_n, ONLY : CANOPY_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(CANOPY_t), INTENT(INOUT) :: SB
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
LOGICAL,           INTENT(IN)  :: OWRITE   ! flag to write canopy terms
END SUBROUTINE WRITESURF_SSO_CANOPY_n

END INTERFACE
END MODULE MODI_WRITESURF_SSO_CANOPY_n 
