!depfile:create_file.F90
MODULE MODI_CREATE_FILE
INTERFACE
      SUBROUTINE CREATE_FILE(HFILE,KDIMS,HNAM_DIM,KFILE_ID,KDIM_ID)
 CHARACTER(LEN=*),            INTENT(IN)          :: HFILE
INTEGER, DIMENSION(:),        INTENT(IN)          :: KDIMS
 CHARACTER(LEN=*),DIMENSION(:),INTENT(IN)         :: HNAM_DIM
INTEGER,                      INTENT(INOUT)       :: KFILE_ID
INTEGER, DIMENSION(:),        INTENT(INOUT)       :: KDIM_ID
END SUBROUTINE CREATE_FILE

END INTERFACE
END MODULE MODI_CREATE_FILE
