!depfile:prep_buffer_grid.F90
MODULE MODI_PREP_BUFFER_GRID
INTERFACE
      SUBROUTINE PREP_BUFFER_GRID(KLUOUT,HINMODEL,TPTIME_BUF)
USE MODD_TYPE_DATE_SURF
INTEGER,          INTENT(IN)    :: KLUOUT    ! logical unit of output listing
 CHARACTER(LEN=6), INTENT(OUT)   :: HINMODEL  ! originating model
TYPE (DATE_TIME)                :: TPTIME_BUF    ! current date and time
END SUBROUTINE PREP_BUFFER_GRID

END INTERFACE
END MODULE MODI_PREP_BUFFER_GRID
