!depfile:default_deepsoil.F90
MODULE MODI_DEFAULT_DEEPSOIL
INTERFACE
      SUBROUTINE DEFAULT_DEEPSOIL(ODEEPSOIL,OPHYSDOMC)
LOGICAL, INTENT(OUT) :: ODEEPSOIL
LOGICAL, INTENT(OUT) :: OPHYSDOMC
END SUBROUTINE DEFAULT_DEEPSOIL

END INTERFACE
END MODULE MODI_DEFAULT_DEEPSOIL
