!depfile:read_isba_confn.F90
MODULE MODI_READ_ISBA_CONF_n 
INTERFACE
      SUBROUTINE READ_ISBA_CONF_n (CHI, DE, DGO, DMI, IO, HPROGRAM)
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DE
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMI
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling ISBA
END SUBROUTINE READ_ISBA_CONF_n

END INTERFACE
END MODULE MODI_READ_ISBA_CONF_n 
