!depfile:read_nam_prep_surfn.F90
MODULE MODI_READ_NAM_PREP_SURF_n
INTERFACE
SUBROUTINE READ_NAM_PREP_SURF_n(HPROGRAM)
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE READ_NAM_PREP_SURF_n

END INTERFACE
END MODULE MODI_READ_NAM_PREP_SURF_n
