!depfile:soiltemp_arp_par.F90
MODULE MODI_SOILTEMP_ARP_PAR 
INTERFACE
      SUBROUTINE SOILTEMP_ARP_PAR (IO, HPROGRAM)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
END SUBROUTINE SOILTEMP_ARP_PAR

END INTERFACE
END MODULE MODI_SOILTEMP_ARP_PAR 
