!depfile:soil.F90
MODULE MODI_SOIL
INTERFACE
      SUBROUTINE SOIL( IO, KK, PK, PEK, DMI, PVEG, PCS, PFROZEN1, PFFG_NOSNOW, PFFV_NOSNOW               )  
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT)       :: KK
TYPE(ISBA_P_t), INTENT(INOUT)       :: PK
TYPE(ISBA_PE_t), INTENT(INOUT)      :: PEK
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMI
REAL, DIMENSION(:), INTENT(IN)      :: PVEG
REAL, DIMENSION(:), INTENT(OUT)     :: PCS, PFROZEN1
REAL, DIMENSION(:), INTENT(IN)   :: PFFG_NOSNOW, PFFV_NOSNOW
END SUBROUTINE SOIL

END INTERFACE
END MODULE MODI_SOIL
