!depfile:get_grid_coord_lonlat_rot.F90
MODULE MODI_GET_GRID_COORD_LONLAT_ROT
INTERFACE
      SUBROUTINE GET_GRID_COORD_LONLAT_ROT(KGRID_PAR,KL,PGRID_PAR,PX,PY)
INTEGER,                    INTENT(IN)  :: KGRID_PAR  ! size of PGRID_PAR
INTEGER,                    INTENT(IN)  :: KL         ! number of points
REAL, DIMENSION(KGRID_PAR), INTENT(IN)  :: PGRID_PAR  ! parameters defining this grid
REAL, DIMENSION(KL),        INTENT(OUT) :: PX         ! (deg)
REAL, DIMENSION(KL),        INTENT(OUT) :: PY         ! (deg)
END SUBROUTINE GET_GRID_COORD_LONLAT_ROT

END INTERFACE
END MODULE MODI_GET_GRID_COORD_LONLAT_ROT
