!depfile:dealloc_naturen.F90
MODULE MODI_DEALLOC_NATURE_n 
INTERFACE
SUBROUTINE DEALLOC_NATURE_n (IM, U)
USE MODD_SURFEX_n, ONLY : ISBA_MODEL_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(ISBA_MODEL_t), INTENT(INOUT) :: IM
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
END SUBROUTINE DEALLOC_NATURE_n

END INTERFACE
END MODULE MODI_DEALLOC_NATURE_n 
