!depfile:hor_interpol_buffer.F90
MODULE MODI_HOR_INTERPOL_BUFFER 
INTERFACE
SUBROUTINE HOR_INTERPOL_BUFFER (DTCO, U, KLUOUT,PFIELDIN,PFIELDOUT)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
INTEGER,            INTENT(IN)  :: KLUOUT    ! logical unit of output listing
REAL, DIMENSION(:,:), INTENT(IN)  :: PFIELDIN  ! field to interpolate horizontally
REAL, DIMENSION(:,:), INTENT(OUT) :: PFIELDOUT ! interpolated field
END SUBROUTINE HOR_INTERPOL_BUFFER

END INTERFACE
END MODULE MODI_HOR_INTERPOL_BUFFER 
