!depfile:get_var_sean.F90
MODULE MODI_GET_VAR_SEA_n 
INTERFACE
      SUBROUTINE GET_VAR_SEA_n (DGO, D, S, HPROGRAM,KI,PQS,PZ0,PZ0H, PSIC)
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t 
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
 CHARACTER(LEN=6),     INTENT(IN)     :: HPROGRAM
INTEGER,              INTENT(IN)     :: KI      ! Number of points
REAL, DIMENSION(KI),  INTENT(OUT)    :: PQS     ! surface humidity
REAL, DIMENSION(KI),  INTENT(OUT)    :: PZ0     ! surface roughness length
REAL, DIMENSION(KI),  INTENT(OUT)    :: PZ0H    ! surface roughness length for heat
REAL, DIMENSION(KI),  INTENT(OUT)    :: PSIC
END SUBROUTINE GET_VAR_SEA_n

END INTERFACE
END MODULE MODI_GET_VAR_SEA_n 
