!depfile:write_gridtype_lonlat_rot.F90
MODULE MODI_WRITE_GRIDTYPE_LONLAT_ROT 
INTERFACE
      SUBROUTINE WRITE_GRIDTYPE_LONLAT_ROT (HSELECT,HPROGRAM,KLU,KGRID_PAR,PGRID_PAR,KRESP)
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
CHARACTER(LEN=6),           INTENT(IN)  :: HPROGRAM   ! calling program
INTEGER,                    INTENT(IN)  :: KLU        ! number of points
INTEGER,                    INTENT(IN)  :: KGRID_PAR  ! size of PGRID_PAR
REAL, DIMENSION(KGRID_PAR), INTENT(IN)  :: PGRID_PAR  ! parameters defining this grid
INTEGER,                    INTENT(OUT) :: KRESP      ! error return code
END SUBROUTINE WRITE_GRIDTYPE_LONLAT_ROT

END INTERFACE
END MODULE MODI_WRITE_GRIDTYPE_LONLAT_ROT 
