!depfile:init_slope_param.F90
MODULE MODI_INIT_SLOPE_PARAM 
INTERFACE
SUBROUTINE INIT_SLOPE_PARAM (UG, PGRID_FULL_PAR, PZS, KI, PLAT)
USE MODD_SFX_GRID_n, ONLY : GRID_t
TYPE(GRID_t), INTENT(INOUT) :: UG
REAL, DIMENSION(:), INTENT(IN) :: PGRID_FULL_PAR
INTEGER,              INTENT(IN)  :: KI        ! number of points
REAL, DIMENSION(KI),   INTENT(IN) :: PZS      ! orography of this MPI thread (or total domain if Open MP)
REAL,DIMENSION(:),INTENT(IN):: PLAT ! latitudes
INTEGER, PARAMETER :: JPHEXT = 1 ! number of points around the physical domain
INTEGER,PARAMETER::ITAG=100
INTEGER,PARAMETER::ITAG2=101
END SUBROUTINE INIT_SLOPE_PARAM

END INTERFACE
END MODULE MODI_INIT_SLOPE_PARAM 
