!depfile:ini_data_cover.F90
MODULE MODI_INI_DATA_COVER 
INTERFACE
      SUBROUTINE INI_DATA_COVER (DTCO, U)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_TYPE_DATE_SURF
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
END SUBROUTINE INI_DATA_COVER

END INTERFACE
END MODULE MODI_INI_DATA_COVER 
