!depfile:read_lcover.F90
MODULE MODI_READ_LCOVER 
INTERFACE
      SUBROUTINE READ_LCOVER (HPROGRAM,OCOVER)
USE MODD_DATA_COVER_PAR, ONLY : JPCOVER
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
LOGICAL, DIMENSION(JPCOVER)    :: OCOVER   ! list of covers
END SUBROUTINE READ_LCOVER

END INTERFACE
END MODULE MODI_READ_LCOVER 
