!depfile:error_write_surf_asc.F90
MODULE MODI_ERROR_WRITE_SURF_ASC
INTERFACE
SUBROUTINE ERROR_WRITE_SURF_ASC(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(OUT):: KRESP
END SUBROUTINE ERROR_WRITE_SURF_ASC

END INTERFACE
END MODULE MODI_ERROR_WRITE_SURF_ASC
