!depfile:writesurf_seafluxn.F90
MODULE MODI_WRITESURF_SEAFLUX_n 
INTERFACE
      SUBROUTINE WRITESURF_SEAFLUX_n (HSELECT, O, OR, S, HPROGRAM)
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT 
TYPE(OCEAN_t), INTENT(INOUT) :: O
TYPE(OCEAN_REL_t), INTENT(INOUT) :: OR
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE WRITESURF_SEAFLUX_n

END INTERFACE
END MODULE MODI_WRITESURF_SEAFLUX_n 
