!depfile:hydro_soildif.F90
MODULE MODI_HYDRO_SOILDIF
INTERFACE
      SUBROUTINE HYDRO_SOILDIF(IO, KK, PK, PEK, PTSTEP, PPG, PLETR, PLEG, PEVAPCOR, &
                               PF2WGHT, PPS, PQSAT, PQSATI, PDRAIN, PHORTON, KMAX_LAYER, PQSB)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
REAL, INTENT(IN)                    :: PTSTEP ! Model time step (s)
REAL, DIMENSION(:), INTENT(IN)      :: PPS, PPG, PLETR, PLEG, PEVAPCOR
REAL, DIMENSION(:,:), INTENT(IN)    :: PQSAT,PQSATI
REAL, DIMENSION(:,:), INTENT(IN)    :: PF2WGHT
INTEGER,               INTENT(IN)   :: KMAX_LAYER  
REAL, DIMENSION(:), INTENT(OUT)     :: PDRAIN, PHORTON
REAL, DIMENSION(:),   INTENT(OUT)   :: PQSB     !Lateral subsurface flow [kg/m²/s]
END SUBROUTINE HYDRO_SOILDIF 

END INTERFACE
END MODULE MODI_HYDRO_SOILDIF
