!depfile:dg_dfto3l.F90
MODULE MODI_DG_DFTO3L 
INTERFACE
      SUBROUTINE DG_DFTO3L (IO, NP, PDG)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_NP_t, ISBA_P_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
 REAL, DIMENSION(:,:), INTENT(OUT) :: PDG
END SUBROUTINE DG_DFTO3L

END INTERFACE
END MODULE MODI_DG_DFTO3L 
