!depfile:get_1d_mask.F90
MODULE MODI_GET_1D_MASK
INTERFACE
SUBROUTINE GET_1D_MASK(KSIZE,KFRAC,PFRAC,KMASK)
INTEGER, INTENT(IN)                      :: KSIZE
INTEGER, INTENT(IN)                      :: KFRAC
REAL, DIMENSION(KFRAC), INTENT(IN)       :: PFRAC
INTEGER, DIMENSION(KSIZE), INTENT(OUT)   :: KMASK
END SUBROUTINE GET_1D_MASK

END INTERFACE
END MODULE MODI_GET_1D_MASK
