!depfile:error_read_surf_asc.F90
MODULE MODI_ERROR_READ_SURF_ASC
INTERFACE
SUBROUTINE ERROR_READ_SURF_ASC(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(OUT):: KRESP
END SUBROUTINE ERROR_READ_SURF_ASC

END INTERFACE
END MODULE MODI_ERROR_READ_SURF_ASC
