!depfile:convert_teb.F90
MODULE MODI_CONVERT_TEB 
INTERFACE
      SUBROUTINE CONVERT_TEB (KTEB_PATCH,PCOVER,PTEB_PATCH)
INTEGER, INTENT(IN) :: KTEB_PATCH
REAL, DIMENSION(:,:),   INTENT(IN)    :: PCOVER
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL   :: PTEB_PATCH !  fraction of each TEB patch
END SUBROUTINE CONVERT_TEB

END INTERFACE
END MODULE MODI_CONVERT_TEB 
