!depfile:get_jcovern.F90
MODULE MODI_GET_JCOVER_n 
INTERFACE
      SUBROUTINE GET_JCOVER_n (U, &
                               HPROGRAM,KCOVER)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),     INTENT(IN)   :: HPROGRAM
INTEGER,              INTENT(OUT)  :: KCOVER  ! number of cover types
END SUBROUTINE GET_JCOVER_n

END INTERFACE
END MODULE MODI_GET_JCOVER_n 
