!depfile:default_ch_surf_atm.F90
MODULE MODI_DEFAULT_CH_SURF_ATM
INTERFACE
      SUBROUTINE DEFAULT_CH_SURF_ATM(HCHEM_SURF_FILE,OSURF_EMIS)
 CHARACTER(LEN=28),        INTENT(OUT) :: HCHEM_SURF_FILE
LOGICAL,                  INTENT(OUT) :: OSURF_EMIS
END SUBROUTINE DEFAULT_CH_SURF_ATM

END INTERFACE
END MODULE MODI_DEFAULT_CH_SURF_ATM
