!depfile:get_sso_stdevn.F90
MODULE MODI_GET_SSO_STDEV_n 
INTERFACE
      SUBROUTINE GET_SSO_STDEV_n (USS, &
                                  HPROGRAM,KI,PSSO_STDEV)
USE MODD_SSO_n, ONLY : SSO_t
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
INTEGER,             INTENT(IN)  :: KI      ! horizontal dim. of cover
REAL, DIMENSION(KI), INTENT(OUT) :: PSSO_STDEV     ! S.S.O. standard deviation (m)
END SUBROUTINE GET_SSO_STDEV_n

END INTERFACE
END MODULE MODI_GET_SSO_STDEV_n 
