!depfile:dgam.F90
MODULE MODI_DGAM
INTERFACE
SUBROUTINE DGAM(PA, PX, PACC, PG, PGSTAR, KFLG, KFLGST)
REAL, INTENT(IN) :: PA, PX, PACC
REAL, INTENT(OUT) :: PG, PGSTAR
INTEGER, INTENT(OUT) :: KFLG, KFLGST
END SUBROUTINE DGAM

END INTERFACE
END MODULE MODI_DGAM
