!depfile:get_type_dimn.F90
MODULE MODI_GET_TYPE_DIM_n 
INTERFACE
      SUBROUTINE GET_TYPE_DIM_n (DTCO, U, &
                                 HTYPE,KDIM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),  INTENT(IN)      :: HTYPE    ! Type of surface
INTEGER,           INTENT(INOUT)   :: KDIM     ! size of the mask
END SUBROUTINE GET_TYPE_DIM_n

END INTERFACE
END MODULE MODI_GET_TYPE_DIM_n 
