!depfile:prep_isba_grib.F90
MODULE MODI_PREP_ISBA_GRIB
INTERFACE
SUBROUTINE PREP_ISBA_GRIB(HPROGRAM,HSURF,HFILE,KLUOUT,PFIELD,OKEY)
USE MODD_TYPE_DATE_SURF
CHARACTER(LEN=6),   INTENT(IN)    :: HPROGRAM  ! program calling surf. schemes
CHARACTER(LEN=7),   INTENT(IN)    :: HSURF     ! type of field
CHARACTER(LEN=28),  INTENT(IN)    :: HFILE     ! name of file
INTEGER,            INTENT(IN)    :: KLUOUT    ! logical unit of output listing
REAL,DIMENSION(:,:,:), POINTER    :: PFIELD    ! field to interpolate horizontally
LOGICAL, OPTIONAL,  INTENT(INOUT) :: OKEY
END SUBROUTINE PREP_ISBA_GRIB

END INTERFACE
END MODULE MODI_PREP_ISBA_GRIB
