!depfile:sfx_xios_readnam_ol.F90
MODULE MODI_SFX_XIOS_READNAM_OL
INTERFACE
SUBROUTINE SFX_XIOS_READNAM_OL(HNAMELIST)
CHARACTER(LEN=28), INTENT(IN )           :: HNAMELIST
END SUBROUTINE SFX_XIOS_READNAM_OL

END INTERFACE
END MODULE MODI_SFX_XIOS_READNAM_OL
