!depfile:prep_output_grid.F90
MODULE MODI_PREP_OUTPUT_GRID 
INTERFACE
      SUBROUTINE PREP_OUTPUT_GRID (UG, G, KSIZE_FULL, KLUOUT)
USE MODD_SFX_GRID_n, ONLY : GRID_t
TYPE(GRID_t), INTENT(INOUT) :: UG
TYPE(GRID_t), INTENT(INOUT) :: G
INTEGER, INTENT(IN) :: KSIZE_FULL
INTEGER,           INTENT(IN)  :: KLUOUT     ! output listing logical unit
END SUBROUTINE PREP_OUTPUT_GRID

END INTERFACE
END MODULE MODI_PREP_OUTPUT_GRID 
