!depfile:diag_naturen.F90
MODULE MODI_DIAG_NATURE_n 
INTERFACE
SUBROUTINE DIAG_NATURE_n (DLO, DL, DLC, ID, HNATURE, &
                          HPROGRAM, DUP, DUPC, KMASK )
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_SURFEX_n, ONLY : ISBA_DIAG_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DLO
TYPE(DIAG_t), INTENT(INOUT) :: DL
TYPE(DIAG_t), INTENT(INOUT) :: DLC
TYPE(ISBA_DIAG_t), INTENT(INOUT) :: ID
 CHARACTER(LEN=*), INTENT(IN) :: HNATURE
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
TYPE(DIAG_t), INTENT(INOUT) :: DUP
TYPE(DIAG_t), INTENT(INOUT) :: DUPC
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
END SUBROUTINE DIAG_NATURE_n

END INTERFACE
END MODULE MODI_DIAG_NATURE_n 
