!depfile:read_sson.F90
MODULE MODI_READ_SSO_n 
INTERFACE
      SUBROUTINE READ_SSO_n (KSIZE_FULL, PSEA, USS, HPROGRAM)
USE MODD_SSO_n, ONLY : SSO_t
INTEGER, INTENT(IN) :: KSIZE_FULL
REAL, DIMENSION(:), INTENT(IN) :: PSEA
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
END SUBROUTINE READ_SSO_n

END INTERFACE
END MODULE MODI_READ_SSO_n 
