!depfile:deepsoil_update.F90
MODULE MODI_DEEPSOIL_UPDATE 
INTERFACE
    SUBROUTINE DEEPSOIL_UPDATE (PTDEEP, PGAMMAT, KMONTH)
REAL, DIMENSION(:), INTENT(INOUT) :: PTDEEP
REAL, DIMENSION(:), INTENT(INOUT) :: PGAMMAT
INTEGER,              INTENT(IN)    :: KMONTH   ! current month
END SUBROUTINE DEEPSOIL_UPDATE

END INTERFACE
END MODULE MODI_DEEPSOIL_UPDATE 
