!depfile:read_dummyn.F90
MODULE MODI_READ_DUMMY_n 
INTERFACE
      SUBROUTINE READ_DUMMY_n (DUU, KSIZE_FULL, HPROGRAM)
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_t
TYPE(DUMMY_SURF_FIELDS_t), INTENT(INOUT) :: DUU
INTEGER, INTENT(IN) :: KSIZE_FULL
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM     ! 
END SUBROUTINE READ_DUMMY_n

END INTERFACE
END MODULE MODI_READ_DUMMY_n 
