!depfile:ol_define_dim.F90
MODULE MODI_OL_DEFINE_DIM 
INTERFACE
SUBROUTINE OL_DEFINE_DIM (UG, KSIZE_FULL, HPROGRAM, KLUOUT, KNI, &
			  									TSNOW,                     &
                          KDIM1, HUNIT1, HUNIT2, PX, PY, KDIMS,  &
                          KDDIM, HNAME_DIM, OSNOWBANDS, KNPATCH, &
			  									KNSNLAYER, PLAT, PLON)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_TYPE_SNOW,ONLY : SURF_SNOW
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
INTEGER, INTENT(IN) :: KSIZE_FULL
 CHARACTER(LEN=6),  INTENT(IN)    :: HPROGRAM
INTEGER, INTENT(IN)              :: KLUOUT
INTEGER, INTENT(IN)              :: KNI
LOGICAL, INTENT(IN)		:: OSNOWBANDS
TYPE(SURF_SNOW),INTENT(IN)           :: TSNOW
INTEGER, INTENT(OUT)             :: KDIM1
 CHARACTER(LEN=13) , DIMENSION(:), INTENT(OUT) :: HUNIT1, HUNIT2
REAL,DIMENSION(:), POINTER                 :: PX, PY
INTEGER, DIMENSION(:), POINTER             :: KDIMS, KDDIM
 CHARACTER(LEN=100), DIMENSION(:), POINTER :: HNAME_DIM
INTEGER, OPTIONAL, INTENT(IN)              :: KNPATCH
INTEGER, OPTIONAL, INTENT(IN)              :: KNSNLAYER
REAL, DIMENSION(:), OPTIONAL, POINTER      :: PLAT, PLON
END SUBROUTINE OL_DEFINE_DIM

END INTERFACE
END MODULE MODI_OL_DEFINE_DIM 
