!depfile:error_write_surf_lfi.F90
MODULE MODI_ERROR_WRITE_SURF_LFI
INTERFACE
SUBROUTINE ERROR_WRITE_SURF_LFI(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN):: HREC
INTEGER,          INTENT(IN):: KRESP
END SUBROUTINE ERROR_WRITE_SURF_LFI

END INTERFACE
END MODULE MODI_ERROR_WRITE_SURF_LFI
