!depfile:read_namelists_slt.F90
MODULE MODI_READ_NAMELISTS_SLT
INTERFACE
SUBROUTINE READ_NAMELISTS_SLT(HPROGRAM)
 CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM ! program calling SLT
END SUBROUTINE READ_NAMELISTS_SLT

END INTERFACE
END MODULE MODI_READ_NAMELISTS_SLT
