!depfile:close_namelist.F90
MODULE MODI_CLOSE_NAMELIST
INTERFACE
      SUBROUTINE CLOSE_NAMELIST(HPROGRAM,KLUNAM)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KLUNAM   ! logical unit of namelist
END SUBROUTINE CLOSE_NAMELIST

END INTERFACE
END MODULE MODI_CLOSE_NAMELIST
