!depfile:bldcode.F90
MODULE MODI_BLDCODE 
INTERFACE
FUNCTION BLDCODE (BDD, KTYPE,KAGE) RESULT(KCODE)
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
INTEGER, DIMENSION(:), INTENT(IN) :: KTYPE ! Type of building
INTEGER, DIMENSION(:), INTENT(IN) :: KAGE  ! date of construction (or total renovation) of building
INTEGER, DIMENSION(SIZE(KTYPE))   :: KCODE ! Building code (merges type & age info).
END FUNCTION BLDCODE

END INTERFACE
END MODULE MODI_BLDCODE 
