!depfile:average_diag.F90
MODULE MODI_AVERAGE_DIAG
INTERFACE
      SUBROUTINE AVERAGE_DIAG(PFRAC_TILE, DGO, D, ND, DC, NDC      )                                
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_NP_t, DIAG_OPTIONS_t
REAL, DIMENSION(:,:), INTENT(IN) :: PFRAC_TILE   ! Fraction in a mesh-area of 
TYPE(DIAG_OPTIONS_t), INTENt(INOUT) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_NP_t), INTENT(INOUT) :: ND
TYPE(DIAG_t), INTENT(INOUT) :: DC
TYPE(DIAG_NP_t), INTENT(INOUT) :: NDC
END SUBROUTINE AVERAGE_DIAG

END INTERFACE
END MODULE MODI_AVERAGE_DIAG
