!depfile:read_nam_pgd_teb_greenroof.F90
MODULE MODI_READ_NAM_PGD_TEB_GREENROOF
INTERFACE
      SUBROUTINE READ_NAM_PGD_TEB_GREENROOF(HPROGRAM, KTIME_GR,KLAYER_GR,HTYP_GR,                   &
                                            PUNIF_OM_GR, PUNIF_CLAY_GR, PUNIF_SAND_GR, PUNIF_LAI_GR,&
                                            HFNAM_OM_GR, HFNAM_CLAY_GR, HFNAM_SAND_GR, HFNAM_LAI_GR,&
                                            HFTYP_OM_GR, HFTYP_CLAY_GR, HFTYP_SAND_GR, HFTYP_LAI_GR )
 CHARACTER(LEN=6),                INTENT(IN)    :: HPROGRAM     ! Type of program
INTEGER,                         INTENT(OUT)   :: KTIME_GR
INTEGER,                         INTENT(OUT)   :: KLAYER_GR
 CHARACTER(LEN=5),                INTENT(OUT)   :: HTYP_GR
REAL,DIMENSION(:),               INTENT(OUT)   :: PUNIF_OM_GR
REAL,DIMENSION(:),               INTENT(OUT)   :: PUNIF_CLAY_GR
REAL,DIMENSION(:),               INTENT(OUT)   :: PUNIF_SAND_GR
REAL,DIMENSION(:),               INTENT(OUT)   :: PUNIF_LAI_GR
 CHARACTER(LEN=28),DIMENSION(:),  INTENT(OUT)   :: HFNAM_OM_GR
 CHARACTER(LEN=28),DIMENSION(:),  INTENT(OUT)   :: HFNAM_CLAY_GR
 CHARACTER(LEN=28),DIMENSION(:),  INTENT(OUT)   :: HFNAM_SAND_GR
 CHARACTER(LEN=28),DIMENSION(:),  INTENT(OUT)   :: HFNAM_LAI_GR
 CHARACTER(LEN=6),DIMENSION(:),   INTENT(OUT)   :: HFTYP_OM_GR
 CHARACTER(LEN=6),DIMENSION(:),   INTENT(OUT)   :: HFTYP_CLAY_GR
 CHARACTER(LEN=6),DIMENSION(:),   INTENT(OUT)   :: HFTYP_SAND_GR
 CHARACTER(LEN=6),DIMENSION(:),   INTENT(OUT)   :: HFTYP_LAI_GR
END SUBROUTINE READ_NAM_PGD_TEB_GREENROOF

END INTERFACE
END MODULE MODI_READ_NAM_PGD_TEB_GREENROOF
