!depfile:prep_snow_buffer.F90
MODULE MODI_PREP_SNOW_BUFFER 
INTERFACE
SUBROUTINE PREP_SNOW_BUFFER (G, U, HPROGRAM,HSURF,KLUOUT,KLAYER,PFIELD)
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_TYPE_DATE_SURF
TYPE(GRID_t), INTENT(INOUT) :: G
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
CHARACTER(LEN=6),   INTENT(IN)   :: HPROGRAM  ! program calling surf. schemes
CHARACTER(LEN=10),  INTENT(IN)   :: HSURF     ! type of field
INTEGER,            INTENT(IN)   :: KLUOUT    ! logical unit of output listing
INTEGER,            INTENT(IN)  :: KLAYER        ! Number of layer of output snow scheme
REAL,DIMENSION(:,:,:), POINTER   :: PFIELD    ! field to interpolate horizontally
INTEGER,PARAMETER                :: IDIM2=10
END SUBROUTINE PREP_SNOW_BUFFER

END INTERFACE
END MODULE MODI_PREP_SNOW_BUFFER 
