!depfile:default_crocus.F90
MODULE MODI_DEFAULT_CROCUS
INTERFACE
      SUBROUTINE DEFAULT_CROCUS(HSNOWDRIFT,OSNOWDRIFT_SUBLIM,OSNOW_ABS_ZENITH,&
                 HSNOWMETAMO,HSNOWRAD,OATMORAD,OSNOWSYTRON,HSNOWFALL,HSNOWCOND,HSNOWHOLD,&
                 HSNOWCOMP,HSNOWZREF, OSNOWCOMPACT_BOOL, OSNOWMAK_BOOL, &
                 OPRODSNOWMAK, OSNOWMAK_PROP, OSNOWTILLER, OSELF_PROD)  
CHARACTER(*), INTENT(OUT)     :: HSNOWDRIFT
LOGICAL, INTENT(OUT)          :: OSNOWDRIFT_SUBLIM
LOGICAL, INTENT(OUT)          :: OSNOW_ABS_ZENITH
LOGICAL, INTENT(OUT)          :: OATMORAD
LOGICAL, INTENT(OUT)          :: OSNOWSYTRON
CHARACTER(*), INTENT(OUT) :: HSNOWMETAMO,HSNOWRAD,HSNOWFALL, HSNOWCOND, HSNOWHOLD, HSNOWCOMP, HSNOWZREF!added HSNOWFALL HSNOWHOLD and HSNOWCOND bber>
LOGICAL, INTENT(OUT)                :: OSNOWCOMPACT_BOOL
LOGICAL, DIMENSION(:), INTENT(OUT)  :: OPRODSNOWMAK
LOGICAL, INTENT(OUT)                :: OSNOWMAK_BOOL
LOGICAL, INTENT(OUT)                :: OSNOWMAK_PROP
LOGICAL, INTENT(OUT)                :: OSNOWTILLER
LOGICAL, INTENT(OUT)                :: OSELF_PROD
END SUBROUTINE DEFAULT_CROCUS

END INTERFACE
END MODULE MODI_DEFAULT_CROCUS
