!depfile:trip_nearest.F90
MODULE MODI_TRIP_NEAREST
INTERFACE
      SUBROUTINE TRIP_NEAREST(KNI,KCODE,PLON,PLAT,PFIELD)
INTEGER,                 INTENT(IN)     :: KNI      ! 
INTEGER,DIMENSION(KNI),  INTENT(INOUT)  :: KCODE    ! code for each point
REAL,   DIMENSION(KNI),  INTENT(IN)      :: PLON      ! x of each grid mesh.
REAL,   DIMENSION(KNI),  INTENT(IN)      :: PLAT      ! y of each grid mesh.
REAL,   DIMENSION(KNI),  INTENT(INOUT)   :: PFIELD  ! pgd field on grid mesh.
END SUBROUTINE TRIP_NEAREST

END INTERFACE
END MODULE MODI_TRIP_NEAREST
