!depfile:close_trip_namelist.F90
MODULE MODI_CLOSE_TRIP_NAMELIST
INTERFACE
      SUBROUTINE CLOSE_TRIP_NAMELIST(KLUNAM)
INTEGER, INTENT(IN)  :: KLUNAM   ! logical unit of namelist
END SUBROUTINE CLOSE_TRIP_NAMELIST

END INTERFACE
END MODULE MODI_CLOSE_TRIP_NAMELIST
