!depfile:open_namelist_asc.F90
MODULE MODI_OPEN_NAMELIST_ASC
INTERFACE
      SUBROUTINE OPEN_NAMELIST_ASC(HPROGRAM,KLUNAM,HFILE)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(OUT) :: KLUNAM   ! logical unit of namelist
 CHARACTER(LEN=28), INTENT(IN)  :: HFILE ! ASCII file to open
END SUBROUTINE OPEN_NAMELIST_ASC

END INTERFACE
END MODULE MODI_OPEN_NAMELIST_ASC
