!depfile:put_zsn.F90
MODULE MODI_PUT_ZS_n 
INTERFACE
      SUBROUTINE PUT_ZS_n (F, IS, S, U, TOP, W, HPROGRAM,KI,PZS)
USE MODD_FLAKE_n, ONLY : FLAKE_t
USE MODD_ISBA_n, ONLY : ISBA_S_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(FLAKE_t), INTENT(INOUT) :: F
TYPE(ISBA_S_t), INTENT(INOUT) :: IS
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
TYPE(WATFLUX_t), INTENT(INOUT) :: W
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
INTEGER,             INTENT(IN)  :: KI      ! horizontal dim. of cover
REAL, DIMENSION(KI), INTENT(IN)  :: PZS     ! orography
END SUBROUTINE PUT_ZS_n

END INTERFACE
END MODULE MODI_PUT_ZS_n 
