!depfile:write_surf_xios.F90
MODULE MODI_WRITE_SURF_XIOS
INTERFACE
SUBROUTINE WRITE_SURF_XIOS(HREC, HCOMMENT, KFIELD, PFIELD, OFIELD, HFIELD, PFIELD1, PFIELD2, PFIELD3, HAXIS, HAXIS2) 
 CHARACTER(LEN=*),      INTENT(IN)            :: HREC     ! name of the field 
 CHARACTER(LEN=*),      INTENT(IN)            :: HCOMMENT !
INTEGER         ,      INTENT(IN), OPTIONAL :: KFIELD   ! value
REAL            ,      INTENT(IN), OPTIONAL :: PFIELD   ! value
REAL,DIMENSION(:),     INTENT(IN), OPTIONAL :: PFIELD1  ! value
REAL,DIMENSION(:,:)   ,INTENT(IN), OPTIONAL :: PFIELD2  ! value
REAL,DIMENSION(:,:,:), INTENT(IN), OPTIONAL :: PFIELD3  ! value
LOGICAL         ,      INTENT(IN), OPTIONAL :: OFIELD   ! value
 CHARACTER(LEN=*),      INTENT(IN), OPTIONAL :: HFIELD   ! value
 CHARACTER(LEN=*) ,     INTENT(IN), OPTIONAL :: HAXIS    ! Name of 2nd dimension. Not necessary even for a 2d field
 CHARACTER(LEN=*) ,     INTENT(IN) , OPTIONAL :: HAXIS2   ! Name of 3rd dimension
END SUBROUTINE WRITE_SURF_XIOS

END INTERFACE
END MODULE MODI_WRITE_SURF_XIOS
