!depfile:stores_hvac_autosize.F90
MODULE MODI_STORES_HVAC_AUTOSIZE 
INTERFACE
      SUBROUTINE STORES_HVAC_AUTOSIZE (B, BOP, DTB)
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_t
TYPE(BEM_t), INTENT(INOUT) :: B
TYPE(BEM_OPTIONS_t), INTENT(INOUT) :: BOP
TYPE(DATA_BEM_t), INTENT(INOUT) :: DTB
END SUBROUTINE STORES_HVAC_AUTOSIZE

END INTERFACE
END MODULE MODI_STORES_HVAC_AUTOSIZE 
