!depfile:circumsolar_rad.F90
MODULE MODI_CIRCUMSOLAR_RAD
INTERFACE
SUBROUTINE CIRCUMSOLAR_RAD(PDIR_SW, PSCA_SW, PZENITH, PF1_o_B)
REAL, DIMENSION(:), INTENT(IN) :: PDIR_SW ! direct radiation
REAL, DIMENSION(:), INTENT(IN) :: PSCA_SW ! scattered radiation
REAL, DIMENSION(:), INTENT(IN) :: PZENITH ! solar zenith angle
REAL, DIMENSION(:), INTENT(OUT) :: PF1_o_B ! coef
END SUBROUTINE CIRCUMSOLAR_RAD

END INTERFACE
END MODULE MODI_CIRCUMSOLAR_RAD
