!depfile:read_namelists_topd.F90
MODULE MODI_READ_NAMELISTS_TOPD
INTERFACE
SUBROUTINE READ_NAMELISTS_TOPD(HPROGRAM)
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE READ_NAMELISTS_TOPD

END INTERFACE
END MODULE MODI_READ_NAMELISTS_TOPD
