!depfile:default_schemes.F90
MODULE MODI_DEFAULT_SCHEMES
INTERFACE
      SUBROUTINE DEFAULT_SCHEMES(HPROGRAM,HNATURE,HSEA,HTOWN,HWATER)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling READ_PGD
 CHARACTER(LEN=6),  INTENT(OUT) :: HNATURE  ! scheme for natural surfaces
 CHARACTER(LEN=6),  INTENT(OUT) :: HSEA     ! scheme for sea
 CHARACTER(LEN=6),  INTENT(OUT) :: HTOWN    ! scheme for towns
 CHARACTER(LEN=6),  INTENT(OUT) :: HWATER   ! scheme for inland water
END SUBROUTINE DEFAULT_SCHEMES

END INTERFACE
END MODULE MODI_DEFAULT_SCHEMES
