!depfile:write_diag_sean.F90
MODULE MODI_WRITE_DIAG_SEA_n 
INTERFACE
SUBROUTINE WRITE_DIAG_SEA_n (DTCO, DUO, U, SM, HPROGRAM,HWRITE)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURFEX_n, ONLY : SEAFLUX_MODEL_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DUO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SEAFLUX_MODEL_t), INTENT(INOUT) :: SM
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HWRITE   ! 'PGD' : only physiographic fields are written
END SUBROUTINE WRITE_DIAG_SEA_n

END INTERFACE
END MODULE MODI_WRITE_DIAG_SEA_n 
