!depfile:default_flake.F90
MODULE MODI_DEFAULT_FLAKE
INTERFACE
      SUBROUTINE DEFAULT_FLAKE(PTSTEP,POUT_TSTEP,OSEDIMENTS,HSNOW_FLK, &
        HFLK_FLUX,HFLK_ALB,OSKINTEMP)  
REAL,             INTENT(OUT) :: PTSTEP     ! time step for run
REAL,             INTENT(OUT) :: POUT_TSTEP ! time step for writing
LOGICAL,          INTENT(OUT) :: OSEDIMENTS 
LOGICAL,          INTENT(OUT) :: OSKINTEMP 
CHARACTER(LEN=3), INTENT(OUT) :: HSNOW_FLK
CHARACTER(LEN=5), INTENT(OUT) :: HFLK_FLUX
CHARACTER(LEN=4), INTENT(OUT) :: HFLK_ALB
END SUBROUTINE DEFAULT_FLAKE

END INTERFACE
END MODULE MODI_DEFAULT_FLAKE
