!depfile:hydro_glacier.F90
MODULE MODI_HYDRO_GLACIER 
INTERFACE
      SUBROUTINE HYDRO_GLACIER (PTSTEP, PSR, PEK, PICEFLUX)
USE MODD_ISBA_n, ONLY : ISBA_PE_t
REAL, INTENT(IN)                     :: PTSTEP
REAL, DIMENSION(:), INTENT(IN)       :: PSR
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
REAL, DIMENSION(:), INTENT(OUT)      :: PICEFLUX
END SUBROUTINE HYDRO_GLACIER

END INTERFACE
END MODULE MODI_HYDRO_GLACIER 
