!depfile:init_io_surf_lfin.F90
MODULE MODI_INIT_IO_SURF_LFI_n 
INTERFACE
      SUBROUTINE INIT_IO_SURF_LFI_n (DTCO, U, &
                                     HMASK,HACTION)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),  INTENT(IN)  :: HMASK    
 CHARACTER(LEN=5),  INTENT(IN)  :: HACTION    
END SUBROUTINE INIT_IO_SURF_LFI_n

END INTERFACE
END MODULE MODI_INIT_IO_SURF_LFI_n 
