!depfile:hydro_veg.F90
MODULE MODI_HYDRO_VEG
INTERFACE
      SUBROUTINE HYDRO_VEG(HRAIN, PTSTEP, PMUF, PRR, PLEV, PLETR,    &
                              PVEG, PPSNV, PWR, PWRMAX, PPG, PDRIP,    &
                              PRRVEG, PLVTT  )    
 CHARACTER(LEN=*),     INTENT(IN)   :: HRAIN   ! Rainfall spatial distribution
REAL, INTENT(IN)                    :: PTSTEP
REAL, DIMENSION(:), INTENT(IN)    :: PRR,  PLEV, PLETR, PMUF, PLVTT
REAL, DIMENSION(:), INTENT(IN)    :: PVEG, PWRMAX
REAL, DIMENSION(:), INTENT(IN)    :: PPSNV
REAL, DIMENSION(:), INTENT(INOUT) :: PWR
REAL, DIMENSION(:), INTENT(OUT)   :: PPG,PDRIP
REAL, DIMENSION(:), INTENT(OUT)   :: PRRVEG  
END SUBROUTINE HYDRO_VEG

END INTERFACE
END MODULE MODI_HYDRO_VEG
