!depfile:outer_product.F90
MODULE MODI_OUTER_PRODUCT
INTERFACE
SUBROUTINE OUTER_PRODUCT(KENS,KX,KY,PX,PY,PA,PC,OPB_CORRELATIONS,HVAR,HOBS)
INTEGER, INTENT(IN) :: KENS, KX, KY
LOGICAL, INTENT(IN) :: OPB_CORRELATIONS
CHARACTER(LEN=3), DIMENSION(KX), INTENT(IN) :: HVAR
CHARACTER(LEN=3), DIMENSION(KY), INTENT(IN) :: HOBS
REAL, DIMENSION(KX,KENS), INTENT(IN) :: PX
REAL, DIMENSION(KY,KENS), INTENT(IN) :: PY
REAL, DIMENSION(KX,KY),  INTENT(OUT) :: PA
REAL, DIMENSION(KY,KY),  INTENT(OUT) :: PC
END SUBROUTINE OUTER_PRODUCT

END INTERFACE
END MODULE MODI_OUTER_PRODUCT
