!depfile:init_write_txt.F90
MODULE MODI_INIT_WRITE_TXT 
INTERFACE
      SUBROUTINE INIT_WRITE_TXT (HSELECT, HREC,OWFL)
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
 CHARACTER(LEN=12),   INTENT(IN)     :: HREC    
LOGICAL,             INTENT(INOUT)  :: OWFL
END SUBROUTINE INIT_WRITE_TXT

END INTERFACE
END MODULE MODI_INIT_WRITE_TXT 
