!depfile:lfiget_luout.F90
MODULE MODI_LFIGET_LUOUT
INTERFACE
      SUBROUTINE LFIGET_LUOUT(HPROGRAM,KLUOUT)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling GROUND
INTEGER,           INTENT(OUT) :: KLUOUT   ! Logical unit of output listing
END SUBROUTINE LFIGET_LUOUT

END INTERFACE
END MODULE MODI_LFIGET_LUOUT
