!depfile:trip_oasis_init.F90
MODULE MODI_TRIP_OASIS_INIT
INTERFACE
SUBROUTINE TRIP_OASIS_INIT(OOASIS,OXIOS,KLOCAL_COMM,PRUNTIME,LPREP)
LOGICAL, INTENT(OUT)           :: OOASIS      ! key to use OASIS
LOGICAL, INTENT(OUT)           :: OXIOS       ! key to use XIOS
INTEGER, INTENT(OUT)           :: KLOCAL_COMM ! value of local communicator
REAL   , INTENT(OUT), OPTIONAL :: PRUNTIME    ! total simulated time (s)
LOGICAL, INTENT(IN),  OPTIONAL :: LPREP
END SUBROUTINE TRIP_OASIS_INIT

END INTERFACE
END MODULE MODI_TRIP_OASIS_INIT
