!depfile:write_cover_tex_isba_par.F90
MODULE MODI_WRITE_COVER_TEX_ISBA_PAR 
INTERFACE
      SUBROUTINE WRITE_COVER_TEX_ISBA_PAR (DTCO, HALBEDO, OTR_ML, &
                                           KPATCH,KLAYER,HISBA,HPHOTO,PSOILGRID)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_TYPE_DATE_SURF
USE MODD_DATA_COVER_PAR, ONLY : JPCOVER, NVEGTYPE
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
 CHARACTER(LEN=*), INTENT(IN) :: HALBEDO
LOGICAL, INTENT(IN) :: OTR_ML
INTEGER,          INTENT(IN) :: KPATCH! number of patch
INTEGER,          INTENT(IN) :: KLAYER! number of soil layers
 CHARACTER(LEN=*), INTENT(IN) :: HISBA ! type of soil (Force-Restore OR Diffusion)
 CHARACTER(LEN=*), INTENT(IN) :: HPHOTO! type of photosynthesis
REAL, DIMENSION(:),INTENT(IN) :: PSOILGRID ! reference grid for DIF
END SUBROUTINE WRITE_COVER_TEX_ISBA_PAR

END INTERFACE
END MODULE MODI_WRITE_COVER_TEX_ISBA_PAR 
