!depfile:control_water_budget_topd.F90
MODULE MODI_CONTROL_WATER_BUDGET_TOPD 
INTERFACE
      SUBROUTINE CONTROL_WATER_BUDGET_TOPD (IO, S, U, PWGM, PWG, PDG, PMESH_SIZE, PAVG_MESH_SIZE, PWSAT)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_S_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
REAL, DIMENSION(:,:), INTENT(IN)    :: PWGM
REAL, DIMENSION(:,:), INTENT(INOUT) :: PWG
REAL, DIMENSION(:,:), INTENT(IN)    :: PDG
REAL, DIMENSION(:),   INTENT(IN)    :: PMESH_SIZE
REAL,                 INTENT(IN)    :: PAVG_MESH_SIZE
REAL, DIMENSION(:),   INTENT(IN)    :: PWSAT
END SUBROUTINE CONTROL_WATER_BUDGET_TOPD

END INTERFACE
END MODULE MODI_CONTROL_WATER_BUDGET_TOPD 
