!depfile:pgd_chemistry.F90
MODULE MODI_PGD_CHEMISTRY 
INTERFACE
      SUBROUTINE PGD_CHEMISTRY (CHE, DTCO, UG, U, USS, &
                                HPROGRAM,OCH_EMIS)
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
LOGICAL,             INTENT(OUT)   :: OCH_EMIS     ! emission flag
END SUBROUTINE PGD_CHEMISTRY

END INTERFACE
END MODULE MODI_PGD_CHEMISTRY 
