!depfile:get_date_ol.F90
MODULE MODI_GET_DATE_OL
INTERFACE
      SUBROUTINE GET_DATE_OL(TPTIME,PTSTEP,HDATE)
USE MODD_TYPE_DATE_SURF, ONLY: DATE_TIME
TYPE(DATE_TIME), INTENT(IN)      :: TPTIME      ! current date and time
REAL,            INTENT(IN)      :: PTSTEP
 CHARACTER(LEN=*), INTENT(OUT)    :: HDATE
END SUBROUTINE GET_DATE_OL

END INTERFACE
END MODULE MODI_GET_DATE_OL
