!depfile:allocate_gr_snow.F90
MODULE MODI_ALLOCATE_GR_SNOW
INTERFACE
      SUBROUTINE ALLOCATE_GR_SNOW(TPSNOW,KLU)
USE MODD_TYPE_SNOW
TYPE(SURF_SNOW), INTENT(INOUT)             :: TPSNOW
INTEGER, INTENT(IN)                        :: KLU
END SUBROUTINE ALLOCATE_GR_SNOW

END INTERFACE
END MODULE MODI_ALLOCATE_GR_SNOW
