!depfile:close_namelist_fa.F90
MODULE MODI_CLOSE_NAMELIST_FA
INTERFACE
      SUBROUTINE CLOSE_NAMELIST_FA(HPROGRAM,KLUNAM)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KLUNAM   ! logical unit of namelist
END SUBROUTINE CLOSE_NAMELIST_FA

END INTERFACE
END MODULE MODI_CLOSE_NAMELIST_FA
