!depfile:trip_gw_buffer_tank.F90
MODULE MODI_TRIP_GW_BUFFER_TANK
INTERFACE
      SUBROUTINE TRIP_GW_BUFFER_TANK(PTSTEP,OPRINT,PAREA,OMASK_GW,PGROUND_STO,PGROUND_STO2,     &
                                     PDRAIN,PTAUG,PGOUT,PGSTO_ALL,PGSTO2_ALL,PGIN_ALL,PGOUT_ALL )  
REAL, INTENT(IN)                     :: PTSTEP
LOGICAL, INTENT(IN)                  :: OPRINT   !Printable budget key 
REAL,    DIMENSION(:,:), INTENT(IN)  :: PAREA      ! Grid-cell area    [m²]
LOGICAL, DIMENSION(:,:), INTENT(IN)  :: OMASK_GW   !Groundwater mask
REAL, DIMENSION(:,:), INTENT(IN)     :: PDRAIN, PTAUG
REAL, DIMENSION(:,:), INTENT(IN   )  :: PGROUND_STO
REAL, DIMENSION(:,:), INTENT(INOUT)  :: PGROUND_STO2
REAL, DIMENSION(:,:), INTENT(OUT)    :: PGOUT
REAL,                 INTENT(OUT)    :: PGSTO_ALL,PGSTO2_ALL,PGIN_ALL,PGOUT_ALL
END SUBROUTINE TRIP_GW_BUFFER_TANK

END INTERFACE
END MODULE MODI_TRIP_GW_BUFFER_TANK
