!depfile:reproj_diag_isban.F90
MODULE MODI_REPROJ_DIAG_ISBA_n 
INTERFACE
SUBROUTINE REPROJ_DIAG_ISBA_n (DK, DEK, DMK, PEK, OSURF_BUDGET, OSURF_EVAP_BUDGET, &
                               OWATER_BUDGET, OSURF_MISC_BUDGET, OPROSNOW, OSNOWSYTRON, &
                               OMEB_PATCH, PSLOPECOS )  
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_ISBA_n, ONLY : ISBA_PE_t
TYPE(DIAG_t), INTENT(INOUT) :: DK
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEK
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
LOGICAL, INTENT(IN) :: OSURF_BUDGET
LOGICAL, INTENT(IN) :: OSURF_EVAP_BUDGET 
LOGICAL, INTENT(IN) :: OWATER_BUDGET 
LOGICAL, INTENT(IN) :: OSURF_MISC_BUDGET
LOGICAL, INTENT(IN) :: OPROSNOW
LOGICAL, INTENT(IN) :: OSNOWSYTRON
LOGICAL, INTENT(IN) :: OMEB_PATCH
REAL, DIMENSION(:), INTENT(IN) :: PSLOPECOS ! cosine of the slope for Crocus
END SUBROUTINE REPROJ_DIAG_ISBA_n

END INTERFACE
END MODULE MODI_REPROJ_DIAG_ISBA_n 
