!depfile:write_pgd_surf_atmn.F90
MODULE MODI_WRITE_PGD_SURF_ATM_n 
INTERFACE
      SUBROUTINE WRITE_PGD_SURF_ATM_n (YSC, HPROGRAM)
USE MODD_SURFEX_n, ONLY : SURFEX_t
TYPE(SURFEX_t), INTENT(INOUT) :: YSC
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE WRITE_PGD_SURF_ATM_n

END INTERFACE
END MODULE MODI_WRITE_PGD_SURF_ATM_n 
