!depfile:close_namelist_ol.F90
MODULE MODI_CLOSE_NAMELIST_OL
INTERFACE
      SUBROUTINE CLOSE_NAMELIST_OL(HPROGRAM,KLUNAM)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KLUNAM   ! logical unit of namelist
END SUBROUTINE CLOSE_NAMELIST_OL

END INTERFACE
END MODULE MODI_CLOSE_NAMELIST_OL
