!depfile:write_diag_ch_aggr.F90
MODULE MODI_WRITE_DIAG_CH_AGGR_n 
INTERFACE
      SUBROUTINE WRITE_DIAG_CH_AGGR_n (DTCO, HSELECT, U, CHE, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE WRITE_DIAG_CH_AGGR_n

END INTERFACE
END MODULE MODI_WRITE_DIAG_CH_AGGR_n 
