!depfile:write_naturen.F90
MODULE MODI_WRITE_NATURE_n 
INTERFACE
      SUBROUTINE WRITE_NATURE_n (DTCO, HSELECT, OSNOWDIMNC, U, IM, NDST,HPROGRAM,HWRITE,OLAND_USE)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURFEX_n, ONLY : ISBA_MODEL_t
USE MODD_DST_n, ONLY : DST_NP_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT 
LOGICAL, INTENT(IN) :: OSNOWDIMNC
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(ISBA_MODEL_t), INTENT(INOUT) :: IM
TYPE(DST_NP_t), INTENT(INOUT) :: NDST
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),    INTENT(IN)  :: HWRITE    ! 'PREP' : does not write SBL XUNDEF fields
LOGICAL,             INTENT(IN)  :: OLAND_USE !
END SUBROUTINE WRITE_NATURE_n

END INTERFACE
END MODULE MODI_WRITE_NATURE_n 
