!depfile:default_sso.F90
MODULE MODI_DEFAULT_SSO
INTERFACE
      SUBROUTINE DEFAULT_SSO(HROUGH,PFRACZ0,PCOEFBE,ODSV,ODSH,ODSL)
 CHARACTER(LEN=4), INTENT(OUT) :: HROUGH
REAL, INTENT(OUT) :: PFRACZ0
REAL, INTENT(OUT) :: PCOEFBE
LOGICAL, INTENT(OUT) :: ODSV, ODSH, ODSL
END SUBROUTINE DEFAULT_SSO

END INTERFACE
END MODULE MODI_DEFAULT_SSO
