!depfile:write_cover_tex_cover.F90
MODULE MODI_WRITE_COVER_TEX_COVER
INTERFACE
      SUBROUTINE WRITE_COVER_TEX_COVER
END SUBROUTINE WRITE_COVER_TEX_COVER

END INTERFACE
END MODULE MODI_WRITE_COVER_TEX_COVER
