!depfile:surfex_deallo.F90
MODULE MODI_SURFEX_DEALLO
INTERFACE
SUBROUTINE SURFEX_DEALLO(YDSURFEX)
USE MODD_SURFEX_n, ONLY : SURFEX_t
TYPE (SURFEX_t), INTENT(INOUT) :: YDSURFEX
END SUBROUTINE SURFEX_DEALLO

END INTERFACE
END MODULE MODI_SURFEX_DEALLO
