!depfile:write_cover_tex_start.F90
MODULE MODI_WRITE_COVER_TEX_START
INTERFACE
      SUBROUTINE WRITE_COVER_TEX_START(HPROGRAM)
 CHARACTER(LEN=6),                INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE WRITE_COVER_TEX_START

END INTERFACE
END MODULE MODI_WRITE_COVER_TEX_START
