!depfile:pack_grid.F90
MODULE MODI_PACK_GRID
INTERFACE
      SUBROUTINE PACK_GRID(KMASK,HGRID1,HGRID2,PGRID_PAR1,PGRID_PAR2)
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK      ! mask used
 CHARACTER(LEN=10),     INTENT(IN) :: HGRID1     ! input grid type
 CHARACTER(LEN=10),     INTENT(OUT):: HGRID2     ! output grid type
REAL,    DIMENSION(:), POINTER    :: PGRID_PAR1 ! parameters of input grid
REAL,    DIMENSION(:), POINTER    :: PGRID_PAR2 ! parameters of output packed grid
END SUBROUTINE PACK_GRID

END INTERFACE
END MODULE MODI_PACK_GRID
