!depfile:read_teb_patch.F90
MODULE MODI_READ_TEB_PATCH 
INTERFACE
      SUBROUTINE READ_TEB_PATCH (HFILEPGD,HFILEPGDTYPE,KVERSION,KBUGFIX,KTEB_PATCH,HDIR)
 CHARACTER(LEN=28),  INTENT(IN)  :: HFILEPGD     ! name of file
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILEPGDTYPE ! type of file
INTEGER, INTENT(IN) :: KVERSION
INTEGER, INTENT(IN) :: KBUGFIX
INTEGER,            INTENT(OUT) :: KTEB_PATCH! number of TEB patches
 CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: HDIR
END SUBROUTINE READ_TEB_PATCH

END INTERFACE
END MODULE MODI_READ_TEB_PATCH 
