!depfile:read_namelists_idealn.F90
MODULE MODI_READ_NAMELISTS_IDEAL_n 
INTERFACE
SUBROUTINE READ_NAMELISTS_IDEAL_n (DGO, HPROGRAM)
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE READ_NAMELISTS_IDEAL_n

END INTERFACE
END MODULE MODI_READ_NAMELISTS_IDEAL_n 
