!depfile:writesurf_sson.F90
MODULE MODI_WRITESURF_SSO_n 
INTERFACE
      SUBROUTINE WRITESURF_SSO_n (HSELECT, USS, HPROGRAM)
USE MODD_SSO_n, ONLY : SSO_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE WRITESURF_SSO_n

END INTERFACE
END MODULE MODI_WRITESURF_SSO_n 
