!depfile:write_dst_conf.F90
MODULE MODI_WRITE_DST_CONF
INTERFACE
      SUBROUTINE WRITE_DST_CONF(KLUDES,HEMISPARAM)
INTEGER,          INTENT(IN) :: KLUDES     ! logical unit
 CHARACTER(LEN=5), INTENT(IN) :: HEMISPARAM ! Reference to paper where emission parameterization is proposed
END SUBROUTINE WRITE_DST_CONF

END INTERFACE
END MODULE MODI_WRITE_DST_CONF
