!depfile:get_offline_conf.F90
MODULE MODI_GET_OFFLINE_CONF
INTERFACE
      SUBROUTINE GET_OFFLINE_CONF(PTSTEP_OUTPUT)
REAL, INTENT(OUT) :: PTSTEP_OUTPUT ! time step of output time series
END SUBROUTINE GET_OFFLINE_CONF

END INTERFACE
END MODULE MODI_GET_OFFLINE_CONF
