!depfile:add_noise.F90
MODULE MODI_ADD_NOISE
INTERFACE
SUBROUTINE ADD_NOISE(PADDTIMECORR,PASSIM_WINH,PWHITE_NOISE,PRED_NOISE)
REAL, INTENT(IN) ::  PADDTIMECORR
REAL, INTENT(IN) ::  PWHITE_NOISE
REAL, INTENT(IN) :: PASSIM_WINH
REAL, INTENT(INOUT) :: PRED_NOISE
END SUBROUTINE ADD_NOISE

END INTERFACE
END MODULE MODI_ADD_NOISE
