!depfile:restart_coupl_topd.F90
MODULE MODI_RESTART_COUPL_TOPD 
INTERFACE
SUBROUTINE RESTART_COUPL_TOPD (UG, KR_NATURE, HPROGRAM,KI)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
INTEGER, DIMENSION(:), INTENT(IN) :: KR_NATURE
 CHARACTER(LEN=6), INTENT(IN)         :: HPROGRAM ! program calling surf. schemes
INTEGER,          INTENT(IN)         :: KI       ! Surfex grid dimension
END SUBROUTINE RESTART_COUPL_TOPD

END INTERFACE
END MODULE MODI_RESTART_COUPL_TOPD 
