!depfile:error_read_surf_fa.F90
MODULE MODI_ERROR_READ_SURF_FA
INTERFACE
SUBROUTINE ERROR_READ_SURF_FA(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(OUT):: KRESP
END SUBROUTINE ERROR_READ_SURF_FA

END INTERFACE
END MODULE MODI_ERROR_READ_SURF_FA
