!depfile:read_pre_surfa_dat_conf.F90
MODULE MODI_READ_PRE_SURFA_DAT_CONF
INTERFACE
      SUBROUTINE READ_PRE_SURFA_DAT_CONF(HPROGRAM,KLUOUT,TPTIME)
USE MODD_TYPE_DATE_SURF
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM    ! program calling ISBA
INTEGER,           INTENT(IN)  :: KLUOUT      ! logical unit of output listing
TYPE (DATE_TIME),  INTENT(OUT) :: TPTIME      ! current date and time
END SUBROUTINE READ_PRE_SURFA_DAT_CONF

END INTERFACE
END MODULE MODI_READ_PRE_SURFA_DAT_CONF
