!depfile:read_surf_atm_conf.F90
MODULE MODI_READ_SURF_ATM_CONF
INTERFACE
      SUBROUTINE READ_SURF_ATM_CONF(HPROGRAM)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling GROUND
END SUBROUTINE READ_SURF_ATM_CONF

END INTERFACE
END MODULE MODI_READ_SURF_ATM_CONF
