!depfile:read_default_dst.F90
MODULE MODI_READ_DEFAULT_DST
INTERFACE
      SUBROUTINE READ_DEFAULT_DST(HPROGRAM)
 CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM ! program calling DST
END SUBROUTINE READ_DEFAULT_DST

END INTERFACE
END MODULE MODI_READ_DEFAULT_DST
