!depfile:read_pgd_seafluxn.F90
MODULE MODI_READ_PGD_SEAFLUX_n 
INTERFACE
      SUBROUTINE READ_PGD_SEAFLUX_n (DTCO, DTS, SG, S, U, UG, GCP, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_t
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_GRID_CONF_PROJ_n, ONLY : GRID_CONF_PROJ_t
USE MODD_TYPE_DATE_SURF
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_SEAFLUX_t), INTENT(INOUT) :: DTS
TYPE(GRID_t), INTENT(INOUT) :: SG
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(GRID_CONF_PROJ_t),INTENT(INOUT) :: GCP
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
END SUBROUTINE READ_PGD_SEAFLUX_n

END INTERFACE
END MODULE MODI_READ_PGD_SEAFLUX_n 
