!depfile:average1_ldb.F90
MODULE MODI_AVERAGE1_LDB
INTERFACE
      SUBROUTINE AVERAGE1_LDB(UG,KLUOUT,KNBLINES,PLAT,PLON,PVALUE,HTYPE,PNODATA)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
INTEGER,                 INTENT(IN)    :: KLUOUT
INTEGER,                 INTENT(IN)    :: KNBLINES
REAL, DIMENSION(:),      INTENT(IN)    :: PLAT    ! latitude of the point to add
REAL, DIMENSION(:),      INTENT(IN)    :: PLON    ! longitude of the point to add
REAL, DIMENSION(:),      INTENT(IN)    :: PVALUE  ! value of the point to add
 CHARACTER(LEN=1),       INTENT(IN)    :: HTYPE
REAL, OPTIONAL, INTENT(IN) :: PNODATA
END SUBROUTINE AVERAGE1_LDB

END INTERFACE
END MODULE MODI_AVERAGE1_LDB
