!depfile:write_cover_tex_water.F90
MODULE MODI_WRITE_COVER_TEX_WATER
INTERFACE
      SUBROUTINE WRITE_COVER_TEX_WATER
END SUBROUTINE WRITE_COVER_TEX_WATER

END INTERFACE
END MODULE MODI_WRITE_COVER_TEX_WATER
