!depfile:latlontoxy1d.F90
MODULE MODI_LATLONTOXY1D
INTERFACE
       SUBROUTINE LATLONTOXY1D(PLAT0,PLON0,PRPK,PBETA,PLATOR,PLONOR, &
                                 PXHATM,PYHATM,PLAT,PLON,KN,PRADIUS)  
INTEGER,             INTENT(IN) :: KN
REAL,                INTENT(IN) :: PLAT0
REAL,                INTENT(IN) :: PLON0
REAL,                INTENT(IN) :: PRPK
REAL,                INTENT(IN) :: PBETA
REAL,                INTENT(IN) :: PLATOR ! Latitude of the origine point
REAL,                INTENT(IN) :: PLONOR ! Longitude of the origine point
REAL, DIMENSION(KN), INTENT(IN) :: PLAT,PLON
REAL, DIMENSION(KN), INTENT(OUT):: PXHATM,PYHATM
REAL, OPTIONAL,      INTENT(IN) :: PRADIUS
END SUBROUTINE LATLONTOXY1D

END INTERFACE
END MODULE MODI_LATLONTOXY1D
