!depfile:default_prep_teb_garden.F90
MODULE MODI_DEFAULT_PREP_TEB_GARDEN
INTERFACE
      SUBROUTINE DEFAULT_PREP_TEB_GARDEN
END SUBROUTINE DEFAULT_PREP_TEB_GARDEN

END INTERFACE
END MODULE MODI_DEFAULT_PREP_TEB_GARDEN
