!depfile:conserv_global_mass.F90
MODULE MODI_CONSERV_GLOBAL_MASS 
INTERFACE
      SUBROUTINE CONSERV_GLOBAL_MASS (DTCO, U, NP, NPE, PMESH_SIZE, KPATCH, &
                                      ILUOUT, PZDG, PZDG_OLD, HNAME, PFIELD_OLD)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_ISBA_n, ONLY : ISBA_NP_t, ISBA_NPE_t, ISBA_P_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
TYPE(ISBA_NPE_t), INTENT(INOUT) :: NPE
REAL, DIMENSION(:), INTENT(IN) :: PMESH_SIZE
INTEGER, INTENT(IN) :: KPATCH
INTEGER,                        INTENT(IN   ) :: ILUOUT
REAL, DIMENSION(:,:,:),         INTENT(IN   ) :: PFIELD_OLD,PZDG,PZDG_OLD
 CHARACTER(LEN=3), INTENT(IN) :: HNAME
END SUBROUTINE CONSERV_GLOBAL_MASS

END INTERFACE
END MODULE MODI_CONSERV_GLOBAL_MASS 
