!depfile:default_data_cover.F90
MODULE MODI_DEFAULT_DATA_COVER
INTERFACE
SUBROUTINE DEFAULT_DATA_COVER(PDATA_TOWN,PDATA_NATURE,PDATA_WATER,PDATA_SEA,&
         PDATA_Z0_TOWN,PDATA_BLD_HEIGHT,PDATA_WALL_O_HOR,PDATA_BLD,PDATA_GARDEN,&
         PDATA_ALB_ROOF,PDATA_ALB_ROAD,PDATA_ALB_WALL,PDATA_EMIS_ROOF,&
         PDATA_EMIS_ROAD,PDATA_EMIS_WALL,PDATA_HC_ROOF,PDATA_TC_ROOF,&
         PDATA_D_ROOF,PDATA_HC_ROAD,PDATA_TC_ROAD,PDATA_D_ROAD,&
         PDATA_HC_WALL,PDATA_TC_WALL,PDATA_D_WALL,PDATA_H_TRAFFIC,&
         PDATA_LE_TRAFFIC,PDATA_H_INDUSTRY,PDATA_LE_INDUSTRY,&
         PDATA_VEGTYPE,PDATA_H_TREE,PDATA_WATSUP,PDATA_IRRIG,&
         PDATA_ROOT_DEPTH,PDATA_GROUND_DEPTH,PDATA_DICE,TPDATA_SEED,&
         TPDATA_REAP)
USE MODD_TYPE_DATE_SURF  
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_TOWN
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_NATURE
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_WATER
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_SEA
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_Z0_TOWN
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_BLD_HEIGHT
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_WALL_O_HOR
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_BLD
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_GARDEN
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_ALB_ROOF
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_ALB_ROAD
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_ALB_WALL
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_EMIS_ROOF
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_EMIS_ROAD
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_EMIS_WALL
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_HC_ROOF
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_TC_ROOF
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_D_ROOF
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_HC_ROAD
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_TC_ROAD
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_D_ROAD
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_HC_WALL
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_TC_WALL
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_D_WALL
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_H_TRAFFIC
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_LE_TRAFFIC
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_H_INDUSTRY
REAL, DIMENSION(:), INTENT(INOUT), OPTIONAL :: PDATA_LE_INDUSTRY
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_VEGTYPE
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_H_TREE
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_WATSUP
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_IRRIG
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_ROOT_DEPTH
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_GROUND_DEPTH
REAL, DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: PDATA_DICE
TYPE(DATE_TIME), DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: TPDATA_SEED
TYPE(DATE_TIME), DIMENSION(:,:), INTENT(INOUT), OPTIONAL :: TPDATA_REAP
END SUBROUTINE DEFAULT_DATA_COVER

END INTERFACE
END MODULE MODI_DEFAULT_DATA_COVER
