!depfile:average_tsurf.F90
MODULE MODI_AVERAGE_TSURF
INTERFACE
      SUBROUTINE AVERAGE_TSURF(PFRAC_TILE, PTSURF_TILE, PTSURF)  
REAL, DIMENSION(:,:), INTENT(IN) :: PFRAC_TILE  ! Fraction in a mesh-area of 
REAL, DIMENSION(:,:), INTENT(IN) :: PTSURF_TILE ! surface effective temperature (K)
REAL, DIMENSION(:),   INTENT(OUT):: PTSURF      ! surface effective temperature   (K)
END SUBROUTINE AVERAGE_TSURF

END INTERFACE
END MODULE MODI_AVERAGE_TSURF
