!depfile:soil_temp_arp.F90
MODULE MODI_SOIL_TEMP_ARP
INTERFACE
      SUBROUTINE SOIL_TEMP_ARP(PTSTEP,PA,PB,PC,PGAMMAT,PTDEEP,PSODELX,PTG)
REAL, INTENT(IN)                   :: PTSTEP ! Model time step (s)
REAL, DIMENSION(:), INTENT(IN)     :: PA,PB,PC ! terms for the linearization of Ts(t)
REAL, DIMENSION(:), INTENT(IN)     :: PTDEEP, PGAMMAT
REAL, DIMENSION(:), INTENT (IN)     ::  PSODELX   ! Pulsation for each layer (Only used if LTEMP_ARP=True)
REAL, DIMENSION(:,:), INTENT(INOUT) :: PTG
END SUBROUTINE SOIL_TEMP_ARP

END INTERFACE
END MODULE MODI_SOIL_TEMP_ARP
