!depfile:average2_cover.F90
MODULE MODI_AVERAGE2_COVER 
INTERFACE
      SUBROUTINE AVERAGE2_COVER (U, HPROGRAM)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM      ! Type of program
END SUBROUTINE AVERAGE2_COVER

END INTERFACE
END MODULE MODI_AVERAGE2_COVER 
