!depfile:carbon_spinup.F90
MODULE MODI_CARBON_SPINUP
INTERFACE
      SUBROUTINE CARBON_SPINUP(TPTIME, IO )
USE MODD_TYPE_DATE_SURF
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
TYPE(DATE_TIME), INTENT(IN) :: TPTIME
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
END SUBROUTINE 

END INTERFACE
END MODULE MODI_CARBON_SPINUP
