!depfile:init_chemicaln.F90
MODULE MODI_INIT_CHEMICAL_n
INTERFACE
SUBROUTINE INIT_CHEMICAL_n(KLUOUT, KSV, HSV, SV, HCH_NAMES, HAER_NAMES, &
                           HDSTNAMES, HSLTNAMES     )  
USE MODD_SV_n, ONLY : SV_t
INTEGER,                          INTENT(IN) :: KLUOUT
INTEGER,                          INTENT(IN) :: KSV      ! number of scalars
 CHARACTER(LEN=6), DIMENSION(KSV), INTENT(IN) :: HSV      ! name of all scalar variables
 TYPE(SV_t), INTENT(INOUT) :: SV
 CHARACTER(LEN=6), DIMENSION(:), POINTER :: HCH_NAMES
 CHARACTER(LEN=6), DIMENSION(:), POINTER :: HAER_NAMES     
 CHARACTER(LEN=6), DIMENSION(:), POINTER, OPTIONAL :: HDSTNAMES
 CHARACTER(LEN=6), DIMENSION(:), POINTER, OPTIONAL :: HSLTNAMES
END SUBROUTINE INIT_CHEMICAL_n

END INTERFACE
END MODULE MODI_INIT_CHEMICAL_n
