!depfile:prep_grid_lonlat_reg.F90
MODULE MODI_PREP_GRID_LONLAT_REG 
INTERFACE
      SUBROUTINE PREP_GRID_LONLAT_REG (HFILETYPE,HINTERP_TYPE,KNI)
 CHARACTER(LEN=6),  INTENT(IN)    :: HFILETYPE    ! file type
 CHARACTER(LEN=6),  INTENT(OUT)   :: HINTERP_TYPE ! Grid type
INTEGER,           INTENT(OUT)   :: KNI          ! number of points
END SUBROUTINE PREP_GRID_LONLAT_REG

END INTERFACE
END MODULE MODI_PREP_GRID_LONLAT_REG 
