!depfile:window_data.F90
MODULE MODI_WINDOW_DATA
INTERFACE
SUBROUTINE WINDOW_DATA(KI, B)
USE MODD_BEM_n, ONLY : BEM_t
INTEGER,             INTENT(IN)  :: KI       ! number of points
TYPE(BEM_t), INTENT(INOUT) :: B
END SUBROUTINE WINDOW_DATA

END INTERFACE
END MODULE MODI_WINDOW_DATA
