!depfile:read_topd_header_connex.F90
MODULE MODI_READ_TOPD_HEADER_CONNEX
INTERFACE
      SUBROUTINE READ_TOPD_HEADER_CONNEX(HPROGRAM,HFILE,HFORM,KNMC)
 CHARACTER(LEN=*),  INTENT(IN)  :: HPROGRAM    !
 CHARACTER(LEN=*),  INTENT(IN)  :: HFILE       ! File to be read
 CHARACTER(LEN=*),  INTENT(IN)  :: HFORM       ! Format of the file to be read
INTEGER,           INTENT(OUT) :: KNMC     ! number of pixels in a catchment 
END SUBROUTINE READ_TOPD_HEADER_CONNEX

END INTERFACE
END MODULE MODI_READ_TOPD_HEADER_CONNEX
