!depfile:pgd_surf_atm.F90
MODULE MODI_PGD_SURF_ATM 
INTERFACE
      SUBROUTINE PGD_SURF_ATM (YSC,HPROGRAM,HFILE,HFILETYPE,OZS)
USE MODD_SURFEX_n, ONLY : SURFEX_t
TYPE(SURFEX_t), INTENT(INOUT) :: YSC
CHARACTER(LEN=6),     INTENT(IN)  :: HPROGRAM ! program calling
CHARACTER(LEN=28),    INTENT(IN)  :: HFILE    ! atmospheric file name
CHARACTER(LEN=6),     INTENT(IN)  :: HFILETYPE! atmospheric file type
LOGICAL,              INTENT(IN)  :: OZS      ! .true. if orography is imposed by atm. model
END SUBROUTINE PGD_SURF_ATM

END INTERFACE
END MODULE MODI_PGD_SURF_ATM 
