!depfile:writesurf_dummyn.F90
MODULE MODI_WRITESURF_DUMMY_n 
INTERFACE
      SUBROUTINE WRITESURF_DUMMY_n (HSELECT, DUU, HPROGRAM)
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(DUMMY_SURF_FIELDS_t), INTENT(INOUT) :: DUU
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM     ! 
END SUBROUTINE WRITESURF_DUMMY_n

END INTERFACE
END MODULE MODI_WRITESURF_DUMMY_n 
