!depfile:read_covers_param.F90
MODULE MODI_READ_COVERS_PARAM
INTERFACE
      SUBROUTINE READ_COVERS_PARAM(KFILE)
USE MODD_TYPE_DATE_SURF
INTEGER, INTENT(IN)   :: KFILE
END SUBROUTINE READ_COVERS_PARAM

END INTERFACE
END MODULE MODI_READ_COVERS_PARAM
