!depfile:prep_teb_garden_ascllv.F90
MODULE MODI_PREP_TEB_GARDEN_ASCLLV 
INTERFACE
SUBROUTINE PREP_TEB_GARDEN_ASCLLV (DTCO, UG, U, USS, &
                                   HPROGRAM,HSURF,KLUOUT,PFIELD)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=7),   INTENT(IN)  :: HSURF     ! type of field
INTEGER,            INTENT(IN)  :: KLUOUT    ! logical unit of output listing
REAL, POINTER, DIMENSION(:,:,:) :: PFIELD    ! field to interpolate horizontally
END SUBROUTINE PREP_TEB_GARDEN_ASCLLV

END INTERFACE
END MODULE MODI_PREP_TEB_GARDEN_ASCLLV 
