!depfile:put_on_all_vegtypes.F90
MODULE MODI_PUT_ON_ALL_VEGTYPES
INTERFACE
      SUBROUTINE PUT_ON_ALL_VEGTYPES(KNI,KLAYER,KPATCH,KVEGTYPE,PFIELD_PATCH,PFIELD_VEGTYPE)
INTEGER, INTENT(IN) :: KNI      ! number of points
INTEGER, INTENT(IN) :: KLAYER   ! number of layers
INTEGER, INTENT(IN) :: KPATCH   ! number of patch
INTEGER, INTENT(IN) :: KVEGTYPE ! number of vegtypes
REAL, DIMENSION(KNI,KLAYER,KPATCH  ),INTENT(IN) :: PFIELD_PATCH   ! field for each patch
REAL, DIMENSION(KNI,KLAYER,KVEGTYPE), INTENT(OUT) :: PFIELD_VEGTYPE ! field for each vegtype
END SUBROUTINE PUT_ON_ALL_VEGTYPES

END INTERFACE
END MODULE MODI_PUT_ON_ALL_VEGTYPES
