!depfile:town_presence.F90
MODULE MODI_TOWN_PRESENCE 
INTERFACE
SUBROUTINE TOWN_PRESENCE (HFILETYPE,OTEB,HDIR)
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILETYPE ! type of input file
LOGICAL,            INTENT(OUT) :: OTEB      ! TRUE if TEB data exist in the file
 CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: HDIR
END SUBROUTINE TOWN_PRESENCE

END INTERFACE
END MODULE MODI_TOWN_PRESENCE 
