!depfile:ccetr.F90
MODULE MODI_CCETR
INTERFACE
   SUBROUTINE CCETR(PXIA,PIA,PXMUS,PABC,PLAI)
REAL, INTENT(IN)               :: PABC
REAL, DIMENSION(:), INTENT(IN) :: PIA,PXMUS,PLAI
REAL, DIMENSION(:), INTENT(OUT):: PXIA
END SUBROUTINE CCETR

END INTERFACE
END MODULE MODI_CCETR
