!depfile:read_arrange_cover.F90
MODULE MODI_READ_ARRANGE_COVER 
INTERFACE
      SUBROUTINE READ_ARRANGE_COVER (&
                                     HPROGRAM,OWATER_TO_NATURE,OTOWN_TO_ROCK,HDIR)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
LOGICAL,           INTENT(OUT) :: OWATER_TO_NATURE ! T: Change Wetland treated as inland water into nature
LOGICAL,           INTENT(OUT) :: OTOWN_TO_ROCK    ! T: Change Town into Rock 
 CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: HDIR
END SUBROUTINE READ_ARRANGE_COVER

END INTERFACE
END MODULE MODI_READ_ARRANGE_COVER 
