!depfile:trip_oasis_end.F90
MODULE MODI_TRIP_OASIS_END
INTERFACE
SUBROUTINE TRIP_OASIS_END(OOASIS,OXIOS)
LOGICAL, INTENT(IN)           :: OOASIS      ! key to use OASIS
LOGICAL, INTENT(IN)           :: OXIOS       ! key to use XIOS
END SUBROUTINE TRIP_OASIS_END

END INTERFACE
END MODULE MODI_TRIP_OASIS_END
