!depfile:init_from_data_teb_vegn.F90
MODULE MODI_INIT_FROM_DATA_TEB_VEG_n 
INTERFACE
      SUBROUTINE INIT_FROM_DATA_TEB_VEG_n (DTV, K, P, PEK, KDECADE, OUPDATE, OFIX, OTIME, OALB)    
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
INTEGER,                INTENT(IN)    :: KDECADE
LOGICAL, INTENT(IN) :: OUPDATE
LOGICAL, INTENT(IN) :: OFIX
LOGICAL, INTENT(IN) :: OTIME
LOGICAL, INTENT(IN) :: OALB
TYPE(ISBA_K_t), INTENT(INOUT) :: K
TYPE(ISBA_P_t), INTENT(INOUT) :: P
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
END SUBROUTINE INIT_FROM_DATA_TEB_VEG_n

END INTERFACE
END MODULE MODI_INIT_FROM_DATA_TEB_VEG_n 
