!depfile:vegtype_grid_to_patch_grid.F90
MODULE MODI_VEGTYPE_GRID_TO_PATCH_GRID
INTERFACE
SUBROUTINE VEGTYPE_GRID_TO_PATCH_GRID(KPATCH,KNPATCH,PVEGTYPE_PATCH,PPATCH,KMASK,PFIELDOUT,PW)
INTEGER, INTENT(IN) :: KPATCH
INTEGER, INTENT(IN) :: KNPATCH
REAL, DIMENSION(:,:), INTENT(IN)   :: PVEGTYPE_PATCH
REAL, DIMENSION(:), INTENT(IN)   :: PPATCH
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
REAL, DIMENSION(:,:,:), INTENT(IN) :: PFIELDOUT
REAL, DIMENSION(:,:), INTENT(OUT) :: PW
END SUBROUTINE VEGTYPE_GRID_TO_PATCH_GRID

END INTERFACE
END MODULE MODI_VEGTYPE_GRID_TO_PATCH_GRID
