!depfile:write_file_vecmap.F90
MODULE MODI_WRITE_FILE_VECMAP
INTERFACE
      SUBROUTINE WRITE_FILE_VECMAP(PVAR,HVAR,KCAT)
REAL, DIMENSION(:),INTENT(IN) :: PVAR   ! variable to write in the file
 CHARACTER(LEN=30), INTENT(IN) :: HVAR   ! end name of the file
INTEGER,           INTENT(IN) :: KCAT   ! catchment number
END SUBROUTINE WRITE_FILE_VECMAP

END INTERFACE
END MODULE MODI_WRITE_FILE_VECMAP
