!depfile:trip_oasis_send.F90
MODULE MODI_TRIP_OASIS_SEND 
INTERFACE
SUBROUTINE TRIP_OASIS_SEND (TP, TPG, &
                            KLISTING,KLON,KLAT,PTIMEC)
USE MODD_TRIP, ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_t), INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER, INTENT(IN)               :: KLISTING
INTEGER, INTENT(IN)               :: KLON
INTEGER, INTENT(IN)               :: KLAT
REAL,    INTENT(IN)               :: PTIMEC        ! Cumulated run time step (s)
END SUBROUTINE TRIP_OASIS_SEND

END INTERFACE
END MODULE MODI_TRIP_OASIS_SEND 
