!depfile:alloc_diag_surf_atmn.F90
MODULE MODI_ALLOC_DIAG_SURF_ATM_n 
INTERFACE
      SUBROUTINE ALLOC_DIAG_SURF_ATM_n (DGO, D, DC, ND, NDC, &
                       KSIZE_FULL, TPTIME, HPROGRAM,KSW)
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_NP_t, DIAG_OPTIONS_t
USE MODD_TYPE_DATE_SURF, ONLY : DATE_TIME
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DC
TYPE(DIAG_NP_t), INTENT(INOUT) :: ND
TYPE(DIAG_NP_t), INTENT(INOUT) :: NDC
INTEGER, INTENT(IN) :: KSIZE_FULL
TYPE(DATE_TIME), INTENT(IN) :: TPTIME
 CHARACTER(LEN=6),        INTENT(IN) :: HPROGRAM  ! program calling surf. schemes
INTEGER,                 INTENT(IN) :: KSW       ! number of short-wave spectral bands
END SUBROUTINE ALLOC_DIAG_SURF_ATM_n

END INTERFACE
END MODULE MODI_ALLOC_DIAG_SURF_ATM_n 
