!depfile:hydro_snow.F90
MODULE MODI_HYDRO_SNOW
INTERFACE
      SUBROUTINE HYDRO_SNOW(OGLACIER, PTSTEP, PVEGTYPE, PSR, PLES, PMELT, TPSNOW, PPG_MELT )  
USE MODD_TYPE_SNOW, ONLY : SURF_SNOW
LOGICAL, INTENT(IN)               :: OGLACIER   ! True = Over permanent snow and ice, 
REAL, INTENT(IN)                  :: PTSTEP
REAL, DIMENSION(:,:), INTENT(IN)  :: PVEGTYPE ! fraction of each vegetation
REAL, DIMENSION(:), INTENT(IN)    :: PSR,  PLES, PMELT
TYPE(SURF_SNOW), INTENT(INOUT) :: TPSNOW
REAL, DIMENSION(:), INTENT(INOUT) :: PPG_MELT
END SUBROUTINE HYDRO_SNOW

END INTERFACE
END MODULE MODI_HYDRO_SNOW
