!depfile:read_surf_atm.F90
MODULE MODI_READ_SURF_ATM 
INTERFACE
SUBROUTINE READ_SURF_ATM     (HPROGRAM, PFIELD, KFORC_STEP, KNB, KINIT)  
REAL, DIMENSION(:,:),INTENT(INOUT) :: PFIELD
INTEGER,INTENT(IN)               :: KFORC_STEP
INTEGER,INTENT(IN)               :: KNB 
INTEGER,INTENT(IN)               :: KINIT
 CHARACTER(LEN=6)    ,INTENT(IN)  :: HPROGRAM
END SUBROUTINE READ_SURF_ATM

END INTERFACE
END MODULE MODI_READ_SURF_ATM 
