!depfile:cotwo.F90
MODULE MODI_COTWO
INTERFACE
    SUBROUTINE COTWO(PCSP, PF2, PIA, PDS, PGAMMT,               &
                     PFZERO, PEPSO, PANMAX, PGMEST, PGC, PDMAX, &
                     PAN, PGS, PRD, PLAITOP, PLAI   )  
REAL, DIMENSION(:),   INTENT(IN):: PCSP, PF2, PIA, PDS,PGAMMT
REAL, DIMENSION(:), INTENT(IN)  :: PFZERO, PEPSO, PANMAX, PGMEST, PGC, PDMAX, PLAITOP, PLAI
REAL, DIMENSION(:),  INTENT(OUT) :: PAN, PGS, PRD
END SUBROUTINE COTWO

END INTERFACE
END MODULE MODI_COTWO
