!depfile:oi_tsl.F90
MODULE MODI_OI_TSL
INTERFACE
SUBROUTINE OI_TSL(KDAT,KSSSSS,PLAT,PLON,PMU0,PMU0M,KH)
INTEGER, INTENT(IN)  :: KDAT
INTEGER, INTENT(IN)  :: KSSSSS 
REAL, INTENT(IN)     :: PLAT, PLON
REAL, INTENT(OUT)    :: PMU0, PMU0M
INTEGER, INTENT(OUT) :: KH
END SUBROUTINE OI_TSL

END INTERFACE
END MODULE MODI_OI_TSL
