!depfile:comput_cold_layers_thick.F90
MODULE MODI_COMPUT_COLD_LAYERS_THICK
INTERFACE
SUBROUTINE COMPUT_COLD_LAYERS_THICK(PDG,PTG,PALT,PFLT)
REAL, DIMENSION(:,:),  INTENT(IN)  :: PDG           ! soil layer depth
REAL, DIMENSION(:,:),  INTENT(IN)  :: PTG           ! soil temperature
REAL, DIMENSION(:),    INTENT(OUT) :: PALT          ! active layer theakness
REAL, DIMENSION(:),    INTENT(OUT) :: PFLT          ! frozen layer theakness
END SUBROUTINE COMPUT_COLD_LAYERS_THICK

END INTERFACE
END MODULE MODI_COMPUT_COLD_LAYERS_THICK
