!depfile:prep_grid_cartesian.F90
MODULE MODI_PREP_GRID_CARTESIAN 
INTERFACE
      SUBROUTINE PREP_GRID_CARTESIAN (HFILETYPE,HINTERP_TYPE,KNI)
 CHARACTER(LEN=6),  INTENT(IN)    :: HFILETYPE    ! file type
 CHARACTER(LEN=6),  INTENT(OUT)   :: HINTERP_TYPE ! Grid type
INTEGER,           INTENT(OUT)   :: KNI          ! number of points
END SUBROUTINE PREP_GRID_CARTESIAN

END INTERFACE
END MODULE MODI_PREP_GRID_CARTESIAN 
