!depfile:read_prep_file_date.F90
MODULE MODI_READ_PREP_FILE_DATE 
INTERFACE
SUBROUTINE READ_PREP_FILE_DATE (HPROGRAM,HFILE,HFILETYPE,TPTIME,KLUOUT)
USE MODD_TYPE_DATE_SURF
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=28),  INTENT(IN)  :: HFILE     ! name of file
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILETYPE ! file type
TYPE (DATE_TIME),   INTENT(OUT) :: TPTIME    ! grib date and time
INTEGER,            INTENT(IN)  :: KLUOUT    ! logical unit of output listing
END SUBROUTINE READ_PREP_FILE_DATE

END INTERFACE
END MODULE MODI_READ_PREP_FILE_DATE 
