!depfile:preps_for_meb_ebud_rad.F90
MODULE MODI_PREPS_FOR_MEB_EBUD_RAD
INTERFACE
SUBROUTINE PREPS_FOR_MEB_EBUD_RAD(PPS,                                         &
     PLAICV,PSNOWRHO,PSNOWSWE,PSNOWHEAT,PSNOWLIQ,                              &
     PSNOWTEMP,PSNOWDZ,PSCOND,PHEATCAPS,PEMISNOW,PSIGMA_F,PCHIP,               &
     PTSTEP,PSR,PTA,PVMOD,PSNOWAGE,PPERMSNOWFRAC,HSNOW_ISBA,HSNOWCOND          )
REAL                                :: PTSTEP   ! time step (s)
REAL, DIMENSION(:),   INTENT(IN)    :: PLAICV
REAL, DIMENSION(:),   INTENT(IN)    :: PPS
REAL, DIMENSION(:),   INTENT(IN)    :: PSR
REAL, DIMENSION(:),   INTENT(IN)    :: PTA
REAL, DIMENSION(:),   INTENT(IN)    :: PVMOD
REAL, DIMENSION(:),   INTENT(IN)    :: PPERMSNOWFRAC 
REAL, DIMENSION(:,:), INTENT(IN)    :: PSNOWHEAT
CHARACTER(LEN=*),     INTENT(IN)    :: HSNOW_ISBA
CHARACTER(LEN=*),     INTENT(IN)    :: HSNOWCOND
REAL, DIMENSION(:,:), INTENT(INOUT) :: PSNOWSWE, PSNOWAGE, PSNOWRHO
REAL, DIMENSION(:),   INTENT(OUT)   :: PSIGMA_F, PCHIP
REAL, DIMENSION(:),   INTENT(OUT)   :: PEMISNOW
REAL, DIMENSION(:,:), INTENT(OUT)   :: PSNOWDZ, PSCOND, PHEATCAPS, PSNOWTEMP, PSNOWLIQ
END SUBROUTINE PREPS_FOR_MEB_EBUD_RAD

END INTERFACE
END MODULE MODI_PREPS_FOR_MEB_EBUD_RAD
