!depfile:read_assim_conf.F90
MODULE MODI_READ_ASSIM_CONF
INTERFACE
      SUBROUTINE READ_ASSIM_CONF(HPROGRAM)
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE READ_ASSIM_CONF

END INTERFACE
END MODULE MODI_READ_ASSIM_CONF
