!depfile:writesurf_covern.F90
MODULE MODI_WRITESURF_COVER_n 
INTERFACE
      SUBROUTINE WRITESURF_COVER_n (HSELECT, U, HPROGRAM)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE WRITESURF_COVER_n

END INTERFACE
END MODULE MODI_WRITESURF_COVER_n 
