!depfile:read_pgd_watfluxn.F90
MODULE MODI_READ_PGD_WATFLUX_n 
INTERFACE
      SUBROUTINE READ_PGD_WATFLUX_n (DTCO, U, UG, WG, W, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
USE MODD_TYPE_DATE_SURF
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(GRID_t), INTENT(INOUT) :: WG
TYPE(WATFLUX_t), INTENT(INOUT) :: W
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
END SUBROUTINE READ_PGD_WATFLUX_n

END INTERFACE
END MODULE MODI_READ_PGD_WATFLUX_n 
