!depfile:convert_cover_frac.F90
MODULE MODI_CONVERT_COVER_FRAC 
INTERFACE
      SUBROUTINE CONVERT_COVER_FRAC (DTCO, &
                                        PCOVER, OCOVER,           &
                                         PSEA,PNATURE,PTOWN,PWATER   )  
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
REAL, DIMENSION(:,:), INTENT(IN)    :: PCOVER
LOGICAL, DIMENSION(:), INTENT(IN)   :: OCOVER
REAL, DIMENSION(:),   INTENT(OUT)   :: PSEA
REAL, DIMENSION(:),   INTENT(OUT)   :: PNATURE
REAL, DIMENSION(:),   INTENT(OUT)   :: PTOWN
REAL, DIMENSION(:),   INTENT(OUT)   :: PWATER
END SUBROUTINE CONVERT_COVER_FRAC

END INTERFACE
END MODULE MODI_CONVERT_COVER_FRAC 
