!depfile:read_nam_pgd_isba_meb.F90
MODULE MODI_READ_NAM_PGD_ISBA_MEB
INTERFACE
      SUBROUTINE READ_NAM_PGD_ISBA_MEB(HPROGRAM, KLUOUT, OMEB_PATCH, OFORC_MEASURE, &
                      OMEB_LITTER, OMEB_GNDRES)  
CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM      ! Type of program
INTEGER,             INTENT(IN)    :: KLUOUT
LOGICAL, DIMENSION(:), INTENT(OUT) :: OMEB_PATCH
LOGICAL              , INTENT(OUT) :: OFORC_MEASURE
LOGICAL              , INTENT(OUT) :: OMEB_LITTER
LOGICAL              , INTENT(OUT) :: OMEB_GNDRES
END SUBROUTINE READ_NAM_PGD_ISBA_MEB

END INTERFACE
END MODULE MODI_READ_NAM_PGD_ISBA_MEB
