!depfile:read_nam_trip_grid.F90
MODULE MODI_READ_NAM_TRIP_GRID 
INTERFACE
SUBROUTINE READ_NAM_TRIP_GRID (TPG, &
                               KLISTING)
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER, INTENT(IN) :: KLISTING
END SUBROUTINE READ_NAM_TRIP_GRID

END INTERFACE
END MODULE MODI_READ_NAM_TRIP_GRID 
