!depfile:ini_var_from_patch.F90
MODULE MODI_INI_VAR_FROM_PATCH 
INTERFACE
      SUBROUTINE INI_VAR_FROM_PATCH (DTCO, UG, U, NP, NPE, KPATCH, &
                           HPROGRAM,KLUOUT,HNAME,KPTS,KLAYER,KLAYER2,PDEF)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_ISBA_n, ONLY : ISBA_NP_t, ISBA_NPE_t, ISBA_P_t, ISBA_PE_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
TYPE(ISBA_NPE_t), INTENT(INOUT) :: NPE
INTEGER, INTENT(IN) :: KPATCH
 CHARACTER(LEN=6),            INTENT(IN) :: HPROGRAM  ! host model
INTEGER,                      INTENT(IN) :: KLUOUT
INTEGER,                      INTENT(IN) :: KPTS
 CHARACTER(LEN=*),            INTENT(IN) :: HNAME
INTEGER, INTENT(IN), OPTIONAL :: KLAYER
INTEGER, INTENT(IN), OPTIONAL :: KLAYER2
REAL, DIMENSION(:), OPTIONAL, INTENT(IN) :: PDEF 
END SUBROUTINE INI_VAR_FROM_PATCH

END INTERFACE
END MODULE MODI_INI_VAR_FROM_PATCH 
