!depfile:init_topd_pgd.F90
MODULE MODI_INIT_TOPD_PGD
INTERFACE
      SUBROUTINE INIT_TOPD_PGD(HPROGRAM)
 CHARACTER(LEN=*), INTENT(IN) :: HPROGRAM    !
END SUBROUTINE INIT_TOPD_PGD

END INTERFACE
END MODULE MODI_INIT_TOPD_PGD
