!depfile:read_sso_canopyn.F90
MODULE MODI_READ_SSO_CANOPY_n 
INTERFACE
      SUBROUTINE READ_SSO_CANOPY_n (DTCO, SB, U, HPROGRAM,HINIT)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_CANOPY_n, ONLY : CANOPY_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(CANOPY_t), INTENT(INOUT) :: SB
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
 CHARACTER(LEN=3),  INTENT(IN)  :: HINIT    ! choice of fields to initialize
END SUBROUTINE READ_SSO_CANOPY_n

END INTERFACE
END MODULE MODI_READ_SSO_CANOPY_n 
