!depfile:get_zsn.F90
MODULE MODI_GET_ZS_n 
INTERFACE
      SUBROUTINE GET_ZS_n (U, &
                           HPROGRAM,KI,PZS)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
INTEGER,             INTENT(IN)  :: KI      ! horizontal dim. of cover
REAL, DIMENSION(KI), INTENT(OUT) :: PZS     ! orography
END SUBROUTINE GET_ZS_n

END INTERFACE
END MODULE MODI_GET_ZS_n 
