!depfile:error_read_surf_nc.F90
MODULE MODI_ERROR_READ_SURF_NC
INTERFACE
SUBROUTINE ERROR_READ_SURF_NC(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(IN):: KRESP
END SUBROUTINE ERROR_READ_SURF_NC

END INTERFACE
END MODULE MODI_ERROR_READ_SURF_NC
