!depfile:read_pgd_schemes.F90
MODULE MODI_READ_PGD_SCHEMES
INTERFACE
      SUBROUTINE READ_PGD_SCHEMES(HPROGRAM,HNATURE,HSEA,HTOWN,HWATER)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling READ_PGD
 CHARACTER(LEN=6),  INTENT(OUT) :: HNATURE  ! scheme for natural surfaces
 CHARACTER(LEN=6),  INTENT(OUT) :: HSEA     ! scheme for sea
 CHARACTER(LEN=6),  INTENT(OUT) :: HTOWN    ! scheme for towns
 CHARACTER(LEN=6),  INTENT(OUT) :: HWATER   ! scheme for inland water
END SUBROUTINE READ_PGD_SCHEMES

END INTERFACE
END MODULE MODI_READ_PGD_SCHEMES
