!depfile:update_data_fracn.F90
MODULE MODI_UPDATE_DATA_FRAC_n
INTERFACE
      SUBROUTINE UPDATE_DATA_FRAC_n(PDATA_NATURE,PDATA_TOWN,PDATA_GARDEN,OGARDEN, &
                                    PDATA_BLD, PDATA_WALL_O_HOR                   )
REAL, DIMENSION(:), INTENT(IN)  :: PDATA_NATURE
REAL, DIMENSION(:), INTENT(IN)  :: PDATA_TOWN
REAL, DIMENSION(:), INTENT(IN)  :: PDATA_GARDEN
LOGICAL,            INTENT(IN)  :: OGARDEN
REAL, DIMENSION(:), INTENT(IN)  :: PDATA_BLD
REAL, DIMENSION(:), INTENT(IN)  :: PDATA_WALL_O_HOR
END SUBROUTINE UPDATE_DATA_FRAC_n

END INTERFACE
END MODULE MODI_UPDATE_DATA_FRAC_n
