!depfile:init_vegn.F90
MODULE MODI_INIT_VEG_n
INTERFACE
SUBROUTINE INIT_VEG_n(IO, KK, PK, PEK, DTV, &
                      OSURF_DIAG_ALBEDO, PDIR_ALB, PSCA_ALB, PEMIS_OUT, PTSRAD )  
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_TYPE_SNOW
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
LOGICAL, INTENT(OUT) :: OSURF_DIAG_ALBEDO
REAL, DIMENSION(:,:), INTENT(OUT) :: PDIR_ALB
REAL, DIMENSION(:,:), INTENT(OUT) :: PSCA_ALB
REAL, DIMENSION(:), INTENT(OUT) :: PEMIS_OUT
REAL, DIMENSION(:), INTENT(OUT) :: PTSRAD
END SUBROUTINE INIT_VEG_n

END INTERFACE
END MODULE MODI_INIT_VEG_n
