!depfile:put_zs_sean.F90
MODULE MODI_PUT_ZS_SEA_n 
INTERFACE
      SUBROUTINE PUT_ZS_SEA_n (S, &
                               HPROGRAM,KI,PZS)
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
INTEGER,             INTENT(IN)  :: KI      ! horizontal dim. of cover
REAL, DIMENSION(KI), INTENT(IN)  :: PZS     ! orography
END SUBROUTINE PUT_ZS_SEA_n

END INTERFACE
END MODULE MODI_PUT_ZS_SEA_n 
