!depfile:init_types_param.F90
MODULE MODI_INIT_TYPES_PARAM
INTERFACE
      SUBROUTINE INIT_TYPES_PARAM
USE MODD_TYPE_DATE_SURF
END SUBROUTINE INIT_TYPES_PARAM

END INTERFACE
END MODULE MODI_INIT_TYPES_PARAM
