!depfile:read_namelists_watfluxn.F90
MODULE MODI_READ_NAMELISTS_WATFLUX_n 
INTERFACE
SUBROUTINE READ_NAMELISTS_WATFLUX_n (WM, HPROGRAM,HINIT)
USE MODD_SURFEX_n, ONLY : WATFLUX_MODEL_t
TYPE(WATFLUX_MODEL_t), INTENT(INOUT) :: WM
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HINIT     ! choice of fields to initialize
END SUBROUTINE READ_NAMELISTS_WATFLUX_n

END INTERFACE
END MODULE MODI_READ_NAMELISTS_WATFLUX_n 
