!depfile:pgd_topo_index.F90
MODULE MODI_PGD_TOPO_INDEX 
INTERFACE
      SUBROUTINE PGD_TOPO_INDEX (DTCO, UG, U, USS, S, OCTI, &
                                 HPROGRAM,KLU,HCTI,HCTIFILETYPE,OIMP_CTI)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
USE MODD_ISBA_n, ONLY : ISBA_S_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
TYPE(ISBA_S_t), INTENT(INOUT) :: S
LOGICAL, INTENT(INOUT) :: OCTI
CHARACTER(LEN=6),     INTENT(IN)  :: HPROGRAM     ! program calling
INTEGER,              INTENT(IN)  :: KLU          ! number of nature points
CHARACTER(LEN=28),    INTENT(IN)  :: HCTI         ! topographic index file name
CHARACTER(LEN=6),     INTENT(IN)  :: HCTIFILETYPE ! topographic index file type
LOGICAL,              INTENT(IN)  :: OIMP_CTI     ! .true. if topographic index statistics is imposed
END SUBROUTINE PGD_TOPO_INDEX

END INTERFACE
END MODULE MODI_PGD_TOPO_INDEX 
