!depfile:split_grid.F90
MODULE MODI_SPLIT_GRID
INTERFACE
      SUBROUTINE SPLIT_GRID(UG, U, HPROGRAM,KGRID_PAR,PGRID_PAR,KHALO)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),     INTENT(IN)  :: HPROGRAM ! program calling
INTEGER, OPTIONAL,           INTENT(INOUT)  :: KGRID_PAR ! size of PGRID_PAR pointer
REAL, DIMENSION(:), OPTIONAL, POINTER, INTENT(INOUT) :: PGRID_PAR ! parameters defining this grid
INTEGER,            INTENT(IN), OPTIONAL   :: KHALO ! size of the Halo
END SUBROUTINE SPLIT_GRID

END INTERFACE
END MODULE MODI_SPLIT_GRID
