!depfile:close_namelist_lfi.F90
MODULE MODI_CLOSE_NAMELIST_LFI
INTERFACE
      SUBROUTINE CLOSE_NAMELIST_LFI(HPROGRAM,KLUNAM)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KLUNAM   ! logical unit of namelist
END SUBROUTINE CLOSE_NAMELIST_LFI

END INTERFACE
END MODULE MODI_CLOSE_NAMELIST_LFI
