!depfile:get_grid_coord_ign.F90
MODULE MODI_GET_GRID_COORD_IGN
INTERFACE
      SUBROUTINE GET_GRID_COORD_IGN(KGRID_PAR,KL,PGRID_PAR,PX,PY)
INTEGER,                    INTENT(IN)  :: KGRID_PAR  ! size of PGRID_PAR
INTEGER,                    INTENT(IN)  :: KL         ! number of points
REAL, DIMENSION(KGRID_PAR), INTENT(IN)  :: PGRID_PAR  ! parameters defining this grid
REAL, DIMENSION(KL),        INTENT(OUT) :: PX         ! X (m)
REAL, DIMENSION(KL),        INTENT(OUT) :: PY         ! Y (m)
END SUBROUTINE GET_GRID_COORD_IGN

END INTERFACE
END MODULE MODI_GET_GRID_COORD_IGN
