!depfile:read_seaicen.F90
MODULE MODI_READ_SEAICE_n 
INTERFACE
      SUBROUTINE READ_SEAICE_n (G, S, HPROGRAM,KLU,KLUOUT)
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
TYPE(GRID_t), INTENT(INOUT) :: G
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
INTEGER,           INTENT(IN)  :: KLU      ! number of sea patch point
INTEGER,           INTENT(IN)  :: KLUOUT
END SUBROUTINE READ_SEAICE_n

END INTERFACE
END MODULE MODI_READ_SEAICE_n 
