!depfile:write_diag_surf_atmn.F90
MODULE MODI_WRITE_DIAG_SURF_ATM_n 
INTERFACE
SUBROUTINE WRITE_DIAG_SURF_ATM_n (YSC,HPROGRAM,HWRITE)
USE MODD_SURFEX_n, ONLY : SURFEX_t
TYPE(SURFEX_t), INTENT(INOUT) :: YSC
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HWRITE    ! 'PGD' : only physiographic fields are written
END SUBROUTINE WRITE_DIAG_SURF_ATM_n

END INTERFACE
END MODULE MODI_WRITE_DIAG_SURF_ATM_n 
