!depfile:init_sytron_table.F90
MODULE MODI_INIT_SYTRON_TABLE
INTERFACE
SUBROUTINE INIT_SYTRON_TABLE(USS,PZS,KI,PLAT,PLON)
USE MODD_SSO_n, ONLY : SSO_t
TYPE(SSO_t), INTENT(IN) :: USS
INTEGER,              INTENT(IN)  :: KI        ! number of points
REAL, DIMENSION(KI),   INTENT(IN) :: PZS      ! orography of this MPI thread (or total domain if Open MP)
REAL,DIMENSION(:),INTENT(IN):: PLAT ! latitudes
REAL,DIMENSION(:),INTENT(IN):: PLON ! longitudes
END SUBROUTINE INIT_SYTRON_TABLE

END INTERFACE
END MODULE MODI_INIT_SYTRON_TABLE
