!depfile:writesurf_cpl_gcmn.F90
MODULE MODI_WRITESURF_CPL_GCM_n 
INTERFACE
      SUBROUTINE WRITESURF_CPL_GCM_n (HSELECT, U, HPROGRAM)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
END SUBROUTINE WRITESURF_CPL_GCM_n

END INTERFACE
END MODULE MODI_WRITESURF_CPL_GCM_n 
