!depfile:ol_alloc_atm.F90
MODULE MODI_OL_ALLOC_ATM
INTERFACE
SUBROUTINE OL_ALLOC_ATM(KNI,KBANDS,KSCAL)
INTEGER,            INTENT(IN)  :: KNI       ! grid dimension
INTEGER,            INTENT(IN)  :: KBANDS    ! grid dimension
INTEGER,            INTENT(IN)  :: KSCAL     ! grid dimension
END SUBROUTINE OL_ALLOC_ATM

END INTERFACE
END MODULE MODI_OL_ALLOC_ATM
