!depfile:writesurf_seaflux_confn.F90
MODULE MODI_WRITESURF_SEAFLUX_CONF_n 
INTERFACE
      SUBROUTINE WRITESURF_SEAFLUX_CONF_n (CHS, DGO, DGMSI, O, S, HPROGRAM)
USE MODD_CH_SEAFLUX_n, ONLY : CH_SEAFLUX_t
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_MISC_SEAICE_n, ONLY : DIAG_MISC_SEAICE_t
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
TYPE(CH_SEAFLUX_t), INTENT(INOUT) :: CHS
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DGO
TYPE(DIAG_MISC_SEAICE_t), INTENT(INOUT) :: DGMSI
TYPE(OCEAN_t), INTENT(INOUT) :: O
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM ! program calling SEAFLUX
END SUBROUTINE WRITESURF_SEAFLUX_CONF_n

END INTERFACE
END MODULE MODI_WRITESURF_SEAFLUX_CONF_n 
