!depfile:ch_aer_velgrav1d.F90
MODULE MODI_CH_AER_VELGRAV1D
INTERFACE
SUBROUTINE CH_AER_VELGRAV1D(PSIG, PRG, PTA, PRHODREF, PRHOP, PMU, PVGK,PDPK, PVGG,PDPG)
REAL, DIMENSION(:,:), INTENT(OUT) :: PVGK,PDPK
REAL, DIMENSION(:),   INTENT(OUT) :: PMU
REAL, DIMENSION(:,:), INTENT(OUT) :: PVGG
REAL, DIMENSION(:,:), INTENT(OUT) :: PDPG
REAL, DIMENSION(:,:), INTENT(IN)    :: PRHOP
REAL, DIMENSION(:,:), INTENT(IN)    :: PSIG, PRG
REAL, DIMENSION(:),   INTENT(IN)    :: PTA, PRHODREF
END SUBROUTINE CH_AER_VELGRAV1D

END INTERFACE
END MODULE MODI_CH_AER_VELGRAV1D
