!depfile:read_default_teb_vegn.F90
MODULE MODI_READ_DEFAULT_TEB_VEG_n 
INTERFACE
      SUBROUTINE READ_DEFAULT_TEB_VEG_n (CHT, IO, HPROGRAM)
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling ISBA
END SUBROUTINE READ_DEFAULT_TEB_VEG_n

END INTERFACE
END MODULE MODI_READ_DEFAULT_TEB_VEG_n 
