!depfile:read_watfluxn.F90
MODULE MODI_READ_WATFLUX_n 
INTERFACE
      SUBROUTINE READ_WATFLUX_n (DTCO, U, W, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(WATFLUX_t), INTENT(INOUT) :: W
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
END SUBROUTINE READ_WATFLUX_n

END INTERFACE
END MODULE MODI_READ_WATFLUX_n 
