!depfile:open_aux_io_surf_asc.F90
MODULE MODI_OPEN_AUX_IO_SURF_ASC 
INTERFACE
      SUBROUTINE OPEN_AUX_IO_SURF_ASC (&
                                       HFILE,HFILETYPE,HMASK,HDIR)
 CHARACTER(LEN=28), INTENT(IN)  :: HFILE     ! file name
 CHARACTER(LEN=6), INTENT(IN)  :: HFILETYPE ! main program
 CHARACTER(LEN=6), INTENT(IN)  :: HMASK
 CHARACTER(LEN=1), INTENT(IN) :: HDIR
END SUBROUTINE OPEN_AUX_IO_SURF_ASC

END INTERFACE
END MODULE MODI_OPEN_AUX_IO_SURF_ASC 
