!depfile:hydro_soil.F90
MODULE MODI_HYDRO_SOIL
INTERFACE
      SUBROUTINE HYDRO_SOIL(IO, KK, PK, PEK, DMK, PTSTEP,  &
                            PLETR, PLEG, PPG, PEVAPCOR, PD_G3, &
                            PWSAT, PWFC, PDWGI1, PDWGI2, PLEGI,&
                            PWG3, PRUNOFF, PDRAIN, PWWILT )  
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMK
REAL, INTENT(IN)                  :: PTSTEP
REAL, DIMENSION(:), INTENT(IN)    :: PLETR, PLEG, PPG, PEVAPCOR
REAL, DIMENSION(:), INTENT(IN)    :: PD_G3, PWSAT, PWFC
REAL, DIMENSION(:), INTENT(IN)    :: PDWGI1, PDWGI2, PLEGI
REAL, DIMENSION(:), INTENT(INOUT) :: PWG3
REAL, DIMENSION(:), INTENT(OUT)   :: PRUNOFF, PDRAIN
REAL, DIMENSION(:), INTENT(IN)    :: PWWILT
END SUBROUTINE HYDRO_SOIL

END INTERFACE
END MODULE MODI_HYDRO_SOIL
