!depfile:prep_sst_init.F90
MODULE MODI_PREP_SST_INIT 
INTERFACE
    SUBROUTINE PREP_SST_INIT (DTS, TPTIME, KSX, PSST)
USE MODD_TYPE_DATE_SURF, ONLY : DATE_TIME
USE MODD_DATA_SEAFLUX_n, ONLY : DATA_SEAFLUX_t
USE MODD_TYPE_DATE_SURF
TYPE(DATA_SEAFLUX_t), INTENT(INOUT) :: DTS
TYPE(DATE_TIME), INTENT(IN) :: TPTIME
INTEGER, INTENT(INOUT) :: KSX
REAL,   DIMENSION(:), INTENT(INOUT) :: PSST    ! sst
END SUBROUTINE PREP_SST_INIT

END INTERFACE
END MODULE MODI_PREP_SST_INIT 
