!depfile:write_diag_inland_watern.F90
MODULE MODI_WRITE_DIAG_INLAND_WATER_n 
INTERFACE
SUBROUTINE WRITE_DIAG_INLAND_WATER_n (DTCO, DUO, U, WM, FM, HPROGRAM,HWRITE)
USE MODD_SURFEX_n, ONLY : FLAKE_MODEL_t
USE MODD_SURFEX_n, ONLY : WATFLUX_MODEL_t
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DUO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(WATFLUX_MODEL_t), INTENT(INOUT) :: WM
TYPE(FLAKE_MODEL_t), INTENT(INOUT) :: FM
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HWRITE   ! 'PGD' : only physiographic fields are written
END SUBROUTINE WRITE_DIAG_INLAND_WATER_n

END INTERFACE
END MODULE MODI_WRITE_DIAG_INLAND_WATER_n 
