!depfile:make_lcover.F90
MODULE MODI_MAKE_LCOVER
INTERFACE
      SUBROUTINE MAKE_LCOVER(OCOVER)
LOGICAL, DIMENSION(:), INTENT(INOUT) :: OCOVER
END SUBROUTINE MAKE_LCOVER

END INTERFACE
END MODULE MODI_MAKE_LCOVER
