!depfile:fix_meb_veg.F90
MODULE MODI_FIX_MEB_VEG 
INTERFACE
      SUBROUTINE FIX_MEB_VEG (DTV, KDIM, OMEB_PATCH, KPATCH)
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
INTEGER, INTENT(IN) :: KDIM
LOGICAL, DIMENSION(:), INTENT(IN) :: OMEB_PATCH
INTEGER, INTENT(IN) :: KPATCH
END SUBROUTINE FIX_MEB_VEG

END INTERFACE
END MODULE MODI_FIX_MEB_VEG 
