!depfile:latlonmask_cartesian.F90
MODULE MODI_LATLONMASK_CARTESIAN
INTERFACE
      SUBROUTINE LATLONMASK_CARTESIAN(KGRID_PAR,PGRID_PAR,OLATLONMASK)
INTEGER,                       INTENT(IN)  :: KGRID_PAR   ! size of PGRID_PAR
REAL,    DIMENSION(KGRID_PAR), INTENT(IN)  :: PGRID_PAR   ! parameters defining this grid
LOGICAL, DIMENSION(720,360),   INTENT(OUT) :: OLATLONMASK ! mask where data are to be read
END SUBROUTINE LATLONMASK_CARTESIAN

END INTERFACE
END MODULE MODI_LATLONMASK_CARTESIAN
