!depfile:refresh_pgdwork.F90
MODULE MODI_REFRESH_PGDWORK
INTERFACE
      SUBROUTINE REFRESH_PGDWORK(HSUBROUTINE)
 CHARACTER(LEN=6),  INTENT(IN) :: HSUBROUTINE   ! Name of the subroutine to call
END SUBROUTINE REFRESH_PGDWORK

END INTERFACE
END MODULE MODI_REFRESH_PGDWORK
