!depfile:diag_inland_watern.F90
MODULE MODI_DIAG_INLAND_WATER_n 
INTERFACE
SUBROUTINE DIAG_INLAND_WATER_n (DLO, DL, DLC, FM, WM, HWATER, &
                                HPROGRAM, DUP, DUPC, KMASK       )
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_SURFEX_n, ONLY : FLAKE_MODEL_t, WATFLUX_MODEL_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DLO
TYPE(DIAG_t), INTENT(INOUT) :: DL
TYPE(DIAG_t), INTENT(INOUT) :: DLC
TYPE(FLAKE_MODEL_t), INTENT(INOUT) :: FM
TYPE(WATFLUX_MODEL_t), INTENT(INOUT) :: WM
 CHARACTER(LEN=*), INTENT(IN) :: HWATER
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! program calling surf. schemes
TYPE(DIAG_t), INTENT(INOUT) :: DUP
TYPE(DIAG_t), INTENT(INOUT) :: DUPC
INTEGER, DIMENSION(:), INTENT(IN) :: KMASK
END SUBROUTINE DIAG_INLAND_WATER_n

END INTERFACE
END MODULE MODI_DIAG_INLAND_WATER_n 
