!depfile:prep_seaflux_unif.F90
MODULE MODI_PREP_SEAFLUX_UNIF
INTERFACE
SUBROUTINE PREP_SEAFLUX_UNIF(KLUOUT,HSURF,PFIELD)
INTEGER,            INTENT(IN)  :: KLUOUT    ! output listing logical unit
CHARACTER(LEN=9),   INTENT(IN)  :: HSURF     ! type of field
REAL, POINTER, DIMENSION(:,:)   :: PFIELD    ! field to interpolate horizontally
END SUBROUTINE PREP_SEAFLUX_UNIF

END INTERFACE
END MODULE MODI_PREP_SEAFLUX_UNIF
