!depfile:latlon_grid.F90
MODULE MODI_LATLON_GRID
INTERFACE
      SUBROUTINE LATLON_GRID(G,KL,PDIR)
USE MODD_SFX_GRID_n, ONLY : GRID_t
TYPE(GRID_t), INTENT(INOUT) :: G
INTEGER,            INTENT(IN)  :: KL         ! number of points
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PDIR ! direction of main grid Y axis (deg. from N, clockwise)
END SUBROUTINE LATLON_GRID

END INTERFACE
END MODULE MODI_LATLON_GRID
