!depfile:diag_seaflux_initn.F90
MODULE MODI_DIAG_SEAFLUX_INIT_n 
INTERFACE
      SUBROUTINE DIAG_SEAFLUX_INIT_n (DOC, DGO, D, DC, OREAD_BUDGETC, S, &
                                      HPROGRAM,KLU,KSW)
USE MODD_DIAG_OCEAN_n, ONLY : DIAG_OCEAN_t
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_SEAFLUX_n, ONLY : SEAFLUX_t
TYPE(DIAG_OCEAN_t), INTENT(INOUT) :: DOC
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DC
LOGICAL, INTENT(IN) :: OREAD_BUDGETC
TYPE(SEAFLUX_t), INTENT(INOUT) :: S
INTEGER, INTENT(IN) :: KLU   ! size of arrays
INTEGER, INTENT(IN) :: KSW   ! number of SW spectral bands
 CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
END SUBROUTINE DIAG_SEAFLUX_INIT_n

END INTERFACE
END MODULE MODI_DIAG_SEAFLUX_INIT_n 
