!depfile:wet_leaves_frac.F90
MODULE MODI_WET_LEAVES_FRAC
INTERFACE
    SUBROUTINE WET_LEAVES_FRAC(PWRM, PVEG, PWRMAX_CF, PZ0, PLAI, PWRMAX, PDELTA)
REAL, DIMENSION(:), INTENT(IN)   :: PWRM
REAL, DIMENSION(:), INTENT(IN)   :: PVEG, PWRMAX_CF, PLAI, PZ0
REAL, DIMENSION(:), INTENT(OUT)  :: PWRMAX
REAL, DIMENSION(:), INTENT(OUT)  :: PDELTA
END SUBROUTINE WET_LEAVES_FRAC

END INTERFACE
END MODULE MODI_WET_LEAVES_FRAC
