!depfile:read_nam_gridtype.F90
MODULE MODI_READ_NAM_GRIDTYPE
INTERFACE
      SUBROUTINE READ_NAM_GRIDTYPE(GCP,PGRID_FULL_PAR,KDIM_FULL,HPROGRAM,HGRID,KGRID_PAR,PGRID_PAR,KL,HDIR)
USE MODD_GRID_CONF_PROJ_n, ONLY :GRID_CONF_PROJ_t
TYPE(GRID_CONF_PROJ_t),INTENT(INOUT) :: GCP
REAL, DIMENSION(:), POINTER :: PGRID_FULL_PAR
INTEGER, INTENT(IN) :: KDIM_FULL
 CHARACTER(LEN=6),  INTENT(IN)   :: HPROGRAM   ! program calling the surface
 CHARACTER(LEN=10), INTENT(IN)   :: HGRID      ! grid type
INTEGER,           INTENT(OUT)  :: KGRID_PAR  ! size of PGRID_PAR
REAL, DIMENSION(:), POINTER     :: PGRID_PAR  ! parameters defining this grid
INTEGER,           INTENT(OUT)  :: KL         ! number of points
 CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: HDIR
END SUBROUTINE READ_NAM_GRIDTYPE

END INTERFACE
END MODULE MODI_READ_NAM_GRIDTYPE
