!depfile:prep_ctrl_flake.F90
MODULE MODI_PREP_CTRL_FLAKE
INTERFACE
SUBROUTINE PREP_CTRL_FLAKE(DGO, KLUOUT,OWATER_PROFILE)  
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
INTEGER,  INTENT(IN)    :: KLUOUT             ! unit number
LOGICAL,  INTENT(INOUT) :: OWATER_PROFILE     !
END SUBROUTINE PREP_CTRL_FLAKE

END INTERFACE
END MODULE MODI_PREP_CTRL_FLAKE
