!depfile:prep_ocean_mercatorvergrid.F90
MODULE MODI_PREP_OCEAN_MERCATORVERGRID
INTERFACE
    SUBROUTINE PREP_OCEAN_MERCATORVERGRID(HPROGRAM,OUNIF)
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
LOGICAL, INTENT(IN) :: OUNIF
END SUBROUTINE PREP_OCEAN_MERCATORVERGRID

END INTERFACE
END MODULE MODI_PREP_OCEAN_MERCATORVERGRID
