!depfile:read_prep_teb_date_conf.F90
MODULE MODI_READ_PREP_TEB_DATE_CONF
INTERFACE
      SUBROUTINE READ_PREP_TEB_DATE_CONF(HPROGRAM,KLUOUT,TPTIME)
USE MODD_TYPE_DATE_SURF
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM    ! program calling TEB
INTEGER,           INTENT(IN)  :: KLUOUT      ! logical unit of output listing
TYPE (DATE_TIME),  INTENT(OUT) :: TPTIME      ! current date and time
END SUBROUTINE READ_PREP_TEB_DATE_CONF

END INTERFACE
END MODULE MODI_READ_PREP_TEB_DATE_CONF
