!depfile:trip_forcing.F90
MODULE MODI_TRIP_FORCING 
INTERFACE
SUBROUTINE TRIP_FORCING (TPG, &
                         KLUOUT,KLON,KLAT,KNB_TSTEP_RUN, &
                        PDRAIN,PRUNOFF,PSRC_FLOOD       )
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER,                INTENT(IN)  :: KLUOUT
INTEGER,                INTENT(IN)  :: KLON
INTEGER,                INTENT(IN)  :: KLAT
INTEGER,                INTENT(IN)  :: KNB_TSTEP_RUN
REAL, DIMENSION(KLON,KLAT,KNB_TSTEP_RUN), INTENT(OUT) :: PDRAIN         
REAL, DIMENSION(KLON,KLAT,KNB_TSTEP_RUN), INTENT(OUT) :: PRUNOFF
REAL, DIMENSION(KLON,KLAT,KNB_TSTEP_RUN), INTENT(OUT) :: PSRC_FLOOD
END SUBROUTINE TRIP_FORCING

END INTERFACE
END MODULE MODI_TRIP_FORCING 
