!depfile:trip_alloc.F90
MODULE MODI_TRIP_ALLOC
INTERFACE
SUBROUTINE TRIP_ALLOC(YDTRIP)
USE MODD_SURFEX_TRIP_n, ONLY : TRIP_MODEL_t
TYPE (TRIP_MODEL_t), INTENT (INOUT) :: YDTRIP
END SUBROUTINE TRIP_ALLOC

END INTERFACE
END MODULE MODI_TRIP_ALLOC
