!depfile:isba_ceb.F90
MODULE MODI_ISBA_CEB
INTERFACE
SUBROUTINE ISBA_CEB(IO, KK, PK, PEK, DK, DEK, DMK,      &
                    HIMPLICIT_WIND, PTSTEP, PPEW_A_COEF,   &
                    PPEW_B_COEF, PPET_A_COEF, PPEQ_A_COEF, PPET_B_COEF,&
                    PPEQ_B_COEF, AT, PSW_RAD, PLW_RAD, PEXNS, PEXNA, PTA,  &
                    PVMOD, PQA, PRR, PSR, PPS, PZREF, PUREF, PDIRCOSZW,&
                    PF5, PFFG_NOSNOW, PFFV_NOSNOW, PRHOA, PCS,         &
                    PSOILCONDZ, PSOILHCAPZ, PFROZEN1, PTDEEP_A,        &
                    PGRNDFLUX, PFLSN_COR, PSNOW_THRUFAL, PDELTA, PHUGI,&
                    PALBT, PEMIST, PDEEP_FLUX, PUSTAR, PAC_AGG, PHU_AGG )
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_SURF_ATM_TURB_n, ONLY : SURF_ATM_TURB_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(DIAG_t), INTENT(INOUT) :: DK
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEK
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMK
 CHARACTER(LEN=*),    INTENT(IN) :: HIMPLICIT_WIND   ! wind implicitation option
REAL,                 INTENT(IN) :: PTSTEP    ! timestep of the integration
REAL, DIMENSION(:),  INTENT(IN)  :: PPEW_A_COEF, PPEW_B_COEF,                   &
                                    PPET_A_COEF, PPEQ_A_COEF, PPET_B_COEF,      &
                                    PPEQ_B_COEF  
TYPE(SURF_ATM_TURB_t), INTENT(IN) :: AT         ! atmospheric turbulence parameters
REAL, DIMENSION(:), INTENT(IN)   :: PSW_RAD, PLW_RAD
REAL, DIMENSION(:), INTENT(IN)   :: PEXNA, PEXNS, PTA, PVMOD, PQA, PRR, PSR, PPS
REAL, DIMENSION(:), INTENT(IN)   :: PZREF, PUREF
REAL, DIMENSION(:), INTENT(IN)    :: PF5
REAL, DIMENSION(:), INTENT(IN)    :: PDIRCOSZW 
REAL, DIMENSION(:), INTENT(IN)   :: PFFG_NOSNOW, PFFV_NOSNOW
REAL, DIMENSION(:), INTENT(IN)   :: PRHOA
REAL, DIMENSION(:), INTENT(IN)   :: PCS
REAL, DIMENSION(:), INTENT(IN)   :: PGRNDFLUX, PFLSN_COR, PSNOW_THRUFAL 
REAL, DIMENSION(:,:), INTENT(IN)  :: PSOILCONDZ, PSOILHCAPZ
REAL, DIMENSION(:), INTENT(IN)    :: PFROZEN1
REAL, DIMENSION(:), INTENT(IN)     :: PTDEEP_A
REAL, DIMENSION(:),   INTENT(INOUT) :: PDELTA
REAL, DIMENSION(:), INTENT(OUT)  :: PHUGI
REAL, DIMENSION(:), INTENT(OUT)  :: PALBT, PEMIST
REAL, DIMENSION(:), INTENT(OUT)   :: PDEEP_FLUX ! Heat flux at bottom of ISBA (W/m2)
REAL, DIMENSION(:), INTENT(OUT)     :: PUSTAR
REAL, DIMENSION(:),  INTENT(OUT) :: PAC_AGG  ! aggregated aerodynamic conductance
REAL, DIMENSION(:),  INTENT(OUT) :: PHU_AGG  ! aggregated relative humidity
END SUBROUTINE ISBA_CEB

END INTERFACE
END MODULE MODI_ISBA_CEB
