!depfile:prep_ver_watflux.F90
MODULE MODI_PREP_VER_WATFLUX 
INTERFACE
SUBROUTINE PREP_VER_WATFLUX (W)
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(WATFLUX_t), INTENT(INOUT) :: W
END SUBROUTINE PREP_VER_WATFLUX

END INTERFACE
END MODULE MODI_PREP_VER_WATFLUX 
