!depfile:dealloc_diag_surf_atmn.F90
MODULE MODI_DEALLOC_DIAG_SURF_ATM_n 
INTERFACE
      SUBROUTINE DEALLOC_DIAG_SURF_ATM_n (D,DC,ND,NDC)
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_NP_t
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DC
TYPE(DIAG_NP_t), INTENT(INOUT) :: ND
TYPE(DIAG_NP_t), INTENT(INOUT) :: NDC
END SUBROUTINE DEALLOC_DIAG_SURF_ATM_n

END INTERFACE
END MODULE MODI_DEALLOC_DIAG_SURF_ATM_n 
