!depfile:prep_watflux_unif.F90
MODULE MODI_PREP_WATFLUX_UNIF
INTERFACE
SUBROUTINE PREP_WATFLUX_UNIF(KLUOUT,HSURF,PFIELD)
INTEGER,            INTENT(IN)  :: KLUOUT    ! output listing logical unit
 CHARACTER(LEN=7),   INTENT(IN)  :: HSURF     ! type of field
REAL, POINTER, DIMENSION(:,:)   :: PFIELD    ! field to interpolate horizontally
END SUBROUTINE PREP_WATFLUX_UNIF

END INTERFACE
END MODULE MODI_PREP_WATFLUX_UNIF
