!depfile:pgd_topd.F90
MODULE MODI_PGD_TOPD 
INTERFACE
      SUBROUTINE PGD_TOPD (HISBA, HGRID, PGRID_PAR, KDIM_FULL, PSSO_SLOPE, HPROGRAM)
 CHARACTER(LEN=*), INTENT(IN) :: HISBA
 CHARACTER(LEN=*), INTENT(IN) :: HGRID
REAL, DIMENSION(:), INTENT(IN) :: PGRID_PAR
 INTEGER, INTENT(IN) :: KDIM_FULL
 REAL, DIMENSION(:), INTENT(INOUT) :: PSSO_SLOPE
CHARACTER(LEN=*),  INTENT(IN)     :: HPROGRAM    !
END SUBROUTINE PGD_TOPD

END INTERFACE
END MODULE MODI_PGD_TOPD 
