!depfile:write_pgd_inland_watern.F90
MODULE MODI_WRITE_PGD_INLAND_WATER_n 
INTERFACE
      SUBROUTINE WRITE_PGD_INLAND_WATER_n (DTCO, HSELECT, U, WG, W, FG, F, &
                                           HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(GRID_t), INTENT(INOUT) :: WG
TYPE(WATFLUX_t), INTENT(INOUT) :: W
TYPE(GRID_t), INTENT(INOUT) :: FG
TYPE(FLAKE_t), INTENT(INOUT) :: F
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE WRITE_PGD_INLAND_WATER_n

END INTERFACE
END MODULE MODI_WRITE_PGD_INLAND_WATER_n 
