!depfile:hor_interpol_gauss.F90
MODULE MODI_HOR_INTERPOL_GAUSS
INTERFACE
SUBROUTINE HOR_INTERPOL_GAUSS(KLUOUT,PFIELDIN,PFIELDOUT)
INTEGER,            INTENT(IN)  :: KLUOUT    ! logical unit of output listing
REAL, DIMENSION(:,:), INTENT(IN)    :: PFIELDIN  ! field to interpolate horizontally
REAL, DIMENSION(:,:), INTENT(OUT)   :: PFIELDOUT ! interpolated field
END SUBROUTINE HOR_INTERPOL_GAUSS

END INTERFACE
END MODULE MODI_HOR_INTERPOL_GAUSS
