!depfile:write_pgd_watfluxn.F90
MODULE MODI_WRITE_PGD_WATFLUX_n 
INTERFACE
      SUBROUTINE WRITE_PGD_WATFLUX_n (DTCO, HSELECT, U, G, W, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_WATFLUX_n, ONLY : WATFLUX_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(GRID_t), INTENT(INOUT) :: G
TYPE(WATFLUX_t), INTENT(INOUT) :: W
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE WRITE_PGD_WATFLUX_n

END INTERFACE
END MODULE MODI_WRITE_PGD_WATFLUX_n 
