!depfile:dealloc_surf_atmn.F90
MODULE MODI_DEALLOC_SURF_ATM_n 
INTERFACE
SUBROUTINE DEALLOC_SURF_ATM_n (YSC)
USE MODD_SURFEX_n, ONLY : SURFEX_t
TYPE(SURFEX_t), INTENT(INOUT) :: YSC
END SUBROUTINE DEALLOC_SURF_ATM_n

END INTERFACE
END MODULE MODI_DEALLOC_SURF_ATM_n 
