!depfile:substract_to_date_surf.F90
MODULE MODI_SUBSTRACT_TO_DATE_SURF
INTERFACE
      SUBROUTINE SUBSTRACT_TO_DATE_SURF(KYEAR,KMONTH,KDAY,PSEC)
INTEGER, INTENT(INOUT) :: KYEAR  ! year of date
INTEGER, INTENT(INOUT) :: KMONTH ! month of date
INTEGER, INTENT(INOUT) :: KDAY   ! day of date
REAL,    INTENT(INOUT) :: PSEC   ! number of seconds since date at 00 UTC
END SUBROUTINE SUBSTRACT_TO_DATE_SURF

END INTERFACE
END MODULE MODI_SUBSTRACT_TO_DATE_SURF
