!depfile:writesurf_isban.F90
MODULE MODI_WRITESURF_ISBA_n 
INTERFACE
      SUBROUTINE WRITESURF_ISBA_n (HSELECT, OSNOWDIMNC, CHI, NDST, &
                                   IO, S, NP, NPE, KI, HPROGRAM, OLAND_USE)
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
USE MODD_DST_n, ONLY : DST_NP_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_NP_t, ISBA_NPE_t, ISBA_S_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT 
LOGICAL, INTENT(IN) :: OSNOWDIMNC  
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHI
TYPE(DST_NP_t), INTENT(INOUT) :: NDST
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
TYPE(ISBA_NPE_t), INTENT(INOUT) :: NPE
INTEGER, INTENT(IN) :: KI
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
LOGICAL,           INTENT(IN)  :: OLAND_USE !
END SUBROUTINE WRITESURF_ISBA_n

END INTERFACE
END MODULE MODI_WRITESURF_ISBA_n 
