!depfile:sfx_oasis_check.F90
MODULE MODI_SFX_OASIS_CHECK 
INTERFACE
SUBROUTINE SFX_OASIS_CHECK (IO, U, KLUOUT)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
INTEGER, INTENT(IN) :: KLUOUT
END SUBROUTINE SFX_OASIS_CHECK

END INTERFACE
END MODULE MODI_SFX_OASIS_CHECK 
