!depfile:write_budget_coupl_rout.F90
MODULE MODI_WRITE_BUDGET_COUPL_ROUT
INTERFACE
      SUBROUTINE WRITE_BUDGET_COUPL_ROUT
END SUBROUTINE WRITE_BUDGET_COUPL_ROUT

END INTERFACE
END MODULE MODI_WRITE_BUDGET_COUPL_ROUT
