!depfile:ch_dep_isba.F90
MODULE MODI_CH_DEP_ISBA
INTERFACE
     SUBROUTINE CH_DEP_ISBA(KK, PK, PEK, D, DM, CHIK, PUSTAR, PTA, PPA, PTRAD, KSIZE  )  
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_CH_ISBA_n, ONLY : CH_ISBA_t
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(CH_ISBA_t), INTENT(INOUT) :: CHIK
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DM
REAL, DIMENSION(:),     INTENT(IN)  :: PUSTAR       ! friction velocity
REAL, DIMENSION(:),     INTENT(IN)  :: PTA          ! air temperature forcing (K)
REAL, DIMENSION(:),     INTENT(IN)  :: PPA          ! surface atmospheric pressure
REAL, DIMENSION(:),     INTENT(IN)  :: PTRAD        ! radiative temperature  (K)
INTEGER, INTENT(IN) :: KSIZE
END SUBROUTINE CH_DEP_ISBA

END INTERFACE
END MODULE MODI_CH_DEP_ISBA
