!depfile:put_in_time.F90
MODULE MODI_PUT_IN_TIME
INTERFACE
SUBROUTINE PUT_IN_TIME(HNAME,HTYPE,NTIME1,NTIME2,PDATA)
CHARACTER(LEN=*), INTENT(IN) :: HNAME
CHARACTER(LEN=3), INTENT(IN) :: HTYPE
INTEGER, INTENT(IN) :: NTIME1
INTEGER, INTENT(IN) :: NTIME2
REAL, DIMENSION(:,:,:), INTENT(INOUT) :: PDATA
END SUBROUTINE PUT_IN_TIME

END INTERFACE
END MODULE MODI_PUT_IN_TIME
