!depfile:diag_teb_initn.F90
MODULE MODI_DIAG_TEB_INIT_n 
INTERFACE
      SUBROUTINE DIAG_TEB_INIT_n (DGO, D, DUT, HPROGRAM,KLU,KSW)
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_TYPE_DATE_SURF
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_UTCI_TEB_t), INTENT(INOUT) :: DUT
INTEGER, INTENT(IN) :: KLU   ! size of arrays
INTEGER, INTENT(IN) :: KSW   ! spectral bands
 CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
END SUBROUTINE DIAG_TEB_INIT_n

END INTERFACE
END MODULE MODI_DIAG_TEB_INIT_n 
