!depfile:get_lonlat_trip.F90
MODULE MODI_GET_LONLAT_TRIP 
INTERFACE
 SUBROUTINE GET_LONLAT_TRIP (TPG, &
                             KLON,KLAT,PLON,PLAT)
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER,               INTENT(IN ) :: KLON
INTEGER,               INTENT(IN ) :: KLAT
REAL, DIMENSION(KLON), INTENT(OUT) :: PLON
REAL, DIMENSION(KLAT), INTENT(OUT) :: PLAT
END SUBROUTINE GET_LONLAT_TRIP

END INTERFACE
END MODULE MODI_GET_LONLAT_TRIP 
