!depfile:read_prep_garden_snow.F90
MODULE MODI_READ_PREP_GARDEN_SNOW
INTERFACE
      SUBROUTINE READ_PREP_GARDEN_SNOW(HPROGRAM,HSNOW,KSNOW_LAYER,HFILE,HFILETYPE,HFILEPGD,HFILEPGDTYPE,OUNIF)
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling ISBA
CHARACTER(LEN=3),  INTENT(OUT) :: HSNOW    ! snow scheme
INTEGER, INTENT(OUT)           :: KSNOW_LAYER  ! number of snow layers
CHARACTER(LEN=28), OPTIONAL, INTENT(OUT) :: HFILE        ! file name
CHARACTER(LEN=6),  OPTIONAL, INTENT(OUT) :: HFILETYPE    ! file type
 CHARACTER(LEN=28),OPTIONAL, INTENT(OUT) :: HFILEPGD     ! file name
 CHARACTER(LEN=6), OPTIONAL, INTENT(OUT) :: HFILEPGDTYPE ! file type 
 LOGICAL,          OPTIONAL, INTENT(OUT) :: OUNIF        ! uniform snow
END SUBROUTINE READ_PREP_GARDEN_SNOW

END INTERFACE
END MODULE MODI_READ_PREP_GARDEN_SNOW
