!depfile:dealloc_sean.F90
MODULE MODI_DEALLOC_SEA_n 
INTERFACE
SUBROUTINE DEALLOC_SEA_n (SM, U)
USE MODD_SURFEX_n, ONLY : SEAFLUX_MODEL_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SEAFLUX_MODEL_t), INTENT(INOUT) :: SM
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
END SUBROUTINE DEALLOC_SEA_n

END INTERFACE
END MODULE MODI_DEALLOC_SEA_n 
