!depfile:test_record_len.F90
MODULE MODI_TEST_RECORD_LEN 
INTERFACE
SUBROUTINE TEST_RECORD_LEN (HPROGRAM,HREC,HSELECT,ONOWRITE)
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM ! calling program
 CHARACTER(LEN=12),  INTENT(IN)  :: HREC     ! name of the article to be written
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
LOGICAL,            INTENT(OUT) :: ONOWRITE ! flag for article to be written
END SUBROUTINE TEST_RECORD_LEN

END INTERFACE
END MODULE MODI_TEST_RECORD_LEN 
