!depfile:exp_decay_soil_fr.F90
MODULE MODI_EXP_DECAY_SOIL_FR 
INTERFACE
      SUBROUTINE EXP_DECAY_SOIL_FR (HISBA, PF, PK, PC_DEPTH_RATIO)  
USE MODD_ISBA_n, ONLY : ISBA_P_t
 CHARACTER(LEN=*)                  :: HISBA   ! hydrology/soil:
REAL, DIMENSION(:), INTENT(IN)    :: PF
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
REAL, DIMENSION(:), INTENT(IN), OPTIONAL :: PC_DEPTH_RATIO
END SUBROUTINE EXP_DECAY_SOIL_FR

END INTERFACE
END MODULE MODI_EXP_DECAY_SOIL_FR 
