!depfile:rmc01_surf.F90
MODULE MODI_RMC01_SURF
INTERFACE
      SUBROUTINE RMC01_SURF(PZ, PLMO, PLK, PLEPS, ONEUTRAL)
REAL, DIMENSION(:,:),   INTENT(IN)  :: PZ   ! altitude of full levels
REAL, DIMENSION(:,:),   INTENT(IN)  :: PLMO ! Monin Obuhkov length
REAL, DIMENSION(:,:),   INTENT(OUT) :: PLK  ! Mixing length
REAL, DIMENSION(:,:),   INTENT(OUT) :: PLEPS! Dissipative length
LOGICAL, OPTIONAL,      INTENT(IN)  :: ONEUTRAL
END SUBROUTINE RMC01_SURF

END INTERFACE
END MODULE MODI_RMC01_SURF
