!depfile:cotwores.F90
MODULE MODI_COTWORES
INTERFACE
SUBROUTINE COTWORES(PTSTEP, IO, OSHADE, PK, PEK, PDMAX, PPOI, PCSP, &
                    PTG, PF2, PSW_RAD, PQA, PQSAT, PPSNV, PDELTA, PRHOA, &
                    PZENITH, PFFV, PIACAN_SUNLIT, PIACAN_SHADE, PFRAC_SUN, &
                    PIACAN, PABC, PRS, PGPP, PRESP_LEAF     ) 
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_P_t, ISBA_PE_t
REAL,                INTENT(IN)  :: PTSTEP      ! time step
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
LOGICAL, DIMENSION(:),INTENT(IN) :: OSHADE
REAL, DIMENSION(:),  INTENT(IN)  :: PPOI     ! Gaussian weights (as above)
REAL,DIMENSION(:),   INTENT(IN)  :: PDMAX  
REAL,DIMENSION(:),   INTENT(IN)  :: PCSP, PTG, PF2, PSW_RAD 
REAL,DIMENSION(:),   INTENT(IN)  :: PQA, PQSAT, PPSNV, PDELTA, PRHOA
REAL,DIMENSION(:),    INTENT(IN)  :: PZENITH
REAL, DIMENSION(:,:), INTENT(IN)    :: PIACAN_SUNLIT, PIACAN_SHADE, PFRAC_SUN
REAL, DIMENSION(:), INTENT(IN)      :: PFFV ! Floodplain fraction over vegetation
REAL, DIMENSION(:,:), INTENT(INOUT) :: PIACAN ! PAR in the canopy at different gauss level
REAL,DIMENSION(:),  INTENT(INOUT) :: PABC, PRS, PGPP
REAL,DIMENSION(:),    INTENT(OUT) :: PRESP_LEAF
END SUBROUTINE COTWORES

END INTERFACE
END MODULE MODI_COTWORES
