!depfile:error_write_surf_txt.F90
MODULE MODI_ERROR_WRITE_SURF_TXT
INTERFACE
SUBROUTINE ERROR_WRITE_SURF_TXT(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(OUT):: KRESP
END SUBROUTINE ERROR_WRITE_SURF_TXT

END INTERFACE
END MODULE MODI_ERROR_WRITE_SURF_TXT
