!depfile:default_write_surf_atm.F90
MODULE MODI_DEFAULT_WRITE_SURF_ATM
INTERFACE
      SUBROUTINE DEFAULT_WRITE_SURF_ATM(ONOWRITE_CANOPY, ONOWRITE_TEXFILE, OSPLIT_PATCH)
LOGICAL,           INTENT(OUT) :: ONOWRITE_CANOPY  ! flag to desactivate writing of canopy fields
LOGICAL,           INTENT(OUT) :: ONOWRITE_TEXFILE ! flag to desactivate writing of tex file
LOGICAL,           INTENT(OUT) :: OSPLIT_PATCH
END SUBROUTINE DEFAULT_WRITE_SURF_ATM

END INTERFACE
END MODULE MODI_DEFAULT_WRITE_SURF_ATM
