!depfile:init_trip.F90
MODULE MODI_INIT_TRIP 
INTERFACE
SUBROUTINE INIT_TRIP (TPDG, TP, TPG, &
                      KYEAR,KMONTH,KDAY,PTIME,KLON,KLAT,&
                      PTSTEP_RUN,PTSTEP_DIAG,ORESTART,OXIOS)
USE MODD_TRIP_DIAG, ONLY : TRIP_DIAG_t
USE MODD_TRIP,      ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_DIAG_t), INTENT(INOUT) :: TPDG
TYPE(TRIP_t),      INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER,          INTENT(OUT) :: KYEAR   !date UTC
INTEGER,          INTENT(OUT) :: KMONTH  !date UTC
INTEGER,          INTENT(OUT) :: KDAY    !date UTC
REAL,             INTENT(OUT) :: PTIME   !date UTC
INTEGER,          INTENT(OUT) :: KLON      ! number of points in longitude
INTEGER,          INTENT(OUT) :: KLAT      ! number of points in latitude
REAL,             INTENT(IN) :: PTSTEP_RUN
REAL,             INTENT(IN) :: PTSTEP_DIAG
LOGICAL,          INTENT(IN) :: ORESTART
LOGICAL,          INTENT(IN) :: OXIOS
END SUBROUTINE INIT_TRIP

END INTERFACE
END MODULE MODI_INIT_TRIP 
