!depfile:soil_albedo.F90
MODULE MODI_SOIL_ALBEDO
INTERFACE
      SUBROUTINE SOIL_ALBEDO(HALBEDO, PWSAT, PWG1, KK, PEK, HBAND)  
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_PE_t
 CHARACTER(LEN=*),       INTENT(IN)   :: HALBEDO
REAL, DIMENSION(:), INTENT(IN)    :: PWSAT       ! saturation water content
REAL, DIMENSION(:), INTENT(IN)  :: PWG1        ! surface water content
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
 CHARACTER(LEN=*), INTENT(IN) :: HBAND
END SUBROUTINE SOIL_ALBEDO

END INTERFACE
END MODULE MODI_SOIL_ALBEDO
