!depfile:close_file.F90
MODULE MODI_CLOSE_FILE
INTERFACE
      SUBROUTINE CLOSE_FILE(HPROGRAM,KUNIT)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(IN)  :: KUNIT    ! logical unit of file
END SUBROUTINE CLOSE_FILE

END INTERFACE
END MODULE MODI_CLOSE_FILE
