!depfile:diag_evap_cumul_isban.F90
MODULE MODI_DIAG_EVAP_CUMUL_ISBA_n 
INTERFACE
SUBROUTINE DIAG_EVAP_CUMUL_ISBA_n (OSURF_BUDGETC, DE, DECK, DCK, DEK, DK, PEK, &
                             IO, PTSTEP, KSIZE, KPATCH, PRHOA)
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_ISBA_n, ONLY : ISBA_PE_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
LOGICAL, INTENT(IN) :: OSURF_BUDGETC
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DE
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DECK
TYPE(DIAG_t), INTENT(INOUT) :: DCK
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEK
TYPE(DIAG_t), INTENT(INOUT) :: DK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
REAL,    INTENT(IN)               :: PTSTEP        ! time step
INTEGER, INTENT(IN)               :: KSIZE  
INTEGER, INTENT(IN) :: KPATCH
REAL,    DIMENSION(:), INTENT(IN) :: PRHOA         ! air density for unit change
END SUBROUTINE DIAG_EVAP_CUMUL_ISBA_n

END INTERFACE
END MODULE MODI_DIAG_EVAP_CUMUL_ISBA_n 
