!depfile:init_restart_trip.F90
MODULE MODI_INIT_RESTART_TRIP 
INTERFACE
      SUBROUTINE INIT_RESTART_TRIP (TPG, &
                                     KLISTING,HFILE,KLON,KLAT,HTITLE,HTIMEUNIT,OTIME)
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
 CHARACTER(LEN=*), INTENT(IN) :: HFILE, HTITLE, HTIMEUNIT
INTEGER, INTENT(IN)          :: KLISTING, KLON, KLAT
LOGICAL, INTENT(IN)          :: OTIME
END SUBROUTINE INIT_RESTART_TRIP

END INTERFACE
END MODULE MODI_INIT_RESTART_TRIP 
