!depfile:ol_time_interp_atm.F90
MODULE MODI_OL_TIME_INTERP_ATM 
INTERFACE
SUBROUTINE OL_TIME_INTERP_ATM (KSURF_STEP,KNB_ATM,                       &
                               PTA1,PTA2,PQA1,PQA2,PWIND1,PWIND2,        &
                               PDIR_SW1,PDIR_SW2,PSCA_SW1,PSCA_SW2,      &
                               PLW1,PLW2,PSNOW2,PRAIN2,                  &
                               PPS1,PPS2,PCO21,PCO22,PDIR1,PDIR2,        &
			       									 PO31,PO32,PAE1,PAE2,PIMPWET2,PIMPDRY2,    &
                               PZEN,PSUMZEN )  
INTEGER,INTENT(IN) :: KSURF_STEP, KNB_ATM
REAL, DIMENSION(:),INTENT(IN) :: PTA1,PTA2,PQA1,PQA2,PWIND1,PWIND2
REAL, DIMENSION(:),INTENT(IN) :: PDIR_SW1,PDIR_SW2,PSCA_SW1,PSCA_SW2,PLW1,PLW2
REAL, DIMENSION(:),INTENT(IN) :: PSNOW2,PRAIN2,PPS1,PPS2,PCO21,PCO22,PDIR1,PDIR2,PO31,PO32,PAE1,PAE2
REAL, DIMENSION(:,:),INTENT(IN) :: PIMPWET2,PIMPDRY2
REAL, DIMENSION(:),INTENT(IN) :: PZEN,PSUMZEN 
END SUBROUTINE OL_TIME_INTERP_ATM

END INTERFACE
END MODULE MODI_OL_TIME_INTERP_ATM 
