!depfile:init_teb_veg_optionsn.F90
MODULE MODI_INIT_TEB_VEG_OPTIONS_n 
INTERFACE
SUBROUTINE INIT_TEB_VEG_OPTIONS_n (CHT, OSURF_DIAG_ALBEDO, OGREENROOF, GDO, GRO, HPROGRAM)
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_TYPE_DATE_SURF
USE MODD_TYPE_SNOW
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
LOGICAL, INTENT(OUT) :: OSURF_DIAG_ALBEDO
LOGICAL, INTENT(IN) :: OGREENROOF 
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: GDO
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: GRO
 CHARACTER(LEN=6),                   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE INIT_TEB_VEG_OPTIONS_n

END INTERFACE
END MODULE MODI_INIT_TEB_VEG_OPTIONS_n 
