!depfile:read_slt_conf.F90
MODULE MODI_READ_SLT_CONF
INTERFACE
      SUBROUTINE READ_SLT_CONF(HPROGRAM)
 CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM ! program calling SLT
END SUBROUTINE READ_SLT_CONF

END INTERFACE
END MODULE MODI_READ_SLT_CONF
