!depfile:pgd_dummy.F90
MODULE MODI_PGD_DUMMY 
INTERFACE
      SUBROUTINE PGD_DUMMY (DTCO, DUU, UG, U, USS, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DUMMY_SURF_FIELDS_n, ONLY : DUMMY_SURF_FIELDS_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DUMMY_SURF_FIELDS_t), INTENT(INOUT) :: DUU
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
END SUBROUTINE PGD_DUMMY

END INTERFACE
END MODULE MODI_PGD_DUMMY 
