!depfile:prep_teb_greenroof_buffer.F90
MODULE MODI_PREP_TEB_GREENROOF_BUFFER
INTERFACE
SUBROUTINE PREP_TEB_GREENROOF_BUFFER(HPROGRAM,HSURF,KLUOUT,PFIELD)
USE MODD_TYPE_DATE_SURF
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM    ! program calling surf. schemes
 CHARACTER(LEN=7),   INTENT(IN)  :: HSURF       ! type of field
INTEGER,            INTENT(IN)  :: KLUOUT      ! logical unit of output listing
REAL,DIMENSION(:,:,:), POINTER  :: PFIELD      ! field to interpolate horizontally
END SUBROUTINE PREP_TEB_GREENROOF_BUFFER

END INTERFACE
END MODULE MODI_PREP_TEB_GREENROOF_BUFFER
