!depfile:prep_ver_teb_veg.F90
MODULE MODI_PREP_VER_TEB_VEG 
INTERFACE
SUBROUTINE PREP_VER_TEB_VEG (P, PEK, IO, PZS)
USE MODD_ISBA_n, ONLY : ISBA_PE_t, ISBA_P_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
TYPE(ISBA_P_t), INTENT(INOUT) :: P
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
REAL, DIMENSION(:), INTENT(IN) :: PZS
END SUBROUTINE PREP_VER_TEB_VEG

END INTERFACE
END MODULE MODI_PREP_VER_TEB_VEG 
