!depfile:write_file_isbamap.F90
MODULE MODI_WRITE_FILE_ISBAMAP 
INTERFACE
      SUBROUTINE WRITE_FILE_ISBAMAP (UG, KUNIT,PVAR,KI)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
INTEGER, INTENT(IN)             :: KUNIT  ! file unit
REAL, DIMENSION(:), INTENT(IN)  :: PVAR   ! variable to write in the file
INTEGER, INTENT(IN)             :: KI    ! Grid dimensions
END SUBROUTINE WRITE_FILE_ISBAMAP

END INTERFACE
END MODULE MODI_WRITE_FILE_ISBAMAP 
