!depfile:read_default_slt.F90
MODULE MODI_READ_DEFAULT_SLT
INTERFACE
      SUBROUTINE READ_DEFAULT_SLT(HPROGRAM)
 CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM ! program calling SLT
END SUBROUTINE READ_DEFAULT_SLT

END INTERFACE
END MODULE MODI_READ_DEFAULT_SLT
