!depfile:writesurf_oceann.F90
MODULE MODI_WRITESURF_OCEAN_n 
INTERFACE
      SUBROUTINE WRITESURF_OCEAN_n (HSELECT, O, OR, HPROGRAM)
USE MODD_OCEAN_n, ONLY : OCEAN_t
USE MODD_OCEAN_REL_n, ONLY : OCEAN_REL_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(OCEAN_t), INTENT(INOUT) :: O
TYPE(OCEAN_REL_t), INTENT(INOUT) :: OR
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE WRITESURF_OCEAN_n

END INTERFACE
END MODULE MODI_WRITESURF_OCEAN_n 
