!depfile:get_teb_depths.F90
MODULE MODI_GET_TEB_DEPTHS 
INTERFACE
      SUBROUTINE GET_TEB_DEPTHS (DTCO,  &
                                 HFILE, HFILETYPE, HFILEPGD, HFILEPGDTYPE, &
                                 PD_ROOF, PD_ROAD, PD_WALL, PD_FLOOR,HDIR)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t, DATA_COVER_INIT
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
 CHARACTER(LEN=28),  INTENT(IN)  :: HFILE ! type of input file
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILETYPE ! type of input file
 CHARACTER(LEN=28),  INTENT(IN)  :: HFILEPGD  ! type of input file
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILEPGDTYPE ! type of input file
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL   :: PD_ROOF
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL   :: PD_ROAD
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL   :: PD_WALL
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL   :: PD_FLOOR
 CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: HDIR
END SUBROUTINE GET_TEB_DEPTHS

END INTERFACE
END MODULE MODI_GET_TEB_DEPTHS 
