!depfile:e_budget_meb.F90
MODULE MODI_E_BUDGET_MEB
INTERFACE
      SUBROUTINE E_BUDGET_MEB(IO, KK, PK, PEK, DK, DEK, DMK,     &
                              PTSTEP, PLTT, PPS, PCT, PTDEEP_A, PD_G, PSOILCONDZ,   &
                              PSOILHCAPZ, PSNOWRHO, PSNOWCONDZ, PSNOWHCAPZ, PTAU_N, &
                              PLWNET_V_DTV, PLWNET_V_DTG, PLWNET_V_DTN,    &
                              PLWNET_G_DTV, PLWNET_G_DTG, PLWNET_G_DTN,    &
                              PLWNET_N_DTV, PLWNET_N_DTG, PLWNET_N_DTN,    &
                              PPEW_A_COEF, PPEW_B_COEF, PPET_A_COEF,       &
                              PPEQ_A_COEF, PPET_B_COEF, PPEQ_B_COEF,       &
                              PTHRMA_TA, PTHRMB_TA, PTHRMA_TC, PTHRMB_TC,  &
                              PTHRMA_TG, PTHRMB_TG, PTHRMA_TV, PTHRMB_TV,  &
                              PTHRMA_TN, PTHRMB_TN, PQSAT_G, PQSAT_V,      &
                              PQSATI_N, PPSNA, PPSNCV, PCHEATV, PCHEATG,   &
                              PCHEATN, PLEG_DELTA, PLEGI_DELTA, PHUGI,     &
                              PHVG, PHVN, PFROZEN1, PFLXC_C_A, PFLXC_G_C,  &
                              PFLXC_VG_C, PFLXC_VN_C, PFLXC_N_C, PFLXC_N_A,&
                              PFLXC_MOM, PTG, PSNOWLIQ, PFLXC_V_C, PHVGS, PHVNS,  &
                              PDQSAT_G, PDQSAT_V, PDQSATI_N, PTA_IC,       &
                              PQA_IC, PUSTAR2_IC, PVMOD, PDELTAT_G,        &
                              PDELTAT_V, PDELTAT_N, PGRNDFLUX, PDEEP_FLUX, &
                              PDELHEATV_SFC, PDELHEATG_SFC, PDELHEATG )
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
USE MODD_DIAG_n, ONLY : DIAG_t
USE MODD_DIAG_EVAP_ISBA_n, ONLY : DIAG_EVAP_ISBA_t
USE MODD_DIAG_MISC_ISBA_n, ONLY : DIAG_MISC_ISBA_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(DIAG_t), INTENT(INOUT) :: DK
TYPE(DIAG_EVAP_ISBA_t), INTENT(INOUT) :: DEK
TYPE(DIAG_MISC_ISBA_t), INTENT(INOUT) :: DMK
REAL,                 INTENT(IN)   :: PTSTEP
REAL, DIMENSION(:),   INTENT(IN)   :: PCT
REAL, DIMENSION(:), INTENT(IN)     :: PTDEEP_A
REAL, DIMENSION(:),   INTENT(IN)   :: PPS
REAL, DIMENSION(:,:), INTENT(IN)   :: PD_G, PSOILCONDZ, PSOILHCAPZ
REAL, DIMENSION(:,:), INTENT(IN)   :: PSNOWCONDZ, PSNOWHCAPZ, PSNOWRHO
REAL, DIMENSION(:,:), INTENT(IN)   :: PTAU_N
REAL, DIMENSION(:),   INTENT(IN)   :: PLWNET_V_DTV, PLWNET_V_DTG, PLWNET_V_DTN
REAL, DIMENSION(:),   INTENT(IN)   :: PLWNET_G_DTV, PLWNET_G_DTG, PLWNET_G_DTN
REAL, DIMENSION(:),   INTENT(IN)   :: PLWNET_N_DTV, PLWNET_N_DTG, PLWNET_N_DTN
REAL, DIMENSION(:),   INTENT(IN)   :: PTHRMA_TA, PTHRMB_TA, PTHRMA_TC, PTHRMB_TC,                     &
                                      PTHRMA_TG, PTHRMB_TG, PTHRMA_TV, PTHRMB_TV, PTHRMA_TN, PTHRMB_TN
REAL, DIMENSION(:),   INTENT(IN)   :: PPET_A_COEF, PPEQ_A_COEF, PPET_B_COEF, PPEQ_B_COEF,             &
                                      PPEW_A_COEF, PPEW_B_COEF
REAL, DIMENSION(:),   INTENT(IN)   :: PQSAT_G, PQSAT_V, PQSATI_N
REAL, DIMENSION(:),   INTENT(IN)   :: PPSNA, PPSNCV
REAL, DIMENSION(:),   INTENT(IN)   :: PLEG_DELTA, PLEGI_DELTA, PHUGI, PHVG, PHVN, PFROZEN1
REAL, DIMENSION(:),   INTENT(IN)   :: PFLXC_C_A, PFLXC_G_C, PFLXC_VG_C, PFLXC_VN_C, PFLXC_N_C, PFLXC_N_A, PFLXC_MOM
REAL, DIMENSION(:),   INTENT(IN)   :: PLTT
REAL, DIMENSION(:,:), INTENT(INOUT):: PTG
REAL, DIMENSION(:,:), INTENT(INOUT):: PSNOWLIQ
REAL, DIMENSION(:),   INTENT(OUT)  :: PCHEATV, PCHEATG, PCHEATN
REAL, DIMENSION(:),   INTENT(OUT)  :: PDQSAT_G, PDQSAT_V, PDQSATI_N
REAL, DIMENSION(:),   INTENT(OUT)  :: PFLXC_V_C, PHVGS, PHVNS
REAL, DIMENSION(:),   INTENT(OUT)  :: PTA_IC, PQA_IC, PUSTAR2_IC, PVMOD
REAL, DIMENSION(:),   INTENT(OUT)  :: PDELTAT_V, PDELTAT_N, PDELTAT_G
REAL, DIMENSION(:),   INTENT(OUT)  :: PGRNDFLUX 
REAL, DIMENSION(:),  INTENT(OUT)   :: PDEEP_FLUX ! Heat flux at bottom of ISBA (W/m2)
REAL, DIMENSION(:),  INTENT(OUT)   :: PDELHEATV_SFC, PDELHEATG_SFC, PDELHEATG
END SUBROUTINE E_BUDGET_MEB

END INTERFACE
END MODULE MODI_E_BUDGET_MEB
