!depfile:average1_orography.F90
MODULE MODI_AVERAGE1_OROGRAPHY 
INTERFACE
      SUBROUTINE AVERAGE1_OROGRAPHY (UG,USS, &
                                     KLUOUT,KNBLINES,PLAT,PLON,PVALUE,PNODATA)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SSO_n, ONLY : SSO_t
USE MODD_POINT_OVERLAY, ONLY : NOVMX
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SSO_t), INTENT(INOUT) :: USS
INTEGER,                 INTENT(IN)    :: KLUOUT
INTEGER,                 INTENT(IN)    :: KNBLINES
REAL, DIMENSION(:),      INTENT(IN)    :: PLAT    ! latitude of the point to add
REAL, DIMENSION(:),      INTENT(IN)    :: PLON    ! longitude of the point to add
REAL, DIMENSION(:),      INTENT(IN)    :: PVALUE  ! value of the point to add
REAL, OPTIONAL, INTENT(IN) :: PNODATA
END SUBROUTINE AVERAGE1_OROGRAPHY

END INTERFACE
END MODULE MODI_AVERAGE1_OROGRAPHY 
