!depfile:allocate_teb_veg_pgd.F90
MODULE MODI_ALLOCATE_TEB_VEG_PGD 
INTERFACE
    SUBROUTINE ALLOCATE_TEB_VEG_PGD (PEK, S, K, P, OALLOC, KLU, KVEGTYPE, KGROUND_LAYER)  
USE MODD_ISBA_n, ONLY : ISBA_S_t, ISBA_PE_t, ISBA_P_t, ISBA_K_t
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(ISBA_P_t), INTENT(INOUT) :: P
TYPE(ISBA_K_t), INTENT(INOUT) :: K
LOGICAL, INTENT(IN) :: OALLOC ! True if constant PGD fields must be allocated
INTEGER, INTENT(IN) :: KLU
INTEGER, INTENT(IN) :: KVEGTYPE
INTEGER, INTENT(IN) :: KGROUND_LAYER
END SUBROUTINE ALLOCATE_TEB_VEG_PGD

END INTERFACE
END MODULE MODI_ALLOCATE_TEB_VEG_PGD 
