!depfile:sfx_oasis_def_ol.F90
MODULE MODI_SFX_OASIS_DEF_OL 
INTERFACE
SUBROUTINE SFX_OASIS_DEF_OL (IO, U, HPROGRAM,HALG_MPI)
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM   ! program calling surf. schemes
CHARACTER(LEN=4),   INTENT(IN)  :: HALG_MPI   ! decomposition algorithm
END SUBROUTINE SFX_OASIS_DEF_OL

END INTERFACE
END MODULE MODI_SFX_OASIS_DEF_OL 
