!depfile:ch_aer_emission.F90
MODULE MODI_CH_AER_EMISSION
INTERFACE
     SUBROUTINE CH_AER_EMISSION(PFLUX, PRHODREF, HSV, KSV_CHSBEG,  PFCO)
REAL,   DIMENSION(:,:),      INTENT(INOUT) :: PFLUX
REAL,   DIMENSION(:),        INTENT(IN) :: PRHODREF
INTEGER,                     INTENT(IN) :: KSV_CHSBEG
 CHARACTER(LEN=*), DIMENSION(:),  INTENT(IN)  :: HSV      ! name of chemical species
REAL,   DIMENSION(:),OPTIONAL, INTENT(IN)  :: PFCO   ! CO flux 
END SUBROUTINE CH_AER_EMISSION

END INTERFACE
END MODULE MODI_CH_AER_EMISSION
