!depfile:lailoss.F90
MODULE MODI_LAILOSS
INTERFACE
    SUBROUTINE LAILOSS(PK, PEK, PBIOMASS)  
USE MODD_ISBA_n, ONLY : ISBA_P_t, ISBA_PE_t
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
REAL,   DIMENSION(:), INTENT(INOUT) :: PBIOMASS ! total dry canopy biomass 
END SUBROUTINE LAILOSS

END INTERFACE
END MODULE MODI_LAILOSS
