!depfile:init_trip_cpl_esm.F90
MODULE MODI_INIT_TRIP_CPL_ESM 
INTERFACE
SUBROUTINE INIT_TRIP_CPL_ESM (TP, TPG, &
                              KLON,KLAT)  
USE MODD_TRIP,      ONLY : TRIP_t
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_t), INTENT(INOUT) :: TP
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER, INTENT(IN) :: KLON
INTEGER, INTENT(IN) :: KLAT
END SUBROUTINE INIT_TRIP_CPL_ESM

END INTERFACE
END MODULE MODI_INIT_TRIP_CPL_ESM 
