!depfile:read_pgd_teb_greenroofn.F90
MODULE MODI_READ_PGD_TEB_GREENROOF_n 
INTERFACE
      SUBROUTINE READ_PGD_TEB_GREENROOF_n (OCH_BIO_FLUX, DTCO, DTV, GB, U, &
                                           IO, S, K, KDIM, HPROGRAM,KVERSION)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_GR_BIOG_n, ONLY : GR_BIOG_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_S_t
LOGICAL, INTENT(IN) :: OCH_BIO_FLUX
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
TYPE(GR_BIOG_t), INTENT(INOUT) :: GB
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_K_t), INTENT(INOUT) :: K
TYPE(ISBA_S_t), INTENT(INOUT) :: S
INTEGER, INTENT(INOUT) :: KDIM
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! calling program
INTEGER,           INTENT(IN)  :: KVERSION ! version of SURFEX of the file being read
END SUBROUTINE READ_PGD_TEB_GREENROOF_n

END INTERFACE
END MODULE MODI_READ_PGD_TEB_GREENROOF_n 
