!depfile:error_read_surf_ol.F90
MODULE MODI_ERROR_READ_SURF_OL
INTERFACE
SUBROUTINE ERROR_READ_SURF_OL(HREC,KRESP)
 CHARACTER(LEN=*), INTENT(IN) :: HREC
INTEGER,          INTENT(IN):: KRESP
END SUBROUTINE ERROR_READ_SURF_OL

END INTERFACE
END MODULE MODI_ERROR_READ_SURF_OL
