!depfile:average1_mesh.F90
MODULE MODI_AVERAGE1_MESH
INTERFACE
      SUBROUTINE AVERAGE1_MESH(UG,KLUOUT,KNBLINES,PLAT,PLON,PVALUE,OMULTITYPE,KFACT,PNODATA)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
INTEGER,                 INTENT(IN)    :: KLUOUT
INTEGER,                 INTENT(IN)    :: KNBLINES
REAL, DIMENSION(:),      INTENT(IN)    :: PLAT    ! latitude of the point to add
REAL, DIMENSION(:),      INTENT(IN)    :: PLON    ! longitude of the point to add
REAL, DIMENSION(:),      INTENT(IN)    :: PVALUE  ! value of the point to add
LOGICAL, INTENT(IN) :: OMULTITYPE
INTEGER, INTENT(IN) :: KFACT
REAL, OPTIONAL, INTENT(IN) :: PNODATA
END SUBROUTINE AVERAGE1_MESH

END INTERFACE
END MODULE MODI_AVERAGE1_MESH
