!depfile:pt_by_pt_treatment.F90
MODULE MODI_PT_BY_PT_TREATMENT 
INTERFACE
      SUBROUTINE PT_BY_PT_TREATMENT (UG, U, USS, &
                                     KLUOUT,PLAT,PLON,PVALUE,HSUBROUTINE,&
                                     KNBLINES,PNODATA,OMULTITYPE,KFACT)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
INTEGER,           INTENT(IN) :: KLUOUT
REAL,DIMENSION(:), INTENT(IN) :: PLAT
REAL,DIMENSION(:), INTENT(IN) :: PLON
REAL,DIMENSION(:), INTENT(IN) :: PVALUE
 CHARACTER(LEN=6), INTENT(IN)  :: HSUBROUTINE   ! Name of the subroutine to call
INTEGER, OPTIONAL, INTENT(IN) :: KNBLINES
REAL, OPTIONAL,    INTENT(IN) :: PNODATA
LOGICAL, OPTIONAL, INTENT(IN) :: OMULTITYPE
INTEGER, OPTIONAL, INTENT(IN) :: KFACT
END SUBROUTINE PT_BY_PT_TREATMENT

END INTERFACE
END MODULE MODI_PT_BY_PT_TREATMENT 
