!depfile:read_pgd_teb_greenroof_parn.F90
MODULE MODI_READ_PGD_TEB_GREENROOF_PAR_n 
INTERFACE
      SUBROUTINE READ_PGD_TEB_GREENROOF_PAR_n (DTV, IO, S, K, KDIM, HPROGRAM)
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_S_t, ISBA_K_t
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(ISBA_K_t), INTENT(INOUT) :: K
INTEGER, INTENT(IN) :: KDIM
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
END SUBROUTINE READ_PGD_TEB_GREENROOF_PAR_n

END INTERFACE
END MODULE MODI_READ_PGD_TEB_GREENROOF_PAR_n 
