!depfile:get_lat_gwf.F90
MODULE MODI_GET_LAT_GWF 
INTERFACE
 SUBROUTINE GET_LAT_GWF (TPG, &
                         KLAT,PRES,PLAT)
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
INTEGER,               INTENT(IN ) :: KLAT
REAL,                  INTENT(OUT) :: PRES
REAL, DIMENSION(KLAT), INTENT(OUT) :: PLAT
END SUBROUTINE GET_LAT_GWF

END INTERFACE
END MODULE MODI_GET_LAT_GWF 
