!depfile:oi_jacobians.F90
MODULE MODI_OI_JACOBIANS 
INTERFACE
SUBROUTINE OI_JACOBIANS (KNBPT,&
!---------------------------------------------------------------------------------
! - INPUT  1D
   PWS_O, PSAB, PARG, PD2, PWP, &
! - OUTPUT 1D .
   PDWG_DWG, PDWG_DW2)    
INTEGER, INTENT(IN)    :: KNBPT
REAL    ,INTENT(IN)    :: PWS_O(KNBPT) 
REAL    ,INTENT(IN)    :: PSAB(KNBPT)
REAL    ,INTENT(IN)    :: PARG(KNBPT)
REAL    ,INTENT(IN)    :: PD2(KNBPT)
REAL    ,INTENT(IN)    :: PWP(KNBPT)
REAL    ,INTENT(OUT)   :: PDWG_DWG(KNBPT)
REAL    ,INTENT(OUT)   :: PDWG_DW2(KNBPT) 
END SUBROUTINE OI_JACOBIANS

END INTERFACE
END MODULE MODI_OI_JACOBIANS 
