!depfile:get_lonlatn.F90
MODULE MODI_GET_LONLAT_n 
INTERFACE
      SUBROUTINE GET_LONLAT_n (DTCO, U, UG, HSELECT, HPROGRAM)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
 CHARACTER(LEN=6),    INTENT(IN)  :: HPROGRAM
END SUBROUTINE GET_LONLAT_n

END INTERFACE
END MODULE MODI_GET_LONLAT_n 
