!depfile:albedo_mk10.F90
MODULE MODI_ALBEDO_MK10
INTERFACE
      FUNCTION ALBEDO_MK10(PZENITH) RESULT(PDIR_ALB)
REAL, DIMENSION(:), INTENT(IN)  :: PZENITH     ! zenithal angle (radian)
REAL, DIMENSION(SIZE(PZENITH))  :: PDIR_ALB    ! direct albedo on water
END FUNCTION ALBEDO_MK10

END INTERFACE
END MODULE MODI_ALBEDO_MK10
