!depfile:writesurf_tebn.F90
MODULE MODI_WRITESURF_TEB_n 
INTERFACE
      SUBROUTINE WRITESURF_TEB_n (HSELECT, OSNOWDIMNC, DTCO, U, TOP, BOP, T, B, ODATA_ROAD_DIR, TPN, &
                                  GDO, GDS, GDPEK, GRO, GRS, GRPEK, HPROGRAM,KPATCH,HWRITE)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
USE MODD_BEM_OPTION_n, ONLY : BEM_OPTIONS_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_BEM_n, ONLY : BEM_t
USE MODD_TEB_PANEL_n, ONLY : TEB_PANEL_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_PE_t, ISBA_S_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT 
LOGICAL, INTENT(IN) :: OSNOWDIMNC
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(TEB_OPTIONS_t), INTENT(IN) :: TOP
TYPE(BEM_OPTIONS_t), INTENT(IN) :: BOP
TYPE(TEB_t), INTENT(IN) :: T
TYPE(BEM_t), INTENT(IN) :: B
LOGICAL, INTENT(IN) :: ODATA_ROAD_DIR
TYPE(TEB_PANEL_t), INTENT(INOUT) :: TPN
TYPE(ISBA_OPTIONS_t), INTENT(IN) :: GDO
TYPE(ISBA_S_t), INTENT(INOUT) :: GDS
TYPE(ISBA_PE_t), INTENT(IN) :: GDPEK
TYPE(ISBA_OPTIONS_t), INTENT(IN) :: GRO
TYPE(ISBA_S_t), INTENT(INOUT) :: GRS
TYPE(ISBA_PE_t), INTENT(IN) :: GRPEK
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling
INTEGER,           INTENT(IN)  :: KPATCH   ! current TEB patch
 CHARACTER(LEN=3),    INTENT(IN)  :: HWRITE    ! 'PREP' : does not write SBL XUNDEF fields
END SUBROUTINE WRITESURF_TEB_n

END INTERFACE
END MODULE MODI_WRITESURF_TEB_n 
