!depfile:read_prep_isba_carbon.F90
MODULE MODI_READ_PREP_ISBA_CARBON
INTERFACE
      SUBROUTINE READ_PREP_ISBA_CARBON(HPROGRAM,HRESPSL)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling ISBA
 CHARACTER(LEN=3),  INTENT(OUT) :: HRESPSL  ! Soil respiration
END SUBROUTINE READ_PREP_ISBA_CARBON

END INTERFACE
END MODULE MODI_READ_PREP_ISBA_CARBON
