!depfile:ol_read_atm_conf.F90
MODULE MODI_OL_READ_ATM_CONF 
INTERFACE
SUBROUTINE OL_READ_ATM_CONF (DTCO, U, HGRID, HSURF_FILETYPE, HFORCING_FILETYPE, ODELAYEDSTART_NC, &
                             KDATESTOP, PDURATION, PTSTEP_FORC, KNI, KYEAR, KMONTH, KDAY,  &
                             PTIME, PLAT, PLON, PZS, PZREF, PUREF, KTIMESTARTINDEX    )  
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=*), INTENT(IN)  :: HGRID
 CHARACTER(LEN=6), INTENT(IN)  :: HSURF_FILETYPE
 CHARACTER(LEN=6), INTENT(IN)  :: HFORCING_FILETYPE
LOGICAL, INTENT(IN)            :: ODELAYEDSTART_NC !Allow the simulation to start from a different time step than the first record of a netcdf file 
INTEGER,DIMENSION(4),INTENT(IN) :: KDATESTOP !Allow the simulation to end at a different time step than the last record of a netcdf file
INTEGER,          INTENT(OUT) :: KNI
INTEGER,          INTENT(OUT) :: KYEAR, KMONTH, KDAY
REAL,             INTENT(OUT) :: PDURATION,PTSTEP_FORC
REAL,             INTENT(OUT) :: PTIME
REAL, DIMENSION(:),  POINTER  :: PLAT, PLON
REAL, DIMENSION(:),  POINTER  :: PZS
REAL, DIMENSION(:),  POINTER  :: PZREF, PUREF
INTEGER,          INTENT(OUT) :: KTIMESTARTINDEX ! index from which we start reading FORCING.nc
END SUBROUTINE OL_READ_ATM_CONF

END INTERFACE
END MODULE MODI_OL_READ_ATM_CONF 
