!depfile:get_luout.F90
MODULE MODI_GET_LUOUT
INTERFACE
      SUBROUTINE GET_LUOUT(HPROGRAM,KLUOUT)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling GROUND
INTEGER,           INTENT(OUT) :: KLUOUT   ! Logical unit of output listing
END SUBROUTINE GET_LUOUT

END INTERFACE
END MODULE MODI_GET_LUOUT
