!depfile:dispatch_wg.F90
MODULE MODI_DISPATCH_WG 
INTERFACE
      SUBROUTINE DISPATCH_WG (S, NP, NPE, PWG, PWGI, PDG)
USE MODD_ISBA_n, ONLY : ISBA_S_t, ISBA_NP_t, ISBA_NPE_t
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
TYPE(ISBA_NPE_t), INTENT(INOUT) :: NPE
 REAL, DIMENSION(:,:), INTENT(IN) :: PWG
 REAL, DIMENSION(:,:), INTENT(IN) :: PWGI
 REAL, DIMENSION(:,:), INTENT(IN) :: PDG
END SUBROUTINE DISPATCH_WG

END INTERFACE
END MODULE MODI_DISPATCH_WG 
