!depfile:average2_mesh.F90
MODULE MODI_AVERAGE2_MESH
INTERFACE
      SUBROUTINE AVERAGE2_MESH(PPGDARRAY)
REAL,    DIMENSION(:,:), INTENT(INOUT) :: PPGDARRAY ! Mesonh field
END SUBROUTINE AVERAGE2_MESH

END INTERFACE
END MODULE MODI_AVERAGE2_MESH
