!depfile:dealloc_seafluxn.F90
MODULE MODI_DEALLOC_SEAFLUX_n 
INTERFACE
SUBROUTINE DEALLOC_SEAFLUX_n (SM)
USE MODD_SURFEX_n, ONLY : SEAFLUX_MODEL_t
TYPE(SEAFLUX_MODEL_t), INTENT(INOUT) :: SM
END SUBROUTINE DEALLOC_SEAFLUX_n

END INTERFACE
END MODULE MODI_DEALLOC_SEAFLUX_n 
