!depfile:old_name.F90
MODULE MODI_OLD_NAME 
INTERFACE
      SUBROUTINE OLD_NAME (HPROGRAM,HRECIN,HRECOUT,HDIR)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
 CHARACTER(LEN=12), INTENT(IN)  :: HRECIN   ! name of field to be read
 CHARACTER(LEN=12), INTENT(OUT) :: HRECOUT  ! name of field to be read is old file
 CHARACTER(LEN=1), INTENT(IN), OPTIONAL :: HDIR
END SUBROUTINE OLD_NAME

END INTERFACE
END MODULE MODI_OLD_NAME 
