!depfile:soil_heatdif.F90
MODULE MODI_SOIL_HEATDIF
INTERFACE
      SUBROUTINE SOIL_HEATDIF(PTSTEP,PDZG,PDZDIF,PSOILCONDZ,   &
                              PSOILHCAPZ,PCT,PTERM1,PTERM2,    &
                              PTDEEP_A,PTDEEP_B,PTG,PDEEP_FLUX,&
                              PFLUX_COR                        )  
REAL, INTENT(IN)                    :: PTSTEP ! Model time step (s)
REAL, DIMENSION(:), INTENT(IN)      :: PCT, PTERM1, PTERM2, PTDEEP_A, PTDEEP_B
REAL, DIMENSION(:,:), INTENT(IN)    :: PSOILCONDZ, PSOILHCAPZ, PFLUX_COR
REAL, DIMENSION(:,:), INTENT(IN)    :: PDZDIF, PDZG
REAL, DIMENSION(:,:), INTENT(INOUT) :: PTG
REAL, DIMENSION(:), INTENT(OUT)     :: PDEEP_FLUX ! Heat flux at bottom of ISBA (W/m2)
END SUBROUTINE SOIL_HEATDIF

END INTERFACE
END MODULE MODI_SOIL_HEATDIF
