!depfile:read_namelists_ideal.F90
MODULE MODI_READ_NAMELISTS_IDEAL
INTERFACE
SUBROUTINE READ_NAMELISTS_IDEAL(HPROGRAM)
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE READ_NAMELISTS_IDEAL

END INTERFACE
END MODULE MODI_READ_NAMELISTS_IDEAL
