!depfile:sat_area_frac.F90
MODULE MODI_SAT_AREA_FRAC
INTERFACE
      SUBROUTINE SAT_AREA_FRAC(PDEF,PAS,GTOPD)
REAL, DIMENSION(:,:),INTENT(IN)     :: PDEF    ! deficit
REAL, DIMENSION(:), INTENT(OUT)     :: PAS     !contributive area fraction in Isba meshes
LOGICAL, DIMENSION(:), INTENT(INOUT)   :: GTOPD     ! 
END SUBROUTINE SAT_AREA_FRAC

END INTERFACE
END MODULE MODI_SAT_AREA_FRAC
