!depfile:fsso.F90
MODULE MODI_FSSO
INTERFACE
      SUBROUTINE FSSO(U, UG, USS)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t 
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n,  ONLY : SSO_t
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SSO_t), INTENT(INOUT) :: USS
END SUBROUTINE FSSO

END INTERFACE
END MODULE MODI_FSSO
