!depfile:init_slt.F90
MODULE MODI_INIT_SLT 
INTERFACE
SUBROUTINE INIT_SLT (SLT, &
                     HPROGRAM  &! Program calling unit
       )  
USE MODD_SLT_n, ONLY : SLT_t
TYPE(SLT_t), INTENT(INOUT) :: SLT
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM              !Passing unit
END SUBROUTINE INIT_SLT

END INTERFACE
END MODULE MODI_INIT_SLT 
