!depfile:ini_data_param_teb.F90
MODULE MODI_INI_DATA_PARAM_TEB 
INTERFACE
      SUBROUTINE INI_DATA_PARAM_TEB (BDD, &
                                     KTYPE,                                          &
                                PZ0_TOWN, PALB_ROOF, PALB_ROAD, PALB_WALL,          &
                                PEMIS_ROOF, PEMIS_ROAD, PEMIS_WALL, PHC_ROOF,       &
                                PHC_ROAD, PHC_WALL, PTC_ROOF, PTC_ROAD, PTC_WALL,   &
                                PD_ROOF, PD_ROAD, PD_WALL, PBLD_HEIGHT,             &
                                PWALL_O_HOR, PBLD, PCAN_HW_RATIO, PH_TRAFFIC,        &
                                PLE_TRAFFIC, PH_INDUSTRY, PLE_INDUSTRY,              &
                                PGARDEN, OGARDEN, PHC_FLOOR,                        &
                                PTC_FLOOR, PD_FLOOR, PTCOOL_TARGET, PTHEAT_TARGET,  &
                                PF_WASTE_CAN, PEFF_HEAT, PQIN, PQIN_FRAD, PSHGC,    &
                                PU_WIN, PGR, PSHGC_SH, PFLOOR_HEIGHT, PINF,         &
                                PF_WATER_COND, PQIN_FLAT, PHR_TARGET, PV_VENT,      &
                                PCAP_SYS_HEAT, PCAP_SYS_RAT, PT_ADP, PM_SYS_RAT,    &
                                PCOP_RAT, PT_SIZE_MAX, PT_SIZE_MIN, PSHADE,         &
                                PNATVENT, PROUGH_ROOF, PROUGH_WALL, PGREENROOF,     &
                                PRESIDENTIAL,                                       &
                                PEMIS_PANEL, PALB_PANEL, PEFF_PANEL, PFRAC_PANEL    )
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
INTEGER, DIMENSION(:), INTENT(IN) :: KTYPE
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PZ0_TOWN
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PALB_ROOF
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PALB_ROAD
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PALB_WALL
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PEMIS_ROOF
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PEMIS_ROAD
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PEMIS_WALL
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PHC_ROOF
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PHC_ROAD
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PHC_WALL
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PTC_ROOF
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PTC_ROAD
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PTC_WALL
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PD_ROOF
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PD_ROAD
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PD_WALL
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PBLD_HEIGHT
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PWALL_O_HOR
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PBLD
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PCAN_HW_RATIO
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PH_TRAFFIC
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PLE_TRAFFIC
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PH_INDUSTRY
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PLE_INDUSTRY
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PGARDEN
LOGICAL,            INTENT(IN),  OPTIONAL :: OGARDEN
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PHC_FLOOR
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PTC_FLOOR
REAL, DIMENSION(:,:), INTENT(OUT), OPTIONAL :: PD_FLOOR
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PTCOOL_TARGET
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PTHEAT_TARGET
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PF_WASTE_CAN
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PEFF_HEAT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PQIN
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PQIN_FRAD
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PSHGC
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PU_WIN
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PGR
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PSHGC_SH
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PFLOOR_HEIGHT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PINF
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PF_WATER_COND
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PQIN_FLAT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PHR_TARGET
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PV_VENT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PCAP_SYS_HEAT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PCAP_SYS_RAT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PT_ADP
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PM_SYS_RAT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PCOP_RAT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PT_SIZE_MAX
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PT_SIZE_MIN
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PSHADE
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PNATVENT
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PROUGH_ROOF
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PROUGH_WALL
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PRESIDENTIAL
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PGREENROOF
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PEMIS_PANEL
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PALB_PANEL
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PEFF_PANEL
REAL, DIMENSION(:),   INTENT(OUT), OPTIONAL   :: PFRAC_PANEL
END SUBROUTINE INI_DATA_PARAM_TEB

END INTERFACE
END MODULE MODI_INI_DATA_PARAM_TEB 
