!depfile:allocate_teb_veg.F90
MODULE MODI_ALLOCATE_TEB_VEG 
INTERFACE
    SUBROUTINE ALLOCATE_TEB_VEG (PEK, KLU,KGROUND_LAYER,KNBIOMASS)  
USE MODD_ISBA_n, ONLY : ISBA_PE_t
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
INTEGER, INTENT(IN) :: KLU
INTEGER, INTENT(IN) :: KGROUND_LAYER
INTEGER, INTENT(IN) :: KNBIOMASS
END SUBROUTINE ALLOCATE_TEB_VEG

END INTERFACE
END MODULE MODI_ALLOCATE_TEB_VEG 
