!depfile:ol_find_file_read.F90
MODULE MODI_OL_FIND_FILE_READ
INTERFACE
        SUBROUTINE OL_FIND_FILE_READ(HNAME,IFILE_ID,OOPTIONAL)
 CHARACTER(LEN=*),   INTENT(IN) :: HNAME
INTEGER, INTENT(OUT):: IFILE_ID
LOGICAL, INTENT(IN), OPTIONAL :: OOPTIONAL
END SUBROUTINE OL_FIND_FILE_READ

END INTERFACE
END MODULE MODI_OL_FIND_FILE_READ
