!depfile:ch_init_depconst.F90
MODULE MODI_CH_INIT_DEPCONST
INTERFACE
       SUBROUTINE CH_INIT_DEPCONST(HPROGRAM,HCHEM_SURF_FILE,KLUOUT,HSV)
CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! Program name
CHARACTER(LEN=28), INTENT(IN)  :: HCHEM_SURF_FILE ! ascii file for chemistry aggregation
INTEGER,                  INTENT(IN)  :: KLUOUT   ! output listing channel
 CHARACTER(LEN=*), DIMENSION(:),  INTENT(IN)  :: HSV      ! name of chemical species
END SUBROUTINE CH_INIT_DEPCONST

END INTERFACE
END MODULE MODI_CH_INIT_DEPCONST
