!depfile:subscale_z0eff.F90
MODULE MODI_SUBSCALE_Z0EFF
INTERFACE
      SUBROUTINE SUBSCALE_Z0EFF(ISSK,PZ0VEG,OZ0REL,OMASK  )
USE MODD_SSO_n, ONLY : SSO_t
TYPE(SSO_t), INTENT(INOUT) :: ISSK
REAL, DIMENSION(:), INTENT(IN)  :: PZ0VEG  ! vegetation roughness length
LOGICAL, INTENT(IN) :: OZ0REL
LOGICAL, DIMENSION(:), INTENT(IN), OPTIONAL :: OMASK ! mask where computations
END SUBROUTINE SUBSCALE_Z0EFF

END INTERFACE
END MODULE MODI_SUBSCALE_Z0EFF
