!depfile:writesurf_snapn.F90
MODULE MODI_WRITESURF_SNAP_n 
INTERFACE
      SUBROUTINE WRITESURF_SNAP_n (HSELECT, CHN, HPROGRAM)
USE MODD_CH_SNAP_n, ONLY : CH_EMIS_SNAP_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
TYPE(CH_EMIS_SNAP_t), INTENT(INOUT) :: CHN
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
END SUBROUTINE WRITESURF_SNAP_n

END INTERFACE
END MODULE MODI_WRITESURF_SNAP_n 
