!depfile:get_iok_assim.F90
MODULE MODI_GET_IOK_ASSIM
INTERFACE
SUBROUTINE GET_IOK_ASSIM(HREC,KOK)
CHARACTER(LEN=16), INTENT(IN) :: HREC
INTEGER, INTENT(OUT) :: KOK
END SUBROUTINE GET_IOK_ASSIM

END INTERFACE
END MODULE MODI_GET_IOK_ASSIM
