!depfile:prep_isba_cc_extern.F90
MODULE MODI_PREP_ISBA_CC_EXTERN 
INTERFACE
SUBROUTINE PREP_ISBA_CC_EXTERN (GCP,HPROGRAM,HSURF,HFILE,HFILETYPE,HFILEPGD,HFILEPGDTYPE,KLUOUT,PFIELD,OPREP_AGS)
USE MODD_GRID_CONF_PROJ_n, ONLY : GRID_CONF_PROJ_t
TYPE(GRID_CONF_PROJ_t),INTENT(INOUT) :: GCP
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=8),   INTENT(IN)  :: HSURF     ! type of field
 CHARACTER(LEN=28),  INTENT(IN)  :: HFILE     ! name of file
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILETYPE ! type of input file
 CHARACTER(LEN=28),  INTENT(IN)  :: HFILEPGD     ! name of file
 CHARACTER(LEN=6),   INTENT(IN)  :: HFILEPGDTYPE ! type of input file
INTEGER,             INTENT(IN)  :: KLUOUT    ! logical unit of output listing
REAL,DIMENSION(:,:,:), POINTER   :: PFIELD    ! field to interpolate horizontally (on final soil grid)
LOGICAL,            INTENT(INOUT):: OPREP_AGS
END SUBROUTINE PREP_ISBA_CC_EXTERN

END INTERFACE
END MODULE MODI_PREP_ISBA_CC_EXTERN 
