!depfile:read_csvdata_teb.F90
MODULE MODI_READ_CSVDATA_TEB 
INTERFACE
      SUBROUTINE READ_CSVDATA_TEB (BDD, &
                                   HPROGRAM,HFILE)
USE MODD_BLD_DESCRIPTION_n, ONLY : BLD_DESC_t
TYPE(BLD_DESC_t), INTENT(INOUT) :: BDD
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM
 CHARACTER(LEN=28), INTENT(IN) :: HFILE    ! file to read
END SUBROUTINE READ_CSVDATA_TEB

END INTERFACE
END MODULE MODI_READ_CSVDATA_TEB 
