!depfile:ol_write_proj.F90
MODULE MODI_OL_WRITE_PROJ
INTERFACE
SUBROUTINE OL_WRITE_PROJ(HSELECT, KFILE_ID, UG)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
INTEGER,               INTENT(IN) :: KFILE_ID
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
END SUBROUTINE OL_WRITE_PROJ

END INTERFACE
END MODULE MODI_OL_WRITE_PROJ
