!depfile:get_trip_grid_conf.F90
MODULE MODI_GET_TRIP_GRID_CONF 
INTERFACE
      SUBROUTINE GET_TRIP_GRID_CONF (TPG, &
                                     PLONMIN,PLONMAX,PLATMIN,PLATMAX,PRES,KLON,KLAT)
USE MODD_TRIP_GRID, ONLY : TRIP_GRID_t
TYPE(TRIP_GRID_t), INTENT(INOUT) :: TPG
REAL,               INTENT(OUT) :: PLONMIN
REAL,               INTENT(OUT) :: PLONMAX
REAL,               INTENT(OUT) :: PLATMIN
REAL,               INTENT(OUT) :: PLATMAX
REAL,               INTENT(OUT) :: PRES
INTEGER,            INTENT(OUT) :: KLON
INTEGER,            INTENT(OUT) :: KLAT
END SUBROUTINE GET_TRIP_GRID_CONF

END INTERFACE
END MODULE MODI_GET_TRIP_GRID_CONF 
