!depfile:control_moist_func.F90
MODULE MODI_CONTROL_MOIST_FUNC 
INTERFACE
FUNCTION CONTROL_MOIST_FUNC (PMOIST,PSAT) RESULT (PMOISTFUNC)
REAL, DIMENSION(:), INTENT(IN)   :: PMOIST ! soil moisture index (-)
REAL, DIMENSION(:), INTENT(IN)   :: PSAT   ! soil saturated index (-)
REAL, DIMENSION(SIZE(PMOIST)) :: PMOISTFUNC    ! moisture control factor
END FUNCTION CONTROL_MOIST_FUNC

END INTERFACE
END MODULE MODI_CONTROL_MOIST_FUNC 
