!depfile:cli_lake.F90
MODULE MODI_CLI_LAKE 
INTERFACE
SUBROUTINE CLI_LAKE (G, F)
USE MODD_SFX_GRID_n, ONLY : GRID_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
TYPE(GRID_t), INTENT(INOUT) :: G
TYPE(FLAKE_t), INTENT(INOUT) :: F
END SUBROUTINE CLI_LAKE

END INTERFACE
END MODULE MODI_CLI_LAKE 
