!depfile:writesurf_teb_confn.F90
MODULE MODI_WRITESURF_TEB_CONF_n 
INTERFACE
      SUBROUTINE WRITESURF_TEB_CONF_n (CHT, DMTO, DGO, DUT, T, TOP, HPROGRAM)
USE MODD_CH_TEB_n, ONLY : CH_TEB_t
USE MODD_DIAG_MISC_TEB_OPTIONS_n, ONLY : DIAG_MISC_TEB_OPTIONS_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_DIAG_UTCI_TEB_n, ONLY : DIAG_UTCI_TEB_t
USE MODD_TEB_n, ONLY : TEB_t
USE MODD_TEB_OPTION_n, ONLY : TEB_OPTIONS_t
TYPE(CH_TEB_t), INTENT(INOUT) :: CHT
TYPE(DIAG_MISC_TEB_OPTIONS_t), INTENT(INOUT) :: DMTO
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(DIAG_UTCI_TEB_t), INTENT(INOUT) :: DUT
TYPE(TEB_t), INTENT(INOUT) :: T
TYPE(TEB_OPTIONS_t), INTENT(INOUT) :: TOP
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM ! program calling TEB
END SUBROUTINE WRITESURF_TEB_CONF_n

END INTERFACE
END MODULE MODI_WRITESURF_TEB_CONF_n 
