!depfile:open_namelist_lfi.F90
MODULE MODI_OPEN_NAMELIST_LFI
INTERFACE
      SUBROUTINE OPEN_NAMELIST_LFI(HPROGRAM,KLUNAM,HFILE)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(OUT) :: KLUNAM   ! logical unit of namelist
 CHARACTER(LEN=28), INTENT(IN)  :: HFILE ! FAII file to open
END SUBROUTINE OPEN_NAMELIST_LFI

END INTERFACE
END MODULE MODI_OPEN_NAMELIST_LFI
