!depfile:vertical_grid_nat.F90
MODULE MODI_VERTICAL_GRID_NAT
INTERFACE
SUBROUTINE VERTICAL_GRID_NAT(PDG1,PT1,PDG2,PT2)
REAL, DIMENSION(:,:), INTENT(IN)  :: PDG1  ! input vertical grid
REAL, DIMENSION(:,:), INTENT(IN)  :: PT1  ! input temperatures
REAL, DIMENSION(:,:), INTENT(IN)  :: PDG2  ! output vertical grid
REAL, DIMENSION(:,:), INTENT(OUT) :: PT2  ! output temperatures
END SUBROUTINE VERTICAL_GRID_NAT

END INTERFACE
END MODULE MODI_VERTICAL_GRID_NAT
