!depfile:make_mask_topd_to_isba.F90
MODULE MODI_MAKE_MASK_TOPD_TO_ISBA 
INTERFACE
    SUBROUTINE MAKE_MASK_TOPD_TO_ISBA (HGRID, PGRID_PAR, KI)
 CHARACTER(LEN=*), INTENT(IN) :: HGRID
REAL, DIMENSION(:), INTENT(IN) :: PGRID_PAR
INTEGER, INTENT(IN) :: KI    ! Grid dimensions
END SUBROUTINE MAKE_MASK_TOPD_TO_ISBA

END INTERFACE
END MODULE MODI_MAKE_MASK_TOPD_TO_ISBA 
