!depfile:default_assim.F90
MODULE MODI_DEFAULT_ASSIM
INTERFACE
      SUBROUTINE DEFAULT_ASSIM(OASSIM,HASSIM,HASSIM_ISBA,KPRINTLEV,         &
                               OAROME,OECSST,OAESST,OAESNM,                 &
                               OALADSURF,OREAD_SST_FROM_FILE,               &
                               HFILE_FORMAT_SST,OEXTRAP_SEA,                &
                               OEXTRAP_WATER,OEXTRAP_NATURE,                &
                               OWATERTG2,KBOUTPUT,KECHGU,KECHGXFU,PRCLIMCA, &
                               PRCLISST,PSIGH2MO,PSIGT2MO,PSIGWGO,          &
                               PSIGWGB,PSIGW2B,OOBSWG,OOBS2M,OIMVEG,        &
                               PSPRECIP2,PRTHR_QC,PSIGWGO_MAX,              &
                               PRSCAL_JAC,OPRT,OSIM,OBEV,OBFIXED,           &
                               KOBSTYPE,OOBSHEADER,HFILE_FORMAT_OBS,OOBSNAT,&
                               HFILE_FORMAT_FG,HFILE_FORMAT_LSM,            &
                               HFILE_FORMAT_CLIM,PERROBS_M,PQCOBS_M,        &
                               KNCO,KIVAR,KVAR,HVAR_M,HPREFIX_M,            &
                               PSIGMA_M,PTPRT_M,KNCV,PSCALE_Q,              &
                               PSCALE_QLAI,HBIO,HPREFIX_BIO,PALPH,          &
                               KENS,KIE,PINFL_M,PADDINFL_M, PASSIM_WINH,    &
                               PADDTIMECORR_M,OENS_GEN,OPB_CORRELATIONS,    &
                               OPERTURBATION_RUN,OBIAS_CORRECTION,          &
                               OENKF,ODENKF,HTEST)
USE MODD_ASSIM, ONLY : NOBSMAX, NVARMAX
LOGICAL,           INTENT(OUT) :: OASSIM        ! assimilation or not
CHARACTER(LEN=5),  INTENT(OUT) :: HASSIM        ! type of corrections PLUS/2DVAR
CHARACTER(LEN=5),  INTENT(OUT) :: HASSIM_ISBA
INTEGER,           INTENT(OUT) :: KPRINTLEV
LOGICAL,           INTENT(OUT) :: OAROME
LOGICAL,           INTENT(OUT) :: OECSST
LOGICAL,           INTENT(OUT) :: OAESST
LOGICAL,           INTENT(OUT) :: OAESNM
LOGICAL,           INTENT(OUT) :: OALADSURF
LOGICAL,           INTENT(OUT) :: OREAD_SST_FROM_FILE
CHARACTER(LEN=6),  INTENT(OUT) :: HFILE_FORMAT_SST
LOGICAL,           INTENT(OUT) :: OEXTRAP_SEA
LOGICAL,           INTENT(OUT) :: OEXTRAP_WATER
LOGICAL,           INTENT(OUT) :: OEXTRAP_NATURE
LOGICAL,           INTENT(OUT) :: OWATERTG2
INTEGER,           INTENT(OUT) :: KBOUTPUT
INTEGER,           INTENT(OUT) :: KECHGU
INTEGER,           INTENT(OUT) :: KECHGXFU
REAL,              INTENT(OUT) :: PRCLIMCA
REAL,              INTENT(OUT) :: PRCLISST
REAL,              INTENT(OUT) :: PSIGH2MO
REAL,              INTENT(OUT) :: PSIGT2MO
REAL,              INTENT(OUT) :: PSIGWGO
REAL,              INTENT(OUT) :: PSIGWGB
REAL,              INTENT(OUT) :: PSIGW2B
LOGICAL,           INTENT(OUT) :: OOBSWG
LOGICAL,           INTENT(OUT) :: OOBS2M
LOGICAL,           INTENT(OUT) :: OIMVEG
REAL,              INTENT(OUT) :: PSPRECIP2 
REAL,              INTENT(OUT) :: PRTHR_QC
REAL,              INTENT(OUT) :: PSIGWGO_MAX
REAL,              INTENT(OUT) :: PRSCAL_JAC
LOGICAL,           INTENT(OUT) :: OPRT
LOGICAL,           INTENT(OUT) :: OSIM
LOGICAL,           INTENT(OUT) :: OBEV
LOGICAL,           INTENT(OUT) :: OBFIXED
INTEGER,             INTENT(OUT) :: KOBSTYPE
LOGICAL,             INTENT(OUT) :: OOBSHEADER
CHARACTER(LEN=6),    INTENT(OUT) :: HFILE_FORMAT_OBS
CHARACTER(LEN=6),    INTENT(OUT) :: HFILE_FORMAT_FG
CHARACTER(LEN=6),    INTENT(OUT) :: HFILE_FORMAT_LSM
CHARACTER(LEN=6),    INTENT(OUT) :: HFILE_FORMAT_CLIM
REAL, DIMENSION(NOBSMAX),    INTENT(OUT) :: PERROBS_M
REAL, DIMENSION(NOBSMAX),    INTENT(OUT) :: PQCOBS_M
INTEGER, DIMENSION(NOBSMAX), INTENT(OUT) :: KNCO
LOGICAL, INTENT(OUT) :: OOBSNAT
INTEGER,           INTENT(OUT) :: KIVAR
INTEGER,           INTENT(OUT) :: KVAR
CHARACTER(LEN=3),  DIMENSION(NVARMAX), INTENT(OUT) :: HVAR_M
CHARACTER(LEN=100),  DIMENSION(NVARMAX), INTENT(OUT) :: HPREFIX_M
REAL, DIMENSION(NVARMAX), INTENT(OUT) :: PSIGMA_M
REAL, DIMENSION(NVARMAX), INTENT(OUT) :: PTPRT_M
INTEGER, DIMENSION(NVARMAX), INTENT(OUT) :: KNCV
REAL,                INTENT(OUT) :: PSCALE_Q
REAL,                INTENT(OUT) :: PSCALE_QLAI
CHARACTER(LEN=12),   INTENT(OUT) :: HBIO
CHARACTER(LEN=100),  INTENT(OUT) :: HPREFIX_BIO
REAL, DIMENSION(12), INTENT(OUT) :: PALPH
INTEGER, INTENT(OUT) :: KENS
INTEGER, INTENT(OUT) :: KIE
REAL, INTENT(OUT) :: PASSIM_WINH
REAL, DIMENSION(NVARMAX),INTENT(OUT) :: PINFL_M
REAL, DIMENSION(NVARMAX),INTENT(OUT) :: PADDINFL_M
REAL, DIMENSION(NVARMAX),INTENT(OUT) :: PADDTIMECORR_M
LOGICAL, INTENT(OUT) :: OENKF
LOGICAL, INTENT(OUT) :: ODENKF
LOGICAL, INTENT(OUT) :: OENS_GEN
LOGICAL, INTENT(OUT) :: OPB_CORRELATIONS
LOGICAL, INTENT(OUT) :: OPERTURBATION_RUN
LOGICAL, INTENT(OUT) :: OBIAS_CORRECTION
CHARACTER(LEN=2),   INTENT(IN) :: HTEST
END SUBROUTINE DEFAULT_ASSIM

END INTERFACE
END MODULE MODI_DEFAULT_ASSIM
