!depfile:get_covern.F90
MODULE MODI_GET_COVER_n 
INTERFACE
      SUBROUTINE GET_COVER_n (U, &
                              HPROGRAM,KCOVER,PCOVER)
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
 CHARACTER(LEN=6),           INTENT(IN)  :: HPROGRAM
INTEGER,                    INTENT(IN)  :: KCOVER  ! number of covers
REAL, DIMENSION(:), INTENT(OUT) :: PCOVER  ! cover types
END SUBROUTINE GET_COVER_n

END INTERFACE
END MODULE MODI_GET_COVER_n 
