!depfile:isba_soc_parameters.F90
MODULE MODI_ISBA_SOC_PARAMETERS 
INTERFACE
SUBROUTINE ISBA_SOC_PARAMETERS (HRUNOFF,PSOC,K,NP,PFRACSOC,PWSAT,PWFC,PWWILT,KPATCH)
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_NP_t
CHARACTER(LEN=4),      INTENT(IN)    :: HRUNOFF
REAL, DIMENSION(:,:),  INTENT(IN)    :: PSOC
TYPE(ISBA_K_t), INTENT(INOUT) :: K
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
REAL, DIMENSION(:,:),  INTENT(OUT)   :: PFRACSOC
INTEGER, INTENT(IN) :: KPATCH
REAL, DIMENSION(:,:), INTENT(INOUT) :: PWSAT
REAL, DIMENSION(:,:), INTENT(INOUT) :: PWFC
REAL, DIMENSION(:,:), INTENT(INOUT) :: PWWILT
END SUBROUTINE ISBA_SOC_PARAMETERS

END INTERFACE
END MODULE MODI_ISBA_SOC_PARAMETERS 
