!depfile:write_file_masktopd.F90
MODULE MODI_WRITE_FILE_MASKTOPD
INTERFACE
      SUBROUTINE WRITE_FILE_MASKTOPD(KI)
INTEGER, INTENT(IN)             :: KI    ! Grid dimensions
END SUBROUTINE WRITE_FILE_MASKTOPD

END INTERFACE
END MODULE MODI_WRITE_FILE_MASKTOPD
