!depfile:assim_nature_isba_enkf.F90
MODULE MODI_ASSIM_NATURE_ISBA_ENKF
INTERFACE
SUBROUTINE ASSIM_NATURE_ISBA_ENKF(IO, S, K, NP, NPE, HPROGRAM, KI, PT2M, PHU2M, HTEST)
USE MODD_ASSIM,         ONLY : NOBSTYPE, XERROBS, NVAR, NPRINTLEV, CVAR,   &
                               XF_PATCH, XF,COBS,CFILE_FORMAT_OBS,NENS,    &
                               NECHGU, NBOUTPUT, NOBS, XYO, LENKF, LDENKF, &
                               LPB_CORRELATIONS, LPERTURBATION_RUN,        &
                               LBIAS_CORRECTION, XINFL
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_ISBA_n, ONLY : ISBA_S_t, ISBA_K_t, ISBA_NP_t, ISBA_NPE_t, ISBA_P_t, ISBA_PE_t
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
TYPE(ISBA_S_t), INTENT(INOUT) :: S
TYPE(ISBA_K_t), INTENT(INOUT) :: K
TYPE(ISBA_NP_t), INTENT(INOUT) :: NP
TYPE(ISBA_NPE_t), INTENT(INOUT) :: NPE
CHARACTER(LEN=6),   INTENT(IN) :: HPROGRAM     ! program calling surf. schemes
INTEGER,            INTENT(IN) :: KI
REAL, DIMENSION(:), INTENT(IN) :: PT2M
REAL, DIMENSION(:), INTENT(IN) :: PHU2M
CHARACTER(LEN=2),   INTENT(IN) :: HTEST        ! must be equal to 'OK'
END SUBROUTINE ASSIM_NATURE_ISBA_ENKF

END INTERFACE
END MODULE MODI_ASSIM_NATURE_ISBA_ENKF
