!depfile:init_index_mpi.F90
MODULE MODI_INIT_INDEX_MPI 
INTERFACE
SUBROUTINE INIT_INDEX_MPI (DTCO, U, UG, GCP, HPROGRAM,HINIT,HALG,PIO_FRAC,OSHADOWS)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_GRID_CONF_PROJ_n, ONLY : GRID_CONF_PROJ_t 
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(GRID_CONF_PROJ_t),INTENT(INOUT) :: GCP
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
 CHARACTER(LEN=3), INTENT(IN) :: HINIT 
 CHARACTER(LEN=4), INTENT(INOUT) :: HALG
REAL, INTENT(IN) :: PIO_FRAC
LOGICAL, INTENT(IN), OPTIONAL :: OSHADOWS
END SUBROUTINE INIT_INDEX_MPI

END INTERFACE
END MODULE MODI_INIT_INDEX_MPI 
