!depfile:prep_ctrl_teb.F90
MODULE MODI_PREP_CTRL_TEB 
INTERFACE
      SUBROUTINE PREP_CTRL_TEB (DGO, OSURF_EVAP_BUDGET,OSURF_MISC_BUDGET,OUTCI,KLUOUT)  
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
LOGICAL,  INTENT(INOUT) :: OSURF_EVAP_BUDGET  ! flag for surface evaporation budget
LOGICAL,  INTENT(INOUT) :: OSURF_MISC_BUDGET  ! flag for surface miscellaneous budget
LOGICAL,  INTENT(INOUT) :: OUTCI              ! flag for UTCI fields
INTEGER,  INTENT(IN)    :: KLUOUT             ! unit number
END SUBROUTINE PREP_CTRL_TEB 

END INTERFACE
END MODULE MODI_PREP_CTRL_TEB 
