!depfile:open_write_cover_tex_lfi.F90
MODULE MODI_OPEN_WRITE_COVER_TEX_LFI
INTERFACE
      SUBROUTINE OPEN_WRITE_COVER_TEX_LFI(KTEX)
INTEGER, INTENT(OUT) :: KTEX ! logical unit of Tex file
END SUBROUTINE OPEN_WRITE_COVER_TEX_LFI

END INTERFACE
END MODULE MODI_OPEN_WRITE_COVER_TEX_LFI
