!depfile:diag_flake_initn.F90
MODULE MODI_DIAG_FLAKE_INIT_n 
INTERFACE
      SUBROUTINE DIAG_FLAKE_INIT_n (OREAD_BUDGETC, DGO, D, DC, DMF, F, &
                                    HPROGRAM,KLU,KSW)
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
TYPE(DIAG_t), INTENT(INOUT) :: DC
TYPE(DIAG_MISC_FLAKE_t), INTENT(INOUT) :: DMF
LOGICAL, INTENT(IN) :: OREAD_BUDGETC
TYPE(FLAKE_t), INTENT(INOUT) :: F
INTEGER, INTENT(IN) :: KLU   ! size of arrays
INTEGER, INTENT(IN) :: KSW   ! number of SW spectral bands
CHARACTER(LEN=6), INTENT(IN):: HPROGRAM  ! program calling
END SUBROUTINE DIAG_FLAKE_INIT_n

END INTERFACE
END MODULE MODI_DIAG_FLAKE_INIT_n 
