!depfile:init_write_bin.F90
MODULE MODI_INIT_WRITE_BIN 
INTERFACE
      SUBROUTINE INIT_WRITE_BIN (HSELECT, KDIM_FULL, &
                                 HREC,KPATCH,OWFL)
 CHARACTER(LEN=*), DIMENSION(:), INTENT(IN) :: HSELECT
 INTEGER, INTENT(IN) :: KDIM_FULL
 CHARACTER(LEN=12),   INTENT(IN)     :: HREC    
INTEGER,             INTENT(IN)     :: KPATCH    
LOGICAL,             INTENT(INOUT)  :: OWFL
END SUBROUTINE INIT_WRITE_BIN

END INTERFACE
END MODULE MODI_INIT_WRITE_BIN 
