!depfile:oi_fctveg.F90
MODULE MODI_OI_FCTVEG
INTERFACE
SUBROUTINE OI_FCTVEG(KH,PVEG,&
   PVGAT1,PVGAT2,PVGAT3,PVGBT1,PVGBT2,PVGBT3,PVGCT1,PVGCT2, &
   PVGAH1,PVGAH2,PVGAH3,PVGBH1,PVGBH2,PVGBH3,PVGCH1,PVGCH2, &
   PSIGT2MP,PSIGHP2,PG1,PG2,PG3,PG4,&
   PVGST,PVGSH,PVGPT1,PVGPH1,PVGPT2,PVGPH2)  
INTEGER, INTENT(IN) :: KH
REAL, DIMENSION(24), INTENT(IN) :: PVGAT1,PVGAT2,PVGAT3
REAL, DIMENSION(24), INTENT(IN) :: PVGBT1,PVGBT2,PVGBT3
REAL, DIMENSION(24), INTENT(IN) :: PVGCT1,PVGCT2
REAL, DIMENSION(24), INTENT(IN) :: PVGAH1,PVGAH2,PVGAH3
REAL, DIMENSION(24), INTENT(IN) :: PVGBH1,PVGBH2,PVGBH3
REAL, DIMENSION(24), INTENT(IN) :: PVGCH1,PVGCH2
REAL, DIMENSION(24), INTENT(IN) :: PSIGT2MP,PSIGHP2
REAL, INTENT(IN) :: PVEG
REAL, INTENT(OUT) :: PG1,PG2,PG3,PG4
REAL, INTENT(OUT) :: PVGST,PVGSH,PVGPT1,PVGPH1,PVGPT2,PVGPH2
END SUBROUTINE OI_FCTVEG

END INTERFACE
END MODULE MODI_OI_FCTVEG
