!depfile:open_namelist_nc.F90
MODULE MODI_OPEN_NAMELIST_NC
INTERFACE
      SUBROUTINE OPEN_NAMELIST_NC(HPROGRAM,KLUNAM,HFILE)
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! main program
INTEGER,           INTENT(OUT) :: KLUNAM   ! logical unit of namelist
 CHARACTER(LEN=28), INTENT(IN)  :: HFILE ! FAII file to open
END SUBROUTINE OPEN_NAMELIST_NC

END INTERFACE
END MODULE MODI_OPEN_NAMELIST_NC
