!depfile:pgd_bem_par.F90
MODULE MODI_PGD_BEM_PAR 
INTERFACE
      SUBROUTINE PGD_BEM_PAR (DTCO, UG, U, USS, DTB, KDIM, &
                              HPROGRAM,OAUTOSIZE)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
USE MODD_DATA_BEM_n, ONLY : DATA_BEM_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
TYPE(DATA_BEM_t), INTENT(INOUT) :: DTB
INTEGER, INTENT(IN) :: KDIM
 CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM     ! Type of program
LOGICAL,          INTENT(IN) :: OAUTOSIZE    ! T for automatic determination
INTEGER, PARAMETER                      :: NFLOOR_MAX  = 9
END SUBROUTINE PGD_BEM_PAR

END INTERFACE
END MODULE MODI_PGD_BEM_PAR 
