!depfile:drag.F90
MODULE MODI_DRAG
INTERFACE
    SUBROUTINE DRAG(HISBA, HSNOW_ISBA, HCPSURF, PTSTEP, PTG, PWG, PWGI,      &
                    PEXNS, PEXNA, PTA, PVMOD, PQA, PRR, PSR, PPS, PRS,       &
                    PVEG, PZ0, PZ0EFF, PZ0H, PWFC, PWSAT, PPSNG, PPSNV,      &
                    PZREF, PUREF, PDIRCOSZW, PDELTA, PF5, AT, PRA, PCH, PCD, &
                    PCDN, PRI, PHUG, PHUGI, PHV, PHU, PCPS, PQS, PFFG,       &
                    PFFV, PFF, PFFG_NOSNOW, PFFV_NOSNOW, PLEG_DELTA,         &
                    PLEGI_DELTA, PWR, PRHOA, PLVTT, PQSAT  )  
USE MODD_SURF_ATM_TURB_n, ONLY : SURF_ATM_TURB_t
CHARACTER(LEN=*),     INTENT(IN)  :: HISBA      ! type of ISBA version:
CHARACTER(LEN=*),     INTENT(IN)  :: HSNOW_ISBA ! 'DEF' = Default F-R snow scheme
CHARACTER(LEN=*),     INTENT(IN)  :: HCPSURF    ! option for specific heat Cp:
REAL,                 INTENT(IN) :: PTSTEP      ! timestep of ISBA (not split time step)
REAL, DIMENSION(:), INTENT(IN)   :: PTG, PWG, PWGI, PEXNS
REAL, DIMENSION(:), INTENT(IN)   :: PEXNA, PTA, PVMOD, PQA, PRR, PSR, PPS
REAL, DIMENSION(:), INTENT(IN)   :: PRS, PVEG, PZ0, PZ0H, PZ0EFF
REAL, DIMENSION(:), INTENT(IN)   :: PWFC, PWSAT, PPSNG, PPSNV, PZREF, PUREF
REAL, DIMENSION(:), INTENT(INOUT) :: PDELTA
REAL, DIMENSION(:), INTENT(IN)    :: PF5
REAL, DIMENSION(:), INTENT(IN)    :: PDIRCOSZW 
REAL, DIMENSION(:), INTENT(INOUT) :: PRA
REAL, DIMENSION(:), INTENT(INOUT) :: PCPS
REAL, DIMENSION(:), INTENT(OUT)  :: PCH, PCD, PCDN, PRI
TYPE(SURF_ATM_TURB_t), INTENT(IN) :: AT ! atmospheric turbulence parameters
REAL, DIMENSION(:), INTENT(OUT)  :: PHUG, PHUGI, PHV, PHU, PQS, PLEG_DELTA, PLEGI_DELTA
REAL, DIMENSION(:), INTENT(IN)   :: PFFV, PFF, PFFG, PFFG_NOSNOW, PFFV_NOSNOW
REAL, DIMENSION(:), INTENT(IN)   :: PWR, PRHOA, PLVTT
REAL, DIMENSION(:), INTENT(OUT), OPTIONAL :: PQSAT
END SUBROUTINE DRAG

END INTERFACE
END MODULE MODI_DRAG
