!depfile:get_grid_conf_isban.F90
MODULE MODI_GET_GRID_CONF_ISBA_n 
INTERFACE
      SUBROUTINE GET_GRID_CONF_ISBA_n (IG, &
                                       PLONMIN,PLONMAX,PLATMIN,PLATMAX,KX,KY,KL)
USE MODD_SFX_GRID_n, ONLY : GRID_t
TYPE(GRID_t), INTENT(INOUT) :: IG
REAL,               INTENT(OUT) :: PLONMIN
REAL,               INTENT(OUT) :: PLONMAX
REAL,               INTENT(OUT) :: PLATMIN
REAL,               INTENT(OUT) :: PLATMAX
INTEGER,            INTENT(OUT) :: KX
INTEGER,            INTENT(OUT) :: KY
INTEGER,            INTENT(OUT) :: KL
END SUBROUTINE GET_GRID_CONF_ISBA_n

END INTERFACE
END MODULE MODI_GET_GRID_CONF_ISBA_n 
