!depfile:init_isba_mixpar.F90
MODULE MODI_INIT_ISBA_MIXPAR 
INTERFACE
      SUBROUTINE INIT_ISBA_MIXPAR (DTCO, DTV, KDIM, IO, &
                                   KDECADE,KDECADE2,PCOVER,OCOVER,HSFTYPE)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_DATA_ISBA_n, ONLY : DATA_ISBA_t
USE MODD_ISBA_OPTIONS_n, ONLY : ISBA_OPTIONS_t
USE MODD_TYPE_DATE_SURF
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(DATA_ISBA_t), INTENT(INOUT) :: DTV
INTEGER, INTENT(IN) :: KDIM
TYPE(ISBA_OPTIONS_t), INTENT(INOUT) :: IO
INTEGER,                INTENT(IN)    :: KDECADE
INTEGER,                INTENT(OUT)   :: KDECADE2
REAL, DIMENSION(:,:),   INTENT(IN)    :: PCOVER
LOGICAL, DIMENSION(:),  INTENT(IN)    :: OCOVER
CHARACTER(LEN=*),       INTENT(IN)    :: HSFTYPE ! nature / garden
END SUBROUTINE INIT_ISBA_MIXPAR

END INTERFACE
END MODULE MODI_INIT_ISBA_MIXPAR 
