!depfile:ch_emission_fluxn.F90
MODULE MODI_CH_EMISSION_FLUX_n 
INTERFACE
      SUBROUTINE CH_EMISSION_FLUX_n (DTCO, U, CHE, SV, CHU, HPROGRAM,PSIMTIME,PSFSV, PRHOA, PTSTEP, KNBTS_MAX)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_CH_EMIS_FIELD_n, ONLY : CH_EMIS_FIELD_t
USE MODD_SV_n, ONLY : SV_t
USE MODD_CH_SURF_n, ONLY : CH_SURF_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(CH_EMIS_FIELD_t), INTENT(INOUT) :: CHE
TYPE(SV_t), INTENT(INOUT) :: SV
TYPE(CH_SURF_t), INTENT(INOUT) :: CHU
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM    ! program calling surf. schemes
REAL,               INTENT(IN)  :: PSIMTIME    ! time of simulation in sec UTC
REAL,DIMENSION(:,:),  INTENT(INOUT) :: PSFSV   ! emission flux in ppp*m/s
REAL, DIMENSION(:),   INTENT(IN)    :: PRHOA     ! air density (kg/m3)
REAL,                 INTENT(IN)    :: PTSTEP    ! atmospheric time-step                 (s)
INTEGER,              INTENT(IN)    :: KNBTS_MAX !max size of TEMISS%NETIMES
END SUBROUTINE CH_EMISSION_FLUX_n

END INTERFACE
END MODULE MODI_CH_EMISSION_FLUX_n 
