!depfile:thrmcondz.F90
MODULE MODI_THRMCONDZ
INTERFACE
    SUBROUTINE THRMCONDZ(PSANDZ,PWSATZ,PCONDDRY,PCONDSLD)
REAL,   DIMENSION(:,:), INTENT(IN) :: PSANDZ     ! soil sand fraction (-)
REAL,   DIMENSION(:,:), INTENT(IN) :: PWSATZ     ! soil porosity (m3 m-3)
REAL,   DIMENSION(:,:), INTENT(OUT):: PCONDDRY  ! soil dry thermal conductivity
REAL,   DIMENSION(:,:), INTENT(OUT):: PCONDSLD  ! soil solids thermal
END SUBROUTINE THRMCONDZ

END INTERFACE
END MODULE MODI_THRMCONDZ
