!depfile:close_write_cover_tex_lfi.F90
MODULE MODI_CLOSE_WRITE_COVER_TEX_LFI
INTERFACE
      SUBROUTINE CLOSE_WRITE_COVER_TEX_LFI(KTEX)
INTEGER, INTENT(IN) :: KTEX  ! logical unit to close
END SUBROUTINE CLOSE_WRITE_COVER_TEX_LFI

END INTERFACE
END MODULE MODI_CLOSE_WRITE_COVER_TEX_LFI
