!depfile:write_data.F90
MODULE MODI_WRITE_DATA
INTERFACE
      SUBROUTINE WRITE_DATA(HPROGRAM)
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
END SUBROUTINE WRITE_DATA

END INTERFACE
END MODULE MODI_WRITE_DATA
