!depfile:make_choice_array.F90
MODULE MODI_MAKE_CHOICE_ARRAY
INTERFACE
SUBROUTINE MAKE_CHOICE_ARRAY(HPROGRAM, KNPATCH, ODIM, HRECFM, PWORK, HDIR, KPATCH)
 CHARACTER(LEN=*), INTENT(IN) :: HPROGRAM
INTEGER, INTENT(IN) :: KNPATCH
LOGICAL, INTENT(IN) :: ODIM
 CHARACTER(LEN=*), INTENT(IN) :: HRECFM
REAL, DIMENSION(:,:), INTENT(INOUT) :: PWORK
 CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: HDIR
INTEGER, INTENT(IN), OPTIONAL :: KPATCH
END SUBROUTINE MAKE_CHOICE_ARRAY

END INTERFACE
END MODULE MODI_MAKE_CHOICE_ARRAY
