!depfile:pgd_grid_io_init.F90
MODULE MODI_PGD_GRID_IO_INIT
INTERFACE
      SUBROUTINE PGD_GRID_IO_INIT(HPROGRAM,UG,KGRID_PAR,PGRID_PAR,HGRID,ORECT,KIMAX,KJMAX,KDXRATIO,KDYRATIO)
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling READ_PGD
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
 INTEGER, OPTIONAL,               INTENT(IN)    :: KGRID_PAR ! size of PGRID_PAR
 REAL, DIMENSION(:), OPTIONAL, INTENT(IN)       :: PGRID_PAR ! grid parameters
 CHARACTER(LEN=10),     INTENT(IN), OPTIONAL    :: HGRID
 LOGICAL,               INTENT(IN), OPTIONAL    :: ORECT
 INTEGER,               INTENT(IN), OPTIONAL    :: KIMAX
 INTEGER,               INTENT(IN), OPTIONAL    :: KJMAX
 INTEGER,               INTENT(IN), OPTIONAL    :: KDXRATIO
 INTEGER,               INTENT(IN), OPTIONAL    :: KDYRATIO
END SUBROUTINE PGD_GRID_IO_INIT

END INTERFACE
END MODULE MODI_PGD_GRID_IO_INIT
