!depfile:get_qsn.F90
MODULE MODI_GET_QS_n 
INTERFACE
      SUBROUTINE GET_QS_n (DGO, D, HPROGRAM,KI,PQS)
USE MODD_DIAG_n, ONLY : DIAG_t, DIAG_OPTIONS_t
TYPE(DIAG_OPTIONS_t), INTENT(IN) :: DGO
TYPE(DIAG_t), INTENT(INOUT) :: D
 CHARACTER(LEN=6),     INTENT(IN)     :: HPROGRAM
INTEGER,              INTENT(IN)     :: KI      ! Number of points
REAL, DIMENSION(KI),  INTENT(OUT)    :: PQS     ! roughness length for momentum (m)
END SUBROUTINE GET_QS_n

END INTERFACE
END MODULE MODI_GET_QS_n 
