!depfile:read_default_flaken.F90
MODULE MODI_READ_DEFAULT_FLAKE_n 
INTERFACE
      SUBROUTINE READ_DEFAULT_FLAKE_n (CHF, DGO, DMF, F, HPROGRAM)
USE MODD_CH_FLAKE_n, ONLY : CH_FLAKE_t
USE MODD_DIAG_n, ONLY : DIAG_OPTIONS_t
USE MODD_DIAG_MISC_FLAKE_n, ONLY : DIAG_MISC_FLAKE_t
USE MODD_FLAKE_n, ONLY : FLAKE_t
TYPE(CH_FLAKE_t), INTENT(INOUT) :: CHF
TYPE(DIAG_OPTIONS_t), INTENT(INOUT) :: DGO
TYPE(DIAG_MISC_FLAKE_t), INTENT(INOUT) :: DMF
TYPE(FLAKE_t), INTENT(INOUT) :: F
 CHARACTER(LEN=6),  INTENT(IN)  :: HPROGRAM ! program calling ISBA
END SUBROUTINE READ_DEFAULT_FLAKE_n

END INTERFACE
END MODULE MODI_READ_DEFAULT_FLAKE_n 
