!depfile:put_pgd_grid.F90
MODULE MODI_PUT_PGD_GRID
INTERFACE
      SUBROUTINE PUT_PGD_GRID(HGRID,KSIZE_FULL,KGRID_PAR,PGRID_PAR)
 CHARACTER(LEN=10), INTENT(IN)   :: HGRID      ! type of horizontal grid
INTEGER,           INTENT(IN)   :: KSIZE_FULL ! number of points
INTEGER,           INTENT(IN)   :: KGRID_PAR  ! size of PGRID_PAR
REAL, DIMENSION(:), POINTER     :: PGRID_PAR  ! parameters defining this grid
END SUBROUTINE PUT_PGD_GRID

END INTERFACE
END MODULE MODI_PUT_PGD_GRID
