!depfile:prep_seaflux_netcdf.F90
MODULE MODI_PREP_SEAFLUX_NETCDF
INTERFACE
SUBROUTINE PREP_SEAFLUX_NETCDF(HPROGRAM,HSURF,HFILE,KLUOUT,PFIELD)
CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
CHARACTER(LEN=9),   INTENT(IN)  :: HSURF     ! type of field
CHARACTER(LEN=28),  INTENT(IN)  :: HFILE     ! name of file
INTEGER,            INTENT(IN)  :: KLUOUT    ! logical unit of output listing
REAL,DIMENSION(:,:), POINTER    :: PFIELD    ! field to interpolate horizontally
END SUBROUTINE PREP_SEAFLUX_NETCDF

END INTERFACE
END MODULE MODI_PREP_SEAFLUX_NETCDF
