!depfile:ice_soildif.F90
MODULE MODI_ICE_SOILDIF
INTERFACE
      SUBROUTINE ICE_SOILDIF(KK, PK, PEK, PTSTEP, PKSFC_IVEG, PLEGI, PSOILHCAPZ, PWGI_EXCESS, PPHASE)  
USE MODD_ISBA_n, ONLY : ISBA_K_t, ISBA_P_t, ISBA_PE_t
TYPE(ISBA_K_t), INTENT(INOUT) :: KK
TYPE(ISBA_P_t), INTENT(INOUT) :: PK
TYPE(ISBA_PE_t), INTENT(INOUT) :: PEK
REAL, INTENT(IN)                   :: PTSTEP  ! Model time step (s)
REAL, DIMENSION(:), INTENT(IN)      :: PKSFC_IVEG, PLEGI
REAL, DIMENSION(:,:), INTENT(IN)    :: PSOILHCAPZ
REAL, DIMENSION(:), INTENT(OUT)     :: PWGI_EXCESS
REAL, DIMENSION(:,:), INTENT(OUT)   :: PPHASE
END SUBROUTINE ICE_SOILDIF

END INTERFACE
END MODULE MODI_ICE_SOILDIF
