!depfile:vegtype_to_patch.F90
MODULE MODI_VEGTYPE_TO_PATCH
INTERFACE
    FUNCTION VEGTYPE_TO_PATCH(IVEGTYPE,INPATCH ) RESULT(IPATCH_NB) 
INTEGER,        INTENT(IN) :: IVEGTYPE !indices of vegetation type           
INTEGER,        INTENT(IN) :: INPATCH  !total number of PATCHES used 
INTEGER                    :: IPATCH_NB! PATCH index corresponding to the vegtype IVEGTYPE  
END FUNCTION VEGTYPE_TO_PATCH

END INTERFACE
END MODULE MODI_VEGTYPE_TO_PATCH
