!depfile:dslt_velgrav1d.F90
MODULE MODI_DSLT_VELGRAV1D
INTERFACE
SUBROUTINE DSLT_VELGRAV1D(PSIG, PRG, PTA, PRHODREF, PRHOP, &
                          PMU, PVGK, PDPK, PVGG, PDPG      )
REAL, DIMENSION(:,:), INTENT(IN)  :: PSIG, PRG
REAL, DIMENSION(:),   INTENT(IN)  :: PTA, PRHODREF
REAL,                 INTENT(IN)  :: PRHOP
REAL, DIMENSION(:),   INTENT(OUT) :: PMU
REAL, DIMENSION(:,:), INTENT(OUT) :: PVGK, PDPK
REAL, DIMENSION(:,:), INTENT(OUT) :: PVGG, PDPG
END SUBROUTINE DSLT_VELGRAV1D

END INTERFACE
END MODULE MODI_DSLT_VELGRAV1D
