!depfile:prep_surf_atm.F90
MODULE MODI_PREP_SURF_ATM 
INTERFACE
SUBROUTINE PREP_SURF_ATM (YSC, HPROGRAM,HATMFILE,HATMFILETYPE,HPGDFILE,HPGDFILETYPE,YDCTL)
USE MODD_SURFEX_n, ONLY : SURFEX_t
USE MODE_PREP_CTL, ONLY : PREP_CTL
TYPE(SURFEX_t), INTENT(INOUT) :: YSC
TYPE (PREP_CTL),   INTENT(INOUT) :: YDCTL
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM    ! program calling surf. schemes
 CHARACTER(LEN=28), INTENT(IN) :: HATMFILE    ! name of the Atmospheric file
 CHARACTER(LEN=6),  INTENT(IN) :: HATMFILETYPE! type of the Atmospheric file
 CHARACTER(LEN=28), INTENT(IN) :: HPGDFILE    ! name of the Atmospheric file
 CHARACTER(LEN=6),  INTENT(IN) :: HPGDFILETYPE! type of the Atmospheric file
END SUBROUTINE PREP_SURF_ATM

END INTERFACE
END MODULE MODI_PREP_SURF_ATM 
