!depfile:set_surfex_file_name_fa.F90
MODULE MODI_SET_SURFEX_FILE_NAME_FA
INTERFACE
SUBROUTINE SET_SURFEX_FILE_NAME_FA(HNAME_IN,HNAME_OUT)
 CHARACTER(LEN=*), OPTIONAL, INTENT(IN)     :: HNAME_IN
 CHARACTER(LEN=*), OPTIONAL, INTENT(OUT)    :: HNAME_OUT
END SUBROUTINE SET_SURFEX_FILE_NAME_FA

END INTERFACE
END MODULE MODI_SET_SURFEX_FILE_NAME_FA
