!depfile:pgd_tsz0_par.F90
MODULE MODI_PGD_TSZ0_PAR 
INTERFACE
      SUBROUTINE PGD_TSZ0_PAR (DTZ, &
                               HPROGRAM)
USE MODD_DATA_TSZ0_n, ONLY : DATA_TSZ0_t
TYPE(DATA_TSZ0_t), INTENT(INOUT) :: DTZ
 CHARACTER(LEN=6),    INTENT(IN)    :: HPROGRAM     ! Type of program
END SUBROUTINE PGD_TSZ0_PAR

END INTERFACE
END MODULE MODI_PGD_TSZ0_PAR 
