!depfile:write_cover_tex_end.F90
MODULE MODI_WRITE_COVER_TEX_END
INTERFACE
      SUBROUTINE WRITE_COVER_TEX_END(HPROGRAM)
 CHARACTER(LEN=6),                INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
END SUBROUTINE WRITE_COVER_TEX_END

END INTERFACE
END MODULE MODI_WRITE_COVER_TEX_END
