!depfile:treat_global_lake_depth.F90
MODULE MODI_TREAT_GLOBAL_LAKE_DEPTH 
INTERFACE
      SUBROUTINE TREAT_GLOBAL_LAKE_DEPTH (DTCO, UG, U, USS, &
                                          HPROGRAM,PDEPTH,KSTATUS)
USE MODD_DATA_COVER_n, ONLY : DATA_COVER_t
USE MODD_SURF_ATM_GRID_n, ONLY : SURF_ATM_GRID_t
USE MODD_SURF_ATM_n, ONLY : SURF_ATM_t
USE MODD_SSO_n, ONLY : SSO_t
TYPE(DATA_COVER_t), INTENT(INOUT) :: DTCO
TYPE(SURF_ATM_GRID_t), INTENT(INOUT) :: UG
TYPE(SURF_ATM_t), INTENT(INOUT) :: U
TYPE(SSO_t), INTENT(INOUT) :: USS
 CHARACTER(LEN=6),  INTENT(IN) :: HPROGRAM  ! Type of program
REAL, DIMENSION(:),INTENT(OUT):: PDEPTH    ! physiographic field
INTEGER, DIMENSION(:),INTENT(OUT):: KSTATUS   ! physiographic field
END SUBROUTINE TREAT_GLOBAL_LAKE_DEPTH

END INTERFACE
END MODULE MODI_TREAT_GLOBAL_LAKE_DEPTH 
