INTERFACE
  SUBROUTINE ARO_CONVBU(KFDIA,KLEV,KRR,PRHODJ,PRRS,PTHS,YDDDH,YDLDDH,YDMDDH)
    USE PARKIND1  ,ONLY : JPRB
    USE DDH_MIX, ONLY : TYP_DDH
    USE YOMLDDH, ONLY : TLDDH
    USE YOMMDDH, ONLY : TMDDH
    INTEGER, INTENT(IN) :: KFDIA
    INTEGER, INTENT(IN) :: KLEV
    INTEGER, INTENT(IN) :: KRR
    REAL(KIND=JPRB), DIMENSION (KFDIA,1,KLEV),  INTENT(IN) :: PRHODJ
    REAL(KIND=JPRB), DIMENSION(KFDIA,1,KLEV),   INTENT(IN) :: PTHS
    REAL(KIND=JPRB), DIMENSION(KFDIA,1,KLEV,KRR), INTENT(IN) :: PRRS
    TYPE(TYP_DDH),                       INTENT(INOUT) :: YDDDH
    TYPE(TLDDH),                         INTENT(IN) :: YDLDDH
    TYPE(TMDDH),                         INTENT(IN) :: YDMDDH
  END SUBROUTINE ARO_CONVBU
END INTERFACE
