INTERFACE
SUBROUTINE ARO_BUPROCN(KNUNBR, KBUPROCNBR)
USE PARKIND1  ,ONLY : JPIM
INTEGER(KIND=JPIM), INTENT(IN)    :: KNUNBR
INTEGER(KIND=JPIM), INTENT(INOUT) :: KBUPROCNBR(KNUNBR)
END SUBROUTINE ARO_BUPROCN
END INTERFACE

