INTERFACE
SUBROUTINE BSSLZR(PBES,KNUM)

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

INTEGER(KIND=JPIM), intent(in) :: KNUM
REAL(KIND=JPRB), intent(out)   :: PBES(:)
END SUBROUTINE bsslzr
END INTERFACE
