INTERFACE

FUNCTION DISTANCE_BETWEEN( PLAT1, PLON1, PLAT2, PLON2, LRADIANS)

USE PARKIND1, ONLY: JPRD

IMPLICIT NONE

REAL (KIND=JPRD) :: DISTANCE_BETWEEN
REAL (KIND=JPRD), INTENT(IN) :: PLAT1, PLON1, PLAT2, PLON2
LOGICAL,OPTIONAL :: LRADIANS

END FUNCTION DISTANCE_BETWEEN

END INTERFACE
