INTERFACE

 SUBROUTINE GET_LSM(ZLATS_UNI_LSM, NLONS, ZVALUES_LSM)

      USE PARKIND1, ONLY : JPIM, JPRD            

      IMPLICIT NONE

      REAL    (KIND=JPRD), ALLOCATABLE, INTENT(OUT) :: ZVALUES_LSM(:)
      INTEGER (KIND=JPIM), ALLOCATABLE, INTENT(OUT) :: NLONS(:)
      REAL    (KIND=JPRD), ALLOCATABLE, INTENT(OUT) :: ZLATS_UNI_LSM(:)
      
      REAL    (KIND=JPRD), ALLOCATABLE :: ZLATS_LSM(:), ZLONS_LSM(:)
      INTEGER (KIND=JPIM)  :: INUM, COUNT1=0
      INTEGER (KIND=JPIM)  :: IGRET, IGRIB, INFILE
      INTEGER (KIND=JPIM)  :: J
      
      LOGICAL, ALLOCATABLE :: MASK(:)
      INTEGER (KIND=JPIM), ALLOCATABLE :: NUM(:)


  END SUBROUTINE GET_LSM
END INTERFACE
