INTERFACE
SUBROUTINE GETCPARAM(KNAV,KCH,KNSAT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM) ,OPTIONAL,INTENT(OUT) :: KNAV
INTEGER(KIND=JPIM) ,OPTIONAL,INTENT(OUT) :: KCH
INTEGER(KIND=JPIM) ,OPTIONAL,INTENT(OUT) :: KNSAT
END SUBROUTINE GETCPARAM
END INTERFACE
