INTERFACE
SUBROUTINE GETCOEF_FIELD(KMSAT,KFMV_CHN,PFF_CWN,PFF_BCO,PFF_BCS,PPLANCK1,PPLANCK2)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK    ,DR_HOOK
!USE MOD_CPARAM    ,ONLY : COEF
INTEGER(KIND=JPIM), INTENT(IN) :: KMSAT
INTEGER(KIND=JPIM), INTENT(INOUT) :: KFMV_CHN
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PFF_CWN(KFMV_CHN)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PFF_BCO(KFMV_CHN)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PFF_BCS(KFMV_CHN)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PPLANCK1(KFMV_CHN)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PPLANCK2(KFMV_CHN)
END SUBROUTINE GETCOEF_FIELD
END INTERFACE
