Interface
  SUBROUTINE rtlimb_erf_tl(X,X_PRIME,ERF_PRIME)

    USE PARKIND1  ,ONLY : JPIM     ,JPRB

    IMPLICIT NONE

    REAL(KIND=JPRB), INTENT(IN)  :: X
    REAL(KIND=JPRB), INTENT(IN)  :: X_PRIME
    REAL(KIND=JPRB), INTENT(OUT) :: ERF_PRIME

  END SUBROUTINE rtlimb_erf_tl
End Interface

