#define ODB_MAINCODE 1

#include "ECMA.h"

PUBLIC void 
ECMA_print_flags_file(void)
{
  int rc = 0, io = -1;
  FILE *fp = NULL;
  cma_open_(&io, "ECMA.flags", "w", &rc, strlen("ECMA.flags"), strlen("w"));
  if (rc != 1) return; /* multi-bin file ==> forget flags-file */
  fp = CMA_get_fp(&io);
  if (!fp) return; /* pointer NULL ==> forget the flags-file ;-( */
  fprintf(fp,"-Abody=(surfbody_feedback,errstat,update_1,update_2,update_3,update_4,fcdiagnostic_body_1,fcdiagnostic_body_2,fcdiagnostic_body_3,fcdiagnostic_body_4,fcdiagnostic_body_5,fcdiagnostic_body_6,fcdiagnostic_body_7,fcdiagnostic_body_8,fcdiagnostic_body_9,fcdiagnostic_body_10,fcdiagnostic_body_11,fcdiagnostic_body_12,fcdiagnostic_body_13,fcdiagnostic_body_14,fcdiagnostic_body_15,fcdiagnostic_body_16,fcdiagnostic_body_17,fcdiagnostic_body_18,fcdiagnostic_body_19,fcdiagnostic_body_20,conv_body,scatt_body,ssmi_body,gbrad_body,radar_body,resat_averaging_kernel,auxiliary_body,allsky_body,radiance_body,gnssro_body,raingg_body,enkf_1,enkf_2,enkf_3,enkf_4,enkf_5,enkf_6,enkf_7,enkf_8,enkf_9,enkf_10,enkf_11,enkf_12,enkf_13,enkf_14,enkf_15,enkf_16,enkf_17,enkf_18,enkf_19,enkf_20,enkf_21,enkf_22,enkf_23,enkf_24,enkf_25,enkf_26,enkf_27,enkf_28,enkf_29,enkf_30,enkf_31,enkf_32,enkf_33,enkf_34,enkf_35,enkf_36,enkf_37,enkf_38,enkf_39,enkf_40,enkf_41,enkf_42,enkf_43,enkf_44,enkf_45,enkf_46,enkf_47,enkf_48,enkf_49,enkf_50,enkf_51,enkf_52,enkf_53,enkf_54,enkf_55,enkf_56,enkf_57,enkf_58,enkf_59,enkf_60,enkf_61,enkf_62,enkf_63,enkf_64,enkf_65,enkf_66,enkf_67,enkf_68,enkf_69,enkf_70,enkf_71,enkf_72,enkf_73,enkf_74,enkf_75,enkf_76,enkf_77,enkf_78,enkf_79,enkf_80,enkf_81,enkf_82,enkf_83,enkf_84,enkf_85,enkf_86,enkf_87,enkf_88,enkf_89,enkf_90,enkf_91,enkf_92,enkf_93,enkf_94,enkf_95,enkf_96,enkf_97,enkf_98,enkf_99,enkf_100,enkf_101,enkf_102,enkf_103,enkf_104,enkf_105,enkf_106,enkf_107,enkf_108,enkf_109,enkf_110,enkf_111,enkf_112,enkf_113,enkf_114,enkf_115,enkf_116,enkf_117,enkf_118,enkf_119,enkf_120,enda_1,enda_2,enda_3,enda_4,enda_5,enda_6,enda_7,enda_8,enda_9,enda_10,enda_11,enda_12,enda_13,enda_14,enda_15,enda_16,enda_17,enda_18,enda_19,enda_20,enda_21,enda_22,enda_23,enda_24,enda_25,enda_26,enda_27,enda_28,enda_29,enda_30,enda_31,enda_32,enda_33,enda_34,enda_35,enda_36,enda_37,enda_38,enda_39,enda_40,enda_41,enda_42,enda_43,enda_44,enda_45,enda_46,enda_47,enda_48,enda_49,enda_50,enda_51,enda_52,enda_53,enda_54,enda_55,enda_56,enda_57,enda_58,enda_59,enda_60,enda_61,enda_62,enda_63,enda_64,enda_65,enda_66,enda_67,enda_68,enda_69,enda_70,enda_71,enda_72,enda_73,enda_74,enda_75,enda_76,enda_77,enda_78,enda_79,enda_80,enda_81,enda_82,enda_83,enda_84,enda_85,enda_86,enda_87,enda_88,enda_89,enda_90,enda_91,enda_92,enda_93,enda_94,enda_95,enda_96,enda_97,enda_98,enda_99,enda_100,surfbody_feedback_1,surfbody_feedback_2,surfbody_feedback_3,surfbody_feedback_4,surfbody_feedback_5,surfbody_feedback_6,surfbody_feedback_7,surfbody_feedback_8,surfbody_feedback_9,surfbody_feedback_10,surfbody_feedback_11,surfbody_feedback_12,surfbody_feedback_13,surfbody_feedback_14,surfbody_feedback_15,surfbody_feedback_16,surfbody_feedback_17,surfbody_feedback_18,surfbody_feedback_19,surfbody_feedback_20,surfbody_feedback_21,surfbody_feedback_22,surfbody_feedback_23,surfbody_feedback_24,surfbody_feedback_25,surfbody_feedback_26,surfbody_feedback_27,surfbody_feedback_28,surfbody_feedback_29,surfbody_feedback_30,surfbody_feedback_31,surfbody_feedback_32,surfbody_feedback_33,surfbody_feedback_34,surfbody_feedback_35,surfbody_feedback_36,surfbody_feedback_37,surfbody_feedback_38,surfbody_feedback_39,surfbody_feedback_40,surfbody_feedback_41,surfbody_feedback_42,surfbody_feedback_43,surfbody_feedback_44,surfbody_feedback_45,surfbody_feedback_46,surfbody_feedback_47,surfbody_feedback_48,surfbody_feedback_49,surfbody_feedback_50,surfbody_feedback_51,surfbody_feedback_52,surfbody_feedback_53,surfbody_feedback_54,surfbody_feedback_55,surfbody_feedback_56,surfbody_feedback_57,surfbody_feedback_58,surfbody_feedback_59,surfbody_feedback_60,surfbody_feedback_61,surfbody_feedback_62,surfbody_feedback_63,surfbody_feedback_64,surfbody_feedback_65,surfbody_feedback_66,surfbody_feedback_67,surfbody_feedback_68,surfbody_feedback_69,surfbody_feedback_70,surfbody_feedback_71,surfbody_feedback_72,surfbody_feedback_73,surfbody_feedback_74,surfbody_feedback_75,surfbody_feedback_76,surfbody_feedback_77,surfbody_feedback_78,surfbody_feedback_79,surfbody_feedback_80,surfbody_feedback_81,surfbody_feedback_82,surfbody_feedback_83,surfbody_feedback_84,surfbody_feedback_85,surfbody_feedback_86,surfbody_feedback_87,surfbody_feedback_88,surfbody_feedback_89,surfbody_feedback_90,surfbody_feedback_91,surfbody_feedback_92,surfbody_feedback_93,surfbody_feedback_94,surfbody_feedback_95,surfbody_feedback_96,surfbody_feedback_97,surfbody_feedback_98,surfbody_feedback_99,surfbody_feedback_100)\n");
  fprintf(fp,"-Ahdr=fcdiagnostic\n");
  fprintf(fp,"-1index=hdr\n");
  fprintf(fp,"-1hdr=(auxiliary,ensemble,sat,modsurf,gbrad,raingg,conv)\n");
  fprintf(fp,"-1sat=(radiance,ssmi,scatt,satob,resat,limb,radar,radar_station,smos,gnssro,aeolus_hdr)\n");
  fprintf(fp,"-1radiance=(allsky,cloud_sink,collocated_imager_information)\n");
  cma_close_(&io, &rc);
}

PRIVATE int 
Create_Funcs(ODB_Pool *pool, int is_new, int io_method, int it)
{
  int nfuncs = 0;
  static int first_time = 1;
  static int IsConsidered[388];
  DRHOOK_START(Create_Funcs);
  if (first_time) {
    ODBMAC_INIT_IsConsidered(desc, 0);
    ODBMAC_INIT_IsConsidered(poolmask, 1);
    ODBMAC_INIT_IsConsidered(timeslot_index, 2);
    ODBMAC_INIT_IsConsidered(index, 3);
    ODBMAC_INIT_IsConsidered(hdr, 4);
    ODBMAC_INIT_IsConsidered(ensemble, 5);
    ODBMAC_INIT_IsConsidered(enkf_1, 6);
    ODBMAC_INIT_IsConsidered(enkf_2, 7);
    ODBMAC_INIT_IsConsidered(enkf_3, 8);
    ODBMAC_INIT_IsConsidered(enkf_4, 9);
    ODBMAC_INIT_IsConsidered(enkf_5, 10);
    ODBMAC_INIT_IsConsidered(enkf_6, 11);
    ODBMAC_INIT_IsConsidered(enkf_7, 12);
    ODBMAC_INIT_IsConsidered(enkf_8, 13);
    ODBMAC_INIT_IsConsidered(enkf_9, 14);
    ODBMAC_INIT_IsConsidered(enkf_10, 15);
    ODBMAC_INIT_IsConsidered(enkf_11, 16);
    ODBMAC_INIT_IsConsidered(enkf_12, 17);
    ODBMAC_INIT_IsConsidered(enkf_13, 18);
    ODBMAC_INIT_IsConsidered(enkf_14, 19);
    ODBMAC_INIT_IsConsidered(enkf_15, 20);
    ODBMAC_INIT_IsConsidered(enkf_16, 21);
    ODBMAC_INIT_IsConsidered(enkf_17, 22);
    ODBMAC_INIT_IsConsidered(enkf_18, 23);
    ODBMAC_INIT_IsConsidered(enkf_19, 24);
    ODBMAC_INIT_IsConsidered(enkf_20, 25);
    ODBMAC_INIT_IsConsidered(enkf_21, 26);
    ODBMAC_INIT_IsConsidered(enkf_22, 27);
    ODBMAC_INIT_IsConsidered(enkf_23, 28);
    ODBMAC_INIT_IsConsidered(enkf_24, 29);
    ODBMAC_INIT_IsConsidered(enkf_25, 30);
    ODBMAC_INIT_IsConsidered(enkf_26, 31);
    ODBMAC_INIT_IsConsidered(enkf_27, 32);
    ODBMAC_INIT_IsConsidered(enkf_28, 33);
    ODBMAC_INIT_IsConsidered(enkf_29, 34);
    ODBMAC_INIT_IsConsidered(enkf_30, 35);
    ODBMAC_INIT_IsConsidered(enkf_31, 36);
    ODBMAC_INIT_IsConsidered(enkf_32, 37);
    ODBMAC_INIT_IsConsidered(enkf_33, 38);
    ODBMAC_INIT_IsConsidered(enkf_34, 39);
    ODBMAC_INIT_IsConsidered(enkf_35, 40);
    ODBMAC_INIT_IsConsidered(enkf_36, 41);
    ODBMAC_INIT_IsConsidered(enkf_37, 42);
    ODBMAC_INIT_IsConsidered(enkf_38, 43);
    ODBMAC_INIT_IsConsidered(enkf_39, 44);
    ODBMAC_INIT_IsConsidered(enkf_40, 45);
    ODBMAC_INIT_IsConsidered(enkf_41, 46);
    ODBMAC_INIT_IsConsidered(enkf_42, 47);
    ODBMAC_INIT_IsConsidered(enkf_43, 48);
    ODBMAC_INIT_IsConsidered(enkf_44, 49);
    ODBMAC_INIT_IsConsidered(enkf_45, 50);
    ODBMAC_INIT_IsConsidered(enkf_46, 51);
    ODBMAC_INIT_IsConsidered(enkf_47, 52);
    ODBMAC_INIT_IsConsidered(enkf_48, 53);
    ODBMAC_INIT_IsConsidered(enkf_49, 54);
    ODBMAC_INIT_IsConsidered(enkf_50, 55);
    ODBMAC_INIT_IsConsidered(enkf_51, 56);
    ODBMAC_INIT_IsConsidered(enkf_52, 57);
    ODBMAC_INIT_IsConsidered(enkf_53, 58);
    ODBMAC_INIT_IsConsidered(enkf_54, 59);
    ODBMAC_INIT_IsConsidered(enkf_55, 60);
    ODBMAC_INIT_IsConsidered(enkf_56, 61);
    ODBMAC_INIT_IsConsidered(enkf_57, 62);
    ODBMAC_INIT_IsConsidered(enkf_58, 63);
    ODBMAC_INIT_IsConsidered(enkf_59, 64);
    ODBMAC_INIT_IsConsidered(enkf_60, 65);
    ODBMAC_INIT_IsConsidered(enkf_61, 66);
    ODBMAC_INIT_IsConsidered(enkf_62, 67);
    ODBMAC_INIT_IsConsidered(enkf_63, 68);
    ODBMAC_INIT_IsConsidered(enkf_64, 69);
    ODBMAC_INIT_IsConsidered(enkf_65, 70);
    ODBMAC_INIT_IsConsidered(enkf_66, 71);
    ODBMAC_INIT_IsConsidered(enkf_67, 72);
    ODBMAC_INIT_IsConsidered(enkf_68, 73);
    ODBMAC_INIT_IsConsidered(enkf_69, 74);
    ODBMAC_INIT_IsConsidered(enkf_70, 75);
    ODBMAC_INIT_IsConsidered(enkf_71, 76);
    ODBMAC_INIT_IsConsidered(enkf_72, 77);
    ODBMAC_INIT_IsConsidered(enkf_73, 78);
    ODBMAC_INIT_IsConsidered(enkf_74, 79);
    ODBMAC_INIT_IsConsidered(enkf_75, 80);
    ODBMAC_INIT_IsConsidered(enkf_76, 81);
    ODBMAC_INIT_IsConsidered(enkf_77, 82);
    ODBMAC_INIT_IsConsidered(enkf_78, 83);
    ODBMAC_INIT_IsConsidered(enkf_79, 84);
    ODBMAC_INIT_IsConsidered(enkf_80, 85);
    ODBMAC_INIT_IsConsidered(enkf_81, 86);
    ODBMAC_INIT_IsConsidered(enkf_82, 87);
    ODBMAC_INIT_IsConsidered(enkf_83, 88);
    ODBMAC_INIT_IsConsidered(enkf_84, 89);
    ODBMAC_INIT_IsConsidered(enkf_85, 90);
    ODBMAC_INIT_IsConsidered(enkf_86, 91);
    ODBMAC_INIT_IsConsidered(enkf_87, 92);
    ODBMAC_INIT_IsConsidered(enkf_88, 93);
    ODBMAC_INIT_IsConsidered(enkf_89, 94);
    ODBMAC_INIT_IsConsidered(enkf_90, 95);
    ODBMAC_INIT_IsConsidered(enkf_91, 96);
    ODBMAC_INIT_IsConsidered(enkf_92, 97);
    ODBMAC_INIT_IsConsidered(enkf_93, 98);
    ODBMAC_INIT_IsConsidered(enkf_94, 99);
    ODBMAC_INIT_IsConsidered(enkf_95, 100);
    ODBMAC_INIT_IsConsidered(enkf_96, 101);
    ODBMAC_INIT_IsConsidered(enkf_97, 102);
    ODBMAC_INIT_IsConsidered(enkf_98, 103);
    ODBMAC_INIT_IsConsidered(enkf_99, 104);
    ODBMAC_INIT_IsConsidered(enkf_100, 105);
    ODBMAC_INIT_IsConsidered(enkf_101, 106);
    ODBMAC_INIT_IsConsidered(enkf_102, 107);
    ODBMAC_INIT_IsConsidered(enkf_103, 108);
    ODBMAC_INIT_IsConsidered(enkf_104, 109);
    ODBMAC_INIT_IsConsidered(enkf_105, 110);
    ODBMAC_INIT_IsConsidered(enkf_106, 111);
    ODBMAC_INIT_IsConsidered(enkf_107, 112);
    ODBMAC_INIT_IsConsidered(enkf_108, 113);
    ODBMAC_INIT_IsConsidered(enkf_109, 114);
    ODBMAC_INIT_IsConsidered(enkf_110, 115);
    ODBMAC_INIT_IsConsidered(enkf_111, 116);
    ODBMAC_INIT_IsConsidered(enkf_112, 117);
    ODBMAC_INIT_IsConsidered(enkf_113, 118);
    ODBMAC_INIT_IsConsidered(enkf_114, 119);
    ODBMAC_INIT_IsConsidered(enkf_115, 120);
    ODBMAC_INIT_IsConsidered(enkf_116, 121);
    ODBMAC_INIT_IsConsidered(enkf_117, 122);
    ODBMAC_INIT_IsConsidered(enkf_118, 123);
    ODBMAC_INIT_IsConsidered(enkf_119, 124);
    ODBMAC_INIT_IsConsidered(enkf_120, 125);
    ODBMAC_INIT_IsConsidered(enda_1, 126);
    ODBMAC_INIT_IsConsidered(enda_2, 127);
    ODBMAC_INIT_IsConsidered(enda_3, 128);
    ODBMAC_INIT_IsConsidered(enda_4, 129);
    ODBMAC_INIT_IsConsidered(enda_5, 130);
    ODBMAC_INIT_IsConsidered(enda_6, 131);
    ODBMAC_INIT_IsConsidered(enda_7, 132);
    ODBMAC_INIT_IsConsidered(enda_8, 133);
    ODBMAC_INIT_IsConsidered(enda_9, 134);
    ODBMAC_INIT_IsConsidered(enda_10, 135);
    ODBMAC_INIT_IsConsidered(enda_11, 136);
    ODBMAC_INIT_IsConsidered(enda_12, 137);
    ODBMAC_INIT_IsConsidered(enda_13, 138);
    ODBMAC_INIT_IsConsidered(enda_14, 139);
    ODBMAC_INIT_IsConsidered(enda_15, 140);
    ODBMAC_INIT_IsConsidered(enda_16, 141);
    ODBMAC_INIT_IsConsidered(enda_17, 142);
    ODBMAC_INIT_IsConsidered(enda_18, 143);
    ODBMAC_INIT_IsConsidered(enda_19, 144);
    ODBMAC_INIT_IsConsidered(enda_20, 145);
    ODBMAC_INIT_IsConsidered(enda_21, 146);
    ODBMAC_INIT_IsConsidered(enda_22, 147);
    ODBMAC_INIT_IsConsidered(enda_23, 148);
    ODBMAC_INIT_IsConsidered(enda_24, 149);
    ODBMAC_INIT_IsConsidered(enda_25, 150);
    ODBMAC_INIT_IsConsidered(enda_26, 151);
    ODBMAC_INIT_IsConsidered(enda_27, 152);
    ODBMAC_INIT_IsConsidered(enda_28, 153);
    ODBMAC_INIT_IsConsidered(enda_29, 154);
    ODBMAC_INIT_IsConsidered(enda_30, 155);
    ODBMAC_INIT_IsConsidered(enda_31, 156);
    ODBMAC_INIT_IsConsidered(enda_32, 157);
    ODBMAC_INIT_IsConsidered(enda_33, 158);
    ODBMAC_INIT_IsConsidered(enda_34, 159);
    ODBMAC_INIT_IsConsidered(enda_35, 160);
    ODBMAC_INIT_IsConsidered(enda_36, 161);
    ODBMAC_INIT_IsConsidered(enda_37, 162);
    ODBMAC_INIT_IsConsidered(enda_38, 163);
    ODBMAC_INIT_IsConsidered(enda_39, 164);
    ODBMAC_INIT_IsConsidered(enda_40, 165);
    ODBMAC_INIT_IsConsidered(enda_41, 166);
    ODBMAC_INIT_IsConsidered(enda_42, 167);
    ODBMAC_INIT_IsConsidered(enda_43, 168);
    ODBMAC_INIT_IsConsidered(enda_44, 169);
    ODBMAC_INIT_IsConsidered(enda_45, 170);
    ODBMAC_INIT_IsConsidered(enda_46, 171);
    ODBMAC_INIT_IsConsidered(enda_47, 172);
    ODBMAC_INIT_IsConsidered(enda_48, 173);
    ODBMAC_INIT_IsConsidered(enda_49, 174);
    ODBMAC_INIT_IsConsidered(enda_50, 175);
    ODBMAC_INIT_IsConsidered(enda_51, 176);
    ODBMAC_INIT_IsConsidered(enda_52, 177);
    ODBMAC_INIT_IsConsidered(enda_53, 178);
    ODBMAC_INIT_IsConsidered(enda_54, 179);
    ODBMAC_INIT_IsConsidered(enda_55, 180);
    ODBMAC_INIT_IsConsidered(enda_56, 181);
    ODBMAC_INIT_IsConsidered(enda_57, 182);
    ODBMAC_INIT_IsConsidered(enda_58, 183);
    ODBMAC_INIT_IsConsidered(enda_59, 184);
    ODBMAC_INIT_IsConsidered(enda_60, 185);
    ODBMAC_INIT_IsConsidered(enda_61, 186);
    ODBMAC_INIT_IsConsidered(enda_62, 187);
    ODBMAC_INIT_IsConsidered(enda_63, 188);
    ODBMAC_INIT_IsConsidered(enda_64, 189);
    ODBMAC_INIT_IsConsidered(enda_65, 190);
    ODBMAC_INIT_IsConsidered(enda_66, 191);
    ODBMAC_INIT_IsConsidered(enda_67, 192);
    ODBMAC_INIT_IsConsidered(enda_68, 193);
    ODBMAC_INIT_IsConsidered(enda_69, 194);
    ODBMAC_INIT_IsConsidered(enda_70, 195);
    ODBMAC_INIT_IsConsidered(enda_71, 196);
    ODBMAC_INIT_IsConsidered(enda_72, 197);
    ODBMAC_INIT_IsConsidered(enda_73, 198);
    ODBMAC_INIT_IsConsidered(enda_74, 199);
    ODBMAC_INIT_IsConsidered(enda_75, 200);
    ODBMAC_INIT_IsConsidered(enda_76, 201);
    ODBMAC_INIT_IsConsidered(enda_77, 202);
    ODBMAC_INIT_IsConsidered(enda_78, 203);
    ODBMAC_INIT_IsConsidered(enda_79, 204);
    ODBMAC_INIT_IsConsidered(enda_80, 205);
    ODBMAC_INIT_IsConsidered(enda_81, 206);
    ODBMAC_INIT_IsConsidered(enda_82, 207);
    ODBMAC_INIT_IsConsidered(enda_83, 208);
    ODBMAC_INIT_IsConsidered(enda_84, 209);
    ODBMAC_INIT_IsConsidered(enda_85, 210);
    ODBMAC_INIT_IsConsidered(enda_86, 211);
    ODBMAC_INIT_IsConsidered(enda_87, 212);
    ODBMAC_INIT_IsConsidered(enda_88, 213);
    ODBMAC_INIT_IsConsidered(enda_89, 214);
    ODBMAC_INIT_IsConsidered(enda_90, 215);
    ODBMAC_INIT_IsConsidered(enda_91, 216);
    ODBMAC_INIT_IsConsidered(enda_92, 217);
    ODBMAC_INIT_IsConsidered(enda_93, 218);
    ODBMAC_INIT_IsConsidered(enda_94, 219);
    ODBMAC_INIT_IsConsidered(enda_95, 220);
    ODBMAC_INIT_IsConsidered(enda_96, 221);
    ODBMAC_INIT_IsConsidered(enda_97, 222);
    ODBMAC_INIT_IsConsidered(enda_98, 223);
    ODBMAC_INIT_IsConsidered(enda_99, 224);
    ODBMAC_INIT_IsConsidered(enda_100, 225);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_1, 226);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_2, 227);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_3, 228);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_4, 229);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_5, 230);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_6, 231);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_7, 232);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_8, 233);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_9, 234);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_10, 235);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_11, 236);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_12, 237);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_13, 238);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_14, 239);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_15, 240);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_16, 241);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_17, 242);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_18, 243);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_19, 244);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_20, 245);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_21, 246);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_22, 247);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_23, 248);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_24, 249);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_25, 250);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_26, 251);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_27, 252);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_28, 253);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_29, 254);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_30, 255);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_31, 256);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_32, 257);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_33, 258);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_34, 259);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_35, 260);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_36, 261);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_37, 262);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_38, 263);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_39, 264);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_40, 265);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_41, 266);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_42, 267);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_43, 268);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_44, 269);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_45, 270);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_46, 271);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_47, 272);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_48, 273);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_49, 274);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_50, 275);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_51, 276);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_52, 277);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_53, 278);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_54, 279);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_55, 280);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_56, 281);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_57, 282);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_58, 283);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_59, 284);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_60, 285);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_61, 286);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_62, 287);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_63, 288);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_64, 289);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_65, 290);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_66, 291);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_67, 292);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_68, 293);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_69, 294);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_70, 295);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_71, 296);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_72, 297);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_73, 298);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_74, 299);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_75, 300);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_76, 301);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_77, 302);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_78, 303);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_79, 304);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_80, 305);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_81, 306);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_82, 307);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_83, 308);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_84, 309);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_85, 310);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_86, 311);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_87, 312);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_88, 313);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_89, 314);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_90, 315);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_91, 316);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_92, 317);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_93, 318);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_94, 319);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_95, 320);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_96, 321);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_97, 322);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_98, 323);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_99, 324);
    ODBMAC_INIT_IsConsidered(surfbody_feedback_100, 325);
    ODBMAC_INIT_IsConsidered(fcdiagnostic, 326);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_1, 327);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_2, 328);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_3, 329);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_4, 330);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_5, 331);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_6, 332);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_7, 333);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_8, 334);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_9, 335);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_10, 336);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_11, 337);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_12, 338);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_13, 339);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_14, 340);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_15, 341);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_16, 342);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_17, 343);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_18, 344);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_19, 345);
    ODBMAC_INIT_IsConsidered(fcdiagnostic_body_20, 346);
    ODBMAC_INIT_IsConsidered(gbrad, 347);
    ODBMAC_INIT_IsConsidered(gbrad_body, 348);
    ODBMAC_INIT_IsConsidered(raingg, 349);
    ODBMAC_INIT_IsConsidered(raingg_body, 350);
    ODBMAC_INIT_IsConsidered(conv, 351);
    ODBMAC_INIT_IsConsidered(conv_body, 352);
    ODBMAC_INIT_IsConsidered(sat, 353);
    ODBMAC_INIT_IsConsidered(modsurf, 354);
    ODBMAC_INIT_IsConsidered(surfbody_feedback, 355);
    ODBMAC_INIT_IsConsidered(radiance, 356);
    ODBMAC_INIT_IsConsidered(radiance_body, 357);
    ODBMAC_INIT_IsConsidered(allsky, 358);
    ODBMAC_INIT_IsConsidered(allsky_body, 359);
    ODBMAC_INIT_IsConsidered(cloud_sink, 360);
    ODBMAC_INIT_IsConsidered(collocated_imager_information, 361);
    ODBMAC_INIT_IsConsidered(auxiliary, 362);
    ODBMAC_INIT_IsConsidered(auxiliary_body, 363);
    ODBMAC_INIT_IsConsidered(resat, 364);
    ODBMAC_INIT_IsConsidered(resat_averaging_kernel, 365);
    ODBMAC_INIT_IsConsidered(gnssro, 366);
    ODBMAC_INIT_IsConsidered(gnssro_body, 367);
    ODBMAC_INIT_IsConsidered(satob, 368);
    ODBMAC_INIT_IsConsidered(scatt, 369);
    ODBMAC_INIT_IsConsidered(scatt_body, 370);
    ODBMAC_INIT_IsConsidered(ssmi, 371);
    ODBMAC_INIT_IsConsidered(ssmi_body, 372);
    ODBMAC_INIT_IsConsidered(smos, 373);
    ODBMAC_INIT_IsConsidered(radar_station, 374);
    ODBMAC_INIT_IsConsidered(radar, 375);
    ODBMAC_INIT_IsConsidered(radar_body, 376);
    ODBMAC_INIT_IsConsidered(limb, 377);
    ODBMAC_INIT_IsConsidered(body, 378);
    ODBMAC_INIT_IsConsidered(errstat, 379);
    ODBMAC_INIT_IsConsidered(update_1, 380);
    ODBMAC_INIT_IsConsidered(update_2, 381);
    ODBMAC_INIT_IsConsidered(update_3, 382);
    ODBMAC_INIT_IsConsidered(update_4, 383);
    ODBMAC_INIT_IsConsidered(aeolus_hdr, 384);
    ODBMAC_INIT_IsConsidered(aeolus_auxmet, 385);
    ODBMAC_INIT_IsConsidered(aeolus_l2c, 386);
    ODBMAC_INIT_IsConsidered(aeolus_l2b, 387);
    first_time = 0;
  } /* if (first_time) */
  ODBMAC_CREATE_TABLE(ECMA, desc, 0, 1);
  ODBMAC_CREATE_TABLE(ECMA, poolmask, 1, 1);
  ODBMAC_CREATE_TABLE(ECMA, timeslot_index, 2, 1);
  ODBMAC_CREATE_TABLE(ECMA, index, 3, 1);
  ODBMAC_CREATE_TABLE(ECMA, hdr, 4, 1);
  ODBMAC_CREATE_TABLE(ECMA, ensemble, 5, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_1, 6, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_2, 7, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_3, 8, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_4, 9, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_5, 10, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_6, 11, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_7, 12, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_8, 13, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_9, 14, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_10, 15, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_11, 16, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_12, 17, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_13, 18, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_14, 19, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_15, 20, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_16, 21, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_17, 22, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_18, 23, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_19, 24, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_20, 25, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_21, 26, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_22, 27, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_23, 28, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_24, 29, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_25, 30, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_26, 31, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_27, 32, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_28, 33, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_29, 34, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_30, 35, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_31, 36, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_32, 37, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_33, 38, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_34, 39, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_35, 40, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_36, 41, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_37, 42, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_38, 43, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_39, 44, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_40, 45, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_41, 46, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_42, 47, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_43, 48, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_44, 49, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_45, 50, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_46, 51, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_47, 52, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_48, 53, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_49, 54, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_50, 55, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_51, 56, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_52, 57, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_53, 58, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_54, 59, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_55, 60, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_56, 61, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_57, 62, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_58, 63, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_59, 64, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_60, 65, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_61, 66, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_62, 67, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_63, 68, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_64, 69, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_65, 70, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_66, 71, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_67, 72, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_68, 73, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_69, 74, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_70, 75, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_71, 76, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_72, 77, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_73, 78, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_74, 79, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_75, 80, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_76, 81, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_77, 82, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_78, 83, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_79, 84, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_80, 85, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_81, 86, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_82, 87, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_83, 88, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_84, 89, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_85, 90, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_86, 91, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_87, 92, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_88, 93, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_89, 94, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_90, 95, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_91, 96, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_92, 97, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_93, 98, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_94, 99, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_95, 100, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_96, 101, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_97, 102, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_98, 103, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_99, 104, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_100, 105, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_101, 106, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_102, 107, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_103, 108, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_104, 109, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_105, 110, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_106, 111, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_107, 112, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_108, 113, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_109, 114, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_110, 115, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_111, 116, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_112, 117, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_113, 118, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_114, 119, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_115, 120, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_116, 121, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_117, 122, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_118, 123, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_119, 124, 1);
  ODBMAC_CREATE_TABLE(ECMA, enkf_120, 125, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_1, 126, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_2, 127, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_3, 128, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_4, 129, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_5, 130, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_6, 131, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_7, 132, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_8, 133, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_9, 134, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_10, 135, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_11, 136, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_12, 137, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_13, 138, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_14, 139, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_15, 140, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_16, 141, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_17, 142, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_18, 143, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_19, 144, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_20, 145, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_21, 146, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_22, 147, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_23, 148, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_24, 149, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_25, 150, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_26, 151, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_27, 152, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_28, 153, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_29, 154, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_30, 155, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_31, 156, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_32, 157, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_33, 158, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_34, 159, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_35, 160, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_36, 161, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_37, 162, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_38, 163, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_39, 164, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_40, 165, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_41, 166, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_42, 167, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_43, 168, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_44, 169, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_45, 170, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_46, 171, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_47, 172, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_48, 173, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_49, 174, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_50, 175, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_51, 176, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_52, 177, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_53, 178, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_54, 179, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_55, 180, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_56, 181, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_57, 182, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_58, 183, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_59, 184, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_60, 185, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_61, 186, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_62, 187, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_63, 188, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_64, 189, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_65, 190, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_66, 191, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_67, 192, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_68, 193, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_69, 194, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_70, 195, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_71, 196, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_72, 197, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_73, 198, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_74, 199, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_75, 200, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_76, 201, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_77, 202, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_78, 203, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_79, 204, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_80, 205, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_81, 206, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_82, 207, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_83, 208, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_84, 209, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_85, 210, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_86, 211, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_87, 212, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_88, 213, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_89, 214, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_90, 215, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_91, 216, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_92, 217, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_93, 218, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_94, 219, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_95, 220, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_96, 221, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_97, 222, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_98, 223, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_99, 224, 1);
  ODBMAC_CREATE_TABLE(ECMA, enda_100, 225, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_1, 226, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_2, 227, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_3, 228, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_4, 229, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_5, 230, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_6, 231, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_7, 232, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_8, 233, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_9, 234, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_10, 235, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_11, 236, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_12, 237, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_13, 238, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_14, 239, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_15, 240, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_16, 241, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_17, 242, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_18, 243, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_19, 244, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_20, 245, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_21, 246, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_22, 247, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_23, 248, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_24, 249, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_25, 250, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_26, 251, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_27, 252, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_28, 253, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_29, 254, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_30, 255, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_31, 256, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_32, 257, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_33, 258, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_34, 259, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_35, 260, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_36, 261, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_37, 262, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_38, 263, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_39, 264, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_40, 265, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_41, 266, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_42, 267, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_43, 268, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_44, 269, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_45, 270, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_46, 271, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_47, 272, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_48, 273, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_49, 274, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_50, 275, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_51, 276, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_52, 277, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_53, 278, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_54, 279, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_55, 280, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_56, 281, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_57, 282, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_58, 283, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_59, 284, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_60, 285, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_61, 286, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_62, 287, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_63, 288, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_64, 289, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_65, 290, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_66, 291, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_67, 292, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_68, 293, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_69, 294, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_70, 295, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_71, 296, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_72, 297, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_73, 298, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_74, 299, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_75, 300, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_76, 301, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_77, 302, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_78, 303, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_79, 304, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_80, 305, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_81, 306, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_82, 307, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_83, 308, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_84, 309, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_85, 310, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_86, 311, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_87, 312, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_88, 313, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_89, 314, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_90, 315, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_91, 316, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_92, 317, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_93, 318, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_94, 319, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_95, 320, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_96, 321, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_97, 322, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_98, 323, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_99, 324, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback_100, 325, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic, 326, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_1, 327, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_2, 328, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_3, 329, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_4, 330, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_5, 331, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_6, 332, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_7, 333, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_8, 334, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_9, 335, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_10, 336, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_11, 337, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_12, 338, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_13, 339, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_14, 340, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_15, 341, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_16, 342, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_17, 343, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_18, 344, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_19, 345, 1);
  ODBMAC_CREATE_TABLE(ECMA, fcdiagnostic_body_20, 346, 1);
  ODBMAC_CREATE_TABLE(ECMA, gbrad, 347, 1);
  ODBMAC_CREATE_TABLE(ECMA, gbrad_body, 348, 1);
  ODBMAC_CREATE_TABLE(ECMA, raingg, 349, 1);
  ODBMAC_CREATE_TABLE(ECMA, raingg_body, 350, 1);
  ODBMAC_CREATE_TABLE(ECMA, conv, 351, 1);
  ODBMAC_CREATE_TABLE(ECMA, conv_body, 352, 1);
  ODBMAC_CREATE_TABLE(ECMA, sat, 353, 1);
  ODBMAC_CREATE_TABLE(ECMA, modsurf, 354, 1);
  ODBMAC_CREATE_TABLE(ECMA, surfbody_feedback, 355, 1);
  ODBMAC_CREATE_TABLE(ECMA, radiance, 356, 1);
  ODBMAC_CREATE_TABLE(ECMA, radiance_body, 357, 1);
  ODBMAC_CREATE_TABLE(ECMA, allsky, 358, 1);
  ODBMAC_CREATE_TABLE(ECMA, allsky_body, 359, 1);
  ODBMAC_CREATE_TABLE(ECMA, cloud_sink, 360, 1);
  ODBMAC_CREATE_TABLE(ECMA, collocated_imager_information, 361, 1);
  ODBMAC_CREATE_TABLE(ECMA, auxiliary, 362, 1);
  ODBMAC_CREATE_TABLE(ECMA, auxiliary_body, 363, 1);
  ODBMAC_CREATE_TABLE(ECMA, resat, 364, 1);
  ODBMAC_CREATE_TABLE(ECMA, resat_averaging_kernel, 365, 1);
  ODBMAC_CREATE_TABLE(ECMA, gnssro, 366, 1);
  ODBMAC_CREATE_TABLE(ECMA, gnssro_body, 367, 1);
  ODBMAC_CREATE_TABLE(ECMA, satob, 368, 1);
  ODBMAC_CREATE_TABLE(ECMA, scatt, 369, 1);
  ODBMAC_CREATE_TABLE(ECMA, scatt_body, 370, 1);
  ODBMAC_CREATE_TABLE(ECMA, ssmi, 371, 1);
  ODBMAC_CREATE_TABLE(ECMA, ssmi_body, 372, 1);
  ODBMAC_CREATE_TABLE(ECMA, smos, 373, 1);
  ODBMAC_CREATE_TABLE(ECMA, radar_station, 374, 1);
  ODBMAC_CREATE_TABLE(ECMA, radar, 375, 1);
  ODBMAC_CREATE_TABLE(ECMA, radar_body, 376, 1);
  ODBMAC_CREATE_TABLE(ECMA, limb, 377, 1);
  ODBMAC_CREATE_TABLE(ECMA, body, 378, 1);
  ODBMAC_CREATE_TABLE(ECMA, errstat, 379, 1);
  ODBMAC_CREATE_TABLE(ECMA, update_1, 380, 1);
  ODBMAC_CREATE_TABLE(ECMA, update_2, 381, 1);
  ODBMAC_CREATE_TABLE(ECMA, update_3, 382, 1);
  ODBMAC_CREATE_TABLE(ECMA, update_4, 383, 1);
  ODBMAC_CREATE_TABLE(ECMA, aeolus_hdr, 384, 1);
  ODBMAC_CREATE_TABLE(ECMA, aeolus_auxmet, 385, 1);
  ODBMAC_CREATE_TABLE(ECMA, aeolus_l2c, 386, 1);
  ODBMAC_CREATE_TABLE(ECMA, aeolus_l2b, 387, 1);
  DRHOOK_END(0);
  return nfuncs;
}

PRIVATE int
Load_Pool(ODB_Pool *P, int io_method)
{
  int rc = 0;
  int Nbytes = 0;
  ODB_Funcs *pf = P->funcs;
  if (io_method != 5) {
    Call_TABLE_Load(desc, pf, 1);
    Call_TABLE_Load(poolmask, pf, 1);
    Call_TABLE_Load(timeslot_index, pf, 1);
    Call_TABLE_Load(index, pf, 1);
    Call_TABLE_Load(hdr, pf, 1);
    Call_TABLE_Load(ensemble, pf, 1);
    Call_TABLE_Load(enkf_1, pf, 1);
    Call_TABLE_Load(enkf_2, pf, 1);
    Call_TABLE_Load(enkf_3, pf, 1);
    Call_TABLE_Load(enkf_4, pf, 1);
    Call_TABLE_Load(enkf_5, pf, 1);
    Call_TABLE_Load(enkf_6, pf, 1);
    Call_TABLE_Load(enkf_7, pf, 1);
    Call_TABLE_Load(enkf_8, pf, 1);
    Call_TABLE_Load(enkf_9, pf, 1);
    Call_TABLE_Load(enkf_10, pf, 1);
    Call_TABLE_Load(enkf_11, pf, 1);
    Call_TABLE_Load(enkf_12, pf, 1);
    Call_TABLE_Load(enkf_13, pf, 1);
    Call_TABLE_Load(enkf_14, pf, 1);
    Call_TABLE_Load(enkf_15, pf, 1);
    Call_TABLE_Load(enkf_16, pf, 1);
    Call_TABLE_Load(enkf_17, pf, 1);
    Call_TABLE_Load(enkf_18, pf, 1);
    Call_TABLE_Load(enkf_19, pf, 1);
    Call_TABLE_Load(enkf_20, pf, 1);
    Call_TABLE_Load(enkf_21, pf, 1);
    Call_TABLE_Load(enkf_22, pf, 1);
    Call_TABLE_Load(enkf_23, pf, 1);
    Call_TABLE_Load(enkf_24, pf, 1);
    Call_TABLE_Load(enkf_25, pf, 1);
    Call_TABLE_Load(enkf_26, pf, 1);
    Call_TABLE_Load(enkf_27, pf, 1);
    Call_TABLE_Load(enkf_28, pf, 1);
    Call_TABLE_Load(enkf_29, pf, 1);
    Call_TABLE_Load(enkf_30, pf, 1);
    Call_TABLE_Load(enkf_31, pf, 1);
    Call_TABLE_Load(enkf_32, pf, 1);
    Call_TABLE_Load(enkf_33, pf, 1);
    Call_TABLE_Load(enkf_34, pf, 1);
    Call_TABLE_Load(enkf_35, pf, 1);
    Call_TABLE_Load(enkf_36, pf, 1);
    Call_TABLE_Load(enkf_37, pf, 1);
    Call_TABLE_Load(enkf_38, pf, 1);
    Call_TABLE_Load(enkf_39, pf, 1);
    Call_TABLE_Load(enkf_40, pf, 1);
    Call_TABLE_Load(enkf_41, pf, 1);
    Call_TABLE_Load(enkf_42, pf, 1);
    Call_TABLE_Load(enkf_43, pf, 1);
    Call_TABLE_Load(enkf_44, pf, 1);
    Call_TABLE_Load(enkf_45, pf, 1);
    Call_TABLE_Load(enkf_46, pf, 1);
    Call_TABLE_Load(enkf_47, pf, 1);
    Call_TABLE_Load(enkf_48, pf, 1);
    Call_TABLE_Load(enkf_49, pf, 1);
    Call_TABLE_Load(enkf_50, pf, 1);
    Call_TABLE_Load(enkf_51, pf, 1);
    Call_TABLE_Load(enkf_52, pf, 1);
    Call_TABLE_Load(enkf_53, pf, 1);
    Call_TABLE_Load(enkf_54, pf, 1);
    Call_TABLE_Load(enkf_55, pf, 1);
    Call_TABLE_Load(enkf_56, pf, 1);
    Call_TABLE_Load(enkf_57, pf, 1);
    Call_TABLE_Load(enkf_58, pf, 1);
    Call_TABLE_Load(enkf_59, pf, 1);
    Call_TABLE_Load(enkf_60, pf, 1);
    Call_TABLE_Load(enkf_61, pf, 1);
    Call_TABLE_Load(enkf_62, pf, 1);
    Call_TABLE_Load(enkf_63, pf, 1);
    Call_TABLE_Load(enkf_64, pf, 1);
    Call_TABLE_Load(enkf_65, pf, 1);
    Call_TABLE_Load(enkf_66, pf, 1);
    Call_TABLE_Load(enkf_67, pf, 1);
    Call_TABLE_Load(enkf_68, pf, 1);
    Call_TABLE_Load(enkf_69, pf, 1);
    Call_TABLE_Load(enkf_70, pf, 1);
    Call_TABLE_Load(enkf_71, pf, 1);
    Call_TABLE_Load(enkf_72, pf, 1);
    Call_TABLE_Load(enkf_73, pf, 1);
    Call_TABLE_Load(enkf_74, pf, 1);
    Call_TABLE_Load(enkf_75, pf, 1);
    Call_TABLE_Load(enkf_76, pf, 1);
    Call_TABLE_Load(enkf_77, pf, 1);
    Call_TABLE_Load(enkf_78, pf, 1);
    Call_TABLE_Load(enkf_79, pf, 1);
    Call_TABLE_Load(enkf_80, pf, 1);
    Call_TABLE_Load(enkf_81, pf, 1);
    Call_TABLE_Load(enkf_82, pf, 1);
    Call_TABLE_Load(enkf_83, pf, 1);
    Call_TABLE_Load(enkf_84, pf, 1);
    Call_TABLE_Load(enkf_85, pf, 1);
    Call_TABLE_Load(enkf_86, pf, 1);
    Call_TABLE_Load(enkf_87, pf, 1);
    Call_TABLE_Load(enkf_88, pf, 1);
    Call_TABLE_Load(enkf_89, pf, 1);
    Call_TABLE_Load(enkf_90, pf, 1);
    Call_TABLE_Load(enkf_91, pf, 1);
    Call_TABLE_Load(enkf_92, pf, 1);
    Call_TABLE_Load(enkf_93, pf, 1);
    Call_TABLE_Load(enkf_94, pf, 1);
    Call_TABLE_Load(enkf_95, pf, 1);
    Call_TABLE_Load(enkf_96, pf, 1);
    Call_TABLE_Load(enkf_97, pf, 1);
    Call_TABLE_Load(enkf_98, pf, 1);
    Call_TABLE_Load(enkf_99, pf, 1);
    Call_TABLE_Load(enkf_100, pf, 1);
    Call_TABLE_Load(enkf_101, pf, 1);
    Call_TABLE_Load(enkf_102, pf, 1);
    Call_TABLE_Load(enkf_103, pf, 1);
    Call_TABLE_Load(enkf_104, pf, 1);
    Call_TABLE_Load(enkf_105, pf, 1);
    Call_TABLE_Load(enkf_106, pf, 1);
    Call_TABLE_Load(enkf_107, pf, 1);
    Call_TABLE_Load(enkf_108, pf, 1);
    Call_TABLE_Load(enkf_109, pf, 1);
    Call_TABLE_Load(enkf_110, pf, 1);
    Call_TABLE_Load(enkf_111, pf, 1);
    Call_TABLE_Load(enkf_112, pf, 1);
    Call_TABLE_Load(enkf_113, pf, 1);
    Call_TABLE_Load(enkf_114, pf, 1);
    Call_TABLE_Load(enkf_115, pf, 1);
    Call_TABLE_Load(enkf_116, pf, 1);
    Call_TABLE_Load(enkf_117, pf, 1);
    Call_TABLE_Load(enkf_118, pf, 1);
    Call_TABLE_Load(enkf_119, pf, 1);
    Call_TABLE_Load(enkf_120, pf, 1);
    Call_TABLE_Load(enda_1, pf, 1);
    Call_TABLE_Load(enda_2, pf, 1);
    Call_TABLE_Load(enda_3, pf, 1);
    Call_TABLE_Load(enda_4, pf, 1);
    Call_TABLE_Load(enda_5, pf, 1);
    Call_TABLE_Load(enda_6, pf, 1);
    Call_TABLE_Load(enda_7, pf, 1);
    Call_TABLE_Load(enda_8, pf, 1);
    Call_TABLE_Load(enda_9, pf, 1);
    Call_TABLE_Load(enda_10, pf, 1);
    Call_TABLE_Load(enda_11, pf, 1);
    Call_TABLE_Load(enda_12, pf, 1);
    Call_TABLE_Load(enda_13, pf, 1);
    Call_TABLE_Load(enda_14, pf, 1);
    Call_TABLE_Load(enda_15, pf, 1);
    Call_TABLE_Load(enda_16, pf, 1);
    Call_TABLE_Load(enda_17, pf, 1);
    Call_TABLE_Load(enda_18, pf, 1);
    Call_TABLE_Load(enda_19, pf, 1);
    Call_TABLE_Load(enda_20, pf, 1);
    Call_TABLE_Load(enda_21, pf, 1);
    Call_TABLE_Load(enda_22, pf, 1);
    Call_TABLE_Load(enda_23, pf, 1);
    Call_TABLE_Load(enda_24, pf, 1);
    Call_TABLE_Load(enda_25, pf, 1);
    Call_TABLE_Load(enda_26, pf, 1);
    Call_TABLE_Load(enda_27, pf, 1);
    Call_TABLE_Load(enda_28, pf, 1);
    Call_TABLE_Load(enda_29, pf, 1);
    Call_TABLE_Load(enda_30, pf, 1);
    Call_TABLE_Load(enda_31, pf, 1);
    Call_TABLE_Load(enda_32, pf, 1);
    Call_TABLE_Load(enda_33, pf, 1);
    Call_TABLE_Load(enda_34, pf, 1);
    Call_TABLE_Load(enda_35, pf, 1);
    Call_TABLE_Load(enda_36, pf, 1);
    Call_TABLE_Load(enda_37, pf, 1);
    Call_TABLE_Load(enda_38, pf, 1);
    Call_TABLE_Load(enda_39, pf, 1);
    Call_TABLE_Load(enda_40, pf, 1);
    Call_TABLE_Load(enda_41, pf, 1);
    Call_TABLE_Load(enda_42, pf, 1);
    Call_TABLE_Load(enda_43, pf, 1);
    Call_TABLE_Load(enda_44, pf, 1);
    Call_TABLE_Load(enda_45, pf, 1);
    Call_TABLE_Load(enda_46, pf, 1);
    Call_TABLE_Load(enda_47, pf, 1);
    Call_TABLE_Load(enda_48, pf, 1);
    Call_TABLE_Load(enda_49, pf, 1);
    Call_TABLE_Load(enda_50, pf, 1);
    Call_TABLE_Load(enda_51, pf, 1);
    Call_TABLE_Load(enda_52, pf, 1);
    Call_TABLE_Load(enda_53, pf, 1);
    Call_TABLE_Load(enda_54, pf, 1);
    Call_TABLE_Load(enda_55, pf, 1);
    Call_TABLE_Load(enda_56, pf, 1);
    Call_TABLE_Load(enda_57, pf, 1);
    Call_TABLE_Load(enda_58, pf, 1);
    Call_TABLE_Load(enda_59, pf, 1);
    Call_TABLE_Load(enda_60, pf, 1);
    Call_TABLE_Load(enda_61, pf, 1);
    Call_TABLE_Load(enda_62, pf, 1);
    Call_TABLE_Load(enda_63, pf, 1);
    Call_TABLE_Load(enda_64, pf, 1);
    Call_TABLE_Load(enda_65, pf, 1);
    Call_TABLE_Load(enda_66, pf, 1);
    Call_TABLE_Load(enda_67, pf, 1);
    Call_TABLE_Load(enda_68, pf, 1);
    Call_TABLE_Load(enda_69, pf, 1);
    Call_TABLE_Load(enda_70, pf, 1);
    Call_TABLE_Load(enda_71, pf, 1);
    Call_TABLE_Load(enda_72, pf, 1);
    Call_TABLE_Load(enda_73, pf, 1);
    Call_TABLE_Load(enda_74, pf, 1);
    Call_TABLE_Load(enda_75, pf, 1);
    Call_TABLE_Load(enda_76, pf, 1);
    Call_TABLE_Load(enda_77, pf, 1);
    Call_TABLE_Load(enda_78, pf, 1);
    Call_TABLE_Load(enda_79, pf, 1);
    Call_TABLE_Load(enda_80, pf, 1);
    Call_TABLE_Load(enda_81, pf, 1);
    Call_TABLE_Load(enda_82, pf, 1);
    Call_TABLE_Load(enda_83, pf, 1);
    Call_TABLE_Load(enda_84, pf, 1);
    Call_TABLE_Load(enda_85, pf, 1);
    Call_TABLE_Load(enda_86, pf, 1);
    Call_TABLE_Load(enda_87, pf, 1);
    Call_TABLE_Load(enda_88, pf, 1);
    Call_TABLE_Load(enda_89, pf, 1);
    Call_TABLE_Load(enda_90, pf, 1);
    Call_TABLE_Load(enda_91, pf, 1);
    Call_TABLE_Load(enda_92, pf, 1);
    Call_TABLE_Load(enda_93, pf, 1);
    Call_TABLE_Load(enda_94, pf, 1);
    Call_TABLE_Load(enda_95, pf, 1);
    Call_TABLE_Load(enda_96, pf, 1);
    Call_TABLE_Load(enda_97, pf, 1);
    Call_TABLE_Load(enda_98, pf, 1);
    Call_TABLE_Load(enda_99, pf, 1);
    Call_TABLE_Load(enda_100, pf, 1);
    Call_TABLE_Load(surfbody_feedback_1, pf, 1);
    Call_TABLE_Load(surfbody_feedback_2, pf, 1);
    Call_TABLE_Load(surfbody_feedback_3, pf, 1);
    Call_TABLE_Load(surfbody_feedback_4, pf, 1);
    Call_TABLE_Load(surfbody_feedback_5, pf, 1);
    Call_TABLE_Load(surfbody_feedback_6, pf, 1);
    Call_TABLE_Load(surfbody_feedback_7, pf, 1);
    Call_TABLE_Load(surfbody_feedback_8, pf, 1);
    Call_TABLE_Load(surfbody_feedback_9, pf, 1);
    Call_TABLE_Load(surfbody_feedback_10, pf, 1);
    Call_TABLE_Load(surfbody_feedback_11, pf, 1);
    Call_TABLE_Load(surfbody_feedback_12, pf, 1);
    Call_TABLE_Load(surfbody_feedback_13, pf, 1);
    Call_TABLE_Load(surfbody_feedback_14, pf, 1);
    Call_TABLE_Load(surfbody_feedback_15, pf, 1);
    Call_TABLE_Load(surfbody_feedback_16, pf, 1);
    Call_TABLE_Load(surfbody_feedback_17, pf, 1);
    Call_TABLE_Load(surfbody_feedback_18, pf, 1);
    Call_TABLE_Load(surfbody_feedback_19, pf, 1);
    Call_TABLE_Load(surfbody_feedback_20, pf, 1);
    Call_TABLE_Load(surfbody_feedback_21, pf, 1);
    Call_TABLE_Load(surfbody_feedback_22, pf, 1);
    Call_TABLE_Load(surfbody_feedback_23, pf, 1);
    Call_TABLE_Load(surfbody_feedback_24, pf, 1);
    Call_TABLE_Load(surfbody_feedback_25, pf, 1);
    Call_TABLE_Load(surfbody_feedback_26, pf, 1);
    Call_TABLE_Load(surfbody_feedback_27, pf, 1);
    Call_TABLE_Load(surfbody_feedback_28, pf, 1);
    Call_TABLE_Load(surfbody_feedback_29, pf, 1);
    Call_TABLE_Load(surfbody_feedback_30, pf, 1);
    Call_TABLE_Load(surfbody_feedback_31, pf, 1);
    Call_TABLE_Load(surfbody_feedback_32, pf, 1);
    Call_TABLE_Load(surfbody_feedback_33, pf, 1);
    Call_TABLE_Load(surfbody_feedback_34, pf, 1);
    Call_TABLE_Load(surfbody_feedback_35, pf, 1);
    Call_TABLE_Load(surfbody_feedback_36, pf, 1);
    Call_TABLE_Load(surfbody_feedback_37, pf, 1);
    Call_TABLE_Load(surfbody_feedback_38, pf, 1);
    Call_TABLE_Load(surfbody_feedback_39, pf, 1);
    Call_TABLE_Load(surfbody_feedback_40, pf, 1);
    Call_TABLE_Load(surfbody_feedback_41, pf, 1);
    Call_TABLE_Load(surfbody_feedback_42, pf, 1);
    Call_TABLE_Load(surfbody_feedback_43, pf, 1);
    Call_TABLE_Load(surfbody_feedback_44, pf, 1);
    Call_TABLE_Load(surfbody_feedback_45, pf, 1);
    Call_TABLE_Load(surfbody_feedback_46, pf, 1);
    Call_TABLE_Load(surfbody_feedback_47, pf, 1);
    Call_TABLE_Load(surfbody_feedback_48, pf, 1);
    Call_TABLE_Load(surfbody_feedback_49, pf, 1);
    Call_TABLE_Load(surfbody_feedback_50, pf, 1);
    Call_TABLE_Load(surfbody_feedback_51, pf, 1);
    Call_TABLE_Load(surfbody_feedback_52, pf, 1);
    Call_TABLE_Load(surfbody_feedback_53, pf, 1);
    Call_TABLE_Load(surfbody_feedback_54, pf, 1);
    Call_TABLE_Load(surfbody_feedback_55, pf, 1);
    Call_TABLE_Load(surfbody_feedback_56, pf, 1);
    Call_TABLE_Load(surfbody_feedback_57, pf, 1);
    Call_TABLE_Load(surfbody_feedback_58, pf, 1);
    Call_TABLE_Load(surfbody_feedback_59, pf, 1);
    Call_TABLE_Load(surfbody_feedback_60, pf, 1);
    Call_TABLE_Load(surfbody_feedback_61, pf, 1);
    Call_TABLE_Load(surfbody_feedback_62, pf, 1);
    Call_TABLE_Load(surfbody_feedback_63, pf, 1);
    Call_TABLE_Load(surfbody_feedback_64, pf, 1);
    Call_TABLE_Load(surfbody_feedback_65, pf, 1);
    Call_TABLE_Load(surfbody_feedback_66, pf, 1);
    Call_TABLE_Load(surfbody_feedback_67, pf, 1);
    Call_TABLE_Load(surfbody_feedback_68, pf, 1);
    Call_TABLE_Load(surfbody_feedback_69, pf, 1);
    Call_TABLE_Load(surfbody_feedback_70, pf, 1);
    Call_TABLE_Load(surfbody_feedback_71, pf, 1);
    Call_TABLE_Load(surfbody_feedback_72, pf, 1);
    Call_TABLE_Load(surfbody_feedback_73, pf, 1);
    Call_TABLE_Load(surfbody_feedback_74, pf, 1);
    Call_TABLE_Load(surfbody_feedback_75, pf, 1);
    Call_TABLE_Load(surfbody_feedback_76, pf, 1);
    Call_TABLE_Load(surfbody_feedback_77, pf, 1);
    Call_TABLE_Load(surfbody_feedback_78, pf, 1);
    Call_TABLE_Load(surfbody_feedback_79, pf, 1);
    Call_TABLE_Load(surfbody_feedback_80, pf, 1);
    Call_TABLE_Load(surfbody_feedback_81, pf, 1);
    Call_TABLE_Load(surfbody_feedback_82, pf, 1);
    Call_TABLE_Load(surfbody_feedback_83, pf, 1);
    Call_TABLE_Load(surfbody_feedback_84, pf, 1);
    Call_TABLE_Load(surfbody_feedback_85, pf, 1);
    Call_TABLE_Load(surfbody_feedback_86, pf, 1);
    Call_TABLE_Load(surfbody_feedback_87, pf, 1);
    Call_TABLE_Load(surfbody_feedback_88, pf, 1);
    Call_TABLE_Load(surfbody_feedback_89, pf, 1);
    Call_TABLE_Load(surfbody_feedback_90, pf, 1);
    Call_TABLE_Load(surfbody_feedback_91, pf, 1);
    Call_TABLE_Load(surfbody_feedback_92, pf, 1);
    Call_TABLE_Load(surfbody_feedback_93, pf, 1);
    Call_TABLE_Load(surfbody_feedback_94, pf, 1);
    Call_TABLE_Load(surfbody_feedback_95, pf, 1);
    Call_TABLE_Load(surfbody_feedback_96, pf, 1);
    Call_TABLE_Load(surfbody_feedback_97, pf, 1);
    Call_TABLE_Load(surfbody_feedback_98, pf, 1);
    Call_TABLE_Load(surfbody_feedback_99, pf, 1);
    Call_TABLE_Load(surfbody_feedback_100, pf, 1);
    Call_TABLE_Load(fcdiagnostic, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_1, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_2, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_3, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_4, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_5, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_6, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_7, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_8, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_9, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_10, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_11, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_12, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_13, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_14, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_15, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_16, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_17, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_18, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_19, pf, 1);
    Call_TABLE_Load(fcdiagnostic_body_20, pf, 1);
    Call_TABLE_Load(gbrad, pf, 1);
    Call_TABLE_Load(gbrad_body, pf, 1);
    Call_TABLE_Load(raingg, pf, 1);
    Call_TABLE_Load(raingg_body, pf, 1);
    Call_TABLE_Load(conv, pf, 1);
    Call_TABLE_Load(conv_body, pf, 1);
    Call_TABLE_Load(sat, pf, 1);
    Call_TABLE_Load(modsurf, pf, 1);
    Call_TABLE_Load(surfbody_feedback, pf, 1);
    Call_TABLE_Load(radiance, pf, 1);
    Call_TABLE_Load(radiance_body, pf, 1);
    Call_TABLE_Load(allsky, pf, 1);
    Call_TABLE_Load(allsky_body, pf, 1);
    Call_TABLE_Load(cloud_sink, pf, 1);
    Call_TABLE_Load(collocated_imager_information, pf, 1);
    Call_TABLE_Load(auxiliary, pf, 1);
    Call_TABLE_Load(auxiliary_body, pf, 1);
    Call_TABLE_Load(resat, pf, 1);
    Call_TABLE_Load(resat_averaging_kernel, pf, 1);
    Call_TABLE_Load(gnssro, pf, 1);
    Call_TABLE_Load(gnssro_body, pf, 1);
    Call_TABLE_Load(satob, pf, 1);
    Call_TABLE_Load(scatt, pf, 1);
    Call_TABLE_Load(scatt_body, pf, 1);
    Call_TABLE_Load(ssmi, pf, 1);
    Call_TABLE_Load(ssmi_body, pf, 1);
    Call_TABLE_Load(smos, pf, 1);
    Call_TABLE_Load(radar_station, pf, 1);
    Call_TABLE_Load(radar, pf, 1);
    Call_TABLE_Load(radar_body, pf, 1);
    Call_TABLE_Load(limb, pf, 1);
    Call_TABLE_Load(body, pf, 1);
    Call_TABLE_Load(errstat, pf, 1);
    Call_TABLE_Load(update_1, pf, 1);
    Call_TABLE_Load(update_2, pf, 1);
    Call_TABLE_Load(update_3, pf, 1);
    Call_TABLE_Load(update_4, pf, 1);
    Call_TABLE_Load(aeolus_hdr, pf, 1);
    Call_TABLE_Load(aeolus_auxmet, pf, 1);
    Call_TABLE_Load(aeolus_l2c, pf, 1);
    Call_TABLE_Load(aeolus_l2b, pf, 1);
  } /* if (io_method != 5) */
  return (rc < 0) ? rc : Nbytes;
}

PRIVATE int
Store_Pool(const ODB_Pool *P, int io_method)
{
  int rc = 0;
  int Nbytes = 0;
  ODB_Funcs *pf = P->funcs;
  if (io_method != 5) {
    Call_TABLE_Store(desc, pf, 1);
    Call_TABLE_Store(poolmask, pf, 1);
    Call_TABLE_Store(timeslot_index, pf, 1);
    Call_TABLE_Store(index, pf, 1);
    Call_TABLE_Store(hdr, pf, 1);
    Call_TABLE_Store(ensemble, pf, 1);
    Call_TABLE_Store(enkf_1, pf, 1);
    Call_TABLE_Store(enkf_2, pf, 1);
    Call_TABLE_Store(enkf_3, pf, 1);
    Call_TABLE_Store(enkf_4, pf, 1);
    Call_TABLE_Store(enkf_5, pf, 1);
    Call_TABLE_Store(enkf_6, pf, 1);
    Call_TABLE_Store(enkf_7, pf, 1);
    Call_TABLE_Store(enkf_8, pf, 1);
    Call_TABLE_Store(enkf_9, pf, 1);
    Call_TABLE_Store(enkf_10, pf, 1);
    Call_TABLE_Store(enkf_11, pf, 1);
    Call_TABLE_Store(enkf_12, pf, 1);
    Call_TABLE_Store(enkf_13, pf, 1);
    Call_TABLE_Store(enkf_14, pf, 1);
    Call_TABLE_Store(enkf_15, pf, 1);
    Call_TABLE_Store(enkf_16, pf, 1);
    Call_TABLE_Store(enkf_17, pf, 1);
    Call_TABLE_Store(enkf_18, pf, 1);
    Call_TABLE_Store(enkf_19, pf, 1);
    Call_TABLE_Store(enkf_20, pf, 1);
    Call_TABLE_Store(enkf_21, pf, 1);
    Call_TABLE_Store(enkf_22, pf, 1);
    Call_TABLE_Store(enkf_23, pf, 1);
    Call_TABLE_Store(enkf_24, pf, 1);
    Call_TABLE_Store(enkf_25, pf, 1);
    Call_TABLE_Store(enkf_26, pf, 1);
    Call_TABLE_Store(enkf_27, pf, 1);
    Call_TABLE_Store(enkf_28, pf, 1);
    Call_TABLE_Store(enkf_29, pf, 1);
    Call_TABLE_Store(enkf_30, pf, 1);
    Call_TABLE_Store(enkf_31, pf, 1);
    Call_TABLE_Store(enkf_32, pf, 1);
    Call_TABLE_Store(enkf_33, pf, 1);
    Call_TABLE_Store(enkf_34, pf, 1);
    Call_TABLE_Store(enkf_35, pf, 1);
    Call_TABLE_Store(enkf_36, pf, 1);
    Call_TABLE_Store(enkf_37, pf, 1);
    Call_TABLE_Store(enkf_38, pf, 1);
    Call_TABLE_Store(enkf_39, pf, 1);
    Call_TABLE_Store(enkf_40, pf, 1);
    Call_TABLE_Store(enkf_41, pf, 1);
    Call_TABLE_Store(enkf_42, pf, 1);
    Call_TABLE_Store(enkf_43, pf, 1);
    Call_TABLE_Store(enkf_44, pf, 1);
    Call_TABLE_Store(enkf_45, pf, 1);
    Call_TABLE_Store(enkf_46, pf, 1);
    Call_TABLE_Store(enkf_47, pf, 1);
    Call_TABLE_Store(enkf_48, pf, 1);
    Call_TABLE_Store(enkf_49, pf, 1);
    Call_TABLE_Store(enkf_50, pf, 1);
    Call_TABLE_Store(enkf_51, pf, 1);
    Call_TABLE_Store(enkf_52, pf, 1);
    Call_TABLE_Store(enkf_53, pf, 1);
    Call_TABLE_Store(enkf_54, pf, 1);
    Call_TABLE_Store(enkf_55, pf, 1);
    Call_TABLE_Store(enkf_56, pf, 1);
    Call_TABLE_Store(enkf_57, pf, 1);
    Call_TABLE_Store(enkf_58, pf, 1);
    Call_TABLE_Store(enkf_59, pf, 1);
    Call_TABLE_Store(enkf_60, pf, 1);
    Call_TABLE_Store(enkf_61, pf, 1);
    Call_TABLE_Store(enkf_62, pf, 1);
    Call_TABLE_Store(enkf_63, pf, 1);
    Call_TABLE_Store(enkf_64, pf, 1);
    Call_TABLE_Store(enkf_65, pf, 1);
    Call_TABLE_Store(enkf_66, pf, 1);
    Call_TABLE_Store(enkf_67, pf, 1);
    Call_TABLE_Store(enkf_68, pf, 1);
    Call_TABLE_Store(enkf_69, pf, 1);
    Call_TABLE_Store(enkf_70, pf, 1);
    Call_TABLE_Store(enkf_71, pf, 1);
    Call_TABLE_Store(enkf_72, pf, 1);
    Call_TABLE_Store(enkf_73, pf, 1);
    Call_TABLE_Store(enkf_74, pf, 1);
    Call_TABLE_Store(enkf_75, pf, 1);
    Call_TABLE_Store(enkf_76, pf, 1);
    Call_TABLE_Store(enkf_77, pf, 1);
    Call_TABLE_Store(enkf_78, pf, 1);
    Call_TABLE_Store(enkf_79, pf, 1);
    Call_TABLE_Store(enkf_80, pf, 1);
    Call_TABLE_Store(enkf_81, pf, 1);
    Call_TABLE_Store(enkf_82, pf, 1);
    Call_TABLE_Store(enkf_83, pf, 1);
    Call_TABLE_Store(enkf_84, pf, 1);
    Call_TABLE_Store(enkf_85, pf, 1);
    Call_TABLE_Store(enkf_86, pf, 1);
    Call_TABLE_Store(enkf_87, pf, 1);
    Call_TABLE_Store(enkf_88, pf, 1);
    Call_TABLE_Store(enkf_89, pf, 1);
    Call_TABLE_Store(enkf_90, pf, 1);
    Call_TABLE_Store(enkf_91, pf, 1);
    Call_TABLE_Store(enkf_92, pf, 1);
    Call_TABLE_Store(enkf_93, pf, 1);
    Call_TABLE_Store(enkf_94, pf, 1);
    Call_TABLE_Store(enkf_95, pf, 1);
    Call_TABLE_Store(enkf_96, pf, 1);
    Call_TABLE_Store(enkf_97, pf, 1);
    Call_TABLE_Store(enkf_98, pf, 1);
    Call_TABLE_Store(enkf_99, pf, 1);
    Call_TABLE_Store(enkf_100, pf, 1);
    Call_TABLE_Store(enkf_101, pf, 1);
    Call_TABLE_Store(enkf_102, pf, 1);
    Call_TABLE_Store(enkf_103, pf, 1);
    Call_TABLE_Store(enkf_104, pf, 1);
    Call_TABLE_Store(enkf_105, pf, 1);
    Call_TABLE_Store(enkf_106, pf, 1);
    Call_TABLE_Store(enkf_107, pf, 1);
    Call_TABLE_Store(enkf_108, pf, 1);
    Call_TABLE_Store(enkf_109, pf, 1);
    Call_TABLE_Store(enkf_110, pf, 1);
    Call_TABLE_Store(enkf_111, pf, 1);
    Call_TABLE_Store(enkf_112, pf, 1);
    Call_TABLE_Store(enkf_113, pf, 1);
    Call_TABLE_Store(enkf_114, pf, 1);
    Call_TABLE_Store(enkf_115, pf, 1);
    Call_TABLE_Store(enkf_116, pf, 1);
    Call_TABLE_Store(enkf_117, pf, 1);
    Call_TABLE_Store(enkf_118, pf, 1);
    Call_TABLE_Store(enkf_119, pf, 1);
    Call_TABLE_Store(enkf_120, pf, 1);
    Call_TABLE_Store(enda_1, pf, 1);
    Call_TABLE_Store(enda_2, pf, 1);
    Call_TABLE_Store(enda_3, pf, 1);
    Call_TABLE_Store(enda_4, pf, 1);
    Call_TABLE_Store(enda_5, pf, 1);
    Call_TABLE_Store(enda_6, pf, 1);
    Call_TABLE_Store(enda_7, pf, 1);
    Call_TABLE_Store(enda_8, pf, 1);
    Call_TABLE_Store(enda_9, pf, 1);
    Call_TABLE_Store(enda_10, pf, 1);
    Call_TABLE_Store(enda_11, pf, 1);
    Call_TABLE_Store(enda_12, pf, 1);
    Call_TABLE_Store(enda_13, pf, 1);
    Call_TABLE_Store(enda_14, pf, 1);
    Call_TABLE_Store(enda_15, pf, 1);
    Call_TABLE_Store(enda_16, pf, 1);
    Call_TABLE_Store(enda_17, pf, 1);
    Call_TABLE_Store(enda_18, pf, 1);
    Call_TABLE_Store(enda_19, pf, 1);
    Call_TABLE_Store(enda_20, pf, 1);
    Call_TABLE_Store(enda_21, pf, 1);
    Call_TABLE_Store(enda_22, pf, 1);
    Call_TABLE_Store(enda_23, pf, 1);
    Call_TABLE_Store(enda_24, pf, 1);
    Call_TABLE_Store(enda_25, pf, 1);
    Call_TABLE_Store(enda_26, pf, 1);
    Call_TABLE_Store(enda_27, pf, 1);
    Call_TABLE_Store(enda_28, pf, 1);
    Call_TABLE_Store(enda_29, pf, 1);
    Call_TABLE_Store(enda_30, pf, 1);
    Call_TABLE_Store(enda_31, pf, 1);
    Call_TABLE_Store(enda_32, pf, 1);
    Call_TABLE_Store(enda_33, pf, 1);
    Call_TABLE_Store(enda_34, pf, 1);
    Call_TABLE_Store(enda_35, pf, 1);
    Call_TABLE_Store(enda_36, pf, 1);
    Call_TABLE_Store(enda_37, pf, 1);
    Call_TABLE_Store(enda_38, pf, 1);
    Call_TABLE_Store(enda_39, pf, 1);
    Call_TABLE_Store(enda_40, pf, 1);
    Call_TABLE_Store(enda_41, pf, 1);
    Call_TABLE_Store(enda_42, pf, 1);
    Call_TABLE_Store(enda_43, pf, 1);
    Call_TABLE_Store(enda_44, pf, 1);
    Call_TABLE_Store(enda_45, pf, 1);
    Call_TABLE_Store(enda_46, pf, 1);
    Call_TABLE_Store(enda_47, pf, 1);
    Call_TABLE_Store(enda_48, pf, 1);
    Call_TABLE_Store(enda_49, pf, 1);
    Call_TABLE_Store(enda_50, pf, 1);
    Call_TABLE_Store(enda_51, pf, 1);
    Call_TABLE_Store(enda_52, pf, 1);
    Call_TABLE_Store(enda_53, pf, 1);
    Call_TABLE_Store(enda_54, pf, 1);
    Call_TABLE_Store(enda_55, pf, 1);
    Call_TABLE_Store(enda_56, pf, 1);
    Call_TABLE_Store(enda_57, pf, 1);
    Call_TABLE_Store(enda_58, pf, 1);
    Call_TABLE_Store(enda_59, pf, 1);
    Call_TABLE_Store(enda_60, pf, 1);
    Call_TABLE_Store(enda_61, pf, 1);
    Call_TABLE_Store(enda_62, pf, 1);
    Call_TABLE_Store(enda_63, pf, 1);
    Call_TABLE_Store(enda_64, pf, 1);
    Call_TABLE_Store(enda_65, pf, 1);
    Call_TABLE_Store(enda_66, pf, 1);
    Call_TABLE_Store(enda_67, pf, 1);
    Call_TABLE_Store(enda_68, pf, 1);
    Call_TABLE_Store(enda_69, pf, 1);
    Call_TABLE_Store(enda_70, pf, 1);
    Call_TABLE_Store(enda_71, pf, 1);
    Call_TABLE_Store(enda_72, pf, 1);
    Call_TABLE_Store(enda_73, pf, 1);
    Call_TABLE_Store(enda_74, pf, 1);
    Call_TABLE_Store(enda_75, pf, 1);
    Call_TABLE_Store(enda_76, pf, 1);
    Call_TABLE_Store(enda_77, pf, 1);
    Call_TABLE_Store(enda_78, pf, 1);
    Call_TABLE_Store(enda_79, pf, 1);
    Call_TABLE_Store(enda_80, pf, 1);
    Call_TABLE_Store(enda_81, pf, 1);
    Call_TABLE_Store(enda_82, pf, 1);
    Call_TABLE_Store(enda_83, pf, 1);
    Call_TABLE_Store(enda_84, pf, 1);
    Call_TABLE_Store(enda_85, pf, 1);
    Call_TABLE_Store(enda_86, pf, 1);
    Call_TABLE_Store(enda_87, pf, 1);
    Call_TABLE_Store(enda_88, pf, 1);
    Call_TABLE_Store(enda_89, pf, 1);
    Call_TABLE_Store(enda_90, pf, 1);
    Call_TABLE_Store(enda_91, pf, 1);
    Call_TABLE_Store(enda_92, pf, 1);
    Call_TABLE_Store(enda_93, pf, 1);
    Call_TABLE_Store(enda_94, pf, 1);
    Call_TABLE_Store(enda_95, pf, 1);
    Call_TABLE_Store(enda_96, pf, 1);
    Call_TABLE_Store(enda_97, pf, 1);
    Call_TABLE_Store(enda_98, pf, 1);
    Call_TABLE_Store(enda_99, pf, 1);
    Call_TABLE_Store(enda_100, pf, 1);
    Call_TABLE_Store(surfbody_feedback_1, pf, 1);
    Call_TABLE_Store(surfbody_feedback_2, pf, 1);
    Call_TABLE_Store(surfbody_feedback_3, pf, 1);
    Call_TABLE_Store(surfbody_feedback_4, pf, 1);
    Call_TABLE_Store(surfbody_feedback_5, pf, 1);
    Call_TABLE_Store(surfbody_feedback_6, pf, 1);
    Call_TABLE_Store(surfbody_feedback_7, pf, 1);
    Call_TABLE_Store(surfbody_feedback_8, pf, 1);
    Call_TABLE_Store(surfbody_feedback_9, pf, 1);
    Call_TABLE_Store(surfbody_feedback_10, pf, 1);
    Call_TABLE_Store(surfbody_feedback_11, pf, 1);
    Call_TABLE_Store(surfbody_feedback_12, pf, 1);
    Call_TABLE_Store(surfbody_feedback_13, pf, 1);
    Call_TABLE_Store(surfbody_feedback_14, pf, 1);
    Call_TABLE_Store(surfbody_feedback_15, pf, 1);
    Call_TABLE_Store(surfbody_feedback_16, pf, 1);
    Call_TABLE_Store(surfbody_feedback_17, pf, 1);
    Call_TABLE_Store(surfbody_feedback_18, pf, 1);
    Call_TABLE_Store(surfbody_feedback_19, pf, 1);
    Call_TABLE_Store(surfbody_feedback_20, pf, 1);
    Call_TABLE_Store(surfbody_feedback_21, pf, 1);
    Call_TABLE_Store(surfbody_feedback_22, pf, 1);
    Call_TABLE_Store(surfbody_feedback_23, pf, 1);
    Call_TABLE_Store(surfbody_feedback_24, pf, 1);
    Call_TABLE_Store(surfbody_feedback_25, pf, 1);
    Call_TABLE_Store(surfbody_feedback_26, pf, 1);
    Call_TABLE_Store(surfbody_feedback_27, pf, 1);
    Call_TABLE_Store(surfbody_feedback_28, pf, 1);
    Call_TABLE_Store(surfbody_feedback_29, pf, 1);
    Call_TABLE_Store(surfbody_feedback_30, pf, 1);
    Call_TABLE_Store(surfbody_feedback_31, pf, 1);
    Call_TABLE_Store(surfbody_feedback_32, pf, 1);
    Call_TABLE_Store(surfbody_feedback_33, pf, 1);
    Call_TABLE_Store(surfbody_feedback_34, pf, 1);
    Call_TABLE_Store(surfbody_feedback_35, pf, 1);
    Call_TABLE_Store(surfbody_feedback_36, pf, 1);
    Call_TABLE_Store(surfbody_feedback_37, pf, 1);
    Call_TABLE_Store(surfbody_feedback_38, pf, 1);
    Call_TABLE_Store(surfbody_feedback_39, pf, 1);
    Call_TABLE_Store(surfbody_feedback_40, pf, 1);
    Call_TABLE_Store(surfbody_feedback_41, pf, 1);
    Call_TABLE_Store(surfbody_feedback_42, pf, 1);
    Call_TABLE_Store(surfbody_feedback_43, pf, 1);
    Call_TABLE_Store(surfbody_feedback_44, pf, 1);
    Call_TABLE_Store(surfbody_feedback_45, pf, 1);
    Call_TABLE_Store(surfbody_feedback_46, pf, 1);
    Call_TABLE_Store(surfbody_feedback_47, pf, 1);
    Call_TABLE_Store(surfbody_feedback_48, pf, 1);
    Call_TABLE_Store(surfbody_feedback_49, pf, 1);
    Call_TABLE_Store(surfbody_feedback_50, pf, 1);
    Call_TABLE_Store(surfbody_feedback_51, pf, 1);
    Call_TABLE_Store(surfbody_feedback_52, pf, 1);
    Call_TABLE_Store(surfbody_feedback_53, pf, 1);
    Call_TABLE_Store(surfbody_feedback_54, pf, 1);
    Call_TABLE_Store(surfbody_feedback_55, pf, 1);
    Call_TABLE_Store(surfbody_feedback_56, pf, 1);
    Call_TABLE_Store(surfbody_feedback_57, pf, 1);
    Call_TABLE_Store(surfbody_feedback_58, pf, 1);
    Call_TABLE_Store(surfbody_feedback_59, pf, 1);
    Call_TABLE_Store(surfbody_feedback_60, pf, 1);
    Call_TABLE_Store(surfbody_feedback_61, pf, 1);
    Call_TABLE_Store(surfbody_feedback_62, pf, 1);
    Call_TABLE_Store(surfbody_feedback_63, pf, 1);
    Call_TABLE_Store(surfbody_feedback_64, pf, 1);
    Call_TABLE_Store(surfbody_feedback_65, pf, 1);
    Call_TABLE_Store(surfbody_feedback_66, pf, 1);
    Call_TABLE_Store(surfbody_feedback_67, pf, 1);
    Call_TABLE_Store(surfbody_feedback_68, pf, 1);
    Call_TABLE_Store(surfbody_feedback_69, pf, 1);
    Call_TABLE_Store(surfbody_feedback_70, pf, 1);
    Call_TABLE_Store(surfbody_feedback_71, pf, 1);
    Call_TABLE_Store(surfbody_feedback_72, pf, 1);
    Call_TABLE_Store(surfbody_feedback_73, pf, 1);
    Call_TABLE_Store(surfbody_feedback_74, pf, 1);
    Call_TABLE_Store(surfbody_feedback_75, pf, 1);
    Call_TABLE_Store(surfbody_feedback_76, pf, 1);
    Call_TABLE_Store(surfbody_feedback_77, pf, 1);
    Call_TABLE_Store(surfbody_feedback_78, pf, 1);
    Call_TABLE_Store(surfbody_feedback_79, pf, 1);
    Call_TABLE_Store(surfbody_feedback_80, pf, 1);
    Call_TABLE_Store(surfbody_feedback_81, pf, 1);
    Call_TABLE_Store(surfbody_feedback_82, pf, 1);
    Call_TABLE_Store(surfbody_feedback_83, pf, 1);
    Call_TABLE_Store(surfbody_feedback_84, pf, 1);
    Call_TABLE_Store(surfbody_feedback_85, pf, 1);
    Call_TABLE_Store(surfbody_feedback_86, pf, 1);
    Call_TABLE_Store(surfbody_feedback_87, pf, 1);
    Call_TABLE_Store(surfbody_feedback_88, pf, 1);
    Call_TABLE_Store(surfbody_feedback_89, pf, 1);
    Call_TABLE_Store(surfbody_feedback_90, pf, 1);
    Call_TABLE_Store(surfbody_feedback_91, pf, 1);
    Call_TABLE_Store(surfbody_feedback_92, pf, 1);
    Call_TABLE_Store(surfbody_feedback_93, pf, 1);
    Call_TABLE_Store(surfbody_feedback_94, pf, 1);
    Call_TABLE_Store(surfbody_feedback_95, pf, 1);
    Call_TABLE_Store(surfbody_feedback_96, pf, 1);
    Call_TABLE_Store(surfbody_feedback_97, pf, 1);
    Call_TABLE_Store(surfbody_feedback_98, pf, 1);
    Call_TABLE_Store(surfbody_feedback_99, pf, 1);
    Call_TABLE_Store(surfbody_feedback_100, pf, 1);
    Call_TABLE_Store(fcdiagnostic, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_1, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_2, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_3, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_4, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_5, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_6, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_7, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_8, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_9, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_10, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_11, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_12, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_13, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_14, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_15, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_16, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_17, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_18, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_19, pf, 1);
    Call_TABLE_Store(fcdiagnostic_body_20, pf, 1);
    Call_TABLE_Store(gbrad, pf, 1);
    Call_TABLE_Store(gbrad_body, pf, 1);
    Call_TABLE_Store(raingg, pf, 1);
    Call_TABLE_Store(raingg_body, pf, 1);
    Call_TABLE_Store(conv, pf, 1);
    Call_TABLE_Store(conv_body, pf, 1);
    Call_TABLE_Store(sat, pf, 1);
    Call_TABLE_Store(modsurf, pf, 1);
    Call_TABLE_Store(surfbody_feedback, pf, 1);
    Call_TABLE_Store(radiance, pf, 1);
    Call_TABLE_Store(radiance_body, pf, 1);
    Call_TABLE_Store(allsky, pf, 1);
    Call_TABLE_Store(allsky_body, pf, 1);
    Call_TABLE_Store(cloud_sink, pf, 1);
    Call_TABLE_Store(collocated_imager_information, pf, 1);
    Call_TABLE_Store(auxiliary, pf, 1);
    Call_TABLE_Store(auxiliary_body, pf, 1);
    Call_TABLE_Store(resat, pf, 1);
    Call_TABLE_Store(resat_averaging_kernel, pf, 1);
    Call_TABLE_Store(gnssro, pf, 1);
    Call_TABLE_Store(gnssro_body, pf, 1);
    Call_TABLE_Store(satob, pf, 1);
    Call_TABLE_Store(scatt, pf, 1);
    Call_TABLE_Store(scatt_body, pf, 1);
    Call_TABLE_Store(ssmi, pf, 1);
    Call_TABLE_Store(ssmi_body, pf, 1);
    Call_TABLE_Store(smos, pf, 1);
    Call_TABLE_Store(radar_station, pf, 1);
    Call_TABLE_Store(radar, pf, 1);
    Call_TABLE_Store(radar_body, pf, 1);
    Call_TABLE_Store(limb, pf, 1);
    Call_TABLE_Store(body, pf, 1);
    Call_TABLE_Store(errstat, pf, 1);
    Call_TABLE_Store(update_1, pf, 1);
    Call_TABLE_Store(update_2, pf, 1);
    Call_TABLE_Store(update_3, pf, 1);
    Call_TABLE_Store(update_4, pf, 1);
    Call_TABLE_Store(aeolus_hdr, pf, 1);
    Call_TABLE_Store(aeolus_auxmet, pf, 1);
    Call_TABLE_Store(aeolus_l2c, pf, 1);
    Call_TABLE_Store(aeolus_l2b, pf, 1);
  } /* if (io_method != 5) */
  return (rc < 0) ? rc : Nbytes;
}

PUBLIC ODB_Funcs *
Anchor2ECMA(void *V, ODB_Pool *pool, int *ntables, int it, int add_vars)
{
  ODB_Anchor_Funcs *func = V;
  ODB_Pool *p = pool;
  DRHOOK_START(Anchor2ECMA);
  /* A special case : ntables not a NULL => return no. of tables */
  if (ntables) {
    *ntables = 388;
    goto finish;
  }
  func->create_funcs = Create_Funcs;
  func->load         = Load_Pool;
  func->store        = Store_Pool;
  if (add_vars) {
    p->add_var(p->dbname, "$mdi", NULL, it, USD_mdi_ECMA);
    p->add_var(p->dbname, "$nmxupd", NULL, it, USD_nmxupd_ECMA);
    p->add_var(p->dbname, "$nmxenkf", NULL, it, USD_nmxenkf_ECMA);
    p->add_var(p->dbname, "$nmxenda", NULL, it, USD_nmxenda_ECMA);
    p->add_var(p->dbname, "$nmxfcdiag", NULL, it, USD_nmxfcdiag_ECMA);
    p->add_var(p->dbname, "$numaux", NULL, it, USD_numaux_ECMA);
    p->add_var(p->dbname, "$numthbox", NULL, it, USD_numthbox_ECMA);
    p->add_var(p->dbname, "$numev", NULL, it, USD_numev_ECMA);
    p->add_var(p->dbname, "$numdiag", NULL, it, USD_numdiag_ECMA);
    p->add_var(p->dbname, "$synop", NULL, it, USD_synop_ECMA);
    p->add_var(p->dbname, "$airep", NULL, it, USD_airep_ECMA);
    p->add_var(p->dbname, "$satob", NULL, it, USD_satob_ECMA);
    p->add_var(p->dbname, "$dribu", NULL, it, USD_dribu_ECMA);
    p->add_var(p->dbname, "$buyo", NULL, it, USD_buyo_ECMA);
    p->add_var(p->dbname, "$temp", NULL, it, USD_temp_ECMA);
    p->add_var(p->dbname, "$pilot", NULL, it, USD_pilot_ECMA);
    p->add_var(p->dbname, "$satem", NULL, it, USD_satem_ECMA);
    p->add_var(p->dbname, "$paob", NULL, it, USD_paob_ECMA);
    p->add_var(p->dbname, "$scatt", NULL, it, USD_scatt_ECMA);
    p->add_var(p->dbname, "$limb", NULL, it, USD_limb_ECMA);
    p->add_var(p->dbname, "$isac", NULL, it, USD_isac_ECMA);
    p->add_var(p->dbname, "$ralt", NULL, it, USD_ralt_ECMA);
    p->add_var(p->dbname, "$radar", NULL, it, USD_radar_ECMA);
    p->add_var(p->dbname, "$gbrad", NULL, it, USD_gbrad_ECMA);
    p->add_var(p->dbname, "$lidar", NULL, it, USD_lidar_ECMA);
    p->add_var(p->dbname, "$allsky", NULL, it, USD_allsky_ECMA);
    p->add_var(p->dbname, "$raingg", NULL, it, USD_raingg_ECMA);
    p->add_var(p->dbname, "$imsims", NULL, it, USD_imsims_ECMA);
    p->add_var(p->dbname, "$reo3", NULL, it, USD_reo3_ECMA);
    p->add_var(p->dbname, "$resat", NULL, it, USD_resat_ECMA);
    p->add_var(p->dbname, "$atovs", NULL, it, USD_atovs_ECMA);
    p->add_var(p->dbname, "$rtovs", NULL, it, USD_rtovs_ECMA);
    p->add_var(p->dbname, "$tovs", NULL, it, USD_tovs_ECMA);
    p->add_var(p->dbname, "$ssmi", NULL, it, USD_ssmi_ECMA);
    p->add_var(p->dbname, "$tcwc", NULL, it, USD_tcwc_ECMA);
    p->add_var(p->dbname, "$radrr", NULL, it, USD_radrr_ECMA);
    p->add_var(p->dbname, "$aeolus", NULL, it, USD_aeolus_ECMA);
    p->add_var(p->dbname, "$satem500", NULL, it, USD_satem500_ECMA);
    p->add_var(p->dbname, "$satem250", NULL, it, USD_satem250_ECMA);
    p->add_var(p->dbname, "$rad1c", NULL, it, USD_rad1c_ECMA);
    p->add_var(p->dbname, "$gpsro", NULL, it, USD_gpsro_ECMA);
    p->add_var(p->dbname, "$lrad", NULL, it, USD_lrad_ECMA);
    p->add_var(p->dbname, "$synop_land", NULL, it, USD_synop_land_ECMA);
    p->add_var(p->dbname, "$synop_land_auto", NULL, it, USD_synop_land_auto_ECMA);
    p->add_var(p->dbname, "$add_land_surface", NULL, it, USD_add_land_surface_ECMA);
    p->add_var(p->dbname, "$synop_rg1h", NULL, it, USD_synop_rg1h_ECMA);
    p->add_var(p->dbname, "$synop_rg3h", NULL, it, USD_synop_rg3h_ECMA);
    p->add_var(p->dbname, "$synop_rg6h", NULL, it, USD_synop_rg6h_ECMA);
    p->add_var(p->dbname, "$synop_rg12h", NULL, it, USD_synop_rg12h_ECMA);
    p->add_var(p->dbname, "$synop_rg24h", NULL, it, USD_synop_rg24h_ECMA);
    p->add_var(p->dbname, "$u", NULL, it, USD_u_ECMA);
    p->add_var(p->dbname, "$v", NULL, it, USD_v_ECMA);
    p->add_var(p->dbname, "$z", NULL, it, USD_z_ECMA);
    p->add_var(p->dbname, "$dz", NULL, it, USD_dz_ECMA);
    p->add_var(p->dbname, "$rh", NULL, it, USD_rh_ECMA);
    p->add_var(p->dbname, "$pwc", NULL, it, USD_pwc_ECMA);
    p->add_var(p->dbname, "$rh2m", NULL, it, USD_rh2m_ECMA);
    p->add_var(p->dbname, "$t", NULL, it, USD_t_ECMA);
    p->add_var(p->dbname, "$td", NULL, it, USD_td_ECMA);
    p->add_var(p->dbname, "$t2m", NULL, it, USD_t2m_ECMA);
    p->add_var(p->dbname, "$td2m", NULL, it, USD_td2m_ECMA);
    p->add_var(p->dbname, "$ts", NULL, it, USD_ts_ECMA);
    p->add_var(p->dbname, "$ptend", NULL, it, USD_ptend_ECMA);
    p->add_var(p->dbname, "$w", NULL, it, USD_w_ECMA);
    p->add_var(p->dbname, "$ww", NULL, it, USD_ww_ECMA);
    p->add_var(p->dbname, "$vv", NULL, it, USD_vv_ECMA);
    p->add_var(p->dbname, "$ch", NULL, it, USD_ch_ECMA);
    p->add_var(p->dbname, "$cm", NULL, it, USD_cm_ECMA);
    p->add_var(p->dbname, "$cl", NULL, it, USD_cl_ECMA);
    p->add_var(p->dbname, "$nh", NULL, it, USD_nh_ECMA);
    p->add_var(p->dbname, "$nn", NULL, it, USD_nn_ECMA);
    p->add_var(p->dbname, "$hshs", NULL, it, USD_hshs_ECMA);
    p->add_var(p->dbname, "$c", NULL, it, USD_c_ECMA);
    p->add_var(p->dbname, "$ns", NULL, it, USD_ns_ECMA);
    p->add_var(p->dbname, "$sdepth", NULL, it, USD_sdepth_ECMA);
    p->add_var(p->dbname, "$e", NULL, it, USD_e_ECMA);
    p->add_var(p->dbname, "$tgtg", NULL, it, USD_tgtg_ECMA);
    p->add_var(p->dbname, "$spsp1", NULL, it, USD_spsp1_ECMA);
    p->add_var(p->dbname, "$spsp2", NULL, it, USD_spsp2_ECMA);
    p->add_var(p->dbname, "$rs", NULL, it, USD_rs_ECMA);
    p->add_var(p->dbname, "$eses", NULL, it, USD_eses_ECMA);
    p->add_var(p->dbname, "$is", NULL, it, USD_is_ECMA);
    p->add_var(p->dbname, "$trtr", NULL, it, USD_trtr_ECMA);
    p->add_var(p->dbname, "$rr", NULL, it, USD_rr_ECMA);
    p->add_var(p->dbname, "$jj", NULL, it, USD_jj_ECMA);
    p->add_var(p->dbname, "$vs", NULL, it, USD_vs_ECMA);
    p->add_var(p->dbname, "$ds", NULL, it, USD_ds_ECMA);
    p->add_var(p->dbname, "$hwhw", NULL, it, USD_hwhw_ECMA);
    p->add_var(p->dbname, "$pwpw", NULL, it, USD_pwpw_ECMA);
    p->add_var(p->dbname, "$dwdw", NULL, it, USD_dwdw_ECMA);
    p->add_var(p->dbname, "$gclg", NULL, it, USD_gclg_ECMA);
    p->add_var(p->dbname, "$rhlc", NULL, it, USD_rhlc_ECMA);
    p->add_var(p->dbname, "$rhmc", NULL, it, USD_rhmc_ECMA);
    p->add_var(p->dbname, "$rhhc", NULL, it, USD_rhhc_ECMA);
    p->add_var(p->dbname, "$n", NULL, it, USD_n_ECMA);
    p->add_var(p->dbname, "$sfall", NULL, it, USD_sfall_ECMA);
    p->add_var(p->dbname, "$ps", NULL, it, USD_ps_ECMA);
    p->add_var(p->dbname, "$dd", NULL, it, USD_dd_ECMA);
    p->add_var(p->dbname, "$ff", NULL, it, USD_ff_ECMA);
    p->add_var(p->dbname, "$rawbt", NULL, it, USD_rawbt_ECMA);
    p->add_var(p->dbname, "$rawra", NULL, it, USD_rawra_ECMA);
    p->add_var(p->dbname, "$satcl", NULL, it, USD_satcl_ECMA);
    p->add_var(p->dbname, "$scatss", NULL, it, USD_scatss_ECMA);
    p->add_var(p->dbname, "$du", NULL, it, USD_du_ECMA);
    p->add_var(p->dbname, "$dv", NULL, it, USD_dv_ECMA);
    p->add_var(p->dbname, "$u10m", NULL, it, USD_u10m_ECMA);
    p->add_var(p->dbname, "$v10m", NULL, it, USD_v10m_ECMA);
    p->add_var(p->dbname, "$rhlay", NULL, it, USD_rhlay_ECMA);
    p->add_var(p->dbname, "$cllqw", NULL, it, USD_cllqw_ECMA);
    p->add_var(p->dbname, "$scatv", NULL, it, USD_scatv_ECMA);
    p->add_var(p->dbname, "$scatu", NULL, it, USD_scatu_ECMA);
    p->add_var(p->dbname, "$q", NULL, it, USD_q_ECMA);
    p->add_var(p->dbname, "$scatwd", NULL, it, USD_scatwd_ECMA);
    p->add_var(p->dbname, "$scatws", NULL, it, USD_scatws_ECMA);
    p->add_var(p->dbname, "$vsp", NULL, it, USD_vsp_ECMA);
    p->add_var(p->dbname, "$vt", NULL, it, USD_vt_ECMA);
    p->add_var(p->dbname, "$o3lay", NULL, it, USD_o3lay_ECMA);
    p->add_var(p->dbname, "$height", NULL, it, USD_height_ECMA);
    p->add_var(p->dbname, "$1dvar", NULL, it, USD_1dvar_ECMA);
    p->add_var(p->dbname, "$w2", NULL, it, USD_w2_ECMA);
    p->add_var(p->dbname, "$cpt", NULL, it, USD_cpt_ECMA);
    p->add_var(p->dbname, "$tsts", NULL, it, USD_tsts_ECMA);
    p->add_var(p->dbname, "$refl", NULL, it, USD_refl_ECMA);
    p->add_var(p->dbname, "$apdss", NULL, it, USD_apdss_ECMA);
    p->add_var(p->dbname, "$bend_angle", NULL, it, USD_bend_angle_ECMA);
    p->add_var(p->dbname, "$los", NULL, it, USD_los_ECMA);
    p->add_var(p->dbname, "$aerod", NULL, it, USD_aerod_ECMA);
    p->add_var(p->dbname, "$limb_radiance", NULL, it, USD_limb_radiance_ECMA);
    p->add_var(p->dbname, "$chem1", NULL, it, USD_chem1_ECMA);
    p->add_var(p->dbname, "$chem2", NULL, it, USD_chem2_ECMA);
    p->add_var(p->dbname, "$chem3", NULL, it, USD_chem3_ECMA);
    p->add_var(p->dbname, "$chem4", NULL, it, USD_chem4_ECMA);
    p->add_var(p->dbname, "$chem5", NULL, it, USD_chem5_ECMA);
    p->add_var(p->dbname, "$cod", NULL, it, USD_cod_ECMA);
    p->add_var(p->dbname, "$rao", NULL, it, USD_rao_ECMA);
    p->add_var(p->dbname, "$od", NULL, it, USD_od_ECMA);
    p->add_var(p->dbname, "$rfltnc", NULL, it, USD_rfltnc_ECMA);
    p->add_var(p->dbname, "$nsoilm", NULL, it, USD_nsoilm_ECMA);
    p->add_var(p->dbname, "$soilm", NULL, it, USD_soilm_ECMA);
    p->add_var(p->dbname, "$flgt_phase", NULL, it, USD_flgt_phase_ECMA);
    p->add_var(p->dbname, "$height_assignment_method", NULL, it, USD_height_assignment_method_ECMA);
    p->add_var(p->dbname, "$dopp", NULL, it, USD_dopp_ECMA);
    p->add_var(p->dbname, "$ghg1", NULL, it, USD_ghg1_ECMA);
    p->add_var(p->dbname, "$ghg2", NULL, it, USD_ghg2_ECMA);
    p->add_var(p->dbname, "$ghg3", NULL, it, USD_ghg3_ECMA);
    p->add_var(p->dbname, "$bt_real", NULL, it, USD_bt_real_ECMA);
    p->add_var(p->dbname, "$bt_imaginary", NULL, it, USD_bt_imaginary_ECMA);
    p->add_var(p->dbname, "$prc", NULL, it, USD_prc_ECMA);
    p->add_var(p->dbname, "$lnprc", NULL, it, USD_lnprc_ECMA);
    p->add_var(p->dbname, "$libksc", NULL, it, USD_libksc_ECMA);
    p->add_var(p->dbname, "$ralt_swh", NULL, it, USD_ralt_swh_ECMA);
    p->add_var(p->dbname, "$ralt_sws", NULL, it, USD_ralt_sws_ECMA);
    p->add_var(p->dbname, "$rawbt_clear", NULL, it, USD_rawbt_clear_ECMA);
    p->add_var(p->dbname, "$rawbt_cloudy", NULL, it, USD_rawbt_cloudy_ECMA);
    p->add_var(p->dbname, "$binary_snow_cover", NULL, it, USD_binary_snow_cover_ECMA);
    p->add_var(p->dbname, "$salinity", NULL, it, USD_salinity_ECMA);
    p->add_var(p->dbname, "$potential_temp", NULL, it, USD_potential_temp_ECMA);
    p->add_var(p->dbname, "$humidity_mixing_ratio", NULL, it, USD_humidity_mixing_ratio_ECMA);
    p->add_var(p->dbname, "$airframe_icing", NULL, it, USD_airframe_icing_ECMA);
    p->add_var(p->dbname, "$turbulence_index", NULL, it, USD_turbulence_index_ECMA);
    p->add_var(p->dbname, "$lidar_aerosol_extinction", NULL, it, USD_lidar_aerosol_extinction_ECMA);
    p->add_var(p->dbname, "$lidar_cloud_backscatter", NULL, it, USD_lidar_cloud_backscatter_ECMA);
    p->add_var(p->dbname, "$lidar_cloud_extinction", NULL, it, USD_lidar_cloud_extinction_ECMA);
    p->add_var(p->dbname, "$cloud_radar_reflectivity", NULL, it, USD_cloud_radar_reflectivity_ECMA);
    p->add_var(p->dbname, "$q2m", NULL, it, USD_q2m_ECMA);
    p->add_var(p->dbname, "$pstation", NULL, it, USD_pstation_ECMA);
    p->add_var(p->dbname, "$pmsl", NULL, it, USD_pmsl_ECMA);
    p->add_var(p->dbname, "$pstandard", NULL, it, USD_pstandard_ECMA);
    p->add_var(p->dbname, "$vert_vv", NULL, it, USD_vert_vv_ECMA);
    p->add_var(p->dbname, "$max_wind_shear1", NULL, it, USD_max_wind_shear1_ECMA);
    p->add_var(p->dbname, "$tot_zen_delay", NULL, it, USD_tot_zen_delay_ECMA);
    p->add_var(p->dbname, "$tot_zen_delay_err", NULL, it, USD_tot_zen_delay_err_ECMA);
    p->add_var(p->dbname, "$cloud_top_temp", NULL, it, USD_cloud_top_temp_ECMA);
    p->add_var(p->dbname, "$rawsca", NULL, it, USD_rawsca_ECMA);
    p->add_var(p->dbname, "$cloud_top_press", NULL, it, USD_cloud_top_press_ECMA);
    p->add_var(p->dbname, "$mean_freq", NULL, it, USD_mean_freq_ECMA);
    p->add_var(p->dbname, "$u_amb", NULL, it, USD_u_amb_ECMA);
    p->add_var(p->dbname, "$v_amb", NULL, it, USD_v_amb_ECMA);
    p->add_var(p->dbname, "$lwp", NULL, it, USD_lwp_ECMA);
    p->add_var(p->dbname, "$tcwv", NULL, it, USD_tcwv_ECMA);
    p->add_var(p->dbname, "$theta", NULL, it, USD_theta_ECMA);
    p->add_var(p->dbname, "$cloud_frac_clear", NULL, it, USD_cloud_frac_clear_ECMA);
    p->add_var(p->dbname, "$rawbt_hirs", NULL, it, USD_rawbt_hirs_ECMA);
    p->add_var(p->dbname, "$rawbt_amsu", NULL, it, USD_rawbt_amsu_ECMA);
    p->add_var(p->dbname, "$rawbt_hirs20", NULL, it, USD_rawbt_hirs20_ECMA);
    p->add_var(p->dbname, "$sea_ice", NULL, it, USD_sea_ice_ECMA);
    p->add_var(p->dbname, "$cloud_frac_covered", NULL, it, USD_cloud_frac_covered_ECMA);
    p->add_var(p->dbname, "$level_mixing_ratio", NULL, it, USD_level_mixing_ratio_ECMA);
    p->add_var(p->dbname, "$radial_velocity", NULL, it, USD_radial_velocity_ECMA);
    p->add_var(p->dbname, "$cloud_ice_water", NULL, it, USD_cloud_ice_water_ECMA);
    p->add_var(p->dbname, "$wind_gust", NULL, it, USD_wind_gust_ECMA);
    p->add_var(p->dbname, "$mass_density", NULL, it, USD_mass_density_ECMA);
    p->add_var(p->dbname, "$atmosphere_number", NULL, it, USD_atmosphere_number_ECMA);
    p->add_var(p->dbname, "$lightning", NULL, it, USD_lightning_ECMA);
    p->add_var(p->dbname, "$level_cloud", NULL, it, USD_level_cloud_ECMA);
    p->add_var(p->dbname, "$rawbt_amsr_89ghz", NULL, it, USD_rawbt_amsr_89ghz_ECMA);
    p->add_var(p->dbname, "$max_wind_shear2", NULL, it, USD_max_wind_shear2_ECMA);
    p->add_var(p->dbname, "$lower_layer_p", NULL, it, USD_lower_layer_p_ECMA);
    p->add_var(p->dbname, "$upper_layer_p", NULL, it, USD_upper_layer_p_ECMA);
    p->add_var(p->dbname, "$cloud_cover", NULL, it, USD_cloud_cover_ECMA);
    p->add_var(p->dbname, "$depth", NULL, it, USD_depth_ECMA);
    p->add_var(p->dbname, "$ssh", NULL, it, USD_ssh_ECMA);
    p->add_var(p->dbname, "$rawbt_mwts", NULL, it, USD_rawbt_mwts_ECMA);
    p->add_var(p->dbname, "$rawbt_mwhs", NULL, it, USD_rawbt_mwhs_ECMA);
    p->add_var(p->dbname, "$pressure", NULL, it, USD_pressure_ECMA);
    p->add_var(p->dbname, "$gpheight", NULL, it, USD_gpheight_ECMA);
    p->add_var(p->dbname, "$tovs_cha", NULL, it, USD_tovs_cha_ECMA);
    p->add_var(p->dbname, "$scat_cha", NULL, it, USD_scat_cha_ECMA);
    p->add_var(p->dbname, "$modlevno", NULL, it, USD_modlevno_ECMA);
    p->add_var(p->dbname, "$imp_param", NULL, it, USD_imp_param_ECMA);
    p->add_var(p->dbname, "$cha_number", NULL, it, USD_cha_number_ECMA);
    p->add_var(p->dbname, "$cha_wavelength", NULL, it, USD_cha_wavelength_ECMA);
    p->add_var(p->dbname, "$cha_frequency", NULL, it, USD_cha_frequency_ECMA);
    p->add_var(p->dbname, "$ocean_depth", NULL, it, USD_ocean_depth_ECMA);
    p->add_var(p->dbname, "$derived_pressure", NULL, it, USD_derived_pressure_ECMA);
    p->add_var(p->dbname, "$amb_wind_num", NULL, it, USD_amb_wind_num_ECMA);
    p->add_var(p->dbname, "$cloud_top_pressure", NULL, it, USD_cloud_top_pressure_ECMA);
    p->add_var(p->dbname, "$tangent_height", NULL, it, USD_tangent_height_ECMA);
    p->add_var(p->dbname, "$model_pressure", NULL, it, USD_model_pressure_ECMA);
    p->add_var(p->dbname, "$psealev", NULL, it, USD_psealev_ECMA);
    p->add_var(p->dbname, "$pstalev", NULL, it, USD_pstalev_ECMA);
    p->add_var(p->dbname, "$g850hpa", NULL, it, USD_g850hpa_ECMA);
    p->add_var(p->dbname, "$g700hpa", NULL, it, USD_g700hpa_ECMA);
    p->add_var(p->dbname, "$p500gpm", NULL, it, USD_p500gpm_ECMA);
    p->add_var(p->dbname, "$p1000gpm", NULL, it, USD_p1000gpm_ECMA);
    p->add_var(p->dbname, "$p2000gpm", NULL, it, USD_p2000gpm_ECMA);
    p->add_var(p->dbname, "$p3000gpm", NULL, it, USD_p3000gpm_ECMA);
    p->add_var(p->dbname, "$p4000gpm", NULL, it, USD_p4000gpm_ECMA);
    p->add_var(p->dbname, "$g900hpa", NULL, it, USD_g900hpa_ECMA);
    p->add_var(p->dbname, "$g1000hpa", NULL, it, USD_g1000hpa_ECMA);
    p->add_var(p->dbname, "$g500hpa", NULL, it, USD_g500hpa_ECMA);
    p->add_var(p->dbname, "$g925hpa", NULL, it, USD_g925hpa_ECMA);
    p->add_var(p->dbname, "$hirs", NULL, it, USD_hirs_ECMA);
    p->add_var(p->dbname, "$msu", NULL, it, USD_msu_ECMA);
    p->add_var(p->dbname, "$ssu", NULL, it, USD_ssu_ECMA);
    p->add_var(p->dbname, "$amsua", NULL, it, USD_amsua_ECMA);
    p->add_var(p->dbname, "$amsub", NULL, it, USD_amsub_ECMA);
    p->add_var(p->dbname, "$tmi", NULL, it, USD_tmi_ECMA);
    p->add_var(p->dbname, "$ssmis", NULL, it, USD_ssmis_ECMA);
    p->add_var(p->dbname, "$iasi", NULL, it, USD_iasi_ECMA);
    p->add_var(p->dbname, "$amsre", NULL, it, USD_amsre_ECMA);
    p->add_var(p->dbname, "$amsr2", NULL, it, USD_amsr2_ECMA);
    p->add_var(p->dbname, "$mwri", NULL, it, USD_mwri_ECMA);
    p->add_var(p->dbname, "$atms", NULL, it, USD_atms_ECMA);
    p->add_var(p->dbname, "$meteosat", NULL, it, USD_meteosat_ECMA);
    p->add_var(p->dbname, "$iras", NULL, it, USD_iras_ECMA);
    p->add_var(p->dbname, "$mwts", NULL, it, USD_mwts_ECMA);
    p->add_var(p->dbname, "$mwhs", NULL, it, USD_mwhs_ECMA);
    p->add_var(p->dbname, "$gmi", NULL, it, USD_gmi_ECMA);
    p->add_var(p->dbname, "$bg", NULL, it, USD_bg_ECMA);
    p->add_var(p->dbname, "$adj", NULL, it, USD_adj_ECMA);
    p->add_var(p->dbname, "$resat_retrtype_ak", NULL, it, USD_resat_retrtype_ak_ECMA);
    p->add_var(p->dbname, "$resat_retrtype", NULL, it, USD_resat_retrtype_ECMA);
    p->add_var(p->dbname, "$mx_ak", NULL, it, USD_mx_ak_ECMA);
    p->add_var(p->dbname, "$mx_radar_niv", NULL, it, USD_mx_radar_niv_ECMA);
    p->add_var(p->dbname, "$mx_limb_tan", NULL, it, USD_mx_limb_tan_ECMA);
  } /* if (add_vars) */
  finish:
  DRHOOK_END(0);
  return NULL;
}
