CREATE VIEW ofb_6 AS
SELECT   
  expver                         as expver   ,    
  class                          as class    ,    
  stream                         as stream   ,    
  type                           as type     ,    
  andate                         as andate   ,    
  antime                         as antime   ,    
  reportype                      as reportype,    

  numtsl                                       ,

  timeslot                                     ,

  seqno                  ,    
  groupid                ,    
  date                   ,    
  time                   ,    
  rdbdate                                           ,
  rdbtime                                           ,
  report_status          ,    
  report_event1          ,    
  report_rdbflag         ,
  degrees(lat)           as lat@hdr                ,    
  degrees(lon)           as lon@hdr                ,    

  obstype                ,
  sensor                 ,
  subtype                ,

  satellite_instrument@sat,
  satellite_identifier@sat, 
  instrument_type@resat   ,
  product_type           ,
  lat_fovcorner[1:4]     ,
  lon_fovcorner[1:4]     ,
  solar_elevation        ,
  scanpos                ,
  cloud_cover            ,
  cloud_top_press        ,
  quality_retrieval      ,
  number_layers          ,
  snow_ice_indicator     ,
  surface_type_indicator ,
  methane_correction     ,
  surface_height         ,
  retrsource             ,

  entryno                                      ,
  obsvalue                                     ,
  varno                                        ,
  vertco_type                                  ,
  vertco_reference_1                           ,
  vertco_reference_2                           ,

  datum_status                                 ,    
  datum_event1                                 ,    
  datum_anflag                                 ,
  biascorr                                     ,
  biascorr_fg                                  ,
  an_depar                                     ,
  fg_depar                                     ,
  datum_status_hires@update_1                        ,

  obs_error                                    ,
  final_obs_error                              ,
  qc_pge                                       ,
  fg_error                                     ,
  an_sens_obs, 
  fc_sens_obs, 
  datum_rdbflag,
  mxup_traj,
  codetype, 
  hires@update_2,
  bufrtype
FROM desc, timeslot_index, hdr, sat, resat, body, errstat, update_1, update_2
WHERE reportype is not null
AND groupid=6;
