CREATE VIEW ofb_5 AS
SELECT   
  expver                 as expver             ,    
  class                  as class              ,    
  stream                 as stream             ,    
  type                   as type               ,    
  andate                 as andate             ,    
  antime                 as antime             ,    
  reportype              as reportype          ,    

  numtsl                             ,    

  timeslot                           ,

  seqno                                 ,    
  bufrtype                           ,    
  subtype                             ,    
  groupid                             ,    
  obstype                             ,    
  codetype                           ,    
  sensor                               ,    
  date                                   ,    
  time                                   ,    
  rdbdate                                           ,
  rdbtime                                           ,
  report_status                                ,    
  report_event1                                ,    
  report_rdbflag                               ,    
  degrees(lat)           as lat@hdr                ,    
  degrees(lon)           as lon@hdr                ,    

  lsm                                     ,
  zenith                                         ,
  azimuth                                        ,
  asr_pclear                          ,
  asr_pcloudy                         ,
  asr_pcloudy_low                         ,
  asr_pcloudy_middle                         ,
  asr_pcloudy_high                         ,
  
  entryno                             ,    
  obsvalue                           ,    
  varno                                 ,    
  vertco_type                     ,    
  vertco_reference_1       ,    
  csr_pclear                       ,

  datum_anflag                                 ,    
  datum_status                                 ,    
  datum_event1                                 ,    
  datum_rdbflag                                ,    
  qc_pge                             ,
  biascorr                           ,    
  biascorr_fg                           ,    
  an_depar                           ,    
  fg_depar                           ,    
  datum_status_hires@update_1                        ,

  obs_error                         ,
  final_obs_error                         ,
  repres_error                       ,
  fg_error                           ,
  eda_spread                         ,
  satellite_identifier               ,

  skintemp_1                                   ,
  skintemp_2                                   ,
  skintemp_3                                   ,
  skintemp_4                                   ,
  skintemper                                   ,
  tausfc                                       ,
  cldne_2,
  an_sens_obs,
  fc_sens_obs,
  cldptop_2,
  mxup_traj,
  hires@update_2,
FROM desc, timeslot_index, hdr, sat, modsurf, body, errstat, radiance, radiance_body, update_1, update_2
WHERE reportype is not null
AND groupid=5;
