INTERFACE
SUBROUTINE ESPCPL(KDLON,KDGLG,KFLEVG,KSTA,KEND,KOFF,&
 & KNVALUE,KMVALUE,KMPSP_Q,KNEK0,KNEK1,KNEN1,KNEN2,LDSPNUSPDL,LDSPQ, &
 & PSPNUDVOR,PSPNUDDIV,PSPNUDT,PSPNUDQ,PSPNUDSP, &
 & PSPVOR3G,PSPDIV3G,PSPT3G,PSPGFL3G,PSPSP3G, &
 & PSPVORG,PSPDIVG,PSPTG,PSPGFL,PSPSPG)
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB

!     ------------------------------------------------------------------

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KDLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KDGLG
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTA
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND
INTEGER(KIND=JPIM),INTENT(IN)    :: KOFF
INTEGER(KIND=JPIM),INTENT(IN)    :: KNVALUE(:)
INTEGER(KIND=JPIM),INTENT(IN)    :: KMVALUE(:)
INTEGER(KIND=JPIM),INTENT(IN)    :: KMPSP_Q
INTEGER(KIND=JPIM),INTENT(IN)    :: KNEK0
INTEGER(KIND=JPIM),INTENT(IN)    :: KNEK1
INTEGER(KIND=JPIM),INTENT(IN)    :: KNEN1
INTEGER(KIND=JPIM),INTENT(IN)    :: KNEN2
LOGICAL           ,INTENT(IN)    :: LDSPNUSPDL
LOGICAL           ,INTENT(IN)    :: LDSPQ
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPNUDVOR
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPNUDDIV
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPNUDT
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPNUDQ
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPNUDSP
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPVOR3G(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPDIV3G(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPT3G(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPGFL3G(:,:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSPSP3G(:)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPVORG(:,:) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPDIVG(:,:) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPTG(:,:) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPGFL(:,:,:) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSPSPG(:) 

!     ------------------------------------------------------------------
END SUBROUTINE ESPCPL
END INTERFACE
