INTERFACE
SUBROUTINE ESPSC2R(KS3D,KSPEC2,KFLEVL,KCPLSPEC2,KSPGFL,KDIMGT3,KSTOP,KMPSP_Q,KOFFGT3BSP,KSTEP,LDSPQ,LDSPSP, &
 & LDSPTENC,PNUDTFRAC,PNUDTENC,PGT3SPBUF,PEWB, &
 & PSPVOR3,PSPDIV3,PSPT3,PSPGFL3,PSPSP3)
!     ------------------------------------------------------------------
USE PARKIND1  ,ONLY : JPIM     ,JPRB
!     ------------------------------------------------------------------
IMPLICIT NONE
!     ------------------------------------------------------------------
INTEGER(KIND=JPIM),INTENT(IN)    :: KS3D
INTEGER(KIND=JPIM),INTENT(IN)    :: KSPEC2
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVL
INTEGER(KIND=JPIM),INTENT(IN)    :: KCPLSPEC2
INTEGER(KIND=JPIM),INTENT(IN)    :: KSPGFL
INTEGER(KIND=JPIM),INTENT(IN)    :: KDIMGT3
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTOP
INTEGER(KIND=JPIM),INTENT(IN)    :: KMPSP_Q
INTEGER(KIND=JPIM),INTENT(IN)    :: KOFFGT3BSP
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTEP
LOGICAL           ,INTENT(IN)    :: LDSPQ
LOGICAL           ,INTENT(IN)    :: LDSPSP
LOGICAL           ,INTENT(IN)    :: LDSPTENC
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNUDTFRAC
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNUDTENC
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGT3SPBUF(KDIMGT3)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEWB(0:KSTOP,1:4,0:9)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPVOR3(KFLEVL,KCPLSPEC2)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPDIV3(KFLEVL,KCPLSPEC2)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPT3(KFLEVL,KCPLSPEC2)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPGFL3(KFLEVL,KCPLSPEC2,KSPGFL)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSPSP3(KCPLSPEC2)
!     ------------------------------------------------------------------
END SUBROUTINE ESPSC2R
END INTERFACE
