INTERFACE
SUBROUTINE ESRLXT1AD(KLON,KFLEV,KDIMCPL_GMV,KDIMCPL_GMVS,KDIMCPL_GFL,&
 & PALFAGMV,PALFAGMVS,PALFAGFL,&
 & PGT3GMV,PGT3GMVS,PGT3GFL,PGT1GMV,PGT1GMVS,PGT1GFL)

!----------------------------------------------------------------------
 
USE PARKIND1  ,ONLY : JPIM     ,JPRB

!----------------------------------------------------------------------

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KDIMCPL_GMV
INTEGER(KIND=JPIM),INTENT(IN)    :: KDIMCPL_GMVS
INTEGER(KIND=JPIM),INTENT(IN)    :: KDIMCPL_GFL
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALFAGMV(KLON,KDIMCPL_GMV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALFAGMVS(KLON,KDIMCPL_GMVS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALFAGFL(KLON,KDIMCPL_GFL)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PGT3GMV(KLON,KFLEV,KDIMCPL_GMV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PGT3GMVS(KLON,KDIMCPL_GMVS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PGT3GFL(KLON,KFLEV,KDIMCPL_GFL)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGT1GMV(KLON,KFLEV,KDIMCPL_GMV)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGT1GMVS(KLON,KDIMCPL_GMVS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGT1GFL(KLON,KFLEV,KDIMCPL_GFL)

!----------------------------------------------------------------------
END SUBROUTINE ESRLXT1AD
END INTERFACE
