INTERFACE
SUBROUTINE GPCOUPL(KSWAP,KCOUPLING,KST,KEND,KLON,KFIELDS,PW,PCPL,PGT3)

USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KSWAP
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KCOUPLING
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KST
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KEND
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KFIELDS
REAL(KIND=JPRB)    ,INTENT(IN)  :: PW(KSWAP)
REAL(KIND=JPRB)    ,INTENT(IN)  :: PCPL(KLON,KSWAP,KFIELDS)
REAL(KIND=JPRB)    ,INTENT(OUT) :: PGT3(KLON,KFIELDS)

END SUBROUTINE GPCOUPL
END INTERFACE
