INTERFACE
SUBROUTINE GPCOUPLAD(KSWAP,KCOUPLING,KST,KEND,KLON,KFIELDS,PGT3,PW,PCPL)

USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE

INTEGER(KIND=JPIM) ,INTENT(IN)  :: KSWAP
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KCOUPLING
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KST
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KEND
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN)  :: KFIELDS
REAL(KIND=JPRB)    ,INTENT(IN)  :: PW(KSWAP)
REAL(KIND=JPRB)    ,INTENT(IN)  :: PGT3(KLON)
REAL(KIND=JPRB)    ,INTENT(OUT) :: PCPL(KLON,KSWAP)

END SUBROUTINE GPCOUPLAD
END INTERFACE
