INTERFACE
SUBROUTINE ACACON ( YDML_PHY_MF,KIDIA,KFDIA,KLON,&
 & LDSIMP,&
 & PEXPA,PEXPN,PLSCP,PPART,PLSM,PNEIJ,PTS,&
 & PQIST,PQLST,PQNST,PQRST,PQGST,PTST,&
 & PACONI,PACONL,PACORL,PACOGI,PACOGL) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL ,INTENT(IN) :: LDSIMP
REAL(KIND=JPRB) ,INTENT(IN) :: PEXPA(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEXPN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PPART(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQIST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQLST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQNST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQRST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQGST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTST(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PACONI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PACONL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PACORL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PACOGI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PACOGL(KLON)
END SUBROUTINE ACACON
END INTERFACE
