INTERFACE
SUBROUTINE ACCOLL ( YDML_PHY_MF,KIDIA,KFDIA,KLON,&
 & PEXPN,PHPLSL,PHPLSN,PHPLSG,PLPLSL,PLPLSN,PLPLSG,PLSCP,PPART,PRCOLL,PRHOAIR,&
 & PQIST,PQLST,PQNST,PQRST,PQGST,PTST,&
 & PCOLNI,PCOLNL,PCOLRI,PCOLRL,PCOLGI,PCOLGL) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PEXPN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHPLSL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHPLSN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHPLSG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLPLSL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLPLSN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLPLSG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PPART(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCOLL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHOAIR(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQIST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQLST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQNST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQRST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQGST(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTST(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLNI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLNL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLRI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLRL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLGI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOLGL(KLON)
END SUBROUTINE ACCOLL
END INTERFACE
