INTERFACE
SUBROUTINE ACCSU ( YDECUCONVCA,YDECUMF,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PR,&
 & PCVGQ, PDELP,PLNPR,&
 & PQ, PQCS, PQI, PQL, PQSAT,PQW,&
 & PRDELP,PT,PTW, PU,PV,PVORT0,&
 & PVERVEL,&
 & PFCSQL, PFCSQN,&
 & PTS,PTAUX,PRCORI, PDECRD,&
 & PUDGRO,&
 & PCUCONVCA,PNLCONVCA,&
 & PDIFCQ,PDIFCQL,PDIFCQI, PDIFCS,&
 & PFCCQL,PFCCQI,PSTRCU,PSTRCV,PZATSLC,&
 & KNACT,PFRDE,PDETFI,&
 & PTU, PQU, PUU, PVU,&
 & KNND,PCAPE,&
 & PGEOSLC,PENTCH,PUDAL,PUDOM) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 , ONLY: JPIM, JPRB
USE YOE_CUCONVCA, ONLY : TECUCONVCA
USE YOECUMF , ONLY : TECUMF
TYPE(TECUCONVCA) ,INTENT(IN) :: YDECUCONVCA
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCVGQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQCS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVORT0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAUX(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCORI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDECRD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUDGRO(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCUCONVCA(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNLCONVCA(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNACT(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNND(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCCQI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFRDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDETFI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRCU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRCV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZATSLC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOSLC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUDAL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUDOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PENTCH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVU(KLON,KLEV)
END SUBROUTINE ACCSU
END INTERFACE
