INTERFACE
SUBROUTINE ACCVIMPDGY( YDPHY,YDPHY0,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & KNCDN,KNLAB,&
 & PALPH,PAPHIF,PAPRS,PAPRSF,&
 & PDELP,PLH,PLNPR,PQ,PQLIC,PQLIS,&
 & PQSAT,PQW,PR,PT,PTW,&
 & PU,PV,&
 & KLEVTEN,&
 & PBET,PDELA,PFORM,PQDN,&
 & PQN2,PSDN,PUM,PVM,&
 & KNLABD) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY , ONLY : TPHY
USE YOMPHY0 , ONLY : TPHY0
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KNCDN(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KNLAB(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVTEN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLIC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLIS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBET(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDELA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFORM(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQDN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQN2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSDN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVM(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNLABD(KLON,KLEV)
END SUBROUTINE ACCVIMPDGY
END INTERFACE
