INTERFACE
SUBROUTINE ACDIFOZ ( YDRIP,YDPHY2,YDVDOZ,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PAPRSF,PDELP,PFPLCL,PFPLSL,PFRSO,&
 & PKTROV,POZONE,PRDELP,PT,PXTROV,&
 & PNEIJ,PGEMU,PIVEG,&
 & PDIFTO) 
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE YOMPHY2 , ONLY : TPHY2
USE YOMRIP , ONLY : TRIP
USE YOMVDOZ , ONLY : TVDOZ
TYPE(TPHY2) ,INTENT(IN) :: YDPHY2
TYPE(TRIP) ,INTENT(IN) :: YDRIP
TYPE(TVDOZ) ,INTENT(IN) :: YDVDOZ
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKTROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POZONE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXTROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PIVEG(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFTO(KLON,0:KLEV)
END SUBROUTINE ACDIFOZ
END INTERFACE
