INTERFACE
SUBROUTINE ACDRO ( YDML_PHY_MF,KIDIA,KFDIA,KLON,KLEV,&
 & PFPLCL,PFPLCN,PFPLSL,PFPLSN,PFRSO,PFRTH,&
 & PFCHSP,PFCLL,PFCLN,PFCS,PFEVL,PFEVN,PLSM,PSNS,&
 & PTS,PWP,PWS,PCT,&
 & PFLWSP,PFONTE,PRUISP,PRUISS) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCHSP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLWSP(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFONTE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISS(KLON)
END SUBROUTINE ACDRO
END INTERFACE
