INTERFACE
SUBROUTINE ACFLSMO ( KIDIA,KFDIA,KLON,KTDIA,KLEV,PAPHIF,PAPRS,PDELP,CDFLUX,PFLUX)
USE PARKIND1, ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON,KLEV)
CHARACTER(LEN=*), INTENT(IN) :: CDFLUX
REAL(KIND=JPRB), INTENT(INOUT) :: PFLUX(KLON,0:KLEV)
END SUBROUTINE ACFLSMO
END INTERFACE
