INTERFACE
SUBROUTINE ACHMTTL ( KIDIA,KFDIA,KLON,KLEV,&
 & PAPHI5,PAPHIF5,PAPRS5,PAPRSF5,PCP5,PQ5,PR5,PT5,&
 & PU5,PV5,PGZ0F5,PHV5,&
 & PNEIJG5,PNEIJV5,PSNS5,PTS5,PWS5,PWSI5,&
 & PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PQ,PR,PT,PU,PV,&
 & PDPHIT,PDPHIV,PGZ0F,PGZ0HF,PGZ0RLF,PHV,PLSM,&
 & PNEIJG,PNEIJV,PSNS,PTS,PVEG0,PWFC,PWS,PWSI,&
 & LDCLS,LDHMT,LDZ0H,&
 & PNBVNO,&
 & PCD,PCDN,PCDROV,PCH,PCHROV,PCPS,PDQSTS,PGWDCS,&
 & PGZ0,PHQ,PHU,PNEIJ,PQCLS,PQS,PQSATS,&
 & PRHCLS,PRS,PSTAB,PTCLS,PUCLS,PVCLS,PUCLN,PVCLN,PZPCLS,PVEG,&
 & PXDROV,PXHROV,&
 & PNBVNO5,&
 & PCD5,PCDN5,PCDROV5,PCH5,PCHROV5,PCPS5,PDQSTS5,&
 & PGWDCS5,&
 & PGZ05,PHQ5,PHU5,PNEIJ5,PQCLS5,PQS5,PQSATS5,&
 & PRHCLS5,PRS5,PTCLS5,PUCLS5,PVCLS5,PZPCLS5,PVEG5,&
 & PXDROV5,PXHROV5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0F5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHV5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJG5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJV5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSI5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0F(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0HF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0RLF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEG0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWFC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSI(KLON)
LOGICAL ,INTENT(IN) :: LDCLS
LOGICAL ,INTENT(IN) :: LDHMT
LOGICAL ,INTENT(IN) :: LDZ0H
REAL(KIND=JPRB) ,INTENT(OUT) :: PNBVNO(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDROV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCHROV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDQSTS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGWDCS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHQ(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSATS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRHCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTAB(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZPCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVEG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXDROV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXHROV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNBVNO5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCD5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDN5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDROV5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCH5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCHROV5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDQSTS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGWDCS5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGZ05(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHQ5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHU5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEIJ5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSATS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRHCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZPCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVEG5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXDROV5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXHROV5(KLON)
END SUBROUTINE ACHMTTL
END INTERFACE
