INTERFACE
SUBROUTINE ACHMTAD ( KIDIA,KFDIA,KLON,KLEV,&
 & PAPHI5,PAPHIF5,PAPRS5,PAPRSF5,PCP5,PQ5,PR5,PT5,&
 & PU5,PV5,PGZ0F5,PHV5,&
 & PNEIJG5,PNEIJV5,PSNS5,PTS5,PWS5,PWSI5,&
 & PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PQ,PR,PT,PU,PV,&
 & PDPHIT,PDPHIV,PGZ0F,PGZ0HF,PGZ0RLF,PHV,PLSM,&
 & PNEIJG,PNEIJV,PSNS,PTS,PVEG0,PWFC,PWS,PWSI,&
 & LDCLS,LDHMT,LDZ0H,&
 & PNBVNO,&
 & PCD,PCDN,PCDROV,PCH,PCHROV,PCPS,PDQSTS,PGWDCS,&
 & PGZ0,PHQ,PHU,PNEIJ,PQCLS,PQS,PQSATS,&
 & PRHCLS,PRS,PSTAB,PTCLS,PUCLS,PVCLS,PUCLN,PVCLN,PZPCLS,PVEG,&
 & PXDROV,PXHROV) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0F5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHV5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJG5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJV5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSI5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGZ0F(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0HF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0RLF(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEIJG(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEIJV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSNS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEG0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWFC(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWSI(KLON)
LOGICAL ,INTENT(IN) :: LDCLS
LOGICAL ,INTENT(IN) :: LDHMT
LOGICAL ,INTENT(IN) :: LDZ0H
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNBVNO(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDROV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCH(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCHROV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDQSTS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGWDCS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHQ(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSATS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRHCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTAB(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUCLN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCLN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZPCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVEG(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXDROV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXHROV(KLON)
END SUBROUTINE ACHMTAD
END INTERFACE
