INTERFACE
SUBROUTINE ACMIXLENTM ( YDPHY0,KIDIA,KFDIA,KLON,KLEV,&
 & PAPHI,PAPHIF,&
 & PGZ0,PGZ0H,PBLH,&
 & PLMU,PLMT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY0 , ONLY : TPHY0
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PBLH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLMU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLMT(KLON,0:KLEV)
END SUBROUTINE ACMIXLENTM
END INTERFACE
