INTERFACE
SUBROUTINE ACMRIP(YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KSTEP,&
 & PAPHI,PAPHIF,PAPRS,PAPRSF,PQ,PQL,PQI,PCP,&
 & PALPH,PLNPR,PQSAT,PQW,PTW,&
 & PR,PT,PU,PV,&
 & PDIFTQ,PDIFTS,PSHEAR,&
 & PTKE,PTTE,&
 & PTS,PQSH,PRS,PCPS,PRTI,PGZ0,&
 & LDCLS,&
 & PMRIPP,PMRIFPP,&
 & PNEBCVPP,PNEBQ,PNBVNO,&
 & PFMTKE,PFTTKE,PF_EPS,PFUN_TTE,&
 & PAUTKE,PATTKE,&
 & PFHORM,PFHORH,&
 & PTH_FUN,PWW_FUN,&
 & PMRIMC,PMRICTERM,PMN2PP,&
 & PMN2_ES,PMN2_EQ,PMN2_DS,PMN2_DQ,PFMGST) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQW (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTW (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTKE (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTE (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSHEAR (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSH (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRS (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPS (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTI (KLON)
LOGICAL ,INTENT(IN) :: LDCLS
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0 (KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMRIPP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMRIFPP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMN2PP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMN2_ES (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMN2_EQ (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMN2_DS (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMN2_DQ (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFMTKE(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFTTKE(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAUTKE(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PATTKE(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PF_EPS (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFUN_TTE (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWW_FUN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTH_FUN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEBCVPP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEBQ (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNBVNO (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMRIMC (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMRICTERM (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHORM (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHORH (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFMGST (KLON,0:KLEV)
END SUBROUTINE ACMRIP
END INTERFACE
