INTERFACE
SUBROUTINE ACMRIS(YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PDELP,PLSCPE,PQ,PQL,PQI,PQSAT,&
 & PR,PT,PU,PV,PLMU,PLMT,&
 & PGZ0,&
 & PMRIPP) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCPE (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLMU (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLMT (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0 (KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMRIPP (KLON,0:KLEV)
END SUBROUTINE ACMRIS
END INTERFACE
