INTERFACE
SUBROUTINE ACMTUD (YDGEM,YDDIM,YDEGEO,YDLDDH,YDMDDH,YDRIP,YDML_PHY_MF, KIDIA,KFDIA,KLON,KTDIA,KLEV,KTRA,&
 & PALPH,PAPHI,PAPHIF,PAPRS,PAPRSF,PVERVEL,PCP,PLH,PR,&
 & PDELP,PLNPR,&
 & PQ,PQLIS,PQSAT,PQW,&
 & PRDELP,PCVGQ,PT,PTW,PU,PV,PTKE,PTRA,PSMOOTRA,PEVAPO,&
 & PGM, PTS,&
 & PDIFCQ,PDIFCQL,PDIFCQI,PDIFCS,PDIFCTH,PPRODTH,&
 & PFCCQL,PFCCQI,PSTRCU,PSTRCV,PSTRCTRA,&
 & PFHMLTS,PFHEVPP,PFPEVPCL,PFPEVPCN,&
 & PFPLCL,PFPLCN,PMF_UP,PMU,PMD,&
 & PNEBC,PQLIC,PTU,PQU,KNLAB,PENTR_U,PDETR_U,PENTR_D,PDETR_D,&
 & PENTR_U_TOT,&
 & KNND,PCAPE,PALF,PALF_CAPE,PALF_CVGQ,&
 & PUDAL,PUDOM,PDDAL,PDDOM,YDDDH) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOMMDDH , ONLY : TMDDH
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDIM , ONLY : TDIM
USE YOMGEM , ONLY : TGEM
USE YEMGEO , ONLY : TEGEO
USE DDH_MIX , ONLY : ADD_FIELD_3D, NEW_ADD_FIELD_3D, TYP_DDH
USE YOMLDDH , ONLY : TLDDH
USE YOMRIP , ONLY : TRIP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TEGEO) , INTENT(IN) :: YDEGEO
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TLDDH) , INTENT(IN) :: YDLDDH
TYPE(TMDDH) , INTENT(IN) :: YDMDDH
TYPE(TRIP) , INTENT(IN) :: YDRIP
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTRA
REAL(KIND=JPRB), INTENT(IN) :: PALPH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PLH(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PLNPR(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQLIS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQW(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCVGQ(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTW(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTRA(KLON,KLEV,KTRA)
REAL(KIND=JPRB), INTENT(IN) :: PSMOOTRA(KTRA)
REAL(KIND=JPRB), INTENT(IN) :: PTKE(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PEVAPO(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PGM(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PTS(KLON)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNLAB(KLON,KLEV)
INTEGER(KIND=JPIM), INTENT(INOUT) :: KNND(KLON)
REAL(KIND=JPRB) , INTENT(INOUT) :: PALF(KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PCAPE(KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDIFCTH(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PPRODTH(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFCCQI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSTRCU(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSTRCV(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSTRCTRA(KLON,0:KLEV,KTRA)
REAL(KIND=JPRB), INTENT(OUT) :: PMF_UP(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PMU(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PMD(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PNEBC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PQLIC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFHMLTS(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PENTR_U(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PDETR_U(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PENTR_D(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PDETR_D(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PENTR_U_TOT(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFPEVPCL(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFPEVPCN(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PFHEVPP(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PALF_CAPE(KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PALF_CVGQ(KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PUDOM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDAL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDOM(KLON,KLEV)
TYPE(TYP_DDH) , INTENT(INOUT) :: YDDDH
END SUBROUTINE ACMTUD
END INTERFACE
