INTERFACE
SUBROUTINE ACNEBR ( YDERAD,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIAT,KTDIAN,KLEV,&
 & PAPHI,PAPHIF,PAPRS,PAPRSF,PLSCPE,PQ,&
 & PQSAT,PR,PT,PU,PV,PRDELP,PDELP,&
 & PGZ0,PFPLCH,PPBLH,PQS,PTS,&
 & PKTROV,PKUROV,PNBVNO,PNEB,PNEBS,PQICE,PQLI,&
 & PQLIS) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOERAD , ONLY : TERAD
TYPE(TERAD) ,INTENT(IN) :: YDERAD
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIAT
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIAN
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCPE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPBLH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKTROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKUROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNBVNO(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEB(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNEBS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQLI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQLIS(KLON,KLEV)
END SUBROUTINE ACNEBR
END INTERFACE
