INTERFACE
SUBROUTINE ACNTCLSTL ( KIDIA,KFDIA,KLON,KLEV,&
 & PAPRS5,PAPRSF5,PCP5,PQ5,PT5,PU5,PV5,&
 & PCD5,PCDN5,PCDNH5,PCH5,PCPS5,PDPHI5,PQS5,PTS5,&
 & PAPRS,PAPRSF,PCP,PQ,PT,PU,PV,&
 & PCD,PCDN,PCDNH,PCH,PCPS,PDPHI,PDPHIT,PDPHIV,&
 & PQS,PSTAB,PTS,&
 & LDZ0H,&
 & PQCLS,PRHCLS,PTCLS,PUCLS,PVCLS,PUCLN,PVCLN,PZPCLS,&
 & PQCLS5,PRHCLS5,PTCLS5,PUCLS5,PVCLS5,PZPCLS5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCD5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCDN5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCDNH5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCH5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHI5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCDN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCDNH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTAB(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
LOGICAL ,INTENT(IN) :: LDZ0H
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRHCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZPCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRHCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZPCLS5(KLON)
END SUBROUTINE ACNTCLSTL
END INTERFACE
