INTERFACE
SUBROUTINE ACNTCLSAD ( KIDIA,KFDIA,KLON,KLEV,&
 & PAPRS5,PAPRSF5,PCP5,PQ5,PT5,PU5,PV5,&
 & PCD5,PCDN5,PCDNH5,PCH5,PCPS5,PDPHI5,PQS5,PTS5,&
 & PAPRS,PAPRSF,PCP,PQ,PT,PU,PV,&
 & PCD,PCDN,PCDNH,PCH,PCPS,PDPHI,PDPHIT,PDPHIV,&
 & PQS,PSTAB,PTS,&
 & LDZ0H,&
 & PQCLS,PRHCLS,PTCLS,PUCLS,PVCLS,PUCLN,PVCLN,PZPCLS) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCD5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCDN5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCDNH5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCH5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHI5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDNH(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCH(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDPHI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPHIV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTAB(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS(KLON)
LOGICAL ,INTENT(IN) :: LDZ0H
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRHCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCLS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUCLN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCLN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZPCLS(KLON)
END SUBROUTINE ACNTCLSAD
END INTERFACE
