INTERFACE
SUBROUTINE ACPTKE(YGFL,YDLDDH,YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KSTEP,&
 & PAPHI,PAPHIF,PDELP,PRDELP,PKNROV,&
 & PT,PU,PV,PALPH,&
 & PAPRS,PAPRSF,PR,PTKE,PLMU,PLNPR,PF_EPS,PFUN_TTE,&
 & PMRIPP,PMRIFPP,PRHS,&
 & PMN2_ES,PMN2_EQ,PRRCOR,PDIFTQ,PDIFTS,PSHEAR,&
 & PCD,PGZ0,&
 & PKUROV,PKTROV,PXPTKEROV,&
 & PLMLTILD,PMXL,PLML,&
 & PTH_FUN,PWW_FUN,&
 & PTENDPTKE,PTTE,PFTCNS) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMLDDH , ONLY : TLDDH
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
TYPE(TLDDH) ,INTENT(IN) :: YDLDDH
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKNROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTKE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLMU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PF_EPS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFUN_TTE(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMRIFPP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMRIPP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMN2_ES (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMN2_EQ (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKUROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKTROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWW_FUN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTH_FUN (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRRCOR (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXPTKEROV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDPTKE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLMLTILD(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLML(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMXL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSHEAR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFTCNS(KLON,0:KLEV,6)
END SUBROUTINE ACPTKE
END INTERFACE
