INTERFACE
SUBROUTINE ACRANEB_TRANS(YDPHY,YDPHY3,KIDIA,KFDIA,KLON,KTDIA,KLEV,KJN,&
 & KIIDIA,KIFDIA,KAUCR,KCALC,&
 & PAPRS,PAPRSF,PDELP,PR,PT,PTS,PQ,PQCO2,PQO3,&
 & PDM0I,&
 & PDEOSA,PDEOSI,PDEOTI,PDEOTI2,PUEOSI,PUEOTI,PUEOTI2,&
 & PEOLT,PEOXT,PPNER0,PPNER1,PRPROX,PRSURF) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY ,ONLY : TPHY
USE YOMPHY3 ,ONLY : TPHY3
TYPE(TPHY) ,INTENT(INOUT):: YDPHY
TYPE(TPHY3) ,INTENT(INOUT):: YDPHY3
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KJN
INTEGER(KIND=JPIM),INTENT(IN) :: KIIDIA(KJN)
INTEGER(KIND=JPIM),INTENT(IN) :: KIFDIA(KJN)
INTEGER(KIND=JPIM),INTENT(IN) :: KAUCR
INTEGER(KIND=JPIM),INTENT(IN) :: KCALC
REAL(KIND=JPRB),INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQCO2(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQO3(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PDM0I(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PDEOSA(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PDEOSI(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PDEOTI(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PDEOTI2(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PUEOSI(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PUEOTI(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PUEOTI2(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PEOLT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PEOXT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PPNER0(KLON,KLEV,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PPNER1(KLON,KLEV,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PRPROX(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PRSURF(KLON)
END SUBROUTINE ACRANEB_TRANS
END INTERFACE
