INTERFACE
SUBROUTINE ACRANEB_SOLVS(YDPHY,LDNUMX,&
 & KLON,KTDIA,KLEV,KJN,KIIDIA,KIFDIA,KAUCR,&
 & PALB,PALBDIR,PCLCT,PFRSOPT,PFRSOPS_C,PFRSOPS_CUN,&
 & PNEB,PB1,PB2,PB3,PB4,&
 & PA1C,PA1CUN,PA2C,PA3C,PA4C,PA5C,PA1N,PA1NUN,PA2N,PA3N,PA4N,PA5N,&
 & PFRSO,&
 & PFRSODS,PFRSOPS,PFRSOPS_UN,PFRSOPS_TRUE) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY ,ONLY : TPHY
TYPE(TPHY) ,INTENT(IN) :: YDPHY
LOGICAL ,INTENT(IN) :: LDNUMX
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KJN
INTEGER(KIND=JPIM),INTENT(IN) :: KIIDIA(KJN)
INTEGER(KIND=JPIM),INTENT(IN) :: KIFDIA(KJN)
INTEGER(KIND=JPIM),INTENT(IN) :: KAUCR
REAL(KIND=JPRB),INTENT(IN) :: PALB(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PALBDIR(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PCLCT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRSOPT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRSOPS_C(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRSOPS_CUN(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PNEB(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PB1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PB2(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PB3(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PB4(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA1C(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA1CUN(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA2C(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA3C(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA4C(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA5C(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA1N(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA1NUN(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA2N(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA3N(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA4N(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA5N(KLON,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PFRSO(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PFRSODS(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PFRSOPS(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PFRSOPS_UN(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PFRSOPS_TRUE(KLON)
END SUBROUTINE ACRANEB_SOLVS
END INTERFACE
