INTERFACE
SUBROUTINE ACRI2PR(YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,KTTYPE,&
 & PMRIPP,&
 & P_ETKE_P,P_ETKE_R) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTTYPE
REAL(KIND=JPRB) ,INTENT(IN) :: PMRIPP (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ETKE_P(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ETKE_R(KLON,0:KLEV)
END SUBROUTINE ACRI2PR
END INTERFACE
