INTERFACE
SUBROUTINE ACTKEZOTLS ( YDPHY0,KIDIA,KFDIA,KLON,KLEV,&
 & PAPHI,PAPHIF,PR,PT,&
 & PGZ0,PGZ0H,&
 & PTS,PQS,&
 & PCDN,PCDNH,PCPS,PRTI,PRS) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY0 , ONLY : TPHY0
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCDN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDNH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRTI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRS(KLON)
END SUBROUTINE ACTKEZOTLS
END INTERFACE
