INTERFACE
SUBROUTINE ACTRGRC( YDECUMF,YDPHY0,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PAPHI,PAPHIF,PAPRS,PAPRSF,PCP,PDELP,&
 & PQ,PQC,PQSAT,PQW, PT,PTVE, PTW,&
 & PIFHCS,&
 & PIB,&
 & KNASC, PQU, PSU, PTU, PTVU,&
 & KNND,KNNS, KUSLT, KLFCT, PPLCL, PQUSL, PTLCL, PTUSL) 
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMPHY0 , ONLY : TPHY0
USE YOECUMF , ONLY : TECUMF
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTVE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIFHCS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIB(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPLCL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQUSL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTUSL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTLCL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTVU(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KNASC(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNND(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNNS(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KUSLT(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLFCT(KLON)
 END SUBROUTINE ACTRGRC
END INTERFACE
