INTERFACE
SUBROUTINE ACUPD( YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PAPRSF,PCP, PLHS, PLHV, PR,&
 & PIPOI, PPOID, PFALLR, PFALLS,PFALLG,&
 & PFPEVPSL,PFPEVPSN,PFPEVPSG,PFPEVPCL,PFPEVPCN,PFPEVPCG,PFHP,&
 & PDIFCSD,PDIFCQD,PDIFCQLD,PDIFCQID,&
 & PZQV,PZQL,PZQI,PZQR,PZQS,PZQG,PZT,PENTCH,&
 & PFCQVNG,PFCQING,PFCQLNG,PFCQRNG,PFCQSNG,PFCQGNG,&
 & PFPLSL, PFPLSN, PFPLSG) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 , ONLY: JPIM, JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN) :: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIPOI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPOID(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFALLR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFALLS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFALLG(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPEVPSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPEVPSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPEVPSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPEVPCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPEVPCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPEVPCG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFHP(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCSD(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQD(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQLD(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQID(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQG(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PENTCH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQVNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQING(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQLNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQRNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQSNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQGNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLSG(KLON,0:KLEV)
END SUBROUTINE ACUPD
END INTERFACE
