INTERFACE
SUBROUTINE ACUPU( YDPHY,YDPHY0,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PUDAL,PUNEBH,PDETFI,&
 & PDPOID,PIPOI,PLHV,PLHS,PCP,&
 & PDIFCQ,PDIFCQI,PDIFCQL,PDIFCS,&
 & PFCCQL,PFCCQN,PFCSQL,PFCSQN,&
 & PSIGP, PSIGPC,&
 & PNEBE,PZQI,PZQL,PZQV,PZT,&
 & PFCQVNG,PFCQING,PFCQLNG) 
USE PARKIND1 , ONLY: JPIM, JPRB
USE YOMPHY , ONLY : TPHY
USE YOMPHY0 , ONLY : TPHY0
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PUDAL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPOID(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIPOI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSIGP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSIGPC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUNEBH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDETFI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEBE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZQV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQING(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQLNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQVNG(KLON,0:KLEV)
END SUBROUTINE ACUPU
END INTERFACE
