INTERFACE
SUBROUTINE ADD_MODERR_AD(YDGEOMETRY,YDFIELDS,YDSPERR,YDGPERR,KSTEP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE PARKIND1 , ONLY : JPIM, JPRB
USE GRIDPOINT_FIELDS_MIX, ONLY : ASSIGNMENT(=), GRIDPOINT_FIELD
USE SPECTRAL_FIELDS_MOD , ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSPERR(:)
TYPE(GRIDPOINT_FIELD),INTENT(INOUT) :: YDGPERR(:)
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTEP
END SUBROUTINE ADD_MODERR_AD
END INTERFACE
