INTERFACE
SUBROUTINE ADDBGS(YDGEOMETRY,YDFIELDS,YDGMV5,YDTCV,YDML_GCONF,YD_JB_STRUCT,YD_BG_SPEC,YD_BG_GFL,YDTCV_BGC,YDACV)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE FIELDS_MOD , ONLY : FIELDS
USE YOMGFL , ONLY : TGFL
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE TOVSCV_BGC_MOD , ONLY : TOVSCV_BGC
USE TOVSCV_MOD , ONLY : TOVSCV
USE TYPE_ACV , ONLY : ACV_CONTAINER
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(TGMV), INTENT(INOUT) :: YDGMV5
TYPE(TOVSCV), INTENT(INOUT) :: YDTCV
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
TYPE(SPECTRAL_FIELD), INTENT(IN) :: YD_BG_SPEC
TYPE(TGFL) , INTENT(IN) :: YD_BG_GFL
TYPE(TOVSCV_BGC) , INTENT(IN) :: YDTCV_BGC
TYPE(ACV_CONTAINER), INTENT(INOUT) :: YDACV
END SUBROUTINE ADDBGS
END INTERFACE
