INTERFACE
SUBROUTINE ADDFGS(YDGEOMETRY,YDGMV,YDGMV5,YDDIMF,YDSP,YDTCV,YDTCV5)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE YOMDIMF , ONLY : TDIMF
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE TOVSCV_MOD , ONLY : TOVSCV
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
TYPE(TGMV) , INTENT(INOUT) :: YDGMV5
TYPE(TDIMF) , INTENT(IN) :: YDDIMF
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
TYPE(TOVSCV), INTENT(INOUT) :: YDTCV
TYPE(TOVSCV), INTENT(IN) :: YDTCV5
END SUBROUTINE ADDFGS
END INTERFACE
