INTERFACE
SUBROUTINE ADDOER(ROBHDR,ROBODY,SATBODY,&
 & KOBS,KBODY,PTFG,PMPS) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KOBS
INTEGER(KIND=JPIM),INTENT(IN) :: KBODY
REAL(KIND=JPRB), INTENT(IN) :: PMPS, PTFG
END SUBROUTINE ADDOER
END INTERFACE
