INTERFACE
SUBROUTINE ADDPGR(CDRECNM,KBLOCK,PDATA,KLEN)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
CHARACTER ,INTENT(IN) :: CDRECNM*(*)
INTEGER(KIND=JPIM),INTENT(IN) :: KBLOCK
REAL(KIND=JPRB) ,INTENT(IN) :: PDATA(KLEN)
END SUBROUTINE ADDPGR
END INTERFACE
