INTERFACE
SUBROUTINE ADVPRCSAD (YDML_PHY_MF,KIDIA, KFDIA, KLON, KTDIA, KFLEV,&
 & PT5, PQ5, PQL5, PQI5,PQR5,PQS5, PAUTOL5, PAUTOI5, PNEB5,PDELP5,PAPHI5,PAPRSF5,PR5,&
 & PT, PQ, PQL, PQI, PAUTOL, PAUTOI, PNEB,PDELP,PAPHI,PAPRSF,PR,&
 & PFPLSL5,PFPLSN5,PFPEVPL5,PFPEVPN5,&
 & PFPLSL,PFPLSN,PFPEVPL,PFPEVPN) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PT5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQR5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQI5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAUTOL5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAUTOI5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEB5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5 (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP5 (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSL5 (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSN5 (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPL5 (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPN5(KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQL (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQI (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAUTOL (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAUTOI (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNEB (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHI (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRSF (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDELP (KLON,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLSL (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLSN (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPEVPL (KLON,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPEVPN(KLON,0:KFLEV)
END SUBROUTINE ADVPRCSAD
END INTERFACE
