INTERFACE
SUBROUTINE AER_CLCLD (&
 & YDMODEL,KIDIA, KFDIA, KLON, KLEV,&
 & PTSPHY,&
 & PT, PQ, PQSAT,&
 & PAPH, PAP,&
 & PGELAM, PGEMU, PCLON, PSLON,&
 & PL, PI, PA,&
 & PLCRIT_AER,&
 & PICRIT_AER,&
 & PRE_LIQ,&
 & PRE_ICE,&
 & PCCN,&
 & PNICE ) 
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLON(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLON(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLCRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PICRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRE_LIQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRE_ICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCCN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNICE(KLON,KLEV)
END SUBROUTINE AER_CLCLD
END INTERFACE
