INTERFACE
SUBROUTINE AER_SO2SO4_V2&
 & ( YDRIP, KIDIA , KFDIA , KLON , KLEV ,&
 & PTSPHY, PTP , PRSF1 , PNEB , PQLI , PGELAT, PGELAM,&
 & PSO2 , PITSO2, POH, PO3, PH2O2 ,&
 & PTSO2 , PTSO4, PFSO2, PFSO4, PDP ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRIP , ONLY : TRIP
USE YOMCST ,ONLY :&
 & RNAVO,&
 & R,&
 & RD,RG 
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PTP (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEB (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLI (KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSO2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PITSO2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PH2O2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PO3(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSO2(KLON,KLEV), PTSO4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSO2(KLON), PFSO4(KLON)
END SUBROUTINE AER_SO2SO4_V2
END INTERFACE
