INTERFACE
SUBROUTINE AER_STRCOMP&
 & ( KLAT, KLEV,&
 & PH2O , PT , PPMB,&
 & PR2SO4&
 & ) 
USE PARKIND1 ,ONLY : JPRB , JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB),INTENT(IN) :: PPMB(KLAT,KLEV), PH2O(KLAT,KLEV), PT(KLAT,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PR2SO4(KLAT,KLEV)
END SUBROUTINE AER_STRCOMP
END INTERFACE
