INTERFACE
SUBROUTINE AER_STRCLOG&
 & ( KLAT , KLEV ,&
 & PH2SO4, PR2SO4, PDENSO4, PRSTDEV, PRMODRA, PT, PRNLOG ) 
USE PARKIND1 ,ONLY : JPRB , JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT,KLEV
REAL(KIND=JPRB),INTENT(IN) :: PH2SO4(KLAT,KLEV) , PR2SO4(KLAT,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRSTDEV(KLAT,KLEV), PRMODRA(KLAT,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PDENSO4(KLAT,KLEV), PT(KLAT,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PRNLOG (KLAT,KLEV)
END SUBROUTINE AER_STRCLOG
END INTERFACE
