INTERFACE
SUBROUTINE AER_SSALT_GRYTHE&
 & ( YDEAERATM,YDEAERSNK,KIDIA, KFDIA, KLON,&
 & PCI , PLSM , PCLK , PWIND, PSST, PRH,&
 & PFLXSS) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOEAERSNK ,ONLY : TEAERSNK
USE YOEAERATM, ONLY : TEAERATM
TYPE(TEAERATM) ,INTENT(INOUT) :: YDEAERATM
TYPE(TEAERSNK) ,INTENT(INOUT) :: YDEAERSNK
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLON), PLSM(KLON), PCLK(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWIND(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSST(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRH(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLXSS(KLON,3)
END SUBROUTINE AER_SSALT_GRYTHE
END INTERFACE
