INTERFACE
SUBROUTINE AER_SEASALT&
 & ( PWIND, PSST,PFLXSS, PLSM, PCI) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PWIND
REAL(KIND=JPRB) ,INTENT(IN) :: PSST
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM,PCI
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLXSS(3)
END SUBROUTINE AER_SEASALT
END INTERFACE
