INTERFACE
SUBROUTINE AER_RAD&
 & ( YDEAERATM,YDML_PHY_AER,YDCOMPO,YGFL,KIDIA , KFDIA , KLON , KTDIA, KLEV , KACTAERO, KNWAVL, KTWAVL, KSTART, KSTEP,&
 & PAP , PAPH , PQ , PT , PAERO,&
 & PTAUAER, POMGAER, PASYAER&
 & ) 
USE MODEL_PHYSICS_AEROSOL_MOD , ONLY : MODEL_PHYSICS_AEROSOL_TYPE
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEAERATM, ONLY : TEAERATM
USE YOMCOMPO , ONLY : TCOMPO
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TEAERATM) ,INTENT(INOUT):: YDEAERATM
TYPE(MODEL_PHYSICS_AEROSOL_TYPE), INTENT(INOUT) :: YDML_PHY_AER
TYPE(TCOMPO) ,INTENT(INOUT):: YDCOMPO
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KACTAERO
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART, KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KNWAVL, KTWAVL(19)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV), PAPH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV) , PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERO(KLON,KLEV,YGFL%NAERO)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTAUAER(KLON,8,KLEV), POMGAER(KLON,8,KLEV), PASYAER(KLON,8,KLEV)
END SUBROUTINE AER_RAD
END INTERFACE
