INTERFACE
SUBROUTINE AER_SSALT&
 & ( YDEAERATM,YDEAERSRC,KIDIA, KFDIA, KLON, KBINSS,&
 & PCI , PLSM , PCLK, PWIND,&
 & PFLXSS&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOEAERATM, ONLY : TEAERATM
USE YOEAERSRC ,ONLY : TEAERSRC
TYPE(TEAERATM) ,INTENT(INOUT) :: YDEAERATM
TYPE(TEAERSRC) ,INTENT(INOUT) :: YDEAERSRC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KBINSS
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLON), PLSM(KLON), PCLK(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWIND(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLXSS(KLON,KBINSS)
END SUBROUTINE AER_SSALT
END INTERFACE
