INTERFACE
SUBROUTINE AER_LOSS&
 & ( YDEAERSNK,KIDIA, KFDIA, KLON, KLEV, KAERO,&
 & PAERO, PTSPHY,&
 & PTAERO&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOEAERSNK ,ONLY : TEAERSNK
TYPE(TEAERSNK) ,INTENT(INOUT):: YDEAERSNK
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO
REAL(KIND=JPRB),INTENT(IN) :: PAERO(KLON,KLEV,KAERO)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(INOUT) :: PTAERO(KLON,KLEV,KAERO)
END SUBROUTINE AER_LOSS
END INTERFACE
