INTERFACE
SUBROUTINE AER_PHY2&
 & ( YDGEOMETRY, YDMODEL,KIDIA, KFDIA, KLON , KTDIA , KLEV , KFLDX, KLEVX, KTILES, KSTGLO,&
 & KTRAC, KAERO, KSW,&
 & PRS1 , PRSF1, PAPHI, PTP , PVERVEL, PCEN , PGEOH,&
 & PALB , PALBD, PALUVD,&
 & PAERDEP,PAERLTS,PAERSCC , PAERWS,PAERGUST, PAERUST,&
 & PBCBF, PBCFF, PBCGF, POMBF , POMFF , POMGF ,PURBF, PRSURF, PSSURF,&
 & PSO2L, PSO2H, PSO2DD, PSOGF, PVOLC , PVOLE , PSOA, PSOACO, PDSF, PVOLCALTI, PDMS,&
 & PCI ,PINJF, PBLH, PFRTI, PLSM, PCLK, PQP, PSST, PSNS ,&
 & PTL ,PGELAM,PGELAT,PGEMU , PHSDFOR,&
 & PUP , PVP , PWSA1, PTSPHY, PZ0M, KCHEM,&
 & KTVL, KTVH, PCVL, PCVH, PLAIL, PLAIH,&
 & PCFLX, PTENC, PDDVLC,&
 & PDMSO, PLDAY, PLISS, PSO2 , PTDMS, PAERDDP, PAERSDM, PAERSRC, PAERMAP, PAERFLX, PAERLIF,&
 & PDMSI, PODMS, PEXTRA ) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL), INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KFLDX, KLEVX
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA, KLEV ,KSTGLO
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO(YDMODEL%YRML_GCONF%YGFL%NAERO)
REAL(KIND=JPRB), INTENT(IN) :: PRS1(KLON,0:KLEV), PRSF1(KLON,KLEV), PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTP(KLON,KLEV) , PVERVEL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB), INTENT(IN) :: PALB(KLON) , PALBD(KLON,KSW)
REAL(KIND=JPRB), INTENT(IN) :: PALUVD(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PAERDEP(KLON), PAERLTS(KLON), PAERSCC(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PAERWS(KLON) , PAERGUST(KLON), PAERUST(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PBCBF(KLON), PBCFF(KLON), PBCGF(KLON), POMBF(KLON), POMFF(KLON), POMGF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PURBF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PRSURF(KLON), PSSURF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PSO2L(KLON), PSO2H(KLON), PSO2DD(KLON), PSOGF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PVOLC(KLON), PVOLE(KLON), PSOA(KLON), PSOACO(KLON), PDSF(KLON),PVOLCALTI(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PDMS(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PCI(KLON) , PFRTI(KLON,KTILES), PLSM(KLON), PCLK(KLON), PSNS(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PINJF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PBLH(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PSST(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PGELAM(KLON), PGELAT(KLON), PGEMU(KLON), PHSDFOR(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PTL(KLON) , PQP(KLON,KLEV), PUP(KLON) , PVP(KLON) , PWSA1(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PTSPHY
REAL(KIND=JPRB), INTENT(IN) :: PZ0M(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCHEM(YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(IN) :: PCVL(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PCVH(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PLAIL(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PLAIH(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTVL(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTVH(KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB), INTENT(OUT) :: PCFLX(KLON,KTRAC)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDVLC(KLON,KTRAC)
REAL(KIND=JPRB), INTENT(OUT) :: PAERDDP(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB), INTENT(OUT) :: PAERSDM(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB), INTENT(OUT) :: PAERSRC(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB), INTENT(OUT) :: PAERMAP(KLON,5)
REAL(KIND=JPRB), INTENT(OUT) :: PAERFLX(KLON,YDMODEL%YRML_PHY_RAD%YREAERATM%NTYPAER(2))
REAL(KIND=JPRB), INTENT(OUT) :: PAERLIF(KLON,YDMODEL%YRML_PHY_RAD%YREAERATM%NTYPAER(2))
REAL(KIND=JPRB), INTENT(OUT) :: PDMSO(KLON), PLDAY(KLON), PLISS(KLON), PSO2(KLON), PTDMS(KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PDMSI(KLON), PODMS(KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PEXTRA(KLON,KLEVX,KFLDX)
END SUBROUTINE AER_PHY2
END INTERFACE
