INTERFACE
SUBROUTINE AER_LIDSIMOP&
 & ( KDLEN, KLEN , KLEV , KDFS,&
 & PLIDPRES ,&
 & PCO2 , PNO2, PGEOP, PTQO, PAELIDPROF, YDGP5,&
 & PLISIS, PLISIT, PULISIS,PULISIT,PEXTT, PEXTS&
 & ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEAERLID , ONLY : YREAERLID
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KDFS
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(IN) :: PLIDPRES(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO2(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNO2(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOP(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTQO(KDLEN,KLEV,KDFS)
REAL(KIND=JPRB) ,INTENT(IN) :: PAELIDPROF(KDLEN,KLEV,YDGP5%NGEMS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLISIS(KDLEN,YREAERLID%NWLID,0:KLEV), PLISIT(KDLEN,YREAERLID%NWLID,0:KLEV),&
 & PULISIS(KDLEN,YREAERLID%NWLID,0:KLEV), PULISIT(KDLEN,YREAERLID%NWLID,0:KLEV),&
 & PEXTS(KDLEN,YREAERLID%NWLID,0:KLEV), PEXTT(KDLEN,YREAERLID%NWLID,0:KLEV) 
END SUBROUTINE AER_LIDSIMOP
END INTERFACE
