INTERFACE
SUBROUTINE AER_LIDSIMTL&
 & ( KDLEN, KLEN , KLEV , KDFS, LDPHYLIN,&
 & PLIDPRES ,&
 & PCO25 , PNO25, PGEOP5, PTQO5 ,PAELIDPROF5,&
 & PCO2 , PNO2 , PGEOP , PTQO ,PAELIDPROF,&
 & YDGP5,&
 & PLISIS, PLISIT, PULISIS,PULISIT,PEXTT, PEXTS&
 & ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEAERLID , ONLY : YREAERLID
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KDFS
LOGICAL ,INTENT(IN) :: LDPHYLIN
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(IN) :: PLIDPRES(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO25(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO2(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNO25(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNO2(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOP5(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOP(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTQO5(KDLEN ,KLEV,KDFS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTQO(KDLEN ,KLEV,KDFS)
REAL(KIND=JPRB) ,INTENT(IN) :: PAELIDPROF5(KDLEN,KLEV,YDGP5%NGEMS)
REAL(KIND=JPRB) ,INTENT(IN) :: PAELIDPROF(KDLEN,KLEV,YDGP5%NGEMS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLISIS(KDLEN,YREAERLID%NWLID,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLISIT(KDLEN,YREAERLID%NWLID,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PULISIS(KDLEN,YREAERLID%NWLID,0:KLEV), PULISIT(KDLEN,YREAERLID%NWLID,0:KLEV),&
 & PEXTS(KDLEN,YREAERLID%NWLID,0:KLEV), PEXTT(KDLEN,YREAERLID%NWLID,0:KLEV) 
END SUBROUTINE AER_LIDSIMTL
END INTERFACE
