INTERFACE
SUBROUTINE AER_STRAACT&
 & ( KLAT, KLEV,&
 & PR2SO4,&
 & PACTSO4&
 & ) 
USE PARKIND1 ,ONLY : JPRB , JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PR2SO4(KLAT,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PACTSO4(KLAT,KLEV)
END SUBROUTINE AER_STRAACT
END INTERFACE
