INTERFACE
SUBROUTINE AER_STRRLOG&
 & ( KLAT , KLEV ,&
 & PACTSO4, PH2SO4, PT , PCONCM,&
 & PCONHS4, PRNLOG ) 
USE PARKIND1 ,ONLY : JPRB , JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT,KLEV
REAL(KIND=JPRB),INTENT(IN) :: PACTSO4(KLAT,KLEV), PH2SO4 (KLAT,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PT (KLAT,KLEV), PCONCM (KLAT,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PCONHS4 (KLAT,KLEV)
REAL(KIND=JPRB),INTENT(INOUT) :: PRNLOG (KLAT,KLEV)
END SUBROUTINE AER_STRRLOG
END INTERFACE
