INTERFACE
SUBROUTINE AER_PHY3&
 & ( YDMODEL,KIDIA , KFDIA , KLON , KTDIA , KLEV , KTILES ,&
 & KFLDX, KLEVX, KTRAC , KAERO , KCHEM,&
 & PRS1 , PRSF1 , PAEROP , PCAERO , PCEN , PAPHIF ,&
 & PFPLCL , PFPLCN , PFPLSL , PFPLSN , PGELAT, PGELAM,&
 & PAP , PIP , PLP , PRP , PSP , PCOVPTOT, PLU ,&
 & PFCCQL, PFCCQN, PFCSQL, PFCSQN,&
 & PO3P ,PQP , PTP , PTHP , PTENC , PCFLX ,&
 & PAERDDP, PAERSDM, PAERSRC, PAERWS , PAERGUST , PAERUST, PAERMAP,&
 & PCLAERS, PPRAERS, PCHEM2AER,&
 & PALBD , PTAUAER, PFRTI , PLSM , PSNS , PWND , PWS1 , PAERFLX, PAERLIF,&
 & PAERODDF, PFRAC_CA1, PFRAC_CA2, PTSPHY , PGFL ,&
 & PODSS , PODDU , PODOM , PODBC, PODSU , PODNI, PODAM, PODSOA, PODVFA , PODVSU ,&
 & PODTOACC , PAEPM1 , PAEPM25, PAEPM10, PAERAOT, PAERLISI,&
 & PEXTRA, PAERO_WVL_DIAG ) 
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOE_AERODIAG , ONLY : NPAERODIAG, NPAERAOT, NPAERLISI_VAR, NPAERLISI_WVL,&
 & JPAERODIAG_SRC, JPAERODIAG_DDP, JPAERODIAG_SDM, JPAERODIAG_WDL,&
 & JPAERODIAG_WDC, JPAERODIAG_NGT, JPAERODIAG_OD,&
 & JPAERLISI_EXT, JPAERLISI_BSTOA, JPAERLISI_BSGND,&
 & JPAERLISI_MOLBSC, JPAERLISI_AERBSC,&
 & JPAERLISI_355, JPAERLISI_532, JPAERLISI_1064,&
 & JPAERO_WVL_AOD, JPAERO_WVL_AODABS, JPAERO_WVL_AODFM,&
 & JPAERO_WVL_SSA, JPAERO_WVL_ASSIMETRY 
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA, KLEV, KFLDX, KLEVX
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO(YDMODEL%YRML_GCONF%YGFL%NAERO)
INTEGER(KIND=JPIM),INTENT(IN) :: KCHEM(YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV), PRS1(KLON,0:KLEV), PAPHIF(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAP(KLON,KLEV) , PIP(KLON,KLEV) , PLP(KLON,KLEV) , PLU(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFCCQL(KLON,KLEV),PFCCQN(KLON,KLEV),PFCSQL(KLON,KLEV), PFCSQN(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRP(KLON,KLEV) , PSP(KLON,KLEV), PCOVPTOT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAEROP(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NAERO)
REAL(KIND=JPRB),INTENT(IN) :: PCAERO(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB),INTENT(IN) :: PCEN(KLON,KLEV,KTRAC), PCFLX(KLON,KTRAC)
REAL(KIND=JPRB),INTENT(IN) :: PO3P(KLON,KLEV), PQP(KLON,KLEV), PTP(KLON,KLEV), PTHP(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFPLCL(KLON,0:KLEV),PFPLCN(KLON,0:KLEV),PFPLSL(KLON,0:KLEV),PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON) , PGELAM(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PALBD(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW), PFRTI(KLON,KTILES)
REAL(KIND=JPRB),INTENT(IN) :: PAERDDP(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO), PAERSDM(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB),INTENT(IN) :: PAERWS(KLON), PAERGUST(KLON), PAERUST(KLON), PAERMAP(KLON,5)
REAL(KIND=JPRB),INTENT(IN) :: PAERSRC(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB),INTENT(IN) :: PCHEM2AER(KLON,KLEV,4)
REAL(KIND=JPRB),INTENT(IN) :: PAERFLX(KLON,YDMODEL%YRML_PHY_RAD%YREAERATM%NTYPAER(2))
REAL(KIND=JPRB),INTENT(IN) :: PAERLIF(KLON,YDMODEL%YRML_PHY_RAD%YREAERATM%NTYPAER(2))
REAL(KIND=JPRB),INTENT(IN) :: PCLAERS(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PLSM(KLON) , PSNS(KLON) , PWND(KLON) , PWS1(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRAC_CA1(KLON),PFRAC_CA2(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB),INTENT(OUT) :: PODSS(KLON), PODDU(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PODOM(KLON), PODBC(KLON), PODSU(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PODNI(KLON), PODAM(KLON), PODSOA(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PODVFA(KLON),PODVSU(KLON)
REAL(KIND=JPRB),INTENT(INOUT) :: PODTOACC(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PAEPM1(KLON),PAEPM25(KLON),PAEPM10(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PAERODDF(KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO,NPAERODIAG)
REAL(KIND=JPRB),INTENT(OUT) :: PTAUAER(KLON,KLEV,7)
REAL(KIND=JPRB),INTENT(INOUT) :: PEXTRA(KLON,KLEVX,KFLDX)
REAL(KIND=JPRB),INTENT(INOUT) :: PGFL(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM), PPRAERS(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PAERAOT(KLON,KLEV,NPAERAOT)
REAL(KIND=JPRB),INTENT(OUT) :: PAERLISI(KLON,KLEV,NPAERLISI_WVL,NPAERLISI_VAR)
REAL(KIND=JPRB),INTENT(OUT) :: PAERO_WVL_DIAG(KLON,YDMODEL%YRML_GCONF%YGFL%NAERO_WVL_DIAG,&
 & YDMODEL%YRML_GCONF%YGFL%NAERO_WVL_DIAG_TYPES) 
END SUBROUTINE AER_PHY3
END INTERFACE
