INTERFACE
SUBROUTINE AER_STRFIND&
 & ( KN, KM, PX, PY, PXC, PYC, PF, PVAL ) 
USE PARKIND1 ,ONLY : JPRB , JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KN, KM
REAL(KIND=JPRB),INTENT(IN) :: PX, PY, PXC(KN), PYC(KM), PF(KN,KM)
REAL(KIND=JPRB),INTENT(OUT) :: PVAL
END SUBROUTINE AER_STRFIND
END INTERFACE
