INTERFACE
SUBROUTINE AER_SRC&
 & ( YDGEOMETRY, YDMODEL,KIDIA, KFDIA, KLON , KTDIA, KLEV, KTILES, KSTART, KSTEP ,KSTGLO,&
 & KSW , KTRAC, KAERO,&
 & PALB , PALBD ,PALUVD, PAPHI ,&
 & PAERDEP, PAERLTS, PAERSCC, PAERGUST, PALTH ,&
 & PBCBF, PBCFF, PBCGF, POMBF, POMFF, POMGF,&
 & PSO2L, PSO2H, PSOGF, PSOA ,&
 & PSOACO, PDSF, PVOLC, PVOLE, PDMS, PVOLCALTI,&
 & PAPH , PAP , PCI , PINJF, PBLH, PDELP, PGELAM, PGELAT, PGEMU , PFRTI , PHSDFOR,&
 & PLSM , PCLK , PQ , PRHO , PSNS , PT , PTS , PTSPHY, PZ0M, KCHEM,&
 & PWIND, PWS1 , PSST,&
 & PDMSO, PLDAY, PLISS, PSO2 , PTDMS, PAERFLX, PAERLIF, PAERMAP , PCFLX , PCEN , PTENC,&
 & PODMS) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON, KIDIA, KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV, KTDIA, KSTGLO
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP, KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO(YDMODEL%YRML_GCONF%YGFL%NAERO)
REAL(KIND=JPRB) ,INTENT(IN) :: PALB(KLON), PALBD(KLON,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV), PALTH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERDEP(KLON), PAERLTS(KLON), PAERSCC(KLON), PALUVD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PBCBF(KLON), PBCFF(KLON), PBCGF(KLON), POMBF(KLON), POMFF(KLON), POMGF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PAERGUST(KLON), PHSDFOR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSO2L(KLON), PSO2H(KLON), PSOGF(KLON),PSOA(KLON), PSOACO (KLON), PVOLC(KLON), PVOLE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDMS(KLON),PVOLCALTI(KLON), PDSF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV), PAPH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON), PGELAT(KLON), PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLON), PLSM(KLON), PCLK(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PINJF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PBLH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV), PRHO(KLON,KLEV), PSNS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWIND(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS1(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSST(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PZ0M(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCHEM(YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAERMAP(KLON,5)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAERFLX(KLON,YDMODEL%YRML_PHY_RAD%YREAERATM%NTYPAER(2))
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAERLIF(KLON,YDMODEL%YRML_PHY_RAD%YREAERATM%NTYPAER(2))
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFLX(KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMSO(KLON), PLDAY(KLON), PLISS(KLON), PSO2(KLON), PTDMS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PODMS(KLON)
END SUBROUTINE AER_SRC
END INTERFACE
