INTERFACE
SUBROUTINE AER_CLOUD_LAYER(&
 & YDMODEL,KDIM, PAUX, STATE, PDIAG, GEMSL,&
 & AUXL) 
USE TYPE_MODEL , ONLY : MODEL
USE YOMPHYDER, ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE, GEMS_LOCAL_TYPE 
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (AUX_DIAG_TYPE) , INTENT (IN) :: PDIAG
TYPE (GEMS_LOCAL_TYPE) , INTENT (IN) :: GEMSL
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
END SUBROUTINE AER_CLOUD_LAYER
END INTERFACE
