INTERFACE
SUBROUTINE AER_GLOMAPDIAG_LAYER(KDIM, PTSPHY, PAUX, STATE, PDIAG,GEMSL)
USE PARKIND1 ,ONLY : JPIM, JPRB
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & AUX_DIAG_TYPE,&
 & GEMS_LOCAL_TYPE 
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (AUX_DIAG_TYPE) , INTENT (IN) :: PDIAG
TYPE (GEMS_LOCAL_TYPE) , INTENT(INOUT) :: GEMSL
END SUBROUTINE AER_GLOMAPDIAG_LAYER
END INTERFACE
