INTERFACE
 SUBROUTINE AER_DRYDEPVELZH14(KVEG,PLAI, PWETD,&
 & PZ0M,PCI,PUSTR,PDZ,PVDEP) 
USE PARKIND1, ONLY: JPRB, JPIM
INTEGER(KIND=JPIM), INTENT(IN) :: KVEG
REAL(KIND=JPRB), INTENT(IN) :: PLAI
REAL(KIND=JPRB), INTENT(IN) :: PWETD
REAL(KIND=JPRB), INTENT(IN) :: PZ0M
REAL(KIND=JPRB), INTENT(IN) :: PCI
REAL(KIND=JPRB), INTENT(IN) :: PUSTR
REAL(KIND=JPRB), INTENT(IN) :: PDZ
REAL(KIND=JPRB), INTENT(OUT) :: PVDEP
END SUBROUTINE AER_DRYDEPVELZH14
END INTERFACE
