INTERFACE
SUBROUTINE AER_LOSS_AD&
 & ( YDEAERSNK,KIDIA, KFDIA, KLON, KLEV, KAERO,&
 & PAERO5 , PTSPHY,&
 & PTAERO5,&
 & PAERO ,&
 & PTAERO&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOEAERSNK ,ONLY : TEAERSNK
TYPE(TEAERSNK) ,INTENT(INOUT):: YDEAERSNK
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO
REAL(KIND=JPRB),INTENT(IN) :: PAERO5(KLON,KLEV,KAERO)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(INOUT) :: PTAERO5(KLON,KLEV,KAERO)
REAL(KIND=JPRB),INTENT(INOUT) :: PAERO(KLON,KLEV,KAERO)
REAL(KIND=JPRB),INTENT(IN) :: PTAERO(KLON,KLEV,KAERO)
END SUBROUTINE AER_LOSS_AD
END INTERFACE
