INTERFACE
SUBROUTINE AER_STRFREE&
 & ( KLAT, KLEV,&
 & PPMB , PT , PRMODRA,&
 & PFPATH ) 
USE PARKIND1 ,ONLY : JPRB , JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT,KLEV
REAL(KIND=JPRB),INTENT(IN) :: PT(KLAT,KLEV), PPMB(KLAT,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRMODRA (KLAT,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PFPATH (KLAT,KLEV)
END SUBROUTINE AER_STRFREE
END INTERFACE
