INTERFACE
 SUBROUTINE AER_VGRAV(KIK,PDP,PSIGMA,PDVISC,PMFPA,PRHOP,PVGRAV_AV)
USE PARKIND1, ONLY: JPRB, JPIM
INTEGER(KIND=JPIM), INTENT(IN) :: KIK
REAL(KIND=JPRB), INTENT(IN) :: PDP
REAL(KIND=JPRB), INTENT(IN) :: PSIGMA
REAL(KIND=JPRB), INTENT(IN) :: PDVISC
REAL(KIND=JPRB), INTENT(IN) :: PMFPA
REAL(KIND=JPRB), INTENT(IN) :: PRHOP
REAL(KIND=JPRB), INTENT(OUT) :: PVGRAV_AV
END SUBROUTINE AER_VGRAV
END INTERFACE
