INTERFACE
SUBROUTINE AER_CGROWTH&
 & ( YDEAERATM,KIDIA , KFDIA , KLON , KLEV ,&
 & PAERPHO , PITAERPHO, PTSPHY ,&
 & PTAERPHI, PTAERPHO&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOEAERATM ,ONLY : TEAERATM
TYPE(TEAERATM) ,INTENT(INOUT) :: YDEAERATM
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAERPHO(KLON,KLEV) , PITAERPHO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTAERPHI(KLON,KLEV), PTAERPHO(KLON,KLEV)
END SUBROUTINE AER_CGROWTH
END INTERFACE
