INTERFACE
SUBROUTINE AER_CLD (&
 & YDECLDP,KIDIA , KFDIA, KLON, KLEV,&
 & KACTAERO,&
 & PAERO , PT ,&
 & PAP ,&
 & PL , PI , PA ,&
 & PLCRIT_AER, PICRIT_AER,&
 & PRE_LIQ , PRE_ICE,&
 & PCCN , PNICE&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOECLDP , ONLY : TECLDP
TYPE(TECLDP) ,INTENT(INOUT) :: YDECLDP
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KACTAERO
REAL(KIND=JPRB) ,INTENT(IN) :: PAERO(KLON,KLEV,KACTAERO)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLCRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PICRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRE_LIQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRE_ICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCCN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNICE(KLON,KLEV)
END SUBROUTINE AER_CLD
END INTERFACE
