INTERFACE
SUBROUTINE AERC_SCAVL19&
 & ( YDMODEL,KIDIA , KFDIA , KLON , KLEV , KAER , KAER_SCAV, KSTEP, PTSPHY,&
 & PRSF1, PDP , PTP, PFLXR, PFLXS, PCLCOV, PCLWAT, PCLICE, PRAIN, PSNOW, PCEN, PTENC0,&
 & PTENC1, PFAERO, PPRCOV ) 
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV, KAER, KAER_SCAV, KSTEP
REAL(KIND=JPRB),INTENT(IN) :: PDP(KLON,KLEV) , PRSF1(KLON,KLEV) , PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCLCOV(KLON,KLEV) , PCLWAT(KLON,KLEV),PCLICE(KLON,KLEV) , PRAIN(KLON,KLEV), PSNOW(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL, INTENT(IN) :: PPRCOV(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFLXR(KLON,KLEV+1), PFLXS(KLON,KLEV+1)
REAL(KIND=JPRB),INTENT(IN) :: PTENC0(KLON,KLEV,KAER), PCEN(KLON,KLEV,KAER)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(OUT) :: PTENC1(KLON,KLEV,KAER)
REAL(KIND=JPRB),INTENT(OUT) :: PFAERO(KLON,KAER)
END SUBROUTINE AERC_SCAVL19
END INTERFACE
