INTERFACE
SUBROUTINE AERDIAG_LAYER(YDSURF,YDECLDP,YDERAD,YDML_GCONF,YDPHY2,KDIM, GEMSL, PAUX, STATE, PDIAG, AUXL,&
 & PSURF) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOECLDP , ONLY : TECLDP, NCLDQI, NCLDQL
USE YOERAD , ONLY : TERAD
USE YOMPHY2 , ONLY : TPHY2
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER , ONLY : DIMENSION_TYPE, AUX_DIAG_LOCAL_TYPE,&
 & SURF_AND_MORE_TYPE, AUX_DIAG_TYPE, STATE_TYPE,&
 & AUX_TYPE, GEMS_LOCAL_TYPE 
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(TECLDP) , INTENT(INOUT) :: YDECLDP
TYPE(TERAD) , INTENT(INOUT) :: YDERAD
TYPE(MODEL_GENERAL_CONF_TYPE) , INTENT(INOUT) :: YDML_GCONF
TYPE(TPHY2) , INTENT(INOUT) :: YDPHY2
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (GEMS_LOCAL_TYPE) , INTENT (IN) :: GEMSL
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (AUX_DIAG_TYPE) , INTENT (IN) :: PDIAG
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
END SUBROUTINE AERDIAG_LAYER
END INTERFACE
