INTERFACE
SUBROUTINE AERINI_LAYER(YDGEOMETRY,YDSURF,&
 & YDMODEL,KDIM,PAUX,STATE,R,S,PSURF,SURFL,GEMSL) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE VARIABLE_MODULE, ONLY : VARIABLE_3D
USE YOMPHYDER, ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE, GEMS_LOCAL_TYPE 
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) ,INTENT (IN) :: KDIM
TYPE (AUX_TYPE) ,INTENT (IN) :: PAUX
TYPE (STATE_TYPE) ,INTENT (IN) :: STATE
TYPE(VARIABLE_3D) ,INTENT (IN) :: R, S
TYPE (SURF_AND_MORE_TYPE) ,INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE),INTENT(INOUT) :: SURFL
TYPE (GEMS_LOCAL_TYPE) ,INTENT(INOUT) :: GEMSL
END SUBROUTINE AERINI_LAYER
END INTERFACE
