INTERFACE
SUBROUTINE AERO_INIT(YGFL,YDCOMPO,YDEAERATM,KDIM,GEMSL)
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMCOMPO , ONLY : TCOMPO
USE YOEAERATM, ONLY : TEAERATM
USE YOMPHYDER, ONLY : DIMENSION_TYPE, GEMS_LOCAL_TYPE
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE(TCOMPO) ,INTENT(IN) :: YDCOMPO
TYPE(TEAERATM) ,INTENT(IN) :: YDEAERATM
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (GEMS_LOCAL_TYPE) , INTENT(INOUT) :: GEMSL
END SUBROUTINE AERO_INIT
END INTERFACE
