INTERFACE
SUBROUTINE AMV_OBERR(ROBODY,SATHDR,YDGP5,&
 & KOBSTYPE,PLAT,PLON) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY,SATHDR
TYPE(TYPE_GOM_PLUS) ,INTENT(IN) :: YDGP5
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSTYPE
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(YDGP5%NDLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(YDGP5%NDLEN)
END SUBROUTINE AMV_OBERR
END INTERFACE
