INTERFACE
SUBROUTINE AOD_AD&
 & (KFLEVG, KDLEN , KLEN , KMXCOUNT,&
 & YDGP_AD,&
 & YDGP5,&
 & PAEROD_HAT) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEVG, KDLEN, KLEN, KMXCOUNT
TYPE (TYPE_GOM_PLUS),INTENT(INOUT) :: YDGP_AD
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAEROD_HAT(KDLEN,KMXCOUNT)
END SUBROUTINE AOD_AD
END INTERFACE
