INTERFACE
SUBROUTINE APACHE(LDNEIGE,KPROMA,KSTART,KPROF,KLEV,KOPLEV,KPPGFL,KPPM,YDKC,&
 & LDPDEP,LDWHALF,LDWFULL,LDGFL,LDOBS,LDSPCH,PRHBNDS,&
 & PORO1,PORO2,PDPBLC,PTS1,PTS2,PEPS2,PEPR2F,PEPR2H,&
 & YDVERT_GEOM,&
 & PT1,PU1,PV1,PSPD1,PWW1,PGFL1,&
 & PRES1H,PRES1F,PLNPR1,PALPH1,PR1,PKAPA1,PRHF1,&
 & PT2,PU2,PV2,PSPD2,PWH2,PWF2,PGFL2,PFI2,PRH2,PEORG) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_GFLFLDS, ONLY : TYPE_IGFLFLD
USE YOMVERT , ONLY : TVERTICAL_GEOM
LOGICAL ,INTENT(IN) :: LDNEIGE
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KOPLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPPGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
TYPE(TYPE_IGFLFLD),INTENT(IN) :: YDKC
LOGICAL ,INTENT(IN) :: LDPDEP
LOGICAL ,INTENT(IN) :: LDWHALF
LOGICAL ,INTENT(IN) :: LDWFULL
LOGICAL ,INTENT(IN) :: LDGFL(KPPGFL)
LOGICAL ,INTENT(IN) :: LDOBS
LOGICAL ,INTENT(IN) :: LDSPCH
REAL(KIND=JPRB) ,INTENT(IN) :: PRHBNDS(2)
REAL(KIND=JPRB) ,INTENT(IN) :: PORO1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PORO2(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPBLC
REAL(KIND=JPRB) ,INTENT(IN) :: PTS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS2(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEPS2(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEPR2F(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PEPR2H(KPROMA,KOPLEV,0:1)
TYPE(TVERTICAL_GEOM), INTENT(IN) :: YDVERT_GEOM
REAL(KIND=JPRB) ,INTENT(IN) :: PT1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPD1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PWW1(KPROMA,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL1(KPROMA,KLEV,KPPGFL)
REAL(KIND=JPRB) ,INTENT(IN) :: PRES1H(KPROMA,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRES1F(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKAPA1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRHF1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPD2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWH2(KPROMA,KOPLEV,0:1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWF2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL2(KPROMA,KOPLEV,KPPGFL)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFI2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRH2(KPROMA,KOPLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEORG(KPROMA,KOPLEV)
END SUBROUTINE APACHE
END INTERFACE
