INTERFACE
SUBROUTINE APL_AROME(YDCST, YDMF_PHYS_BASE_STATE, YDMF_PHYS_NEXT_STATE, YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS,&
 & YDCPG_MISC, YDCPG_GPAR, YDCPG_PHY0, YDMF_PHYS, YDCPG_DYN0, YDMF_PHYS_SURF,&
 & YDCPG_SL1, YDVARS, YDGMV, YDSURF, YDCFU, YDXFU, YDMODEL, PGFL, PGP2DSDT, PGMVT1,&
 & PGFLT1, PTRAJ_PHYS, YDDDH) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_MISC_TYPE, CPG_GPAR_TYPE, CPG_SL1_TYPE, CPG_DYN_TYPE, CPG_PHY_TYPE
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMXFU , ONLY : TXFU
USE YOMCFU , ONLY : TCFU
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM ,JPRB ,JPRD
USE YOMCST , ONLY : TCST
USE DDH_MIX , ONLY : NEW_ADD_FIELD_3D, NEW_ADD_FIELD_2D,&
 & NTOTSVAR, NTOTSURF, NTOTSVFS, TYP_DDH 
USE YOMSPSDT , ONLY : YSPPT_CONFIG, YSPPT
USE MF_PHYS_BASE_STATE_TYPE_MOD&
 & , ONLY : MF_PHYS_BASE_STATE_TYPE 
USE MF_PHYS_NEXT_STATE_TYPE_MOD&
 & , ONLY : MF_PHYS_NEXT_STATE_TYPE 
USE YOMGMV , ONLY : TGMV
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE
TYPE(TCST), INTENT(IN) :: YDCST
TYPE (MF_PHYS_BASE_STATE_TYPE), INTENT(IN) :: YDMF_PHYS_BASE_STATE
TYPE (MF_PHYS_NEXT_STATE_TYPE), INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE), INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE), INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_MISC_TYPE), INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_GPAR_TYPE), INTENT(INOUT) :: YDCPG_GPAR
TYPE(CPG_PHY_TYPE), INTENT(IN) :: YDCPG_PHY0
TYPE(MF_PHYS_TYPE), INTENT(IN) :: YDMF_PHYS
TYPE(CPG_DYN_TYPE), INTENT(IN) :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE), INTENT(INOUT) :: YDMF_PHYS_SURF
TYPE(CPG_SL1_TYPE), INTENT(INOUT) :: YDCPG_SL1
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
TYPE(TGMV), INTENT(IN) :: YDGMV
TYPE(TSURF), INTENT(IN) :: YDSURF
TYPE(TCFU), INTENT(IN) :: YDCFU
TYPE(TXFU), INTENT(IN) :: YDXFU
TYPE(MODEL), INTENT(IN) :: YDMODEL
REAL(KIND=JPRB), INTENT(INOUT) :: PGFL(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB), INTENT(IN) :: PGP2DSDT(YDCPG_OPTS%KLON,YSPPT%YGPSDT(1)%NG2D,YSPPT%N2D)
REAL(KIND=JPRB), INTENT(INOUT) :: PGMVT1(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB), INTENT(INOUT) :: PGFLT1(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1)
TYPE (TRAJ_PHYS_TYPE), INTENT(INOUT) :: PTRAJ_PHYS
TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
END SUBROUTINE APL_AROME
END INTERFACE
