INTERFACE
SUBROUTINE APL_AROME_CALC_IPTR (YDMODEL, KEFB1, KEFB2, KEFB3, KPTR, KPTREXT, KPTRLIMA, KPTRTKE, KRR)
USE PARKIND1, ONLY : JPIM, JPRB
USE TYPE_MODEL , ONLY : MODEL
TYPE(MODEL), INTENT (IN) :: YDMODEL
INTEGER(KIND=JPIM), INTENT (OUT) :: KPTREXT,KEFB1,KEFB2,KEFB3
INTEGER(KIND=JPIM), INTENT (OUT) :: KPTR(YDMODEL%YRML_GCONF%YGFL%NUMFLDS)
INTEGER(KIND=JPIM), INTENT (OUT) :: KPTRLIMA
INTEGER(KIND=JPIM), INTENT (OUT) :: KPTRTKE
INTEGER(KIND=JPIM), INTENT (OUT) :: KRR
END SUBROUTINE
END INTERFACE
