INTERFACE
SUBROUTINE APLMPHYS ( YDML_PHY_MF,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PAPRS,PAPRSF,PCP,PQMP,PQIMP,PQLMP,PQNMP,PQRMP,PQGMP,PR,PTMP,&
 & PIPOI,PDQ,PDQM,PLHS,PLHV,PNEBM,PPOID,PRCVOTT,PTCORR,&
 & PLSM,PNEIJ,PTS,PDECRD,&
 & PFCSQL,PFCSQN,&
 & PFALLR,PFALLS,PFALLG,&
 & PFASL,PFASN,PFASG,PFESL,PFESN,PFESG,PFPLSL,PFPLSN,PFPLSG,PSEDIQL,PSEDIQI,&
 & PGRVINT) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB ,JPRD
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQIMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQNMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQRMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQGMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTMP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIPOI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDQM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEBM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPOID(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCVOTT(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTCORR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDECRD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCSQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCSQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFALLR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFALLS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFALLG(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFASL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFASN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFASG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFESL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFESN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFESG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSEDIQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSEDIQI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGRVINT(KLON)
END SUBROUTINE APLMPHYS
END INTERFACE
