INTERFACE
SUBROUTINE APLPAR2INTFLEX(YGFL,YDPHY,KPROMA, KST, KEND, KFLEV,&
 & PDIFCQ , PDIFCQI, PDIFCQL, PDIFCS ,PDIFEXT,&
 & PDIFTQ , PDIFTQI, PDIFTQL, PDIFTS ,&
 & PFCCQL , PFCCQN , PFCSQL , PFCSQN ,&
 & PFPLSL , PFPLSN , PFPLCL, PFPLCN,&
 & PFESL , PFESN , PFECL , PFECN ,&
 & PFASL , PFASN , PFACL , PFACN ,&
 & PFCQLNG, PFCQING, PFCQRNG, PFCQSNG,&
 & PFCQNG , PFRMH , PFRMQ , PFRSO , PFRTH ,&
 & PSTRCU , PSTRCV , PSTRDU , PSTRDV ,&
 & PSTRTU , PSTRTV , PSTRMU , PSTRMV ,&
 & PDIFCQLC,PDIFCQIC,PFIMCC,&
 & PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC,&
 & PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC,&
 & PFTKE,&
 & PTENDTKE, PTENDEXT, PTENDEXT_DEP,&
 & YDPROCSET) 
USE PARKIND1, ONLY : JPIM, JPRB
USE INTFLEX_MOD, ONLY : TYPE_INTPROCSET, TYPE_INTPROC, NEWINTPROC, NEWINTFIELD
USE YOMPHY, ONLY : TPHY
USE YOM_YGFL, ONLY : TYPE_GFLD
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TYPE_GFLD) ,INTENT(IN),TARGET :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQ (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQI (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCS (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQI (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFESL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFESN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFECL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFECN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFASL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFASN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFACL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFACN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQNG (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQLNG (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQING (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQRNG (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQSNG (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRMH (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRMQ (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRCU (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRCV (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRDU (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRDV (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTU (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTV (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRMU (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRMV (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDTKE (KPROMA,1:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFTKE (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFEXT (KPROMA,0:KFLEV,YGFL%NGFL_EXT)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDEXT (KPROMA,1:KFLEV,YGFL%NGFL_EXT)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDEXT_DEP (KPROMA,1:KFLEV,YGFL%NGFL_EXT)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQLC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQIC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFIMCC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEDQLC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEDQIC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEDQRC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEDQSC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCNEGQLC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCNEGQIC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCNEGQRC(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCNEGQSC(KPROMA,0:KFLEV)
TYPE(TYPE_INTPROCSET), INTENT(INOUT) :: YDPROCSET
END SUBROUTINE APLPAR2INTFLEX
END INTERFACE
