INTERFACE
SUBROUTINE APLPASSH (YDCST,YDPHY,YDPHY1,KIDIA,KFDIA,KLON,KLEV,&
 & PAPRS, PQ,&
 & PSNS, PTS, PWS, PLSM, PVEG,&
 & PQS) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY , ONLY : TPHY
USE YOMPHY1 , ONLY : TPHY1
USE YOMCST , ONLY : TCST
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TPHY1) ,INTENT(IN) :: YDPHY1
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQS(KLON)
END SUBROUTINE APLPASSH
END INTERFACE
