INTERFACE
SUBROUTINE APPLY_HPGAUSS1D(PSIGMA,PGAMMA,PFIELD,KNORDER,KNPASSES,KNOCTAVES)
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 REAL(KIND=JPRB), INTENT(IN) :: PSIGMA
 REAL(KIND=JPRB), INTENT(IN) :: PGAMMA
 REAL(KIND=JPRB), INTENT(INOUT) :: PFIELD(:)
 INTEGER(KIND=JPIM) , INTENT(IN) :: KNORDER
 INTEGER(KIND=JPIM) , INTENT(IN) :: KNPASSES
 INTEGER(KIND=JPIM) , INTENT(IN) :: KNOCTAVES
END SUBROUTINE APPLY_HPGAUSS1D
END INTERFACE
