INTERFACE
SUBROUTINE APPLY_BAL_TL(YDGEOMETRY,PSPVO,PSPT,PSP3,PSP2)
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB),INTENT(INOUT) :: PSPVO(:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PSPT(:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PSP3(:,:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PSP2(:,:)
END SUBROUTINE APPLY_BAL_TL
END INTERFACE
