INTERFACE
SUBROUTINE APPLY_RECF1D(PALPHA,PFIELD,KNGRID,KNORDER)
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 REAL(KIND=JPRB), INTENT(IN) :: PALPHA(:)
 REAL(KIND=JPRB), INTENT(INOUT) :: PFIELD(:)
 INTEGER(KIND=JPIM) , INTENT(IN) :: KNGRID
 INTEGER(KIND=JPIM) , INTENT(IN) :: KNORDER
END SUBROUTINE APPLY_RECF1D
END INTERFACE
