INTERFACE
SUBROUTINE ASCATIN (KSCATP,&
 & KOBTYP,KCDTYP,KOBSQNO,KCDSQNO,&
 & LDMESAGE,LDTAKEN) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE PARERSCA
USE YOMDB
INTEGER(KIND=JPIM),INTENT(IN) :: KSCATP
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KCDTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSQNO
INTEGER(KIND=JPIM),INTENT(IN) :: KCDSQNO
LOGICAL ,INTENT(INOUT) :: LDMESAGE
LOGICAL ,INTENT(OUT) :: LDTAKEN
END SUBROUTINE ASCATIN
END INTERFACE
