INTERFACE
SUBROUTINE BACKSCATTER_LAYER(&
 & YDDIM, YDML_PHY_STOCH,YDDYN,YDPHY2,KDIM, PAUX, STATE_T0, STATE_TMP,&
 & PPERT, PERTL, PDIAG, PSURF, TENDENCY) 
USE MODEL_PHYSICS_STOCHAST_MOD , ONLY : MODEL_PHYSICS_STOCHAST_TYPE
USE YOMDYN , ONLY : TDYN
USE YOMPHY2 , ONLY : TPHY2
USE YOMDIM , ONLY : TDIM
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & PERTURB_TYPE, PERTURB_LOCAL_TYPE, SURF_AND_MORE_TYPE,&
 & AUX_DIAG_TYPE 
TYPE(TDIM) , INTENT (IN) :: YDDIM
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_PHYSICS_STOCHAST_TYPE),INTENT(INOUT):: YDML_PHY_STOCH
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE_T0
TYPE (STATE_TYPE) , INTENT (IN) :: STATE_TMP
TYPE (PERTURB_TYPE) , INTENT(INOUT) :: PPERT
TYPE (PERTURB_LOCAL_TYPE) , INTENT(INOUT) :: PERTL
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY
END SUBROUTINE BACKSCATTER_LAYER
END INTERFACE
