INTERFACE
SUBROUTINE BALNONLIN(YDGEOMETRY,PVOR,PZZP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB), INTENT(INOUT) :: PVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB), INTENT(OUT) :: PZZP(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
END SUBROUTINE BALNONLIN
END INTERFACE
