INTERFACE
SUBROUTINE BALVERTI(YDGEOMETRY,YD_JB_STRUCT,PSPZZP,YDSPEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
REAL(KIND=JPRB) ,INTENT(IN) :: PSPZZP(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
END SUBROUTINE BALVERTI
END INTERFACE
