INTERFACE
SUBROUTINE BASCOE_PSC_POSSIBLE( KIDIA, KFDIA, KLON, KLEV, KJULDAY, PTP,PRSF1,PLAT,KTROPOP,&
 & LD_PSC_POSSIBLE,KTOP_PSC,KBOT_PSC) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB),INTENT(IN) :: PTP(KLON,KLEV),PRSF1(KLON,KLEV),PLAT(KLON)
INTEGER(KIND=JPIM), INTENT(IN) :: KJULDAY
INTEGER(KIND=JPIM), INTENT(IN) :: KTROPOP(KLON)
LOGICAL, INTENT(OUT) :: LD_PSC_POSSIBLE(KLON)
INTEGER(KIND=JPIM) , INTENT(OUT) :: KTOP_PSC(KLON),KBOT_PSC(KLON)
END SUBROUTINE BASCOE_PSC_POSSIBLE
END INTERFACE
