INTERFACE
SUBROUTINE BASCOE_J_CALC( KLEV, PZKM, PSZA, PTP, PDENSA , PALB, PAJVAL)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE BASCOE_TUV_MODULE , ONLY : nabspec, abs_molmass,&
 & air, O2abs, O3abs, NOabs, CO2abs, NO2abs 
USE BASCOE_J_MODULE , ONLY : NDISS
 INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
 REAL(KIND=JPRB), INTENT(IN) :: PZKM(KLEV)
 REAL(KIND=JPRB), INTENT(IN) :: PSZA
 REAL(KIND=JPRB), INTENT(IN) :: PTP(KLEV)
 REAL(KIND=JPRB), INTENT(IN) :: PDENSA(KLEV,NABSPEC)
 REAL(KIND=JPRB), INTENT(IN) :: PALB
 REAL(KIND=JPRB), DIMENSION(KLEV,NDISS), INTENT(OUT) :: PAJVAL
END SUBROUTINE BASCOE_J_CALC
END INTERFACE
