INTERFACE
SUBROUTINE BASCOE_KPP_KppDecomp( PJVS, KERR )
 USE BASCOE_KPP_Parameters, only: LU_NONZERO
 USE PARKIND1 , ONLY : JPIM ,JPRB
 INTEGER(KIND=JPIM), INTENT(OUT) :: KERR
 REAL(kind=JPRB), INTENT(INOUT) :: PJVS(LU_NONZERO)
END SUBROUTINE BASCOE_KPP_KppDecomp
END INTERFACE
