INTERFACE
SUBROUTINE BASCOE_INTERP2D_LOC(KX, KY, PX, PY, LDXLON, PXO, PYO, KDX, PRD, k_ok )
USE PARKIND1 , ONLY : JPIM , JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KX, KY
REAL(KIND=JPRB) , INTENT(IN) :: PX(KX), PY(KY)
REAL(KIND=JPRB) , INTENT(IN) :: PXO, PYO
LOGICAL, INTENT(IN) :: LDXLON
INTEGER(KIND=JPIM), INTENT(OUT) :: KDX(4)
REAL(KIND=JPRB) , INTENT(OUT) :: PRD(2)
INTEGER(KIND=JPIM), INTENT(OUT) :: k_ok
END SUBROUTINE BASCOE_INTERP2D_LOC
END INTERFACE
