INTERFACE
SUBROUTINE BASCOE_KPP_Rates (PAJVAL,PRHET, PTEMP, PCFACTOR, PRCONST, PVAR)
 USE PARKIND1 ,ONLY : JPIM, JPRB
 USE BASCOE_MODULE, ONLY : NHET
 USE BASCOE_J_MODULE, ONLY : NDISS,&
 & J_O2_O,J_O3_O,&
 & J_O3_O1D,J_HO2,J_H2O2_OH ,J_NO2,J_NO3_O ,J_NO3_O2,J_N2O5,J_HNO3,&
 & J_HO2NO2_HO2,J_Cl2,J_Br2,J_OClO,J_Cl2O2 ,J_HOCl,J_ClONO2_Cl ,&
 & J_BrCl,J_BrONO2_Br ,J_CH2O_HCO,J_CH2O_CO ,J_CH3OOH,&
 & J_HO2NO2_OH ,J_ClONO2_ClO,J_BrO,J_CCl4,J_CFC11 ,J_CFC113,J_CFC114,J_CFC115,&
 & J_CFC12 ,J_CH3Br ,J_CH3CCl3 ,J_CH3Cl ,J_CH4,J_CHBr3 ,J_ClNO2 ,J_ClOO,&
 & J_ClO,J_H2O,J_HA1211,J_HA1301,J_HCFC22,J_HCl,&
 & J_HOBr,J_N2O,J_NO,J_O2_O1D,J_BrONO2_BrO,J_CO2,J_CH2Br2,J_H2O2_HO2,&
 & J_OCS, J_H2SO4, J_SO3 
 USE BASCOE_KPP_Parameters, only: NREACT,NVAR,ind_H2O
 REAL(KIND=JPRB) , INTENT(IN) :: PTEMP
 REAL(KIND=JPRB) , DIMENSION(NDISS) , INTENT(IN) :: PAJVAL
 REAL(KIND=JPRB) , INTENT(IN) :: PRHET(NHET)
 REAL(KIND=JPRB) , INTENT(IN) :: PCFACTOR
 REAL(KIND=JPRB) , intent(out) :: PRCONST(NREACT)
 REAL(KIND=JPRB) , INTENT(IN) :: PVAR(NVAR)
END SUBROUTINE BASCOE_KPP_Rates
END INTERFACE
