INTERFACE
SUBROUTINE BASCOE_TROPOPAUSE(KIDIA,KFDIA,KLON,KLEV,PTP,PRSF1,PGEOH,PLAT,KTROPOP)
USE PARKIND1 , ONLY : JPIM , JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA , KFDIA , KLON , KLEV
REAL(KIND=JPRB) , INTENT(IN) :: PTP(KLON,KLEV),PRSF1(KLON,KLEV),PGEOH(KLON,KLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PLAT(KLON)
INTEGER(KIND=JPIM), INTENT(OUT) :: KTROPOP(KLON)
END SUBROUTINE BASCOE_TROPOPAUSE
END INTERFACE
