INTERFACE
SUBROUTINE BASCOE_J_INTERP(PSZA,PZKM,PO3_OVER, PAJVAL )
USE PARKIND1 , ONLY : JPIM ,JPRB
USE BASCOE_J_MODULE , ONLY : NDISS
REAL(KIND=JPRB),INTENT(IN) :: PSZA
REAL(KIND=JPRB),INTENT(IN) :: PZKM
REAL(KIND=JPRB),INTENT(IN) :: PO3_OVER
REAL(KIND=JPRB),DIMENSION(NDISS), INTENT(out) :: PAJVAL
END SUBROUTINE BASCOE_J_INTERP
END INTERFACE
