INTERFACE
SUBROUTINE BASCOE_CSKIP( CD , KUNIT )
USE PARKIND1 , ONLY : JPIM, JPRB
 CHARACTER(LEN=*), INTENT(IN) :: CD
 INTEGER(KIND=JPIM), INTENT(IN) :: KUNIT
END SUBROUTINE BASCOE_CSKIP
END INTERFACE
