INTERFACE
SUBROUTINE BASCOE_READ_COLDAT( CD_FILENM, KN_OUT, PZ, PVAL, CD_EXT_VALS )
USE PARKIND1 , ONLY : JPIM ,JPRB
 CHARACTER(LEN=*), intent(in) :: CD_FILENM
 INTEGER(KIND=JPIM), intent(in) :: KN_OUT
 REAL(KIND=JPRB), dimension(KN_OUT), intent(in) :: PZ
 REAL(KIND=JPRB), dimension(KN_OUT), intent(inout) :: PVAL
 CHARACTER(LEN=*), intent(in) :: CD_EXT_VALS
END SUBROUTINE BASCOE_READ_COLDAT
END INTERFACE
