INTERFACE
SUBROUTINE BAYRAD_NEW_THIN(ROBHDR,ROBODY,KLEN,KBOXNO,KSENSOR_RQ)
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY : IFS_DBASE_VIEW
USE YOMDB
USE YOMOBS
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR, ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KBOXNO
INTEGER(KIND=JPIM),INTENT(IN) :: KSENSOR_RQ
END SUBROUTINE BAYRAD_NEW_THIN
END INTERFACE
