INTERFACE
SUBROUTINE BAYRAD_SIM(ROBODY,KLEN,KMAXCOUNT,KHORIZ,KNFLEVG,KSAT,KISENSOR,KNCHANINS,KNCHAN,KBCHAN,PPRESF5_2D,&
 & PPRESH5_2D,PTF5_2D,PQF5_2D,PCLWF5_2D,PCIWF5_2D,PCCF5_2D,PCRWF5_2D,PCSWF5_2D,&
 & PTS5,PLS5,POROG5,PUF5,PVF5,PZENITHSAT,PAZIMSAT,PLAT,ZEM5,LDCFRAC,PRADSIM_2D,KNPART) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE BAYRAD_CONST, ONLY: FASTEM_OCEAN, FASTEM_LAND_COEFF,&
 & COEF_RTTOV, COEF_SCATT_MULTI, IMAXPART 
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KMAXCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM),INTENT(IN) :: KNFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KSAT
INTEGER(KIND=JPIM),INTENT(IN) :: KISENSOR
INTEGER(KIND=JPIM),INTENT(IN) :: KNCHANINS
INTEGER(KIND=JPIM),INTENT(IN) :: KNCHAN
INTEGER(KIND=JPIM),INTENT(IN) :: KBCHAN(KNCHAN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PPRESF5_2D(KLEN,KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PPRESH5_2D(KLEN,0:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PTF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PQF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PCLWF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PCIWF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PCCF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PCRWF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PCSWF5_2D(KLEN,1:KNFLEVG,KHORIZ)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PTS5(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PLS5(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: POROG5(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PUF5(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PVF5(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PZENITHSAT(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PAZIMSAT(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PLAT(KLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: ZEM5(KLEN,KMAXCOUNT)
LOGICAL,INTENT(IN) :: LDCFRAC
REAL(KIND=JPRB),INTENT(INOUT) :: PRADSIM_2D(KLEN,KHORIZ,KNCHANINS,IMAXPART)
INTEGER(KIND=JPIM),INTENT(IN) :: KNPART
END SUBROUTINE BAYRAD_SIM
END INTERFACE
