INTERFACE
SUBROUTINE BAYRAD_OPOBS(ROBODY,KDLEN,KMAXCOUNT,KHORIZ,KISAT,KISENSOR,KNCHANINS,KCHANINSRT,KNRTCHAN,LELAM,&
 & YDGP5,PTS5,PENITHSAT,PAZIMSAT,PLAT,PEM5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KMAXCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM),INTENT(IN) :: KISAT
INTEGER(KIND=JPIM),INTENT(IN) :: KISENSOR
INTEGER(KIND=JPIM),INTENT(IN) :: KNCHANINS
INTEGER(KIND=JPIM),INTENT(IN) :: KNRTCHAN
INTEGER(KIND=JPIM),INTENT(IN) :: KCHANINSRT(KNRTCHAN)
LOGICAL,INTENT(IN) :: LELAM
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB),INTENT(IN),TARGET :: PTS5(KDLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PENITHSAT(KDLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PAZIMSAT(KDLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PLAT(KDLEN)
REAL(KIND=JPRB),INTENT(IN),TARGET :: PEM5(KDLEN,KMAXCOUNT)
END SUBROUTINE BAYRAD_OPOBS
END INTERFACE
