INTERFACE
SUBROUTINE BCASTCOV(KLEV,KSMAX,PCOVT,PCOVV,PCOVD,K3D,PCOV3,KPROC)
USE PARKIND1, ONLY: JPIM, JPRB
USE MPL_MODULE
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV,KSMAX,K3D,KPROC
REAL(KIND=JPRB) , INTENT(INOUT) :: PCOVT(KLEV+1,KLEV+1,0:KSMAX)
REAL(KIND=JPRB) , INTENT(INOUT) :: PCOVV(KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB) , INTENT(INOUT) :: PCOVD(KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB) , INTENT(INOUT) :: PCOV3(KLEV,KLEV,0:KSMAX,K3D)
END SUBROUTINE BCASTCOV
END INTERFACE
