INTERFACE
SUBROUTINE BGPERT(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YD_BG,YD_TRAJEC,YDVARBC,YDTCV_BGC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS, FIELDS_CREATE, FIELDS_DELETE
USE MTRAJ_MOD , ONLY : MTRAJ
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_BGC_MOD, ONLY : TOVSCV_BGC
USE YOMTRAJ , ONLY : TRAJ_TYPE
USE CONTROL_VECTORS_MOD
USE RANDOM_NUMBERS_MIX
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(TRAJ_TYPE), INTENT(INOUT) :: YD_BG
TYPE(TRAJ_TYPE), INTENT(IN) :: YD_TRAJEC
TYPE(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV_BGC) ,INTENT(IN) :: YDTCV_BGC
END SUBROUTINE BGPERT
END INTERFACE
