INTERFACE
SUBROUTINE BIASCOR_ERA40 (LD_LBC,K_NST,P_SPP,P_ST,P_STNBC,&
 & CD_CIDENT,K_IY,K_IM,K_ID,K_IH,P_RLAT,P_RLON,&
 & P_RMISS,LDSOLAR,LDHOMOGEN) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
LOGICAL ,INTENT(OUT) :: LD_LBC
INTEGER(KIND=JPIM),INTENT(IN) :: K_NST
REAL(KIND=JPRB) ,INTENT(IN) :: P_SPP(K_NST)
REAL(KIND=JPRB) ,INTENT(IN) :: P_ST(K_NST)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_STNBC(K_NST)
CHARACTER(LEN=5) ,INTENT(IN) :: CD_CIDENT
INTEGER(KIND=JPIM),INTENT(IN) :: K_IM
INTEGER(KIND=JPIM),INTENT(IN) :: K_ID
INTEGER(KIND=JPIM),INTENT(IN) :: K_IH
INTEGER(KIND=JPIM),INTENT(IN) :: K_IY
REAL(KIND=JPRB) ,INTENT(IN) :: P_RLAT
REAL(KIND=JPRB) ,INTENT(IN) :: P_RLON
REAL(KIND=JPRB) ,INTENT(IN) :: P_RMISS
LOGICAL ,INTENT(IN) :: LDSOLAR,LDHOMOGEN
END SUBROUTINE BIASCOR_ERA40
END INTERFACE
