INTERFACE
SUBROUTINE BIASCOR_ODB(LDBC ,KNOPLEV,PPRES,PT,PTBC,&
 & CDIDENT, KY, KM,KD, KH,PLAT,PLON,PALT,KRSTYP,&
 & KMISS ,PMISS ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRSTBIAS
INTEGER(KIND=JPIM),INTENT(IN) :: KNOPLEV
LOGICAL ,INTENT(OUT) :: LDBC
REAL(KIND=JPRB) ,INTENT(IN) :: PPRES(KNOPLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KNOPLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTBC(KNOPLEV)
CHARACTER(LEN=*) ,INTENT(IN) :: CDIDENT
INTEGER(KIND=JPIM),INTENT(IN) :: KY
INTEGER(KIND=JPIM),INTENT(IN) :: KM
INTEGER(KIND=JPIM),INTENT(IN) :: KD
INTEGER(KIND=JPIM),INTENT(IN) :: KH
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
REAL(KIND=JPRB) ,INTENT(IN) :: PALT
INTEGER(KIND=JPIM),INTENT(IN) :: KRSTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KMISS
REAL(KIND=JPRB) ,INTENT(IN) :: PMISS
END SUBROUTINE BIASCOR_ODB
END INTERFACE
