INTERFACE
SUBROUTINE BRI2ACCONV(YDML_PHY_MF,YDEGEO,&
 & KIDIA,KFDIA,&
 & KLON,KLEV,&
 & PGM,PAPRSF,PZZF,&
 & PT,PRV,PRC,PRI,PRHOREF,&
 & PU,PV,PW,&
 & PMF,PTTEN,PRVTEN,PRCTEN,PRITEN,&
 & PPRTEN,PPRSTEN) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMGEO , ONLY : TEGEO
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
TYPE(TEGEO), INTENT(IN) :: YDEGEO
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PZZF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHOREF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRVTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRCTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRITEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPRTEN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPRSTEN(KLON)
END SUBROUTINE BRI2ACCONV
END INTERFACE
