INTERFACE
SUBROUTINE BRPTOB(YDGEOMETRY,PPSP,PSPT,PSPTALLG)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPSP(:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT(:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPTALLG(:,:)
END SUBROUTINE BRPTOB
END INTERFACE
