INTERFACE
SUBROUTINE BTEMDUP(ROBHDR, KLEN)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
END SUBROUTINE BTEMDUP
END INTERFACE
