INTERFACE
SUBROUTINE CABINE(YDDIMV,PHI,PHU,PRESF,KPOS)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE QAPASS , ONLY : JPNVS
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
REAL(KIND=JPRB), DIMENSION(JPNVS) ,INTENT(IN) :: PHI
REAL(KIND=JPRB), DIMENSION(JPNVS) ,INTENT(IN) :: PHU
REAL(KIND=JPRB), DIMENSION(YDDIMV%NFLEVG),INTENT(IN) :: PRESF
INTEGER(KIND=JPIM),INTENT(IN) :: KPOS
END SUBROUTINE CABINE
END INTERFACE
