INTERFACE
SUBROUTINE CABOTU (PLAT,PLON,KBOITE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
INTEGER(KIND=JPIM),INTENT(INOUT) :: KBOITE
END SUBROUTINE CABOTU
END INTERFACE
