INTERFACE
SUBROUTINE CACHBU( PLAT , PLON , PDIST , KNUMB , KLNBB )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE QAPABO , ONLY : NBONLA ,NBONLO ,NBONBT ,NBONBU
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
REAL(KIND=JPRB) ,INTENT(IN) :: PDIST
INTEGER(KIND=JPIM),INTENT(OUT) :: KNUMB(NBONBT)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KLNBB
END SUBROUTINE CACHBU
END INTERFACE
