INTERFACE
SUBROUTINE CACLSST(YDGEOMETRY,YDSURF,YDPHY1)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHY1 , ONLY : TPHY1
USE MPL_MODULE
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TPHY1) ,INTENT(INOUT) :: YDPHY1
END SUBROUTINE CACLSST
END INTERFACE
