INTERFACE
SUBROUTINE CADAVR(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDVARBC,YDODB,YGOM5)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE SUPERGOM_CLASS, ONLY : CLASS_SUPERGOM
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CLASS_VARBC),INTENT(INOUT) :: YDVARBC
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
TYPE(CLASS_SUPERGOM),INTENT(INOUT) :: YGOM5
END SUBROUTINE CADAVR
END INTERFACE
