INTERFACE
SUBROUTINE CAEINCW(YDGEOMETRY,YDSURF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
END SUBROUTINE CAEINCW
END INTERFACE
