INTERFACE
SUBROUTINE CAHUAX(ROBHDR,ROBODY,YDVAB,YDDIMV,YDPHY,KPROMA,KNBPT,KTASK,PTT,PQT,PSFL,PSFLN,POLDT,&
 & PGELAT,PGELAM,PMORO,PMLSM,PCAGUE,PESIG,PSGHUM) 
USE YOMVERT , ONLY : TVAB
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY , ONLY : TPHY
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TPHY) ,INTENT(INOUT) :: YDPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KNBPT
INTEGER(KIND=JPIM),INTENT(IN) :: KTASK
REAL(KIND=JPRB) ,INTENT(IN) :: PTT(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQT(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSFL(KNBPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSFLN(KNBPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: POLDT(KNBPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PMORO(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PMLSM(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAGUE(2,KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PESIG(2*YDDIMV%NFLEVG+5,KNBPT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSGHUM(YDDIMV%NFLEVG,KNBPT)
END SUBROUTINE CAHUAX
END INTERFACE
