INTERFACE
SUBROUTINE CALIFE(YDGEOMETRY,YDRIP,KREP1,KREP2)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(INOUT) :: KREP1
INTEGER(KIND=JPIM),INTENT(INOUT) :: KREP2
END SUBROUTINE CALIFE
END INTERFACE
