INTERFACE
SUBROUTINE CALINCW(YDGEOMETRY,YDSURF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE MPL_MODULE
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
END SUBROUTINE CALINCW
END INTERFACE
