INTERFACE
SUBROUTINE CALLPARAD(YDGEOMETRY,YDSURF,YDMODEL,YDCST,YDTHF,KIDIA,KFDIA,KLON,KSMAX,KLEVS,KTILES,&
 & KSTGLO,&
 & KTDIA,KLEV,KSTART,KIBL,KSTEP,LDRAIN1D,&
 & PT5 , PQ5, PGFL5,&
 & PU5 , PV5 , PVERVEL5,&
 & PRS15 , PRSF15,&
 & PAPRS5 , PAPRSF5, PDELP5,&
 & PAPHI5 , PAPHIF5,&
 & PEMTD5 , PTRSO5 , PMU0, PMU0M, PGAW,&
 & PSNS5 , PTSA5 , PWL5, PTL5,&
 & PWSA5 , PTIA5,&
 & PASN5 , PRSN5 , PTSN5,&
 & PHSTD , PHSDFOR, PGAMMA,&
 & PTHETA , PSIG,&
 & PLSM , PALBF ,&
 & PALCOEFF,&
 & PEMISF,&
 & PCVL , PCVH , PTVL , PTVH ,&
 & PLAILC , PLAIHC ,&
 & PSOTY , PCI , PSST,&
 & PGZ0MCL ,PLZ0HCL,&
 & PSD_VF5, PGZ0M5 , PLZ0H5,&
 & PUCFL5, PVCFL5, PTCFL5, PDCFL5, PQCFL5, PU10N5, PV10N5,&
 & PTENT5 , PTENQ5, PTENGFL5,&
 & PTENU5 , PTENV5,&
 & PNTOP , PNBAS , PACPR5,&
 & PUSTRTI5, PVSTRTI5, PAHFSTI5,PEVAPTI5 ,PTSKTI5,&
 & PT , PQ , PGFL,&
 & PU , PV , PVERVEL,&
 & PL , PI , PA ,&
 & PRS1 , PRSF1,&
 & PAPRS , PAPRSF , PDELP,&
 & PAPHI , PAPHIF,&
 & PTSA , PTL,&
 & PWSA , PTIA , PTSN, PII0,&
 & PTENT , PTENQ, PTENGFL,&
 & PTENU , PTENV,&
 & PACPR , PACCPR, PACCPR3,&
 & PUSTRTI, PVSTRTI, PAHFSTI,PEVAPTI ,PTSKTI,&
 & PHYS_MWAVE,&
 & PDIFTQ , PDIFTS , PSTRTU , PSTRTV,&
 & PGZ0M , PLZ0H,&
 & PUCFL, PVCFL, PTCFL, PDCFL, PQCFL, PU10N, PV10N,&
 & PTSAE1 , PTLE1, PTIAE1, PTSNE1,&
 & PGPHIST, PTRAJ_PHYS_TLAD,YDACV) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMCST , ONLY : TCST
USE YOETHF , ONLY : TTHF
USE YOMSPHYHIST , ONLY : SPHYS_HIST_TYPE
USE YOMTRAJ , ONLY : TRAJ_PHYS_TLAD_TYPE
USE YOE_PHYS_MWAVE , ONLY : N_PHYS_MWAVE
USE TYPE_ACV , ONLY : ACV_CONTAINER
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TTHF) ,INTENT(IN) :: YDTHF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KIBL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
LOGICAL ,INTENT(IN) :: LDRAIN1D
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL5(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRS15(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSF15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEMTD5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRSO5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0M(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSA5(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PWL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSA5(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTIA5(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PASN5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSN5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSN5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHSTD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHSDFOR(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGAMMA(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTHETA(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSIG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PALCOEFF(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMISF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCVL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCVH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTVL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTVH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAILC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAIHC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOTY(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSST(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGZ0MCL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLZ0HCL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VF5(KLON,YDSURF%YSD_VFD%NDIM5)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGZ0M5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLZ0H5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENGFL5(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNTOP(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNBAS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PACPR5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFSTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHYS_MWAVE(KLON,KLEV,N_PHYS_MWAVE)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUCFL5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCFL5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTCFL5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCFL5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCFL5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU10N5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10N5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSA(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSN(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTIA(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWSA(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PII0
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENGFL(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PACPR(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PACCPR(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PACCPR3(KLON,YDMODEL%YRML_GCONF%YRRIP%NSTOP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFSTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFTQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFTS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUCFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTCFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU10N(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10N(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGZ0M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTLE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSNE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSAE1(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTIAE1(KLON,KLEVS)
TYPE (SPHYS_HIST_TYPE),INTENT(INOUT) :: PGPHIST
TYPE (TRAJ_PHYS_TLAD_TYPE), INTENT(IN) :: PTRAJ_PHYS_TLAD
TYPE(ACV_CONTAINER),INTENT(INOUT),OPTIONAL :: YDACV
END SUBROUTINE CALLPARAD
END INTERFACE
