INTERFACE
SUBROUTINE CAMERA (KASELS, KOSELS, PDSELS, PDIFORO, PDIFLSM, KNSELS, PCOVAR, PCOREL,&
 & PCORMIN, KNM, KNIN, KNLX, KNBPV, KNOUT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE QAPABL , ONLY : JPKZMA
USE QAPAVU , ONLY : JPNVY
INTEGER(KIND=JPIM),INTENT(IN) :: KNIN
INTEGER(KIND=JPIM),INTENT(IN) :: KNLX
INTEGER(KIND=JPIM),INTENT(IN) :: KNBPV
INTEGER(KIND=JPIM),INTENT(INOUT) :: KASELS(JPNVY,JPKZMA)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KOSELS(JPNVY,JPKZMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSELS(JPNVY,JPKZMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFORO(JPNVY,JPKZMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFLSM(JPNVY,JPKZMA)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KNSELS(JPNVY)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOVAR(KNIN,KNLX*KNBPV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOREL(KNIN,KNLX*KNBPV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCORMIN
INTEGER(KIND=JPIM),INTENT(IN) :: KNM(KNLX)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNOUT
END SUBROUTINE CAMERA
END INTERFACE
