INTERFACE
SUBROUTINE CANALI(YDDIMV,YDSURF,YDEGEO)
USE YOMDIMV , ONLY : TDIMV
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YEMGEO , ONLY : TEGEO
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TEGEO), INTENT(IN) :: YDEGEO
END SUBROUTINE CANALI
END INTERFACE
