INTERFACE
SUBROUTINE CAOHIS(YDGEOMETRY,YDRIP,LDACT,KREP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
LOGICAL ,INTENT(IN) :: LDACT
INTEGER(KIND=JPIM),INTENT(OUT) :: KREP
END SUBROUTINE CAOHIS
END INTERFACE
