INTERFACE
SUBROUTINE CAPESHEAR(YDVAB,KPROMA,KST,KND,KFLEVG,&
 & PRESH,PRESF,PU,PV,PCAPE,&
 & PCAPES) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMVERT , ONLY : TVAB
TYPE(TVAB) ,INTENT(IN) :: YDVAB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KND
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPES(KPROMA)
END SUBROUTINE CAPESHEAR
END INTERFACE
