INTERFACE
SUBROUTINE CAPREDI(KNVYS, KNVYE, KPOS, KNLYJ, KNYJ)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE VARNO_MODULE, ONLY : NVNUMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KPOS
INTEGER(KIND=JPIM),INTENT(IN) :: KNVYS(NVNUMAX)
INTEGER(KIND=JPIM),INTENT(IN) :: KNVYE(KPOS)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNLYJ
INTEGER(KIND=JPIM),INTENT(INOUT) :: KNYJ(NVNUMAX)
END SUBROUTINE CAPREDI
END INTERFACE
