INTERFACE
SUBROUTINE CARCFO(YDODB,YDGEOMETRY)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE DBASE_MOD, ONLY : DBASE
CLASS(DBASE), INTENT(INOUT) :: YDODB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
END SUBROUTINE CARCFO
END INTERFACE
