INTERFACE
SUBROUTINE CASELA ( ROBHDR, ROBODY, KTASK, LDFLAI, KNLX, KNM, PCORMIN,&
 & PLAT, PLON, PRESS, PSIG, KNBPV, KIV, KASELS,KOSELS,PDSELS,&
 & PDIFORO, PDIFLSM, KNSELS, PDXMB, KNIN, KNOUT, YDCOST ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE QAPABL , ONLY : JPNPM ,JPKZMA
USE QAPAVU , ONLY : JPNVX ,JPNVY
USE QACOST , ONLY : TYPE_QACOST
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KNLX
INTEGER(KIND=JPIM),INTENT(IN) :: KNBPV
INTEGER(KIND=JPIM),INTENT(IN) :: KTASK
LOGICAL ,INTENT(IN) :: LDFLAI(JPNVX)
INTEGER(KIND=JPIM),INTENT(IN) :: KNM(KNLX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCORMIN
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
REAL(KIND=JPRB) ,INTENT(IN) :: PRESS(KNBPV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIG(JPNVX,KNBPV)
INTEGER(KIND=JPIM),INTENT(IN) :: KIV
INTEGER(KIND=JPIM),INTENT(INOUT) :: KASELS(JPNVY,JPKZMA)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KOSELS(JPNVY,JPKZMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSELS(JPNVY,JPKZMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFORO(JPNVY,JPKZMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFLSM(JPNVY,JPKZMA)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KNSELS(JPNVY)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDXMB(JPNPM,KNLX,KNBPV*2)
INTEGER(KIND=JPIM),INTENT(IN) :: KNIN
INTEGER(KIND=JPIM),INTENT(INOUT) :: KNOUT
TYPE(TYPE_QACOST) ,INTENT(IN) :: YDCOST
END SUBROUTINE CASELA
END INTERFACE
