INTERFACE
SUBROUTINE CASGVA (ROBHDR,KTYPA,PDISTR,KMXGSL,KMXGQ,PLAT,PLON,PMORO,PMLSM,KH,KTSK)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE PARDIMO , ONLY : JPNOTP
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPA
INTEGER(KIND=JPIM),INTENT(IN) :: KH
REAL(KIND=JPRB) ,INTENT(IN) :: PDISTR(JPNOTP)
INTEGER(KIND=JPIM),INTENT(IN) :: KMXGSL(JPNOTP)
INTEGER(KIND=JPIM),INTENT(IN) :: KMXGQ(JPNOTP)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KH)
REAL(KIND=JPRB) ,INTENT(IN) :: PMORO(KH)
REAL(KIND=JPRB) ,INTENT(IN) :: PMLSM(KH)
INTEGER(KIND=JPIM),INTENT(IN) :: KTSK
END SUBROUTINE CASGVA
END INTERFACE
