INTERFACE
SUBROUTINE CASGRA (ROBHDR,KTYPA,KTYPO,KNBPH,KTSK,PLAT,PLON,PMORO,PMLSM,PDISTR,KMXGSL)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPA
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPO
INTEGER(KIND=JPIM),INTENT(IN) :: KNBPH
INTEGER(KIND=JPIM),INTENT(IN) :: KTSK
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KNBPH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KNBPH)
REAL(KIND=JPRB) ,INTENT(IN) :: PMORO(KNBPH)
REAL(KIND=JPRB) ,INTENT(IN) :: PMLSM(KNBPH)
REAL(KIND=JPRB) ,INTENT(IN) :: PDISTR
INTEGER(KIND=JPIM),INTENT(OUT) :: KMXGSL
END SUBROUTINE CASGRA
END INTERFACE
