INTERFACE
SUBROUTINE CASND1(KLOC,KTOT,KDIM,KTAI)
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLOC(KDIM)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTOT(KDIM)
INTEGER(KIND=JPIM),INTENT(IN) :: KTAI
END SUBROUTINE CASND1
END INTERFACE
