INTERFACE
SUBROUTINE CASPIA(ROBODY,KANTY,LDFLAJ,PDELTA,PDELPI,PRESS,PPHAUT,PPBAS,KH,KTASK,&
 & KMXSELG,KMXWAG,KALLWAG,KASELS,KOSELS,PDSELS,PDIFORO,PDIFLSM,KNSELS,KNOUT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE QAPABL , ONLY : JPKZMA
USE QAPAVU , ONLY : JPNVY
USE PARDIMO , ONLY : JPNOTP
USE VARNO_MODULE, ONLY : VARNO, NVNUMAX
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KANTY
INTEGER(KIND=JPIM),INTENT(IN) :: KH
LOGICAL ,INTENT(IN) :: LDFLAJ(NVNUMAX)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELTA(JPNOTP)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELPI
REAL(KIND=JPRB) ,INTENT(IN) :: PRESS(KH)
REAL(KIND=JPRB),INTENT(IN) :: PPBAS(JPNOTP,KH), PPHAUT(JPNOTP,KH)
INTEGER(KIND=JPIM),INTENT(IN) :: KTASK
INTEGER(KIND=JPIM),INTENT(IN) :: KMXSELG
INTEGER(KIND=JPIM),INTENT(IN) :: KMXWAG
INTEGER(KIND=JPIM),INTENT(IN) :: KALLWAG
INTEGER(KIND=JPIM),INTENT(OUT) :: KASELS(JPNVY,JPKZMA,KH)
INTEGER(KIND=JPIM),INTENT(OUT) :: KOSELS(JPNVY,JPKZMA,KH)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDSELS(JPNVY,JPKZMA,KH)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFORO(JPNVY,JPKZMA,KH)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFLSM(JPNVY,JPKZMA,KH)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNSELS(JPNVY,KH)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNOUT(KH)
END SUBROUTINE CASPIA
END INTERFACE
