INTERFACE
SUBROUTINE CAT2AS(ROBHDR,ROBODY,YDDIMV,YDSURF,KPROMA,KNBPT,KTASK,PSLN,PT2INC,PSP_CI,&
 & PESIG,PCAGUE,PGELAT,PGELAM,PMORO,PMLSM) 
USE YOMDIMV , ONLY : TDIMV
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KNBPT
INTEGER(KIND=JPIM),INTENT(IN) :: KTASK
REAL(KIND=JPRB) ,INTENT(IN) :: PSLN(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PT2INC(KNBPT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP_CI(KPROMA,YDSURF%YSP_CID%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PESIG(2*YDDIMV%NFLEVG+5,KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAGUE(2,KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PMORO(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PMLSM(KNBPT)
END SUBROUTINE CAT2AS
END INTERFACE
