INTERFACE
SUBROUTINE CAUPFLG(KBUFR,KDIM)
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(INOUT) :: KBUFR(KDIM)
END SUBROUTINE CAUPFLG
END INTERFACE
