INTERFACE
SUBROUTINE CAV1AS(ROBHDR,ROBODY,YDDIMV,YDSURF,KPROMA,KNBPT,KTASK,PSLN,PSP_CI,PESIG,PCAGUE,&
 & PGELAT,PGELAM,PMORO,PMLSM,PGNORDL,PGNORDM,PGM) 
USE YOMDIMV , ONLY : TDIMV
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KNBPT
INTEGER(KIND=JPIM),INTENT(IN) :: KTASK
REAL(KIND=JPRB) ,INTENT(IN) :: PSLN(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP_CI(KPROMA,YDSURF%YSP_CID%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PESIG(2*YDDIMV%NFLEVG+5,KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAGUE(2,KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PMORO(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PMLSM(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGNORDL(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGNORDM(KNBPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KNBPT)
END SUBROUTINE CAV1AS
END INTERFACE
