INTERFACE
SUBROUTINE CAVISO( YDODB, KSY , KAI , KSB , KDR , KTP , KPL , KST )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE DBASE_MOD, ONLY : DBASE
CLASS(DBASE), INTENT(INOUT) :: YDODB
INTEGER(KIND=JPIM),INTENT(IN) :: KSY
INTEGER(KIND=JPIM),INTENT(IN) :: KAI
INTEGER(KIND=JPIM),INTENT(IN) :: KSB
INTEGER(KIND=JPIM),INTENT(IN) :: KDR
INTEGER(KIND=JPIM),INTENT(IN) :: KTP
INTEGER(KIND=JPIM),INTENT(IN) :: KPL
INTEGER(KIND=JPIM),INTENT(IN) :: KST
END SUBROUTINE CAVISO
END INTERFACE
