INTERFACE
SUBROUTINE CCLOUD ( YDEPHLI,YDECLD,KIDIA , KFDIA , KLON , KLEV,&
 & KBASECM, KTOPCM,&
 & PAPM1 , PARPRCM,&
 & PQM1 , PQS , PTM1 , PVERVEL,&
 & PCC , PCH , PCL , PCM,&
 & PCLC , PCT , PQIWP , PQLWP ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOECLD , ONLY : TECLD
USE YOEPHLI , ONLY : TEPHLI
TYPE(TECLD) ,INTENT(INOUT) :: YDECLD
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KBASECM(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTOPCM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PARPRCM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCH(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCM(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQIWP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQLWP(KLON,KLEV)
END SUBROUTINE CCLOUD
END INTERFACE
