INTERFACE
SUBROUTINE CDSTA(YDGEOMETRY,YDMTRAJ,YDGFL,YDML_GCONF,YDSPEC,YDVARBC,YDTCV)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MTRAJ_MOD , ONLY : MTRAJ
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_MOD , ONLY : TOVSCV
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT) :: YDML_GCONF
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSPEC
TYPE(CLASS_VARBC) ,INTENT(INOUT),OPTIONAL :: YDVARBC
TYPE(TOVSCV) ,INTENT(INOUT), OPTIONAL :: YDTCV
END SUBROUTINE CDSTA
END INTERFACE
