INTERFACE
SUBROUTINE CENSCOV3(YD_INTERP,YDCV,YDSPEC)
 USE JB_CONTROL_VECTORS_BASE_MOD
 USE SPECTRAL_FIELDS_MOD
 USE INTERPOLATOR_MOD, ONLY : T_INTERPOL, INTERPOLATOR_INTERPOLATE_FIELDS
 USE YOMENSCOV
 TYPE(T_INTERPOL) , INTENT(INOUT) :: YD_INTERP
 TYPE(JB_CONTROL_VECTOR), INTENT(IN) :: YDCV
 TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSPEC
END SUBROUTINE CENSCOV3
END INTERFACE
