INTERFACE
SUBROUTINE CF_DIGITAL(&
 & K__SENSOR,&
 & K__BAND,&
 & K__NUMCHANS,&
 & P__DBT,&
 & K__INDEX,&
 & K__CHAN_HIGH,&
 & K__CHAN_LOW,&
 & K__CHAN_WINDOWS,&
 & K__WINDOW_WIDTH,&
 & K__CLOUD_FLAG,&
 & K__CLOUD_LEVEL,&
 & K__CLEAR_LEVEL,&
 & K__IMAGER_FLAG) 
USE PARKIND1, ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K__SENSOR
INTEGER(KIND=JPIM),INTENT(IN) :: K__BAND
INTEGER(KIND=JPIM),INTENT(IN) :: K__NUMCHANS
REAL(KIND=JPRB), INTENT(IN) :: P__DBT(K__NUMCHANS)
INTEGER(KIND=JPIM),INTENT(IN) :: K__INDEX(K__NUMCHANS)
INTEGER(KIND=JPIM),INTENT(IN) :: K__WINDOW_WIDTH
INTEGER(KIND=JPIM),INTENT(IN) :: K__CHAN_HIGH
INTEGER(KIND=JPIM),INTENT(IN) :: K__CHAN_LOW
INTEGER(KIND=JPIM),INTENT(IN) :: K__CHAN_WINDOWS(2)
INTEGER(KIND=JPIM),INTENT(INOUT) :: K__CLOUD_FLAG(K__NUMCHANS)
INTEGER(KIND=JPIM),INTENT(OUT) :: K__CLOUD_LEVEL
INTEGER(KIND=JPIM),INTENT(OUT) :: K__CLEAR_LEVEL
INTEGER(KIND=JPIM),INTENT(IN) :: K__IMAGER_FLAG
END SUBROUTINE CF_DIGITAL
END INTERFACE
