INTERFACE
SUBROUTINE CH4_TCMR_AD&
 & (KFLEVG, KDLEN , KLEN , KDCOUNT, KCOUNT,&
 & PPRESH, PPRESF,&
 & YDGP_AD,&
 & PPRESH5, PPRESF5, PSOLEL,&
 & YDGP5,&
 & PCH4MEAN) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG, KDLEN, KLEN, KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KCOUNT(KDLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRESH5(KDLEN,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRESF5(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPRESH(KDLEN,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRESF(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOLEL(KDLEN)
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
TYPE (TYPE_GOM_PLUS),INTENT(INOUT) :: YDGP_AD
REAL(KIND=JPRB), INTENT(INOUT) :: PCH4MEAN(KDLEN,KDCOUNT)
END SUBROUTINE CH4_TCMR_AD
END INTERFACE
