INTERFACE
SUBROUTINE CHECKRSDRIFT(KLEN, CDIDENTI, POBLON, POBLAT, POBTIM, LDFLAG)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
INTEGER(KIND=JPIM), INTENT(IN) :: KLEN
CHARACTER (LEN=8), INTENT(IN) :: CDIDENTI
REAL(KIND=JPRB), INTENT(IN) :: POBLAT(:)
REAL(KIND=JPRB), INTENT(IN) :: POBLON(:)
REAL(KIND=JPRB), INTENT(IN) :: POBTIM(:)
LOGICAL, INTENT(OUT) :: LDFLAG(:)
END SUBROUTINE CHECKRSDRIFT
END INTERFACE
