INTERFACE
SUBROUTINE CHECKINCLIM(YDNAMFPSCI,KPROMA,YDSURF,KEND,POROG,PSD_VX,PSD_VV)
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMFPC , ONLY : TNAMFPSCI
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
TYPE(TSURF) ,INTENT(IN) :: YDSURF
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VX(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VV(:,:)
END SUBROUTINE CHECKINCLIM
END INTERFACE
