INTERFACE
SUBROUTINE CHECKAIRPOS(ROBHDR,KPATH,KNOAIR,KIDAIR,KMAX,KIDPAI)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KIDAIR
INTEGER(KIND=JPIM),INTENT(IN) :: KMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KPATH
INTEGER(KIND=JPIM),INTENT(IN) :: KNOAIR
INTEGER(KIND=JPIM),INTENT(IN) :: KIDPAI(KIDAIR,KMAX)
END SUBROUTINE CHECKAIRPOS
END INTERFACE
