INTERFACE
SUBROUTINE CHECK_SL_STRUCT(YDSL,CDSTR)
USE EINT_MOD, ONLY : SL_STRUCT
TYPE(SL_STRUCT),INTENT(INOUT) :: YDSL
CHARACTER(LEN=*),INTENT(IN) :: CDSTR
END SUBROUTINE CHECK_SL_STRUCT
END INTERFACE
