INTERFACE
SUBROUTINE CHEM_INEXT&
 & ( KIDIA , KFDIA , KLON , KLEV , KCHEM, KCEXTR, PDP, PTSTEP, PTENC1, PTENC0, PEXTRA, KTOP ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV, KCHEM, KCEXTR
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KTOP(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PDP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(IN) :: PTENC0(KLON,KLEV,KCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PTENC1(KLON,KLEV,KCHEM)
REAL(KIND=JPRB),INTENT(INOUT) :: PEXTRA(KLON,KCEXTR)
END SUBROUTINE CHEM_INEXT
END INTERFACE
