INTERFACE
 SUBROUTINE CHEM_DECAY&
 & (YGFL,KIDIA , KFDIA , KLON, KLEV, PTSTEP, PRSF1, PGELAT,&
 & PCEN ,PTENC) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA , KFDIA , KLON , KLEV
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(INOUT) :: PTENC(KLON,KLEV, YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PCEN(KLON,KLEV, YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON)
END SUBROUTINE CHEM_DECAY
END INTERFACE
