INTERFACE
 SUBROUTINE CHEM_RNPB&
 & (YGFL, KIDIA , KFDIA , KLON , KLEV , KTRAC,&
 & PTSTEP , PRSF1, PTP, PCEN ,&
 & PTENC) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL ,ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA , KFDIA , KLON , KLEV, KTRAC
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB),INTENT(OUT) :: PTENC(KLON,KLEV,KTRAC)
END SUBROUTINE CHEM_RNPB
END INTERFACE
