INTERFACE
SUBROUTINE CHEM_MOCAGE&
 & (YDMODEL,KSTEP, KIDIA, KFDIA, KLON, KLEV, KAERO,&
 & PTSTEP, PDELP, PRS1, PRSF1, PGEOH, PTP, PALB, PCSZA, PGELAT,&
 & PGEMU, PGELAM, PQP, PLP, PAP, PCEN, PTENC, PJOUT, PAEROP,&
 & CDMOCAGESCHEME) 
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM ,JPRB, JPRD
TYPE(MODEL), INTENT(INOUT)::YDMODEL
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP, KIDIA , KFDIA , KLON , KLEV, KAERO
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
REAL(KIND=JPRB), INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCEN(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(IN) :: PCSZA(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PALB(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PLP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PTENC(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(OUT) :: PJOUT(KLON,KLEV,5)
REAL(KIND=JPRB), INTENT(IN) :: PAEROP(KLON,KLEV,KAERO)
CHARACTER(LEN=*), INTENT(IN) :: CDMOCAGESCHEME
END SUBROUTINE CHEM_MOCAGE
END INTERFACE
