INTERFACE
SUBROUTINE CHEM_INITFLUX(YDSURF, YDMODEL,KIDIA, KFDIA, KLEV, KLON, KTRAC,&
 & GSD_VF, KAERO, KCHEM, LDINJ_CHEM, PCEN, PTENC, PCFLX, PDDVLC, PSCAV, PVOLCALTI,&
 & PCHEMDV, KFLDX , KLEVX, PGELAM, PGELAT,PTL, PRSF1L, PDELP, PAPHIF, PLSM, PINJF, POMFIRE, PCO2FIRE, PBLH, PEXTRA) 
USE TYPE_MODEL , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE SURFACE_VIEWS_MODULE, ONLY: SURFACE_VIEW_GROUP_VARSF
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVX
LOGICAL ,INTENT(IN) :: LDINJ_CHEM
TYPE(SURFACE_VIEW_GROUP_VARSF), INTENT(IN) :: GSD_VF
REAL(KIND=JPRB), INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB), INTENT(IN) :: POMFIRE(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PCO2FIRE(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PINJF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PBLH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB), INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB), INTENT(IN) :: PTL(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PRSF1L(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PVOLCALTI(KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PCFLX(KLON,KTRAC)
REAL(KIND=JPRB), INTENT(INOUT) :: PDDVLC(KLON,KTRAC)
REAL(KIND=JPRB), INTENT(INOUT) :: PSCAV(KTRAC)
REAL(KIND=JPRB), INTENT(INOUT) :: PCHEMDV(KLON,YDMODEL%YRML_GCONF%YGFL%NCHEM_DV)
REAL(KIND=JPRB),INTENT(INOUT), OPTIONAL :: PEXTRA(KLON,KLEVX,KFLDX)
INTEGER(KIND=JPIM), INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM), INTENT(IN) :: KCHEM(YDMODEL%YRML_GCONF%YGFL%NCHEM), KAERO(YDMODEL%YRML_GCONF%YGFL%NAERO)
END SUBROUTINE CHEM_INITFLUX
END INTERFACE
