INTERFACE
SUBROUTINE CHEM_NOYADV(YDGEOMETRY,YGFL,YDCHEM, KMODE,KCHEM_NOXADV,PGFL,PGFLT1)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMCHEM , ONLY : TCHEM
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE(TCHEM) ,INTENT(INOUT) :: YDCHEM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1,&
 & YDGEOMETRY%YRDIM%NGPBLKS) 
INTEGER(KIND=JPIM), INTENT(IN) :: KMODE
INTEGER(KIND=JPIM), INTENT(IN) :: KCHEM_NOXADV
END SUBROUTINE CHEM_NOYADV
END INTERFACE
