INTERFACE
 SUBROUTINE CHEM_MAIN&
 & (YDVAB,YDDIMV,YDMODEL,KIDIA , KFDIA , KLON, KLEV , KVCLIS, KTRAC, KCHEM ,&
 & PTSTEP, KGPLAT, KFLDX, KFLDX2 , KLEVX,&
 & PEXTRA , PEXTR2 ,PDELP, PRS1, PRSF1, PGEOH, PGEOF, PQP, PTP,&
 & PLP, PIP, PRP, PSP, PAP, PQSAT, PFPLCL, PFPLCN , PFPLSL , PFPLSN , PCOVPTOT,&
 & PALB, PWND, PLSM, PCSZA, PGELAT, PGELAM, PGEMU, PKOZO, PCFLX, PCFLXO, PDV, PGFL,&
 & PAEROC,PWETDIAM, PWETVOL, PND, PAERAOT, PAERAAOT, PAERASY,&
 & PTENGFL, PCEN ,PTENC,PNEEFLX, PCHEM2AER) 
USE TYPE_MODEL , ONLY : MODEL
USE YOMVERT , ONLY : TVAB
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE UKCA_MODE_SETUP, ONLY: NMODES
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA , KFDIA , KLON , KLEV, KVCLIS
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC, KLEVX, KFLDX, KFLDX2
INTEGER(KIND=JPIM),INTENT(IN) :: KCHEM(YDMODEL%YRML_GCONF%YGFL%NCHEM)
INTEGER(KIND=JPIM),INTENT(IN) :: KGPLAT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(INOUT) :: PEXTRA(KLON,KLEVX,KFLDX),PEXTR2(KLON,KFLDX2)
REAL(KIND=JPRB),INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGEOF(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PLP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PIP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PSP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCOVPTOT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCFLX(KLON,KTRAC)
REAL(KIND=JPRB),INTENT(IN) :: PCFLXO(KLON,KTRAC)
REAL(KIND=JPRB),INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB),INTENT(IN) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB),INTENT(IN) :: PCSZA(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PALB(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PWND(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PDV(KLON,YDMODEL%YRML_GCONF%YGFL%NCHEM_DV)
REAL(KIND=JPRB),INTENT(IN) :: PKOZO(KLON,KLEV,KVCLIS)
REAL(KIND=JPRB),INTENT(IN) :: PAEROC(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB),INTENT(IN) :: PWETDIAM(KLON,KLEV,NMODES)
REAL(KIND=JPRB),INTENT(IN) :: PWETVOL(KLON,KLEV,NMODES)
REAL(KIND=JPRB),INTENT(IN) :: PND(KLON,KLEV,NMODES)
REAL(KIND=JPRB),INTENT(IN) :: PAERAOT(KLON,KLEV,6)
REAL(KIND=JPRB),INTENT(IN) :: PAERAAOT(KLON,KLEV,6)
REAL(KIND=JPRB),INTENT(IN) :: PAERASY(KLON,KLEV,6)
REAL(KIND=JPRB),INTENT(IN) :: PGFL(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB),INTENT(IN) :: PTENGFL(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB),INTENT(IN) :: PNEEFLX(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PCHEM2AER(KLON,KLEV,4)
END SUBROUTINE CHEM_MAIN
END INTERFACE
