INTERFACE
 SUBROUTINE CHEM_TM5&
 & (YDVAB,YDDIMV,YDMODEL,KSTEP, KIDIA , KFDIA , KLON, KLEV ,KVCLIS,KAERO,&
 & PTSTEP ,PDELP, PRS1, PRSF1, PGEOH, PQP, PTP,&
 & PLP, PIP, PAP, PPTROPO, PALB, PWND, PLSM, PCSZA, PGELAT,&
 & PGELAM, PGEMU, PKOZO, PDV, PCEN , PTENC1, PBUDR, PBUDJ, PBUDX, POUT,&
 & PAEROP,PWETDIAM, PWETVOL,PND,PAERAOT, PAERAAOT, PAERASY) 
USE TYPE_MODEL , ONLY : MODEL
USE YOMVERT , ONLY : TVAB
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE TM5_CHEM_MODULE, ONLY : NREAC, IO3, ICH4, IHNO3,&
 & XMH2O, IACID, IAIR, IH2O, IO3S, INO, INO2,&
 & INO3_A, ISO4, INH3 , INH4, IMSA, IHO2, IOH, NBUD_EXTRA,&
 & KHO2L, KHO2_AER 
USE TM5_PHOTOLYSIS_NEW , ONLY : NPHOTO,NBANDS_TROP,NGRID
USE UKCA_MODE_SETUP, ONLY: NMODES
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP, KIDIA , KFDIA , KLON , KLEV, KVCLIS, KAERO
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT):: PTENC1(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB) ,INTENT(IN) :: PCEN(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB) ,INTENT(IN) :: PCSZA(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PPTROPO(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PALB(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PWND(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDV(KLON,YDMODEL%YRML_GCONF%YGFL%NCHEM_DV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKOZO(KLON,KLEV,KVCLIS)
REAL(KIND=JPRB) ,INTENT(OUT):: PBUDJ(KLON,KLEV,NPHOTO)
REAL(KIND=JPRB) ,INTENT(OUT):: PBUDR(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB) ,INTENT(OUT):: PBUDX(KLON,KLEV,NBUD_EXTRA)
REAL(KIND=JPRB) ,INTENT(OUT):: POUT(KLON,KLEV,5)
REAL(KIND=JPRB) ,INTENT(IN) :: PAEROP(KLON,KLEV,KAERO)
REAL(KIND=JPRB) ,INTENT(IN) :: PWETDIAM(KLON,KLEV,NMODES)
REAL(KIND=JPRB) ,INTENT(IN) :: PWETVOL(KLON,KLEV,NMODES)
REAL(KIND=JPRB) ,INTENT(IN) :: PND(KLON,KLEV,NMODES)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERAOT(KLON,KLEV,6)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERAAOT(KLON,KLEV,6)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERASY(KLON,KLEV,6)
END SUBROUTINE CHEM_TM5
END INTERFACE
