INTERFACE
 SUBROUTINE CHEM_BASCOETM5&
 & (YDDIMV, YDMODEL,KSTEP, KIDIA , KFDIA , KLON, KLEV , KAERO,&
 & PTSTEP, PDELP, PRS1, PRSF1, PGEOH, PQP, PTP,&
 & PLP, PIP, PAP, KLEVTROP, PALB, PWND, PLSM, PCSZA, PGELAT,&
 & PGELAM, PGEMU, PCEN , PTENC1,PBUDR, PBUDJ, PBUDX, POUT,&
 & PAEROP, PWETDIAM, PWETVOL,PND,PAERAOT, PAERAAOT, PAERASY) 
USE TYPE_MODEL , ONLY : MODEL
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE BASCOETM5_MODULE, ONLY : IO3, ICO, IH2O, ICO2, INO2, ICH4, ISTRATAER,&
 & INH3, INH4, INO3_A, ISO4, IMSA, IHO2, IOH,&
 & IN2O5, IHCL, IHOCL, ICLONO2,IHOBR, IHBR,IBRONO2, IHNO3,&
 & IAIR, IACID, NBC, BASCOE_BC,BASCOE_BCVAL,BASCOE_BCVAL_1750,BASCOE_BCVAL_1850,&
 & IN, INO 
USE TM5_CHEM_MODULE , ONLY : NREAC,NBUD_EXTRA, KHO2L, KHO2_AER
USE TM5_PHOTOLYSIS_NEW, ONLY : JO3D,JNO2,JH2O2,JHNO3,JHNO4,JN2O5,JACH2O,JBCH2O,JANO3,&
 & JBNO3,JO2,JMEPE, NPHOTO,NBANDS_TROP,NGRID 
USE UKCA_MODE_SETUP, ONLY: NMODES
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP, KIDIA , KFDIA , KLON , KLEV, KAERO
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PLP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PIP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PTENC1(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PCEN(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PCSZA(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVTROP(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PALB(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PWND(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PBUDJ(KLON,KLEV,NPHOTO)
REAL(KIND=JPRB),INTENT(OUT) :: PBUDR(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(OUT) :: PBUDX(KLON,KLEV,NBUD_EXTRA)
REAL(KIND=JPRB),INTENT(OUT) :: POUT(KLON,KLEV,5)
REAL(KIND=JPRB),INTENT(IN) :: PAEROP(KLON,KLEV,KAERO)
REAL(KIND=JPRB) ,INTENT(IN) :: PWETDIAM(KLON,KLEV,NMODES)
REAL(KIND=JPRB) ,INTENT(IN) :: PWETVOL(KLON,KLEV,NMODES)
REAL(KIND=JPRB) ,INTENT(IN) :: PND(KLON,KLEV,NMODES)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERAOT(KLON,KLEV,6)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERAAOT(KLON,KLEV,6)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERASY(KLON,KLEV,6)
END SUBROUTINE CHEM_BASCOETM5
END INTERFACE
