INTERFACE
SUBROUTINE CHEM_MAIN_LAYER(YDVAB,YDDIMV,YDSURF,&
 & YDMODEL,KDIM, PAUX, STATE, PDIAG, SURFL, FLUX, PGFL, PTENGFL,&
 & GEMSL, PSURF, PCHEM2AER) 
USE TYPE_MODEL , ONLY : MODEL
USE YOMVERT , ONLY : TVAB
USE YOMDIMV , ONLY : TDIMV
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHYDER , ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE, SURF_AND_MORE_TYPE,&
 & FLUX_TYPE, GEMS_LOCAL_TYPE, SURF_AND_MORE_LOCAL_TYPE, AUX_DIAG_TYPE 
TYPE(TVAB) , INTENT(IN) :: YDVAB
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT(IN) :: KDIM
TYPE (AUX_TYPE) , INTENT(IN) :: PAUX
TYPE (STATE_TYPE) , INTENT(IN) :: STATE
TYPE (AUX_DIAG_TYPE) , INTENT(IN) :: PDIAG
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(IN) :: SURFL
TYPE (FLUX_TYPE) , INTENT(IN) :: FLUX
REAL(KIND=JPRB) , INTENT(INOUT) :: PGFL(KDIM%KLON,KDIM%KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) , INTENT(IN) :: PTENGFL(KDIM%KLON,KDIM%KLEV,YDMODEL%YRML_GCONF%YGFL%NDIM1)
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (GEMS_LOCAL_TYPE) , INTENT(INOUT) :: GEMSL
REAL(KIND=JPRB) , INTENT(OUT) :: PCHEM2AER(KDIM%KLON,KDIM%KLEV,4)
END SUBROUTINE CHEM_MAIN_LAYER
END INTERFACE
