INTERFACE
SUBROUTINE CHEM_SCAV&
 & ( YDCHEM,YDECLDP,YDEDBUG,YGFL,KIDIA , KFDIA , KLON , KLEV , KCHEM , KCHEM_SCAV, KSTEP, PTSPHY,&
 & PRSF1, PDP , PTP, PFLXR, PFLXS, PCLCOV, PCLWAT, PCLICE, PRAIN, PSNOW, PCEN, PTENC0,&
 & PTENC1, PWLOSS, PPRCOV ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEDBUG , ONLY : TEDBUG
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOECLDP , ONLY : TECLDP
USE YOMCHEM , ONLY : TCHEM
TYPE(TCHEM) ,INTENT(INOUT):: YDCHEM
TYPE(TECLDP) ,INTENT(INOUT):: YDECLDP
TYPE(TEDBUG) ,INTENT(INOUT):: YDEDBUG
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV, KCHEM, KCHEM_SCAV, KSTEP
REAL(KIND=JPRB),INTENT(IN) :: PDP(KLON,KLEV) , PRSF1(KLON,KLEV) , PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCLCOV(KLON,KLEV) , PCLWAT(KLON,KLEV),PCLICE(KLON,KLEV) , PRAIN(KLON,KLEV), PSNOW(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL, INTENT(IN) :: PPRCOV(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PFLXR(KLON,KLEV+1), PFLXS(KLON,KLEV+1)
REAL(KIND=JPRB),INTENT(IN) :: PTENC0(KLON,KLEV,KCHEM), PCEN(KLON,KLEV,KCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(OUT) :: PWLOSS(KLON,KCHEM_SCAV), PTENC1(KLON,KLEV,KCHEM)
END SUBROUTINE CHEM_SCAV
END INTERFACE
