INTERFACE
SUBROUTINE CHEM_MASSDIA(YDGEOMETRY,YDGFL,YDSURF,YDML_GCONF,YDCOMPO,YDCHEM,YDDPHY,YDSPEC)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMCOMPO , ONLY : TCOMPO
USE YOMCHEM , ONLY : TCHEM, IEXTR_PH, IEXTR_WD, IEXTR_EM, IEXTR_NG, IEXTR_ROH, IEXTR_CH, IEXTR_CHTR, IEXTR_FE,&
 & IEXTR_ROH_TROP, IEXTR_DD, IEXTR_CHEMX,IEXTR_SDM, IEXTR_COND, IEXTR_NUC, IEXTR_RMOD 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL , ONLY : TGFL
USE YOMDPHY , ONLY : TDPHY
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TCOMPO) ,INTENT(IN) :: YDCOMPO
TYPE(TCHEM) ,INTENT(INOUT) :: YDCHEM
TYPE(TDPHY) ,INTENT(INOUT) :: YDDPHY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(SPECTRAL_FIELD),INTENT(IN) :: YDSPEC
END SUBROUTINE CHEM_MASSDIA
END INTERFACE
