INTERFACE
 SUBROUTINE CHEM_N2O&
 & (YDML_GCONF,YDEPHY,YDML_CHEM,YDPHY2,KSTEP, KIDIA , KFDIA , KLON, KLEV , KVCLIS,&
 & PTSTEP ,PDELP, PRS1, PRSF1, PGEOH, PTP, PKOZO,PPTROPO,&
 & PCSZA, PGELAT, PGELAM,&
 & PGEMU, PCEN , PTENC1, POUT) 
USE MODEL_CHEM_MOD , ONLY : MODEL_CHEM_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOEPHY , ONLY : TEPHY
USE YOMPHY2 , ONLY : TPHY2
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
TYPE(TEPHY) ,INTENT(INOUT):: YDEPHY
TYPE(MODEL_CHEM_TYPE),INTENT(INOUT):: YDML_CHEM
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TPHY2) ,INTENT(INOUT):: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP, KIDIA , KFDIA , KLON , KLEV, KVCLIS
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PPTROPO(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PKOZO(KLON,KLEV,KVCLIS)
REAL(KIND=JPRB),INTENT(OUT) :: PTENC1(KLON,KLEV,YDML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PCEN(KLON,KLEV,YDML_GCONF%YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(IN) :: PCSZA(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: POUT(KLON,KLEV,5)
END SUBROUTINE CHEM_N2O
END INTERFACE
