INTERFACE
SUBROUTINE CHK923(YDGEOMETRY,KNUM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KNUM
END SUBROUTINE CHK923
END INTERFACE
