INTERFACE
SUBROUTINE CHOLESKY(CDMODE, PU, PV, KN, PQ)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KN
CHARACTER(LEN=5), INTENT(IN) :: CDMODE
REAL(KIND=JPRB), INTENT(IN) :: PU(KN,KN)
REAL(KIND=JPRB), INTENT(IN) :: PV(KN)
REAL(KIND=JPRB), INTENT(OUT) :: PQ(KN)
END SUBROUTINE CHOLESKY
END INTERFACE
