INTERFACE
SUBROUTINE CLAERVIS&
 & ( KIDIA , KFDIA , KLON , KLEV,&
 & PCLAERS, PA, PL, PI, PR, PS , PRSF1 , PT ,&
 & PVISICL&
 & ) 
USE PARKIND1 , ONLY : JPIM , JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PA(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PL(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PI(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PS(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCLAERS(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PVISICL(KLON)
END SUBROUTINE CLAERVIS
END INTERFACE
