INTERFACE
SUBROUTINE CLDPPTL ( YDERDI,KIDIA , KFDIA , KLON , KLEV,&
 & PA5 , PL5 , PI5,&
 & PCLC5 , PQIWP5 , PQLWP5,&
 & PA , PL , PI,&
 & PCLC , PQIWP , PQLWP ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOERDI , ONLY : TERDI
TYPE(TERDI) ,INTENT(INOUT) :: YDERDI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(INOUT) :: PA5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PI5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCLC5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQIWP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQLWP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQIWP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQLWP(KLON,KLEV)
END SUBROUTINE CLDPPTL
END INTERFACE
