INTERFACE
SUBROUTINE CLDPRG_LAYER(YDSURF,&
 & YDMODEL,KDIM,PAUX,STATE,PSURF,PRAD) 
USE TYPE_MODEL , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_RAD_TYPE, AUX_TYPE,&
 & SURF_AND_MORE_TYPE 
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (AUX_RAD_TYPE) , INTENT(INOUT) :: PRAD
END SUBROUTINE CLDPRG_LAYER
END INTERFACE
