INTERFACE
SUBROUTINE CLIMAER_LAYER(YDSURF,YDML_PHY_RAD,YDPHY2,KDIM,LDPHYLIN,PAUX,STATE,PSURF,GEMSL)
USE MODEL_PHYSICS_RADIATION_MOD , ONLY : MODEL_PHYSICS_RADIATION_TYPE
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER , ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & SURF_AND_MORE_TYPE, GEMS_LOCAL_TYPE 
USE YOMPHY2 , ONLY : TPHY2
TYPE(TSURF) , INTENT (INOUT) :: YDSURF
TYPE(MODEL_PHYSICS_RADIATION_TYPE), INTENT (INOUT) :: YDML_PHY_RAD
TYPE(TPHY2) , INTENT (INOUT) :: YDPHY2
LOGICAL , INTENT (IN) :: LDPHYLIN
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (SURF_AND_MORE_TYPE) , INTENT (INOUT) :: PSURF
TYPE (GEMS_LOCAL_TYPE) , INTENT (INOUT) :: GEMSL
END SUBROUTINE CLIMAER_LAYER
END INTERFACE
