INTERFACE
SUBROUTINE CLOUDSC&
 & (YDECLDP,YDECUMF,YDEPHLI,YDERAD, YDEPHY,KIDIA, KFDIA, KLON, KLEV, KSPPN2D,&
 & PTSPHY,&
 & PT, PQ,&
 & TENDENCY_CML_T, TENDENCY_CML_Q, TENDENCY_CML_A, TENDENCY_CML_CLD,&
 & TENDENCY_TMP_T, TENDENCY_TMP_Q, TENDENCY_TMP_A, TENDENCY_TMP_CLD,&
 & TENDENCY_LOC_T, TENDENCY_LOC_Q, TENDENCY_LOC_A, TENDENCY_LOC_CLD,&
 & PVFA, PVFL, PVFI, PDYNA, PDYNL, PDYNI,&
 & PHRSW, PHRLW,&
 & PVERVEL, PAP, PAPH,&
 & PLSM, PGAW, LDCUM, KTYPE,&
 & PLU, PLUDE, PLUDELI, PSNDE, PMFU, PMFD, PGP2DSPP,&
 & LDSLPHY,&
 & PA,&
 & PCLV,&
 & PSUPSAT,&
 & PLCRIT_AER,PICRIT_AER,&
 & PRE_ICE,&
 & PCCN, PNICE,&
 & PCOVPTOT, PFSD, PRAINFRAC_TOPRFZ,&
 & PFSQLF, PFSQIF , PFCQNNG, PFCQLNG,&
 & PFSQRF, PFSQSF , PFCQRNG, PFCQSNG,&
 & PFSQLTUR, PFSQITUR ,&
 & PFPLSL, PFPLSN, PFHPSL, PFHPSN,&
 & PEXTRA, KFLDX) 
USE YOECLDP , ONLY : TECLDP, NCLDQV, NCLDQL, NCLDQR, NCLDQI, NCLDQS, NCLV
USE YOEPHLI , ONLY : TEPHLI
USE YOERAD , ONLY : TERAD
USE YOEPHY , ONLY : TEPHY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOECUMF , ONLY : TECUMF
TYPE(TECLDP) ,INTENT(INOUT) :: YDECLDP
TYPE(TECUMF) ,INTENT(INOUT) :: YDECUMF
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSPPN2D
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_CML_T(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_CML_Q(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_CML_A(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_CML_CLD(KLON,KLEV,NCLV)
REAL(KIND=JPRB) ,INTENT(OUT) :: TENDENCY_LOC_T(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: TENDENCY_LOC_Q(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: TENDENCY_LOC_A(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: TENDENCY_LOC_CLD(KLON,KLEV,NCLV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_TMP_T(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_TMP_Q(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_TMP_A(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: TENDENCY_TMP_CLD(KLON,KLEV,NCLV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVFA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVFL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVFI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDYNA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDYNL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDYNI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PHRSW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PHRLW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLUDELI(KLON,KLEV,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNDE(KLON,KLEV,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2DSPP(KLON,KSPPN2D)
LOGICAL ,INTENT(IN) :: LDSLPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLV(KLON,KLEV,NCLV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSUPSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLCRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PICRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE_ICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCCN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOVPTOT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAINFRAC_TOPRFZ(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSQLF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSQIF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQLNG(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQNNG(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSQRF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSQSF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQRNG(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQSNG(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSQLTUR(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSQITUR(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPSL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPSN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEXTRA(KLON,KLEV,KFLDX)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSD(KLON,KLEV)
END SUBROUTINE CLOUDSC
END INTERFACE
