INTERFACE
SUBROUTINE CO2_TCMR&
 & (KFLEVG, KDLEN , KLEN , KDCOUNT, KCOUNT,&
 & PPRESH, PPRESF, PSOLEL,&
 & YDGP5,&
 & PCO2MEAN ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG, KDLEN, KLEN, KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KCOUNT(KDLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRESH(KDLEN,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRESF(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOLEL(KDLEN)
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(OUT) :: PCO2MEAN(KDLEN,KDCOUNT)
END SUBROUTINE CO2_TCMR
END INTERFACE
