INTERFACE
SUBROUTINE CO2SLICING_ML(YDGP5,KPTNAV,KSENSOR,KEND,PPRES,PANGL,PANGLA,&
 & PANGS,PANGSA,KSURF,KSAT,KCHPF,KCHID,KNCHU,PROF,&
 & PT2SAT,PH2SAT,PPSSAT,PUSSAT,PVSSAT,PTSKIN,PCTOP,PCAMT,&
 & PEMIS,PTAU,POBS,PRADM,PTBM,PRADOV,&
 & PLAT,PLON,POROG,PCT,PEM,KTOPLEVELS) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDIMO , ONLY : NMXTCHU
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS
USE YOMSATS , ONLY : NJPPF,&
 & AIRSCHAN_BACK,&
 & IASICHAN_BACK 
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
INTEGER(KIND=JPIM), INTENT(IN) :: KPTNAV
REAL(KIND=JPRB), INTENT(IN), DIMENSION(YDGP5%NFLEVG+1,KEND) :: PPRES
INTEGER(KIND=JPIM), INTENT(IN) :: KEND
INTEGER(KIND=JPIM), INTENT(IN) :: KSENSOR
INTEGER(KIND=JPIM), INTENT(IN) :: KSAT
INTEGER(KIND=JPIM), INTENT(IN) :: KCHPF
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PANGL,PANGS
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PANGLA,PANGSA
INTEGER(KIND=JPIM), INTENT(IN), DIMENSION(NJPPF*NMXTCHU) :: KCHID
INTEGER(KIND=JPIM), INTENT(IN), DIMENSION(KEND) :: KSURF
INTEGER(KIND=JPIM), INTENT(IN), DIMENSION(KEND) :: KNCHU
REAL(KIND=JPRB), INTENT(IN), DIMENSION(YDGP5%NFLEVG+1,KPTNAV,KEND) :: PROF
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PT2SAT
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PH2SAT
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PPSSAT
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PUSSAT
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PVSSAT
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PCTOP
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PCAMT
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PTSKIN
REAL(KIND=JPRB),INTENT(IN), DIMENSION(NJPPF*NMXTCHU) :: PEMIS
REAL(KIND=JPRB), INTENT(IN), DIMENSION(YDGP5%NFLEVG+1,KCHPF) :: PTAU
REAL(KIND=JPRB),INTENT(IN), DIMENSION(NJPPF*NMXTCHU) :: POBS
REAL(KIND=JPRB), INTENT(IN), DIMENSION(NJPPF*NMXTCHU) :: PRADM
REAL(KIND=JPRB), INTENT(IN), DIMENSION(NJPPF*NMXTCHU) :: PTBM
REAL(KIND=JPRB), INTENT(IN), DIMENSION(YDGP5%NFLEVG+1,KCHPF) :: PRADOV
REAL(KIND=JPRB), INTENT(IN), DIMENSION(KEND) :: PLAT,PLON,POROG
INTEGER(KIND=JPIM), INTENT(IN) :: KTOPLEVELS
REAL(KIND=JPRB), INTENT(OUT), DIMENSION(KEND) :: PCT
REAL(KIND=JPRB), INTENT(OUT), DIMENSION(KEND) :: PEM
END SUBROUTINE CO2SLICING_ML
END INTERFACE
