INTERFACE
SUBROUTINE COBSALLTL(YDGEOMETRY,YDDIMACV,YGFL,YDPHY,YDROB,YDGMV,YDSURF,YDGOM,YDECVAR,YDPHYSMWAVE,&
 & PGFL,PGMV,PGMVS,PSD_VD,PSD_VN,LDGP_DONE,LDUPD_DONE,YDACV) 
USE YOMPHY , ONLY : TPHY
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE EINT_MOD , ONLY : SL_STRUCT
USE GOM_MOD , ONLY : TYPE_GOM, GOM_MAKE_PRE_INTERP, GOM_FINISH_PRE_INTERP,&
 & TYPE_PRE_INTERP_ACCESS, GOM_PRE_INTERP_ACCESS, GOM_SENDOBS_NUMBER 
USE YOMECTAB , ONLY : TECVAR
USE YOE_PHYS_MWAVE , ONLY : TEPHYSMWAVE
USE TYPE_ACV , ONLY : TACVDIM, ACV_CONTAINER
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TACVDIM) ,INTENT(IN) :: YDDIMACV
TYPE(TPHY) ,INTENT(INOUT) :: YDPHY
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDROB
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TYPE_GOM) ,INTENT(INOUT) :: YDGOM
TYPE(TECVAR) ,INTENT(IN) :: YDECVAR
TYPE(TEPHYSMWAVE), INTENT(IN) :: YDPHYSMWAVE
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VD(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VDD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VN(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VND%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
LOGICAL ,INTENT(IN) :: LDGP_DONE
LOGICAL , INTENT(IN) :: LDUPD_DONE
TYPE(ACV_CONTAINER),INTENT(IN) :: YDACV
END SUBROUTINE COBSALLTL
END INTERFACE
