INTERFACE
SUBROUTINE COD_OPTL(KFLEVG, KDLEN , KLEN , KMXCOUNT,YDGP_TL ,YDGP5,&
 & PCOD,PTAUC) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG, KDLEN, KLEN, KMXCOUNT
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP_TL
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOD(KDLEN,KMXCOUNT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTAUC(KDLEN,KFLEVG,KMXCOUNT)
END SUBROUTINE COD_OPTL
END INTERFACE
