INTERFACE
SUBROUTINE COMMSPNORM1(YDGEOMETRY,KFIELDSL,KFIELDSG,PMLOCAL,PMGLOBAL,KSMAX,KIOMASTER,&
 & KSETV,KLOC) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDSG
INTEGER(KIND=JPIM),INTENT(IN) :: KSMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PMLOCAL(KFIELDSL,YDGEOMETRY%YRDIM%NUMP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMGLOBAL(KFIELDSG,0:KSMAX)
INTEGER(KIND=JPIM),INTENT(IN) :: KIOMASTER
INTEGER(KIND=JPIM),INTENT(IN) :: KSETV(KFIELDSG)
INTEGER(KIND=JPIM),INTENT(IN) :: KLOC(KFIELDSG)
END SUBROUTINE COMMSPNORM1
END INTERFACE
