INTERFACE
SUBROUTINE COND_LAYER(&
 & YDECLDP,YDECND,YDEPHLI,YDPHY2,KDIM, PAUX, STATE, TENDENCY,&
 & FLUX, PDIAG,&
 & TENDENCY_LOC) 
USE YOECLDP , ONLY : TECLDP, NCLDQR, NCLDQS, NCLDQI, NCLDQL
USE YOECND , ONLY : TECND
USE YOEPHLI , ONLY : TEPHLI
USE YOMPHYDER, ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & FLUX_TYPE, MASK_GFL_TYPE, AUX_DIAG_TYPE 
USE YOMPHY2 , ONLY : TPHY2
TYPE(TECLDP) , INTENT(INOUT) :: YDECLDP
TYPE(TECND) , INTENT(INOUT) :: YDECND
TYPE(TEPHLI) , INTENT(INOUT) :: YDEPHLI
TYPE(TPHY2) , INTENT(INOUT) :: YDPHY2
TYPE (DIMENSION_TYPE), INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY_LOC
END SUBROUTINE COND_LAYER
END INTERFACE
