INTERFACE
SUBROUTINE CONGRAD_AD(YDSENS,KMAXIT,KITER,PWORK,YDCGLWK)
USE PARKIND1,ONLY: JPRB, JPIM
USE CONTROL_VECTORS_MOD
TYPE(CONTROL_VECTOR), INTENT(INOUT) :: YDSENS
INTEGER(KIND=JPIM), INTENT(IN) :: KMAXIT,KITER
REAL(KIND=JPRB), INTENT(IN) :: PWORK(KMAXIT+1,4)
TYPE(CONTROL_VECTOR), INTENT(IN) :: YDCGLWK(KMAXIT+1)
END SUBROUTINE CONGRAD_AD
END INTERFACE
