INTERFACE
SUBROUTINE CONVDDR(KFLAG,PDDRS,KDDR1,PDDR1,CDDR1,KDDR2,PDDR2,CDDR2)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCMDDR , ONLY : NLENCD1 ,NLEND1I ,NLEND1R ,NLEND1C ,&
 & NLENCD2 ,NLEND2I ,NLEND2R ,NLEND2C 
INTEGER(KIND=JPIM),INTENT(IN) :: KFLAG
REAL(KIND=JPRB),INTENT(INOUT) :: PDDRS(NLENCD1+NLENCD2)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KDDR1(NLEND1I)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDDR1(NLEND1R)
CHARACTER(LEN=NLEND1C),INTENT(INOUT) :: CDDR1
INTEGER(KIND=JPIM),INTENT(INOUT) :: KDDR2(NLEND2I)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDDR2(NLEND2R)
CHARACTER(LEN=NLEND2C),INTENT(INOUT) :: CDDR2
END SUBROUTINE CONVDDR
END INTERFACE
