INTERFACE
SUBROUTINE CONVECTION_S_LAYER(YDTHF, YDCST, YDSURF,&
 & YDERAD,YDML_PHY_SLIN,YDML_PHY_EC,YDPHY2,KDIM, LDSLPHY, LDRAIN1D, STATE, TENDENCY_CML, TENDENCY_TMP, PAUX, PVDIFTS,&
 & LLKEYS, PDIAG, AUXL, FLUX, PSURF, GEMSL,&
 & TENDENCY_LOC) 
USE MODEL_PHYSICS_ECMWF_MOD , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD , ONLY : TERAD
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMCST , ONLY : TCST
USE YOETHF , ONLY : TTHF
USE PARKIND1 ,ONLY : JPRB
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE, SURF_AND_MORE_TYPE,&
 & KEYS_LOCAL_TYPE, FLUX_TYPE, GEMS_LOCAL_TYPE 
USE YOMPHY2 , ONLY : TPHY2
TYPE(TTHF) ,INTENT(IN) :: YDTHF
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TERAD), INTENT(INOUT) :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE),INTENT(INOUT) :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT):: YDML_PHY_SLIN
TYPE(TPHY2) , INTENT(INOUT) :: YDPHY2
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
LOGICAL , INTENT (IN) :: LDSLPHY
LOGICAL , INTENT (IN) :: LDRAIN1D
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_CML
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_TMP
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
REAL(KIND=JPRB) , INTENT (IN) :: PVDIFTS
TYPE (KEYS_LOCAL_TYPE) , INTENT(INOUT) :: LLKEYS
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
TYPE (AUX_DIAG_LOCAL_TYPE), INTENT(INOUT) :: AUXL
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (GEMS_LOCAL_TYPE) , INTENT(INOUT) :: GEMSL
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY_LOC
END SUBROUTINE CONVECTION_S_LAYER
END INTERFACE
