INTERFACE
SUBROUTINE COORD_DTS(KX,KY,PLON,PLAT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) ::KX,KY
REAL(KIND=JPRB),INTENT(OUT) :: PLON(KX,KY),PLAT(KX,KY)
END SUBROUTINE COORD_DTS
END INTERFACE
