INTERFACE
SUBROUTINE COPY_SPA2SPEC(YDGEOMETRY,KS3D,KS2D,KS1D,PSP3D,PSP2D,PSP1D,YD_SPEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KS3D
INTEGER(KIND=JPIM),INTENT(IN) :: KS2D
INTEGER(KIND=JPIM),INTENT(IN) :: KS1D
REAL(KIND=JPRB) ,INTENT(IN) :: PSP3D(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2,KS3D)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP2D(YDGEOMETRY%YRDIM%NSPEC2,KS2D)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP1D(YDGEOMETRY%YRDIMV%NFLEVL,KS1D)
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YD_SPEC
END SUBROUTINE COPY_SPA2SPEC
END INTERFACE
