INTERFACE
SUBROUTINE COUPLNEMO(YDGEM,YDMCC,YDRIP,KSTEP)
USE YOMGEM , ONLY : TGEM
USE PARKIND1 , ONLY : JPRD, JPIM, JPRB
USE YOMRIP , ONLY : TRIP
USE YOMMCC , ONLY : TMCC
USE CPLNG
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TMCC) ,INTENT(INOUT):: YDMCC
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
END SUBROUTINE COUPLNEMO
END INTERFACE
