INTERFACE
SUBROUTINE CP_FORCING (YDGEOMETRY, YDMODEL, YDCPG_OPTS, YDCPG_BNDS, YDCPG_DYN0, YDCPG_TND, YDVARS, YDDDH)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMLSFORC
USE DDH_MIX , ONLY : ADD_FIELD_3D, NEW_ADD_FIELD_3D, TYP_DDH
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_DYN_TYPE, CPG_TND_TYPE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_DYN_TYPE) ,INTENT(IN) :: YDCPG_DYN0
TYPE(CPG_TND_TYPE) ,INTENT(INOUT) :: YDCPG_TND
TYPE(FIELD_VARIABLES) ,INTENT(IN) :: YDVARS
TYPE(TYP_DDH) ,INTENT(INOUT) :: YDDDH
END SUBROUTINE CP_FORCING
END INTERFACE
