INTERFACE
SUBROUTINE CPCHET(&
 & YDMF_PHYS, YDMF_PHYS_STATE, YDCPG_MISC,&
 & YDRIP,YDPHY,KPROMA, KSTART, KPROF, KFLEV, KTSNO,&
 & PFRMQ ,&
 & PCPS ,&
 & PTENDH , PTENDQ ,&
 & PTENDQI, PTENDQL, PTENDQR, PTENDQS,&
 & PGEMU , PGELAM ) 
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_MISC_TYPE
USE MF_PHYS_BASE_STATE_TYPE_MOD, ONLY : MF_PHYS_BASE_STATE_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRIP ,ONLY : TRIP
USE YOMPHY ,ONLY : TPHY
TYPE(MF_PHYS_TYPE),INTENT(INOUT) :: YDMF_PHYS
TYPE (MF_PHYS_BASE_STATE_TYPE),INTENT(IN) :: YDMF_PHYS_STATE
TYPE(CPG_MISC_TYPE),INTENT(INOUT):: YDCPG_MISC
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTSNO
REAL(KIND=JPRB) ,INTENT(IN) :: PFRMQ (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPS (KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDH (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQ (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQI(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQS(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU (KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM (KPROMA)
END SUBROUTINE CPCHET
END INTERFACE
