INTERFACE
SUBROUTINE CPCLIMI(YDCLIMO,YDNAMFPINT,YDNAMFPSCI,YDAFN,KFPXFLD,YDFPGEOMETRY,YDFPWSTD,YDFPSTRUCT,YDGEOMETRY,YDSURF,YDMODEL,&
 & KFLD,KOD,KORDER,PHALO,PFPOUT) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMFPC , ONLY : TNAMFPSCI, TNAMFPINT, LALLOFP
USE YOMWFPB , ONLY : TFPWSTD, TFPSUW
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMAFN , ONLY : TAFN
USE YOMFPGEOMETRY , ONLY : TFPGEOMETRY, LFPDISTRIB
USE TYPE_FPOSBUF , ONLY : FPOSBUF
TYPE(FPOSBUF) ,INTENT(IN) :: YDCLIMO
TYPE(TNAMFPINT) ,INTENT(IN) :: YDNAMFPINT
TYPE(TNAMFPSCI) ,INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN) ,INTENT(IN) :: YDAFN
INTEGER(KIND=JPIM),INTENT(IN) :: KFPXFLD
TYPE (TFPGEOMETRY),INTENT(IN) :: YDFPGEOMETRY
TYPE (TFPWSTD) ,INTENT(IN) :: YDFPWSTD
TYPE(SL_STRUCT) ,INTENT(IN) :: YDFPSTRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
INTEGER(KIND=JPIM),INTENT(IN) :: KOD (KFLD)
INTEGER(KIND=JPIM),INTENT(IN) :: KORDER(KFLD)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHALO(YDFPSTRUCT%NASLB1,KFLD)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPOUT(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA,KFLD,YDFPGEOMETRY%YFPGEO_DEP%NFPBLOCS)
END SUBROUTINE CPCLIMI
END INTERFACE
