INTERFACE
SUBROUTINE CPCLS_ASSIM(YDMODEL,YDCPG_OPTS, YDCPG_BNDS,&
 & YDMF_PHYS_SURF, YDMF_PHYS_OUT,&
 & PXUCLS, PXVCLS, PXNUCLS, PXNVCLS ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_OUT_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE TYPE_MODEL , ONLY : MODEL
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(CPG_OPTS_TYPE),INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE),INTENT(IN) :: YDCPG_BNDS
TYPE(MF_PHYS_SURF_TYPE),INTENT(IN) :: YDMF_PHYS_SURF
TYPE(MF_PHYS_OUT_TYPE),INTENT(IN):: YDMF_PHYS_OUT
REAL(KIND=JPRB) ,INTENT(IN) :: PXUCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PXVCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PXNUCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PXNVCLS(YDCPG_OPTS%KLON)
END SUBROUTINE CPCLS_ASSIM
END INTERFACE
