INTERFACE
SUBROUTINE CPCUDDH(YDML_DIAG,YDRIP,KPROMA, KSTART, KPROF, KFLEVG, KDDHI, PDHSF,&
 & PDHCV, PDHCS, LDDYN, LDPHY,KDHCVSU) 
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
TYPE(MODEL_DIAGNOSTICS_TYPE), INTENT(INOUT) :: YDML_DIAG
TYPE(TRIP) , INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM) , INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) , INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) , INTENT(IN) :: KPROF
INTEGER(KIND=JPIM) , INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM) , INTENT(IN) :: KDHCVSU
INTEGER(KIND=JPIM) , INTENT(IN) :: KDDHI(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PDHSF(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PDHCV(KPROMA,KDHCVSU*(KFLEVG+1))
REAL(KIND=JPRB) , INTENT(IN) :: PDHCS(KPROMA,YDML_DIAG%YRMDDH%NDHCSSU)
LOGICAL , INTENT(IN) :: LDDYN
LOGICAL , INTENT(IN) :: LDPHY
END SUBROUTINE CPCUDDH
END INTERFACE
