INTERFACE
SUBROUTINE CPCUDDH_OMP(YDMDDH,YDTDDH,KPROMA,KSTART,KPROF,KFLEVG,KDDHI,YDDDH,LDDYN)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMMDDH , ONLY : TMDDH
USE YOMTDDH , ONLY : TTDDH
USE DDH_MIX , ONLY : TYP_DDH
TYPE(TMDDH) ,INTENT(INOUT) :: YDMDDH
TYPE(TTDDH) ,INTENT(INOUT) :: YDTDDH
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KDDHI(KPROMA)
TYPE(TYP_DDH) ,INTENT(INOUT) :: YDDDH
LOGICAL ,INTENT(IN) :: LDDYN
END SUBROUTINE CPCUDDH_OMP
END INTERFACE
