INTERFACE
SUBROUTINE CPDYSLDIA(YDCST, YDVARS, YDCPG_DYN0, YDCPG_OPTS, YDCPG_BNDS, YDGEOMETRY,YDDPHY,YDML_GCONF,&
 & YDA_EXTRA) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCST , ONLY : TCST
USE YOMDPHY , ONLY : TDPHY
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD , ONLY : CPG_DYN_TYPE
USE ARRAY_FIELD_WRAPPER_MOD, ONLY : ARRAY_4D
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(FIELD_VARIABLES) ,INTENT(IN) :: YDVARS
TYPE(CPG_DYN_TYPE) ,INTENT(IN) :: YDCPG_DYN0
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDPHY) ,INTENT(IN) :: YDDPHY
TYPE(MODEL_GENERAL_CONF_TYPE) ,INTENT(IN) :: YDML_GCONF
TYPE(ARRAY_4D) ,INTENT(IN) :: YDA_EXTRA
END SUBROUTINE CPDYSLDIA
END INTERFACE
