INTERFACE
SUBROUTINE CPEDIA(YDVAB,YDECUMF,YDML_GCONF,KPROMA,KIDIA,KFDIA,KFLEVG,KSATSIM,&
 & LDFSTEP,LDMLPP,LDRS6,LDRSACC,LDACCRS,&
 & PGELAM ,PGELAT ,PFPLCL ,PFPLCN ,PFPLSL ,PFPLSN ,&
 & PFRSO ,PFRSOD ,PFRSODC,PFRTH ,PFRTHD ,PFRTHDC,PUVDF ,PPARF ,&
 & PCAPE ,PPARCF ,PTINCF ,PFDIR ,PDSRP ,PCDIR ,PCBASE,P0DEGL,PVISIH,&
 & PCIN ,PCONVIND,&
 & PLIGH_TOT ,PLIGH_CTG,&
 & PCBASEA,PCTOPC ,PZTWETB,&
 & PDIFTS ,PDIFTQ ,PSTRTU ,PSTRTV,&
 & PFCLL ,PFCLN ,PTCLS ,PQCLS ,PUCLS ,PVCLS ,&
 & PTRENU ,PQLINU ,PLSM ,PCI ,PISUND,&
 & PVDIS ,PVDISG ,PUSTRG,&
 & PVSTRG ,PRUISS ,PRUISP,&
 & PINEE ,PIGPP ,PIREC,&
 & PRESH ,PRESF ,PDELP,&
 & PU ,PV ,PT ,PQ ,PO3 ,PGHG ,PCHEM ,PAERO,&
 & PA ,PL ,PR ,PI ,PS ,PTENQ ,POROG,&
 & PDLSP ,PDCP ,PDSF ,PDFZRA ,PDBLD ,PSUND,&
 & PITTRC ,PITSRC ,PISTRC ,PISSRC ,PIES ,PISMLT,PI10FG, PILSPF,&
 & PPRECTYPE ,PFZRA ,PIVIMD ,PEVAPMU,&
 & PVTTRC ,PVTSRC ,PVSTRC ,PVSSRC ,PVES, PVSMLT, PV10FG, PV10FG6,PVI10FG,&
 & PVLSPF ,PVVIMD ,&
 & PDSSHF ,PDSLHF ,PDSP ,PDMSL ,&
 & PDSSR ,PDSTR ,PDSSRD ,PDSTRD ,PDSSRDC,PDSTRDC,PDTSR ,PDTTR,&
 & PDUVDF ,PDPARF ,PDCAPE ,PDCAPES,PDMXCAP6,PDMXCAPS6,&
 & PDPARCF,PDTINCF,PDFDIR,PDDSRP,PDCDIR,&
 & PDCBASE,PD0DEGL,PDVISIH,&
 & PDCIN ,PDKINDEX,PDTTINDEX,&
 & PDCBASEA,PDCTOPC, PDZTWETB0, PDZTWETB1,&
 & PDEWSS ,PDNSSS ,PDE ,PDPEV ,PDLGWS,&
 & PDMGWS ,PDGWD ,PDMX2T ,PDMN2T ,PDMX2T6,PDMN2T6,PDRO,PDSSRO,PDSRO,&
 & PDNEE ,PDGPP ,PDREC,&
 & PDCSF ,PDLSSF ,PDMXTPR ,PDMNTPR ,PDMXTPR6,PDMNTPR6,&
 & PDTPR ,PDLSRR ,PDCRR ,PDLSSFR,PDCSFR,PDPTYPE,PVILSPF,&
 & PDIEWSS,PDINSSS,PDISSHF,PDIE ,PDVIWVE,PDVIWVN,&
 & PDTCW ,PDTCWV ,PDTCLW ,PDTCIW ,PDTCRW ,PDTCSW ,PDTCSLW, PDTCO3,&
 & PDTCGHG,PDTCCHEM,PDTCAERO,&
 & PDLITOTI,PDLITOTA6,PDLICGI,PDLICGA6,&
 & PDCLBT ,PDCSBT) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMVERT , ONLY : TVAB
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOECUMF , ONLY : TECUMF
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KSATSIM
LOGICAL ,INTENT(IN) :: LDFSTEP
LOGICAL ,INTENT(IN) :: LDMLPP
LOGICAL ,INTENT(IN) :: LDRSACC
LOGICAL ,INTENT(IN) :: LDACCRS
LOGICAL ,INTENT(IN) :: LDRS6
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFZRA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSOD(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSODC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTHD(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTHDC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUVDF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPARF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPARCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTINCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCBASE(KPROMA), P0DEGL(KPROMA), PVISIH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCIN(KPROMA), PCONVIND(KPROMA,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PLIGH_TOT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLIGH_CTG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCBASEA(KPROMA), PCTOPC(KPROMA), PZTWETB(KPROMA,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PFDIR(KPROMA), PDSRP(KPROMA), PCDIR(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRENU(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLINU(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISUND(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDISG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUSTRG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSTRG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PINEE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PIGPP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PIREC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PO3(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PGHG(KPROMA,KFLEVG,YDML_GCONF%YGFL%NGHG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCHEM(KPROMA,KFLEVG,YDML_GCONF%YGFL%NCHEM_TC)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERO(KPROMA,KFLEVG,YDML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENQ(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PL(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PI(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PS(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLSP(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCP(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDFZRA(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDBLD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSUND(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PITTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PITSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PIES(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISMLT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PI10FG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PILSPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRECTYPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVAPMU(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PIVIMD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVTTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVTSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVES(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSMLT(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10FG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10FG6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVI10FG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVLSPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSSHF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSLHF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVVIMD(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDSP(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDMSL(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSSR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSTR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSSRD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSTRD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSSRDC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSTRDC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDTSR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDTTR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDUVDF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDPARF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDCAPES(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMXCAP6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMXCAPS6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDPARCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDTINCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCBASE(KPROMA), PD0DEGL(KPROMA), PDVISIH(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCIN(KPROMA), PDKINDEX(KPROMA), PDTTINDEX(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCBASEA(KPROMA), PDCTOPC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDZTWETB0(KPROMA), PDZTWETB1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDFDIR(KPROMA), PDDSRP(KPROMA), PDCDIR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDEWSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDNSSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDE(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDPEV(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLGWS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMGWS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDGWD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMX2T(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMN2T(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMX2T6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMN2T6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDRO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSRO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSSRO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDNEE(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDGPP(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDREC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDCSF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLSSF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMXTPR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMNTPR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMXTPR6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDMNTPR6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTPR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLSRR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDCRR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLSSFR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDCSFR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDPTYPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVILSPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIEWSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDINSSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDISSHF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDVIWVE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDVIWVN(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCWV(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCLW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCIW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCRW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCSW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCSLW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCO3(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCGHG(KPROMA,YDML_GCONF%YGFL%NGHG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCCHEM(KPROMA,YDML_GCONF%YGFL%NCHEM_TC)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTCAERO(KPROMA,YDML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLITOTI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLITOTA6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLICGI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLICGA6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDCLBT(KPROMA,KSATSIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDCSBT(KPROMA,KSATSIM)
END SUBROUTINE CPEDIA
END INTERFACE
