INTERFACE
SUBROUTINE CPEULDYN(YDCST, YDGEOMETRY, YDEPHY, YGFL, YDML_DYN, YDPHY, PBETADT,&
 & PDT, PTSOL, PQSOL, PNHXT0, PKENE, YDCTY, PRES0, PRDELP, YDCPG_TND, PNHXT9, PGFLPC,&
 & YDVARS, YDCPG_BNDS, YDCPG_SL2) 
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCST , ONLY : TCST
USE YOEPHY , ONLY : TEPHY
USE YOMPHY , ONLY : TPHY
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_SL2_TYPE,CPG_CTY_TYPE,CPG_TND_TYPE
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(MODEL_DYNAMICS_TYPE) ,INTENT(IN) :: YDML_DYN
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
TYPE(FIELD_VARIABLES) ,INTENT(INOUT) :: YDVARS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_SL2_TYPE) ,INTENT(INOUT) :: YDCPG_SL2
TYPE(CPG_CTY_TYPE) ,INTENT(INOUT) :: YDCTY
TYPE(CPG_TND_TYPE) ,INTENT(INOUT) :: YDCPG_TND
REAL(KIND=JPRB) ,INTENT(IN) :: PBETADT
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PTSOL(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSOL(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PNHXT0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PKENE(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRES0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PNHXT9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLPC(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIMPC)
END SUBROUTINE CPEULDYN
END INTERFACE
