INTERFACE
SUBROUTINE CPFPFILTER(YDGEOMETRY,CDDILA,CDCONT,KFPDOM,KFPCMAX,PSEL,KFMAX,PBED,PLTF,&
 & LDBED,KCMAX,PSTRET,PMAXDEV,LDFPFIL,PFPFIL,PFPMAT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=*), INTENT(IN) :: CDDILA
CHARACTER(LEN=*), INTENT(IN) :: CDCONT
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCMAX
REAL(KIND=JPRB), INTENT(IN) :: PSEL(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KFMAX(KFPDOM)
REAL(KIND=JPRB), INTENT(IN) :: PBED
REAL(KIND=JPRB), INTENT(IN) :: PLTF
LOGICAL, INTENT(IN) :: LDBED
INTEGER(KIND=JPIM), INTENT(OUT) :: KCMAX(KFPDOM)
REAL(KIND=JPRB), INTENT(IN) :: PSTRET
REAL(KIND=JPRB), INTENT(IN) :: PMAXDEV
LOGICAL, INTENT(IN) :: LDFPFIL(KFPDOM)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFPFIL(:,:)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFPMAT(:,:)
END SUBROUTINE CPFPFILTER
END INTERFACE
