INTERFACE
SUBROUTINE CPG5_GP(YDGEOMETRY,YDGMV5,YDSURF,&
 & YDML_GCONF,YDPHLC,YDSIMPHL,YDML_DYN,KST,KEND,KSTGLO,&
 & KIBL,&
 & PTRAJ_PHYS,PTRAJ_SRFC,PTRAJ_CST,&
 & PGFL5,PGMV5,PGMV5S,&
 & POROGL,POROGM,&
 & PGMVT95,PGFLT95,&
 & PRE5,PRE5L,PRE5M,PRE5F,PXYB5,PRPREF5,&
 & PUVH5,PHI5,PHIF5,PRCP5,PRRED5,PCTY5,PRT5,PRT5L,PRT5M,&
 & PRE95,PRE95F,PXYB95,PRRED95,PHI95,PHIF95,PRCP95,&
 & PGPPC5,PQS,PQS1,PTS,PTS1,PSNS,PSD_VF5,PQCHA5L,PQCHA5M,&
 & PXYBDER5,PRNHPPI5,PHI5FL,PHI5FM,PNH15L,PNH15M) 
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMSIMPHL, ONLY : TSIMPHL
USE YOPHLC , ONLY : TPHLC
USE INTDYN_MOD,ONLY : YYTHW5, YYTCTY5, YYTXYBDER5,&
 & YYTRCP5, YYTRCP95, YYTXYB5, YYTXYB95, YYTGMVT95, YYTGFLT95 
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE, TRAJ_CST_TYPE, TRAJ_SRFC_TYPE,&
 & LPRTTRAJ 
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(MODEL_DYNAMICS_TYPE),INTENT(INOUT):: YDML_DYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TPHLC) ,INTENT(INOUT) :: YDPHLC
TYPE(TSIMPHL) ,INTENT(INOUT) :: YDSIMPHL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIBL
TYPE(TRAJ_PHYS_TYPE),INTENT(IN) :: PTRAJ_PHYS
TYPE(TRAJ_SRFC_TYPE),INTENT(IN) :: PTRAJ_SRFC
TYPE(TRAJ_CST_TYPE) ,INTENT(IN) :: PTRAJ_CST
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_GCONF%YGFL%NDIM5)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV5%YT5%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV5S(YDGEOMETRY%YRDIM%NPROMA,YDGMV5%YT5%NDIMS)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGL(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGM(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGMVT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTGMVT95%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGFLT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTGFLT95%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRE5(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRE5L(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRE5M(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRE5F(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXYB5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB5%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRPREF5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUVH5(YDGEOMETRY%YRDIM%NPROMNH,0:YDGEOMETRY%YRDIMV%NFLEVG,YYTHW5%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHI5(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIF5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRCP5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTRCP5%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRRED5(YDGEOMETRY%YRDIM%NPROMNH,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCTY5(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG,YYTCTY5%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRT5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRT5L(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRT5M(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRE95(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRE95F(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXYB95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB95%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRRED95(YDGEOMETRY%YRDIM%NPROMNH,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHI95(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIF95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRCP95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTRCP95%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGPPC5(YDGEOMETRY%YRDIM%NPROMA,YDML_DYN%YRPTRGPPC%NFGPPC+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQS1(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTS1(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSNS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSD_VF5(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VFD%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCHA5L(YDGEOMETRY%YRDIM%NPROMNH,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCHA5M(YDGEOMETRY%YRDIM%NPROMNH,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXYBDER5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYBDER5%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRNHPPI5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHI5FL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHI5FM(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNH15L(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNH15M(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
END SUBROUTINE CPG5_GP
END INTERFACE
