INTERFACE
SUBROUTINE CPG_PB1 (YDCPG_BNDS, YDCPG_OPTS, YDMODEL, YDSL, PB1, PSLBUF1AU)
USE PARKIND1, ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE TYPE_MODEL , ONLY : MODEL
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(SL_STRUCT) ,INTENT(IN) :: YDSL
REAL(KIND=JPRB) ,INTENT(OUT) :: PB1(YDSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLBUF1AU(YDCPG_OPTS%KLON,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
END SUBROUTINE
END INTERFACE
