INTERFACE
SUBROUTINE CPG_DYN_EUL (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_TND, YDCPG_MISC, YDCPG_DYN0, YDCPG_DYN9,&
 & YDVARS, YDMODEL,YDCPG_SL2, YDA_GFLPC ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_SL2_TYPE, CPG_TND_TYPE, CPG_MISC_TYPE, CPG_DYN_TYPE
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
USE TYPE_MODEL , ONLY : MODEL
USE ARRAY_FIELD_WRAPPER_MOD, ONLY : ARRAY_4D
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_TND_TYPE) ,INTENT(INOUT) :: YDCPG_TND
TYPE(CPG_MISC_TYPE) ,INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_DYN_TYPE) ,INTENT(INOUT) :: YDCPG_DYN0
TYPE(CPG_DYN_TYPE) ,INTENT(INOUT) :: YDCPG_DYN9
TYPE(FIELD_VARIABLES) ,INTENT(INOUT) :: YDVARS
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(CPG_SL2_TYPE) ,INTENT(INOUT) :: YDCPG_SL2
TYPE(ARRAY_4D) ,INTENT(INOUT) :: YDA_GFLPC
END SUBROUTINE
END INTERFACE
