INTERFACE
SUBROUTINE CPG_DIA_DDH (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, YDCPG_TND, YDCPG_MISC, YDCPG_GPAR,&
 & YDMF_PHYS_OUT, YDCPG_DYN0, YDMF_PHYS_SURF, YDVARS, YDMODEL, KDDHI, POMEGA, YDCPG_TNDSI_DDH,&
 & YDCPG_TNDHD_DDH, PDHCV, YDDDH, PFTCNS) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_DYN_TYPE, CPG_GPAR_TYPE, CPG_MISC_TYPE, CPG_TND_TYPE
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_OUT_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD, ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
USE TYPE_MODEL , ONLY : MODEL
USE DDH_MIX , ONLY : NTOTFIELD, RDDHSURF_FIELD, RDDH_FIELD, TYP_DDH
USE CPG_DDH_TND_TYPE_MOD , ONLY : CPG_TNDHD_DDH_TYPE, CPG_TNDSI_DDH_TYPE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_TND_TYPE) ,INTENT(INOUT) :: YDCPG_TND
TYPE(CPG_MISC_TYPE) ,INTENT(INOUT) :: YDCPG_MISC
TYPE(CPG_GPAR_TYPE) ,INTENT(INOUT) :: YDCPG_GPAR
TYPE(MF_PHYS_OUT_TYPE) ,INTENT(IN) :: YDMF_PHYS_OUT
TYPE(CPG_DYN_TYPE) ,INTENT(IN) :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE) ,INTENT(IN) :: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES) ,INTENT(IN) :: YDVARS
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KDDHI(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: POMEGA(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
TYPE(CPG_TNDSI_DDH_TYPE) ,INTENT(INOUT) :: YDCPG_TNDSI_DDH
TYPE(CPG_TNDHD_DDH_TYPE) ,INTENT(INOUT) :: YDCPG_TNDHD_DDH
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDHCV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,YDMODEL%YRML_DIAG%YRMDDH%NDHCVSUN)
TYPE(TYP_DDH) ,INTENT(INOUT) :: YDDDH
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFTCNS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,6)
END SUBROUTINE
END INTERFACE
