INTERFACE
SUBROUTINE CPG_PT_ULP (YDMODEL, YDGEOMETRY, YDCPG_SL1, YDVARS, YGFL, KSTART,&
 & KPROF, LDGET, PGFLPT, PGFLT1, PGFL) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE
USE TYPE_MODEL , ONLY : MODEL
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(CPG_SL1_TYPE) ,INTENT(INOUT) :: YDCPG_SL1
TYPE(FIELD_VARIABLES) ,INTENT(INOUT) :: YDVARS
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
LOGICAL ,INTENT(IN) :: LDGET
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLPT(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIMPT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM)
END SUBROUTINE CPG_PT_ULP
END INTERFACE
