INTERFACE
SUBROUTINE CPGLAG(YDGEOMETRY,YDGMV,YDML_DIAG,YDML_GCONF,YDDYN,YDPTRSLB2,&
 & KGPCOMP,KSTGLO,LDCONFX,&
 & PGMV,PGMVS,PB2,PGFLT1,PGMVT1,PGMVT1S,PGFL,&
 & PGMVTNDSL,PGFLTNDSL,YDDDH,PGPSTRESS,PTRAJEC,PTRAJEC_OOPS) 
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE PTRSLB2 , ONLY : TPTRSLB2
USE YOMDYN , ONLY : TDYN
USE YOMTRAJ , ONLY : TRAJ_TYPE, LPRTTRAJ, LTRAJSAVE, LTRAJSLAG
USE YOMTRAJ_OOPS , ONLY : TRAJ_TYPE_OOPS, LTRAJSAVE_OOPS, LTRAJSLAG_OOPS
USE DDH_MIX , ONLY : TYP_DDH
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_DIAGNOSTICS_TYPE) ,INTENT(INOUT) :: YDML_DIAG
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT) :: YDML_GCONF
TYPE(TPTRSLB2) ,INTENT(INOUT) :: YDPTRSLB2
INTEGER(KIND=JPIM) ,INTENT(IN) :: KGPCOMP
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
LOGICAL ,INTENT(IN) :: LDCONFX
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PB2(YDGEOMETRY%YRDIM%NPROMA,YDPTRSLB2%NFLDSLB2)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVTNDSL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & 2+YDML_GCONF%YRDIMF%NFTHER) 
REAL(KIND=JPRB) ,INTENT(IN) :: PGFLTNDSL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_GCONF%YGFL%NUMFLDS)
TYPE(TRAJ_TYPE) ,OPTIONAL,INTENT(INOUT) :: PTRAJEC
TYPE(TRAJ_TYPE_OOPS) ,OPTIONAL,INTENT(INOUT) :: PTRAJEC_OOPS
TYPE(TYP_DDH) ,INTENT(INOUT) :: YDDDH
REAL(KIND=JPRB) ,OPTIONAL, INTENT(IN) :: PGPSTRESS(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,3)
END SUBROUTINE CPGLAG
END INTERFACE
