INTERFACE
SUBROUTINE CPGTL(YDGEOMETRY,YDGMV,YDGMV5,YDSURF5,&
 & YDMODEL,LDFSTEP,LDUSEPB1,LDSTR,&
 & KGPCOMP,KSTGLO,KIBL,&
 & PDT,PDTPHY,PTE,PBETADT,YDSL,&
 & PFORCEU,PFORCEV,PFORCET,PFORCEQ,&
 & PGMV,PGMVS,PGFL,&
 & KSETTLOFF,PB1,PB2,PGMVT1,PGMVT1S,PGFLT1,&
 & PB15,PGMV5,PGMV5S,PGFL5,PTRAJ_PHYS,PTRAJ_PHYS_TLAD,&
 & PTRAJ_SRFC,PTRAJ_CST,PTRAJ_SLAG) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE, TRAJ_PHYS_TLAD_TYPE,&
 & TRAJ_SRFC_TYPE, TRAJ_CST_TYPE, TRAJ_SLAG_TYPE 
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(TSURF) ,INTENT(IN) :: YDSURF5
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
LOGICAL ,INTENT(IN) :: LDFSTEP
LOGICAL ,INTENT(IN) :: LDUSEPB1
LOGICAL ,INTENT(IN) :: LDSTR
INTEGER(KIND=JPIM) ,INTENT(IN) :: KGPCOMP
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KSETTLOFF(YDGEOMETRY%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIBL
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PDTPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PTE
REAL(KIND=JPRB) ,INTENT(IN) :: PBETADT
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEU(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCET(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEQ(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PB1(YDSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PB2(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGMVT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PB15(YDSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB15%NFLDSLB15)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV5%YT5%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV5S(YDGEOMETRY%YRDIM%NPROMA,YDGMV5%YT5%NDIMS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM5)
TYPE(TRAJ_PHYS_TYPE) ,INTENT(IN) :: PTRAJ_PHYS
TYPE(TRAJ_PHYS_TLAD_TYPE),INTENT(INOUT) :: PTRAJ_PHYS_TLAD
TYPE(TRAJ_SRFC_TYPE) ,INTENT(IN) :: PTRAJ_SRFC
TYPE(TRAJ_CST_TYPE) ,INTENT(IN) :: PTRAJ_CST
TYPE(TRAJ_SLAG_TYPE) ,INTENT(IN) :: PTRAJ_SLAG
END SUBROUTINE CPGTL
END INTERFACE
