INTERFACE
SUBROUTINE CPICGFL(YDGEOMETRY,YDGMV,YDML_CHEM,YGFL,PGMV,PGMVS,PGFLT1)
USE MODEL_CHEM_MOD , ONLY : MODEL_CHEM_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMGMV , ONLY : TGMV
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(MODEL_CHEM_TYPE),INTENT(INOUT) :: YDML_CHEM
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMV(:,:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVS(:,:,:)
END SUBROUTINE CPICGFL
END INTERFACE
