INTERFACE
SUBROUTINE CPNUDG ( KPROMA, KSTART, KPROF, KFNUDG, KLEV, KBLK,&
 & PPNUDG,&
 & PVNUDM,&
 & PTS1, PWS1,&
 & PWP1, PSNS1,&
 & PTG1, PQG1, PUG1, PVG1,&
 & PPG1,&
 & PTG0, PQG0, PUG0, PVG0, PPG0, PGM, PLSM) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFNUDG
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KBLK
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PPNUDG(KFNUDG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVNUDM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWP1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSNS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTG1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQG1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUG1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVG1(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPG1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTG0(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQG0(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUG0(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVG0(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPG0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KPROMA)
END SUBROUTINE CPNUDG
END INTERFACE
