INTERFACE
SUBROUTINE CPPHDDH( YDCPG_BNDS, YDCPG_OPTS, YDCST, YDML_DIAG, YDEPHY, YDRIP, YDML_PHY_MF, LDDYN,&
 & YDVARS, YDMF_PHYS_OUT, YDMF_PHYS_SURF, PUZGEO, PVMGEO, PENTRA, PENTRV, PHI0, PDHCV, PDHCS, PFTCNS) 
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
USE YOMCST , ONLY : TCST
USE YOEPHY , ONLY : TEPHY
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_OUT_TYPE
USE MF_PHYS_SURFACE_TYPE_MOD, ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(MODEL_DIAGNOSTICS_TYPE) ,INTENT(IN) :: YDML_DIAG
TYPE(MODEL_PHYSICS_MF_TYPE) ,INTENT(IN) :: YDML_PHY_MF
TYPE(TRIP) ,INTENT(IN) :: YDRIP
LOGICAL ,INTENT(IN) :: LDDYN
TYPE(FIELD_VARIABLES) ,INTENT(IN) :: YDVARS
TYPE(MF_PHYS_OUT_TYPE) ,INTENT(IN) :: YDMF_PHYS_OUT
TYPE(MF_PHYS_SURF_TYPE) ,INTENT(IN) :: YDMF_PHYS_SURF
REAL(KIND=JPRB) ,INTENT(IN) :: PUZGEO(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVMGEO(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PENTRA(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PENTRV(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PHI0(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDHCV(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,YDML_DIAG%YRMDDH%NDHCVSU)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDHCS(YDCPG_OPTS%KLON,YDML_DIAG%YRMDDH%NDHCSSU)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFTCNS(YDCPG_OPTS%KLON,0:YDCPG_OPTS%KFLEVG,6)
END SUBROUTINE CPPHDDH
END INTERFACE
