INTERFACE
SUBROUTINE CPPSOLAN(YDCST,KLON,KST,KEND,PGEMU,PGELAM,PMU0)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCST , ONLY : TCST
TYPE(TCST) ,INTENT(IN) :: YDCST
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMU0(KLON)
END SUBROUTINE CPPSOLAN
END INTERFACE
