INTERFACE
SUBROUTINE CPREP1(YDGEOMETRY,YDSURF,YDEPHY,YDML_GCONF,YDPHY1,PTEFRCL)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMPHY1 , ONLY : TPHY1
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TPHY1) ,INTENT(INOUT) :: YDPHY1
REAL(KIND=JPRB),INTENT(IN) :: PTEFRCL
END SUBROUTINE CPREP1
END INTERFACE
