INTERFACE
SUBROUTINE CPTENDSM(YDCST, YDPHY,KPROMA, KSTART, KPROF, KFLEV,&
 & PDIFCQ , PDIFCS , PDIFTQ , PDIFTS ,&
 & PFCCQL , PFCCQN , PFCSQL , PFCSQN ,&
 & PFPLCL , PFPLCN , PFPLSL , PFPLSN ,&
 & PFRSO , PFRTH ,&
 & PSTRCU , PSTRCV , PSTRDU , PSTRDV ,&
 & PSTRTU , PSTRTV ,&
 & PSTRMU , PSTRMV , PFRMH ,&
 & PRDELP , PAPHIF ,&
 & PU , PV , PT , PQ ,&
 & PQS , PTS , POROG ,&
 & PTENDU , PTENDV , PTENDH ,&
 & PTENDQ ,&
 & P_ZFHPCL , P_ZFHPCN , P_ZFHPSL , P_ZFHPSN ,&
 & P_ZFHSCL , P_ZFHSCN , P_ZFHSSL , P_ZFHSSN ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
USE YOMPHY , ONLY : TPHY
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TPHY) ,INTENT(IN) :: YDPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQ(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCS(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRCU(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRCV(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRDU(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRDV(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTU(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTV(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRMU(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRMV(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRMH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDU(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDQ(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHPCL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHPCN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHPSL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHPSN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHSCL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHSCN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHSSL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZFHSSN(KPROMA,0:KFLEV)
END SUBROUTINE CPTENDSM
END INTERFACE
