INTERFACE
SUBROUTINE CPTENDS ( YDCST, YDML_PHY_MF,KPROMA, KSTART, KPROF, KFLEV, KCSS, PDT,&
 & PFPLCL, PFPLSL, PFPLCN, PFPLSN,&
 & PFRSO, PFRTH,&
 & PALBNS1 ,PCT, PC1, PC2,&
 & PFCHSP, PFCLL, PFCLN, PFCS, PFEVI, PFEVL, PFEVN,&
 & PFEVV , PFGEL, PFGELS, PFLWSP, PFONTE, PFTR,&
 & PLSM, PRHONS1, PRUISL, PRUISP, PRUISS, PSNS1, PVEG,&
 & PTDTS, PTDTP, PTDWS, PTDWSI, PTDWP, PTDWPI, PTDWL, PTDSNS,&
 & PTDALBNS, PTDRHONS ) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KCSS
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBNS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PC1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PC2(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCHSP(KPROMA,KCSS)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVV(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGELS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFLWSP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFONTE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFTR(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHONS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEG(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDTP(KPROMA,KCSS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDWS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDWSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDWP(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDWPI(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDWL(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDSNS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDALBNS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDRHONS(KPROMA)
END SUBROUTINE CPTENDS
END INTERFACE
