INTERFACE
SUBROUTINE CPTEND_FLEX ( YDLDDH,YDMDDH,YGFL,YDPHY,KPROMA, KSTART, KPROF, KFLEV,PGNORDL,PGNORDM,&
 & PDELP,PRDELP , PCP,&
 & PU, PV, PT, PTS, PGFL,&
 & YDPROCSET ,&
 & PTENDU , PTENDV , PTENDH, PTENDGFL ,&
 & PFHSCL , PFHSCN , PFHSSL , PFHSSN,&
 & PFHPCL , PFHPCN , PFHPSL , PFHPSN,&
 & PFHP , PFP , PFEPFP , PFCMPCQ, PFCMPSN, PFCMPSL,&
 & YDDDH) 
USE YOMMDDH , ONLY : TMDDH
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMPHY , ONLY : TPHY
USE YOMLDDH , ONLY : TLDDH
USE DDH_MIX , ONLY : ADD_FIELD_3D, NEW_ADD_FIELD_3D, TYP_DDH
USE INTFLEX_MOD, ONLY : TYPE_INTPROCSET, TYPE_INTPROC
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TLDDH) ,INTENT(IN) :: YDLDDH
TYPE(TMDDH) ,INTENT(IN) :: YDMDDH
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PGNORDL (KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGNORDM (KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP (KPROMA,0:KFLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS (KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL (KPROMA,KFLEV,YGFL%NUMFLDS)
TYPE(TYPE_INTPROCSET),INTENT(IN) :: YDPROCSET
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDU (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDV (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDH (KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDGFL(KPROMA,KFLEV,YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHSCL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHSCN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHSSL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHSSN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPSL (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPSN (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PFHP (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PFP (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEPFP (KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCMPCQ(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCMPSN(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCMPSL(KPROMA,0:KFLEV)
TYPE(TYP_DDH), INTENT(INOUT) :: YDDDH
END SUBROUTINE CPTEND_FLEX
END INTERFACE
