INTERFACE
SUBROUTINE CPUTQY_AROME_EXPL(YDMF_PHYS_NEXT_STATE, YDVARS, YDMODEL, YDDIMV, YDCPG_BNDS, YDCPG_OPTS,&
 & PDT, PTENDQ, PTENDL, PTENDR, PTENDI, PTENDS, PTENDG, PTENDH, PTENDTKE, PTENDT, PTENDU, PTENDV,&
 & PTENDD) 
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_MODEL, ONLY : MODEL
USE CPG_OPTS_TYPE_MOD&
 & , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE 
USE MF_PHYS_NEXT_STATE_TYPE_MOD&
 & , ONLY : MF_PHYS_NEXT_STATE_TYPE 
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
TYPE (MF_PHYS_NEXT_STATE_TYPE) ,INTENT(INOUT) :: YDMF_PHYS_NEXT_STATE
TYPE(FIELD_VARIABLES) ,INTENT(IN) :: YDVARS
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQ (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDL (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDR (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDI (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDS (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDG (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDTKE (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDH (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDT (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDU (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDV (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDD (YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG)
END SUBROUTINE CPUTQY_AROME_EXPL
END INTERFACE
