INTERFACE
SUBROUTINE CPUTQY_AROME_LOOP(YDMODEL, YDDIMV, YDGMV, YDCPG_BNDS, YDCPG_OPTS, PDT, KPGFL, KPTR,&
 & PTENDGFLR, PB1, PGMVT1, PGFLT1) 
USE YOMDIMV , ONLY : TDIMV
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_MODEL, ONLY : MODEL
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TGMV) ,INTENT(IN) :: YDGMV
TYPE(CPG_BNDS_TYPE),INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN) :: YDCPG_OPTS
INTEGER(KIND=JPIM),INTENT(IN) :: KPGFL(YDMODEL%YRML_GCONF%YGFL%NUMFLDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KPTR(YDMODEL%YRML_GCONF%YGFL%NUMFLDS)
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDGFLR(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NUMFLDS)
REAL(KIND=JPRB) ,TARGET, INTENT(INOUT) :: PB1(YDCPG_OPTS%KLON,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,TARGET, INTENT(INOUT) :: PGMVT1(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDCPG_OPTS%KLON,YDCPG_OPTS%KFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1)
END SUBROUTINE CPUTQY_AROME_LOOP
END INTERFACE
