INTERFACE
SUBROUTINE CPUTQYSAD(YDDIMV,YDGMV, YGFL,YDPTRSLB1,KPROMA, KSTART, KPROF, KFLEV, PDT, KPQ,KPQL,KPQI,&
 & KSLB1U9,KSLB1V9,KSLB1T9,KSLB1GFL9,&
 & PTENDH5, PTENDQ5,PTENDQL5,PTENDQI5,PTENDU5, PTENDV5,&
 & PCP95, PDELP95, PTT95, PUT95, PVT95,&
 & PCP05, PDELP05, PTT05, PUT05, PVT05,&
 & PTENDH, PTENDQ,PTENDQL,PTENDQI,PTENDU, PTENDV,&
 & PCP9, PDELP9, PTT9, PUT9, PVT9,&
 & PCP0, PDELP0, PTT0, PUT0, PVT0,&
 & PB1, PGMVT1, PGFLT1,&
 & PFDIS) 
USE YOMDIMV , ONLY : TDIMV
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE PTRSLB1 , ONLY : TPTRSLB1
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TPTRSLB1) ,INTENT(IN) :: YDPTRSLB1
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KPQ
INTEGER(KIND=JPIM),INTENT(IN) :: KPQL
INTEGER(KIND=JPIM),INTENT(IN) :: KPQI
INTEGER(KIND=JPIM),INTENT(IN) :: KSLB1U9
INTEGER(KIND=JPIM),INTENT(IN) :: KSLB1V9
INTEGER(KIND=JPIM),INTENT(IN) :: KSLB1T9
INTEGER(KIND=JPIM),INTENT(IN) :: KSLB1GFL9
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDH5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQ5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQL5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDQI5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDU5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENDV5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PCP95(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PDELP95(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PTT95(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PUT95(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PVT95(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PCP05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PDELP05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PTT05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PUT05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PVT05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENDH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENDQ(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENDQL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENDQI(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENDU(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENDV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PCP9(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PDELP9(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PTT9(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PUT9(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PVT9(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PCP0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PDELP0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PTT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PUT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PVT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFDIS(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,TARGET, INTENT(INOUT) :: PB1(KPROMA,YDPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,TARGET, INTENT(INOUT) :: PGMVT1(KPROMA,KFLEV,YDGMV%YT1%NDIM)
REAL(KIND=JPRB) ,TARGET, INTENT(IN) :: PGFLT1(KPROMA,KFLEV,YGFL%NDIM1)
END SUBROUTINE CPUTQYSAD
END INTERFACE
