INTERFACE
SUBROUTINE CPVPOSPR(KFPCONF,YDAFN,YDQTYPE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMAFN , ONLY : TAFN
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KFPCONF
TYPE(TAFN), INTENT(IN) :: YDAFN
TYPE(TYPE_FPRQDYN),INTENT(INOUT) :: YDQTYPE
END SUBROUTINE CPVPOSPR
END INTERFACE
