INTERFACE
SUBROUTINE CTONB(KDUM,YD_PU,YD_PV)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE CONTROL_VECTORS_MOD
INTEGER(KIND=JPIM) :: KDUM
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_PU
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_PV
END SUBROUTINE CTONB
END INTERFACE
