INTERFACE
SUBROUTINE CUANCAPE2(YDECUMF,YDEPHLI, KIDIA, KFDIA, KLON, KLEV,&
 & PAP, PAPH, PT, PQ, PCAPE, PCIN) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOECUMF , ONLY : TECUMF
USE YOEPHLI , ONLY : TEPHLI
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
TYPE(TEPHLI) ,INTENT(IN) :: YDEPHLI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCIN(KLON)
END SUBROUTINE CUANCAPE2
END INTERFACE
