INTERFACE
SUBROUTINE CUASCN2&
 & (YDECUMF2, YDEPHLI, KIDIA, KFDIA, KLON, KLEV,&
 & LDRAIN1D, LDLAND, PTEN, PTENH, PQENH,&
 & PGEOH, PQEN, PQSEN,&
 & PAPH,&
 & PLGLAC, PQPRCV,&
 & PBUOH, PWUBASE, LDCUM, KTYPE,&
 & PTU, PQU, PLU,&
 & PMFU, PMFUB,&
 & PMFUS, PMFUQ, PMFUL, PLUDE, PDMFUP,&
 & KCBOT, KCTOP, KSTUP,&
 & PMFUDE_RATE, PWMEAN, PERATEU ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOECUMF2 , ONLY : TECUMF2
USE YOEPHLI , ONLY : TEPHLI
TYPE(TECUMF2) ,INTENT(INOUT) :: YDECUMF2
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL ,INTENT(IN) :: LDRAIN1D
LOGICAL ,INTENT(IN) :: LDLAND(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLGLAC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQPRCV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBUOH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PWUBASE(KLON)
LOGICAL ,INTENT(INOUT) :: LDCUM(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KTYPE(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFUB(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFUS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFUQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFUL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDMFUP(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSTUP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFUDE_RATE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWMEAN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PERATEU(KLON,KLEV)
END SUBROUTINE CUASCN2
END INTERFACE
