INTERFACE
SUBROUTINE CUBASEN2TL&
 & (YDCUMFS, YDECUMF2, YDECLDP,&
 & KIDIA, KFDIA, KLON, KLEV,&
 & PTENH5, PQENH5, PGEOH5, PAP5, PAPH5,&
 & PQHFL5, PAHFS5,&
 & PTEN5, PQEN5, PQSEN5, PGEO5,&
 & PTU5, PQU5, PLU5,&
 & PBUOH5, PWUBASE5, PLGLAC5, PQPRCV5, PCAPE5,&
 & KTYPE, KLAB, LDCUM, LDSC,&
 & KCBOT, KBOTSC, KCTOP, KSTUP,&
 & PTENH, PQENH, PGEOH, PAP, PAPH,&
 & PQHFL, PAHFS,&
 & PTEN, PQEN, PQSEN, PGEO,&
 & PTU, PQU, PLU,&
 & PBUOH, PWUBASE, PLGLAC, PQPRCV, PCAPE ) 
USE YOECLDP , ONLY : TECLDP
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECUMF2 , ONLY : TECUMF2
USE YOMCUMFS , ONLY : TCUMFS
TYPE(TCUMFS) ,INTENT(INOUT) :: YDCUMFS
TYPE(TECLDP) ,INTENT(INOUT) :: YDECLDP
TYPE(TECUMF2) ,INTENT(INOUT) :: YDECUMF2
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTENH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQENH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBUOH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWUBASE5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLGLAC5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQPRCV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE5(KLON)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KTYPE(KLON)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KLAB(KLON,KLEV)
LOGICAL ,INTENT(OUT) :: LDCUM(KLON)
LOGICAL ,INTENT(OUT) :: LDSC(KLON)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KBOTSC(KLON)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KSTUP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBUOH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWUBASE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLGLAC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQPRCV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
END SUBROUTINE CUBASEN2TL
END INTERFACE
