INTERFACE
SUBROUTINE CUCALLN2AD&
 & (YDTHF, YDCST, YDML_PHY_SLIN, YDML_PHY_EC,&
 & KIDIA, KFDIA, KLON, KLEV,&
 & LDLAND, LDRAIN1D,&
 & PTSPHY,&
 & PTM15, PQM15, PUM15, PVM15,&
 & PVERVEL5, PQHFL5, PAHFS5, PAPHM15,&
 & PAP5, PAPH5, PGEO5, PGEOH5, PGAW,&
 & PTENT5, PGTENT5, PTENQ5, PGTENQ5,&
 & PTENU5, PGTENU5, PTENV5, PGTENV5,&
 & PTENT25, PTENQ25, PTENU25, PTENV25,&
 & KTYPE,&
 & KCBOT, KCTOP, KBOTSC, LDCUM, LDSC,&
 & PLU5, PLUDE5, PMFU5, PMFD5,&
 & PFPLCL5, PFPLCN5,&
 & KTRAC, PCM15, PTENC5, PSCAV5,&
 & PTM1, PQM1, PUM1, PVM1,&
 & PVERVEL, PQHFL, PAHFS, PAPHM1,&
 & PAP, PAPH, PGEO, PGEOH,&
 & PTENT , PGTENT, PTENQ, PGTENQ,&
 & PTENU, PGTENU, PTENV, PGTENV,&
 & PLU, PLUDE, PMFU, PMFD,&
 & PDIFCQ, PDIFCS, PFHPCL, PFHPCN,&
 & PFPLCL, PFPLCN, PSTRCU, PSTRCV, PFCQLF ,PFCQIF,&
 & PCAPE,&
 & PCM1, PTENC ) 
USE MODEL_PHYSICS_ECMWF_MOD , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
USE YOETHF , ONLY : TTHF
TYPE(TTHF) ,INTENT(IN) :: YDTHF
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(MODEL_PHYSICS_ECMWF_TYPE),INTENT(INOUT):: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT):: YDML_PHY_SLIN
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL ,INTENT(IN) :: LDLAND(KLON)
LOGICAL ,INTENT(IN) :: LDRAIN1D
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PTM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM15(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PSCAV5(KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC5(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENT25(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENQ25(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENU25(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENV25(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KBOTSC(KLON)
LOGICAL ,INTENT(OUT) :: LDCUM(KLON)
LOGICAL ,INTENT(OUT) :: LDSC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCN5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCM1(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQHFL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQ(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLCL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPLCN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCU(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCV(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQLF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQIF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCAPE(KLON)
END SUBROUTINE CUCALLN2AD
END INTERFACE
