INTERFACE
SUBROUTINE CUCALLN2TL&
 & (YDERAD, YDML_PHY_SLIN, YDECLDP, YDEPHY,&
 & KIDIA, KFDIA, KLON, KLEV,&
 & LDLAND, LDRAIN1D,&
 & PTSPHY, PVDIFTS,&
 & PTM15, PQM15, PUM15, PVM15,&
 & PVERVEL5, PQHFL5, PAHFS5, PAPHM15,&
 & PAP5, PAPH5, PGEO5, PGEOH5, PGAW,&
 & PTENT5, PGTENT5, PTENQ5, PGTENQ5,&
 & PTENU5, PGTENU5, PTENV5, PGTENV5, PARPRC5,&
 & KTOPC, KBASEC, KTYPE,&
 & KCBOT, KCTOP, KBOTSC, LDCUM, LDSC,&
 & PLU5, PLUDE5, PMFU5, PMFD5,&
 & PDIFCQ5, PDIFCS5, PFHPCL5, PFHPCN5,&
 & PFPLCL5, PFPLCN5, PSTRCU5, PSTRCV5, PFCQLF5,PFCQIF5,&
 & PCAPE5,&
 & KTRAC, PCM15, PTENC5, PSCAV5,&
 & PTM1, PQM1, PUM1, PVM1,&
 & PVERVEL, PQHFL, PAHFS, PAPHM1,&
 & PAP, PAPH, PGEO, PGEOH,&
 & PTENT , PGTENT, PTENQ, PGTENQ,&
 & PTENU, PGTENU, PTENV, PGTENV,&
 & PLU, PLUDE, PMFU, PMFD,&
 & PDIFCQ, PDIFCS, PFHPCL, PFHPCN,&
 & PFPLCL, PFPLCN, PSTRCU, PSTRCV, PFCQLF ,PFCQIF,&
 & PCAPE,&
 & PCM1, PTENC) 
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOECLDP , ONLY : TECLDP
USE YOERAD , ONLY : TERAD
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOEPHY , ONLY : TEPHY
TYPE(TECLDP) ,INTENT(INOUT) :: YDECLDP
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT):: YDML_PHY_SLIN
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL ,INTENT(IN) :: LDLAND(KLON)
LOGICAL ,INTENT(IN) :: LDRAIN1D
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PTM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM15(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PSCAV5(KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC5(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PARPRC5(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KTOPC(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KBASEC(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KBOTSC(KLON)
LOGICAL ,INTENT(OUT) :: LDCUM(KLON)
LOGICAL ,INTENT(OUT) :: LDSC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQ5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCS5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCN5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCN5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCU5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCV5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQLF5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQIF5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM1(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQ(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCU(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCV(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQLF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQIF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
END SUBROUTINE CUCALLN2TL
END INTERFACE
