INTERFACE
SUBROUTINE CUCALLN&
 & (PPLDARE, PPLRG, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, YGFL,&
 & KIDIA, KFDIA, KLON, KSMAX, KLEV,KSPPN2D,&
 & LDLAND, LDSLPHY,&
 & PTSPHY,PVDIFTS,&
 & PTM1, PQM1, PUM1, PVM1, PLITOT,&
 & PVERVEL, PQHFL, PAHFS, PAPHM1,&
 & PAP, PAPH, PGEO, PGEOH, PGAW,&
 & PCUCONVCA,PGP2DSPP,&
 & TENDENCY_CML,TENDENCY_TMP,TENDENCY_LOC,&
 & PARPRC,&
 & KTOPC, KBASEC, KTYPE,&
 & KCBOT, KCTOP, KBOTSC, LDCUM, LDSC,&
 & LDSHCV,&
 & PLCRIT_AER,&
 & PLU, PLUDE, PLUDELI, PSNDE, PMFU, PMFD,&
 & PDIFCQ, PDIFCS, PFHPCL, PFHPCN,&
 & PFPLCL, PFPLCN, PLRAIN, PRSUD,&
 & PSTRCU, PSTRCV, PFCQLF, PFCQIF,&
 & PMFUDE_RATE , PMFDDE_RATE , PCAPE ,PWMEAN, PDISS,&
 & KTRAC, PCM1, PTENC, PSCAV ) 
USE MODEL_PHYSICS_ECMWF_MOD , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD , ONLY : TERAD
USE YOM_YGFL , ONLY : TYPE_GFLD
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
USE YOETHF , ONLY : TTHF
USE YOMPHYDER , ONLY : STATE_TYPE
REAL(KIND=JPRB) ,INTENT(IN) :: PPLDARE
REAL(KIND=JPRB) ,INTENT(IN) :: PPLRG
TYPE(TTHF) ,INTENT(IN) :: YDTHF
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE) ,INTENT(INOUT) :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT) :: YDML_PHY_SLIN
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSPPN2D
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL ,INTENT(IN) :: LDLAND(KLON)
LOGICAL ,INTENT(IN) :: LDSLPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PLCRIT_AER(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM1(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PLITOT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCUCONVCA(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2DSPP(KLON,KSPPN2D)
REAL(KIND=JPRB) ,INTENT(IN) :: PSCAV(KTRAC)
TYPE (STATE_TYPE) ,INTENT (IN) :: TENDENCY_CML
TYPE (STATE_TYPE) ,INTENT (IN) :: TENDENCY_TMP
TYPE (STATE_TYPE) ,INTENT(INOUT) :: TENDENCY_LOC
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(OUT) :: PARPRC(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTOPC(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KBASEC(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KBOTSC(KLON)
LOGICAL ,INTENT(OUT) :: LDCUM(KLON)
LOGICAL ,INTENT(OUT) :: LDSC(KLON)
LOGICAL ,INTENT(IN) :: LDSHCV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDELI(KLON,KLEV,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSNDE(KLON,KLEV,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQ(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCN(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLRAIN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRSUD(KLON,KLEV,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCU(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCV(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQLF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQIF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFUDE_RATE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFDDE_RATE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWMEAN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDISS(KLON,KLEV)
END SUBROUTINE CUCALLN
END INTERFACE
