INTERFACE
SUBROUTINE CUDTDQN2&
 & (YDML_PHY_SLIN, YDEPHY,&
 & KIDIA, KFDIA, KLON, KLEV,&
 & KTOPM2, KCTOP, KDTOP,&
 & LDRAIN1D, LDCUM, LDDRAF, PTSPHY,&
 & PAPH, PGEOH, PGEO,&
 & PTEN, PTENH, PQEN, PQENH, PQSEN,&
 & PLGLAC, PLUDE, PMFU, PMFD,&
 & PMFUS, PMFDS, PMFUQ, PMFDQ,&
 & PMFUL, PDMFUP, PDMFDP, PDPMEL,&
 & PTENT, PTENQ, PENTH ) 
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT):: YDML_PHY_SLIN
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOPM2
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KDTOP(KLON)
LOGICAL ,INTENT(IN) :: LDRAIN1D
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
LOGICAL ,INTENT(IN) :: LDDRAF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLGLAC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFUS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFDS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFUQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFDQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFUL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDMFUP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDMFDP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDPMEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PENTH(KLON,KLEV)
END SUBROUTINE CUDTDQN2
END INTERFACE
