INTERFACE
SUBROUTINE CUDUDV2&
 & (YDECUMF2,KIDIA, KFDIA, KLON, KLEV,&
 & KTOPM2, KTYPE, KCBOT, KCTOP, LDCUM, PTSPHY,&
 & PAPH, PUEN, PVEN, PMFU, PMFD,&
 & PUU, PUD, PVU, PVD,&
 & PTENU, PTENV ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECUMF2 , ONLY : TECUMF2
TYPE(TECUMF2) ,INTENT(INOUT) :: YDECUMF2
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOPM2
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP(KLON)
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV(KLON,KLEV)
END SUBROUTINE CUDUDV2
END INTERFACE
