INTERFACE
SUBROUTINE CUDUDV2AD&
 & (YDECUMF2,KIDIA, KFDIA, KLON, KLEV,&
 & KTOPM2, KTYPE, KCBOT, KCTOP, LDCUM, PTSPHY,&
 & PAPH5, PUEN5, PVEN5, PMFU5, PMFD5,&
 & PUU5, PUD5, PVU5, PVD5,&
 & PTENU5, PTENV5,&
 & PAPH, PUEN, PVEN, PMFU, PMFD,&
 & PUU, PUD, PVU, PVD,&
 & PTENU, PTENV ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECUMF2 , ONLY : TECUMF2
TYPE(TECUMF2) ,INTENT(INOUT) :: YDECUMF2
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOPM2
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP(KLON)
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV(KLON,KLEV)
END SUBROUTINE CUDUDV2AD
END INTERFACE
