INTERFACE
SUBROUTINE CUININ2TL&
 & (YDECUMF2,KIDIA, KFDIA, KLON, KLEV,&
 & PTEN5, PQEN5, PQSEN5, PUEN5, PVEN5,&
 & PVERVEL5, PGEO5, PAPH5,&
 & KLWMIN, KLAB,&
 & PTENH5, PQENH5, PQSENH5, PGEOH5,&
 & PTU5, PQU5, PTD5, PQD5,&
 & PUU5, PVU5, PUD5, PVD5,&
 & PLU5,&
 & PTEN, PQEN, PQSEN, PUEN, PVEN,&
 & PVERVEL, PGEO, PAPH,&
 & PTENH, PQENH, PQSENH, PGEOH,&
 & PTU, PQU, PTD, PQD,&
 & PUU, PVU, PUD, PVD,&
 & PLU ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECUMF2 , ONLY : TECUMF2
TYPE(TECUMF2) ,INTENT(INOUT) :: YDECUMF2
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,KLEV+1)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLWMIN(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLAB(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQENH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSENH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU(KLON,KLEV)
END SUBROUTINE CUININ2TL
END INTERFACE
