INTERFACE
SUBROUTINE CULIGHTTL&
 & ( YDEPHY, KIDIA , KFDIA, KLON, KLEV, PGAW, PGELAT,&
 & PAP5, PAPH5 , PAPHI5, PAPHIF5, LDLAND,&
 & PT5 , PLU5 , PMFU5, PCAPE5,&
 & PFPLCL5, PFPLCN5,&
 & LDCUM , KCBOT , KCTOP,&
 & PLIGH_TOT5, PLIGH_CTG5, PCTOPH5,&
 & PPRECMX5, PICE5, PCDEPTH5, PWMFU5,&
 & PAP, PAPH , PAPHI, PAPHIF,&
 & PT , PLU , PMFU, PCAPE,&
 & PFPLCL, PFPLCN,&
 & PLIGH_TOT, PLIGH_CTG, PCTOPH,&
 & PPRECMX, PICE, PCDEPTH, PWMFU) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KLON)
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
LOGICAL ,INTENT(IN) :: LDLAND(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAPE5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLIGH_TOT5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLIGH_CTG5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCTOPH5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPRECMX5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PICE5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDEPTH5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWMFU5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAPE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLIGH_TOT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLIGH_CTG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCTOPH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPRECMX(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PICE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDEPTH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWMFU(KLON)
END SUBROUTINE CULIGHTTL
END INTERFACE
