INTERFACE
SUBROUTINE CUMASTRN2TL&
 & ( YDML_PHY_SLIN,YDECLDP,YDEPHY,&
 & KIDIA, KFDIA, KLON, KLEV,&
 & LDLAND, LDRAIN1D, PTSPHY,&
 & PTEN5, PQEN5, PUEN5, PVEN5,&
 & PVERVEL5, PQSEN5, PQHFL5, PAHFS5,&
 & PAP5, PAPH5, PGEO5, PGEOH5, PGAW,&
 & PTENT5, PTENQ5, PTENU5, PTENV5,&
 & LDCUM, KTYPE, KCBOT, KCTOP,&
 & KBOTSC, LDSC,&
 & PTU5, PQU5, PLU5, PLUDE5,&
 & PENTH5, PMFLXR5, PMFLXS5, PRAIN5,&
 & PMFU5, PMFD5, PCAPE5,&
 & KTRAC, PCEN5, PTENC5, PSCAV5,&
 & PTEN, PQEN, PUEN, PVEN,&
 & PVERVEL, PQSEN, PQHFL, PAHFS,&
 & PAP, PAPH, PGEO, PGEOH,&
 & PTENT, PTENQ, PTENU, PTENV,&
 & PTU, PQU, PLU, PLUDE,&
 & PENTH, PMFLXR, PMFLXS, PRAIN,&
 & PMFU, PMFD, PCAPE,&
 & PCEN, PTENC ) 
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOECLDP , ONLY : TECLDP
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOEPHY , ONLY : TEPHY
TYPE(TECLDP) ,INTENT(INOUT) :: YDECLDP
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT):: YDML_PHY_SLIN
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
LOGICAL ,INTENT(IN) :: LDLAND(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCEN5(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PSCAV5(KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSEN5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENQ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC5(KLON,KLEV,KTRAC)
LOGICAL ,INTENT(IN) :: LDRAIN1D
LOGICAL ,INTENT(OUT) :: LDCUM(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KBOTSC(KLON)
LOGICAL ,INTENT(OUT) :: LDSC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PENTH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFLXR5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFLXS5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAIN5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFU5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PENTH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFLXR(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFLXS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAIN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
END SUBROUTINE CUMASTRN2TL
END INTERFACE
