INTERFACE
SUBROUTINE CUMCPL(YDCST, YDCPG_OPTS, YDCPG_BNDS, YDRIP, YDPHY, YDMF_PHYS_OUT, PSTRTU, PSTRTV, PTSUR,&
 & PUCLS, PVCLS) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE YOMCST , ONLY : TCST
USE YOMRIP , ONLY : TRIP
USE YOMPHY , ONLY : TPHY
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_OUT_TYPE
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TRIP) ,INTENT(IN) :: YDRIP
TYPE(MF_PHYS_OUT_TYPE) ,INTENT(IN) :: YDMF_PHYS_OUT
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSUR(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUCLS(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCLS(YDCPG_OPTS%KLON)
END SUBROUTINE CUMCPL
END INTERFACE
