INTERFACE
SUBROUTINE CUPDRA&
 & ( YDECUMF2,YDEPHLI,YDECLDP,&
 & KIDIA, KFDIA, KLON, KLEV,&
 & K_JKSTART, LD_LLGO_ON, LDRAIN1D,&
 & PQENH, PGEO, PGEOH, PAPH, PQSEN,&
 & PTU, PQU, PLU,&
 & PSENH, PWU2H, PSUH,&
 & PBUOH, PLGLAC, PQPRCV, PCAPE,&
 & KLAB, LDCUM, LDSC, KCBOT,&
 & KBOTSC, KCTOP, KSTUP ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOECUMF2 , ONLY : TECUMF2
USE YOECLDP , ONLY : TECLDP
USE YOEPHLI , ONLY : TEPHLI
TYPE(TECLDP) ,INTENT(INOUT) :: YDECLDP
TYPE(TECUMF2) ,INTENT(INOUT) :: YDECUMF2
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: K_JKSTART
LOGICAL ,INTENT(INOUT) :: LD_LLGO_ON(KLON)
LOGICAL ,INTENT(IN) :: LDRAIN1D
REAL(KIND=JPRB) ,INTENT(IN) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSENH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWU2H(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSUH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBUOH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLGLAC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQPRCV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCAPE(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KLAB(KLON,KLEV)
LOGICAL ,INTENT(INOUT) :: LDCUM(KLON)
LOGICAL ,INTENT(INOUT) :: LDSC(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KBOTSC(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSTUP(KLON)
END SUBROUTINE CUPDRA
END INTERFACE
