INTERFACE
SUBROUTINE CVA2(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YD_BG,YD_TRAJEC,YDJOT,YDVARBC,YDTCV5,YDGOM,YDTCV,YDTCV_BGC,YDGOM5,YDODB)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_BGC_MOD , ONLY : TOVSCV_BGC
USE TOVSCV_MOD , ONLY : TOVSCV
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE YOMTRAJ , ONLY : TRAJ_TYPE
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE DBASE_MOD , ONLY : DBASE
USE CONTROL_VECTORS_MOD
USE RANDOM_NUMBERS_MIX
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(TRAJ_TYPE) ,INTENT(INOUT) :: YD_BG
TYPE(TRAJ_TYPE) ,INTENT(IN) :: YD_TRAJEC
TYPE(JO_TABLE) ,INTENT(INOUT) :: YDJOT
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(INOUT) :: YDTCV5
TYPE(TOVSCV_BGC) ,INTENT(INOUT) :: YDTCV_BGC
TYPE(CLASS_SUPERGOM),INTENT(INOUT) :: YDGOM, YDGOM5
TYPE(TOVSCV) ,INTENT(INOUT) :: YDTCV
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
END SUBROUTINE CVA2
END INTERFACE
