INTERFACE
SUBROUTINE CVARGPTL(YDGEOMETRY,CDSELECT,KSCALE,YD_JB_STRUCT,PSP3,PSP2,PSP1,PGP3,PGP2)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=1) ,INTENT(IN) :: CDSELECT
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSCALE
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP3(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP2(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP1(:,:)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PGP3(:,:,:)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PGP2(:,:,:)
END SUBROUTINE CVARGPTL
END INTERFACE
