INTERFACE
SUBROUTINE CVAR2(YDGEOMETRY,YDFIELDS,YDGMV5,YDML_GCONF,YDVAZX,YD_BG,YD_TRAJ,YDVARBC,YD_JB_STRUCT,YDTCV,YDTCV_BGC)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMGMV , ONLY : TGMV
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_MOD,ONLY : TOVSCV
USE TOVSCV_BGC_MOD,ONLY : TOVSCV_BGC
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDVAZX
TYPE(FIELDS) ,INTENT(IN) :: YD_BG
TYPE(FIELDS) ,INTENT(IN) :: YD_TRAJ
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
TYPE(TOVSCV),OPTIONAL ,INTENT(INOUT) :: YDTCV
TYPE(TOVSCV_BGC),OPTIONAL ,INTENT(IN) :: YDTCV_BGC
END SUBROUTINE CVAR2
END INTERFACE
