INTERFACE
SUBROUTINE CVAR3AD(YDGEOMETRY,YDGMV,YDGMV5,YGFL,YDSPEC,YDCV,PGP3,PGP2,YD_BG,YD_TRAJ,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE YOM_YGFL , ONLY : TYPE_GFLD
USE JB_CONTROL_VECTORS_MOD
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD, ALLOCATE_SPEC, DEALLOCATE_SPEC
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE(JB_CONTROL_VECTOR),INTENT(INOUT) :: YDCV
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSPEC
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP3(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2(:,:,:)
TYPE(FIELDS) ,INTENT(IN) :: YD_BG
TYPE(FIELDS) ,INTENT(IN) :: YD_TRAJ
TYPE(TYPE_JB_STRUCT) ,INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE CVAR3AD
END INTERFACE
