INTERFACE
SUBROUTINE DDHRCV(PRCV,KLEN,YD_IOSTREAM,YD_IOREQUEST)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE IOSTREAM_MIX , ONLY : IO_GET,TYPE_IOSTREAM , TYPE_IOREQUEST
INTEGER(KIND=JPIM) , INTENT(IN) :: KLEN
REAL(KIND=JPRB) , INTENT(OUT) :: PRCV(KLEN)
TYPE(TYPE_IOSTREAM) , INTENT(INOUT) :: YD_IOSTREAM
TYPE(TYPE_IOREQUEST), INTENT(INOUT) :: YD_IOREQUEST
END SUBROUTINE DDHRCV
END INTERFACE
