INTERFACE
SUBROUTINE DDR_ZH_SEASON(KIDIA, KFDIA, KLON, KMONTH, KDAY, PLAT,&
 & KTILE, KVEG_IFS, KSEASON, KVEG_ZH ) 
USE PARKIND1 ,ONLY : JPIM, JPRB
 INTEGER (KIND=JPIM), INTENT(IN) :: kmonth
 INTEGER (KIND=JPIM), INTENT(IN) :: kday
 INTEGER (KIND=JPIM), INTENT(IN) :: klon
 INTEGER (KIND=JPIM), INTENT(IN) :: kidia
 INTEGER (KIND=JPIM), INTENT(IN) :: kfdia
 REAL (KIND=JPRB), DIMENSION(klon), INTENT(IN) :: plat
 INTEGER (KIND=JPIM), DIMENSION(klon), INTENT(IN) :: ktile
 INTEGER (KIND=JPIM), DIMENSION(klon), INTENT(IN) :: kveg_ifs
 INTEGER (KIND=JPIM), DIMENSION(klon), INTENT(OUT) :: kseason
 INTEGER (KIND=JPIM), DIMENSION(klon), INTENT(OUT) :: kveg_ZH
END SUBROUTINE DDR_ZH_SEASON
END INTERFACE
