INTERFACE
SUBROUTINE DDR_LAMINAR_RES(KIDIA, KFDIA, KLON, PUSTAR, PXDIMO, PWRB)
USE PARKIND1 ,ONLY : JPIM, JPRB
INTEGER (KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KLON
REAL (KIND=JPRB), INTENT(IN) :: PXDIMO
REAL (KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PUSTAR
REAL (KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PWRB
END SUBROUTINE DDR_LAMINAR_RES
END INTERFACE
