INTERFACE
SUBROUTINE DEALXMO(YDGFL,YDGMV)
USE YOMGFL , ONLY : TGFL
USE YOMGMV , ONLY : TGMV
TYPE(TGFL) , INTENT(INOUT) :: YDGFL
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
END SUBROUTINE DEALXMO
END INTERFACE
