INTERFACE
SUBROUTINE DEALLT(YDDIM,YDMTRAJ,YDGMV,YDSURF,YDMODEL)
USE TYPE_MODEL , ONLY : MODEL
USE YOMDIM , ONLY : TDIM
USE MTRAJ_MOD , ONLY : MTRAJ
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV , ONLY : TGMV
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
END SUBROUTINE DEALLT
END INTERFACE
