INTERFACE
SUBROUTINE DECVLANISO(KST,KEND,KPROMA,LDGAMA,LDALFA,PGAMA,PALFA,PU,PV,PSDO)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
LOGICAL ,INTENT(IN) :: LDGAMA
LOGICAL ,INTENT(IN) :: LDALFA
REAL(KIND=JPRB) ,INTENT(OUT) :: PGAMA(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PALFA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSDO(KPROMA)
END SUBROUTINE DECVLANISO
END INTERFACE
