INTERFACE
SUBROUTINE DEFRUN(YDSTA,YDDIMV,YDJOT)
USE YOMSTA , ONLY : TSTA
USE YOMDIMV , ONLY : TDIMV
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE YOMMKODB
USE MPL_MODULE
TYPE(TSTA) , INTENT(IN) :: YDSTA
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(JO_TABLE), INTENT(INOUT) :: YDJOT
END SUBROUTINE DEFRUN
END INTERFACE
