INTERFACE
SUBROUTINE DEPERERR(PHOUPDAY,PPI,KANCDY,PDAYPYEA,PG)
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PHOUPDAY
REAL(KIND=JPRB) ,INTENT(IN) :: PPI
INTEGER(KIND=JPIM),INTENT(IN) :: KANCDY
REAL(KIND=JPRB) ,INTENT(IN) :: PDAYPYEA
REAL(KIND=JPRB) ,INTENT(IN) :: PG
END SUBROUTINE DEPERERR
END INTERFACE
