INTERFACE
SUBROUTINE DEPVEL_WSL (YDMODEL, KIDIA, KFDIA, KLON, KTRAC, KCHEM, KTILES, PFRTI , PGLAT,&
 & PCVL , PCVH ,PLAIL, PLAIH, KTVL, KTVH,&
 & PCRB, PCRL, PCRLU , PCRH, PCRHS,&
 & PTS, PFRSO, PRAQTI, PKCLEV,&
 & PUSTAR, PZ0M, PDEPVELCLIM, PDEPVEL ) 
USE parkind1 ,ONLY : JPIM, JPRB, JPRD
USE TYPE_MODEL , ONLY : MODEL
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) , INTENT(IN) :: KLON, KTRAC, KCHEM
INTEGER(KIND=JPIM) , INTENT(IN) :: KIDIA, KFDIA
INTEGER(KIND=JPIM) , INTENT(IN) :: KTILES
REAL(KIND=JPRB) , DIMENSION (KLON,KTILES), INTENT(IN) :: PFRTI
REAL(KIND=JPRB) , DIMENSION (KLON,KTILES), INTENT(IN) :: PRAQTI
REAL(KIND=JPRB) , DIMENSION (KLON), INTENT(IN) :: PKCLEV
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PTS
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCVL
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCVH
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PLAIL
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PLAIH
INTEGER(KIND=JPIM) , DIMENSION (KLON),INTENT(IN) :: KTVL
INTEGER(KIND=JPIM) , DIMENSION (KLON),INTENT(IN) :: KTVH
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCRB
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCRL
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCRLU
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCRH
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PCRHS
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PFRSO
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PGLAT
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PUSTAR
REAL(KIND=JPRB) , DIMENSION (KLON),INTENT(IN) :: PZ0M
REAL(KIND=JPRB), DIMENSION (KLON, KTRAC), INTENT(IN) :: PDEPVELCLIM
REAL(KIND=JPRB), DIMENSION (KLON, KTRAC), INTENT(OUT) :: PDEPVEL
END SUBROUTINE DEPVEL_WSL
END INTERFACE
