INTERFACE
SUBROUTINE DFI(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDVARBC,YDTCV,YDJOT,YDGOM5,YDODB)
USE TYPE_MODEL ,ONLY : MODEL
USE GEOMETRY_MOD ,ONLY : GEOMETRY
USE FIELDS_MOD ,ONLY : FIELDS
USE MTRAJ_MOD ,ONLY : MTRAJ
USE JO_TABLE_MOD ,ONLY : JO_TABLE
USE VARBC_CLASS ,ONLY : CLASS_VARBC
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE TOVSCV_MOD ,ONLY : TOVSCV
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CLASS_VARBC),INTENT(INOUT) :: YDVARBC
TYPE(CLASS_SUPERGOM), INTENT(INOUT), OPTIONAL :: YDGOM5
CLASS(DBASE), INTENT(INOUT), OPTIONAL :: YDODB
TYPE(TOVSCV) ,INTENT(IN), OPTIONAL :: YDTCV
TYPE(JO_TABLE) ,INTENT(INOUT), OPTIONAL :: YDJOT
END SUBROUTINE DFI
END INTERFACE
