INTERFACE
SUBROUTINE DFI2MOD(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,KSTDFI,PSTEP,KSTDFIA,PSTEPA,LDIFH,YDVARBC,YDTCV)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE PARKIND1 , ONLY : JPIM, JPRB
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_MOD , ONLY : TOVSCV
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTDFI
REAL(KIND=JPRB) ,INTENT(IN) :: PSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTDFIA
REAL(KIND=JPRB) ,INTENT(IN) :: PSTEPA
LOGICAL ,INTENT(IN) :: LDIFH
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(IN) :: YDTCV
END SUBROUTINE DFI2MOD
END INTERFACE
