INTERFACE
SUBROUTINE DIAG_TURB&
 & ( YDECUMF,KIDIA, KFDIA, KLON, KLEV,&
 & LEGWWMS, KLAUNCH,KTYPE, KCTOP,&
 & POROG, POROGSTD, PGAW,&
 & PAP, PAPH, PGEO, PGEOH,&
 & PT, PQ, PU, PV, PVERVEL,&
 & PTDX, PTDY, PUDX, PVDX, PVOR, PDIV,&
 & PTEND_T,PTENOGW_U, PTENOGW_V, PEDRP ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOECUMF , ONLY : TECUMF
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLAUNCH
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP(KLON)
LOGICAL ,INTENT(IN) :: LEGWWMS
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGSTD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVERVEL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTDX(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTDY(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUDX(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDX(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEND_T(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENOGW_U(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENOGW_V(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEDRP(KLON,KLEV,2)
END SUBROUTINE DIAG_TURB
END INTERFACE
