INTERFACE
SUBROUTINE DISTDDH(PCOMM,LDFLAG)
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOMM(7)
LOGICAL ,INTENT(OUT) :: LDFLAG
END SUBROUTINE DISTDDH
END INTERFACE
