INTERFACE
SUBROUTINE DIURNAL(K_MM,K_DD,K_HH,P_DLAT,P_DLON,P_ANGLE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K_MM
INTEGER(KIND=JPIM),INTENT(IN) :: K_DD
INTEGER(KIND=JPIM),INTENT(IN) :: K_HH
REAL(KIND=JPRB) ,INTENT(IN) :: P_DLAT
REAL(KIND=JPRB) ,INTENT(IN) :: P_DLON
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ANGLE
END SUBROUTINE DIURNAL
END INTERFACE
