INTERFACE
SUBROUTINE DIWRGRID_SURF_EXT(YDGEOMETRY,KIOPROC,KNUM,KKIND,KDIM,PREAL,LD_GATHERV)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KIOPROC
INTEGER(KIND=JPIM),INTENT(IN) :: KNUM
INTEGER(KIND=JPIM),INTENT(IN) :: KKIND
REAL(KIND=JPRB) ,INTENT(INOUT) :: PREAL(KDIM)
LOGICAL, INTENT(IN), OPTIONAL :: LD_GATHERV
END SUBROUTINE DIWRGRID_SURF_EXT
END INTERFACE
