INTERFACE
SUBROUTINE DMADDH(YDMDDH,YDPADDH,KMALIST)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMMDDH , ONLY : TMDDH
USE YOMPADDH , ONLY : TPADDH
USE MPL_MODULE
TYPE(TMDDH) ,INTENT(INOUT) :: YDMDDH
TYPE(TPADDH) ,INTENT(INOUT) :: YDPADDH
INTEGER(KIND=JPIM),INTENT(IN) :: KMALIST(YDMDDH%NDHNOM)
END SUBROUTINE DMADDH
END INTERFACE
