INTERFACE
SUBROUTINE DOPPLSIM_TL(KFLEVG,ROBODY,SATHDR,SATBODY,&
 & KDLEN,KDBDY,KLEN,KDCOUNT,KCOUNT,KPNLV,PUF,PVF,PGEOPH5,PXPP) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY,SATHDR,SATBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN,KDBDY,KLEN,KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN),DIMENSION(KDLEN) :: KCOUNT
INTEGER(KIND=JPIM),INTENT(IN),DIMENSION(KDLEN,KDBDY) :: KPNLV
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG) :: PUF,PVF
REAL(KIND=JPRB),INTENT(OUT), DIMENSION(KDLEN,KDCOUNT) :: PXPP
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,0:KFLEVG) :: PGEOPH5
END SUBROUTINE DOPPLSIM_TL
END INTERFACE
