INTERFACE
SUBROUTINE DOT_PRODUCT_CTLVEC(YDGEOMETRY,YDCV1,YDCV2,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,&
 & LDNORM) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE CONTROL_VECTORS_BASE_MIX, ONLY : CONTROL_VECTOR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(CONTROL_VECTOR),INTENT(IN) :: YDCV1
TYPE(CONTROL_VECTOR),INTENT(IN) :: YDCV2
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD1
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD2
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD3
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD4
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD5
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD6
REAL(KIND=JPRB) ,INTENT(OUT) :: PROD7
LOGICAL ,INTENT(IN) :: LDNORM
END SUBROUTINE DOT_PRODUCT_CTLVEC
END INTERFACE
