INTERFACE
SUBROUTINE DPRECIPS_OLD(KIDIA,KFDIA,KLON,KDTPREC,PDPRECIPS,PXPTYPE,PXPTYPESEV)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KDTPREC
REAL(KIND=JPRB) ,INTENT(IN) :: PDPRECIPS(KLON,KDTPREC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXPTYPE(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXPTYPESEV(KLON)
END SUBROUTINE DPRECIPS_OLD
END INTERFACE
