INTERFACE
SUBROUTINE DRESDDH(YDDIMV,YDMDDH,YDPADDH,PRESULT,KTID,KMASK)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMMDDH , ONLY : TMDDH
USE YOMPADDH , ONLY : TPADDH
USE MPL_MODULE
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TMDDH) ,INTENT(INOUT) :: YDMDDH
TYPE(TPADDH) ,INTENT(INOUT) :: YDPADDH
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRESULT((YDDIMV%NFLEVG+1)*(YDMDDH%NDHCVSU+YDMDDH%NDHVV)&
 & +YDMDDH%NDHCSSU+YDMDDH%NDHVS+YDMDDH%NDHVFS+1) 
INTEGER(KIND=JPIM),INTENT(IN) :: KTID
INTEGER(KIND=JPIM),INTENT(IN) :: KMASK
END SUBROUTINE DRESDDH
END INTERFACE
