INTERFACE
SUBROUTINE DUCTDIA ( KIDIA, KFDIA, KLON, KLEV,&
 & PT, PQ, PAP, PGEOM1,&
 & PREFRAC, PDNDZ_MIN, PDNDZ_AVG,&
 & PZDCBOT, PZTLBOT, PZTLTOP) 
USE PARKIND1 , ONLY: JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
REAL (KIND=JPRB) , INTENT(IN) :: PT(KLON,KLEV)
REAL (KIND=JPRB) , INTENT(IN) :: PQ(KLON,KLEV)
REAL (KIND=JPRB) , INTENT(IN) :: PAP(KLON,KLEV)
REAL (KIND=JPRB) , INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL (KIND=JPRB) , INTENT(OUT) :: PREFRAC(KLON,KLEV)
REAL (KIND=JPRB) , INTENT(OUT) :: PDNDZ_MIN(KLON)
REAL (KIND=JPRB) , INTENT(OUT) :: PDNDZ_AVG(KLON)
REAL (KIND=JPRB) , INTENT(OUT) :: PZDCBOT(KLON)
REAL (KIND=JPRB) , INTENT(OUT) :: PZTLBOT(KLON)
REAL (KIND=JPRB) , INTENT(OUT) :: PZTLTOP(KLON)
END SUBROUTINE DUCTDIA
END INTERFACE
