INTERFACE
SUBROUTINE DVERINT(KPROMA,KSTART,KPROF,KFLEV_IN,KFLEV_OUT,PINTE,PIN,POUT,KTYPE)
USE PARKIND1 ,ONLY : JPRD, JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV_IN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV_OUT
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRD) ,INTENT(IN) :: PINTE(KFLEV_OUT,KFLEV_IN)
REAL(KIND=JPRD) ,INTENT(IN) :: PIN(KPROMA,KFLEV_IN)
REAL(KIND=JPRD) ,INTENT(OUT) :: POUT(KPROMA,KFLEV_OUT)
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE
END SUBROUTINE DVERINT
END INTERFACE
