INTERFACE
SUBROUTINE DYNFPOS(YDQTYPE,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,YDAFN,KFPXFLD,YDFPGEOMETRY,YDFPWSTD,YDFPSTRUCT,KFPDOM,&
 & LDHPOS,LDEZO,YDGEOMETRY,YDGMV,YDGFL,YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,CDVCONF,KPXLEV,PXLEV,&
 & PBUF,PGPP,PAUX,P2DFIELDS,P3DFIELDS,P3DPHYS,KP3FIELDS) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMGMV , ONLY : TGMV
USE YOMGFL , ONLY : TGFL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMXFU , ONLY : TXFU
USE TYPE_MODEL , ONLY : MODEL
USE YOMFPGEOMETRY , ONLY : TFPGEOMETRY, LFPOSBUF, LFPDISTRIB
USE YOMFPC , ONLY : TNAMFPSCI, TNAMFPINT, LALLOFP
USE YOMWFPB , ONLY : TFPWSTD
USE YOMAFN , ONLY : TAFN
USE TYPE_FPOSBUF , ONLY : FPOSBUF
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(FPOSBUF) ,INTENT(IN) :: YDCLIMO
TYPE(TNAMFPINT), INTENT(IN) :: YDNAMFPINT
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN) ,INTENT(IN) :: YDAFN
INTEGER(KIND=JPIM),INTENT(IN) :: KFPXFLD
TYPE(TFPGEOMETRY), INTENT(IN) :: YDFPGEOMETRY
TYPE(TFPWSTD), INTENT(IN) :: YDFPWSTD
TYPE(SL_STRUCT), INTENT(IN) :: YDFPSTRUCT
INTEGER(KIND=JPIM),INTENT(IN) :: KFPDOM
LOGICAL ,INTENT(IN) :: LDHPOS
LOGICAL ,INTENT(IN) :: LDEZO
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(IN) :: YDGMV
TYPE(TGFL) ,INTENT(IN) :: YDGFL
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(TXFU) ,INTENT(IN) :: YDXFU
INTEGER(KIND=JPIM),INTENT(IN) :: KCUFNR
REAL(KIND=JPRB), INTENT(IN) :: PMCUFGP(YDGEOMETRY%YRDIM%NPROMA,KCUFNR,YDGEOMETRY%YRDIM%NGPBLKS)
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
CHARACTER(LEN=1) ,INTENT(IN) :: CDVCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KPXLEV
REAL(KIND=JPRB), INTENT(IN) :: PXLEV(KPXLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KP3FIELDS
REAL(KIND=JPRB) ,POINTER, INTENT(OUT) :: PBUF(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE, INTENT(INOUT), OPTIONAL :: PGPP(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE, INTENT(INOUT), OPTIONAL :: PAUX(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE, TARGET, INTENT(INOUT), OPTIONAL :: P2DFIELDS(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE, TARGET, INTENT(INOUT), OPTIONAL :: P3DFIELDS(:,:,:,:)
REAL(KIND=JPRB) ,TARGET, INTENT(INOUT), OPTIONAL :: P3DPHYS(YDFPGEOMETRY%YFPGEO%NFPROMA,KPXLEV,KP3FIELDS,YDFPGEOMETRY%YFPGEO%NFPBLOCS)
END SUBROUTINE DYNFPOS
END INTERFACE
