INTERFACE
SUBROUTINE EADD_PERT_SST(YDEGEO,PS,PERRPS,KINJQ,KINIQ,KF)
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE YEMGEO , ONLY : TEGEO
 USE RANDOM_NUMBERS_MIX
 TYPE(TEGEO), INTENT(IN) :: YDEGEO
 REAL(KIND=JPRB), INTENT(INOUT) :: PS(:)
 REAL(KIND=JPRB), INTENT(IN) :: PERRPS(:)
 INTEGER(KIND=JPIM), INTENT(IN) :: KINJQ, KINIQ
 INTEGER(KIND=JPIM), INTENT(IN) :: KF
END SUBROUTINE EADD_PERT_SST
END INTERFACE
