INTERFACE
SUBROUTINE EC_PHYS_TL(YDGEOMETRY,YDGMV,YDSURF,YDMODEL,KBL,KNUMB,KSTGLO,KIBL,&
 & PB2,&
 & PGMV,PGMVS,PGFL,PGFL5,&
 & PGMVT1,PGMVT1S,PGFLT1,&
 & PSP_SB,PSP_SG,PSP_RR,&
 & PSD_VN,PSD_VD,YDTILEPROP,YDPHYSMWAVE,&
 & PFORCEU,PFORCEV,PFORCET,PFORCEQ,&
 & PII0,&
 & PTRAJ_PHYS,&
 & PGPHIST,PTRAJ_PHYS_TLAD,PTRAJ_SRFC,PTRAJ_CST,&
 & PTRAJ_RAINGG_TLAD,&
 & PHYS_MWAVE5,YDACV) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF, GPPOPER, GPOPER
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOE_TILE_PROP , ONLY : TETILEPROP
USE YOE_PHYS_MWAVE , ONLY : TEPHYSMWAVE, N_PHYS_MWAVE
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE, TRAJ_PHYS_TLAD_TYPE,&
 & TRAJ_CST_TYPE, TRAJ_SRFC_TYPE, NGP5, NTRAJ_CST, TRAJ_RAINGG_TLAD_TYPE,&
 & LPRTTRAJ 
USE YOMSPHYHIST , ONLY : SPHYS_HIST_TYPE
USE TYPE_ACV , ONLY : ACV_CONTAINER
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KBL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNUMB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIBL
REAL(KIND=JPRB) ,INTENT(IN) :: PB2(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & YDMODEL%YRML_GCONF%YGFL%NDIM5) 
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & YDMODEL%YRML_GCONF%YGFL%NDIM1) 
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP_SB(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SBD%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP_SG(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_SGD%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP_RR(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_RRD%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSD_VN(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VND%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSD_VD(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VDD%NDIM)
TYPE(TETILEPROP) ,INTENT(INOUT) :: YDTILEPROP
TYPE(TEPHYSMWAVE) ,INTENT(INOUT) :: YDPHYSMWAVE
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEU(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCET(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEQ(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) , INTENT(IN) :: PII0
TYPE (TRAJ_PHYS_TYPE) ,INTENT(IN) :: PTRAJ_PHYS
TYPE (SPHYS_HIST_TYPE) ,INTENT(INOUT) :: PGPHIST
TYPE (TRAJ_PHYS_TLAD_TYPE) ,INTENT(INOUT) :: PTRAJ_PHYS_TLAD
TYPE (TRAJ_SRFC_TYPE) ,INTENT(IN) :: PTRAJ_SRFC
TYPE (TRAJ_CST_TYPE) ,INTENT(IN) :: PTRAJ_CST
TYPE (TRAJ_RAINGG_TLAD_TYPE),INTENT(INOUT) :: PTRAJ_RAINGG_TLAD
REAL(KIND=JPRB) ,INTENT(INOUT),OPTIONAL :: PHYS_MWAVE5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,N_PHYS_MWAVE)
TYPE(ACV_CONTAINER),INTENT(INOUT),OPTIONAL :: YDACV
END SUBROUTINE EC_PHYS_TL
END INTERFACE
