INTERFACE
SUBROUTINE ECR2DF(KUL,CDNOMA,PTAB,KLONLOC,KLON,KLEV)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KUL
CHARACTER(LEN=*),INTENT(IN) :: CDNOMA
REAL(KIND=JPRB) ,INTENT(IN) :: PTAB(KLON,0:KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KLONLOC
END SUBROUTINE ECR2DF
END INTERFACE
