INTERFACE
SUBROUTINE ECRADFR(YDDIM,YDML_PHY_RAD,YDRIP)
USE MODEL_PHYSICS_RADIATION_MOD , ONLY : MODEL_PHYSICS_RADIATION_TYPE
USE YOMDIM , ONLY : TDIM
USE YOMRIP , ONLY : TRIP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(MODEL_PHYSICS_RADIATION_TYPE),INTENT(INOUT):: YDML_PHY_RAD
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE ECRADFR
END INTERFACE
