INTERFACE
SUBROUTINE ECRPNEBH(KUL,CDNOMA,PNEBH,KLONLOC,KLON,KNEBH)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KNEBH
INTEGER(KIND=JPIM),INTENT(IN) :: KUL
CHARACTER(LEN=*) ,INTENT(IN) :: CDNOMA
REAL(KIND=JPRB) ,INTENT(IN) :: PNEBH(KLON,KNEBH)
INTEGER(KIND=JPIM),INTENT(IN) :: KLONLOC
END SUBROUTINE ECRPNEBH
END INTERFACE
