INTERFACE
SUBROUTINE ECSET(YDODB,KTSLOTNO,KOBTOT,KOFFTOT,KSETOT,KTYPOB,KLNSET,KMXBDY,KSUMBDY,KTSLSET,KMAPOMM,PZENITH,LDTHSAFE_REPLICATION)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
USE DBASE_MOD, ONLY : DBASE
CLASS(DBASE), INTENT(INOUT) :: YDODB
INTEGER(KIND=JPIM),INTENT(IN) :: KTSLOTNO
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTOT
INTEGER(KIND=JPIM),INTENT(IN) :: KOFFTOT
INTEGER(KIND=JPIM),INTENT(OUT) :: KSETOT
INTEGER(KIND=JPIM),INTENT(OUT) :: KTYPOB(:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLNSET(:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KMXBDY(:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KSUMBDY(:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KTSLSET(:)
INTEGER(KIND=JPIM),INTENT(OUT),POINTER :: KMAPOMM(:,:)
REAL(KIND=JPRB), INTENT(OUT),POINTER :: PZENITH(:,:)
LOGICAL, OPTIONAL, INTENT(IN) :: LDTHSAFE_REPLICATION
END SUBROUTINE ECSET
END INTERFACE
