INTERFACE
SUBROUTINE EGPLOC(YDGEOMETRY,PGP3,PGP2)
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 USE PARKIND1 , ONLY : JPIM, JPRB
 TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
 REAL(KIND=JPRB), INTENT(INOUT) :: PGP3(:,:,:)
 REAL(KIND=JPRB), INTENT(INOUT) :: PGP2(:,:)
END SUBROUTINE EGPLOC
END INTERFACE
