INTERFACE
SUBROUTINE EIGENMD(PMATRIX,PMODES,PEIGENV,KDIM,LDEVI,LDEVN,LDEVZ)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
REAL(KIND=JPRB) ,INTENT(IN) :: PMATRIX(KDIM,KDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMODES(KDIM,KDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEIGENV(KDIM)
LOGICAL ,INTENT(OUT) :: LDEVI
LOGICAL ,INTENT(OUT) :: LDEVN
LOGICAL ,INTENT(OUT) :: LDEVZ
END SUBROUTINE EIGENMD
END INTERFACE
