INTERFACE
SUBROUTINE EMIS_MW_N(K_ISENSOR,PANGL,PLS,PTS,PSN,PWS,PIC,&
 & P23R,P31R,P50R,P89R ,K_ISUR_M , PEM) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDIMO , ONLY : NMXTCH
INTEGER(KIND=JPIM),INTENT(IN) :: K_ISENSOR
REAL(KIND=JPRB) ,INTENT(IN) :: PANGL
REAL(KIND=JPRB) ,INTENT(IN) :: PLS
REAL(KIND=JPRB) ,INTENT(IN) :: PTS
REAL(KIND=JPRB) ,INTENT(IN) :: PSN
REAL(KIND=JPRB) ,INTENT(IN) :: PWS
REAL(KIND=JPRB) ,INTENT(IN) :: PIC
REAL(KIND=JPRB) ,INTENT(IN) :: P23R
REAL(KIND=JPRB) ,INTENT(IN) :: P31R
REAL(KIND=JPRB) ,INTENT(IN) :: P50R
REAL(KIND=JPRB) ,INTENT(IN) :: P89R
INTEGER(KIND=JPIM),INTENT(OUT) :: K_ISUR_M
REAL(KIND=JPRB) ,INTENT(OUT) :: PEM(NMXTCH)
END SUBROUTINE EMIS_MW_N
END INTERFACE
