INTERFACE
SUBROUTINE EMIS_IR_ATLAS(K_ISENSOR,PLS,PLAT,PLON,PEM)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMDIMO , ONLY : NMXTCH
INTEGER(KIND=JPIM),INTENT(IN) :: K_ISENSOR
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
REAL(KIND=JPRB) ,INTENT(IN) :: PLS
REAL(KIND=JPRB) ,INTENT(OUT) :: PEM(NMXTCH)
END SUBROUTINE EMIS_IR_ATLAS
END INTERFACE
