INTERFACE
SUBROUTINE EMIS_IR(PLS,PTS,PSN,PWS,PEM)
USE PARKIND1 ,ONLY : JPRB
USE YOMDIMO , ONLY : NMXTCH
REAL(KIND=JPRB) ,INTENT(IN) :: PLS
REAL(KIND=JPRB) ,INTENT(IN) :: PTS
REAL(KIND=JPRB) ,INTENT(IN) :: PSN
REAL(KIND=JPRB) ,INTENT(IN) :: PWS
REAL(KIND=JPRB) ,INTENT(OUT) :: PEM(NMXTCH)
END SUBROUTINE EMIS_IR
END INTERFACE
