INTERFACE
SUBROUTINE EMPTB(KWRDS,POUT,PBUF,KSTA)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KWRDS
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT(KWRDS)
REAL(KIND=JPRB) ,INTENT(IN) :: PBUF(:)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSTA
END SUBROUTINE EMPTB
END INTERFACE
