INTERFACE
SUBROUTINE ENDVPOS(YDCST, KLMOD,YDQTYPE,YDAUX,YDCLIMO,YDNAMFPSCI,YDAFN,YDFPGEO,YDFPVAB,YDGEOMETRY,YDML_GCONF,YDML_PHY_MF,LDZ0H,CDCONF,&
 & KPXLEV,PXLEV,PABUF,KCUFNR,KAPTR,PGP,PFP) 
USE YOMVERT , ONLY : TVAB
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMFPGEO, ONLY : TFPGEO
USE TYPE_FPOSBUF, ONLY : FPOSBUF
USE YOMFPC , ONLY : TNAMFPSCI
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
USE YOMAFN, ONLY : TAFN
USE YOMCST , ONLY : TCST
USE PARFPOS , ONLY : JPOSDYN
TYPE (TCST), INTENT (IN) :: YDCST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLMOD(JPOSDYN)
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE (FPOSBUF), INTENT(IN) :: YDAUX
TYPE (FPOSBUF), INTENT(IN) :: YDCLIMO
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE (TAFN), INTENT(IN) :: YDAFN
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO
TYPE(TVAB) ,INTENT(IN) :: YDFPVAB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN) :: YDML_PHY_MF
LOGICAL ,INTENT(IN) :: LDZ0H
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KPXLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PXLEV(KPXLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PABUF(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KCUFNR
INTEGER(KIND=JPIM),INTENT(IN) :: KAPTR(JPOSDYN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGP(YDFPGEO%NFPROMA,YDQTYPE%NFPAUXB,YDFPGEO%NFPBLOCS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFP(YDFPGEO%NFPROMA,YDQTYPE%NFPGT1,YDFPGEO%NFPBLOCS)
END SUBROUTINE ENDVPOS
END INTERFACE
