INTERFACE
SUBROUTINE ERRSTAT(KOBTYP,KOBSQNO,KCDTYP,KCDSQNO,PLAT,PLON,PTIMDIF,&
 & KVNM,KSTAT,PPRES,PPRL,&
 & PPERR,POERR,PFERR,PWEIGHT) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSQNO
INTEGER(KIND=JPIM),INTENT(IN) :: KCDTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KCDSQNO
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
REAL(KIND=JPRB) ,INTENT(IN) :: PTIMDIF
INTEGER(KIND=JPIM),INTENT(IN) :: KVNM
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSTAT
REAL(KIND=JPRB) ,INTENT(IN) :: PPRES
REAL(KIND=JPRB) ,INTENT(IN) :: PPRL
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPERR
REAL(KIND=JPRB) ,INTENT(INOUT) :: POERR
REAL(KIND=JPRB) ,INTENT(OUT) :: PFERR
REAL(KIND=JPRB) ,INTENT(IN) :: PWEIGHT
END SUBROUTINE ERRSTAT
END INTERFACE
