INTERFACE
SUBROUTINE EVJCDFI(YDGEOMETRY,YDDIMF,YDDYN,KULOUT,LDPRT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDIMF , ONLY : TDIMF
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDIMF) ,INTENT(INOUT) :: YDDIMF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
LOGICAL ,INTENT(IN) :: LDPRT
END SUBROUTINE EVJCDFI
END INTERFACE
