INTERFACE
SUBROUTINE EXCHCOAD(&
 & YDPHY0,KPROMA,KIDIA,KFDIA,&
 & PQ5,PT5,PAPHI5,PAPHIH5,PR5,PTS5,&
 & PQ,PT,PAPHI,PAPHIH,PR,PTS,&
 & PUB5,PVB5,PAZO5,&
 & PUB,PVB,PAZO,&
 & PWET5,PQS5,&
 & PWET,PQS,&
 & PRI5,&
 & PBN,PBM,PBH) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHY0 , ONLY : TPHY0
TYPE(TPHY0) ,INTENT(INOUT) :: YDPHY0
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIH5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PR5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHIH(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUB5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVB5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAZO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUB(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVB(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAZO(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWET5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWET(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBN(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBH(KPROMA)
END SUBROUTINE EXCHCOAD
END INTERFACE
