INTERFACE
SUBROUTINE EXHEIZ2P_LIDAR(ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,&
 & LDGETDB,KDIM1,KDIM2,KOBS,KSET,KCOUNT,PHEIGH,LDZORPHI) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
LOGICAL ,INTENT(IN) :: LDGETDB
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM1
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM2
INTEGER(KIND=JPIM),INTENT(IN) :: KOBS
INTEGER(KIND=JPIM),INTENT(IN) :: KSET
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCOUNT(KDIM1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHEIGH(KDIM1,KDIM2)
LOGICAL ,INTENT(IN) :: LDZORPHI
END SUBROUTINE EXHEIZ2P_LIDAR
END INTERFACE
