INTERFACE
SUBROUTINE EXPBESU(KPROMA,KSTART,KPROF,KFLEV,KLEVP,KLOLEV,&
 & PZO,LDBELS,LDBLES,POROG,&
 & PRESH,PT,&
 & PPPP) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PZO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELS(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBLES(KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPPP(KPROMA,KLEVP)
END SUBROUTINE EXPBESU
END INTERFACE
