INTERFACE
SUBROUTINE FGER_INFO(MNVARS,MFIELDS,MNLEVS,IFLDOFF,TFGER)
 USE PARKIND1 , ONLY : JPIM, JPRB
 USE YOMFGER , ONLY : TYPE_FGER_INFO
 INTEGER(KIND=JPIM), INTENT(IN) :: MNVARS
 INTEGER(KIND=JPIM), INTENT(IN) :: MFIELDS(:)
 INTEGER(KIND=JPIM), INTENT(IN) :: MNLEVS(:)
 INTEGER(KIND=JPIM), INTENT(INOUT) :: IFLDOFF(:)
 TYPE(TYPE_FGER_INFO), INTENT(OUT) :: TFGER
END SUBROUTINE FGER_INFO
END INTERFACE
