INTERFACE
SUBROUTINE FIELDS_FP_CHANGE_RESOL(YDFPDATA,YDFIELDS_IN,YDFIELDS_OUT,YDFIELDS_BASE)
USE FULLPOS , ONLY : TFPDATA
USE FIELDS_MOD , ONLY : FIELDS, FIELDS_CREATE, FIELDS_DELETE, FIELDS_ZEROS
TYPE(TFPDATA) ,INTENT(IN) :: YDFPDATA
TYPE(FIELDS) ,INTENT(IN) :: YDFIELDS_IN
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS_OUT
TYPE(FIELDS) ,INTENT(INOUT), OPTIONAL :: YDFIELDS_BASE
END SUBROUTINE FIELDS_FP_CHANGE_RESOL
END INTERFACE
