INTERFACE
SUBROUTINE FINAL_STATS(CDLABEL,KSTEP)
USE PARKIND1 , ONLY : JPIM, JPIB, JPRB, JPRD
CHARACTER(LEN=*), INTENT(IN) :: CDLABEL
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
END SUBROUTINE FINAL_STATS
END INTERFACE
