INTERFACE
SUBROUTINE FINDL(PCMPPP,KSTDLE,PDIFF)
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PCMPPP
INTEGER(KIND=JPIM),INTENT(OUT) :: KSTDLE
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFF
END SUBROUTINE FINDL
END INTERFACE
