INTERFACE
SUBROUTINE FINOEREV(PERERR,POBSERR,PMDI,PFINOERR)
USE PARKIND1 ,ONLY : JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PERERR
REAL(KIND=JPRB) ,INTENT(IN) :: POBSERR
REAL(KIND=JPRB) ,INTENT(IN) :: PMDI
REAL(KIND=JPRB) ,INTENT(OUT) :: PFINOERR
END SUBROUTINE FINOEREV
END INTERFACE
