INTERFACE
SUBROUTINE FIREINJ(YDGEOMETRY, YDSURF, YDCOMPO,YDML_GCONF,YDPHY2,KIDIA, KFDIA, KLON, KLEV, KSTGLO, KTRAC, PDELP, PAPHIF,&
 & PFLUX ,PTENC,PINJF, PBLH, PCO2F, PCH4F) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCOMPO , ONLY : TCOMPO
USE YOMPHY2 , ONLY : TPHY2
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TCOMPO) ,INTENT(INOUT) :: YDCOMPO
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA , KFDIA , KLON , KLEV, KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PINJF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PBLH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO2F(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCH4F(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLUX(KLON,KTRAC)
END SUBROUTINE FIREINJ
END INTERFACE
