INTERFACE
SUBROUTINE FLGTST(ROBHDR,ROBODY,SATBODY,YDSETINFO)
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY : TYPE_SET_INFO
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATBODY
TYPE(TYPE_SET_INFO),INTENT(IN) :: YDSETINFO
END SUBROUTINE FLGTST
END INTERFACE
