INTERFACE
SUBROUTINE FLTBGCALC(YDDIMV,YDDIMF)
USE YOMDIMV , ONLY : TDIMV
USE YOMDIMF , ONLY : TDIMF
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TDIMF) ,INTENT(INOUT):: YDDIMF
END SUBROUTINE FLTBGCALC
END INTERFACE
