INTERFACE
SUBROUTINE FLTBGCALC_CRT(YDGEOMETRY,PSP2VAR,PSP3VAR,PGP2M4,PGP3M4)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1, ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB),INTENT(INOUT) :: PSP2VAR(:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PSP3VAR(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP2M4(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP3M4(:,:,:,:)
END SUBROUTINE FLTBGCALC_CRT
END INTERFACE
