INTERFACE
SUBROUTINE FP_SERV_SUIOSCTMPL (YDFPS, YDGEOMETRY)
USE YOMFP_SERV, ONLY : FP_SERV, FP_SERV_DISTR
USE GEOMETRY_MOD, ONLY : GEOMETRY
TYPE (FP_SERV), INTENT (INOUT), TARGET :: YDFPS
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
END SUBROUTINE FP_SERV_SUIOSCTMPL
END INTERFACE
