INTERFACE
SUBROUTINE FP_SERV_SYNC(PTSTEP,YDFPS,KTYPE,CDNAME,LDSTOP)
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMFP_SERV, ONLY : FP_SERV,&
 & NFP_SERV_SYN_TYPE_CLO,&
 & NFP_SERV_SYN_TYPE_STO 
REAL(KIND=JPRB), INTENT (IN) :: PTSTEP
TYPE (FP_SERV), INTENT (INOUT) :: YDFPS
INTEGER (KIND=JPIM), INTENT (IN) :: KTYPE
CHARACTER (LEN=*), INTENT (IN) :: CDNAME
LOGICAL, OPTIONAL, INTENT (IN) :: LDSTOP
END SUBROUTINE FP_SERV_SYNC
END INTERFACE
