INTERFACE
SUBROUTINE FP_SERV_CPFPFILTER (YDFPS, YDGEOMETRY, YDFPFILTERS)
USE YOMFP_SERV, ONLY : FP_SERV
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMFPFILTERS, ONLY : TFPFILTERS
TYPE (FP_SERV), INTENT (INOUT), TARGET :: YDFPS
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE (TFPFILTERS),INTENT (INOUT) :: YDFPFILTERS
END SUBROUTINE FP_SERV_CPFPFILTER
END INTERFACE
