INTERFACE
SUBROUTINE FPCICA(YDML_PHY_MF,KST,KEND,KPROMA,KLEV,KCAPETYPE,LDMUL,PENTRA,PMLDEP,PTCLS,PRPCLS,PRHCLS,PT,PRP,&
 & PQV,PCAPE,PTCVS,PCIN,KLCL,KFCL,KEL,PMLCAPE) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KCAPETYPE
LOGICAL ,INTENT(IN) :: LDMUL
REAL(KIND=JPRB) ,INTENT(IN) :: PENTRA
REAL(KIND=JPRB) ,INTENT(IN) :: PMLDEP
REAL(KIND=JPRB) ,INTENT(IN), TARGET :: PTCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRP(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQV(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCVS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PCIN(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(OUT), OPTIONAL :: KLCL(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(OUT), OPTIONAL :: KFCL(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(OUT), OPTIONAL :: KEL(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PMLCAPE(KPROMA)
END SUBROUTINE FPCICA
END INTERFACE
