INTERFACE
SUBROUTINE FPCINCAPE(YDTOPH,KST,KEND,KPROMA,KLEV,KLEVST,PENTRA,PMLDEP,PT,PRP,PQV,PCAPE,PCIN,KLCL,KFCL,KLNB)
USE PARKIND1 ,ONLY : JPIM ,JPRB , JPRD
USE YOMTOPH, ONLY : TTOPH
TYPE(TTOPH) ,INTENT(IN) :: YDTOPH
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVST
REAL(KIND=JPRB) ,INTENT(IN) :: PENTRA
REAL(KIND=JPRB) ,INTENT(IN) :: PMLDEP
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRP(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQV(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCIN(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KLCL(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KFCL(KPROMA)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KLNB(KPROMA)
END SUBROUTINE FPCINCAPE
END INTERFACE
