INTERFACE
SUBROUTINE FPCLIPHY(YDRQCLI,YDGFP,KFLD,KCOD,KST,KEND,KFPROMA,PCLI,PROW,LDCLI)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMFP4L, ONLY : TRQFP, IFPSEARCH
USE YOMAFN , ONLY : ALL_FPDSPHY_TYPES
TYPE (TRQFP), INTENT(IN) :: YDRQCLI
TYPE(ALL_FPDSPHY_TYPES), INTENT(IN) :: YDGFP
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
INTEGER(KIND=JPIM),INTENT(IN) :: KCOD(KFLD)
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PCLI(KFPROMA,0:YDRQCLI%NFIELDG)
REAL(KIND=JPRB) ,INTENT(OUT) , OPTIONAL :: PROW(KFPROMA,KFLD)
LOGICAL ,INTENT(OUT) , OPTIONAL :: LDCLI(KFLD)
END SUBROUTINE FPCLIPHY
END INTERFACE
