INTERFACE
SUBROUTINE FPCORPHY(YDRQCLI,YDNAMFPSCI,YDAFN,YDEPHY,YDPHY,YDPHY1,KST,KEND,KFPROMA,LDFPOSHOR,KFIELDS,KCOD,PROW,KAUX,PAUX,YDRQAUX,&
 & KCLI,PCLI,PWSXI,PWDXI,LDALT,KWIC) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMAFN , ONLY : TAFN
USE YOMFPC , ONLY : TNAMFPSCI
USE YOMPHY1 , ONLY : TPHY1
USE YOMPHY , ONLY : TPHY
USE YOEPHY , ONLY : TEPHY
USE YOMFP4L , ONLY : TRQFP, IFPSEARCH
TYPE(TRQFP) ,INTENT(IN) :: YDRQCLI
TYPE(TNAMFPSCI) ,INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN) ,INTENT(IN) :: YDAFN
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TPHY1) ,INTENT(IN) :: YDPHY1
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
LOGICAL ,INTENT(IN) :: LDFPOSHOR
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),INTENT(IN) :: KCOD(KFIELDS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PROW(KFPROMA,KFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KAUX
REAL(KIND=JPRB) ,INTENT(IN) :: PAUX(KFPROMA,KAUX)
TYPE(TRQFP),INTENT(IN) :: YDRQAUX
INTEGER(KIND=JPIM),INTENT(IN) :: KCLI
REAL(KIND=JPRB) ,INTENT(IN) :: PCLI(KFPROMA,0:KCLI)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSXI
REAL(KIND=JPRB) ,INTENT(IN) :: PWDXI
LOGICAL ,INTENT(IN), OPTIONAL :: LDALT
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KWIC(KFPROMA)
END SUBROUTINE FPCORPHY
END INTERFACE
