INTERFACE
SUBROUTINE FPHOR12(KFLD,KST,KEND,PROW,KFLDROW,KFPROMA,KORR,PSEA,&
 & PLSM,PMIN,PMAX,PSCAL,PTT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDROW
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(INOUT) :: PROW(KFPROMA,KFLDROW)
INTEGER(KIND=JPIM),INTENT(IN) :: KORR
REAL(KIND=JPRB) ,INTENT(IN) :: PSEA(KFPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KFPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PMIN(KFPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PMAX(KFPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSCAL(KFPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT(KFPROMA)
END SUBROUTINE FPHOR12
END INTERFACE
