INTERFACE
SUBROUTINE FPINT4(KASLB1,KFPROW,KFIELDS,KGPST,KGPEND,KFPROMA,KFLDBUF,KDER,&
 & KDMP,LDML,LDNRST,KBOX,KL0,PWXX,PWXY,LDMASK,PBUF,PROW,PUNDEF) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KASLB1
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROW
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDBUF
INTEGER(KIND=JPIM),INTENT(IN) :: KGPST
INTEGER(KIND=JPIM),INTENT(IN) :: KGPEND
INTEGER(KIND=JPIM),INTENT(IN) :: KDER(KFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KDMP(KFLDBUF)
LOGICAL ,INTENT(IN) :: LDML
LOGICAL ,INTENT(IN) :: LDNRST(KFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KBOX(KGPEND)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KFPROMA,KFPROW)
REAL(KIND=JPRB) ,INTENT(IN) :: PWXX(KFPROMA,4)
REAL(KIND=JPRB) ,INTENT(IN) :: PWXY(KFPROMA,5:16)
LOGICAL ,INTENT(IN) :: LDMASK(KFIELDS)
REAL(KIND=JPRB) ,INTENT(IN) :: PBUF(KASLB1*KFLDBUF)
REAL(KIND=JPRB) ,INTENT(OUT) :: PROW(KFPROMA,KFIELDS)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PUNDEF
END SUBROUTINE FPINT4
END INTERFACE
