INTERFACE
SUBROUTINE FPOSHOR(YDQTYPE,YDNAMFPINT,YDTFP_DYNDS,YDFPGEOMETRY,YDFPWSTD,YDFPSTRUCT,YDFPGEO_DEP,KFLDIN,PBUF1,KFLDOUT,PFP)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMFPGEOMETRY, ONLY : TFPGEOMETRY
USE YOMFPGEO , ONLY : TFPGEO
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMWFPB , ONLY : TFPWSTD
USE FULLPOS_MIX , ONLY : FULLPOS_TYPE
USE YOMFPC , ONLY : TNAMFPINT
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(TNAMFPINT), INTENT(IN) :: YDNAMFPINT
TYPE(FULLPOS_TYPE),INTENT(IN) :: YDTFP_DYNDS(:)
TYPE (TFPGEOMETRY),INTENT(IN) :: YDFPGEOMETRY
TYPE (TFPWSTD), INTENT(IN) :: YDFPWSTD
TYPE(SL_STRUCT), INTENT(IN) :: YDFPSTRUCT
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO_DEP
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDIN
REAL(KIND=JPRB), INTENT(IN) :: PBUF1(YDFPSTRUCT%NASLB1*KFLDIN)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDOUT
REAL(KIND=JPRB), INTENT(OUT) :: PFP(YDFPGEO_DEP%NFPROMA,KFLDOUT,YDFPGEO_DEP%NFPBLOCS)
END SUBROUTINE FPOSHOR
END INTERFACE
