INTERFACE
SUBROUTINE FPOSHORPHY(YDRQPHY,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,YDAFN,YDFPGEOMETRY,YDFPSUW,YDFPWSTD,YDFPSTRUCT,YDFPGEO_DEP,&
 & KFLDIN,PBUF1,KCOD,PFP,YDRQAUX) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMFPGEOMETRY, ONLY : TFPGEOMETRY
USE YOMFPGEO , ONLY : TFPGEO
USE TYPE_FPOSBUF , ONLY : FPOSBUF
USE YOMFPC , ONLY : TNAMFPINT, TNAMFPSCI
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMWFPB , ONLY : TFPWSTD, TFPSUW
USE YOMAFN , ONLY : TAFN
USE YOMFP4L, ONLY : TRQFP
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
TYPE (FPOSBUF) , INTENT(IN) :: YDCLIMO
TYPE (TNAMFPINT), INTENT(IN) :: YDNAMFPINT
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN), INTENT(IN) :: YDAFN
TYPE (TFPGEOMETRY),INTENT(IN) :: YDFPGEOMETRY
TYPE (TFPSUW), INTENT(IN) :: YDFPSUW
TYPE (TFPWSTD), INTENT(IN) :: YDFPWSTD
TYPE(SL_STRUCT), INTENT(IN) :: YDFPSTRUCT
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO_DEP
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDIN
REAL(KIND=JPRB), INTENT(IN) :: PBUF1(YDFPSTRUCT%NASLB1*KFLDIN)
INTEGER(KIND=JPIM), INTENT(IN) :: KCOD(YDRQPHY%NFIELDG)
REAL(KIND=JPRB), INTENT(OUT) :: PFP(YDFPGEO_DEP%NFPROMA,YDRQPHY%NFIELDG,YDFPGEO_DEP%NFPBLOCS)
TYPE (TRQFP), INTENT(IN), OPTIONAL :: YDRQAUX
END SUBROUTINE FPOSHORPHY
END INTERFACE
