INTERFACE
SUBROUTINE FPOSHORLAGPHY(YDRQPHY,YDCLIMO,PWSXI,PWDXI,YDNAMFPSCI,YDAFN,YDFPGEO,YDEPHY,YDPHY,YDPHY1,LDINTERPOL,PFP,LDFPOSHOR,&
 & KWIC,YDAUX) 
USE YOMPHY1 , ONLY : TPHY1
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMFPGEO , ONLY : TFPGEO
USE YOMFPC , ONLY : TNAMFPSCI
USE TYPE_FPOSBUF, ONLY : FPOSBUF
USE YOMPHY , ONLY : TPHY
USE YOEPHY , ONLY : TEPHY
USE YOMAFN , ONLY : TAFN
USE YOMFP4L, ONLY : TRQFP
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
TYPE (FPOSBUF), INTENT(IN) :: YDCLIMO
REAL(KIND=JPRB) ,INTENT(IN) :: PWSXI
REAL(KIND=JPRB) ,INTENT(IN) :: PWDXI
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN), INTENT(IN) :: YDAFN
TYPE(TFPGEO), INTENT(IN) :: YDFPGEO
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(TPHY) ,INTENT(IN) :: YDPHY
TYPE(TPHY1) ,INTENT(IN) :: YDPHY1
LOGICAL ,INTENT(IN) :: LDINTERPOL
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFP(YDFPGEO%NFPROMA,YDRQPHY%NFIELDG,YDFPGEO%NFPBLOCS)
LOGICAL ,INTENT(IN) :: LDFPOSHOR
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KWIC(:,:)
TYPE (FPOSBUF), INTENT(IN), OPTIONAL :: YDAUX
END SUBROUTINE FPOSHORLAGPHY
END INTERFACE
