INTERFACE
SUBROUTINE FPSATURCAP(YDAFN,YDFPGEO,YDGEOMETRY,KAPTR,PABUF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE PARFPOS , ONLY : JPOSDYN
USE YOMFPGEO , ONLY : TFPGEO
USE YOMAFN , ONLY : TAFN
TYPE(TAFN), INTENT(IN) :: YDAFN
TYPE(TFPGEO), INTENT(IN) :: YDFPGEO
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KAPTR(JPOSDYN)
REAL(KIND=JPRB), INTENT(INOUT) :: PABUF(:,:,:)
END SUBROUTINE FPSATURCAP
END INTERFACE
