INTERFACE
SUBROUTINE FPSCAW(YDFPSTRUCT,KPROMA,KSTART,KEND,KFPROW,KLAT,KLONN,KLON,KLOS,KLOSS,KL0)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE EINT_MOD, ONLY : SL_STRUCT
TYPE(SL_STRUCT), INTENT(IN) :: YDFPSTRUCT
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROW
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLONN(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLON(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLOS(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLOSS(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KL0(KPROMA,KFPROW)
END SUBROUTINE FPSCAW
END INTERFACE
