INTERFACE
SUBROUTINE FPSELEZO (YDFPUSERGEO, KPTR, KGP, KFXLAT, KFXLON, PWI, PNO)
USE PARKIND1, ONLY : JPRB, JPIM
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
TYPE (TFPUSERGEO), INTENT (IN) :: YDFPUSERGEO
INTEGER (KIND=JPIM), INTENT (IN) :: KPTR
INTEGER (KIND=JPIM), INTENT (IN) :: KGP
INTEGER (KIND=JPIM), INTENT (IN) :: KFXLAT
INTEGER (KIND=JPIM), INTENT (IN) :: KFXLON
REAL (KIND=JPRB), INTENT (IN) :: PWI (:)
REAL (KIND=JPRB), INTENT (INOUT) :: PNO (:)
END SUBROUTINE FPSELEZO
END INTERFACE
