INTERFACE
SUBROUTINE FPSPNORMS(KRESOL,PSPEC,KVSET,LDSURF,CDPREF,PLEV,CDNAME,KGRIB,CDCONF)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KRESOL(:)
REAL(KIND=JPRB), INTENT(IN) :: PSPEC(:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: KVSET(:)
LOGICAL, INTENT(IN) :: LDSURF(:)
CHARACTER(LEN=*), INTENT(IN) :: CDPREF(:)
REAL(KIND=JPRB), INTENT(IN) :: PLEV(:)
CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: CDNAME(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KGRIB(:)
CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: CDCONF
END SUBROUTINE FPSPNORMS
END INTERFACE
