INTERFACE
SUBROUTINE FPSRH(KST,KEND,KPROMA,KLEV,&
 & PU,PV,PDELP,PPFULL,POROG,PGEOPF,PSTRMMU,PSTRMMV,PSRH) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KST,KEND,KPROMA,KLEV
REAL(KIND=JPRB),INTENT(IN):: PU(KPROMA,KLEV),PV(KPROMA,KLEV),PDELP(KPROMA,KLEV),PPFULL(KPROMA,KLEV)
REAL(KIND=JPRB),INTENT(IN):: POROG(KPROMA), PGEOPF(KPROMA,KLEV)
REAL(KIND=JPRB),INTENT(IN):: PSTRMMU(KPROMA), PSTRMMV(KPROMA)
REAL(KIND=JPRB),INTENT(OUT):: PSRH(KPROMA)
END SUBROUTINE FPSRH
END INTERFACE
