INTERFACE
SUBROUTINE FPSTRMM(KST,KEND,KPROMA,KLEV,&
 & PU,PV,PDELP,PPFULL,POROG,PGEOPF,PSTRMMU,PSTRMMV) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KST,KEND,KPROMA,KLEV
REAL(KIND=JPRB),INTENT(IN):: PU(KPROMA,KLEV),PV(KPROMA,KLEV),PDELP(KPROMA,KLEV),PPFULL(KPROMA,KLEV)
REAL(KIND=JPRB),INTENT(IN):: POROG(KPROMA), PGEOPF(KPROMA,KLEV)
REAL(KIND=JPRB),INTENT(OUT):: PSTRMMU(KPROMA), PSTRMMV(KPROMA)
END SUBROUTINE FPSTRMM
END INTERFACE
