INTERFACE
SUBROUTINE FPTENSOR(KST,KEND,KPROMA,KFIELDS,KORDER,PGM,PBUF,PFPARITY)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),INTENT(IN) :: KORDER(KFIELDS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBUF(KPROMA,KFIELDS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPARITY(KFIELDS)
END SUBROUTINE FPTENSOR
END INTERFACE
