INTERFACE
SUBROUTINE FPTSA_DIR(YDQTYPE,YDTFP,KRESOL,PSCA,PVOR,PDIV,PUMEAN,PVMEAN,PSPBFP,PUMEANFP,PVMEANFP)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
USE YOMAFN , ONLY : ALL_FULLPOS_TYPES
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(ALL_FULLPOS_TYPES), INTENT(IN) :: YDTFP
INTEGER(KIND=JPIM) ,INTENT(IN) :: KRESOL
REAL(KIND=JPRB) ,INTENT(IN) :: PSCA(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOR(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIV(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PUMEAN(:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PVMEAN(:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPBFP(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PUMEANFP(:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PVMEANFP(:)
END SUBROUTINE FPTSA_DIR
END INTERFACE
