INTERFACE
SUBROUTINE FPUH(KST,KEND,KPROMA,KLEV,PUH_LOWER_LIMIT,PUH_UPPER_LIMIT,&
 & PGEOPH,PWVEL0,PVOR,PUH) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KST,KEND,KPROMA,KLEV
REAL(KIND=JPRB),INTENT(IN) :: PUH_LOWER_LIMIT
REAL(KIND=JPRB),INTENT(IN) :: PUH_UPPER_LIMIT
REAL(KIND=JPRB),INTENT(IN) :: PGEOPH(KPROMA,0:KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PWVEL0(KPROMA,KLEV),PVOR(KPROMA,KLEV)
REAL(KIND=JPRB),INTENT(OUT):: PUH(KPROMA)
END SUBROUTINE FPUH
END INTERFACE
