INTERFACE
SUBROUTINE FV_GRADIENT(YDGEOMETRY,PVAR,PGRAD)
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_GEOMETRY , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB),INTENT(IN) :: PVAR(:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PGRAD(:,:,:)
END SUBROUTINE FV_GRADIENT
END INTERFACE
