INTERFACE
SUBROUTINE GANISO(YDGEOMETRY,KPDG,P1,P2,P3,PGAMA,PTHETA)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPDG
REAL(KIND=JPRB) ,INTENT(IN) :: P1(KPDG)
REAL(KIND=JPRB) ,INTENT(IN) :: P2(KPDG)
REAL(KIND=JPRB) ,INTENT(IN) :: P3(KPDG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGAMA(KPDG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTHETA(KPDG)
END SUBROUTINE GANISO
END INTERFACE
