INTERFACE
SUBROUTINE GASPARI_COHN99(Z,LENGTH,ZOUT)
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 REAL(KIND=JPRB) , INTENT(IN) :: Z
 REAL(KIND=JPRB) , INTENT(IN) :: LENGTH
 REAL(KIND=JPRB) , INTENT(INOUT) :: ZOUT
END SUBROUTINE GASPARI_COHN99
END INTERFACE
