INTERFACE
SUBROUTINE GATHERBDY(YDGEOMETRY,PRBDY,PRBDYG)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE MPL_MODULE
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) , INTENT(IN) :: PRBDY(:)
REAL(KIND=JPRB) , INTENT(OUT) :: PRBDYG(:)
END SUBROUTINE GATHERBDY
END INTERFACE
