INTERFACE
SUBROUTINE GATHERGPF(YDGEOMETRY,PLOCGP,PGLOBGP,KFLDS,KROOT,KSCALE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,TARGET,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDS
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCGP(:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGLOBGP(:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KROOT
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KSCALE
END SUBROUTINE GATHERGPF
END INTERFACE
