INTERFACE
SUBROUTINE GATHERSPA(YDGEOMETRY,PGSPA3,PGSPA2,PLSPA3,PLSPA2)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) , INTENT(OUT) :: PGSPA3(:,:,:)
REAL(KIND=JPRB) , INTENT(OUT) :: PGSPA2(:,:)
REAL(KIND=JPRB) , INTENT(IN) :: PLSPA3(:,:,:)
REAL(KIND=JPRB) , INTENT(IN) :: PLSPA2(:,:)
END SUBROUTINE GATHERSPA
END INTERFACE
