INTERFACE
SUBROUTINE GEFGER(YDEPHY,YDML_PHY_MF,YDGOM5,KTSLOT,YDOBSET,YDODB)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOEPHY , ONLY : TEPHY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE SUPERGOM_CLASS, ONLY : CLASS_SUPERGOM
USE MPL_MODULE
USE OBSOP_SETS, ONLY : CLASS_OBSOP_SETS, TYPE_SET_INFO
USE DBASE_MOD, ONLY : DBASE
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KTSLOT
TYPE(CLASS_SUPERGOM), INTENT(IN) :: YDGOM5
TYPE(CLASS_OBSOP_SETS), INTENT(IN) :: YDOBSET
CLASS(DBASE), INTENT(INOUT) :: YDODB
END SUBROUTINE GEFGER
END INTERFACE
