INTERFACE
SUBROUTINE GEO923(YDGEOMETRY,KPINT,KLEN,PBO,PLONG,PMU,PSLAC,PSLOC,PCLOC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPINT
INTEGER(KIND=JPIM),INTENT(OUT) :: KLEN
REAL(KIND=JPRB) ,INTENT(OUT) :: PBO(YDGEOMETRY%YRDIM%NDGLG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLONG(YDGEOMETRY%YRDIM%NDGLG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMU(YDGEOMETRY%YRDIM%NDGLG*YDGEOMETRY%YRDIM%NDLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLAC(YDGEOMETRY%YRDIM%NDGLG*KPINT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLOC(YDGEOMETRY%YRDIM%NDLON*KPINT,YDGEOMETRY%YRDIM%NDGLG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLOC(YDGEOMETRY%YRDIM%NDLON*KPINT,YDGEOMETRY%YRDIM%NDGLG)
END SUBROUTINE GEO923
END INTERFACE
