INTERFACE
SUBROUTINE GESKTER(YDSKTER,KSET,YSETINFO)
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMDB
USE YOMSKTER , ONLY : SKTER, JPMAXVAR
USE MPL_MODULE
USE OBSOP_SETS, ONLY : CLASS_OBSOP_SETS, TYPE_SET_INFO
TYPE(SKTER),INTENT(IN) :: YDSKTER
INTEGER(KIND=JPIM),INTENT(IN) :: KSET
TYPE(TYPE_SET_INFO),INTENT(IN) :: YSETINFO
END SUBROUTINE GESKTER
END INTERFACE
