INTERFACE
SUBROUTINE GET_SPP_CONF( YDRIP, YDCONF )
USE YOMRIP , ONLY : TRIP
USE SPP_MOD , ONLY : TSPP_CONFIG, NWRMAX
TYPE(TRIP), INTENT(IN) :: YDRIP
TYPE(TSPP_CONFIG), INTENT(OUT) :: YDCONF
END SUBROUTINE GET_SPP_CONF
END INTERFACE
