INTERFACE
SUBROUTINE GET_JBVCOORD_COEFFS(YDDIMV,P_ZAH,P_ZBH,P_ZCH,P_ZDH,KBLLEV)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
REAL(KIND=JPRB) , INTENT(OUT) :: P_ZAH(0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) , INTENT(OUT) :: P_ZBH(0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) , INTENT(OUT) :: P_ZCH(0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) , INTENT(OUT) :: P_ZDH(0:YDDIMV%NFLEVG)
INTEGER(KIND=JPIM), INTENT(OUT) :: KBLLEV
END SUBROUTINE GET_JBVCOORD_COEFFS
END INTERFACE
