INTERFACE
SUBROUTINE GETMINI2(YDGEOMETRY,YDVAZX, CDFILE, KSTART, KEND, YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY: TYPE_JB_STRUCT
USE CONTROL_VECTORS_MOD, ONLY : CONTROL_VECTOR, ALLOCATE_CTLVEC, DEALLOCATE_CTLVEC,&
 & ASSIGNMENT(=) 
USE NETCDF
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDVAZX(KSTART:KEND)
CHARACTER(LEN=*) ,INTENT(IN) :: CDFILE
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE GETMINI2
END INTERFACE
