INTERFACE
SUBROUTINE GETMINI(YDGEOMETRY,YDRIP,YDVAZX,YD_JB_STRUCT,CDFILE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMRIP , ONLY : TRIP
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE CONTROL_VECTORS_MOD, ONLY : CONTROL_VECTOR,&
 & ALLOCATE_CTLVEC, DEALLOCATE_CTLVEC, ASSIGNMENT(=) 
USE NETCDF
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDVAZX
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
CHARACTER(LEN=*) ,OPTIONAL,INTENT(IN) :: CDFILE
END SUBROUTINE GETMINI
END INTERFACE
