INTERFACE
SUBROUTINE GETNEMODIAG(KGPTOT,KPROMA,KSTEP,YDSURF,YDMCC)
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMMCC , ONLY : TMCC
USE PARKIND1 , ONLY : JPRD, JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TMCC), INTENT(INOUT) :: YDMCC
END SUBROUTINE GETNEMODIAG
END INTERFACE
