INTERFACE
SUBROUTINE GETSATID(KLEN,KBUFID,KSERIESID,KSATNO)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KBUFID(KLEN)
INTEGER(KIND=JPIM),INTENT(OUT) :: KSERIESID(KLEN)
INTEGER(KIND=JPIM),INTENT(OUT) :: KSATNO(KLEN)
END SUBROUTINE GETSATID
END INTERFACE
