INTERFACE
SUBROUTINE GHG_AK_AD(KFLEVG,KDLEN,KLEN,KDCOUNT,KGRIBC,KCOUNT,&
 & KAK,PWAK,PAPAK,PRESO,YDGP_AD,&
 & KDPP,PXGHG,&
 & PRESH5,PRESF5,YDGP5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE PARCMA , ONLY : JPMX_AK
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIBC
INTEGER(KIND=JPIM),INTENT(IN) :: KCOUNT(KDLEN)
INTEGER(KIND=JPIM),INTENT(IN) :: KAK(KDLEN,KDCOUNT)
REAL(KIND=JPRB) ,INTENT(IN) :: PWAK(KDLEN,KDCOUNT,JPMX_AK)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPAK(KDLEN,KDCOUNT,JPMX_AK)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESO(KDLEN,KDCOUNT,JPMX_AK)
INTEGER(KIND=JPIM),INTENT(IN) :: KDPP
REAL(KIND=JPRB) ,INTENT(IN) :: PXGHG(KDLEN,KDCOUNT,KDPP)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH5(KDLEN,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5(KDLEN,KFLEVG)
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
TYPE (TYPE_GOM_PLUS),INTENT(INOUT) :: YDGP_AD
END SUBROUTINE GHG_AK_AD
END INTERFACE
