INTERFACE
SUBROUTINE GMASSDIAG(YDGEOMETRY,YDGMV,YDML_CHEM,YGFL,YDDYN,PGMV,PGMVS,PGMVT1S,PGFL,PGFLT1,KOPT,LDTROP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE MODEL_CHEM_MOD , ONLY : MODEL_CHEM_TYPE
USE YOM_YGFL , ONLY : TYPE_GFLD
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(IN) :: YDGMV
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_CHEM_TYPE),INTENT(INOUT) :: YDML_CHEM
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
REAL(KIND=JPRB) ,INTENT(IN) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM,&
 & YDGEOMETRY%YRDIM%NGPBLKS) 
REAL(KIND=JPRB) ,INTENT(IN) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1,&
 & YDGEOMETRY%YRDIM%NGPBLKS) 
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KOPT
LOGICAL ,INTENT(IN), OPTIONAL :: LDTROP
END SUBROUTINE GMASSDIAG
END INTERFACE
