INTERFACE
SUBROUTINE GNH_TNDLAGADIAB_GW( LDGWADV, LDVERTFE, LDVFE_ECMWF, LDVFE_GW, LDVFE_LAPL_BC, YDCST,&
 & YDGEOMETRY, KFLEV, KPROMA, KSTART, KPROF, POROGL, POROGM, POROGLM, POROGLL, POROGMM, PUS, PVS,&
 & PTNDUS, PTNDVS, PDEP, PDEPS, PREF, PREH, PDELP, PRDELP, PDELNHPRE, PEVEL, PTNDGWH_LAP, PTNDGWH_OTH,&
 & PTNDGWF_LAP, PTNDGWF_OTH, PDBBC ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCST , ONLY : TCST
LOGICAL ,INTENT(IN) :: LDGWADV
LOGICAL ,INTENT(IN) :: LDVERTFE
LOGICAL ,INTENT(IN) :: LDVFE_ECMWF
LOGICAL ,INTENT(IN) :: LDVFE_GW
LOGICAL ,INTENT(IN) :: LDVFE_LAPL_BC
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: POROGLM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: POROGLL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: POROGMM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PUS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PVS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PTNDUS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PTNDVS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PDEP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PDEPS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PREH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PDELP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PRDELP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PDELNHPRE(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PEVEL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PTNDGWH_LAP(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PTNDGWH_OTH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PTNDGWF_LAP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PTNDGWF_OTH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PDBBC(KPROMA)
END SUBROUTINE GNH_TNDLAGADIAB_GW
END INTERFACE
