INTERFACE
SUBROUTINE GNH_TNDLAGADIAB_UVS(&
 & KPROMA,KSTART,KPROF,LDPLANE,&
 & PRCORI,PRATATX,PRATATH,PUS,PVS,PSGRTSL,PSGRTSM,&
 & PTNDUS,PTNDVS&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
LOGICAL ,INTENT(IN) :: LDPLANE
REAL(KIND=JPRB) ,INTENT(IN) :: PRCORI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRATATX(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRATATH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSGRTSL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSGRTSM(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTNDUS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTNDVS(KPROMA)
END SUBROUTINE GNH_TNDLAGADIAB_UVS
END INTERFACE
