INTERFACE
SUBROUTINE GNH_TNDLAGADIAB_SPD( KPDVAR, YDGEOMETRY, KFLEV, KPROMA, KSTART, KPROF, PKAP, P3DIVG,&
 & PVVEL, PTNDPD ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPDVAR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PKAP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: P3DIVG(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVVEL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTNDPD(KPROMA,KFLEV)
END SUBROUTINE GNH_TNDLAGADIAB_SPD
END INTERFACE
