INTERFACE
SUBROUTINE GNHD3( LD_RDRY_VD, YDCST, KFLEV, KPROMA, KSTART, KEND, PDIV, PNHX, PDVER, PR, PMAX_D3,&
 & LDBOUND_D3, P3DIVG) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
LOGICAL ,INTENT(IN) :: LD_RDRY_VD
TYPE(TCST) ,INTENT(IN) :: YDCST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PDIV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNHX(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDVER(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMAX_D3
LOGICAL ,INTENT(IN) :: LDBOUND_D3
REAL(KIND=JPRB) ,INTENT(OUT) :: P3DIVG(KPROMA,KFLEV)
END SUBROUTINE GNHD3
END INTERFACE
