INTERFACE
SUBROUTINE GNHGRPRE( KPDVAR, YDGEOMETRY, KPROMA, KFLEV, KSTART, KEND, PRTGR, PREL, PREM, PNHPREF,&
 & PSPDL, PSPDM, PNHPREFL, PNHPREFM, PLNNHPREFL, PLNNHPREFM, PQCHAL, PQCHAM) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPDVAR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PRTGR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PREL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PREM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PNHPREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPDL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPDM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNHPREFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNHPREFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLNNHPREFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLNNHPREFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCHAL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCHAM(KPROMA,KFLEV)
END SUBROUTINE GNHGRPRE
END INTERFACE
