INTERFACE
SUBROUTINE GP_DERIVATIVES(YDGEOMETRY,YDFIELDS,YGFL)
USE YOM_YGFL , ONLY : TYPE_GFLD
USE FIELDS_MOD , ONLY : FIELDS
USE TYPE_GEOMETRY , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(TYPE_GFLD),INTENT(IN) :: YGFL
END SUBROUTINE GP_DERIVATIVES
END INTERFACE
