INTERFACE
SUBROUTINE GP_KAPPATAD(&
 & YDGEOMETRY, YDDYN,KPROMA,KSTART,KPROF,KFLEV,&
 & PDTS2,PTT05,PTT0L5,PTT0M5,PSPT05,PSPT0L5,PSPT0M5,&
 & PTT0,PTT0L,PTT0M,PSPT0,PSPT0L,PSPT0M,PSLHDA,PSLHDD0,&
 & PKAPPA) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS2
REAL(KIND=JPRB) ,INTENT(IN) :: PTT05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0L5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0M5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT05(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0L5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0M5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT0L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT0M(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT0L(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT0M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDD0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKAPPA(KPROMA,KFLEV)
END SUBROUTINE GP_KAPPATAD
END INTERFACE
