INTERFACE
SUBROUTINE GP_KAPPA(&
 & YDDYNA, YDVAB, YDDYN,KPROMA,KSTART,KPROF,KFLEV,&
 & PDTS2,PUT0L,PVT0L,PVORT0,PDIVT0,&
 & PLHU0,PLHV0,PRES0,PSPT0L,PSPT0M,PRDELP,PSLHDA,PSLHDD0,&
 & PKAPPA) 
USE YOMVERT , ONLY : TVAB
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYNA , ONLY : TDYNA
USE YOMDYN , ONLY : TDYN
TYPE (TDYNA), INTENT (IN) :: YDDYNA
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS2
REAL(KIND=JPRB) ,INTENT(IN) :: PUT0L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT0L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVORT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHU0(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLHV0(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRES0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0L(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDD0(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKAPPA(KPROMA,KFLEV)
END SUBROUTINE GP_KAPPA
END INTERFACE
