INTERFACE
SUBROUTINE GP_KAPPATL(&
 & YDDYN,KPROMA,KSTART,KPROF,KFLEV,&
 & PDTS2,&
 & PUT0L5,PVT0L5,PVORT05,PDIVT05,&
 & PUT0L,PVT0L,PVORT0,PDIVT0,&
 & PSLHDA,PSLHDD0,&
 & PKAPPA) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMDYN , ONLY : TDYN
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS2
REAL(KIND=JPRB) ,INTENT(IN) :: PUT0L5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT0L5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVORT05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT0L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT0L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVORT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDD0(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKAPPA(KPROMA,KFLEV)
END SUBROUTINE GP_KAPPATL
END INTERFACE
