INTERFACE
SUBROUTINE GP_KAPPAT(&
 & LDVERTFE, PTOPPRES, YDDYNA, YDCST, YDGEOMETRY, YDDYN,KPROMA,KSTART,KPROF,KFLEV,&
 & PDTS2,PTT0,PTT0L,PTT0M,PSPT0,PSPT0L,PSPT0M,PSLHDA,PSLHDD0,&
 & PKAPPA) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMDYNA , ONLY : TDYNA
USE YOMDYN , ONLY : TDYN
USE YOMCST , ONLY : TCST
REAL (KIND=JPRB), INTENT (IN) :: PTOPPRES
LOGICAL, INTENT (IN) :: LDVERTFE
TYPE (TDYNA), INTENT (IN) :: YDDYNA
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS2
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0M(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0L(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLHDD0(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKAPPA(KPROMA,KFLEV)
END SUBROUTINE GP_KAPPAT
END INTERFACE
