INTERFACE
SUBROUTINE GP_MODEL_DRV(YDGEO,YDFIELDS,MDL,CDCONF,LD_DFISTEP,PTRAJEC,PTRAJEC_OOPS)
USE GEOMETRY_MOD,ONLY: GEOMETRY
USE FIELDS_MOD,ONLY: FIELDS
USE TYPE_MODEL,ONLY: MODEL
USE YOMTRAJ,ONLY: TRAJ_TYPE
USE YOMTRAJ_OOPS,ONLY: TRAJ_TYPE_OOPS
TYPE(GEOMETRY),INTENT(IN) :: YDGEO
TYPE(FIELDS),INTENT(INOUT) :: YDFIELDS
TYPE(MODEL),INTENT(INOUT) :: MDL
CHARACTER(LEN=9),INTENT(IN) :: CDCONF
TYPE(TRAJ_TYPE),OPTIONAL,INTENT(INOUT) :: PTRAJEC
TYPE(TRAJ_TYPE_OOPS),OPTIONAL,INTENT(INOUT) :: PTRAJEC_OOPS
LOGICAL,INTENT(IN) :: LD_DFISTEP
END SUBROUTINE
END INTERFACE
