INTERFACE
SUBROUTINE GP_MODEL(YDGEOMETRY,YDFIELDS,YDMODEL,CDCONF,LD_DFISTEP,PSLBUF1,PSLBUF2,PGRADPHY,&
 & PTRAJEC,PTRAJEC_OOPS) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMTRAJ , ONLY : TRAJ_TYPE
USE YOMTRAJ_OOPS , ONLY : TRAJ_TYPE_OOPS
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
CHARACTER(LEN=9) ,INTENT(IN) :: CDCONF
LOGICAL ,INTENT(IN) :: LD_DFISTEP
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLBUF1(YDMODEL%YRML_DYN%YRSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLBUF2(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGRADPHY(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_MF%YRARPHY%NGRADIENTS,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
TYPE(TRAJ_TYPE) ,OPTIONAL,INTENT(INOUT) :: PTRAJEC
TYPE(TRAJ_TYPE_OOPS) ,OPTIONAL,INTENT(INOUT) :: PTRAJEC_OOPS
END SUBROUTINE GP_MODEL
END INTERFACE
