INTERFACE
SUBROUTINE GPADDSLPHY(YDGEOMETRY,YDSLPHY,YGFL,LDLFSTEP,KST,KEND,PTMST,&
 & PSAVTEND,PGFLSLP,&
 & PSLB1U0,PSLB1V0,PSLB1T0,PSLB1GFL0) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMSLPHY , ONLY : TSLPHY
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSLPHY) ,INTENT(IN) :: YDSLPHY
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
LOGICAL ,INTENT(IN) :: LDLFSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PSAVTEND(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDSLPHY%NVTEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFLSLP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIMSLP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSLB1U0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSLB1V0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSLB1T0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSLB1GFL0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLSA:YDGEOMETRY%YRDIMV%NFLEN,&
 & YGFL%NUMFLDS) 
END SUBROUTINE GPADDSLPHY
END INTERFACE
