INTERFACE
SUBROUTINE GPCTY_FORC(YDCST, YDGEOMETRY, YDML_GCONF, YDPHY2, YDCPG_BNDS, YDCPG_OPTS, YDVARS, YDCPG_DYN0)
USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCST , ONLY : TCST
USE YOMPHY2 , ONLY : TPHY2
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD , ONLY : CPG_DYN_TYPE
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE) ,INTENT(IN) :: YDML_GCONF
TYPE(TPHY2) ,INTENT(IN) :: YDPHY2
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(FIELD_VARIABLES) ,INTENT(INOUT) :: YDVARS
TYPE(CPG_DYN_TYPE) ,INTENT(INOUT) :: YDCPG_DYN0
END SUBROUTINE GPCTY_FORC
END INTERFACE
