INTERFACE
SUBROUTINE GPCTY(YDVFE,KPROMA,KD,KF,KFLEV,LDRUBC,YDVAB,YDVETA,&
 & PU,PV,PD,PEVT,PXYB,PSPL,PSPM,PRPREF,PCTY,PDPHYCTY) 
USE YOMVERT , ONLY : TVFE, TVAB, TVETA
USE PARKIND1 , ONLY : JPIM, JPRB
USE INTDYN_MOD, ONLY : YYTCTY, YYTXYB
TYPE(TVFE) ,INTENT(IN) :: YDVFE
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KD
INTEGER(KIND=JPIM),INTENT(IN) :: KF
LOGICAL ,INTENT(IN) :: LDRUBC
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TVETA) ,INTENT(IN) :: YDVETA
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PD(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB(KPROMA,KFLEV,YYTXYB%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCTY(KPROMA,0:KFLEV,YYTCTY%NDIM)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PDPHYCTY(KPROMA,KFLEV)
END SUBROUTINE GPCTY
END INTERFACE
