INTERFACE
SUBROUTINE GPCTYTL(YDVFE,KPROMA,KD,KF,KFLEV,YDVAB,YDVETA,&
 & PU,PV,PD,PXYB,PSPL,PSPM,PRPREF,PCTY,&
 & PU5,PV5,PD5,PXYB5,PSPL5,PSPM5,PSDIV5,PRPREF5) 
USE YOMVERT , ONLY : TVFE, TVAB, TVETA
USE PARKIND1 , ONLY : JPIM, JPRB
USE INTDYN_MOD, ONLY : YYTCTY, YYTXYB, YYTXYBT
TYPE(TVFE) ,INTENT(IN) :: YDVFE
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KD
INTEGER(KIND=JPIM),INTENT(IN) :: KF
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TVETA) ,INTENT(IN) :: YDVETA
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PD(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB(KPROMA,KFLEV,YYTXYB%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,TARGET,INTENT(OUT) :: PCTY(KPROMA,0:KFLEV,YYTCTY%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PU5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PD5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB5(KPROMA,KFLEV,YYTXYBT%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPL5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPM5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSDIV5(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPREF5(KPROMA,KFLEV)
END SUBROUTINE GPCTYTL
END INTERFACE
