INTERFACE
SUBROUTINE GPFLWI(YDDIMV,KPROMA,KSTART,KPROF,&
 & PLNPR,PALPH,PRESH,PRESF,PDELP,PWW,LDVERINT) 
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TDIMV), INTENT(IN) :: YDDIMV
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KPROMA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWW(KPROMA,YDDIMV%NFLEVG,2)
LOGICAL,OPTIONAL ,INTENT(IN) :: LDVERINT
END SUBROUTINE GPFLWI
END INTERFACE
