INTERFACE
SUBROUTINE GPGEOAD(KPROMA,KSTART,KPROF,KFLEV,PHI,PHIF,PT,PR,PLNPR,&
 & PALPH,PT5,PR5,PLNPR5,PALPH5,PVGEOM) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMVERT , ONLY : TVERTICAL_GEOM
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHI(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHIF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLNPR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH5(KPROMA,KFLEV)
TYPE(TVERTICAL_GEOM),INTENT(IN) :: PVGEOM
END SUBROUTINE GPGEOAD
END INTERFACE
