INTERFACE
SUBROUTINE GPGRGEOTL(&
 & YDGEOMETRY,LDNHDYN,KPROMA,KD,KF,KFLEV,&
 & PT,PR,PRTL,PRTM,&
 & PLNPR,PALPH,PXYBDER,&
 & PHIFL,PHIFM,PHIHL,PHIHM,&
 & PREHYDSPRE5,PT5,PR5,PRT5L,PRT5M,&
 & PLNPR5,PALPH5,PXYBDER5&
 & ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE INTDYN_MOD , ONLY : YYTXYBDER, YYTXYBDERT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
LOGICAL ,INTENT(IN) :: LDNHDYN
INTEGER(KIND=JPIM) ,INTENT(IN) :: KD
INTEGER(KIND=JPIM) ,INTENT(IN) :: KF
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYBDER(KPROMA,KFLEV,YYTXYBDER%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIHL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIHM(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PREHYDSPRE5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRT5L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRT5M(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYBDER5(KPROMA,KFLEV,YYTXYBDERT%NDIM)
END SUBROUTINE GPGRGEOTL
END INTERFACE
