INTERFACE
SUBROUTINE GPGRXYBAD(&
 & KPROMA,KD,KF,KFLEV,YDVAB,&
 & PREL,PREM,PXYB,&
 & PXYBDER,&
 & PRE5L,PRE5M,PXYB5,PXYBDER5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMVERT , ONLY : TVAB
USE INTDYN_MOD, ONLY : YYTXYB, YYTXYBT, YYTXYBDER, YYTXYBDERT
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KD
INTEGER(KIND=JPIM),INTENT(IN) :: KF
TYPE(TVAB) ,INTENT(IN) :: YDVAB
REAL(KIND=JPRB) ,INTENT(INOUT) :: PREL(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PREM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXYB(KPROMA,KFLEV,YYTXYB%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXYBDER(KPROMA,KFLEV,YYTXYBDER%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE5L(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE5M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB5(KPROMA,KFLEV,YYTXYBT%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYBDER5(KPROMA,KFLEV,YYTXYBDERT%NDIM)
END SUBROUTINE GPGRXYBAD
END INTERFACE
