INTERFACE
SUBROUTINE GPGRXYB (KPROMA,KD,KF,KFLEV,LDCOEF,YDVAB,PREL,PREM,PXYB,PXYBDER)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMVERT , ONLY : TVAB
USE INTDYN_MOD, ONLY : YYTXYB, YYTXYBDER
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KD
INTEGER(KIND=JPIM),INTENT(IN) :: KF
LOGICAL ,INTENT(IN) :: LDCOEF
TYPE(TVAB) ,INTENT(IN) :: YDVAB
REAL(KIND=JPRB) ,INTENT(IN) :: PREL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PREM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB(KPROMA,KFLEV,YYTXYB%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXYBDER(KPROMA,KFLEV,YYTXYBDER%NDIM)
END SUBROUTINE GPGRXYB
END INTERFACE
