INTERFACE
SUBROUTINE GPGRGEO(&
 & YDGEOMETRY,KPROMA,KD,KF,KFLEV,&
 & PRT,PRTL,PRTM,&
 & PLNPR,PALPH,PXYBDER,&
 & POROGL,POROGM,&
 & PHIFL,PHIFM,PHIHL,PHIHM,&
 & LDNHEE,PRNHPPI,PQCHAL,PQCHAM,&
 & PNH1L,PNH1M) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE INTDYN_MOD , ONLY : YYTXYBDER
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KD
INTEGER(KIND=JPIM),INTENT(IN) :: KF
REAL(KIND=JPRB) ,INTENT(IN) :: PRT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYBDER(KPROMA,KFLEV,YYTXYBDER%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIHL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIHM(KPROMA,0:KFLEV)
LOGICAL,OPTIONAL,INTENT(IN) :: LDNHEE
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PRNHPPI(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQCHAL(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQCHAM(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PNH1L(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PNH1M(KPROMA,KFLEV)
END SUBROUTINE GPGRGEO
END INTERFACE
