INTERFACE
SUBROUTINE GPGRGEO_EXPL( LDVERTFE, YDGEOMETRY, KPROMA, KD, KF, KFLEV, PRT, PRTL, PRTM, PLNPR,&
 & PALPH, POROGL, POROGM, PHIFL, PHIFM, PHIHL, PHIHM, LDNHEE, PRNHPPI, PQCHAL, PQCHAM, PNH1L, PNH1M,&
 & PLNPRL_DER, PLNPRM_DER, PALPHL_DER, PALPHM_DER) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
LOGICAL ,INTENT(IN) :: LDVERTFE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KD
INTEGER(KIND=JPIM) ,INTENT(IN) :: KF
REAL(KIND=JPRB) ,INTENT(IN) :: PRT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRTM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIHL(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHIHM(KPROMA,0:KFLEV)
LOGICAL ,INTENT(IN) ,OPTIONAL :: LDNHEE
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PRNHPPI(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PQCHAL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) ,OPTIONAL :: PQCHAM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PNH1L(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL :: PNH1M(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPRL_DER(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPRM_DER(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPHL_DER(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPHM_DER(KPROMA,KFLEV)
END SUBROUTINE GPGRGEO_EXPL
END INTERFACE
