INTERFACE
SUBROUTINE GPHLWI(YDDIMV, KPROMA, KSTART, KPROF, PLNPR, PALPH, PWW, LDVERINT)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDIMV , ONLY : TDIMV
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWW(KPROMA,YDDIMV%NFLEVG)
LOGICAL ,INTENT(IN) ,OPTIONAL :: LDVERINT
END SUBROUTINE GPHLWI
END INTERFACE
