INTERFACE
SUBROUTINE GPHLUV(YDDIMV,KPROMA,KSTART,KPROF,PU,PV,PUVH)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE INTDYN_MOD, ONLY : YYTHW
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUVH(KPROMA,0:YDDIMV%NFLEVG,YYTHW%NDIM)
END SUBROUTINE GPHLUV
END INTERFACE
