INTERFACE
SUBROUTINE GPHPRE(KPROMA,KFLEV,K1,K2,VAB,PRESH,PXYB,PRESF,LHSET,LDELP,LALPHA,LRTGR,LRPP)
USE PARKIND1,ONLY: JPIM,JPRB
USE YOMVERT,ONLY: TVAB,TOPPRES,LVERTFE
USE INTDYN_MOD,ONLY: YYTXYB
TYPE(TVAB), INTENT(IN) :: VAB
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA,KFLEV,K1,K2
LOGICAL,OPTIONAL, INTENT(IN) :: LHSET,LDELP,LALPHA,LRTGR,LRPP
REAL(KIND=JPRB), INTENT(INOUT) :: PRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB),TARGET,OPTIONAL,INTENT(OUT) :: PXYB(KPROMA,KFLEV,YYTXYB%NDIM)
REAL(KIND=JPRB),TARGET,OPTIONAL,INTENT(OUT) :: PRESF(KPROMA,KFLEV)
END SUBROUTINE
END INTERFACE
