INTERFACE
SUBROUTINE GPHPRE_EXPL(LDAPRXPK, LDVERTFE, KDLNPR, RHYDR0, TOPPRES, YDCST, KPROMA, KFLEV, K1, K2,&
 & VAB, PRESH, PRESF, LHSET, LDELP, LALPHA, LRTGR, LRPP, PDELP, PLNPR, PRDELP, PALPH, PRTGR, PRPRE,&
 & PRPP) 
USE PARKIND1,ONLY: JPIM, JPRB
USE YOMCST, ONLY: TCST
USE YOMVERT, ONLY: TVAB
LOGICAL ,INTENT(IN) :: LDAPRXPK
LOGICAL ,INTENT(IN) :: LDVERTFE
INTEGER(KIND=JPIM) ,INTENT(IN) :: KDLNPR
REAL(KIND=JPRB) ,INTENT(IN) :: RHYDR0
REAL(KIND=JPRB) ,INTENT(IN) :: TOPPRES
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TVAB) ,INTENT(IN) :: VAB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA,KFLEV,K1,K2
LOGICAL ,INTENT(IN) ,OPTIONAL :: LHSET,LDELP,LALPHA,LRTGR,LRPP
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL ,TARGET :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL ,TARGET :: PDELP(KPROMA,KFLEV),PLNPR(KPROMA,KFLEV),PRDELP(KPROMA,KFLEV),PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) ,OPTIONAL ,TARGET :: PRTGR(KPROMA,KFLEV),PRPRE(KPROMA,KFLEV),PRPP(KPROMA,KFLEV)
END SUBROUTINE
END INTERFACE
