INTERFACE
SUBROUTINE GPHVINT(KPROMA,KFLEV,KSTART,KPROF,PRESH,PRESF,PXYB,PWEIG)
USE PARKIND1 , ONLY : JPIM, JPRB
USE INTDYN_MOD, ONLY : YYTXYB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB(KPROMA,KFLEV,YYTXYB%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWEIG(KPROMA,KFLEV,3)
END SUBROUTINE GPHVINT
END INTERFACE
