INTERFACE
SUBROUTINE GPIAU(YGFL,KPROMA,KFLEVG,KST,KND,PGFL,PIAUGFL)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KND
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(KPROMA,KFLEVG,YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PIAUGFL(KPROMA,KFLEVG,1)
END SUBROUTINE GPIAU
END INTERFACE
