INTERFACE
SUBROUTINE GPIET(YDPHY,KPROMA,KSTART,KPROF,KFLEV,PQT0,PTT0,PCP,PRPRESF,PTETAE)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMPHY , ONLY : TPHY
TYPE(TPHY) ,INTENT(IN) :: YDPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PQT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTETAE(KPROMA,KFLEV)
END SUBROUTINE GPIET
END INTERFACE
