INTERFACE
SUBROUTINE GPINCOCH(YDCHEM,KSTART,KPROF,KLEV,KPROMA,KGPLAT,PKCO,PTOP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCHEM , ONLY : TCHEM
TYPE(TCHEM) ,INTENT(INOUT) :: YDCHEM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KGPLAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKCO(KPROMA,KLEV*YDCHEM%NCHEM_LCOCOEF)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTOP(KPROMA)
END SUBROUTINE GPINCOCH
END INTERFACE
