INTERFACE
SUBROUTINE GPMPFC_PGFL_PART2 (YDML_GCONF, KPROMA, KFLEV, KST, KEN, PGM, PGFL)
USE PARKIND1, ONLY : JPIM, JPRB
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEN
REAL(KIND=JPRB),INTENT(IN) :: PGM(KPROMA)
REAL(KIND=JPRB),INTENT(INOUT) :: PGFL(KPROMA,KFLEV,YDML_GCONF%YGFL%NDIM)
END SUBROUTINE
END INTERFACE
