INTERFACE
SUBROUTINE GPMPFC_EXPL_PART2 (YDVARS, KPROMA, KFLEV, KST, KEN, PGM)
USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
INTEGER(KIND=JPIM) , INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) , INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) , INTENT(IN) :: KST
INTEGER(KIND=JPIM) , INTENT(IN) :: KEN
REAL(KIND=JPRB) , INTENT(IN) :: PGM (KPROMA)
END SUBROUTINE
END INTERFACE
