INTERFACE
SUBROUTINE GPMPFC5(YDGMV5,YDML_GCONF,KPROMA,KFLEV,KST,KEN,KFLAG,PGM,PGMV5,PGMV5S,PGFL5)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLAG
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV5(KPROMA,KFLEV,YDGMV5%YT5%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV5S(KPROMA,YDGMV5%YT5%NDIMS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL5(KPROMA,KFLEV,YDML_GCONF%YGFL%NDIM5)
END SUBROUTINE GPMPFC5
END INTERFACE
