INTERFACE
SUBROUTINE GPNOX(KPROMA,KSTART,KPROF,KFLEV,PNO2,PT,PO3,PNOX,PSOL,PJNO2,PRXP)
USE PARKIND1 , ONLY : JPIM, JPRB
USE PARDIM , ONLY : JPNPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(OUT) :: PNO2(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PO3(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNOX(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PJNO2(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXP(KPROMA,0:KFLEV,JPNPPM)
END SUBROUTINE GPNOX
END INTERFACE
