INTERFACE
SUBROUTINE GPNORM_GMV(YDGEOMETRY,YDGMV)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) , INTENT(IN) :: YDGMV
END SUBROUTINE GPNORM_GMV
END INTERFACE
