INTERFACE
SUBROUTINE GPNORM1(YDGEOMETRY,PGP,KFIELDS,LDLEVELS,CDLABEL,PNORMS)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
REAL(KIND=JPRB) ,INTENT(IN) :: PGP(YDGEOMETRY%YRDIM%NPROMA,KFIELDS,YDGEOMETRY%YRDIM%NGPBLKS)
LOGICAL ,INTENT(IN) :: LDLEVELS
CHARACTER(LEN=*) ,INTENT(IN),OPTIONAL :: CDLABEL
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PNORMS(3,KFIELDS)
END SUBROUTINE GPNORM1
END INTERFACE
