INTERFACE
SUBROUTINE GPNORM_GFL(YDGEOMETRY,YDGFL,LDPRINT_TL)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TGFL) , INTENT(IN) :: YDGFL
LOGICAL,OPTIONAL, INTENT(IN) :: LDPRINT_TL
END SUBROUTINE GPNORM_GFL
END INTERFACE
