INTERFACE
SUBROUTINE GPNSPNG_EXPL (YDSPNG,KPROMA,KFLEVG,KST,KND,YDVARS)
USE PARKIND1 , ONLY : JPIM, JPRB
USE SPNG_MOD , ONLY : TSPNG
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
TYPE(TSPNG) ,INTENT(IN) :: YDSPNG
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KND
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
END SUBROUTINE GPNSPNG_EXPL
END INTERFACE
