INTERFACE
SUBROUTINE GPPCLOUD(KPROMA,KSTART,KPROF,KFLEV,PXCLDFRAC,PPRESF,PCLDFC,PGEOF,POROG,PPTOP,PPBASE,PHBASE)
USE PARKIND1, ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA,KSTART,KPROF,KFLEV
REAL(KIND=JPRB),INTENT(IN) :: PXCLDFRAC
REAL(KIND=JPRB),INTENT(IN) :: PPRESF(KPROMA,KFLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCLDFC(KPROMA,KFLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGEOF(KPROMA,KFLEV)
REAL(KIND=JPRB),INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PPTOP(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PPBASE(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PHBASE(KPROMA)
END SUBROUTINE GPPCLOUD
END INTERFACE
