INTERFACE
SUBROUTINE GPPECHOT(KPROMA,KSTART,KPROF,KFLEV,PPRESF,PSIMRFCDB,PECHOT)
USE PARKIND1,ONLY : JPRD, JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA,KSTART,KPROF,KFLEV
REAL(KIND=JPRB),INTENT(IN) :: PPRESF(KPROMA,KFLEV),PSIMRFCDB(KPROMA,KFLEV)
REAL(KIND=JPRB),INTENT(OUT) :: PECHOT(KPROMA)
END SUBROUTINE GPPECHOT
END INTERFACE
