INTERFACE
SUBROUTINE GPPVO(YDVAB,KPROMA,KSTART,KPROF,KFLEV,&
 & PRESF,PRDELP,PKAP,PRCORI,&
 & PVOR,PU,PV,PT,PTM,PTL,PSPM,PSPL,PVO,PTETA,PTETAL,PTETAM) 
USE YOMVERT , ONLY : TVAB
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TVAB) ,INTENT(IN) :: YDVAB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKAP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCORI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPL(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVO(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTETA(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PTETAL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: PTETAM(KPROMA,KFLEV)
END SUBROUTINE GPPVO
END INTERFACE
