INTERFACE
SUBROUTINE GPRCP_EXPL (YDCST,KPROMA,KST,KPROF,KFLEV,PCP,PR,PKAP,YDVARS,KGFLTYP)
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMCST, ONLY: TCST
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
TYPE(TCST), INTENT(IN) :: YDCST
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA,KFLEV,KST,KPROF
INTEGER(KIND=JPIM),OPTIONAL, INTENT(IN) :: KGFLTYP
TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT) :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL, INTENT(OUT) :: PKAP(KPROMA,KFLEV)
END SUBROUTINE GPRCP_EXPL
END INTERFACE
