INTERFACE
SUBROUTINE GPRCPTL(KPROMA,KSTART,KPROF,KFLEV,PQ,PQI,PQL,PQR,PQS,PQG,&
 & PCP,PR,PKAP,PCP5,PR5,PGFL,KGFLTYP,LDTHERMACT) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PQ(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PQI(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PQL(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PQR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PQS(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PQG(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PGFL(KPROMA,KFLEV,YGFL%NDIM)
REAL(KIND=JPRB),OPTIONAL ,INTENT(OUT) :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(OUT) :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(OUT) :: PKAP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PCP5(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PR5(KPROMA,KFLEV)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGFLTYP
LOGICAL,OPTIONAL,INTENT(IN) :: LDTHERMACT
END SUBROUTINE GPRCPTL
END INTERFACE
