INTERFACE
SUBROUTINE GPRHTL(LDWMORH,KPROMA,KSTART,KPROF,KFLEV,&
 & PRHMAX,PRHMIN,PQ,PT,PRESF,PES,PRH,&
 & PES5,PRESF5,PQ5,PT5) 
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
LOGICAL ,INTENT(IN) :: LDWMORH
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMIN
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PES(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PES5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA,KFLEV)
END SUBROUTINE GPRHTL
END INTERFACE
