INTERFACE
SUBROUTINE GPRT(LDSPRT,KPROMA,KSTART,KEND,KLEV,PRD,PRV,PR,&
 & PT,PTL,PTM,PQL,PQM,PRT,PRTL,PRTM,PRL,PRM) 
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
LOGICAL ,INTENT(IN) :: LDSPRT
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PRD
REAL(KIND=JPRB) ,INTENT(IN) :: PRV
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQL(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRT(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRTL(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRTM(KPROMA,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PRL(KPROMA,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PRM(KPROMA,KLEV)
END SUBROUTINE GPRT
END INTERFACE
