INTERFACE
SUBROUTINE GPSCALC_NRAD(K_NLEV,P_ROC,P_LAT,P_ZG,P_ZG_HAT,P_REFRAC,P_REFRAC_HAT,&
 & PZ_COMP,PZ_COMP_HAT,P_NR_HAT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K_NLEV
REAL(KIND=JPRB) ,INTENT(IN) :: P_ROC
REAL(KIND=JPRB) ,INTENT(IN) :: P_LAT
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG(K_NLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_ZG_HAT(K_NLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: P_REFRAC(K_NLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_REFRAC_HAT(K_NLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_COMP(K_NLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ_COMP_HAT(K_NLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_NR_HAT(K_NLEV)
END SUBROUTINE GPSCALC_NRAD
END INTERFACE
