INTERFACE
SUBROUTINE GPSCALC_INIT_SPLINE_AD(KLEV,PX,PX_AD,PY,PY_AD,PY2,PY2_AD)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PY(KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PX_AD(KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY_AD(KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY2(KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY2_AD(KLEV)
END SUBROUTINE GPSCALC_INIT_SPLINE_AD
END INTERFACE
