INTERFACE
SUBROUTINE GPSCALC_NR2DTL(KLEV,KHORIZ,&
& P_ROC,P_LAT,P_ZG,P_ZG_PRIME,P_REFRAC,P_REFRAC_PRIME,&
& P_RAD,P_RAD_PRIME,P_NR,P_NR_PRIME) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
REAL(KIND=JPRB) ,INTENT(IN) :: P_ROC
REAL(KIND=JPRB) ,INTENT(IN) :: P_LAT
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_REFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_REFRAC_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_RAD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_RAD_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_NR(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_NR_PRIME(KLEV,KHORIZ)
END SUBROUTINE GPSCALC_NR2DTL
END INTERFACE
