INTERFACE
SUBROUTINE GPSCALC_NR(K_NLEV,P_ROC,P_LAT,P_ZG,P_REFRAC,PZ_COMP,P_NR,P_Z)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K_NLEV
REAL(KIND=JPRB) ,INTENT(IN) :: P_ROC
REAL(KIND=JPRB) ,INTENT(IN) :: P_LAT
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG(K_NLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: P_REFRAC(K_NLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_COMP(K_NLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_NR(K_NLEV)
REAL(KIND=JPRB) ,INTENT(OUT), OPTIONAL :: P_Z(K_NLEV)
END SUBROUTINE GPSCALC_NR
END INTERFACE
