INTERFACE
SUBROUTINE GPSCALC_INIT_SPLINE(KLEV,PX,PY,PY2)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PY(KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY2(KLEV)
END SUBROUTINE GPSCALC_INIT_SPLINE
END INTERFACE
