INTERFACE
SUBROUTINE GPSCALC_SPLINE_INTERP_AD(KLEV,KLEV2,KHORIZ,KSPLINE,&
 & P_ZG,P_ZG_AD,P_REFRAC,P_REFRAC_AD,PZ_COMP,&
 & PZ_COMP_AD,P_ZG_INT_AD,P_REFRAC_INT_AD) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV2
INTEGER(KIND=JPIM),INTENT(IN) :: KSPLINE
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_ZG_AD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_REFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_REFRAC_AD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_COMP(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ_COMP_AD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_ZG_INT_AD(KLEV2,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_REFRAC_INT_AD(KLEV2,KHORIZ)
END SUBROUTINE GPSCALC_SPLINE_INTERP_AD
END INTERFACE
