INTERFACE
SUBROUTINE GPSCALC_COMPRESS2DAD(KLEV,KHORIZ,PRES,PRES_HAT,PTEMP,PTEMP_HAT,PQ,PQ_HAT,&
& PZCOMP_MIX_HAT,PZCOMP_DRY_INV_HAT,PZCOMP_WET_INV_HAT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV,KHORIZ
REAL(KIND=JPRB),INTENT(IN) :: PRES(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(INOUT) :: PRES_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(IN) :: PTEMP(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(INOUT) :: PTEMP_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(IN) :: PQ(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(INOUT) :: PQ_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(INOUT) :: PZCOMP_MIX_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(INOUT) :: PZCOMP_DRY_INV_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB),INTENT(INOUT) :: PZCOMP_WET_INV_HAT(KLEV,KHORIZ)
END SUBROUTINE GPSCALC_COMPRESS2DAD
END INTERFACE
