INTERFACE
SUBROUTINE GPSCALC_ALPHA2DTL(KOBS,&
 & klev,&
 & khoriz,&
 & pdsep,&
 & pa,&
 & prefrac,&
 & prefrac_prime,&
 & pradius,&
 & pradius_prime,&
 & pnr,&
 & pnr_prime,&
 & pa_path_prime,&
 & palpha_prime) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KOBS
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KHORIZ
REAL(KIND=JPRB), INTENT(IN) :: PDSEP
REAL(KIND=JPRB), INTENT(IN) :: PA(KOBS)
REAL(KIND=JPRB), INTENT(IN) :: PREFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PREFRAC_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PRADIUS(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PRADIUS_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PNR(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PNR_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(OUT) :: PA_PATH_PRIME(KOBS,2)
REAL(KIND=JPRB), INTENT(OUT) :: PALPHA_PRIME(KOBS)
END SUBROUTINE GPSCALC_ALPHA2DTL
END INTERFACE
