INTERFACE
SUBROUTINE GPSCALC_NR2DAD(KLEV,KHORIZ,&
& P_ROC,P_LAT,P_ZG,P_ZG_HAT,P_REFRAC,P_REFRAC_HAT,&
& P_RAD_HAT,P_NR_HAT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
REAL(KIND=JPRB) ,INTENT(IN) :: P_ROC
REAL(KIND=JPRB) ,INTENT(IN) :: P_LAT
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_ZG_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_REFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_REFRAC_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_RAD_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_NR_HAT(KLEV,KHORIZ)
END SUBROUTINE GPSCALC_NR2DAD
END INTERFACE
