INTERFACE
SUBROUTINE GPSCALC_SPLINT_AD(KLEV,KLEV2,KHORIZ,P_ZG,P_ZG_AD,PLogN,PLogN_AD,PY2,&
& PY2_AD,PZG_INT,PZG_INT_AD,P_REFRAC_INT_AD) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV2
REAL(KIND=JPRB) ,INTENT(IN) :: P_ZG(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_ZG_AD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PLogN(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLogN_AD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PY2(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PY2_AD(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PZG_INT(KLEV2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZG_INT_AD(KLEV2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_REFRAC_INT_AD(KLEV2,KHORIZ)
END SUBROUTINE GPSCALC_SPLINT_AD
END INTERFACE
