INTERFACE
SUBROUTINE GPSCALC_REFRAC2DTL(KLEV,&
 & KHORIZ,&
 & PRES,&
 & PRES_PRIME,&
 & P_TEMP,&
 & P_TEMP_PRIME,&
 & P_Q,&
 & P_Q_PRIME,&
 & PZ_DRY,&
 & PZ_DRY_PRIME,&
 & PZ_WET,&
 & PZ_WET_PRIME,&
 & P_REFRAC,&
 & P_REFRAC_PRIME) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
REAL(KIND=JPRB) ,INTENT(IN) :: PRES(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PRES_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TEMP(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TEMP_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_Q(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_Q_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_DRY(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_DRY_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_WET(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ_WET_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_REFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_REFRAC_PRIME(KLEV,KHORIZ)
END SUBROUTINE GPSCALC_REFRAC2DTL
END INTERFACE
