INTERFACE
SUBROUTINE GPSKAP(YDGEOMETRY,LDCOMPUTE_SKAP,KPROMA,KST,KEND,PXYB,PIN,POU)
USE PARKIND1 , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE INTDYN_MOD , ONLY : YYTXYB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
LOGICAL, INTENT(IN) :: LDCOMPUTE_SKAP
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KST
INTEGER(KIND=JPIM), INTENT(IN) :: KEND
REAL(KIND=JPRB), INTENT(IN) :: PXYB(KPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB%NDIM)
REAL(KIND=JPRB), INTENT(IN) :: PIN(KPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: POU(KPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
END SUBROUTINE GPSKAP
END INTERFACE
