INTERFACE
SUBROUTINE GPSPDERIVSTL(KLEV,&
 & khoriz,&
 & kk,&
 & pdsep,&
 & ptheta_min,&
 & ptheta_max,&
 & ptheta_tan,&
 & prtan,&
 & prtan_prime,&
 & pamult,&
 & prefrac,&
 & prefrac_prime,&
 & pradius,&
 & pradius_prime,&
 & py,&
 & py_prime,&
 & pdydh,&
 & pdydh_prime) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM), INTENT(IN) :: KK
REAL(KIND=JPRB), INTENT(IN) :: PDSEP
REAL(KIND=JPRB), INTENT(IN) :: PTHETA_MIN
REAL(KIND=JPRB), INTENT(IN) :: PTHETA_MAX
REAL(KIND=JPRB), INTENT(IN) :: PTHETA_TAN
REAL(KIND=JPRB), INTENT(IN) :: PRTAN
REAL(KIND=JPRB), INTENT(IN) :: PRTAN_PRIME
REAL(KIND=JPRB), INTENT(IN) :: PAMULT
REAL(KIND=JPRB), INTENT(IN) :: PREFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PREFRAC_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PRADIUS(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PRADIUS_PRIME(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PY(4)
REAL(KIND=JPRB), INTENT(IN) :: PY_PRIME(4)
REAL(KIND=JPRB), INTENT(OUT) :: PDYDH(4)
REAL(KIND=JPRB), INTENT(OUT) :: PDYDH_PRIME(4)
END SUBROUTINE GPSPDERIVSTL
END INTERFACE
