INTERFACE
SUBROUTINE GPSPDERIVSAD(KLEV,&
 & khoriz,&
 & kk,&
 & pdsep,&
 & ptheta_min,&
 & ptheta_max,&
 & ptheta_tan,&
 & prtan,&
 & prtan_hat,&
 & pamult,&
 & prefrac,&
 & prefrac_hat,&
 & pradius,&
 & pradius_hat,&
 & py,&
 & py_hat,&
 & pdydh_hat) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM), INTENT(IN) :: KK
REAL(KIND=JPRB), INTENT(IN) :: PDSEP
REAL(KIND=JPRB), INTENT(IN) :: PTHETA_MIN
REAL(KIND=JPRB), INTENT(IN) :: PTHETA_MAX
REAL(KIND=JPRB), INTENT(IN) :: PTHETA_TAN
REAL(KIND=JPRB), INTENT(IN) :: PRTAN
REAL(KIND=JPRB), INTENT(INOUT) :: PRTAN_HAT
REAL(KIND=JPRB), INTENT(IN) :: PAMULT
REAL(KIND=JPRB), INTENT(IN) :: PREFRAC(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(INOUT) :: PREFRAC_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PRADIUS(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(INOUT) :: PRADIUS_HAT(KLEV,KHORIZ)
REAL(KIND=JPRB), INTENT(IN) :: PY(4)
REAL(KIND=JPRB), INTENT(INOUT) :: PY_HAT(4)
REAL(KIND=JPRB), INTENT(INOUT) :: PDYDH_HAT(4)
END SUBROUTINE GPSPDERIVSAD
END INTERFACE
