INTERFACE
SUBROUTINE GPSRO_TL(KFLEVG,ROBHDR,ROBODY,SATHDR,&
 & KDLEN,KDBDY,K_IMXCOUNT,KLEN,K_IVNMRQ,PRESF5,&
 & PRESF5_PRIME,P_TF5,P_TF5_PRIME,P_QF5,P_QF5_PRIME,&
 & P_GEOPF5,P_GEOPF5_PRIME,P_ZXPP_PRIME) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDBDY
INTEGER(KIND=JPIM),INTENT(IN) :: K_IMXCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: K_IVNMRQ(KDLEN,KDBDY)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5_PRIME(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TF5(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TF5_PRIME(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_QF5(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_QF5_PRIME(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_GEOPF5(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_GEOPF5_PRIME(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_ZXPP_PRIME(KDLEN,K_IMXCOUNT)
END SUBROUTINE GPSRO_TL
END INTERFACE
