INTERFACE
SUBROUTINE GPSRO_2DAD(KFLEVG,KLEV2,ROBHDR,ROBODY,SATHDR,&
 & KDLEN,KDBDY,KHORIZ,K_IMXCOUNT,KLEN,K_IVNMRQ,PRESF5,&
 & PRESF5_HAT,P_TF5,P_TF5_HAT,P_QF5,P_QF5_HAT,&
 & P_GEOPF5,P_GEOPF5_HAT,P_ZXPP_HAT) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV2
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDBDY
INTEGER(KIND=JPIM),INTENT(IN) :: KHORIZ
INTEGER(KIND=JPIM),INTENT(IN) :: K_IMXCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: K_IVNMRQ(KDLEN,KDBDY)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRESF5_HAT(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TF5(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_TF5_HAT(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_QF5(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_QF5_HAT(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(IN) :: P_GEOPF5(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_GEOPF5_HAT(KDLEN,KFLEVG,KHORIZ)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_ZXPP_HAT(KDLEN,K_IMXCOUNT)
END SUBROUTINE GPSRO_2DAD
END INTERFACE
