INTERFACE
SUBROUTINE GPSZEN_DELAYTL(KFLEVG,KDLEN,KLEN,KDCOUNT,LDPROCESS,&
 & PRESH, PGEOH, PTF, PQF,&
 & POROGOB,PRESOB,&
 & PZEN_DELAYTL,&
 & PRESH5,PGEOH5,PTF5,PQF5,&
 & PRESOB5,&
 & PZHD_DELAYTL, PZWD_DELAYTL) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG,KDLEN,KLEN,KDCOUNT
LOGICAL, INTENT(IN) :: LDPROCESS(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(IN) :: PRESH(KDLEN,0:KFLEVG),PGEOH(KDLEN,0:KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PTF(KDLEN,KFLEVG),PQF(KDLEN,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PRESH5(KDLEN,0:KFLEVG),PGEOH5(KDLEN,0:KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PTF5(KDLEN,KFLEVG),PQF5(KDLEN,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: POROGOB(KDLEN),PRESOB(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(IN) :: PRESOB5(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(OUT) :: PZEN_DELAYTL(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PZHD_DELAYTL(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PZWD_DELAYTL(KDLEN,KDCOUNT)
END SUBROUTINE GPSZEN_DELAYTL
END INTERFACE
