INTERFACE
SUBROUTINE GPSZEN_DELAY(KFLEVG,KDLEN,KLEN,KDCOUNT,LDPROCESS,&
 & PRESH5,PGEOH5,PTF5,PQF5,&
 & POROGOB,PRESOB,&
 & PZEN_DELAY,&
 & PZHD_DELAY,PZWD_DELAY) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG, KDLEN, KLEN,KDCOUNT
REAL(KIND=JPRB), INTENT(IN) :: PRESH5(KDLEN,0:KFLEVG),PGEOH5(KDLEN,0:KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PTF5(KDLEN,KFLEVG),PQF5(KDLEN,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: POROGOB(KDLEN),PRESOB(KDLEN,KDCOUNT)
LOGICAL, INTENT(IN) :: LDPROCESS(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(OUT) :: PZEN_DELAY(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PZHD_DELAY(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PZWD_DELAY(KDLEN,KDCOUNT)
END SUBROUTINE GPSZEN_DELAY
END INTERFACE
