INTERFACE
SUBROUTINE GPSZEN_DELAYAD(KFLEVG,KDLEN,KLEN,KDCOUNT,LDPROCESS,&
 & PRESH, PGEOH, PTF, PQF,&
 & POROGOB,PRESOB,&
 & PZEN_DELAYAD,&
 & PRESH5,PGEOH5,PTF5,PQF5,&
 & PRESOB5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG,KDLEN,KLEN,KDCOUNT
LOGICAL, INTENT(IN) :: LDPROCESS(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(INOUT) :: PRESH(KDLEN,0:KFLEVG),PGEOH(KDLEN,0:KFLEVG)
REAL(KIND=JPRB), INTENT(INOUT) :: PTF(KDLEN,KFLEVG),PQF(KDLEN,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PRESH5(KDLEN,0:KFLEVG),PGEOH5(KDLEN,0:KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: PTF5(KDLEN,KFLEVG),PQF5(KDLEN,KFLEVG)
REAL(KIND=JPRB), INTENT(IN) :: POROGOB(KDLEN)
REAL(KIND=JPRB), INTENT(INOUT) :: PRESOB(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(IN) :: PRESOB5(KDLEN,KDCOUNT)
REAL(KIND=JPRB), INTENT(INOUT) :: PZEN_DELAYAD(KDLEN,KDCOUNT)
END SUBROUTINE GPSZEN_DELAYAD
END INTERFACE
