INTERFACE
SUBROUTINE GPTET(KPROMA,KSTART,KPROF,KFLEV,PRESF,PT,PKAP,PTETA)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKAP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTETA(KPROMA,KFLEV)
END SUBROUTINE GPTET
END INTERFACE
