INTERFACE
SUBROUTINE GPTF2_EXPL_3TL_PART1 (YDGEOMETRY, YDML_GCONF, YDDYN, KST, KEN, LDFSTEP, LDNHDYN, KVDVAR,&
 & P0SP, P0SPL, P0SPM, P9SP, P9SPL, P9SPM, P0DIV, P0NHX, P0SPD, P0SPDL, P0SPDM, P0SVD, P0SVDL, P0SVDM,&
 & P0T, P0TL, P0TM, P0U, P0V, P9DIV, P9NHX, P9SPD, P9SPDL, P9SPDM, P9SVD, P9SVDL, P9SVDM, P9T, P9TL,&
 & P9TM, P9U, P9V) 
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE) ,INTENT(IN) :: YDML_GCONF
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM) ,INTENT(IN) :: KST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEN
LOGICAL ,INTENT(IN) :: LDFSTEP
LOGICAL ,INTENT(IN) :: LDNHDYN
INTEGER(KIND=JPIM) ,INTENT(IN) :: KVDVAR
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA) ,INTENT(INOUT) ,OPTIONAL :: P0SP
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA) ,INTENT(INOUT) ,OPTIONAL :: P0SPL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA) ,INTENT(INOUT) ,OPTIONAL :: P0SPM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA) ,INTENT(INOUT) ,OPTIONAL :: P9SP
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA) ,INTENT(INOUT) ,OPTIONAL :: P9SPL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA) ,INTENT(INOUT) ,OPTIONAL :: P9SPM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0DIV
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0NHX
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0SPD
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0SPDL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0SPDM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0SVD
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0SVDL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0SVDM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0T
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0TL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0TM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0U
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0V
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9DIV
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9NHX
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9SPD
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9SPDL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9SPDM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9SVD
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9SVDL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9SVDM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9T
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9TL
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9TM
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9U
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9V
END SUBROUTINE
END INTERFACE
