INTERFACE
SUBROUTINE GPTF2_EXPL_3TL_PART2 (YDGEOMETRY, YDDYN, KST, KEN, LDFSTEP, YDVARS)
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELD_VARIABLES_MOD , ONLY : FIELD_VARIABLES
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEN
LOGICAL ,INTENT(IN) :: LDFSTEP
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
END SUBROUTINE
END INTERFACE
