INTERFACE
SUBROUTINE GPTF2_EXPL_2TL (YDGEOMETRY, KST, KEN, LDFSTEP, P0U, P0V, P9U, P9V)
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEN
LOGICAL ,INTENT(IN) :: LDFSTEP
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0U
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P0V
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9U
REAL(KIND=JPRB) ,DIMENSION(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) ,INTENT(INOUT) ,OPTIONAL :: P9V
END SUBROUTINE
END INTERFACE
