INTERFACE
SUBROUTINE GPUVSAD(&
 & KFLEV,KPROMA,KSTART,KEND,LDER,&
 & PUF,PVF,&
 & PUS,PVS,&
 & PDIVF,PVORF,PUFL,PVFL,&
 & PUS_L,PVS_L,PUS_M,PVS_M&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
LOGICAL ,INTENT(IN) :: LDER
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVS(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PDIVF(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PVORF(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PUFL(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PVFL(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PUS_L(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PVS_L(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PUS_M(KPROMA)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PVS_M(KPROMA)
END SUBROUTINE GPUVSAD
END INTERFACE
