INTERFACE
SUBROUTINE GPYY( LDVERTFE, LDVFE_GW, YDGEOMETRY, KFLEV, KPROMA, KST, KEND, POROGL, POROGM, PUH,&
 & PVH, PNHY) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
LOGICAL ,INTENT(IN) :: LDVERTFE
LOGICAL ,INTENT(IN) :: LDVFE_GW
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNHY(KPROMA,0:KFLEV)
END SUBROUTINE GPYY
END INTERFACE
