INTERFACE
SUBROUTINE GRIB_CODE_MESSAGE(PTSTEP,KGRIB_HANDLE,KGRIBCD,KLEV,CDREPR,CDLTYPE,&
 & LDGRAD,LDVALID,KTOP,KBOT,KSMAX) 
USE PARKIND1 , ONLY : JPIM, JPRB
REAL(KIND=JPRB) , INTENT(IN) :: PTSTEP
INTEGER(KIND=JPIM), INTENT(IN) :: KGRIB_HANDLE
INTEGER(KIND=JPIM), INTENT(IN) :: KGRIBCD
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
CHARACTER , INTENT(IN) :: CDREPR*(*)
CHARACTER , INTENT(IN) :: CDLTYPE*(*)
LOGICAL , INTENT(OUT) :: LDGRAD
LOGICAL , INTENT(OUT) :: LDVALID
INTEGER(KIND=JPIM), INTENT(OUT) :: KTOP
INTEGER(KIND=JPIM), INTENT(OUT) :: KBOT
INTEGER(KIND=JPIM), OPTIONAL,INTENT(IN) :: KSMAX
END SUBROUTINE GRIB_CODE_MESSAGE
END INTERFACE
