INTERFACE
SUBROUTINE GRID_PSGLOBAL(YDGEOMETRY,PSPSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1,ONLY: JPIM, JPRB
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB), INTENT(IN) :: PSPSP(YDGEOMETRY%YRDIM%NSPEC2)
END SUBROUTINE GRID_PSGLOBAL
END INTERFACE
