INTERFACE
SUBROUTINE GRID_MINMAXAVG(YDGEOMETRY,KFLD,PGRID)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
REAL(KIND=JPRB) ,INTENT(IN) :: PGRID(YDGEOMETRY%YRDIM%NPROMA,KFLD,YDGEOMETRY%YRDIM%NGPBLKS)
END SUBROUTINE GRID_MINMAXAVG
END INTERFACE
