INTERFACE
SUBROUTINE GRIDPOINT_NORM(YDGEOMETRY,YDGRID,CDGREP,LDLEVS)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE GRIDPOINT_FIELDS_MIX, ONLY: GRIDPOINT_FIELD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(GRIDPOINT_FIELD),INTENT(IN) :: YDGRID
CHARACTER(LEN=*) ,INTENT(IN) :: CDGREP
LOGICAL, OPTIONAL, INTENT(IN) :: LDLEVS
END SUBROUTINE GRIDPOINT_NORM
END INTERFACE
