INTERFACE
SUBROUTINE GRID_BICONSERV (PVAH,PVBH, KLAT_IN,KLON_IN,PLAT_IN,KIN,&
 & KLAT_OUT,KLON_OUT,PLAT_OUT,KOUT,&
 & PFLD_IN,PFLD_OUT,&
 & LDPAR,KLEVEL,PSP_IN,PSP_OUT) 
USE PARKIND1 , ONLY : JPIM, JPRB
REAL (KIND=JPRB), INTENT(IN) :: PVAH(0:)
REAL (KIND=JPRB), INTENT(IN) :: PVBH(0:)
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT_IN
INTEGER(KIND=JPIM),INTENT(IN) :: KLON_IN(KLAT_IN)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT_IN(KLAT_IN)
INTEGER(KIND=JPIM),INTENT(IN) :: KIN
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT_OUT
INTEGER(KIND=JPIM),INTENT(IN) :: KLON_OUT(KLAT_OUT)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT_OUT(KLAT_OUT)
INTEGER(KIND=JPIM),INTENT(IN) :: KOUT
REAL(KIND=JPRB) ,INTENT(IN) :: PFLD_IN(KIN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLD_OUT(KOUT)
LOGICAL, OPTIONAL, INTENT(IN) :: LDPAR
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KLEVEL
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSP_IN(KIN)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSP_OUT(KOUT)
END SUBROUTINE GRID_BICONSERV
END INTERFACE
