INTERFACE
SUBROUTINE GRTESTR(YDGEOMETRY,SIMUL,SCAPR,KDIM,PX,PF,PG,PDXINI,KNBMAX)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
EXTERNAL SIMUL,SCAPR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PDXINI,PX(KDIM),PF,PG(KDIM)
INTEGER(KIND=JPIM),INTENT(IN) :: KNBMAX,KDIM
END SUBROUTINE GRTESTR
END INTERFACE
