INTERFACE
SUBROUTINE GRTEST(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDJOT,YDVARBC,YDGOM,YDGOM5,SCAPR,YD_PX,PDXINI,KNBMAX,KOUT,YDODB)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE PARKIND1 , ONLY : JPIM ,JPRB
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE SUPERGOM_CLASS, ONLY : CLASS_SUPERGOM
USE DBASE_MOD , ONLY : DBASE
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(JO_TABLE) ,INTENT(INOUT) :: YDJOT
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(CLASS_SUPERGOM),INTENT(INOUT) :: YDGOM
TYPE(CLASS_SUPERGOM),INTENT(INOUT) :: YDGOM5
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_PX
REAL(KIND=JPRB) ,INTENT(IN) :: PDXINI
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNBMAX
INTEGER(KIND=JPIM) ,INTENT(IN) :: KOUT
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
EXTERNAL SCAPR
END SUBROUTINE GRTEST
END INTERFACE
