INTERFACE
SUBROUTINE GTOPTXY(KLAT,KLON,KJJ1,KJJ2,PREL)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KJJ1
INTEGER(KIND=JPIM),INTENT(IN) :: KJJ2
REAL(KIND=JPRB) ,INTENT(INOUT) :: PREL(KLON,KLAT)
END SUBROUTINE GTOPTXY
END INTERFACE
