INTERFACE
SUBROUTINE GTOPTY2(KLAT,KLON,PREL)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
REAL(KIND=JPRB) ,INTENT(INOUT) :: PREL(KLON,KLAT)
END SUBROUTINE GTOPTY2
END INTERFACE
