INTERFACE
SUBROUTINE GWDRAG_LAYER(YDSURF,&
 & YDEPHLI,YDEGWD,KDIM, PAUX, STATE,&
 & PSURF, AUXL) 
USE YOEGWD , ONLY : TEGWD
USE YOEPHLI , ONLY : TEPHLI
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & AUX_DIAG_LOCAL_TYPE, SURF_AND_MORE_TYPE 
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TEGWD) ,INTENT(INOUT) :: YDEGWD
TYPE(TEPHLI),INTENT(INOUT) :: YDEPHLI
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
END SUBROUTINE GWDRAG_LAYER
END INTERFACE
