INTERFACE
SUBROUTINE GWDRAG_WMSS(YDEGWD,YDEGWWMS,KIDIA, KFDIA, KLON , KLEV , PTSTEP,&
 & PTM1 , PUM1 , PVM1 , PAPM1 , PAPHM1, PGEO1 ,&
 & PGELAT,PGAW ,&
 & PTENU, PTENV, PFLUXU, PFLUXV) 
USE PARKIND1, ONLY : JPIM, JPRB
USE YOEGWWMS, ONLY : TEGWWMS
USE YOEGWD, ONLY : TEGWD
TYPE(TEGWD) ,INTENT(INOUT):: YDEGWD
TYPE(TEGWWMS) ,INTENT(INOUT):: YDEGWWMS
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB),INTENT(IN) :: PGEO1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PGAW(KLON)
REAL(KIND=JPRB),INTENT(OUT):: PTENU(KLON,KLEV)
REAL(KIND=JPRB),INTENT(OUT):: PTENV(KLON,KLEV)
REAL(KIND=JPRB),INTENT(OUT):: PFLUXU(KLON,KLEV+1)
REAL(KIND=JPRB),INTENT(OUT):: PFLUXV(KLON,KLEV+1)
END SUBROUTINE GWDRAG_WMSS
END INTERFACE
