INTERFACE
SUBROUTINE GWDRAGS( YDEPHLI,YDEGWD,KIDIA,KFDIA,KLON,KLEV,&
 & PTSPHY, KSTEP, KSTART,&
 & PAPHM1,PAPM1,PGEOM1,&
 & PTM1,PUM1,PVM1,&
 & PHSTD , PGAMMA, PTHETA, PSIG,&
 & PUSTRGW,PVSTRGW,PVDISGW,PVOL,PVOM,PTE,&
 & PSTRDU,PSTRDV ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOEGWD , ONLY : TEGWD
USE YOEPHLI , ONLY : TEPHLI
TYPE(TEGWD) ,INTENT(INOUT) :: YDEGWD
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PHSTD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGAMMA(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTHETA(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUSTRGW(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVSTRGW(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDISGW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRDU(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRDV(KLON,KLEV+1)
END SUBROUTINE GWDRAGS
END INTERFACE
