INTERFACE
SUBROUTINE GWPROFIL&
 & ( YDEPHLI,YDEGWD,KIDIA ,KFDIA ,KLON , KLEV,&
 & LDGWD,&
 & KKCRITH, KCRIT , KKENVH, KKNU,KKNU2,&
 & PAPHM1, PRHO , PSTAB , PVPH , PRI , PTAU,&
 & PDMOD , PSIG , PHSTD ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOEGWD , ONLY : TEGWD
USE YOEPHLI , ONLY : TEPHLI
TYPE(TEGWD) ,INTENT(INOUT) :: YDEGWD
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL ,INTENT(IN) :: LDGWD(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KKCRITH(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCRIT(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KKENVH(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KKNU(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KKNU2(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHO(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTAB(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PVPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PRI(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAU(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PDMOD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIG(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHSTD(KLON)
END SUBROUTINE GWPROFIL
END INTERFACE
