INTERFACE
SUBROUTINE HJO(ROBHDR,ROBODY,SCATTBODY,&
 & YDSET,KDOBS,KCMBDY,KCDTYP,KVNMRQ,PHOFX,PNDBIAS,PTIME,KSCAN,YDJOT) 
USE PARKIND1 , ONLY : JPIM ,JPRB ,JPRD
USE JO_TABLE_MOD, ONLY : JO_TABLE
USE OBSOP_SETS , ONLY : TYPE_SET_INFO
USE IFS_DBASE_VIEW_MOD , ONLY: IFS_DBASE_VIEW
USE RANDOM_NUMBERS_MIX
TYPE(IFS_DBASE_VIEW), TARGET, INTENT(INOUT) :: ROBHDR, ROBODY
TYPE(IFS_DBASE_VIEW), TARGET, INTENT(IN) :: SCATTBODY
INTEGER(KIND=JPIM), INTENT(IN) :: KDOBS
TYPE(TYPE_SET_INFO), INTENT(IN) :: YDSET
INTEGER(KIND=JPIM), INTENT(IN) :: KCMBDY(KDOBS)
INTEGER(KIND=JPIM), INTENT(IN) :: KCDTYP(KDOBS)
INTEGER(KIND=JPIM), INTENT(IN) :: KVNMRQ(KDOBS,YDSET%MXBDY)
REAL(KIND=JPRB), INTENT(INOUT) :: PHOFX(KDOBS,YDSET%MXBDY)
REAL(KIND=JPRB), INTENT(INOUT) :: PNDBIAS(KDOBS,YDSET%MXBDY)
INTEGER(KIND=JPIM), INTENT(IN) :: KSCAN
REAL(KIND=JPRB), INTENT(IN) :: PTIME(KDOBS)
TYPE(JO_TABLE), INTENT(INOUT) :: YDJOT
END SUBROUTINE HJO
END INTERFACE
