INTERFACE
SUBROUTINE HLRADIA ( KHOR , KLEV , KSTART , KSTOP , PHYBF ,&
 & PHYBH , PSA , PSCOS , PALBEDO , PEMSURF ,&
 & PFRLAND , PTSK , PT , PQ , PCLQ ,&
 & PCICE , PF , PH , PDPF , PTOTCOV ,&
 & LDSTAT , PSALBCOR,&
 & pstrad , pstdrad , pstclo , pstdclo , pslwdn ,&
 & psswdf ,&
 & psswdn , pslwnet , psswnet , ptswdn , ptlwnet ,&
 & ptswnet , plwnet , pswnet , pdtdt ) 
USE PARKIND1 ,ONLY : JPIM , JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KHOR
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KSTART
INTEGER(KIND=JPIM), INTENT(IN) :: KSTOP
REAL(KIND=JPRB), INTENT(IN) :: PHYBF(KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PHYBH(KLEV+1)
REAL(KIND=JPRB), INTENT(IN) :: PSA
REAL(KIND=JPRB), INTENT(IN) :: PSCOS(KHOR)
REAL(KIND=JPRB), INTENT(IN) :: PALBEDO(KHOR)
REAL(KIND=JPRB), INTENT(IN) :: PEMSURF(KHOR)
REAL(KIND=JPRB), INTENT(IN) :: PFRLAND(KHOR)
REAL(KIND=JPRB), INTENT(IN) :: PTSK(KHOR)
REAL(KIND=JPRB), INTENT(IN) :: PT(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQ(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCLQ(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCICE(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PF(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PH(KHOR,KLEV+1)
REAL(KIND=JPRB), INTENT(IN) :: PDPF(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTOTCOV(KHOR,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PSALBCOR(KHOR)
LOGICAL, INTENT(IN) :: LDSTAT
REAL(KIND=JPRB), INTENT(INOUT) :: PSTRAD(KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSTDRAD(KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSTCLO(KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSTDCLO(KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PSLWDN(KHOR)
REAL(KIND=JPRB), INTENT(INOUT) :: PSSWDN(KHOR)
REAL(KIND=JPRB), INTENT(INOUT) :: PSSWDF(KHOR)
REAL(KIND=JPRB), INTENT(OUT) :: PSLWNET(KHOR)
REAL(KIND=JPRB), INTENT(OUT) :: PSSWNET(KHOR)
REAL(KIND=JPRB), INTENT(OUT) :: PTSWDN(KHOR)
REAL(KIND=JPRB), INTENT(OUT) :: PTLWNET(KHOR)
REAL(KIND=JPRB), INTENT(OUT) :: PTSWNET(KHOR)
REAL(KIND=JPRB), INTENT(OUT) :: PLWNET(KHOR,KLEV+1)
REAL(KIND=JPRB), INTENT(OUT) :: PSWNET(KHOR,KLEV+1)
REAL(KIND=JPRB), INTENT(OUT) :: PDTDT(KHOR,KLEV)
END SUBROUTINE HLRADIA
END INTERFACE
