INTERFACE
SUBROUTINE HOP(YDGP5,YDODB,YDJOT,YDVARBC,YDTCV5,YDSET,PHOFX,PBIAS,PNDBIAS,YDPHY,YDGP_TL,&
 & YDGP_AD,YDTCV_TL,YDTCV_AD,PHOFX_FLAT,PNDBIAS_FLAT,NOTVAR,YDHOP_RESULTS) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS,IH
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_MOD , ONLY : TOVSCV
USE OBSOP_SETS , ONLY : TYPE_SET_INFO
USE YOMHOP_RESULTS , ONLY : THOP_RESULTS
USE YOMDB
USE DBASE_MOD
USE DBASE_MOD , ONLY : DBASE
USE YOMPHY , ONLY : TPHY
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
CLASS(DBASE), INTENT(INOUT) :: YDODB
TYPE(JO_TABLE), INTENT(IN) :: YDJOT
CLASS(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV), INTENT(IN) :: YDTCV5
TYPE(TYPE_SET_INFO), INTENT(IN) :: YDSET
REAL(KIND=JPRB), INTENT(INOUT) :: PHOFX(YDGP5%NDLEN,YDSET%MXBDY)
REAL(KIND=JPRB), INTENT(INOUT) :: PBIAS(YDGP5%NDLEN,YDSET%MXBDY)
REAL(KIND=JPRB), INTENT(INOUT) :: PNDBIAS(YDGP5%NDLEN,YDSET%MXBDY)
TYPE(TPHY), INTENT(IN) :: YDPHY
REAL(KIND=JPRB), INTENT(INOUT), OPTIONAL :: PHOFX_FLAT(:)
REAL(KIND=JPRB), INTENT(INOUT), OPTIONAL :: PNDBIAS_FLAT(:)
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: NOTVAR(:,:)
TYPE(TYPE_GOM_PLUS), INTENT(IN), OPTIONAL :: YDGP_TL
TYPE(TYPE_GOM_PLUS), INTENT(INOUT), OPTIONAL :: YDGP_AD
TYPE(TOVSCV), INTENT(IN), OPTIONAL :: YDTCV_TL
TYPE(TOVSCV), INTENT(INOUT), OPTIONAL :: YDTCV_AD
TYPE(THOP_RESULTS), INTENT(INOUT), OPTIONAL :: YDHOP_RESULTS
END SUBROUTINE HOP
END INTERFACE
