INTERFACE
SUBROUTINE HPOS(YDRQPHY,YDRQCLI,YDNAMFPSCI,YDAFN,LDFPOSHOR,YDGEOMETRY,YDSURF,YDMODEL,KEND,KSTGLO,&
 & PSP_SB, PSP_SG, PSP_SL, PSP_RR, PSP_CI, PSD_WS, PSD_VD, PSD_VX,&
 & PSD_VF, PSD_VV, PSD_VP, PSD_VA, PSD_VC, PSD_X2,PSD_SM, PSD_OC, PWSXI, PWDXI,&
 & PFPBUF1) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMAFN , ONLY : TAFN
USE YOMFPC , ONLY : TNAMFPSCI
USE YOMFP4L , ONLY : TRQFP, IFPSEARCH
TYPE (TRQFP) ,INTENT(IN) :: YDRQPHY
TYPE (TRQFP) ,INTENT(IN) :: YDRQCLI
TYPE (TNAMFPSCI) ,INTENT(IN) :: YDNAMFPSCI
TYPE (TAFN) ,INTENT(IN) :: YDAFN
LOGICAL ,INTENT(IN) :: LDFPOSHOR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PSP_SB(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP_SG(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP_SL(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP_RR(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSP_CI(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_WS(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VD(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VX(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VF(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VV(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VP(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VA(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VC(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_X2(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_SM(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_OC(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSXI
REAL(KIND=JPRB) ,INTENT(IN) :: PWDXI
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPBUF1(YDGEOMETRY%YRDIM%NPROMA,YDRQPHY%NFIELDG)
END SUBROUTINE HPOS
END INTERFACE
