INTERFACE
SUBROUTINE HPOS_CFU(YDAFN,LDFPOSHOR,YDCFU,KPROMA,KFLEVG,KEND,KC,KFPCLI,PCFU,PFPBUF1)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMCFU , ONLY : TCFU
USE YOMAFN, ONLY : TAFN
TYPE (TAFN), INTENT(IN) :: YDAFN
LOGICAL ,INTENT(IN) :: LDFPOSHOR
TYPE(TCFU) ,INTENT(IN) :: YDCFU
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KC
INTEGER(KIND=JPIM),INTENT(IN) :: KFPCLI
REAL(KIND=JPRB) ,INTENT(IN) :: PCFU(KPROMA,YDCFU%NFDCFU)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFPBUF1(KPROMA)
END SUBROUTINE HPOS_CFU
END INTERFACE
