INTERFACE
SUBROUTINE HPOS_DYN(YDQTYPE,YDNAMFPSCI,YDAFN,LDFPOSHOR,YDGEOMETRY,KEND,YDGSGEOM,KGPP,KAUX,PGPP,PAUX,KFLDIN,PARFP1,PFPBUF1)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMAFN, ONLY : TAFN
USE YOMFPC, ONLY : TNAMFPSCI
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
USE YOMGSGEOM, ONLY : TGSGEOM
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN) ,INTENT(IN) :: YDAFN
LOGICAL ,INTENT(IN) :: LDFPOSHOR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
INTEGER(KIND=JPIM),INTENT(IN) :: KGPP
INTEGER(KIND=JPIM),INTENT(IN) :: KAUX
REAL(KIND=JPRB) ,INTENT(IN) :: PGPP(YDGEOMETRY%YRDIM%NPROMA,KGPP)
REAL(KIND=JPRB) ,INTENT(IN) :: PAUX(YDGEOMETRY%YRDIM%NPROMA,KAUX)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDIN
REAL(KIND=JPRB) ,INTENT(INOUT) :: PARFP1(KFLDIN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPBUF1(YDGEOMETRY%YRDIM%NPROMA,KFLDIN)
END SUBROUTINE HPOS_DYN
END INTERFACE
