INTERFACE
SUBROUTINE HRADP_ML_TL(YDGP5,YDTCV5,YDGP_TL,YDTCV_TL,ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,&
 & KDLEN,KSET,KOBSTYPE,KGROUP,KCOEF,&
 & PPS ,PTS ,PT2M ,PQ2M ,PCTOP,PCAMT,&
 & PPS5,PTS5,PT2M5,PQ2M5,PCTOP5,PCAMT5,&
 & PO3F,PO3F5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE TOVSCV_MOD,ONLY : TOVSCV
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
TYPE(TOVSCV), INTENT(IN) :: YDTCV5
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP_TL
TYPE(TOVSCV), INTENT(IN) :: YDTCV_TL
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KSET
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSTYPE,KGROUP
INTEGER(KIND=JPIM),INTENT(OUT) :: KCOEF
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPS(KDLEN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS(KDLEN),PCTOP(KDLEN),PCAMT(KDLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PT2M(KDLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQ2M(KDLEN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPS5(KDLEN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS5(KDLEN),PCTOP5(KDLEN),PCAMT5(KDLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PT2M5(KDLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQ2M5(KDLEN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PO3F(KDLEN,YDGP5%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PO3F5(KDLEN,YDGP5%NFLEVG)
END SUBROUTINE HRADP_ML_TL
END INTERFACE
