INTERFACE
SUBROUTINE HRADP_ML_O3CLRT(KLEV, PPRESF, PO3)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
REAL(KIND=JPRB), INTENT(IN) :: PPRESF(KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PO3(KLEV)
END SUBROUTINE HRADP_ML_O3CLRT
END INTERFACE
