INTERFACE
SUBROUTINE HRETR_RAD(ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,YDSET,YDGP5,YDTCV5,YDJOT,YDVARBC)
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_MOD,ONLY : TOVSCV
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY: TYPE_SET_INFO
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
TYPE(TYPE_SET_INFO), INTENT(IN) :: YDSET
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
TYPE(TOVSCV), INTENT(IN) :: YDTCV5
TYPE(JO_TABLE), INTENT(IN) :: YDJOT
CLASS(CLASS_VARBC), INTENT(IN) :: YDVARBC
END SUBROUTINE HRETR_RAD
END INTERFACE
