INTERFACE
SUBROUTINE HSATANG(SATHDR,KLEN,KOBSTYPE,KSATGRP,PNVANG,PZEANG,KFOVOB)
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: SATHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSTYPE
INTEGER(KIND=JPIM),INTENT(IN) :: KSATGRP
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KFOVOB(KLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNVANG(KLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZEANG(KLEN)
END SUBROUTINE HSATANG
END INTERFACE
