INTERFACE
SUBROUTINE ICESTATENEMO(YDMCC,KSTGLO,KIDIA,KFDIA,PTHKICE,PSNTICE,PALBICE,PTEMPSEA,PTEMPICE)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMMCC , ONLY : TMCC
TYPE(TMCC) ,INTENT(INOUT):: YDMCC
INTEGER(KIND=JPIM), INTENT(IN) :: KSTGLO, KIDIA, KFDIA
REAL(KIND=JPRB),INTENT(INOUT), DIMENSION(KIDIA:KFDIA), OPTIONAL :: PTHKICE
REAL(KIND=JPRB),INTENT(INOUT), DIMENSION(KIDIA:KFDIA), OPTIONAL :: PSNTICE
REAL(KIND=JPRB),INTENT(INOUT), DIMENSION(KIDIA:KFDIA), OPTIONAL :: PALBICE
REAL(KIND=JPRB),INTENT(INOUT), DIMENSION(KIDIA:KFDIA), OPTIONAL :: PTEMPSEA
REAL(KIND=JPRB),INTENT(INOUT), DIMENSION(KIDIA:KFDIA), OPTIONAL :: PTEMPICE
END SUBROUTINE ICESTATENEMO
END INTERFACE
