INTERFACE
SUBROUTINE IFS_INIT(CDEXPV,KCOMM)
USE PARKIND1, ONLY : JPRB, JPIM
CHARACTER (LEN=4), INTENT(IN), OPTIONAL :: CDEXPV
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KCOMM
END SUBROUTINE IFS_INIT
END INTERFACE
