INTERFACE
SUBROUTINE IFSODBDDR1F(KSLOT ,&
 & KCMDDR1,&
 & KNDATRE,KMXDRL ,KMXCRL ,KNOOBS ,&
 & KNOSYNO,KNOAIRE,KNOSATO,KNODRIB,&
 & KNOTEMP,KNOPILO,KNOSTNR,KNOSTRA,KNOSTRAA,&
 & KNOPAOB,KNOSCAT,KNOLIMB,KNOSSMI,KNOREO3,&
 & KCMALEN ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCMA
USE YOMCMDDR
USE YOMMKODB
INTEGER(KIND=JPIM),INTENT(IN) :: KSLOT
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCMDDR1(NMXDCL)
INTEGER(KIND=JPIM),INTENT(IN) :: KNDATRE
INTEGER(KIND=JPIM),INTENT(IN) :: KMXDRL
INTEGER(KIND=JPIM),INTENT(IN) :: KMXCRL
INTEGER(KIND=JPIM),INTENT(IN) :: KNOOBS
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSYNO
INTEGER(KIND=JPIM),INTENT(IN) :: KNOAIRE
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSATO
INTEGER(KIND=JPIM),INTENT(IN) :: KNODRIB
INTEGER(KIND=JPIM),INTENT(IN) :: KNOTEMP
INTEGER(KIND=JPIM),INTENT(IN) :: KNOPILO
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSTNR
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSTRA
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSTRAA
INTEGER(KIND=JPIM),INTENT(IN) :: KNOPAOB
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSCAT
INTEGER(KIND=JPIM),INTENT(IN) :: KNOLIMB
INTEGER(KIND=JPIM),INTENT(IN) :: KNOSSMI
INTEGER(KIND=JPIM),INTENT(IN) :: KNOREO3
INTEGER(KIND=JPIM),INTENT(IN) :: KCMALEN
END SUBROUTINE IFSODBDDR1F
END INTERFACE
