INTERFACE
SUBROUTINE IFSODBDDR1S(KCMDDR1)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCMA
USE YOMMKODB
USE YOMCMDDR
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCMDDR1(NMXDCL)
END SUBROUTINE IFSODBDDR1S
END INTERFACE
