INTERFACE
SUBROUTINE IMAGER_CLOUD_DETECT(&
 & K__SENSOR,&
 & K__NCHANS,&
 & K__NCLUST,&
 & K__CLOUD_FLAG,&
 & P__CL_FRACTION,&
 & P__CL_MEAN,&
 & P__OV_STDDEV,&
 & P__FG_BT ) 
USE PARKIND1 ,ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K__SENSOR
INTEGER(KIND=JPIM),INTENT(IN) :: K__NCHANS
INTEGER(KIND=JPIM),INTENT(IN) :: K__NCLUST
INTEGER(KIND=JPIM),INTENT(OUT) :: K__CLOUD_FLAG
REAL(KIND=JPRB) ,INTENT(IN) :: P__CL_FRACTION(K__NCLUST)
REAL(KIND=JPRB) ,INTENT(IN) :: P__CL_MEAN(K__NCHANS,K__NCLUST)
REAL(KIND=JPRB) ,INTENT(IN) :: P__OV_STDDEV(K__NCHANS)
REAL(KIND=JPRB) ,INTENT(IN) :: P__FG_BT(K__NCHANS)
END SUBROUTINE IMAGER_CLOUD_DETECT
END INTERFACE
