INTERFACE
SUBROUTINE INCFPF(KNFG,KNFD,KFLDOFF,KBFA,KFPROMA,KFIELDS,KBLOCKS,KLAST,KGPG,KGPD,KGPIND,PREALG,PGP)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMMP0 , ONLY : MYPROC, NPRCIDS, NPROC
INTEGER(KIND=JPIM), INTENT(IN) :: KNFG
INTEGER(KIND=JPIM), INTENT(IN) :: KNFD(NPROC)
INTEGER(KIND=JPIM), INTENT(IN) :: KFLDOFF(NPROC)
INTEGER(KIND=JPIM), INTENT(IN) :: KBFA
INTEGER(KIND=JPIM), INTENT(IN) :: KFPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM), INTENT(IN) :: KBLOCKS
INTEGER(KIND=JPIM), INTENT(IN) :: KLAST(KBLOCKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KGPG
INTEGER(KIND=JPIM), INTENT(IN) :: KGPD(NPROC)
INTEGER(KIND=JPIM), INTENT(IN) :: KGPIND(MAXVAL(KGPD),NPROC)
REAL(KIND=JPRB), INTENT(IN) :: PREALG(KGPG,KNFD(MYPROC))
REAL(KIND=JPRB), INTENT(INOUT) :: PGP(KFPROMA,KFIELDS,KBLOCKS)
END SUBROUTINE INCFPF
END INTERFACE
