INTERFACE
SUBROUTINE INCGPF(YDGEOMETRY,KFIELDS,PGPBUF,KFLDPTP,PREAL)
USE GEOMETRY_MOD ,ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
REAL (KIND=JPRB) ,INTENT(INOUT) :: PGPBUF (:,:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDPTP(SIZE (PGPBUF, 2))
REAL(KIND=JPRB) ,INTENT(IN) :: PREAL(YDGEOMETRY%YRGEM%NGPTOT,KFIELDS)
END SUBROUTINE INCGPF
END INTERFACE
