INTERFACE
SUBROUTINE INCLI3(YDGEOMETRY,YDSURF,YDPHY,YDPHY1)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHY , ONLY : TPHY
USE YOMPHY1 , ONLY : TPHY1
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TPHY) ,INTENT(INOUT) :: YDPHY
TYPE(TPHY1) ,INTENT(INOUT) :: YDPHY1
END SUBROUTINE INCLI3
END INTERFACE
