INTERFACE
SUBROUTINE INCLAG(P,PSHT,KNPT,KLEN1,KLEN2,KSTEP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN1
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN2
REAL(KIND=JPRB) ,INTENT(INOUT) :: P(KLEN1,KLEN2)
REAL(KIND=JPRB) ,INTENT(IN) :: PSHT
INTEGER(KIND=JPIM),INTENT(IN) :: KNPT
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
END SUBROUTINE INCLAG
END INTERFACE
