INTERFACE
SUBROUTINE INCLI2(YDGEOMETRY,YDPHY)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMPHY , ONLY : TPHY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TPHY) ,INTENT(INOUT):: YDPHY
END SUBROUTINE INCLI2
END INTERFACE
