INTERFACE
SUBROUTINE INCLI10(YDGEOMETRY,YDPHY1)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMPHY1 , ONLY : TPHY1
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TPHY1) ,INTENT(INOUT):: YDPHY1
END SUBROUTINE INCLI10
END INTERFACE
