INTERFACE
SUBROUTINE INFLATION_PERT(YDGEOMETRY,YDGFL,YDGFL5,YDSURF,YDSP,YDCFU,YDXFU,YDMODEL)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE TYPE_MODEL , ONLY : MODEL
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL) , INTENT(INOUT) :: YDGFL
TYPE(TGFL) , INTENT(INOUT) :: YDGFL5
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
TYPE(TCFU) , INTENT(INOUT) :: YDCFU
TYPE(TXFU) , INTENT(INOUT) :: YDXFU
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
END SUBROUTINE INFLATION_PERT
END INTERFACE
