INTERFACE
SUBROUTINE INI_SPP(YDGEOMETRY,YDRIP,YDCONF,YDSPP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMRIP , ONLY : TRIP
USE SPP_MOD , ONLY : JPSPPLABLEN,TSPP_CONFIG, TSPP_DATA, KGET_SEED_SPP
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(TRIP) , INTENT(INOUT) :: YDRIP
TYPE(TSPP_CONFIG) , INTENT(IN) :: YDCONF
TYPE(TSPP_DATA) , INTENT(INOUT) :: YDSPP
END SUBROUTINE INI_SPP
END INTERFACE
