INTERFACE
SUBROUTINE INIFAOUTINFO(YDRIP,YDXFU,CDCONF,CDINC,CDFIC,KDATEF)
USE YOMXFU , ONLY : TXFU, JPFUXT
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
TYPE(TRIP) ,INTENT(IN) :: YDRIP
TYPE(TXFU) ,INTENT(IN) :: YDXFU
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
CHARACTER(LEN=*), INTENT(OUT), OPTIONAL :: CDINC
CHARACTER(LEN=*), INTENT(OUT), OPTIONAL :: CDFIC
INTEGER(KIND=JPIM),INTENT(OUT), OPTIONAL :: KDATEF (:)
END SUBROUTINE INIFAOUTINFO
END INTERFACE
