INTERFACE
SUBROUTINE INIPGO(YDDIMV,YDMDDH,KBLOCKS,KNBARP)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMMDDH , ONLY : TMDDH
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
TYPE(TMDDH) , INTENT(INOUT):: YDMDDH
INTEGER(KIND=JPIM), INTENT(IN) :: KBLOCKS
INTEGER(KIND=JPIM), INTENT(IN) :: KNBARP
END SUBROUTINE INIPGO
END INTERFACE
