INTERFACE
SUBROUTINE INIRP(YDLAP,YDELAP,YDDIM)
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
USE YOMDIM , ONLY : TDIM
TYPE(TLAP) , INTENT(IN) :: YDLAP
TYPE(TLEP) , INTENT(IN) :: YDELAP
TYPE(TDIM) , INTENT(IN) :: YDDIM
END SUBROUTINE INIRP
END INTERFACE
