INTERFACE
SUBROUTINE INITAPLPAR&
 & (YGFL,YDARPHY,KIDIA , KFDIA , KLON , KLEV , KSGST , KCSS ,&
 & PVEG0 ,&
 & PDIFCQ , PDIFCQN, PDIFCQL, PDIFCS , PDIFSV , PDIFTQ , PDIFTQN, PDIFTQL,&
 & PDIFTS , PFCCQL , PFCCQN , PFCSQL , PFCSQN , PFCQNG , PFCQING,&
 & PFCQLNG, PFCQRNG, PFCQSNG, PFCQGNG,&
 & PFPLCL , PFPLCN , PFPLCG , PFPLCH , PFPLSL , PFPLSN , PFPLSG ,&
 & PFPLSH , PFRSO , PFRSOC ,&
 & PFRTH , PFRTHC , PSTRCU , PSTRCV , PSTRDU , PSTRDV , PSTRTU ,&
 & PSTRTV , PSTRMU , PSTRMV , PFRMH , PFRMQ ,&
 & PDIFCQLC,PDIFCQIC,PFIMCC,&
 & PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC, PFCNEGQLC,PFCNEGQIC,PFCNEGQRC,PFCNEGQSC,&
 & PFHPCG , PFHPSG , PFHSSG , PFCHOZ , PCPS , PLHS ,&
 & PRS , PLH , PLSCPE , PNEB , PQICE , PQLI , PQSAT ,&
 & PQW , PRH , PTW , PALB , PCD , PCDN , PCH ,&
 & PC1 , PC2 , PCT , PEMIS , PFCHSP , PFCLL , PFCLN ,&
 & PFCS , PFEVI , PFEVL , PFEVN , PFEVV , PFLASH , PFTR , PFLWSP ,&
 & PFONTE , PFGEL , PFGELS ,&
 & PFRSGNI, PFRSDNI, PFRSODS, PFRSOPS, PFRSOPT, PFRSOLU, PFRTHDS,&
 & PFPFPSL, PFPFPSN, PFPFPSG, PFPFPCL, PFPFPCN, PFPEVPSL,PFPEVPSN,PFPEVPSG,PFPEVPCL,&
 & PFPEVPCN,PFPEVPCG,PFTKE , PFTKEI , PFEFB1 , PFEFB2 , PFEFB3 ,PGZ0 , PGZ0H ,&
 & PNEIJ , PVEG , PQS , PQSATS , PRUISL , PRUISP , PRUISS ,&
 & PUCLS , PVCLS , PNUCLS , PNVCLS , PTCLS , PMRT ,&
 & PQCLS , PRHCLS , PCLCT , PCLCH , PCLCM , PCLCL , PCLCC ,&
 & PCAPE , PCTOP , KCLPH , PCLPH , PVEIN , PUGST , PVGST , PDIAGH ,PTDISS,&
 & PVISICLD, PVISIHYDRO, PMXCLWC, PSIC) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMARPHY ,ONLY : TARPHY
USE YOM_YGFL ,ONLY : TYPE_GFLD
TYPE(TARPHY) ,INTENT(INOUT) :: YDARPHY
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSGST
INTEGER(KIND=JPIM),INTENT(IN) :: KCSS
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PVEG0(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFSV(KLON,0:KLEV,1:YGFL%NGFL_EXT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCCQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCCQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCSQL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCSQN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQING(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQLNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQRNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQSNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCQGNG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSO(KLON,0:KLEV,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOC(KLON,0:1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTH(KLON,0:KLEV,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTHC(KLON,0:1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRCV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRDU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRDV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRTU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRTV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRMU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRMV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRMH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRMQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCHOZ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPFPSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPFPSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPFPSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPFPCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPFPCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPSL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPSN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPCL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPCN(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPEVPCG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFTKE(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFTKEI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEFB1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEFB2(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEFB3(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQLC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFCQIC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFIMCC (KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEDQLC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEDQIC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEDQRC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEDQSC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCNEGQLC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCNEGQIC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCNEGQRC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCNEGQSC(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPCG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHPSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFHSSG(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCPS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLHS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLSCPE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNEB(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQICE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQLI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSAT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PALB(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCD(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PC1(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PC2(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCHSP(KLON,KCSS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCLL(KLON,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCLN(KLON,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFCS(KLON,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEVI(KLON,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEVL(KLON,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEVN(KLON,KSGST+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFEVV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLASH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFTR(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLWSP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFONTE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFGEL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFGELS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSGNI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSDNI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSODS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOPS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOPT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOLU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTHDS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGZ0(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNEIJ(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVEG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSATS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRUISS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNUCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNVCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMRT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRHCLS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLCT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLCH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLCM(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLCL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLCC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCTOP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLPH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVEIN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUGST(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVGST(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIAGH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTDISS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVISICLD(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVISIHYDRO(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMXCLWC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSIC(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCLPH(KLON)
END SUBROUTINE INITAPLPAR
END INTERFACE
