INTERFACE
SUBROUTINE init_common(log_io, CDNAME)
USE PARKIND1 ,ONLY : JPIM ,JPRD
USE YOMSTDIN
USE YOMWT
USE YOMSIZEOF
USE YOMKEYS
USE YOMPARALLEL
USE YOMPER
USE YOMSEQNO
USE yomvirt
USE yomobsmap
USE MPL_MODULE
INTEGER(KIND=JPIM), intent(in) :: log_io
character*(*), intent(in) :: CDNAME
END SUBROUTINE init_common
END INTERFACE
