INTERFACE
SUBROUTINE INTERCHAN_OBSERR_COR(KOBS,KSATGRP,KLEN,KCHANS,KDSTATS,PDEPAR)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KOBS
INTEGER(KIND=JPIM),INTENT(IN) :: KSATGRP
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KCHANS(KLEN)
INTEGER(KIND=JPIM),INTENT(IN) :: KDSTATS(KLEN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDEPAR(KLEN)
END SUBROUTINE INTERCHAN_OBSERR_COR
END INTERFACE
