INTERFACE
SUBROUTINE INTER10 (KLAT,KLON,KLAT0,KLON0,KNCH,KPP,KNPT,&
 & KNCO,KNJQ,KNIQ,KNIP,KLEN,PZI,PZS,PZ0,PSLAC,PSLOC,PCLOC,&
 & PSEA0,PSEA1,PSEA2,PSEA3,PSPCM) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT0
INTEGER(KIND=JPIM),INTENT(IN) :: KLON0
INTEGER(KIND=JPIM),INTENT(IN) :: KNCH
INTEGER(KIND=JPIM),INTENT(IN) :: KNPT
INTEGER(KIND=JPIM),INTENT(IN) :: KNJQ
INTEGER(KIND=JPIM),INTENT(IN) :: KNIQ
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KPP
INTEGER(KIND=JPIM),INTENT(IN) :: KNCO
INTEGER(KIND=JPIM),INTENT(IN) :: KNIP(KLAT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZI(KLEN,KNCH)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZS(KLEN,KNCH)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0(KLON0,KLAT0,KNCH)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLAC(KNJQ)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLOC(KNIQ,KLAT)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLOC(KNIQ,KLAT)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEA0(KLON0,KLAT0)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEA1(KNPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEA2(KNPT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSEA3(KNPT)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPCM
END SUBROUTINE INTER10
END INTERFACE
