INTERFACE
SUBROUTINE INTER0(KLAT,KLON,KLAT0,KLON0,PSTRET,KPP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT0
INTEGER(KIND=JPIM),INTENT(IN) :: KLON0
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRET
INTEGER(KIND=JPIM),INTENT(OUT) :: KPP
END SUBROUTINE INTER0
END INTERFACE
