INTERFACE
SUBROUTINE INTERP_CUBIC1D(PDCOORD,PFIELD_IN,PFIELD_OUT)
 USE PARKIND1 , ONLY : JPIM, JPRB
 REAL(KIND=JPRB), INTENT(IN) :: PDCOORD(:)
 REAL(KIND=JPRB), INTENT(IN) :: PFIELD_IN(:)
 REAL(KIND=JPRB), INTENT(INOUT) :: PFIELD_OUT(:)
END SUBROUTINE INTERP_CUBIC1D
END INTERFACE
