INTERFACE
SUBROUTINE IO_SERV_CREATE_FA (YDFL, YDMODELPAR, LDOUV, KERR, YDFAGIOT_ARGS)
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMIO_SERV_FALFI, ONLY : IO_SERV_FALFI
USE YOMIO_SERV, ONLY : IO_SERV_MODELPAR,&
 & IO_SERV_FAFRAME,&
 & IO_SERV_FAGIOT_ARGS,&
 & NUNIT 
TYPE (IO_SERV_FALFI), INTENT (INOUT) :: YDFL
TYPE (IO_SERV_MODELPAR),INTENT (INOUT) :: YDMODELPAR
LOGICAL, INTENT (IN) :: LDOUV
INTEGER(KIND=JPIM), INTENT (OUT) :: KERR
TYPE (IO_SERV_FAGIOT_ARGS), OPTIONAL,&
 & INTENT (IN) :: YDFAGIOT_ARGS 
END SUBROUTINE IO_SERV_CREATE_FA
END INTERFACE
