INTERFACE
SUBROUTINE IO_SERV_WV_WGRIBENCODE (K1, K2, PFIELD,&
 & YDIOS, FLDDESC,&
 & KGRIB_HANDLE) 
 USE PARKIND_WAVE, ONLY : JWIM, JWRB
 USE YOMIO_SERV, ONLY : IO_SERV
 USE IOFLDDESC_MOD, ONLY : IOFLDDESC
 USE GRIB_API_INTERFACE
 INTEGER(KIND=JWIM), INTENT(IN) :: K1
 INTEGER(KIND=JWIM), INTENT(IN) :: K2
 INTEGER(KIND=JWIM), INTENT(INOUT) :: KGRIB_HANDLE
 REAL(KIND=JWRB), INTENT(INOUT) :: PFIELD(K1,K2)
 TYPE (IO_SERV), INTENT (IN) :: YDIOS
 TYPE (IOFLDDESC), INTENT (IN) :: FLDDESC
END SUBROUTINE IO_SERV_WV_WGRIBENCODE
END INTERFACE
