INTERFACE
SUBROUTINE IO_SERV_HDR2_INIT(YDIOS,KSIZEL,KSIZEG,LDSPEC,KTYPE,YDHDRS,YDHDRA)
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMIO_SERV, ONLY : IO_SERV
USE YOMIO_SERV_HDR, ONLY : IO_SERV_HDR2,&
 & NIO_SERV_HDR_IDOM_MDL,&
 & NIO_SERV_HDR_IDOM_FPA,&
 & NIO_SERV_HDR_IDOM_MDP,&
 & NIO_SERV_HDR_IDOM_WV 
TYPE (IO_SERV), INTENT (IN) :: YDIOS
INTEGER (KIND=JPIM), INTENT (IN) :: KSIZEL
INTEGER (KIND=JPIM), INTENT (IN) :: KSIZEG
LOGICAL, INTENT (IN) :: LDSPEC
INTEGER (KIND=JPIM), INTENT (IN) :: KTYPE
TYPE (IO_SERV_HDR2), INTENT (INOUT), OPTIONAL :: YDHDRS
TYPE (IO_SERV_HDR2), INTENT (INOUT), OPTIONAL :: YDHDRA (:)
END SUBROUTINE IO_SERV_HDR2_INIT
END INTERFACE
