INTERFACE
SUBROUTINE IO_SERV_MAP_RECV_PART1(YDIOS,KSIZEL,KSIZEG,YDFLDSC,PTSTEP,KTAG,YDIOSMPP,&
 & KDOM_TYPE,PIOPROC1,PIOPROC2,PTIME) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_RECV_PLAN
USE IOFLDDESC_MOD , ONLY : IOFLDDESC,&
 & NIOFLDDESC_SIZE,&
 & IOFLDDESC_FREEZE 
USE YOMIO_SERV , ONLY : IO_SERV
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
INTEGER (KIND=JPIM), INTENT (IN) :: KSIZEL
INTEGER (KIND=JPIM), INTENT (IN) :: KSIZEG
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC (:)
TYPE (IO_SERV_RECV_PLAN), INTENT (INOUT) :: YDIOSMPP
REAL (KIND=JPRB), INTENT (IN) :: PTSTEP
INTEGER (KIND=JPIM), INTENT (IN) :: KTAG
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KDOM_TYPE
REAL (KIND=JPRB), INTENT (IN), OPTIONAL :: PIOPROC1
REAL (KIND=JPRB), INTENT (IN), OPTIONAL :: PIOPROC2
REAL (KIND=JPRB), INTENT (IN), OPTIONAL :: PTIME
END SUBROUTINE IO_SERV_MAP_RECV_PART1
END INTERFACE
