INTERFACE
SUBROUTINE IO_SERV_WV_REC (YDIOS,FIELD,FLDDESC,KGRIB_HANDLE)
 USE PARKIND_WAVE, ONLY : JWIM, JWRB, JWRU
 USE YOMIO_SERV, ONLY : IO_SERV
 USE IOFLDDESC_MOD, ONLY : IOFLDDESC
 USE GRIB_API_INTERFACE
 USE GRIB_UTILS_MOD
 TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
 REAL(KIND=JWRB), INTENT (INOUT) :: FIELD (YDIOS%MODELPAR%YWAM%NGX,YDIOS%MODELPAR%YWAM%NGY)
 TYPE (IOFLDDESC), INTENT (IN) :: FLDDESC
 INTEGER(KIND=JWIM), INTENT (INOUT) :: KGRIB_HANDLE
END SUBROUTINE IO_SERV_WV_REC
END INTERFACE
