INTERFACE
SUBROUTINE IO_SERV_SEND_SORT (YDIOS, PBUF)
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMIO_SERV, ONLY : IO_SERV
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
REAL (KIND=JPRB), INTENT (IN) :: PBUF (:)
END SUBROUTINE IO_SERV_SEND_SORT
END INTERFACE
