INTERFACE
Subroutine IO_SERV_SUIOSCTMPL(YDIOS,YDGEOMETRY,PTSTEP,YDEWCOU,YDFPGEOMETRY,YDFPOPH)
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE PARKIND1, ONLY : JPIM, JPRB
USE TYPE_FAOPH, ONLY : TFAOPH
USE YOMFPGEOMETRY, ONLY : TFPGEOMETRY
USE YOMIO_SERV, ONLY : IO_SERV, IO_SERV_FAFRAME
USE GRIB_API_INTERFACE
USE YOEWCOU , ONLY : TEWCOU
TYPE (IO_SERV) , INTENT(INOUT) :: YDIOS
TYPE (GEOMETRY), INTENT(IN), OPTIONAL, TARGET :: YDGEOMETRY
REAL(KIND=JPRB), INTENT(IN), OPTIONAL :: PTSTEP
TYPE(TEWCOU), INTENT(INOUT), OPTIONAL :: YDEWCOU
TYPE (TFPGEOMETRY), INTENT(IN), OPTIONAL :: YDFPGEOMETRY
TYPE (TFAOPH), INTENT(IN), OPTIONAL :: YDFPOPH(:)
END SUBROUTINE IO_SERV_SUIOSCTMPL
END INTERFACE
