INTERFACE
SUBROUTINE IO_SERV_GROK_NPROC (KULNAM, KPROC)
USE PARKIND1, ONLY : JPRB, JPIM
INTEGER (KIND=JPIM), INTENT (IN) :: KULNAM
INTEGER (KIND=JPIM), INTENT (INOUT) :: KPROC
END SUBROUTINE IO_SERV_GROK_NPROC
END INTERFACE
