INTERFACE
SUBROUTINE IO_SERV_GET_REQ_READY (YDIOS, YDREQ, KSTEPMAX)
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMIO_SERV , ONLY : IO_SERV
USE YOMIO_SERV_REQ, ONLY : IO_SERV_REQ
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_REQ), POINTER :: YDREQ
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KSTEPMAX
END SUBROUTINE IO_SERV_GET_REQ_READY
END INTERFACE
