INTERFACE
SUBROUTINE IO_SERV_CCOMM (KRANK, KCOMMI, KCOMMO)
USE PARKIND1, ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT (IN) :: KRANK (:)
INTEGER(KIND=JPIM), INTENT (IN) :: KCOMMI
INTEGER(KIND=JPIM), INTENT (OUT) :: KCOMMO
END SUBROUTINE IO_SERV_CCOMM
END INTERFACE
