INTERFACE
SUBROUTINE IO_SERV_CLOSE_EC (YDIOS, YDREQ)
USE YOMIO_SERV, ONLY : IO_SERV
USE YOMIO_SERV_REQ, ONLY : IO_SERV_REQ
TYPE(IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_REQ), INTENT (INOUT) :: YDREQ
END SUBROUTINE IO_SERV_CLOSE_EC
END INTERFACE
