INTERFACE
SUBROUTINE IO_SERV_SEND_READ (YDIOS, YDFLC, YDHG, YDFLDSC, PBUFG)
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMIO_SERV, ONLY : IO_SERV,&
 & NUNIT 
USE YOMIO_SERV_FALFI, ONLY : IO_SERV_FALFI
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE YOMIO_SERV_HDR, ONLY : IO_SERV_HDRG
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_FALFI), INTENT (INOUT) :: YDFLC (:)
TYPE (IO_SERV_HDRG), INTENT (IN) :: YDHG
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC (:)
REAL (KIND=JPRB), INTENT (OUT) :: PBUFG (:,:)
END SUBROUTINE IO_SERV_SEND_READ
END INTERFACE
