INTERFACE
SUBROUTINE IO_SERV_MAP_SEND_PART2 (YDIOS, YDIOSMPP)
USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_SEND_PLAN
USE YOMIO_SERV, ONLY : IO_SERV
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_SEND_PLAN), INTENT (INOUT) :: YDIOSMPP
END SUBROUTINE IO_SERV_MAP_SEND_PART2
END INTERFACE
