INTERFACE
SUBROUTINE IO_SERV_INC (YDIOS, YDH1, CDINC)
USE YOMIO_SERV , ONLY : IO_SERV
USE YOMIO_SERV_HDR, ONLY : IO_SERV_HDR1
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_HDR1), INTENT (IN) :: YDH1
CHARACTER (LEN=*), INTENT (OUT) :: CDINC
END SUBROUTINE IO_SERV_INC
END INTERFACE
