INTERFACE
SUBROUTINE IO_SERV_SETUP_FA (YDIOS, YDFLC, YDFLW)
USE YOMIO_SERV, ONLY : IO_SERV
USE YOMIO_SERV_FALFI, ONLY : IO_SERV_FALFI
TYPE(IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_FALFI), POINTER :: YDFLC (:)
TYPE (IO_SERV_FALFI), INTENT (INOUT) :: YDFLW
END SUBROUTINE IO_SERV_SETUP_FA
END INTERFACE
