INTERFACE
SUBROUTINE IO_SERV_WRGP2FA_COMPRESS (YDIOS, YDH1, YDFA, YDFLDSC, PGPG, YDCPDSC, PCPT)
USE PARKIND1, ONLY : JPIM, JPRB
USE FA_MOD, ONLY : FA_COM, JPPRCM
USE YOMIO_SERV, ONLY : IO_SERV, NUNIT
USE YOMIO_SERV_HDR, ONLY : IO_SERV_HDR1
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOCPTDESC_MOD, ONLY : IOCPTDESC
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_HDR1), INTENT (IN) :: YDH1
TYPE (FA_COM), INTENT (INOUT) :: YDFA
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC
REAL (KIND=JPRB), INTENT (INOUT) :: PGPG (:)
TYPE (IOCPTDESC), INTENT (INOUT) :: YDCPDSC
REAL (KIND=JPRB), INTENT (INOUT) :: PCPT (:)
END SUBROUTINE IO_SERV_WRGP2FA_COMPRESS
END INTERFACE
