INTERFACE
SUBROUTINE IO_SERV_COMPRESS (YDIOS, YDFL, YDREQ)
USE YOMIO_SERV, ONLY : IO_SERV
USE YOMIO_SERV_REQ, ONLY : IO_SERV_REQ
USE YOMIO_SERV_FALFI, ONLY : IO_SERV_FALFI
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_FALFI), INTENT (INOUT) :: YDFL (:)
TYPE (IO_SERV_REQ), TARGET, INTENT (INOUT) :: YDREQ
END SUBROUTINE IO_SERV_COMPRESS
END INTERFACE
