INTERFACE
SUBROUTINE IO_SERV_SYNC(YDIOS,KTYPE,CDNAME,LDSTOP,PTSTEP)
USE PARKIND1, ONLY : JPIM, JPRB, JPRD
USE YOMIO_SERV, ONLY : IO_SERV,&
 & NIO_SERV_PROCESS_RECV 
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
INTEGER (KIND=JPIM), INTENT (IN) :: KTYPE
CHARACTER (LEN=*), INTENT (IN) :: CDNAME
LOGICAL, OPTIONAL, INTENT (IN) :: LDSTOP
REAL (KIND=JPRB), INTENT (IN), OPTIONAL :: PTSTEP
END SUBROUTINE IO_SERV_SYNC
END INTERFACE
