INTERFACE
SUBROUTINE IO_SERV_WRITE (YDIOS, YDREQ, YDFLC, YDFLW)
USE YOMIO_SERV, ONLY : IO_SERV,&
 & NIO_SERV_PROCESS_COMP,&
 & NIO_SERV_PROCESS_WRIT,&
 & NUNIT 
USE YOMIO_SERV_REQ, ONLY : IO_SERV_REQ
USE YOMIO_SERV_FALFI, ONLY : IO_SERV_FALFI
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IO_SERV_REQ), INTENT (INOUT) :: YDREQ
TYPE (IO_SERV_FALFI), INTENT (INOUT) :: YDFLC (:)
TYPE (IO_SERV_FALFI), INTENT (INOUT) :: YDFLW
END SUBROUTINE IO_SERV_WRITE
END INTERFACE
