INTERFACE
SUBROUTINE IO_SERV_MAKE_CHUNKS (KNVG_B, KNVG_A, KVAL_B, KNVL_B, P1VG_B, P2VG_B)
USE PARKIND1, ONLY : JPIM, JPRB
INTEGER (KIND=JPIM), INTENT (IN) :: KNVG_B
INTEGER (KIND=JPIM), INTENT (IN) :: KNVG_A
INTEGER (KIND=JPIM), POINTER :: KVAL_B (:)
INTEGER (KIND=JPIM), POINTER :: KNVL_B (:)
REAL (KIND=JPRB), INTENT (IN), OPTIONAL :: P1VG_B
REAL (KIND=JPRB), INTENT (IN), OPTIONAL :: P2VG_B
END SUBROUTINE IO_SERV_MAKE_CHUNKS
END INTERFACE
