INTERFACE
SUBROUTINE IO_SERV_WRITEFLD_EC (YDIOS,YDFLDSC,KGRIB_HANDLE,KSTEP, PFLD)
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMIO_SERV, ONLY : IO_SERV
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE GRIB_UTILS_MOD
USE GRIB_API_INTERFACE
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC
INTEGER (KIND=JPIM), INTENT (INOUT) :: KGRIB_HANDLE
INTEGER (KIND=JPIM), INTENT (IN) :: KSTEP
REAL (KIND=JPRB), INTENT (IN) :: PFLD (:)
END SUBROUTINE IO_SERV_WRITEFLD_EC
END INTERFACE
