INTERFACE
SUBROUTINE ISAC_GRGTL(KFLEVG,KPPM,KDLEN,KLEN,KDCOUNT,KGRIBC,KCOUNT,&
 & PRESO,PRESH,PRESF,PXP,PXPD,YDGP_TL,&
 & KDPP,PXGEMS,&
 & PRESH5,PRESF5,PXP5,PXPD5,YDGP5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIBC
INTEGER(KIND=JPIM),INTENT(IN) :: KCOUNT(KDLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESO(KDLEN,KDCOUNT)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KDLEN,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PXP(KDLEN,0:KFLEVG,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXPD(KDLEN,0:KFLEVG,KPPM)
INTEGER(KIND=JPIM),INTENT(IN) :: KDPP
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXGEMS(KDLEN,KDCOUNT,KDPP)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH5(KDLEN,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5(KDLEN,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PXP5(KDLEN,0:KFLEVG,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXPD5(KDLEN,0:KFLEVG,KPPM)
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP_TL
END SUBROUTINE ISAC_GRGTL
END INTERFACE
