INTERFACE
SUBROUTINE JACOBIAN_PEAK(&
 & K__SENSOR,&
 & K__NCHANS,&
 & K__CHANID,&
 & K__LEVELS,&
 & P__TAU,&
 & P__PRESF,&
 & P__PEAKP,&
 & K__PEAKL) 
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K__NCHANS
INTEGER(KIND=JPIM),INTENT(IN) :: K__SENSOR
INTEGER(KIND=JPIM),INTENT(IN) :: K__CHANID(K__NCHANS)
INTEGER(KIND=JPIM),INTENT(IN) :: K__LEVELS
REAL(KIND=JPRB) ,INTENT(IN) :: P__TAU(K__NCHANS,K__LEVELS)
REAL(KIND=JPRB) ,INTENT(IN) :: P__PRESF(K__LEVELS)
REAL(KIND=JPRB) ,INTENT(OUT) :: P__PEAKP(K__NCHANS,2)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: K__PEAKL(K__NCHANS,2)
END SUBROUTINE JACOBIAN_PEAK
END INTERFACE
