INTERFACE
SUBROUTINE JB_WAV_VAR(YDGEOMETRY,CDCONF,KSCALE,KNUMB,PLON,PLAT,&
 & PGP3T1,PGP2T1,YD_JB_STRUCT) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCVA , ONLY : CVA_DATA
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KSCALE
INTEGER(KIND=JPIM),INTENT(IN) :: KNUMB
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGP3T1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,CVA_DATA%NVA3D)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGP2T1(YDGEOMETRY%YRDIM%NPROMA,CVA_DATA%NVA2D)
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE jb_wav_var
END INTERFACE
