INTERFACE
SUBROUTINE JBMATINTERP (PLON0G,KLON_OFFSET,PDLONE,&
 & PLATG,KLAT_OFFSET,KLATG,KLATE,KLONE,&
 & PLONM,PLATM,KNPTS,KNDIM1,KINDEX) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLATG
INTEGER(KIND=JPIM),INTENT(IN) :: KLATE
INTEGER(KIND=JPIM),INTENT(IN) :: KNPTS
INTEGER(KIND=JPIM),INTENT(IN) :: KNDIM1
REAL(KIND=JPRB) ,INTENT(IN) :: PLON0G(KLATG)
INTEGER(KIND=JPIM),INTENT(IN) :: KLON_OFFSET(KLATE)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLONE(KLATE)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATG(KLATG)
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT_OFFSET
INTEGER(KIND=JPIM),INTENT(IN) :: KLONE(KLATE)
REAL(KIND=JPRB) ,INTENT(IN) :: PLONM(KNPTS)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATM(KNPTS)
INTEGER(KIND=JPIM),INTENT(OUT) :: KINDEX(KNPTS)
END SUBROUTINE JBMATINTERP
END INTERFACE
