INTERFACE
SUBROUTINE JBTOMODEL(YDGEOMETRY,SPEC_FC,GRID_FC,PGFL5,YDSPJB,PGP3,PGP2,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPRB, JPIM
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE FIELD_CONTAINER_GP_MOD, ONLY : FIELD_CONTAINER_GP
USE FIELD_CONTAINER_SP_MOD, ONLY : FIELD_CONTAINER_SP
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELD_CONTAINER_SP),INTENT(INOUT) :: SPEC_FC
TYPE(FIELD_CONTAINER_GP),INTENT(INOUT) :: GRID_FC
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL5(:,:,:,:)
TYPE(SPECTRAL_FIELD) ,INTENT(IN) :: YDSPJB
REAL(KIND=JPRB) ,INTENT(IN) :: PGP3(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2(:,:,:)
TYPE(TYPE_JB_STRUCT) ,INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE JBTOMODEL
END INTERFACE
