INTERFACE
SUBROUTINE JBTOMODELAD(YDGEOMETRY,SPEC_FC,GRID_FC,PGFL5,YDSPJB,PGP3,PGP2,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPRB, JPIM
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE SPECTRAL_FIELDS_MOD
USE FIELD_CONTAINER_GP_MOD, ONLY : FIELD_CONTAINER_GP
USE FIELD_CONTAINER_SP_MOD, ONLY : FIELD_CONTAINER_SP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELD_CONTAINER_SP),INTENT(INOUT) :: SPEC_FC
TYPE(FIELD_CONTAINER_GP),INTENT(INOUT) :: GRID_FC
REAL(KIND=JPRB) ,INTENT(IN ) :: PGFL5(:,:,:,:)
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPJB
REAL(KIND=JPRB) ,INTENT(OUT) :: PGP3(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2(:,:,:)
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE JBTOMODELAD
END INTERFACE
