INTERFACE
SUBROUTINE JBVCORG(YDGEOMETRY,CDCONF,KSCALE,KNUMB,PLON,PLAT,&
 & PGP3T0,PGP2T0,PGP3T1,PGP2T1,YD_JB_STRUCT) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSCALE
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNUMB
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(YDGEOMETRY%YRDIM%NPROMA)
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
REAL(KIND=JPRB) ,INTENT(IN) :: PGP3T0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YD_JB_STRUCT%CONFIG%SPVARS%NS3D)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2T0(YDGEOMETRY%YRDIM%NPROMA,YD_JB_STRUCT%CONFIG%SPVARS%NS2D)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGP3T1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YD_JB_STRUCT%CONFIG%SPVARS%NS3D)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGP2T1(YDGEOMETRY%YRDIM%NPROMA,YD_JB_STRUCT%CONFIG%SPVARS%NS2D)
END SUBROUTINE JBVCORG
END INTERFACE
