INTERFACE
SUBROUTINE JGNRI(YDGEOMETRY,KNUMB,KSTGLO,PGP3JB,PGP2JB,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNUMB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP3JB(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YD_JB_STRUCT%CONFIG%SPVARS%NS3D)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2JB(YDGEOMETRY%YRDIM%NPROMA,YD_JB_STRUCT%CONFIG%SPVARS%NS2D)
END SUBROUTINE JGNRI
END INTERFACE
