INTERFACE
SUBROUTINE JGVCOR(YDGEOMETRY,PSP3DG,PSP2DG,KSPSTA,KSPEND,LDIR,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP3DG(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP2DG(:,:)
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSPSTA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSPEND
LOGICAL ,INTENT(IN) :: LDIR
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE JGVCOR
END INTERFACE
