INTERFACE
SUBROUTINE JMGFIXER(YDGEOMETRY,YDGMV,YDDPHY,YGFL,YDDYN,YDPTRSLB1,KL0,PB1,YDSL,PGMVS,PGMVT1S,PGFL,PGFLT1,PEXTRADYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMDYN , ONLY : TDYN
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
USE PTRSLB1 , ONLY : TPTRSLB1
USE YOMDPHY , ONLY : TDPHY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TDPHY) ,INTENT(INOUT) :: YDDPHY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE(TPTRSLB1) ,INTENT(INOUT) :: YDPTRSLB1
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,0:3,YDGEOMETRY%YRDIM%NGPBLKS)
TYPE(SL_STRUCT) ,INTENT(IN) :: YDSL
REAL(KIND=JPRB) ,INTENT(IN) :: PB1(YDSL%NASLB1,YDPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM,&
 & YDGEOMETRY%YRDIM%NGPBLKS) 
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1,&
 & YDGEOMETRY%YRDIM%NGPBLKS) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PEXTRADYN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDDPHY%NVEXTRDYN,&
 & YDGEOMETRY%YRDIM%NGPBLKS) 
END SUBROUTINE JMGFIXER
END INTERFACE
