INTERFACE
SUBROUTINE JQVCOR(YDGEOMETRY,YDSPEC, YDVCOR)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJQ , ONLY : ERRMODVCOR_STRUCT, NVALERR
USE SPECTRAL_COLUMNS_MIX
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSPEC
TYPE(ERRMODVCOR_STRUCT),INTENT(IN) :: YDVCOR
END SUBROUTINE JQVCOR
END INTERFACE
