INTERFACE
 SUBROUTINE KERNEL_PBP(KIS,PPSL,PBETAL,PXPL,PBP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE RT6SVALUES, ONLY: KNT, KNANG, KMU, ZEPS
INTEGER(KIND=JPIM), INTENT(IN) :: KIS
REAL(KIND=JPRB), INTENT(IN) :: PBETAL(0:KNT,0:KNANG)
REAL(KIND=JPRB), INTENT(IN) :: PPSL(0:KNANG,-1:KNANG,-KMU:KMU)
REAL(KIND=JPRB), INTENT(OUT) :: PXPL(-KMU:KMU)
REAL(KIND=JPRB), INTENT(OUT) :: PBP(0:KNT,0:KMU,-KMU:KMU)
END SUBROUTINE KERNEL_PBP
END INTERFACE
