INTERFACE
SUBROUTINE LACDYNSHW(YDGEM,YDDYN,CDCONF,KPROMA,KSTART,KPROF,PDT,&
 & PUT9,PVT9,PSPT9,PDIVT9,PSPT9L,PSPT9M,&
 & PUT0,PVT0,PSPT0,PDIVT0,PSPT0L,PSPT0M,&
 & YDGSGEOM,POROG,POROGL,POROGM,&
 & PSPNLT9,&
 & PUL9,PVL9,PSPL9,PUL0,PVL0,PSPL0,PUT1,PVT1,PSPT1,&
 & PURL0,PVRL0,PUSI,PVSI,PURL,PVRL) 
USE YOMGEM , ONLY : TGEM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMGSGEOM, ONLY : TGSGEOM
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
CHARACTER(LEN=1) , INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM), INTENT(IN) :: KSTART
INTEGER(KIND=JPIM), INTENT(IN) :: KPROF
REAL(KIND=JPRB) , INTENT(IN) :: PDT
REAL(KIND=JPRB) , INTENT(IN) :: PUT9(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVT9(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPT9(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PDIVT9(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPT9L(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPT9M(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PUT0(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PVT0(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPT0(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PDIVT0(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPT0L(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PSPT0M(KPROMA)
TYPE(TGSGEOM) , INTENT(IN) :: YDGSGEOM
REAL(KIND=JPRB) , INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PSPNLT9(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PUL9(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PVL9(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PSPL9(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PUL0(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PVL0(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PSPL0(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PUT1(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PVT1(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PSPT1(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PURL0(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PVRL0(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PUSI(KPROMA)
REAL(KIND=JPRB) , INTENT(INOUT) :: PVSI(KPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PURL(KPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVRL(KPROMA)
END SUBROUTINE LACDYNSHW
END INTERFACE
