INTERFACE
SUBROUTINE LACDYNSHWAD(YDGEM,YDDYN,CDCONF,KPROMA,KSTART,KPROF,PDT,&
 & PUT9,PVT9,&
 & PUT0,PVT0,PSPT0,PDIVT0,PSPT0L,PSPT0M,&
 & PSPT5,PDIVT5,&
 & YDGSGEOM,POROG,POROGL,POROGM,&
 & PSPNLT9,&
 & PUL9,PVL9,PSPL9,PUL0,PVL0,PSPL0,PSPT1,&
 & PURL0,PVRL0,PUSI,PVSI,PURL,PVRL) 
USE YOMGEM , ONLY : TGEM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMGSGEOM, ONLY : TGSGEOM
TYPE(TGEM) ,INTENT(IN) :: YDGEM
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIVT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT0L(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT0M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT5(KPROMA)
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
REAL(KIND=JPRB) , INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPNLT9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPL9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PURL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVRL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PURL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL(KPROMA)
END SUBROUTINE LACDYNSHWAD
END INTERFACE
