INTERFACE
SUBROUTINE LACDYNSHWTL(YDGEM,YDDYN,CDCONF,KPROMA,KSTART,KPROF,PDT,&
 & PUT9,PVT9,PSPT9L,PSPT9M,&
 & PUT0,PVT0,PSPT0,PDIVT0,PSPT0L,PSPT0M,&
 & PUT5,PVT5,PSPT5,PDIVT5,PSPT5L,PSPT5M,&
 & YDGSGEOM,POROG,POROGL,POROGM,&
 & PSPNLT9,PUT95,PVT95,PSPNLT95,&
 & PUL9,PVL9,PSPL9,PUL0,PVL0,PSPL0,PSPT1,&
 & PURL0,PVRL0,PUSI,PVSI,PURL,PVRL,&
 & PUL95,PVL95,PSPL95,PUL05,PVL05,PSPL05,&
 & PUT15,PVT15,PURL05,PVRL05,PUSI5,PVSI5,PURL5,PVRL5) 
USE YOMGEM , ONLY : TGEM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMGSGEOM, ONLY : TGSGEOM
TYPE(TGEM) ,INTENT(IN) :: YDGEM
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PUT9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT9L(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT9M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0L(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0M(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIVT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT5L(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT5M(KPROMA)
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROGM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPNLT9(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT95(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT95(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPNLT95(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUL9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVL9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPL9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PURL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVRL0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PURL(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVRL(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUL95(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVL95(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPL95(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUL05(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVL05(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPL05(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT15(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT15(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PURL05(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVRL05(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUSI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVSI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PURL5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVRL5(KPROMA)
END SUBROUTINE LACDYNSHWTL
END INTERFACE
