INTERFACE
SUBROUTINE LADINETL(YDGEOMETRY,YDRIP,YDDYN,KSTART,KPROF,YDSL,KPROMA,KFLDN,KFLDX,&
 & KIBL,&
 & PURL0,PVRL0,PURL,PVRL,&
 & PUL0,PVL0,PCL0,PUL9,PVL9,PCL9,&
 & PURL05,PVRL05,PURL5,PVRL5,&
 & PUL05,PVL05,PCL05,PUL95,PVL95,PCL95,&
 & PUSI,PVSI,PUSI5,PVSI5,PUT1,PVT1,PSPT1,PUT15,PVT15 ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMRIP , ONLY : TRIP
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KIBL
REAL(KIND=JPRB) ,INTENT(IN) :: PURL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PURL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL9(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL9(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL9(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PURL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PURL5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL95(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL95(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL95(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PUSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUSI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUT15(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT15(KPROMA)
END SUBROUTINE LADINETL
END INTERFACE
