INTERFACE
SUBROUTINE LAIDDI_RAD(KPROMA,KFIELDS,PCLA,PDLO,PCLO,KL0,PRE,POST)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
REAL(KIND=JPRB) ,INTENT(IN) :: PCLA(3)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO(0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLO(3,2)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(0:3,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE(KPROMA,KFIELDS)
REAL(KIND=JPRB) ,INTENT(OUT) :: POST(KFIELDS)
END SUBROUTINE LAIDDI_RAD
END INTERFACE
