INTERFACE
SUBROUTINE LAIHVT(KPROMA,KPROMB,KST,KPROF,KFLEV,&
 & KFLDN,KFLDX,KQM,&
 & PDLAT,PCLA,PDLO,PCLO,KL0,PVDERW,PDZ,&
 & PXSL,PXF) 
USE PARKIND1 , ONLY : JPIM ,JPRB ,JPIA
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KQM
REAL(KIND=JPRB) ,INTENT(IN) :: PDLAT(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLA(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLO(KPROMB,KFLEV,3,2)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDERW(KPROMB,KFLEV,2,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PDZ(KPROMB,KFLEV,4)
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL(KPROMA*(KFLDX-KFLDN+1))
REAL(KIND=JPRB) ,INTENT(OUT) :: PXF(KPROMB,KFLEV)
END SUBROUTINE LAIHVT
END INTERFACE
