INTERFACE
SUBROUTINE LAINOR2TL(YDHSLMER,YDDYN,YDSL,KPROMA,KSTART,KPROF,KFLDN,KFLDX,&
 & KSTABUF,&
 & KVLAG,KWLAG,LDPLANE,&
 & LDQMHW,LDQMHP,&
 & PUL9,PVL9,PCL9,PUL0,PVL0,PCL0,&
 & PUL95,PVL95,PCL95,PUL05,PVL05,PCL05,&
 & YDGSGEOM,YDCSGEOM,&
 & KSTTYP,PDSTRET,PC2M1,PC2P1,P4JP,PI,PDEPI,PIS2,&
 & PLOCEN,PMUCEN,PLSDEPI,PLATI,&
 & PCOSCO,PSINCO,PSINLA,PCOPHI,&
 & PCOSCO5,PSINCO5,PSINLA5,PCOPHI5,&
 & PLON,PLAT,&
 & PO,PQ,&
 & PU9,PV9,PC9,&
 & PLON5,PLAT5,&
 & PO5,PQ5,&
 & PU95,PV95,PC95,&
 & PZUZ9,PZVZ9,PZUZ95,PZVZ95) 
USE YOMDYN , ONLY : TDYN
USE YOMHSLMER , ONLY : THSLMER
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMCSGEOM , ONLY : TCSGEOM
USE YOMGSGEOM , ONLY : TGSGEOM
TYPE(THSLMER) ,INTENT(IN) :: YDHSLMER
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTABUF(YDSL%NDGSAH:YDSL%NDGENH)
INTEGER(KIND=JPIM),INTENT(IN) :: KVLAG
INTEGER(KIND=JPIM),INTENT(IN) :: KWLAG
LOGICAL ,INTENT(IN) :: LDPLANE
LOGICAL ,INTENT(IN) :: LDQMHW
LOGICAL ,INTENT(IN) :: LDQMHP
REAL(KIND=JPRB) ,INTENT(IN) :: PUL9(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL9(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL9(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL95(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL95(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL95(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PUL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL05(YDSL%NASLB1,KFLDN:KFLDX)
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
TYPE(TCSGEOM) ,INTENT(IN) :: YDCSGEOM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PDSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PC2M1
REAL(KIND=JPRB) ,INTENT(IN) :: PC2P1
REAL(KIND=JPRB) ,INTENT(IN) :: P4JP
REAL(KIND=JPRB) ,INTENT(IN) :: PI
REAL(KIND=JPRB) ,INTENT(IN) :: PDEPI
REAL(KIND=JPRB) ,INTENT(IN) :: PIS2
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PLSDEPI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOSCO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINCO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINLA(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOSCO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINCO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINLA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOPHI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLON(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PO(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQ(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PU9(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PV9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PC9(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLON5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLAT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU95(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV95(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PC95(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZUZ9(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZVZ9(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZUZ95(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZVZ95(KPROMA)
END SUBROUTINE LAINOR2TL
END INTERFACE
