INTERFACE
SUBROUTINE LAITRE_GFL_AD(YDML_DYN,KASLB1,KPROMA,KSTART,KPROF,KFLEV,KFLDN,KFLDX,&
 & KFLD,KSEP,KMAPQ,KMAP,KMAPL,PSIGNQ,PSIGN,PSIGNL,KDEP,LDVECADIN,LDPLANE,&
 & CDINT,PWENOALPHA,LDMOM,LDADV5,KNOWENO,KL0,PLSCAW,PRSCAW,PLSCAW5,PRSCAW5,&
 & KINC,PZINC,KDIM,PXSL,PXSL5,POUT) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
INTEGER(KIND=JPIM),INTENT(IN) :: KASLB1
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
INTEGER(KIND=JPIM),INTENT(IN) :: KSEP
INTEGER(KIND=JPIM),INTENT(IN) :: KMAPQ(KPROMA,56,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGNQ(KPROMA,56,KFLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KMAP(KPROMA,32,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGN(KPROMA,32,KFLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KMAPL(KPROMA,8,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGNL(KPROMA,8,KFLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KDEP(KPROMA,KFLEV)
LOGICAL ,INTENT(IN) :: LDVECADIN
LOGICAL ,INTENT(IN) :: LDPLANE
LOGICAL ,INTENT(IN) :: LDMOM
LOGICAL ,INTENT(IN) :: LDADV5
CHARACTER(LEN=12) ,INTENT(IN) :: CDINT
REAL(KIND=JPRB) ,INTENT(IN) :: PWENOALPHA
INTEGER(KIND=JPIM),INTENT(IN) :: KNOWENO(KPROMA,KFLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMA,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLSCAW(KPROMA,KFLEV,YDML_DYN%YYTLSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRSCAW(KPROMA,KFLEV,YDML_DYN%YYTRSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCAW5(KPROMA,KFLEV,YDML_DYN%YYTLSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSCAW5(KPROMA,KFLEV,YDML_DYN%YYTRSCAW%NDIM)
INTEGER(KIND=JPIM),INTENT(OUT) :: KINC(KDIM*KFLEV+1,KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZINC(KDIM*KFLEV+1,KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXSL(KASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL5(KASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(INOUT) :: POUT(KPROMA,KFLEV)
END SUBROUTINE LAITRE_GFL_AD
END INTERFACE
