INTERFACE
SUBROUTINE LAITLIAD(KPROMA,KPROMB,KSTART,KPROF,KFLEV,&
 & KFLDN,KFLDX,KFLD,KSEP,KMAP,PSIGN,LDVECADIN,&
 & PDLAT,PDLO,KL0,PDVER,PDLAT5,PDLO5,PDVER5,&
 & KINC,PZINC,KDIM,PXSL,PXSL5,PXF) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
INTEGER(KIND=JPIM),INTENT(IN) :: KSEP
INTEGER(KIND=JPIM),INTENT(IN) :: KMAP(KPROMB,8,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGN(KPROMB,8,KFLEV)
LOGICAL ,INTENT(IN) :: LDVECADIN
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLAT(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLO(KPROMB,KFLEV,1:2)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMB,KFLEV,1:2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDVER(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLAT5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO5(KPROMB,KFLEV,1:2)
REAL(KIND=JPRB) ,INTENT(IN) :: PDVER5(KPROMB,KFLEV)
INTEGER(KIND=JPIM),INTENT(OUT) :: KINC(KDIM*KFLEV+1,KPROMB)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZINC(KDIM*KFLEV+1,KPROMB)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXSL(KPROMA*(KFLDX-KFLDN+1))
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL5(KPROMA*(KFLDX-KFLDN+1))
REAL(KIND=JPRB) ,INTENT(IN) :: PXF(KPROMB,KFLEV)
END SUBROUTINE LAITLIAD
END INTERFACE
