INTERFACE
SUBROUTINE LAITRE_GMV_TL(&
 & YDML_DYN,KASLB1,KPROMA,KSTART,KPROF,KFLEV,KFLDN,KFLDX,&
 & LDSLHD,LDVWENO,PWENOALPHA,LDMOM,LDADV5,KNOWENO,KL0,PLSCAW,PRSCAW,PLSCAW5,PRSCAW5,&
 & PXSL,PXSL5,&
 & POUT,POUT5) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
INTEGER(KIND=JPIM),INTENT(IN) :: KASLB1
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
LOGICAL ,INTENT(IN) :: LDSLHD
LOGICAL ,INTENT(IN) :: LDVWENO
REAL(KIND=JPRB) ,INTENT(IN) :: PWENOALPHA
LOGICAL ,INTENT(IN) :: LDMOM
LOGICAL ,INTENT(IN) :: LDADV5
INTEGER(KIND=JPIM),INTENT(IN) :: KNOWENO(KPROMA,KFLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMA,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCAW(KPROMA,KFLEV,YDML_DYN%YYTLSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSCAW(KPROMA,KFLEV,YDML_DYN%YYTRSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSCAW5(KPROMA,KFLEV,YDML_DYN%YYTLSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSCAW5(KPROMA,KFLEV,YDML_DYN%YYTRSCAW%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL(KASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL5(KASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT5(KPROMA,KFLEV)
END SUBROUTINE LAITRE_GMV_TL
END INTERFACE
