INTERFACE
SUBROUTINE LAITRITL(KPROMA,KPROMB,KSTART,KPROF,KFLEV,&
 & KFLDN,KFLDX,LDADV55,&
 & PDLAT,PCLA,PDLO,PCLO,PDLAT5,PCLA5,PDLO5,PCLO5,KL0,&
 & PVINTW,PVINTW5,&
 & PXSL,PXSL5,PXF,PXF5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
LOGICAL ,INTENT(IN) :: LDADV55
REAL(KIND=JPRB) ,INTENT(IN) :: PDLAT(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLA(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLO(KPROMB,KFLEV,3,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLAT5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLA5(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO5(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLO5(KPROMB,KFLEV,3,2)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PVINTW(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PVINTW5(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL(KPROMA*(KFLDX-KFLDN+1))
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL5(KPROMA*(KFLDX-KFLDN+1))
REAL(KIND=JPRB) ,INTENT(OUT) :: PXF(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXF5(KPROMB,KFLEV)
END SUBROUTINE LAITRITL
END INTERFACE
