INTERFACE
SUBROUTINE LAPINEA5(YDGEOMETRY,YDRIP,YDML_DYN,KST,KPROF,YDSL,LD_AD,&
 & KIBL,KSTAGE2,KSTAGE3,&
 & PB15,PB2,PCCO5,&
 & PUF5,PVF5,PZF5,PUF05,PVF05,PZF05,PWF05,PUS5,PVS5,PZS5,PWS5,&
 & KL0,KLH0,PLSCAW5,PRSCAW5,PSCO5,PLEV5,POUT5,KDEP,KNOWENO) 
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
LOGICAL ,INTENT(IN) :: LD_AD
INTEGER(KIND=JPIM),INTENT(IN) :: KIBL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTAGE2
INTEGER(KIND=JPIM),INTENT(IN) :: KSTAGE3
REAL(KIND=JPRB) ,INTENT(IN) :: PB15(YDSL%NASLB1,YDML_DYN%YRPTRSLB15%NFLDSLB15)
REAL(KIND=JPRB) ,INTENT(IN) :: PB2(YDGEOMETRY%YRDIM%NPROMA,YDML_DYN%YRPTRSLB2%NFLDSLB2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YYTCCO%NDIM,&
 & YDML_DYN%YRDYN%NITMP,KSTAGE3) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PUF5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP-1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVF5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP-1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZF5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP-1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUF05(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,KSTAGE2,&
 & YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PVF05(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,KSTAGE2,&
 & YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PZF05(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,KSTAGE2,&
 & YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PWF05(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,KSTAGE2,&
 & YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PUS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & KSTAGE3,YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PVS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & KSTAGE3,YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PZS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & KSTAGE3,YDML_DYN%YRDYN%NITMP) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PWS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & KSTAGE3,YDML_DYN%YRDYN%NITMP) 
INTEGER(KIND=JPIM),INTENT(OUT) :: KL0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,0:3,YDML_DYN%YRDYN%NITMP,&
 & KSTAGE3) 
INTEGER(KIND=JPIM),INTENT(OUT) :: KLH0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,0:3)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLSCAW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YYTLSCAW%NDIM,&
 & YDML_DYN%YRDYN%NITMP,KSTAGE3) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PRSCAW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YYTRSCAW%NDIM,&
 & YDML_DYN%YRDYN%NITMP,KSTAGE3) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PSCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YYTSCO%NDIM,&
 & YDML_DYN%YRDYN%NITMP,KSTAGE2) 
REAL(KIND=JPRB) ,INTENT(OUT) :: PLEV5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP,&
 & KSTAGE2) 
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDEP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP,&
 & KSTAGE3) 
INTEGER(KIND=JPIM),INTENT(OUT) :: KNOWENO(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_DYN%YRDYN%NITMP,&
 & KSTAGE3) 
END SUBROUTINE LAPINEA5
END INTERFACE
