INTERFACE
SUBROUTINE LAQMLIMITER(YDVETA,LDQM3DCONS,KPROMA,KPROMB,KST,KPROF,KFLEV,&
 & KFLDN,KFLDX,KL0,PXSL,PXF) 
USE YOMVERT , ONLY : TVETA
USE PARKIND1 , ONLY : JPIM ,JPRB ,JPIA
TYPE(TVETA) ,INTENT(IN) :: YDVETA
LOGICAL ,INTENT(IN) :: LDQM3DCONS
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PXSL(KPROMA*(KFLDX-KFLDN+1))
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXF(KPROMB,KFLEV)
END SUBROUTINE LAQMLIMITER
END INTERFACE
