INTERFACE
SUBROUTINE LARCHE2TL(KPROMA,KSTART,KPROF,&
 & KSTTYP,PDSTRET,PC2M1,PC2P1,PI,PDEPI,&
 & PLOCEN,PMUCEN,YDGSGEOM,YDCSGEOM,&
 & PCOSCO,PSINCO,PSINLA,PCOPHI,&
 & PCOSCO5,PSINCO5,PSINLA5,PCOPHI5,&
 & KROT,PLON,PLAT,PQX,PQY,&
 & PLON5,PLAT5,PQX5,PQY5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCSGEOM, ONLY : TCSGEOM
USE YOMGSGEOM, ONLY : TGSGEOM
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PDSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PC2M1
REAL(KIND=JPRB) ,INTENT(IN) :: PC2P1
REAL(KIND=JPRB) ,INTENT(IN) :: PI
REAL(KIND=JPRB) ,INTENT(IN) :: PDEPI
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
TYPE(TCSGEOM) ,INTENT(IN) :: YDCSGEOM
REAL(KIND=JPRB) ,INTENT(IN) :: PCOSCO(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINCO(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINLA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOSCO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINCO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINLA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOPHI5(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KROT
REAL(KIND=JPRB) ,INTENT(OUT) :: PLON(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQX(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQY(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLON5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLAT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQX5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQY5(KPROMA)
END SUBROUTINE LARCHE2TL
END INTERFACE
