INTERFACE
SUBROUTINE LARCHE25(KPROMA,KSTART,KPROF,&
 & KSTTYP,PDSTRET,PC2M1,PC2P1,PI,PDEPI,&
 & PLOCEN,PMUCEN,YDGSGEOM,YDCSGEOM,&
 & PCOSCO5,PSINCO5,PSINLA5,PCOPHI5,&
 & KROT,PLON5,PLAT5,PQX5,PQY5,&
 & PCOSLR5,PCOSLA5,PCOSL25,PXX5,PYY5,PZW5,PZA5,PDECO5,P1ST5,&
 & PFACT5,PZSINLA5,PZCOSLA5,PZSILON5,&
 & PZY5,PZX5,PDI5,PZZ5,PZP5,P1STT5,PRP5,PRQ5,PCA5,PSA5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCSGEOM , ONLY : TCSGEOM
USE YOMGSGEOM , ONLY : TGSGEOM
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PDSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PC2M1
REAL(KIND=JPRB) ,INTENT(IN) :: PC2P1
REAL(KIND=JPRB) ,INTENT(IN) :: PI
REAL(KIND=JPRB) ,INTENT(IN) :: PDEPI
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
TYPE(TCSGEOM) ,INTENT(IN) :: YDCSGEOM
REAL(KIND=JPRB) ,INTENT(IN) :: PCOSCO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINCO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINLA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOPHI5(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KROT
REAL(KIND=JPRB) ,INTENT(OUT) :: PLON5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLAT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQX5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQY5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLR5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOSLA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSL25(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXX5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PYY5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZW5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDECO5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: P1ST5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFACT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZSINLA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZCOSLA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZSILON5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZY5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZX5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZZ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: P1STT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRQ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSA5(KPROMA)
END SUBROUTINE LARCHE25
END INTERFACE
