INTERFACE
SUBROUTINE LARCHEAD(YDTCCO,YDTSCO,KPROMA,KSTART,KPROF,KFLEV,&
 & KSTTYP,PDSTRET,PC2M1,PC2P1,PI,PDEPI,&
 & PLOCEN,PMUCEN,YDGSGEOM,YDCSGEOM,&
 & PSCO,PSCO5,KROT,PCCO) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCSGEOM , ONLY : TCSGEOM
USE YOMGSGEOM , ONLY : TGSGEOM
USE INTDYNSL_MOD, ONLY : TSCO,TCCO
TYPE(TCCO) ,INTENT(IN) :: YDTCCO
TYPE(TSCO) ,INTENT(IN) :: YDTSCO
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PDSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PC2M1
REAL(KIND=JPRB) ,INTENT(IN) :: PC2P1
REAL(KIND=JPRB) ,INTENT(IN) :: PI
REAL(KIND=JPRB) ,INTENT(IN) :: PDEPI
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
TYPE(TCSGEOM) ,INTENT(IN) :: YDCSGEOM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSCO(KPROMA,KFLEV,YDTSCO%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PSCO5(KPROMA,KFLEV,YDTSCO%NDIM)
INTEGER(KIND=JPIM),INTENT(IN) :: KROT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCCO(KPROMA,KFLEV,YDTCCO%NDIM)
END SUBROUTINE LARCHEAD
END INTERFACE
