INTERFACE
SUBROUTINE LARMES2(YDGEOMETRY,YDDYN,YDSL,KPROMA,KSTART,KPROF,KFLDN,KFLDX,&
 & KULOUT,KSTABUF,&
 & KVLAG,KWLAG,&
 & KITER,PVMAX1,PVMAX2,LDPLANE,LDSETTLS,LDELTRA,&
 & PURL0,PVRL0,PURL,PVRL,&
 & KSTTYP,PDSTRET,PC2M1,PC2P1,P4JP,PI,PDEPI,PIS2,&
 & PDTSA,PDTS62,PDTS22,&
 & PLOCEN,PMUCEN,PLSDEPI,PLATI,&
 & KIBL,&
 & PLON,PLAT,&
 & PCOSCO,PSINCO,PSINLA,PCOPHI,&
 & PR,PS) 
USE YOMDYN , ONLY : TDYN
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
INTEGER(KIND=JPIM),INTENT(IN) :: KSTABUF(YDSL%NDGSAH:YDSL%NDGENH)
INTEGER(KIND=JPIM),INTENT(IN) :: KVLAG
INTEGER(KIND=JPIM),INTENT(IN) :: KWLAG
INTEGER(KIND=JPIM),INTENT(IN) :: KITER
REAL(KIND=JPRB) ,INTENT(IN) :: PVMAX1
REAL(KIND=JPRB) ,INTENT(IN) :: PVMAX2
LOGICAL ,INTENT(IN) :: LDPLANE
LOGICAL ,INTENT(IN) :: LDSETTLS
LOGICAL ,INTENT(IN) :: LDELTRA
REAL(KIND=JPRB) ,INTENT(IN) :: PURL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL0(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PURL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PDSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PC2M1
REAL(KIND=JPRB) ,INTENT(IN) :: PC2P1
REAL(KIND=JPRB) ,INTENT(IN) :: P4JP
REAL(KIND=JPRB) ,INTENT(IN) :: PI
REAL(KIND=JPRB) ,INTENT(IN) :: PDEPI
REAL(KIND=JPRB) ,INTENT(IN) :: PIS2
REAL(KIND=JPRB) ,INTENT(IN) :: PDTSA
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS62
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS22
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PLSDEPI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATI(YDSL%NDGSAH:YDSL%NDGENH)
INTEGER(KIND=JPIM),INTENT(IN) :: KIBL
REAL(KIND=JPRB) ,INTENT(OUT) :: PLON(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOSCO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINCO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINLA(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PS(KPROMA)
END SUBROUTINE LARMES2
END INTERFACE
