INTERFACE
SUBROUTINE LARMES25(YDGEOMETRY,YDDYN,YDSL,KPROMA,KSTART,KPROF,KFLDN,KFLDX,&
 & KSTABUF,&
 & KVLAG,KWLAG,&
 & KITER,LDPLANE,LDSETTLS,LDELTRA,&
 & PURL05,PVRL05,PURL5,PVRL5,&
 & KSTTYP,PDSTRET,PC2M1,PC2P1,P4JP,PI,PDEPI,PIS2,&
 & PDTSA,PDTS62,PDTS22,&
 & PLOCEN,PMUCEN,PLSDEPI,PLATI,&
 & KIBL,&
 & PCOSCO5,PSINCO5,PSINLA5,PCOPHI5,&
 & PR5,PS5,PUF5,PVF5) 
USE YOMDYN , ONLY : TDYN
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
INTEGER(KIND=JPIM),INTENT(IN) :: KITER
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTABUF(YDSL%NDGSAH:YDSL%NDGENH)
INTEGER(KIND=JPIM),INTENT(IN) :: KVLAG
INTEGER(KIND=JPIM),INTENT(IN) :: KWLAG
LOGICAL ,INTENT(IN) :: LDPLANE
LOGICAL ,INTENT(IN) :: LDSETTLS
LOGICAL ,INTENT(IN) :: LDELTRA
REAL(KIND=JPRB) ,INTENT(IN) :: PURL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL05(YDSL%NASLB1,KFLDN:KFLDX)
REAL(KIND=JPRB) ,INTENT(IN) :: PURL5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRL5(KPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PDSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PC2M1
REAL(KIND=JPRB) ,INTENT(IN) :: PC2P1
REAL(KIND=JPRB) ,INTENT(IN) :: P4JP
REAL(KIND=JPRB) ,INTENT(IN) :: PI
REAL(KIND=JPRB) ,INTENT(IN) :: PDEPI
REAL(KIND=JPRB) ,INTENT(IN) :: PIS2
REAL(KIND=JPRB) ,INTENT(IN) :: PDTSA
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS62
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS22
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PLSDEPI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATI(YDSL%NDGSAH:YDSL%NDGENH)
INTEGER(KIND=JPIM),INTENT(IN) :: KIBL
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOSCO5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINCO5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSINLA5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOPHI5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PS5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUF5(KPROMA,KITER)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVF5(KPROMA,KITER)
END SUBROUTINE LARMES25
END INTERFACE
