INTERFACE
SUBROUTINE LASCAW_CLO_AD(KFLEV,KPROM,KST,KPROF,LDT_SLHD,LDSLHDHEAT,PSLHDKMIN,&
 & PDLO,PKAPPA,PKAPPAT,&
 & PDLO5,PKAPPA5,PKAPPAT5,PCLO,PCLOSLD,PCLOSLT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KPROM
INTEGER(KIND=JPIM), INTENT(IN) :: KST
INTEGER(KIND=JPIM), INTENT(IN) :: KPROF
LOGICAL , INTENT(IN) :: LDT_SLHD(3)
LOGICAL , INTENT(IN) :: LDSLHDHEAT
REAL(KIND=JPRB) , INTENT(IN) :: PSLHDKMIN
REAL(KIND=JPRB) , INTENT(INOUT) :: PDLO(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(INOUT) :: PKAPPA(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(INOUT) :: PKAPPAT(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PDLO5(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PKAPPA5(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PKAPPAT5(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PCLO(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(IN) :: PCLOSLD(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(IN) :: PCLOSLT(KPROM,KFLEV,3)
END SUBROUTINE LASCAW_CLO_AD
END INTERFACE
