INTERFACE
SUBROUTINE LASCAW_CLA_AD(YDSL,KFLEV,KPROM,KST,KPROF,LDT_SLHD,LDSLHDHEAT,&
 & PSLHDKMIN,&
 & KILA,PWH,PDLAT,PKAPPA,PKAPPAT,PSLD,PSLDW,&
 & PWH5,PDLAT5,PKAPPA5,PKAPPAT5,&
 & PCLA,PCLASLD,PCLASLT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(SL_STRUCT), INTENT(IN) :: YDSL
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KPROM
INTEGER(KIND=JPIM), INTENT(IN) :: KST
INTEGER(KIND=JPIM), INTENT(IN) :: KPROF
LOGICAL , INTENT(IN) :: LDT_SLHD(3)
LOGICAL , INTENT(IN) :: LDSLHDHEAT
REAL(KIND=JPRB) , INTENT(IN) :: PSLHDKMIN
INTEGER(KIND=JPIM), INTENT(IN) :: KILA(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(OUT) :: PWH(KPROM,3,KFLEV)
REAL(KIND=JPRB) , INTENT(INOUT) :: PDLAT(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(INOUT) :: PKAPPA(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(INOUT) :: PKAPPAT(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PSLD(YDSL%NDGSAH:YDSL%NDGENH,3)
REAL(KIND=JPRB) , INTENT(IN) :: PSLDW(3,3,YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) , INTENT(IN) :: PWH5(KPROM,3,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PDLAT5(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PKAPPA5(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PKAPPAT5(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PCLA(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(IN) :: PCLASLD(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(IN) :: PCLASLT(KPROM,KFLEV,3)
END SUBROUTINE LASCAW_CLA_AD
END INTERFACE
