INTERFACE
SUBROUTINE LASCAW_CLOTURB(KFLEV,KPROM,KST,KPROF,PKHTURB,PCLO,PCLOSLD)
USE PARKIND1,ONLY: JPIA,JPIM,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KPROM
INTEGER(KIND=JPIM), INTENT(IN) :: KST
INTEGER(KIND=JPIM), INTENT(IN) :: KPROF
REAL(KIND=JPRB) , INTENT(IN) :: PKHTURB(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(INOUT) :: PCLO(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(INOUT) :: PCLOSLD(KPROM,KFLEV,3)
END SUBROUTINE LASCAW_CLOTURB
END INTERFACE
