INTERFACE
SUBROUTINE LASCAWAD(YDSL,KPROMB,KST,KPROF,KFLEV,&
 & KFLDN,KWIS,KHOR,KWENO,&
 & LDSLHD,LDSLHDQUAD,LDSLHD_OLD,LDSLHDHEAT,&
 & P4JP,PIS2,PLSDEPI,PLATI,&
 & PIPI,PSLD,PSLDW,PGAMMA_WENO,&
 & PLON,PLAT,PLEV,PKAPPA,PKAPPAT,&
 & PLON5,PLAT5,PLEV5,PKAPPA5,PKAPPAT5,PDVER5,&
 & PVETA,KVAUT,&
 & PVCUICO,PVSLD,PVSLDW,KRLEVX,PVRLEVX,&
 & PDLAT,PCLA,PCLASLD,PCLASLT,PDLO,PCLO,PCLOSLD,PCLOSLT,PCW,PDVER,PVINTW,PVINTWSLD,PVINTWSLT) 
USE PARKIND1 , ONLY : JPIM ,JPRB, JPRD
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(SL_STRUCT), INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KRLEVX
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDN
INTEGER(KIND=JPIM),INTENT(IN) :: KWIS
INTEGER(KIND=JPIM),INTENT(IN) :: KHOR
INTEGER(KIND=JPIM),INTENT(IN) :: KWENO
LOGICAL ,INTENT(IN) :: LDSLHD
LOGICAL ,INTENT(IN) :: LDSLHDQUAD
LOGICAL ,INTENT(IN) :: LDSLHD_OLD
LOGICAL ,INTENT(IN) :: LDSLHDHEAT
REAL(KIND=JPRB) ,INTENT(IN) :: P4JP
REAL(KIND=JPRB) ,INTENT(IN) :: PIS2
REAL(KIND=JPRB) ,INTENT(IN) :: PLSDEPI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRD) ,INTENT(IN) :: PIPI(YDSL%NDGSAH:YDSL%NDGENH,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLD(YDSL%NDGSAH:YDSL%NDGENH,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLDW(3,3,YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAMMA_WENO(KFLEV,3)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLON(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLAT(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLEV(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKAPPA(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKAPPAT(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLEV5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKAPPA5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKAPPAT5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDVER5(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVETA(0:KFLEV+1)
INTEGER(KIND=JPIM),INTENT(IN) :: KVAUT(0:KRLEVX)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCUICO(4,0:KFLEV-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSLD(3,0:KFLEV-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSLDW(3,3,0:KFLEV-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PVRLEVX
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLAT(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLA(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLASLD(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLASLT(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDLO(KPROMB,KFLEV,0:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLO(KPROMB,KFLEV,3,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLOSLD(KPROMB,KFLEV,3,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLOSLT(KPROMB,KFLEV,3,2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCW(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDVER(KPROMB,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVINTW(KPROMB,KFLEV,3*KWENO)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVINTWSLD(KPROMB,KFLEV,3)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVINTWSLT(KPROMB,KFLEV,3)
END SUBROUTINE LASCAWAD
END INTERFACE
