INTERFACE
SUBROUTINE LASCAW_CLO(KFLEV,KPROM,KST,KPROF,LDT,PSLHDKMIN,PDLO,PDLOMAD,PKAPPA,&
 & PCLO,PCLOMAD,PCLOSLD) 
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KPROM
INTEGER(KIND=JPIM), INTENT(IN) :: KST
INTEGER(KIND=JPIM), INTENT(IN) :: KPROF
LOGICAL , INTENT(IN) :: LDT(4)
REAL(KIND=JPRB) , INTENT(IN) :: PSLHDKMIN
REAL(KIND=JPRB) , INTENT(IN) :: PDLO(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PDLOMAD(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(IN) :: PKAPPA(KPROM,KFLEV)
REAL(KIND=JPRB) , INTENT(OUT) :: PCLO(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(OUT) :: PCLOMAD(KPROM,KFLEV,3)
REAL(KIND=JPRB) , INTENT(OUT) :: PCLOSLD(KPROM,KFLEV,3)
END SUBROUTINE LASCAW_CLO
END INTERFACE
