INTERFACE
SUBROUTINE LASURE(&
 & YDGEOMETRY,YDEPHY,YDDYN,YDEDYN,YDPHY,KSTART,KPROF,PBETADT,PDT,PMAPPA,PGM,&
 & PDTS2,PBT,LD2TLFF1,PBDT,PREDIV,PESGP,PESGM ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMPHY , ONLY : TPHY
USE YEMDYN , ONLY : TEDYN
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(TEDYN) ,INTENT(IN) :: YDEDYN
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(TPHY) ,INTENT(IN) :: YDPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PBETADT
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(IN) :: PMAPPA(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTS2
REAL(KIND=JPRB) ,INTENT(OUT) :: PBT
LOGICAL ,INTENT(OUT) :: LD2TLFF1
REAL(KIND=JPRB) ,INTENT(OUT) :: PBDT(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PREDIV(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PESGP
REAL(KIND=JPRB) ,INTENT(OUT) :: PESGM
END SUBROUTINE LASURE
END INTERFACE
