INTERFACE
SUBROUTINE LATTE_BBC(YDGEOMETRY,YDVARS,YDCPG_SL1,YDCPG_SL2, YDCPG_BNDS, YDCPG_OPTS,&
 & YDML_DYN,PDTS2,PESGP,PESGM,PDBBC,PRDPHI,PMIXNL,&
 & PGWS) 
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE FIELD_VARIABLES_MOD,ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD,ONLY : CPG_SL1_TYPE, CPG_SL2_TYPE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELD_VARIABLES) ,INTENT(INOUT) :: YDVARS
TYPE(CPG_SL1_TYPE) ,INTENT(INOUT) :: YDCPG_SL1
TYPE(CPG_SL2_TYPE) ,INTENT(INOUT) :: YDCPG_SL2
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
REAL(KIND=JPRB) ,INTENT(IN) :: PDTS2
REAL(KIND=JPRB) ,INTENT(IN) :: PESGP
REAL(KIND=JPRB) ,INTENT(IN) :: PESGM
REAL(KIND=JPRB) ,INTENT(IN) :: PDBBC(YDGEOMETRY%YRDIM%NPROMNH)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDPHI(YDGEOMETRY%YRDIM%NPROMNH,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PMIXNL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGWS(YDGEOMETRY%YRDIM%NPROMNH)
END SUBROUTINE LATTE_BBC
END INTERFACE
