INTERFACE
SUBROUTINE LAVABOTL(YDGEOMETRY,YGFL,YDML_DYN,KST,KPROF,LD2TLFF1,PB15,PB1)
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
LOGICAL ,INTENT(IN) :: LD2TLFF1
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB15(YDGEOMETRY%YRDIM%NPROMA,YDML_DYN%YRPTRSLB15%NFLDSLB15)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1(YDGEOMETRY%YRDIM%NPROMA,YDML_DYN%YRPTRSLB1%NFLDSLB1)
END SUBROUTINE LAVABOTL
END INTERFACE
