INTERFACE
SUBROUTINE LAVABO_EXPL_LAITVSPCQM_PART2 (YDGEOMETRY, YGFL, KST, KPROF, YDCPG_SL1)
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOM_YGFL , ONLY : TYPE_GFLD
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1
END SUBROUTINE
END INTERFACE
