INTERFACE
SUBROUTINE LCHECK4NHFIELDS(LDNHDYN,YDTFP,YD3,YD2)
USE YOM4FPOS , ONLY : TRQ3FP, TRQ2FP
USE YOMAFN , ONLY : ALL_FULLPOS_TYPES
LOGICAL, INTENT(INOUT) :: LDNHDYN
TYPE(ALL_FULLPOS_TYPES), INTENT(IN) :: YDTFP
TYPE(TRQ3FP), INTENT(IN), OPTIONAL :: YD3
TYPE(TRQ2FP), INTENT(IN), OPTIONAL :: YD2
END SUBROUTINE LCHECK4NHFIELDS
END INTERFACE
