INTERFACE
SUBROUTINE LCHTFLT(YDGEOMETRY,K3D,K2D,KGRB3,KGRB2,PGP3XX,PGP2XX,PGP3YY,PGP2YY,PGP3XY,PGP2XY,PGP3XM4,PGP2XM4,PGP3YM4,PGP2YM4,&
 & LDUSETRUNCS,PTRUNC3XX,PTRUNC2XX,PTRUNC3YY,PTRUNC2YY) 
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: K3D
INTEGER(KIND=JPIM),INTENT(IN) :: K2D
INTEGER(KIND=JPIM),INTENT(INOUT) :: KGRB3(:)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KGRB2(:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGP3XX(:,:,:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGP2XX(:,:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGP3YY(:,:,:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGP2YY(:,:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGP3XY(:,:,:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGP2XY(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP3XM4(:,:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP2XM4(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP3YM4(:,:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGP2YM4(:,:,:)
LOGICAL, INTENT(IN) :: LDUSETRUNCS
REAL(KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PTRUNC3XX(:,:),&
 & PTRUNC2XX(:),PTRUNC3YY(:,:), PTRUNC2YY(:) 
END SUBROUTINE LCHTFLT
END INTERFACE
