INTERFACE
SUBROUTINE LEGTRIV (PSIN,KCP,KDIM,PALP,KLON)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
REAL(KIND=JPRB) ,INTENT(IN) :: PSIN(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCP
REAL(KIND=JPRB) ,INTENT(OUT) :: PALP(KDIM,KLON)
END SUBROUTINE LEGTRIV
END INTERFACE
