INTERFACE
SUBROUTINE LEGTRI (PSIN,KCP,KDIM,PALP)
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
REAL(KIND=JPRD) ,INTENT(IN) :: PSIN
INTEGER(KIND=JPIM),INTENT(IN) :: KCP
REAL(KIND=JPRD) ,INTENT(OUT) :: PALP(KDIM)
END SUBROUTINE LEGTRI
END INTERFACE
