INTERFACE
SUBROUTINE LIGHTNING_LAYER(&
 & YDTHF, YDCST, YDCHEM,YDEPHY,YGFL,KDIM, PAUX, LLKEYS, STATE, PDIAG, FLUX,&
 & VNOEMI) 
USE YOEPHY , ONLY : TEPHY
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & AUX_DIAG_TYPE, KEYS_LOCAL_TYPE, FLUX_TYPE 
USE YOMCHEM , ONLY : TCHEM
USE VARIABLE_MODULE, ONLY: VARIABLE_3D
USE YOMCST , ONLY : TCST
USE YOETHF , ONLY : TTHF
TYPE(TTHF) ,INTENT(IN) :: YDTHF
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TCHEM) ,INTENT(INOUT) :: YDCHEM
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (KEYS_LOCAL_TYPE) , INTENT (IN) :: LLKEYS
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (AUX_DIAG_TYPE) , INTENT (INOUT) :: PDIAG
TYPE (FLUX_TYPE) , INTENT (IN) :: FLUX
TYPE (VARIABLE_3D) , INTENT (INOUT) :: VNOEMI
END SUBROUTINE LIGHTNING_LAYER
END INTERFACE
