INTERFACE
SUBROUTINE LIMB_PLANE(PLAT,PLON,PAZIM1,KPROF,LDCENTRED,PLAT_2D,PLON_2D,KERROR)
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB), INTENT(IN) :: PLAT
REAL(KIND=JPRB), INTENT(IN) :: PLON
REAL(KIND=JPRB), INTENT(IN) :: PAZIM1
INTEGER(KIND=JPIM), INTENT(IN) :: KPROF
LOGICAL, INTENT(IN) :: LDCENTRED
REAL(KIND=JPRB), INTENT(OUT) :: PLAT_2D(KPROF)
REAL(KIND=JPRB), INTENT(OUT) :: PLON_2D(KPROF)
INTEGER(KIND=JPIM), INTENT(OUT) :: KERROR
END SUBROUTINE LIMB_PLANE
END INTERFACE
