INTERFACE
SUBROUTINE LINCO_CHEM_INI(YDGEOMETRY,YDML_GCONF,YDCHEM)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCHEM , ONLY : TCHEM
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TCHEM), INTENT(INOUT):: YDCHEM
END SUBROUTINE LINCO_CHEM_INI
END INTERFACE
