INTERFACE
SUBROUTINE LISLAP(P,KINIP,KLATG,KLONG,KPDG,PCOS,PLAT,PFAC,POCE,PSPCM,&
 & PORTEE) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLATG
INTEGER(KIND=JPIM),INTENT(IN) :: KPDG
REAL(KIND=JPRB) ,INTENT(INOUT) :: P(KPDG)
INTEGER(KIND=JPIM),INTENT(IN) :: KINIP(KLATG)
INTEGER(KIND=JPIM) :: KLONG
REAL(KIND=JPRB) ,INTENT(IN) :: PCOS(KLATG)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KLATG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFAC
REAL(KIND=JPRB) ,INTENT(IN) :: POCE(KPDG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPCM
REAL(KIND=JPRB) ,INTENT(IN) :: PORTEE
END SUBROUTINE LISLAP
END INTERFACE
