INTERFACE
SUBROUTINE LITEST(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDINCR,YDVARBC,YDTCV_BGC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE CONTROL_VECTORS_MOD
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_BGC_MOD,ONLY : TOVSCV_BGC
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CONTROL_VECTOR),INTENT(IN) :: YDINCR
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV_BGC) ,INTENT(IN) :: YDTCV_BGC
END SUBROUTINE LITEST
END INTERFACE
