INTERFACE
SUBROUTINE LOCAL_ARRAYS_FIN(LLKEYS,AUXL,SURFL,PERTL,GEMSL)
USE YOMPHYDER ,ONLY : KEYS_LOCAL_TYPE, AUX_DIAG_LOCAL_TYPE,&
 & SURF_AND_MORE_LOCAL_TYPE, PERTURB_LOCAL_TYPE, GEMS_LOCAL_TYPE 
TYPE(KEYS_LOCAL_TYPE) , INTENT(INOUT) :: LLKEYS
TYPE(AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
TYPE(SURF_AND_MORE_LOCAL_TYPE) , INTENT(INOUT) :: SURFL
TYPE(PERTURB_LOCAL_TYPE) , INTENT(INOUT) :: PERTL
TYPE(GEMS_LOCAL_TYPE) , INTENT(INOUT) :: GEMSL
END SUBROUTINE LOCAL_ARRAYS_FIN
END INTERFACE
