INTERFACE
SUBROUTINE LWBVTL&
 & ( YDPHNC,KIDIA, KFDIA, KLON , KLEV , KMODE,&
 & PDT05 , PEMIS5, PEMIW5,&
 & PTL5 , PTAVE5,&
 & PEMIT5, PFLUC5,&
 & PABCU5, PBINT5, PBSUI5, PCNTRB5,&
 & PDT0 , PEMIS , PEMIW ,&
 & PTL , PTAVE ,&
 & PEMIT , PFLUC ,&
 & PABCU , PBINT , PBSUI , PCNTRB&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOELW , ONLY : NSIL ,NIPD ,NUA
USE YOPHNC , ONLY : TPHNC
TYPE(TPHNC) ,INTENT(INOUT) :: YDPHNC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KMODE
REAL(KIND=JPRB) ,INTENT(IN) :: PDT05(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIW5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAVE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMIT5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLUC5(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PABCU5(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBINT5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBSUI5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCNTRB5(KLON,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PDT0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAVE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMIT(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLUC(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PABCU(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBINT(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBSUI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCNTRB(KLON,KLEV+1,KLEV+1)
END SUBROUTINE LWBVTL
END INTERFACE
