INTERFACE
SUBROUTINE LWNEUR&
 & ( YDENEUR,KIDIA , KFDIA , KLON , KLEV,&
 & PCCO2 , PCLDLU, PCLDLUP,&
 & PDP , PDT0 , PEMIW,&
 & PPMB , PQOF , PTL,&
 & PTAVE , PWV,&
 & PGEMU , PCLON , PSLON,&
 & PUPF , PDNF&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOENEUR , ONLY : TENEUR
TYPE(TENEUR) ,INTENT(INOUT) :: YDENEUR
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PCCO2
REAL(KIND=JPRB) ,INTENT(IN) :: PCLDLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLDLUP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDT0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PPMB(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQOF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAVE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PWV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCLON(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLON(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUPF(KLON,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDNF(KLON,KLEV+1,KLEV+1)
END SUBROUTINE LWNEUR
END INTERFACE
