INTERFACE
SUBROUTINE LWTTAD ( KIDIA, KFDIA, KLON, PGA, PGB, PUU5, PTT5, PUU, PTT )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOELW , ONLY : NIPD , NTRA ,NUA ,RPTYPE ,RETYPE ,&
 & RO1H ,RO2H ,RPIALF0 
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PGA(KLON,NIPD,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PGB(KLON,NIPD,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PUU5(KLON,NUA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTT5(KLON,NTRA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUU(KLON,NUA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT(KLON,NTRA)
END SUBROUTINE LWTTAD
END INTERFACE
