INTERFACE
SUBROUTINE LWUAD&
 & ( YDERDI,YDPHNC,KIDIA, KFDIA, KLON, KLEV,&
 & PVIEW , PCCO2 , PAER5 , PDP5 , PPMB5, PQOF5 , PTAVE5, PWV5,&
 & PABCU5 ,&
 & PAER , PDP , PPMB , PQOF , PTAVE , PWV ,&
 & PABCU&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOELW , ONLY : NSIL ,NUA ,NG1 ,NG1P1 ,&
 & ALWT ,BLWT ,RO3T ,RT1 ,TREF ,&
 & RVGCO2 ,RVGH2O ,RVGO3 
USE YOERDI , ONLY : TERDI
USE YOPHNC , ONLY : TPHNC
TYPE(TERDI) ,INTENT(IN) :: YDERDI
TYPE(TPHNC) ,INTENT(IN) :: YDPHNC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PVIEW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCCO2
REAL(KIND=JPRB) ,INTENT(IN) :: PAER5(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPMB5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQOF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAVE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PWV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PABCU5(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAER(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPMB(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQOF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAVE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PABCU(KLON,NUA,3*KLEV+1)
END SUBROUTINE LWUAD
END INTERFACE
