INTERFACE
SUBROUTINE LWVAD&
 & ( YDELWRAD,YDPHNC,KIDIA, KFDIA, KLON , KLEV , KUAER , KTRAER,&
 & PGA , PGB , PGASUR , PGBSUR, PGATOP , PGBTOP,&
 & PABCU5 , PB5 , PBINT5 , PBSUR5, PBTOP5 , PDBSL5,&
 & PEMIS5 , PEMIW5,&
 & PCNTRB5, PFLUC5,&
 & PADJD5, PADJU5, PDBDT5, PDISD5, PDISU5, PDWFSU5,&
 & PCOND5 , PTTPA5 , PTTPB5 , PTTA5 , PTTB5 ,&
 & PZZA5 , PZZB5 , PXNA5 , PXNB5 , PXDIVA5,&
 & PXDIVB5 , PZZA15 , PZZB15 , PXNA15, PXNB15 ,&
 & PXDIVA15, PXDIVB15, PTTPA15, PTTPB15,&
 & PABCU , PB , PBINT , PBSUR , PBTOP , PDBSL,&
 & PEMIS , PEMIW ,&
 & PCNTRB , PFLUC&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOELW , ONLY : NSIL ,NIPD ,NUA
USE YOPHNC , ONLY : TPHNC
USE YOELWRAD , ONLY : TELWRAD
TYPE(TELWRAD) ,INTENT(IN) :: YDELWRAD
TYPE(TPHNC) ,INTENT(IN) :: YDPHNC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KUAER
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAER
REAL(KIND=JPRB) ,INTENT(IN) :: PGA(KLON,NIPD,2,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGB(KLON,NIPD,2,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGASUR(KLON,NIPD,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PGBSUR(KLON,NIPD,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PGATOP(KLON,NIPD,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PGBTOP(KLON,NIPD,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PABCU5(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PB5(KLON,NSIL,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PBINT5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PBSUR5(KLON,NSIL)
REAL(KIND=JPRB) ,INTENT(IN) :: PBTOP5(KLON,NSIL)
REAL(KIND=JPRB) ,INTENT(IN) :: PDBSL5(KLON,NSIL,KLEV*2)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIW5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCNTRB5(KLON,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLUC5(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PABCU(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB(KLON,NSIL,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBINT(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBSUR(KLON,NSIL)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBTOP(KLON,NSIL)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDBSL(KLON,NSIL,KLEV*2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEMIW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCNTRB(KLON,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLUC(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PADJD5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PADJU5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDBDT5(KLON,NSIL,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDWFSU5(KLON,NSIL)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDISD5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDISU5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCOND5(YDELWRAD%NPROMALW,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTPA5(YDELWRAD%NPROMALW,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTPB5(YDELWRAD%NPROMALW,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTA5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTB5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZZA5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZZB5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXNA5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXNB5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXDIVA5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXDIVB5(YDELWRAD%NPROMALW,KTRAER,KLEV,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZZA15(YDELWRAD%NPROMALW,KTRAER,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZZB15(YDELWRAD%NPROMALW,KTRAER,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXNA15(YDELWRAD%NPROMALW,KTRAER,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXNB15(YDELWRAD%NPROMALW,KTRAER,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXDIVA15(YDELWRAD%NPROMALW,KTRAER,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXDIVB15(YDELWRAD%NPROMALW,KTRAER,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTPA15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTTPB15(KLON,KLEV+1)
END SUBROUTINE LWVAD
END INTERFACE
