INTERFACE
SUBROUTINE LWVNRAD&
 & ( YDPHNC,KIDIA, KFDIA, KLON , KLEV , KUAER,&
 & PGA , PGB , PABCU5 , PDBSL5,&
 & PADJD5, PADJU5, PCNTRB5, PDBDT5, PDWFSU5,&
 & PABCU , PDBSL ,&
 & PADJD , PADJU , PCNTRB , PDBDT , PDWFSU&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOELW , ONLY : NSIL ,NIPD ,NTRA ,NUA ,&
 & NG1 ,NG1P1 ,WG1 
USE YOPHNC , ONLY : TPHNC
TYPE(TPHNC) ,INTENT(IN) :: YDPHNC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KUAER
REAL(KIND=JPRB) ,INTENT(IN) :: PGA(KLON,NIPD,2,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGB(KLON,NIPD,2,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PABCU5(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PDBSL5(KLON,NSIL,KLEV*2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PADJD5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PADJU5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCNTRB5(KLON,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDBDT5(KLON,NSIL,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDWFSU5(KLON,NSIL)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PABCU(KLON,NUA,3*KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDBSL(KLON,NSIL,KLEV*2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PADJD(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PADJU(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCNTRB(KLON,KLEV+1,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDBDT(KLON,NSIL,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDWFSU(KLON,NSIL)
END SUBROUTINE LWVNRAD
END INTERFACE
