INTERFACE
SUBROUTINE makedesc(KPOOLNO, KANDAT, KANTIM, KNMXUPD,&
 & KLATLON_RAD) 
USE PARKIND1 ,ONLY : JPIM ,JPRD
USE odb_module
USE yomdb
INTEGER(KIND=JPIM), intent(in) :: KPOOLNO, KANDAT, KANTIM, KNMXUPD
INTEGER(KIND=JPIM), intent(in), optional :: KLATLON_RAD
END SUBROUTINE makedesc
END INTERFACE
