INTERFACE
SUBROUTINE MAP_VARNO_TO_NVAR(KVARNO,CDLV,KVARL,KIMPLIED_VARNO)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KVARNO
CHARACTER(LEN=10) ,INTENT(OUT) :: CDLV
INTEGER(KIND=JPIM),INTENT(OUT) :: KVARL
INTEGER(KIND=JPIM),INTENT(OUT) :: KIMPLIED_VARNO
END SUBROUTINE MAP_VARNO_TO_NVAR
END INTERFACE
