INTERFACE
SUBROUTINE MAXGPFV(YDGEOMETRY,YDSURF,PWSMAX,PWDMAX)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
REAL(KIND=JPRB) ,INTENT(OUT) :: PWSMAX
REAL(KIND=JPRB) ,INTENT(OUT) :: PWDMAX
END SUBROUTINE MAXGPFV
END INTERFACE
