INTERFACE
SUBROUTINE MEANWIND_XFU (YDCPG_OPTS, YDCPG_BNDS, KMEANSTEPS, PXFU, PXFV, PXU, PXV, PMWINDCALC, ZUM, ZVM)
USE PARKIND1 , ONLY : JPIM, JPRB
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
TYPE(CPG_OPTS_TYPE) ,INTENT(IN) :: YDCPG_OPTS
TYPE(CPG_BNDS_TYPE) ,INTENT(IN) :: YDCPG_BNDS
INTEGER(KIND=JPIM) ,INTENT(IN) :: KMEANSTEPS
REAL(KIND=JPRB) ,INTENT(IN) :: PXFU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PXFV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PXU(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PXV(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMWINDCALC(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: ZUM(YDCPG_OPTS%KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: ZVM(YDCPG_OPTS%KLON)
END SUBROUTINE MEANWIND_XFU
END INTERFACE
