INTERFACE
SUBROUTINE MEAN_RAD_TEMP(KIDIA,KFDIA,KLON,&
 & PMU0,PFRSOS,PFRSODS,PFRSOPS,PFRTHS,PFRTHDS,&
 & PMRT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
REAL(KIND=JPRB),INTENT(IN) :: PMU0 (KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRSOS (KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRSODS(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRSOPS(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRTHS (KLON)
REAL(KIND=JPRB),INTENT(IN) :: PFRTHDS(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PMRT (KLON)
END SUBROUTINE MEAN_RAD_TEMP
END INTERFACE
