INTERFACE
SUBROUTINE MEANUV_AVERAGE(KDLEN,KDCOUNT,KLEV,PUV,PW,PXPP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PUV(KDLEN,KLEV,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PW(KDLEN,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXPP(KDLEN,KDCOUNT,2)
END SUBROUTINE MEANUV_AVERAGE
END INTERFACE
