INTERFACE
SUBROUTINE MF_PHYS_NHQE_PART2 (YDGEOMETRY, YDCPG_BNDS, YDCPG_OPTS, PNHQ_TT0, PNHQ_TT0L, PNHQ_TT0M,&
 & PNHQ_TT9, YDVARS) 
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD , ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE),INTENT(IN) :: YDCPG_BNDS
TYPE(CPG_OPTS_TYPE),INTENT(IN) :: YDCPG_OPTS
REAL (KIND=JPRB), INTENT(IN) :: PNHQ_TT0 (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT(IN) :: PNHQ_TT0L (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT(IN) :: PNHQ_TT0M (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
REAL (KIND=JPRB), INTENT(IN) :: PNHQ_TT9 (YDCPG_OPTS%KLON, 1:YDCPG_OPTS%KFLEVG)
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS
END SUBROUTINE MF_PHYS_NHQE_PART2
END INTERFACE
