INTERFACE
SUBROUTINE MF_PHYSTL(YDGEOMETRY,YDGMV,YDGMV5,YDSURF5,&
 & YDMODEL,KST,KEND,KSTGLO,PDTPHY,&
 & KIBL,&
 & PGMV,PGFL,PRCP0,PXYB0,PHI0,PHIF0,PRE0,PRE0F,PCTY0,&
 & PRCP9,PXYB9,PHI9,PHIF9,PRE9,PRE9F,&
 & PQS,PQS1,PSNS,PTS,PTS1,&
 & PFORCEU,PFORCEV,PFORCET,PFORCEQ,&
 & PB1,PGMVT1,PGFLT1,&
 & PGMVT5,PGFLT5,PRCP5,PXYB5,PHI5,PHIF5,PRE5,PRE5F,PCTY5,&
 & PGMVT95,PGFLT95,PRCP95,PXYB95,PHI95,PHIF95,PRE95,PRE95F,&
 & PSD_VF5,&
 & PTRAJ_PHYS,PTRAJ_PHYS_TLAD) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM ,JPRB
USE INTDYN_MOD,ONLY : YYTCTY5 ,YYTCTY0 ,YYTRCP5 ,YYTRCP95 ,&
 & YYTRCP0 ,YYTRCP9 ,YYTXYB5 ,YYTXYB95 ,YYTXYB0 ,YYTXYB9 ,YYTGMVT95,YYTGFLT95 
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE, TRAJ_PHYS_TLAD_TYPE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(TSURF) ,INTENT(IN) :: YDSURF5
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KST
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PDTPHY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIBL
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCP0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTRCP0%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB0%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PHI0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PHIF0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE0F(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCTY0(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG,YYTCTY0%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTRCP9%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB9%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PHI9(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PHIF9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE9(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE9F(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS1(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS1(YDGEOMETRY%YRDIM%NPROMM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%YT1%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVT5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV5%YT5%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFLT5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM5)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCP5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTRCP5%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB5%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PHI5(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PHIF5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE5(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE5F(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PCTY5(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG,YYTCTY5%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTGMVT95%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFLT95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTGFLT95%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCP95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTRCP95%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PXYB95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB95%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PHI95(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PHIF95(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE95(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE95F(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSD_VF5(YDGEOMETRY%YRDIM%NPROMA,YDSURF5%YSD_VFD%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEU(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCET(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFORCEQ(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
TYPE (TRAJ_PHYS_TYPE) ,INTENT(IN) :: PTRAJ_PHYS
TYPE (TRAJ_PHYS_TLAD_TYPE),INTENT(INOUT) :: PTRAJ_PHYS_TLAD
END SUBROUTINE MF_PHYSTL
END INTERFACE
