INTERFACE
SUBROUTINE MKGLOBSTAB_MODEL(YDGEOMETRY,YDSLREP,YDOBSLOCS,YDG)
USE YOMSLREP , ONLY : TSLREP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMLOCS , ONLY : TOBSLOCS
USE YOMGLOBS , ONLY : TGLOBS
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TSLREP) ,INTENT(INOUT) :: YDSLREP
TYPE(TOBSLOCS), INTENT(IN) :: YDOBSLOCS
TYPE(TGLOBS), INTENT(INOUT) :: YDG
END SUBROUTINE MKGLOBSTAB_MODEL
END INTERFACE
