INTERFACE
SUBROUTINE MO_ADJRXT( KIDIA, KFDIA, PRATE, PINV, PM, KLON, KLEV )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE MO_MOD_CHEM_MODS, ONLY : NFS, RXNTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB), INTENT(IN) :: PINV(KLON,KLEV,NFS)
REAL(KIND=JPRB), INTENT(IN) :: PM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PRATE(KLON,KLEV,RXNTOT)
END SUBROUTINE MO_ADJRXT
END INTERFACE
