INTERFACE
SUBROUTINE MO_CHEM_INIT_MOZ(YGFL, YDGEOMETRY)
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(GEOMETRY), INTENT(IN):: YDGEOMETRY
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
END SUBROUTINE MO_CHEM_INIT_MOZ
END INTERFACE
