INTERFACE
SUBROUTINE MO_EXP_PROD_LOSS(YGFL,KLON,KLEV, PROD, PLOSS, PY, PRXT, PHET_RATES )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE MO_MOD_CHEM_MODS, ONLY : CLSCNT1, HETCNT, RXNTOT
TYPE(TYPE_GFLD) ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV
REAL(KIND=JPRB), DIMENSION(KLON,KLEV,MAX(1,CLSCNT1)), INTENT(OUT) ::&
 & PROD,&
 & PLOSS 
REAL(KIND=JPRB), INTENT(IN) :: PY(KLON,KLEV,YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(IN) :: PRXT(KLON,KLEV,MAX(1,RXNTOT))
REAL(KIND=JPRB), INTENT(IN) :: PHET_RATES(KLON,KLEV,MAX(1,HETCNT))
END SUBROUTINE MO_EXP_PROD_LOSS
END INTERFACE
