INTERFACE
SUBROUTINE MO_GET_CRS( KSHT_INDEXER, CDJNAMES )
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(INOUT) :: KSHT_INDEXER(:)
CHARACTER(LEN=9) , INTENT(IN) :: CDJNAMES(110)
END SUBROUTINE MO_GET_CRS
END INTERFACE
