INTERFACE
SUBROUTINE MO_H2FLBC_SET(YGFL, KIDIA, KFDIA, PGELAT, PVMR, KLON, KLEV )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA
REAL(KIND=JPRB), INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PVMR(KLON,KLEV,YGFL%NCHEM)
END SUBROUTINE MO_H2FLBC_SET
END INTERFACE
