INTERFACE
SUBROUTINE MO_IMP_NLNMAT(YGFL, PMAT, PY, PRXT, PLMAT, PDTI )
USE PARKIND1 ,ONLY : JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE MO_MOD_CHEM_MODS, ONLY : RXNTOT, IMP_NZCNT
 TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
REAL(KIND=JPRB), INTENT(IN) :: PDTI
REAL(KIND=JPRB), INTENT(IN) :: PLMAT(IMP_NZCNT)
REAL(KIND=JPRB), INTENT(IN) :: PY(YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(IN) :: PRXT(RXNTOT)
REAL(KIND=JPRB), INTENT(INOUT) :: PMAT(IMP_NZCNT)
END SUBROUTINE MO_IMP_NLNMAT
END INTERFACE
