INTERFACE
SUBROUTINE MO_JLONG_INIT( KLNG_INDEXER, CDJNAMES )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE MO_MOD_CHEM_MODS, ONLY : PHTCNT
INTEGER(KIND=JPIM), INTENT(INOUT) :: KLNG_INDEXER(PHTCNT)
CHARACTER(LEN=9) , INTENT(IN) :: CDJNAMES(110)
END SUBROUTINE MO_JLONG_INIT
END INTERFACE
