INTERFACE
SUBROUTINE MO_JPL( PRATE, PM, PFACTOR, PKO, PKINF)
USE PARKIND1 ,ONLY : JPIM, JPRB
REAL(KIND=JPRB), INTENT(IN) :: PFACTOR
REAL(KIND=JPRB), INTENT(IN) :: PKO
REAL(KIND=JPRB), INTENT(IN) :: PKINF
REAL(KIND=JPRB), INTENT(IN) :: PM
REAL(KIND=JPRB), INTENT(OUT) :: PRATE
END SUBROUTINE MO_JPL
END INTERFACE
