INTERFACE
SUBROUTINE MO_JSHORT( KLEV, PZEN, PN2CC, PO2CC, PO3CC,&
 & PNOCC, PTLEV, PZKM, PJO2_SHT, PJNO_SHT, PJSHT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE MO_MOD_JSHORT, ONLY:&
 & NSRC_TOT, NSRB_TOT, NSRBTUV, NW, ETFPHOT, XS_WL, NJ 
INTEGER(KIND=JPIM), PARAMETER :: IBRANCH = 2_JPIM
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
REAL(KIND=JPRB), INTENT (IN) :: PZEN
REAL(KIND=JPRB), INTENT (IN) :: PN2CC(KLEV)
REAL(KIND=JPRB), INTENT (IN) :: PO2CC(KLEV)
REAL(KIND=JPRB), INTENT (IN) :: PO3CC(KLEV)
REAL(KIND=JPRB), INTENT (IN) :: PNOCC(KLEV)
REAL(KIND=JPRB), INTENT (IN) :: PTLEV(KLEV)
REAL(KIND=JPRB), INTENT (IN) :: PZKM(KLEV)
REAL(KIND=JPRB), INTENT (OUT) :: PJO2_SHT(KLEV,IBRANCH)
REAL(KIND=JPRB), INTENT (OUT) :: PJNO_SHT(KLEV)
REAL(KIND=JPRB), INTENT (OUT) :: PJSHT(KLEV,NJ)
END SUBROUTINE MO_JSHORT
END INTERFACE
