INTERFACE
SUBROUTINE MO_LBOUNDARY(YGFL, KIDIA, KFDIA, KLON, KLEV, PTSTEP, PY0, PTEND )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA
REAL(KIND=JPRB),INTENT(IN) :: PTSTEP
REAL(KIND=JPRB),INTENT(IN) :: PY0(KLON,YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(INOUT) :: PTEND(KLON, KLEV, YGFL%NCHEM)
END SUBROUTINE MO_LBOUNDARY
END INTERFACE
