INTERFACE
SUBROUTINE MO_NECKEL_SCALE_ETF( PF107, PF107A )
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB), INTENT(IN) :: PF107
REAL(KIND=JPRB), INTENT(IN) :: PF107A
END SUBROUTINE MO_NECKEL_SCALE_ETF
END INTERFACE
