INTERFACE
SUBROUTINE MO_NEGTRC(YGFL, KIDIA, KFDIA, PFLD, KLON, KLEV )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB), INTENT(INOUT) :: PFLD(KLON,KLEV,YGFL%NCHEM)
END SUBROUTINE MO_NEGTRC
END INTERFACE
