INTERFACE
SUBROUTINE MO_REBIN( KNSRC, KNTRG, PSRC_X, PTRG_X, PSRC, PTRG )
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KNSRC
INTEGER(KIND=JPIM), INTENT(IN) :: KNTRG
REAL(KIND=JPRB), INTENT(IN) :: PSRC_X(KNSRC+1)
REAL(KIND=JPRB), INTENT(IN) :: PTRG_X(KNTRG+1)
REAL(KIND=JPRB), INTENT(IN) :: PSRC(KNSRC)
REAL(KIND=JPRB), INTENT(OUT) :: PTRG(KNTRG)
END SUBROUTINE MO_REBIN
END INTERFACE
