INTERFACE
SUBROUTINE MO_SET_UB_COL(YGFL, KIDIA, KFDIA, PCOL_DELTA, PVMR, PINVARIANTS, PDEL, KLON, KLEV )
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE MO_MOD_CHEM_MODS, ONLY : NCOL_ABS, NFS, INDEXM
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB), INTENT(OUT) :: PCOL_DELTA(KLON,0:KLEV,MAX(1,NCOL_ABS))
REAL(KIND=JPRB), INTENT(IN) :: PVMR(KLON,KLEV,YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(IN) :: PINVARIANTS(KLON,KLEV,NFS)
REAL(KIND=JPRB), INTENT(IN) :: PDEL(KLON,KLEV)
END SUBROUTINE MO_SET_UB_COL
END INTERFACE
