INTERFACE
 SUBROUTINE MO_SETHET(YGFL, KIDIA, KFDIA, PHET_RATES, PRESS, PZMID, PHIS,&
 & PTFLD, PRECIP, PDELT,&
 & PXHNM, PQIN, KTOP, KLON, KLEV ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE MO_MOD_CHEM_MODS, ONLY : HETCNT
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV, KIDIA, KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTOP
REAL(KIND=JPRB), INTENT(IN) :: PDELT
REAL(KIND=JPRB), INTENT(IN) :: PRESS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRECIP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQIN(KLON,KLEV,YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(IN) :: PZMID(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PHIS(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PTFLD(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PXHNM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PHET_RATES(KLON,KLEV,MAX(1,HETCNT))
END SUBROUTINE MO_SETHET
END INTERFACE
