INTERFACE
 SUBROUTINE MO_SETINV(YGFL, KIDIA, KFDIA, PINVARIANTS, PTFLD,&
 & PMID, PVMR, KLON, KLEV ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE MO_MOD_CHEM_MODS, ONLY : NFS
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB), INTENT(IN) :: PTFLD(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PMID(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PVMR(KLON,KLEV,YGFL%NCHEM)
REAL(KIND=JPRB), INTENT(OUT) :: PINVARIANTS(KLON,KLEV,NFS)
END SUBROUTINE MO_SETINV
END INTERFACE
