INTERFACE
SUBROUTINE MO_SAD_STRAT_CALC( KIDIA, KFDIA, PM, PRESS, PTEMP,&
 & PHNO3_GAS, PHNO3_COND, PH2O_GAS, PH2O_COND, PSAD_SAGE,&
 & PRADIUS_STRAT, PSAD_STRAT, KTOP, KLON, KLEV ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KTOP
REAL(KIND=JPRB), INTENT(IN) :: PM(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PSAD_SAGE(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRESS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTEMP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PH2O_COND(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PH2O_GAS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PHNO3_GAS(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PHNO3_COND(KLON,KLEV,3)
REAL(KIND=JPRB), INTENT(OUT) :: PRADIUS_STRAT(KLON,KLEV,4)
REAL(KIND=JPRB), INTENT(OUT) :: PSAD_STRAT(KLON,KLEV,4)
 END SUBROUTINE MO_SAD_STRAT_CALC
END INTERFACE
