INTERFACE
SUBROUTINE MO_TROP_HETRATES(YDCHEM,YDEAERSNK,YDEAERATM,YGFL, KIDIA, KFDIA, KLON, KL, KLEV,&
 & KAEROC, PTP, PRSF1,&
 & PQP, PHO2,&
 & PNH4,PNO3_A, PSO4,&
 & PAEROP,&
 & PRR) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE MO_MOD_CHEM_MODS, ONLY : RXNTOT
USE YOEAERATM, ONLY : TEAERATM
USE YOEAERSNK ,ONLY : TEAERSNK
USE YOMCHEM , ONLY : TCHEM
TYPE(TCHEM), INTENT(INOUT) :: YDCHEM
TYPE(TEAERSNK), INTENT(INOUT) :: YDEAERSNK
TYPE(TEAERATM), INTENT(INOUT) :: YDEAERATM
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA , KFDIA , KLON , KL, KLEV, KAEROC
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PNH4(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PNO3_A(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PSO4(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PAEROP(KLON,KLEV,KAEROC)
REAL(KIND=JPRB),INTENT(IN) :: PHO2(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PRR(KLON,KLEV,RXNTOT)
END SUBROUTINE MO_TROP_HETRATES
END INTERFACE
