INTERFACE
SUBROUTINE MO_USRRXT(YDCHEM,YDEAERSNK,YDEAERATM,YGFL, KIDIA, KFDIA, PRXT, PTEMP, PINVARIANTS, PH2OVMR, PRELHUM,&
 & PSULFATE, PM, KTROPLEV, KLON, KLEV, PQP, PRSF1,&
 & KAEROC, PAEROP, PHO2, PNO3, PNH4, PSO4 ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOEAERATM, ONLY : TEAERATM
USE YOEAERSNK ,ONLY : TEAERSNK
USE YOMCHEM , ONLY : TCHEM
USE MO_MOD_CHEM_MODS, ONLY : NFS, RXNTOT
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
TYPE(TEAERSNK), INTENT(INOUT) :: YDEAERSNK
TYPE(TEAERATM), INTENT(INOUT) :: YDEAERATM
TYPE(TCHEM), INTENT(INOUT) :: YDCHEM
INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV, KIDIA, KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KTROPLEV(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PTEMP(KLON,KLEV),&
 & PM(KLON,KLEV),&
 & PH2OVMR(KLON,KLEV),&
 & PRELHUM(KLON,KLEV),&
 & PINVARIANTS(KLON,KLEV,NFS),&
 & PSULFATE(KLON,KLEV) 
REAL(KIND=JPRB),INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KAEROC
REAL(KIND=JPRB),INTENT(IN) :: PAEROP(KLON,KLEV,KAEROC)
REAL(KIND=JPRB),INTENT(IN) :: PHO2(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PNO3(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PNH4(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PSO4(KLON,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PRXT(KLON,KLEV,RXNTOT)
END SUBROUTINE MO_USRRXT
END INTERFACE
