INTERFACE
SUBROUTINE MOC_KPP_ROSENBROCK(PY,PFIX, PRCONST, PTSTART,PTEND,&
 & PABSTOL,PRELTOL, PCFACTOR,&
 & PRCNTRL,KCNTRL,PRSTATUS,KSTATUS,KERR) 
 USE MOC_KPP_Parameters, only:NREACT,NVAR ,NFIX
 USE PARKIND1 , ONLY : JPIM ,JPRB
 REAL(KIND=JPRB), INTENT(INOUT) :: PY(NVAR),PFIX(NFIX)
 REAL(KIND=JPRB), INTENT(IN) :: PRCONST(NREACT)
 REAL(KIND=JPRB), INTENT(IN) :: PTSTART,PTEND
 REAL(KIND=JPRB), INTENT(IN) :: PABSTOL(NVAR),PRELTOL(NVAR)
 INTEGER(KIND=JPIM), INTENT(IN) :: KCNTRL(20)
 REAL(KIND=JPRB), INTENT(IN) :: PRCNTRL(20)
 INTEGER(KIND=JPIM), INTENT(INOUT) :: KSTATUS(20)
 REAL(KIND=JPRB), INTENT(IN) :: PCFACTOR
 REAL(KIND=JPRB), INTENT(INOUT) :: PRSTATUS(20)
 INTEGER(KIND=JPIM), INTENT(OUT) :: KERR
END SUBROUTINE MOC_KPP_Rosenbrock
END INTERFACE
