INTERFACE
SUBROUTINE MOC_KPP_KPPDECOMP( PJVS, KERR )
 USE MOC_KPP_Parameters, only: LU_NONZERO
 USE PARKIND1 , ONLY : JPIM ,JPRB
 INTEGER(KIND=JPIM), INTENT(OUT) :: KERR
 REAL(kind=JPRB), INTENT(INOUT) :: PJVS(LU_NONZERO)
END SUBROUTINE MOC_KPP_KPPDECOMP
END INTERFACE
