INTERFACE
SUBROUTINE MOC_KPP_FUN ( PV, PF, PRCT, PVDOT )
 USE PARKIND1, ONLY : JPIM, JPRB
 USE MOC_KPP_PARAMETERS, ONLY : NVAR, NREACT, NFIX
 REAL(KIND=JPRB), INTENT(IN) :: PV(NVAR)
 REAL(KIND=JPRB), INTENT(IN) :: PF(NFIX)
 REAL(KIND=JPRB), INTENT(IN) :: PRCT(NREACT)
 REAL(KIND=JPRB), INTENT(OUT) :: PVDOT(NVAR)
END SUBROUTINE MOC_KPP_FUN
END INTERFACE
