INTERFACE
SUBROUTINE MOC_KPP_UPDATE_CIFS_CONC(YGFL,PVAR,PCVM)
 USE PARKIND1 , ONLY : JPIM ,JPRB
 USE YOM_YGFL , ONLY : TYPE_GFLD
 USE MOC_KPP_PARAMETERS, ONLY: NVAR,&
 & IND_H2SO4 , IND_CH3SO3H , IND_H2S ,&
 & IND_Cl2O2 , IND_CF2Cl2 , IND_CFCl3 , IND_CF3Br ,&
 & IND_Cl2 , IND_CCl4 , IND_CH3CCl3 , IND_CF2ClCFCl2 ,&
 & IND_CF2ClBr , IND_LXYL , IND_TOLUENE , IND_DMSO ,&
 & IND_N2O , IND_OClO , IND_ClNO2 , IND_N2O5 ,&
 & IND_BrNO3 , IND_BrCl , IND_C5H12 , IND_CH3Cl ,&
 & IND_C8H18 , IND_C3H8 , IND_HCOCO3H ,&
 & IND_SO2 , IND_N , IND_CHF2Cl , IND_CH3Br ,&
 & IND_C2H6 , IND_HOBr , IND_DMS , IND_ClNO3 ,&
 & IND_CH3OOH , IND_HNO4 , IND_PHO , IND_HBr ,&
 & IND_HONO , IND_CH3O , IND_CH3 , IND_HOCl ,&
 & IND_H2O2 , IND_HCl , IND_HKET , IND_C2H4 ,&
 & IND_CH3CO3H ,IND_ADDT , IND_ADDX , IND_CO ,&
 & IND_APINENE , IND_LIMON , IND_ADDC , IND_HNO3 ,&
 & IND_PAN , IND_C4H6 , IND_HOCH2CH2O2 ,IND_CRESOL ,&
 & IND_CH4 , IND_OLTP , IND_OLIP , IND_TPAN ,&
 & IND_C5H8 , IND_APIP , IND_LIMP , IND_C8H17O2 ,&
 & IND_C5H11O2 , IND_BrO , IND_CH3COCH3 ,IND_GLYOX ,&
 & IND_ISOPBO2 , IND_H2O , IND_MGLYOX ,IND_C7H9O4 ,&
 & IND_Br , IND_XO2 , IND_ClO ,&
 & IND_C7H9O3 ,IND_C8H11O3 , IND_IC3H7O2 , IND_C2H5O2 ,&
 & IND_CH3CHO ,IND_MACR , IND_OLI , IND_OLNN ,&
 & IND_OLND , IND_CH3COCH2O2 , IND_H , IND_OLT ,&
 & IND_TCO3 , IND_DCB , IND_Cl , IND_HCHO ,&
 & IND_O1D , IND_ORGNTR , IND_HO2 , IND_OH ,&
 & IND_CH3CO3 ,IND_OP2 , IND_CH3O2 , IND_O3P ,&
 & IND_O3 , IND_NO , IND_NO2 , IND_NO3 
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
 REAL(KIND=JPRB),INTENT(IN) :: PVAR(NVAR)
 REAL(KIND=JPRB),INTENT(INOUT) :: PCVM(YGFL%NCHEM)
END SUBROUTINE MOC_KPP_UPDATE_CIFS_CONC
END INTERFACE
