INTERFACE
SUBROUTINE MOC_KPP_INTEGRATOR( PTIN, PTOUT,&
 & KCNTRL_U, PRCNTRL_U, KSTATUS_U, PRSTATUS_U, KERR_U, PVAR, PFIX, PRCONST, PCFACTOR ) 
 USE PARKIND1 ,ONLY : JPIM, JPRB
 USE MOC_KPP_Parameters, ONLY: NVAR, NFIX, NHEXIT, NREACT
 REAL(KIND=JPRB), INTENT(IN) :: PTIN
 REAL(KIND=JPRB), INTENT(IN) :: PTOUT
 INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KCNTRL_U(20)
 REAL(KIND=JPRB), INTENT(IN), OPTIONAL :: PRCNTRL_U(20)
 INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KSTATUS_U(20)
 REAL(KIND=JPRB), INTENT(OUT), OPTIONAL :: PRSTATUS_U(20)
 INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KERR_U
 REAL(KIND=JPRB), INTENT(INOUT) :: PVAR(NVAR),PFIX(NFIX)
 REAL(KIND=JPRB), INTENT(IN) :: PRCONST(NREACT)
 REAL(KIND=JPRB), INTENT(IN) :: PCFACTOR
END SUBROUTINE MOC_KPP_INTEGRATOR
END INTERFACE
