INTERFACE
SUBROUTINE MOCAGE_CHEM_INI(CDMOCAGESCHEME, YGFL, YDGEOMETRY, YDCHEM)
USE YOM_YGFL, ONLY : TYPE_GFLD
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMCHEM, ONLY : TCHEM
CHARACTER(LEN=*),INTENT(IN) :: CDMOCAGESCHEME
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TCHEM), INTENT(IN) :: YDCHEM
END SUBROUTINE MOCAGE_CHEM_INI
END INTERFACE
