INTERFACE
 SUBROUTINE MOCAGE_SOUFREAQ(KIDIA, KFDIA, KLON, KLEV, KNCHEM,&
 & PPAM, PTGRIM, PRNEB, PCEN, PQLIQ) 
 USE PARKIND1, ONLY : JPIM, JPRB
 INTEGER(KIND=JPIM), INTENT(IN) :: KLON, KLEV, KIDIA, KFDIA, KNCHEM
 REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PPAM
 REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PTGRIM
 REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PRNEB
 REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PQLIQ
 REAL(KIND=JPRB), DIMENSION(KLON,KLEV,KNCHEM), INTENT(INOUT) :: PCEN
END SUBROUTINE MOCAGE_SOUFREAQ
END INTERFACE
