INTERFACE
SUBROUTINE MOD_INI(KUDATE,KUSSSS,KSTEP,KUCONF,KUSTOP,&
 & KSTEPINI,PTSTEP,KULOUT) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(INOUT) :: KUDATE
INTEGER(KIND=JPIM),INTENT(INOUT) :: KUSSSS
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KUCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KUSTOP
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSTEPINI
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE MOD_INI
END INTERFACE
