INTERFACE
SUBROUTINE MODGRIN(YDGEM,YDMCC,YDEPHY,KFIELDS,KPAR,PFPDGG)
USE YOMGEM , ONLY : TGEM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMMCC , ONLY : TMCC
TYPE(TGEM) ,INTENT(IN) :: YDGEM
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),INTENT(OUT) :: KPAR(:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPDGG(:,:)
END SUBROUTINE MODGRIN
END INTERFACE
