INTERFACE
SUBROUTINE MONIO(YDCFU,YDXFU,YDRIP,YDARPHY,YDLDDH,KPOSTS,KHISTS,KSFXHISTS,KGDITS,KSDITS,KDHFGTS,&
 & KDHFZTS,KDHFDTS,KDHPTS,KCFUTS,KXFUTS,KRESTS,KMASSCONS,KRAZTS) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCT0 , ONLY : NPOSTS ,NHISTS ,NGDITS ,&
 & NSDITS ,NDHFGTS ,NDHFZTS ,NDHFDTS ,NDHPTS ,&
 & NMASSCONS,NFRPOS ,&
 & NFRHIS ,NFRGDI ,NFRSDI ,NFRDHFG ,NFRDHFZ ,&
 & NFRDHFD ,NFRDHP ,NFRMASSCON,NSFXHISTS ,NFRSFXHIS,&
 & NHISTSMIN, NSFXHISTSMIN, NPOSTSMIN 
USE YOMRIP , ONLY : TRIP
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE YOMRES , ONLY : NRESTS ,NFRRES
USE YOMARPHY , ONLY : TARPHY
USE YOMLDDH , ONLY : TLDDH
TYPE(TCFU) ,INTENT(INOUT) :: YDCFU
TYPE(TXFU) ,INTENT(INOUT) :: YDXFU
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
TYPE(TARPHY) ,INTENT(INOUT) :: YDARPHY
TYPE(TLDDH) ,INTENT(INOUT) :: YDLDDH
INTEGER(KIND=JPIM),INTENT(OUT) :: KPOSTS(YDRIP%NSTART:YDRIP%NSTOP/NFRPOS)
INTEGER(KIND=JPIM),INTENT(OUT) :: KHISTS(YDRIP%NSTART:YDRIP%NSTOP/NFRHIS)
INTEGER(KIND=JPIM),INTENT(OUT) :: KSFXHISTS(YDRIP%NSTART:YDRIP%NSTOP/NFRSFXHIS)
INTEGER(KIND=JPIM),INTENT(OUT) :: KGDITS(YDRIP%NSTART:YDRIP%NSTOP/NFRGDI)
INTEGER(KIND=JPIM),INTENT(OUT) :: KSDITS(YDRIP%NSTART:YDRIP%NSTOP/MAX(1,NFRSDI))
INTEGER(KIND=JPIM),INTENT(OUT) :: KDHFGTS(YDRIP%NSTART:YDRIP%NSTOP/NFRDHFG)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDHFZTS(YDRIP%NSTART:YDRIP%NSTOP/NFRDHFZ)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDHFDTS(YDRIP%NSTART:YDRIP%NSTOP/NFRDHFD)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDHPTS(YDRIP%NSTART:YDRIP%NSTOP/NFRDHP)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCFUTS(YDRIP%NSTART:YDRIP%NSTOP/YDCFU%NFRCFU)
INTEGER(KIND=JPIM),INTENT(OUT) :: KXFUTS(YDRIP%NSTART:YDRIP%NSTOP/YDXFU%NFRXFU)
INTEGER(KIND=JPIM),INTENT(OUT) :: KRESTS(YDRIP%NSTART:YDRIP%NSTOP/NFRRES)
INTEGER(KIND=JPIM),INTENT(OUT) :: KMASSCONS(YDRIP%NSTART:YDRIP%NSTOP/NFRMASSCON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KRAZTS(YDRIP%NSTART:YDRIP%NSTOP/YDXFU%NFRRAZ)
END SUBROUTINE MONIO
END INTERFACE
