INTERFACE
SUBROUTINE MONVAR(YDRIP,KREFTS,KANATS,KGRATS)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMRIP , ONLY : TRIP
USE YOMVAR , ONLY : NREFTS ,NANATS ,NGRATS ,&
 & NSIMU ,NDIAG ,NFRREF ,NFRANA ,NFRGRA ,NSIM4DL 
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(OUT) :: KREFTS(0:YDRIP%NSTOP/NFRREF)
INTEGER(KIND=JPIM),INTENT(OUT) :: KANATS(0:NSIM4DL/NFRANA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KGRATS(0:NSIM4DL/NFRGRA)
END SUBROUTINE MONVAR
END INTERFACE
