INTERFACE
SUBROUTINE MOVINGA(PV,KV,KW,PVA)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KV
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KV)
INTEGER(KIND=JPIM),INTENT(IN) :: KW
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVA(KV)
END SUBROUTINE MOVINGA
END INTERFACE
