INTERFACE
SUBROUTINE MWAVE_SETUP_CMEM_PHYS(YDGP5, YD_CMEM_PHYS_FW)
USE GOM_PLUS, ONLY: TYPE_GOM_PLUS, IH
USE YOMCMEMTYPES_IFS, ONLY: CMEM_IFS_PHYS_TYPE
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
TYPE(CMEM_IFS_PHYS_TYPE), INTENT(INOUT) :: YD_CMEM_PHYS_FW(YDGP5%NDLEN)
END SUBROUTINE MWAVE_SETUP_CMEM_PHYS
END INTERFACE
