INTERFACE
SUBROUTINE MWAVE_FLUX_TO_MMR (&
 & KLEV,&
 & ksat,&
 & ldrain,&
 & pflux_fw,&
 & pcont_fw,&
 & ppres_fw,&
 & ptemp_fw,&
 & pflux_tl,&
 & pcont_tl,&
 & ppres_tl,&
 & ptemp_tl,&
 & pflux_ad,&
 & pcont_ad,&
 & ppres_ad,&
 & ptemp_ad,&
 & ldensity) 
USE PARKIND1, ONLY: JPIM, JPRB
INTEGER (KIND=JPIM), INTENT (IN) :: KLEV, KSAT
LOGICAL, INTENT (IN) :: LDRAIN
REAL (KIND=JPRB), INTENT (IN) :: PFLUX_FW(KLEV)
REAL (KIND=JPRB), INTENT (OUT) :: PCONT_FW(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (IN) :: PPRES_FW(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (IN) :: PTEMP_FW(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (IN) :: PFLUX_TL(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (OUT) :: PCONT_TL(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (IN) :: PPRES_TL(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (IN) :: PTEMP_TL(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (INOUT) :: PFLUX_AD(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (INOUT) :: PCONT_AD(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (INOUT) :: PPRES_AD(KLEV)
REAL (KIND=JPRB), OPTIONAL, INTENT (INOUT) :: PTEMP_AD(KLEV)
LOGICAL, OPTIONAL, INTENT(IN) :: LDENSITY
END SUBROUTINE MWAVE_FLUX_TO_MMR
END INTERFACE
