INTERFACE
SUBROUTINE MWAVE_DIAGS (&
 & KLEV,&
 & ksat,&
 & yd_mwave_phys,&
 & pdiag ) 
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMMWAVE, ONLY: MWAVE_PHYS_TYPE
USE PARMWAVE, ONLY: IMWAVE_RAIN_SFC, IMWAVE_SNOW_SFC,&
 & IMWAVE_TCWV, IMWAVE_TCLW, IMWAVE_TCIW, IMWAVE_RWP, IMWAVE_SWP, IMWAVE_UTH,&
 & NMWAVE_DIAG, IMWAVE_THETA700, IMWAVE_THETASFC, IMWAVE_CONV, IMWAVE_PBL 
INTEGER (KIND=JPIM), INTENT (IN) :: KLEV, KSAT
TYPE (MWAVE_PHYS_TYPE), INTENT (IN) :: YD_MWAVE_PHYS
REAL (KIND=JPRB), INTENT (INOUT) :: PDIAG(NMWAVE_DIAG)
END SUBROUTINE MWAVE_DIAGS
END INTERFACE
