INTERFACE
SUBROUTINE MWAVE_OBSOP_TEST (ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,&
 & KOBS, KLEV, KMAXCHANNELS,&
 & yd_mwave_phys_fw, yd_mwave_phys_tl, yd_mwave_rad, YDGP5, YDVARBC) 
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMMWAVE, ONLY: MWAVE_PHYS_TYPE, MWAVE_RAD_TYPE, MWAVE_ID,&
 & MWAVE_OK, MWAVE_OK_A1, MWAVE_OK_A3 
USE VARBC_CLASS, ONLY : CLASS_VARBC
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE GOM_PLUS, ONLY: TYPE_GOM_PLUS
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
INTEGER (KIND=JPIM), INTENT (IN) :: KOBS, KLEV, KMAXCHANNELS
TYPE (MWAVE_PHYS_TYPE), INTENT (IN) :: YD_MWAVE_PHYS_FW (KOBS), YD_MWAVE_PHYS_TL (KOBS)
TYPE (MWAVE_RAD_TYPE) , INTENT (IN) :: YD_MWAVE_RAD (KOBS)
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
TYPE(CLASS_VARBC), INTENT(IN) :: YDVARBC
INTEGER (KIND=JPIM), PARAMETER :: JPHYS = 3
INTEGER (KIND=JPIM), PARAMETER :: JPKS = KIND (ZZ)
END SUBROUTINE MWAVE_OBSOP_TEST
END INTERFACE
