INTERFACE
SUBROUTINE MWAVE_WRAPPER (ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,&
 & YDGP5, YDVARBC, YDGP_TL, YDGP_AD, LDSCREEN, KSET ) 
USE PARKIND1, ONLY: JPIM, JPRB
USE GOM_PLUS, ONLY: TYPE_GOM_PLUS, IH
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE VARBC_CLASS, ONLY : CLASS_VARBC
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
TYPE(CLASS_VARBC), INTENT(IN) :: YDVARBC
TYPE(TYPE_GOM_PLUS), INTENT(IN), OPTIONAL :: YDGP_TL
TYPE(TYPE_GOM_PLUS), INTENT(INOUT), OPTIONAL :: YDGP_AD
LOGICAL, INTENT(IN), OPTIONAL :: LDSCREEN
INTEGER (KIND=JPIM), INTENT(IN), OPTIONAL :: KSET
END SUBROUTINE MWAVE_WRAPPER
END INTERFACE
