INTERFACE
SUBROUTINE MWAVE_ASSIGN_EMIS_ATMS ( KSAT, KCHAN, LDSEAICE, PEMIS_MIN, PDEMIS, KMAP)
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMMWAVE, ONLY: MWAVE_ID
INTEGER (KIND=JPIM), INTENT (IN) :: KSAT, KCHAN
LOGICAL, INTENT (IN) :: LDSEAICE
REAL (KIND=JPRB), INTENT (OUT) :: PEMIS_MIN(KCHAN)
REAL (KIND=JPRB), INTENT (OUT) :: PDEMIS(KCHAN)
INTEGER(KIND=JPIM), INTENT (OUT) :: KMAP(KCHAN)
END SUBROUTINE MWAVE_ASSIGN_EMIS_ATMS
END INTERFACE
