INTERFACE
SUBROUTINE MWAVE_SCREEN (ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,&
 & KOBS, KLEV, KMAXCHANNELS,&
 & yd_mwave_phys, yd_mwave_rad, YDGP5, YDVARBC, YD_CMEM_PHYS) 
USE PARKIND1, ONLY: JPIM, JPRB
USE VARBC_CLASS, ONLY : CLASS_VARBC
USE YOMMWAVE, ONLY: MWAVE_ID, RLIMIT_LAT, MWAVE_PHYS_TYPE, MWAVE_RAD_TYPE,&
 & MWAVE_MISSING,&
 & MWAVE_OBS_TB, MWAVE_TSFC, MWAVE_LAND, MWAVE_OCEAN, MWAVE_COAST,&
 & MWAVE_IFS_SEA_ICE, MWAVE_LATITUDE, MWAVE_ACTIVE, MWAVE_OROG, MWAVE_TAU,&
 & MWAVE_OK, MWAVE_SEA_ICE_ASSIM, MWAVE_SNOW_ASSIM, MWAVE_THINNED,&
 & MWAVE_MISSING_TB, MWAVE_CLEAR_SKY, LDMWAVE_LAND,&
 & MWAVE_CHAN_IMAGER, MWAVE_CHAN_TROP, LUSE_TAU_SCREENING,&
 & CPROX_TYPE_P37, CPROX_TYPE_SI, CPROX_TYPE_LWP,&
 & NTHIN_LAT, NTHIN_LON, YTHIN_GRID 
USE GOM_PLUS, ONLY: TYPE_GOM_PLUS
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE YOMCMEMTYPES_IFS, ONLY: CMEM_IFS_PHYS_TYPE, CMEM_IFS_RAD_TYPE
TYPE(IFS_DBASE_VIEW), INTENT (INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
INTEGER (KIND=JPIM), INTENT (IN) :: KOBS, KLEV, KMAXCHANNELS
TYPE(MWAVE_PHYS_TYPE), INTENT (INOUT) :: YD_MWAVE_PHYS (KOBS)
TYPE(MWAVE_RAD_TYPE) , INTENT (INOUT) :: YD_MWAVE_RAD (:)
TYPE(TYPE_GOM_PLUS), INTENT (IN) :: YDGP5
TYPE(CLASS_VARBC), INTENT (IN) :: YDVARBC
TYPE(CMEM_IFS_PHYS_TYPE), INTENT (INOUT) :: YD_CMEM_PHYS(KOBS)
END SUBROUTINE MWAVE_SCREEN
END INTERFACE
