INTERFACE
SUBROUTINE MWAVE_READ_SAT_ERROR(YD_MWAVEID, KFILE_ID)
USE PARKIND1 , ONLY: JPIM, JPRB
USE YOMMWAVE , ONLY: MWAVE_IDS, RSPLIT_OBS_ERR
TYPE (MWAVE_IDS), INTENT(INOUT) :: YD_MWAVEID
INTEGER(KIND=JPIM), OPTIONAL, INTENT (IN) :: KFILE_ID
END SUBROUTINE MWAVE_READ_SAT_ERROR
END INTERFACE
