INTERFACE
SUBROUTINE MWAVE_EMIS (ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,&
 & KOBS, KLEV, KMAXCHANNELS,&
 & yd_mwave_phys_fw, yd_mwave_rad, YDGP5, YDVARBC) 
USE PARKIND1, ONLY: JPIM, JPRB
USE VARBC_CLASS, ONLY : CLASS_VARBC
USE YOMMWAVE, ONLY: MWAVE_PHYS_TYPE, MWAVE_RAD_TYPE, MWAVE_ID,&
 & MWAVE_LAND, MWAVE_SERIOUS, IDEMIS_ASSIGN, MWAVE_EM_RET_FAILURE, MWAVE_TAU,&
 & EMIS_FROM_ATLAS, EMIS_FROM_RETRIEVAL_AND_ATLAS,&
 & MWAVE_SEA_ICE_ASSIM, MWAVE_SNOW_ASSIM, MWAVE_CHAN_MIDATMOS 
USE GOM_PLUS, ONLY: TYPE_GOM_PLUS
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
INTEGER (KIND=JPIM), INTENT (IN) :: KOBS, KLEV, KMAXCHANNELS
TYPE (MWAVE_PHYS_TYPE), INTENT (INOUT) :: YD_MWAVE_PHYS_FW (KOBS)
TYPE (MWAVE_RAD_TYPE) , INTENT (INOUT) :: YD_MWAVE_RAD (KOBS)
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
TYPE(CLASS_VARBC), INTENT(IN) :: YDVARBC
END SUBROUTINE MWAVE_EMIS
END INTERFACE
