INTERFACE
SUBROUTINE MWAVE_SETUP (KNPROC, KMYPROC, KERROR, KFILE_ID, KSATGRP_DIM, KNRTCHANNELS)
USE PARKIND1, ONLY: JPIM, JPRB
INTEGER (KIND=JPIM), INTENT ( IN) :: KMYPROC
INTEGER (KIND=JPIM), INTENT ( IN) :: KNPROC
INTEGER (KIND=JPIM), INTENT ( IN) :: KFILE_ID
INTEGER (KIND=JPIM), INTENT ( IN) :: KSATGRP_DIM
INTEGER (KIND=JPIM), INTENT ( IN) :: KNRTCHANNELS(KSATGRP_DIM)
INTEGER (KIND=JPIM), INTENT (OUT) :: KERROR
END SUBROUTINE MWAVE_SETUP
END INTERFACE
