INTERFACE
SUBROUTINE MWAVE_CPFRAC (&
 & KLEV,&
 & ksat,&
 & yd_mwave_phys_fw,&
 & pcfrac_fw,&
 & yd_mwave_phys_tl,&
 & pcfrac_tl,&
 & yd_mwave_phys_ad,&
 & pcfrac_ad ) 
USE PARKIND1, ONLY: JPIM, JPRB
USE YOMMWAVE, ONLY: MWAVE_PHYS_TYPE
INTEGER (KIND=JPIM), INTENT (IN) :: KLEV, KSAT
TYPE (MWAVE_PHYS_TYPE), INTENT (IN) :: YD_MWAVE_PHYS_FW
REAL (KIND=JPRB), INTENT (OUT) :: PCFRAC_FW
TYPE (MWAVE_PHYS_TYPE), OPTIONAL, INTENT(IN) :: YD_MWAVE_PHYS_TL
TYPE (MWAVE_PHYS_TYPE), OPTIONAL, INTENT(INOUT) :: YD_MWAVE_PHYS_AD
REAL (KIND=JPRB), OPTIONAL, INTENT(OUT) :: PCFRAC_TL
REAL (KIND=JPRB), OPTIONAL, INTENT(INOUT) :: PCFRAC_AD
END SUBROUTINE MWAVE_CPFRAC
END INTERFACE
