INTERFACE
SUBROUTINE MWAVE_PUT_TL(ROBHDR,ROBODY,SATBODY,&
 & KLEN, YD_MWAVE_RAD) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE YOMMWAVE , ONLY : N_SATSENS, MWAVE_ID, MWAVE_OK,&
 & MWAVE_REJECTOBS,MWAVE_RAD_TYPE 
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATBODY
TYPE(MWAVE_RAD_TYPE), INTENT(INOUT) :: YD_MWAVE_RAD (:)
INTEGER(KIND=JPIM), INTENT(IN) :: KLEN
END SUBROUTINE MWAVE_PUT_TL
END INTERFACE
