INTERFACE
SUBROUTINE N2O_J_INTERP(PSZA,PZKM,PO3_OVER, KDISS, PAJVAL )
USE PARKIND1 , ONLY : JPIM ,JPRB
REAL(KIND=JPRB),INTENT(IN) :: PSZA
REAL(KIND=JPRB),INTENT(IN) :: PZKM
REAL(KIND=JPRB),INTENT(IN) :: PO3_OVER
INTEGER(KIND=JPIM),INTENT(IN) :: KDISS(2)
REAL(KIND=JPRB),INTENT(out) :: PAJVAL(2)
END SUBROUTINE N2O_J_INTERP
END INTERFACE
