INTERFACE
SUBROUTINE NEWFA(KNBARP,CDNMCA,KUNTIN,CDFN,LDIMST,KNIMES,CDIDEN,KDATE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KNBARP
CHARACTER(LEN=*) ,INTENT(IN) :: CDNMCA
INTEGER(KIND=JPIM),INTENT(IN) :: KUNTIN
CHARACTER(LEN=*) ,INTENT(IN) :: CDFN
LOGICAL ,INTENT(IN) :: LDIMST
INTEGER(KIND=JPIM),INTENT(IN) :: KNIMES
CHARACTER(LEN=*) ,INTENT(IN) :: CDIDEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDATE(:)
END SUBROUTINE NEWFA
END INTERFACE
