INTERFACE
SUBROUTINE NGEDSTA(KOBODY,KCOUNT,KDSTA)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(IN) :: KOBODY
INTEGER(KIND=JPIM),INTENT(OUT) :: KCOUNT
INTEGER(KIND=JPIM),INTENT(OUT) :: KDSTA(4)
END SUBROUTINE NGEDSTA
END INTERFACE
