INTERFACE
SUBROUTINE NGEDEVE(KDEVEN1,KEVENT,KLIST)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE PARCMA , ONLY : JPMXDE1
INTEGER(KIND=JPIM),INTENT(IN) :: KDEVEN1
INTEGER(KIND=JPIM),INTENT(OUT) :: KEVENT
INTEGER(KIND=JPIM),INTENT(OUT) :: KLIST(JPMXDE1)
END SUBROUTINE NGEDEVE
END INTERFACE
