INTERFACE
SUBROUTINE NGEREVE2(ROBHDR,ROBODY,KREVEN2,KOBTYP,KCDTYP,KREPEV2)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE PARCMA , ONLY : JPMXRE2
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KREVEN2, KOBTYP, KCDTYP
INTEGER(KIND=JPIM),INTENT(OUT) :: KREPEV2(JPMXRE2)
END SUBROUTINE NGEREVE2
END INTERFACE
