INTERFACE
SUBROUTINE NOCLOUD(YDECLDP,KDIM,&
 & FLUX, PDIAG, tendency_loc) 
USE YOECLDP , ONLY : TECLDP, NCLDQR, NCLDQS, NCLDQI, NCLDQL
USE YOMPHYDER, ONLY : DIMENSION_TYPE, FLUX_TYPE, STATE_TYPE, MASK_GFL_TYPE,&
 & AUX_DIAG_TYPE 
TYPE(TECLDP) , INTENT(INOUT) :: YDECLDP
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY_LOC
END SUBROUTINE NOCLOUD
END INTERFACE
