INTERFACE
SUBROUTINE NOCONVECTION(YDEPHY,KDIM,&
 & FLUX, LLKEYS, PDIAG) 
USE YOMPHYDER, ONLY : DIMENSION_TYPE, AUX_DIAG_TYPE,&
 & KEYS_LOCAL_TYPE, FLUX_TYPE 
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (KEYS_LOCAL_TYPE) , INTENT(INOUT) :: LLKEYS
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
END SUBROUTINE NOCONVECTION
END INTERFACE
