INTERFACE
SUBROUTINE NOMFI(CDPREF,CDSUFF,CDNOM)
CHARACTER(LEN=*) ,INTENT(IN) :: CDPREF
CHARACTER(LEN=*) ,INTENT(IN) :: CDSUFF
CHARACTER(LEN=*) ,INTENT(INOUT) :: CDNOM
END SUBROUTINE NOMFI
END INTERFACE
