INTERFACE
SUBROUTINE NOSURFTSTP(KDIM,&
 & FLUX, PDDHS) 
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, FLUX_TYPE, DDH_SURF_TYPE
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (DDH_SURF_TYPE) , INTENT(INOUT) :: PDDHS
END SUBROUTINE NOSURFTSTP
END INTERFACE
