INTERFACE
SUBROUTINE NOTURBULENCE(YDSURF,KDIM,&
 & PDIAG,FLUX,PSURF,SURFL,AUXL,PDDHS,TENDENCY_VDF) 
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE,&
 & FLUX_TYPE,SURF_AND_MORE_TYPE,SURF_AND_MORE_LOCAL_TYPE,DDH_SURF_TYPE 
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: SURFL
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
TYPE (DDH_SURF_TYPE) , INTENT(INOUT) :: PDDHS
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY_VDF
END SUBROUTINE NOTURBULENCE
END INTERFACE
