INTERFACE
SUBROUTINE O2E_INITLONG(KCOBTYP, KCCDTYP, KHEADER, KHEADERL, KBODYEL)
USE PARKIND1 ,ONLY : JPIM ,JPRD
USE YOMCMA, ONLY : NO1DVSLV, NO1DVLV, NO1DVVA, NO1DVSLVA, NO1DVLVA,&
 & NO1DVVAA, NRESUPD , NODEPT, NMXCRL 
INTEGER(KIND=JPIM), INTENT(IN) :: KCOBTYP, KCCDTYP
INTEGER(KIND=JPIM), INTENT(OUT) :: KHEADER(NMXCRL), KHEADERL, KBODYEL
END
END INTERFACE
