INTERFACE
SUBROUTINE OBADAT(YDGEOMETRY,KWINLEN,YDODB,CD_DBNAME)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMOBS
USE YOMMKODB
USE YOMCMA
USE YOMCMDDR
USE YOMANCS
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN):: KWINLEN
CLASS(DBASE), INTENT(OUT) :: YDODB
CHARACTER(LEN=*),OPTIONAL,INTENT(IN) :: CD_DBNAME
END SUBROUTINE OBADAT
END INTERFACE
