INTERFACE
SUBROUTINE OBATABS(YDGEOMETRY,KTSLOTNO,&
 & KOBTOT ,KOBTOV ,KOBNTV ,KOBSCA ,&
 & KOFFTOT,KOFFTOV,KOFFNTV,KOFFSCA,YDODB) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMDB
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KTSLOTNO
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTOT
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTOV
INTEGER(KIND=JPIM),INTENT(IN) :: KOBNTV
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSCA
INTEGER(KIND=JPIM),INTENT(IN) :: KOFFTOT
INTEGER(KIND=JPIM),INTENT(IN) :: KOFFTOV
INTEGER(KIND=JPIM),INTENT(IN) :: KOFFNTV
INTEGER(KIND=JPIM),INTENT(IN) :: KOFFSCA
CLASS(DBASE),INTENT(INOUT) :: YDODB
END SUBROUTINE OBATABS
END INTERFACE
