INTERFACE
SUBROUTINE OBINSSP(PLAT ,PLON,&
 & KOBTYP ,KCDTYP ,KOTMAP ,KOCMAP ,&
 & KSTID ,KPHASE ,KCHAN ,KINS ,KDPT,&
 & KINSPEC,KINSTP ) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT
REAL(KIND=JPRB) ,INTENT(IN) :: PLON
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KCDTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KOTMAP
INTEGER(KIND=JPIM),INTENT(IN) :: KOCMAP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTID
INTEGER(KIND=JPIM),INTENT(INOUT) :: KPHASE
INTEGER(KIND=JPIM),INTENT(IN) :: KCHAN
INTEGER(KIND=JPIM),INTENT(IN) :: KINS
INTEGER(KIND=JPIM),INTENT(IN) :: KDPT
INTEGER(KIND=JPIM),INTENT(INOUT) :: KINSPEC
INTEGER(KIND=JPIM),INTENT(OUT) :: KINSTP
END SUBROUTINE OBINSSP
END INTERFACE
