INTERFACE
SUBROUTINE OBSOP_CONV(ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,SCATTBODY,YDGP5,VARNOS_TO_PROCESS,LDSCREEN,&
 & LDFINAL,YDPHY,YDSET,PHOFX,YDGP_TL,YDGP_AD) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMDB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
USE IFS_DBASE_VIEW_MOD , ONLY : IFS_DBASE_VIEW
USE OBSOP_SETS , ONLY : TYPE_SET_INFO
USE YOMPHY , ONLY : TPHY
TYPE(IFS_DBASE_VIEW) , INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,SCATTBODY
TYPE(TYPE_GOM_PLUS) , INTENT(IN) :: YDGP5
INTEGER(KIND=JPIM) , INTENT(INOUT) :: VARNOS_TO_PROCESS(:,:)
LOGICAL , INTENT(IN) :: LDSCREEN
LOGICAL , INTENT(IN) :: LDFINAL
TYPE(TPHY) , INTENT(IN) :: YDPHY
TYPE(TYPE_SET_INFO) , INTENT(IN) :: YDSET
REAL(KIND=JPRB) , INTENT(INOUT) :: PHOFX(YDGP5%NDLEN,YDSET%MXBDY)
TYPE(TYPE_GOM_PLUS) , INTENT(IN) , OPTIONAL :: YDGP_TL
TYPE(TYPE_GOM_PLUS) , INTENT(INOUT), OPTIONAL :: YDGP_AD
END SUBROUTINE OBSOP_CONV
END INTERFACE
