INTERFACE
SUBROUTINE OBSOP_VARBC(ROBHDR,ROBODY,&
 & YDVARBC,YDGP5,KDBDY,PHOFX,YDVARBC_PRED,LDRSONDE_BODY,LD_MWAVE,PVERTP,PBIAS,PNDBIAS,KSET,&
 & LDTL,LDAD,LDCVARBC_ONLY) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS
USE VARBC_CLASS, ONLY : CLASS_VARBC
USE VARBC_PRED, ONLY : TYPE_VARBC_PRED
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
CLASS(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
INTEGER(KIND=JPIM), INTENT(IN) :: KDBDY
REAL(KIND=JPRB), INTENT(IN) :: PHOFX(YDGP5%NDLEN,KDBDY)
TYPE(TYPE_VARBC_PRED), INTENT(IN) :: YDVARBC_PRED
LOGICAL, INTENT(IN) :: LDRSONDE_BODY, LD_MWAVE
REAL(KIND=JPRD), INTENT(IN) :: PVERTP(YDGP5%NDLEN,KDBDY)
REAL(KIND=JPRB), INTENT(INOUT) :: PBIAS(YDGP5%NDLEN,KDBDY)
REAL(KIND=JPRB), INTENT(INOUT) :: PNDBIAS(YDGP5%NDLEN,KDBDY)
INTEGER(KIND=JPIM), INTENT(IN):: KSET
LOGICAL, INTENT(IN), OPTIONAL :: LDTL
LOGICAL, INTENT(IN), OPTIONAL :: LDAD
LOGICAL, INTENT(IN), OPTIONAL :: LDCVARBC_ONLY
END SUBROUTINE OBSOP_VARBC
END INTERFACE
