INTERFACE
SUBROUTINE OBSOP_RAD(ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,YDGP5,YDTCV5,KVARNOS_TO_PROCESS,LDSCREEN,&
 & LDFINAL,YDSET,PHOFX,YDJOT,YDVARBC,YDGP_TL,YDGP_AD,YDTCV_TL,YDTCV_AD) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE TOVSCV_MOD,ONLY : TOVSCV
USE VARBC_CLASS, ONLY : CLASS_VARBC
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY: TYPE_SET_INFO
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
INTEGER(KIND=JPIM), INTENT(INOUT) :: KVARNOS_TO_PROCESS(:,:)
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
TYPE(TOVSCV), INTENT(IN) :: YDTCV5
LOGICAL, INTENT(IN) :: LDSCREEN
LOGICAL, INTENT(IN) :: LDFINAL
TYPE(TYPE_SET_INFO), INTENT(IN) :: YDSET
REAL(KIND=JPRB), INTENT(INOUT) :: PHOFX(YDGP5%NDLEN,YDSET%MXBDY)
TYPE(JO_TABLE), INTENT(IN) :: YDJOT
CLASS(CLASS_VARBC), INTENT(IN) :: YDVARBC
TYPE(TYPE_GOM_PLUS), INTENT(IN), OPTIONAL :: YDGP_TL
TYPE(TYPE_GOM_PLUS), INTENT(INOUT), OPTIONAL :: YDGP_AD
TYPE(TOVSCV), INTENT(IN), OPTIONAL :: YDTCV_TL
TYPE(TOVSCV), INTENT(INOUT), OPTIONAL :: YDTCV_AD
END SUBROUTINE OBSOP_RAD
END INTERFACE
