INTERFACE
SUBROUTINE OBSOP_RADAR(ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU,YDGP5,VARNOS_TO_PROCESS,LDSCREEN,&
 & YDSET,PHOFX,YDGP_TL,YDGP_AD) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS,IH
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY: TYPE_SET_INFO
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATHDR,SATBODY,ROBSU
INTEGER(KIND=JPIM), INTENT(IN) :: VARNOS_TO_PROCESS(:,:)
TYPE(TYPE_GOM_PLUS), INTENT(IN) :: YDGP5
LOGICAL, INTENT(IN) :: LDSCREEN
TYPE(TYPE_SET_INFO) ,INTENT(IN) :: YDSET
REAL(KIND=JPRB), INTENT(INOUT) :: PHOFX(YDGP5%NDLEN,YDSET%MXBDY)
TYPE(TYPE_GOM_PLUS), INTENT(IN), OPTIONAL :: YDGP_TL
TYPE(TYPE_GOM_PLUS), INTENT(INOUT), OPTIONAL :: YDGP_AD
END SUBROUTINE OBSOP_RADAR
END INTERFACE
