INTERFACE
SUBROUTINE OBSOP_VARNO_SUBSET(KVNMRQ,KDLEN,KMXBDY,KVNM,KCOUNT,KMXCOUNT,KPNLV)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KVNMRQ(KDLEN,KMXBDY)
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KMXBDY
INTEGER(KIND=JPIM),INTENT(IN) :: KVNM
INTEGER(KIND=JPIM),INTENT(OUT) :: KCOUNT(KDLEN)
INTEGER(KIND=JPIM),INTENT(OUT) :: KMXCOUNT
INTEGER(KIND=JPIM),INTENT(OUT) :: KPNLV(KDLEN,KMXBDY)
END SUBROUTINE OBSOP_VARNO_SUBSET
END INTERFACE
