INTERFACE
SUBROUTINE OBSPREP(YDGEOMETRY,KSLOT,YDODB)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KSLOT
CLASS(DBASE),INTENT(INOUT) :: YDODB
END SUBROUTINE OBSPREP
END INTERFACE
