INTERFACE
SUBROUTINE OBSVTL(YDEPHY,YDML_PHY_MF,YDJOT,YDVARBC,YDTCV5,YDGOM,YDTCV,YDGOM5,YDODB,KSLOT)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOEPHY , ONLY : TEPHY
USE PARKIND1 , ONLY : JPIM, JPRB
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_MOD , ONLY : TOVSCV
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE DBASE_MOD , ONLY : DBASE
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT) :: YDML_PHY_MF
TYPE(JO_TABLE) ,INTENT(INOUT) :: YDJOT
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(IN) :: YDTCV5
TYPE(CLASS_SUPERGOM) ,INTENT(IN) :: YDGOM5
TYPE(CLASS_SUPERGOM) ,INTENT(IN) :: YDGOM
TYPE(TOVSCV) ,INTENT(IN) :: YDTCV
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSLOT
END SUBROUTINE OBSVTL
END INTERFACE
