INTERFACE
SUBROUTINE OPDIS(CDCONF,CDCALLER,PCP,PVCP,PRT,PACP,PART,KSTEP)
USE PARKIND1 , ONLY : JPIM, JPRB, JPIB, JPRD
CHARACTER(LEN=9) ,INTENT(IN) :: CDCONF
CHARACTER(LEN=*) ,INTENT(IN) :: CDCALLER
REAL(KIND=JPRD) ,INTENT(IN) :: PCP
REAL(KIND=JPRD) ,INTENT(IN) :: PVCP
REAL(KIND=JPRD) ,INTENT(IN) :: PRT
REAL(KIND=JPRD) ,INTENT(IN) :: PACP
REAL(KIND=JPRD) ,INTENT(IN) :: PART
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
END SUBROUTINE OPDIS
END INTERFACE
