INTERFACE
SUBROUTINE OPENFA (YDGEOMETRY,YDRIP,KFILE, KUNTIN, YDML_LBC, KDEB2, KFIN, KINDEX,&
 & KDATE, CDFILE, CDNOMC, KINITMONTH) 
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB, JPRD
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) , INTENT(IN), TARGET :: YDGEOMETRY
TYPE(TRIP) , INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM), INTENT(IN) :: KFILE
INTEGER(KIND=JPIM), INTENT(OUT) :: KUNTIN
TYPE(TELBC_MODEL) , INTENT(IN), OPTIONAL :: YDML_LBC
INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KDEB2
INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KFIN
INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KINDEX
INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KDATE(11)
CHARACTER(LEN=*) , INTENT(IN), OPTIONAL :: CDFILE
CHARACTER(LEN=*) , INTENT(OUT), OPTIONAL :: CDNOMC
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KINITMONTH
END SUBROUTINE OPENFA
END INTERFACE
