INTERFACE
SUBROUTINE OPK_OBSCOR(YDGEOMETRY,YDRIP,KNUMOBS,PX,PY)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KNUMOBS
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KNUMOBS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PY(KNUMOBS)
END SUBROUTINE OPK_OBSCOR
END INTERFACE
