INTERFACE
SUBROUTINE OPM_OBSCOR(KSIZE,PX,PY)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KSIZE
REAL(KIND=JPRB), INTENT(IN) :: PX(KSIZE)
REAL(KIND=JPRB), INTENT(OUT) :: PY(KSIZE)
END SUBROUTINE OPM_OBSCOR
END INTERFACE
