INTERFACE
SUBROUTINE ORTHNORM (PVECS,KLEN,KVECS)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KVECS
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVECS(KLEN,KVECS)
END SUBROUTINE ORTHNORM
END INTERFACE
