INTERFACE
SUBROUTINE PFIXER(YDGEOMETRY,YDGMV,YGFL,YDDYN,PSURF0,PSURF1,PGMVT1S)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM , JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
REAL(KIND=JPRB) ,INTENT(IN) :: PSURF0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSURF1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEOMETRY%YRDIM%NGPBLKS)
END SUBROUTINE PFIXER
END INTERFACE
