INTERFACE
SUBROUTINE PHYS_NL (YDTHF,YDCST,YDERAD,YDML_PHY_SLIN,YDML_PHY_EC,YDRIP,KLEV, KLON, PVDIFTS,&
 & PT ,&
 & PQ ,&
 & PP ,&
 & PPH ,&
 & PTENT ,&
 & PTENQ ,&
 & PDIFTS ,&
 & PDIFTQ ,&
 & PSTRTU ,&
 & PSTRTV ,&
 & PRAIN3D ,&
 & PSNOW3D ,&
 & PDQL ,&
 & PDQI ,&
 & PDCC ,&
 & PFLS ,&
 & PFLC) 
USE MODEL_PHYSICS_ECMWF_MOD , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD , ONLY : TERAD
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
USE YOMCST , ONLY : TCST
USE YOETHF , ONLY : TTHF
TYPE(TTHF) ,INTENT(IN) :: YDTHF
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(MODEL_PHYSICS_ECMWF_TYPE) ,INTENT(INOUT) :: YDML_PHY_EC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT) :: YDML_PHY_SLIN
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER (KIND=JPIM), INTENT ( IN) :: KLEV, KLON
REAL(KIND=JPRB) ,INTENT (IN) :: PVDIFTS
REAL (KIND=JPRB), INTENT ( IN), DIMENSION (KLON,KLEV) :: PP, PT, PQ
REAL (KIND=JPRB), INTENT ( IN), DIMENSION (KLON,KLEV+1) :: PPH
REAL (KIND=JPRB), INTENT (INOUT), DIMENSION (KLON,KLEV) :: PTENQ, PTENT
REAL (KIND=JPRB), INTENT ( IN), DIMENSION (KLON) :: PDIFTS, PDIFTQ, PSTRTU, PSTRTV
REAL (KIND=JPRB), INTENT (OUT), DIMENSION (KLON,KLEV) :: PRAIN3D, PSNOW3D
REAL (KIND=JPRB), INTENT (OUT), DIMENSION (KLON,KLEV) :: PDQL, PDQI, PDCC
REAL (KIND=JPRB), INTENT (OUT), DIMENSION (KLON) :: PFLS, PFLC
END SUBROUTINE PHYS_NL
END INTERFACE
