INTERFACE
SUBROUTINE PKGRIDA(YDGEOMETRY,KFIELDS,KBIT,PGP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM), INTENT(IN) :: KBIT(KFIELDS)
REAL(KIND=JPRB), INTENT(INOUT) :: PGP(YDGEOMETRY%YRGEM%NGPTOT,KFIELDS)
END SUBROUTINE PKGRIDA
END INTERFACE
