INTERFACE
SUBROUTINE POSCT(KNOIR,PTIMTR,PLON,PLAT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KNOIR
REAL(KIND=JPRB) ,INTENT(IN) :: PTIMTR
REAL(KIND=JPRB) ,INTENT(OUT) :: PLON
REAL(KIND=JPRB) ,INTENT(OUT) :: PLAT
END SUBROUTINE POSCT
END INTERFACE
