INTERFACE
SUBROUTINE POSDDH(YDDIMV,YDSURF,YDML_DIAG,YDDPHY,YDML_GCONF,YDPHY)
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDPHY , ONLY : TDPHY
USE YOMPHY , ONLY : TPHY
USE YOMDIMV , ONLY : TDIMV
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TDPHY), INTENT(IN) :: YDDPHY
TYPE(MODEL_DIAGNOSTICS_TYPE) ,INTENT(INOUT):: YDML_DIAG
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
TYPE(TPHY) , INTENT(INOUT) :: YDPHY
END SUBROUTINE POSDDH
END INTERFACE
