INTERFACE
SUBROUTINE POST_THINNER(ROBHDR,ROBODY,KLEN,CD_MODE,&
 & KOBSTYPE_RQ,KCDTYPE_RQ,KSENSOR_RQ,KVNM_RQ) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE YOMOBS
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
CHARACTER(LEN=*) ,INTENT(IN) :: CD_MODE
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSTYPE_RQ
INTEGER(KIND=JPIM),INTENT(IN) :: KCDTYPE_RQ
INTEGER(KIND=JPIM),INTENT(IN) :: KSENSOR_RQ
INTEGER(KIND=JPIM),INTENT(IN) :: KVNM_RQ
END SUBROUTINE POST_THINNER
END INTERFACE
