INTERFACE
SUBROUTINE POSTPHY(YDGEOMETRY,YDSURF,YDMODEL,KPROMA ,KST ,KEND ,KFLEVG ,&
 & LDFSTEP,LDMLPP, LDRS6, LDACCRS,&
 & KLEVS ,KLEVXP ,KFLDXP ,KSATSIM,KSTGLO,KLEVSN,&
 & KFLDXP2,KLEVO ,PDTPHY,&
 & PUT9,PVT9,PTT9,PGFL,PAERODDF,PTENQ,&
 & PDELP9 ,PDIFTQ ,PDIFCQ ,PDIFTS ,PDIFCS,&
 & PFRSO ,PFRSOD ,PFRSODC,PFRTH ,PFRTHD ,PFRTHDC,PUVDF ,PPARF ,&
 & PCAPE ,PPARCF ,PTINCF ,PFDIR ,PDSRP ,PCDIR,&
 & PCBASE ,P0DEGL ,PVISIH ,PCIN ,PCONVIND,&
 & PLIGH_TOT ,PLIGH_CTG,&
 & PCBASEA,PCTOPC ,PZTWETB,&
 & PFHPCL ,PFHPCN ,PFHPSL ,PFHPSN ,PFPLCL,&
 & PFPLCN ,PFPLSL ,PFPLSN ,PSTRCU ,PSTRCV ,PSTRDU ,PSTRDV,&
 & PFCCQN ,PFCCQL ,PFCSQN ,PFCSQL ,PFCQLNG,&
 & PFCQNNG,PFSQRF, PFSQSF , PFCQRNG, PFCQSNG,PFSQLTUR, PFSQITUR ,&
 & PSTRTU ,PSTRTV ,&
 & POROG ,PENES ,PFEVN,&
 & PGESLO ,PGECLO ,PVFLSM ,PVFCI,&
 & PINEE ,PIGPP ,PIREC,&
 & PVDZ0F,&
 & PTSAE1 ,PTLE1 ,PWSAE1,&
 & PISAE1,&
 & PWLE1 ,PSNSE1,PWSNE1,&
 & PASNE1 ,PRSNE1 ,PTSNE1,&
 & PTLICEE1, PTLMNWE1,&
 & PTLWMLE1, PTLBOTE1,&
 & PTLSFE1 ,&
 & PHLICEE1, PHLMLE1,&
 & PEXTRE1,PXTR2E1,PEVAPMU,&
 & PUOE1 ,PVOE1 ,PTOE1 ,PSOE1,&
 & PFSNNU1,PWSNU1,&
 & PASNU1 ,PRSNU1 ,PTSNU1,&
 & PTSLNU1,PWRENU1,PTRENU1,PQLINU1,&
 & PTILINU1,&
 & PTLICNU1, PTLMNNU1,&
 & PTLMLNU1, PTLBTNU1,&
 & PTLSFNU1,&
 & PHLICNU1, PHLMNU1,&
 & PEXTRP1,PXTRP21,&
 & PUO1 ,PVO1 ,PTO1 ,PSO1,&
 & PRE9 ,PRE9F ,&
 & PWRENU0,PFCLL ,PFCLN,&
 & PTRENU0,PQLINU0,&
 & PTCLS,&
 & PQCLS ,PISUND ,PVDBLH ,PVDSUND,&
 & PITTRC ,PITSRC ,PISTRC ,PISSRC ,PI10FG, PI10FGCV, PILSPF, PPRECTYPE, PFZRA,&
 & PVTTRC ,PVTSRC ,PVSTRC ,PVSSRC ,PVES, PVSMLT, PV10FG, PV10FG6, PVI10FG,&
 & PVLSPF ,PVVIMD ,&
 & PUCLS ,PVCLS ,PVDLZ0H,PVDALB,&
 & PVLCC ,PVMCC ,PVHCC ,PVTCC,&
 & PVDIS ,PVDISG ,PUSTRG,&
 & PVSTRG ,PRUISS,&
 & PVDLSP ,PVDCP ,PVDSF ,PVDFZRA,PVDBLD ,PVDSSHF,PVDSLHF,PVDSP,PVDMSL,&
 & PVDSSR ,PVDSTR ,PVDSSRD,PVDSTRD,PVDSSRDC,PVDSTRDC,&
 & PVDTSR ,PVDTTR ,PVDUVDF,PVDPARF,PVDCAPE ,PVDCAPES,PVDMXCAP6,PVDMXCAPS6,&
 & PVDPARCF, PVDTINCF, PVDFDIR, PVDDSRP, PVDCDIR,&
 & PVCBASE,PV0DEGL,PVVISIH,PVCIN ,PVKINDEX,PVTTINDEX,&
 & PVCBASEA,PVCTOPC,PVZTWETB0, PVZTWETB1,&
 & PVDIEWSS,PVDINSSS,&
 & PVDEWSS,PVDNSSS,PVDE ,PVDPEV ,PVDLGWS,PVDISSHF,PVDIE,PVDVIWVE,PVDVIWVN,&
 & PVDTCW ,PVDTCWV,PVDTCLW,PVDTCIW,PVDTCRW,PVDTCSW,PVDTCSLW,&
 & PVDMGWS,PVDGWD ,PVDMX2T,PVDMN2T,PVDMX2T6,PVDMN2T6,&
 & PVDRO,PVDSSRO,PVDSRO,PVDCSF,PVDLSSF,&
 & PVDMXTPR,PVDMNTPR,PVDMXTPR6,PVDMNTPR6,&
 & PVDTPR ,PVDLSRR,PVDCRR ,PVDLSSFR,PVDCSFR,PVDPTYPE,PVILSPF,&
 & PVDTCO3,PVDNEE ,PVDGPP ,PVDREC,&
 & PVDLITOTI,PVDLITOTA6,PVDLICGI,PVDLICGA6,&
 & PSMCLBT,PSMCSBT,&
 & PVDTCAERO,PVDAEROF,PVDTCGHG,PVDTCCHEM,GSD_VF,&
 & PGNORDL,PGNORDM,PGEMU ,PGSQM2 ,PGELAM ,PGELAT ,PGAW ,PFCQNG ,&
 & PFONTE ,PRUISP ,PDHTLS ,PDHTSS ,PDHTTS ,PDHTIS ,PDHSSS ,PDHIIS,&
 & PDHWLS ,PDHFSS) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE SURFACE_VIEWS_MODULE, ONLY: SURFACE_VIEW_GROUP_VARSF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOE_AERODIAG , ONLY : NPAERODIAG
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVSN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVXP
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVO
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDXP
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDXP2
INTEGER(KIND=JPIM),INTENT(IN) :: KSATSIM
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
LOGICAL ,INTENT(IN) :: LDFSTEP
LOGICAL ,INTENT(IN) :: LDMLPP
LOGICAL ,INTENT(IN) :: LDRS6
LOGICAL ,INTENT(IN) :: LDACCRS
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PDTPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PUT9(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PVT9(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTT9(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(KPROMA,KFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERODDF(KPROMA,YDMODEL%YRML_GCONF%YGFL%NACTAERO,NPAERODIAG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENQ(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELP9(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCQ(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFCS(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSO(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSOD(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSODC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTHD(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTHDC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUVDF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPARF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPARCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTINCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFDIR(KPROMA), PDSRP(KPROMA), PCDIR(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCBASE(KPROMA), P0DEGL(KPROMA), PVISIH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCIN(KPROMA), PCONVIND(KPROMA,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PLIGH_TOT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PLIGH_CTG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCBASEA(KPROMA), PCTOPC(KPROMA), PZTWETB(KPROMA,2)
REAL(KIND=JPRB) ,INTENT(IN) :: PPRECTYPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFZRA(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFHPCL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFHPCN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFHPSL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFHPSN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRCU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRCV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRDU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRDV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCCQL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCSQL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQLNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQNNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFSQRF(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFSQSF(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQRNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQSNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFSQLTUR(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFSQITUR(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRTV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PENES(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PFEVN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGESLO(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGECLO(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVFLSM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVFCI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PINEE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PIGPP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PIREC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDZ0F(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSAE1(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSAE1(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PISAE1(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PWLE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNSE1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PASNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLICEE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLMNWE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLWMLE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLBOTE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLSFE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PHLICEE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PHLMLE1(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEXTRE1(KPROMA,KLEVXP,KFLDXP)
REAL(KIND=JPRB) ,INTENT(IN) :: PXTR2E1(KPROMA,KFLDXP2)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVAPMU(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUOE1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOE1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(IN) :: PTOE1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOE1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFSNNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PASNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRSNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWSNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSLNU1(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWRENU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRENU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQLINU1(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTILINU1(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTLICNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTLMNNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTLMLNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTLBTNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTLSFNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHLICNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PHLMNU1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEXTRP1(KPROMA,KLEVXP,KFLDXP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXTRP21(KPROMA,KFLDXP2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUO1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVO1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTO1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSO1(KPROMA,KLEVO)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE9(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PRE9F(KPROMA,KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PWRENU0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCLN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRENU0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLINU0(KPROMA,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISUND(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDBLH(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSUND(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PITTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PITSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PISSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PI10FG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PI10FGCV(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PILSPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVTTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVTSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSSRC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVES(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSMLT(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10FG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10FG6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVI10FG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVLSPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVVIMD(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCLS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDLZ0H(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDALB(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVLCC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVMCC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVHCC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVTCC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDISG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUSTRG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSTRG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDLSP(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDCP(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDFZRA(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDBLD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSSHF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSLHF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDSP(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDMSL(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSSR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSTR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSSRD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSSRDC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSTRD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSTRDC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDTSR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDTTR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDUVDF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDPARF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDCAPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDCAPES(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMXCAP6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMXCAPS6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDPARCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDTINCF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCBASE(KPROMA), PV0DEGL(KPROMA), PVVISIH(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCIN(KPROMA), PVKINDEX(KPROMA), PVTTINDEX(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVCBASEA(KPROMA), PVCTOPC(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVZTWETB0(KPROMA), PVZTWETB1(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDFDIR(KPROMA), PVDDSRP(KPROMA), PVDCDIR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIEWSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDINSSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDEWSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDNSSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDE(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDPEV(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDLGWS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDISSHF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDVIWVE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDVIWVN(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCWV(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCLW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCIW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCRW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCSW(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCSLW(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMGWS(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDGWD(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMX2T(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMN2T(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMX2T6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMN2T6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDRO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSRO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDSSRO(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDCSF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDLSSF(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMXTPR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMNTPR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMXTPR6(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDMNTPR6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTPR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDLSRR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDCRR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDLSSFR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDCSFR(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDPTYPE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVILSPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCO3(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDNEE(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDGPP(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDREC(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDLITOTI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDLITOTA6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDLICGI(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDLICGA6(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSMCLBT(KPROMA,KSATSIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSMCSBT(KPROMA,KSATSIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCAERO(KPROMA,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDAEROF(KPROMA,YDMODEL%YRML_GCONF%YGFL%NACTAERO,8)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCGHG(KPROMA,YDMODEL%YRML_GCONF%YGFL%NGHG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDTCCHEM(KPROMA,YDMODEL%YRML_GCONF%YGFL%NCHEM_TC)
TYPE(SURFACE_VIEW_GROUP_VARSF), INTENT(IN) :: GSD_VF
REAL(KIND=JPRB) ,INTENT(IN) :: PGNORDL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGNORDM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGSQM2(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFCQNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFONTE(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRUISP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDHTLS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NTILES,&
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTLS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTLS) 
REAL(KIND=JPRB) ,INTENT(IN) :: PDHTSS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NCSNEC,&
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTSS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTSS) 
REAL(KIND=JPRB) ,INTENT(IN) :: PDHTTS(KPROMA,YDSURF%YSP_SBD%NLEVS,&
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTTS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTTS) 
REAL(KIND=JPRB) ,INTENT(IN) :: PDHTIS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NCSI,&
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTIS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTIS) 
REAL(KIND=JPRB) ,INTENT(IN) :: PDHSSS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NCSNEC,&
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVSSS+YDMODEL%YRML_DIAG%YRMDDH%NDHFSSS) 
REAL(KIND=JPRB) ,INTENT(IN) :: PDHIIS(KPROMA,YDMODEL%YRML_DIAG%YRMDDH%NDHVIIS+YDMODEL%YRML_DIAG%YRMDDH%NDHFIIS)
REAL(KIND=JPRB) ,INTENT(IN) :: PDHWLS(KPROMA,YDSURF%YSP_SBD%NLEVS,&
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVWLS+YDMODEL%YRML_DIAG%YRMDDH%NDHFWLS) 
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDHFSS(KPROMA,YDMODEL%YRML_DIAG%YRMDDH%NDHVFS+YDMODEL%YRML_DIAG%YRMDDH%NDHFFS)
END SUBROUTINE POSTPHY
END INTERFACE
