INTERFACE
SUBROUTINE PPEDDHEC(YDDIMV,YDSURF,YDML_DIAG,YDDPHY,YDML_GCONF,PDHNOM,PDDHCV,PDDHCS,CDNAMX,KDATEF)
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDIMV , ONLY : TDIMV
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDPHY , ONLY : TDPHY
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(TDPHY) , INTENT(IN) :: YDDPHY
TYPE(MODEL_DIAGNOSTICS_TYPE) ,INTENT(INOUT):: YDML_DIAG
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
REAL(KIND=JPRB) , INTENT(IN) :: PDHNOM(11)
REAL(KIND=JPRB) , INTENT(IN) :: PDDHCV(0:YDDIMV%NFLEVG,YDML_DIAG%YRMDDH%NDHCVSU+YDML_DIAG%YRMDDH%NDHVV)
REAL(KIND=JPRB) , INTENT(IN) :: PDDHCS(YDML_DIAG%YRMDDH%NDHCSSU+YDML_DIAG%YRMDDH%NDHVS)
CHARACTER , INTENT(IN) :: CDNAMX*4
INTEGER(KIND=JPIM), INTENT(IN) :: KDATEF(11)
END SUBROUTINE PPEDDHEC
END INTERFACE
