INTERFACE
SUBROUTINE PPEDDH(YDDIMV,YDML_DIAG,YDRIP,PDHNOM,PDDHCV,PDDHCS,CDNAMX,KDATEF)
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
TYPE(MODEL_DIAGNOSTICS_TYPE),INTENT(INOUT):: YDML_DIAG
TYPE(TRIP) , INTENT(IN) :: YDRIP
REAL(KIND=JPRB) , INTENT(IN) :: PDHNOM(11)
REAL(KIND=JPRB) , INTENT(IN) :: PDDHCV(0:YDDIMV%NFLEVG,YDML_DIAG%YRMDDH%NDHCVSU+YDML_DIAG%YRMDDH%NDHVV)
REAL(KIND=JPRB) , INTENT(IN) :: PDDHCS(YDML_DIAG%YRMDDH%NDHCSSU+YDML_DIAG%YRMDDH%NDHVS)
CHARACTER , INTENT(IN) :: CDNAMX*4
INTEGER(KIND=JPIM), INTENT(IN) :: KDATEF(11)
END SUBROUTINE PPEDDH
END INTERFACE
