INTERFACE
SUBROUTINE PPGEOPAD(KPROMA,KSTART,KPROF,KFLEV,KLEVP,KLOLEV,KPPM,KLEVB,&
 & PLNPRES,LDBELO,LDBELS,LDBLOW,LDBLES,LDEXTR,POROG,PVGEOM,&
 & PRXP,PRXPD,PTSTAR,PR0,PLNPR,PALPH,PTF,PZPP,&
 & PRXP5,PRXPD5,PTSTAR5,PR05,PLNPR5,PALPH5,PTF5) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMVERT , ONLY : TVERTICAL_GEOM
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVB(KPROMA,KLEVP,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPRES(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELS(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBLOW(KLEVP)
LOGICAL ,INTENT(IN) :: LDBLES(KLEVP)
LOGICAL ,INTENT(IN) :: LDEXTR
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
TYPE(TVERTICAL_GEOM), INTENT(IN) :: PVGEOM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRXP(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRXPD(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSTAR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PR0(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLNPR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PALPH(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZPP(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXP5(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXPD5(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTAR5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PR05(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALPH5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTF5(KPROMA,KFLEV)
END SUBROUTINE PPGEOPAD
END INTERFACE
