INTERFACE
SUBROUTINE PPINTZTL (KPROMA,KSTART,KPROF,KFLEV,KLEVP,KLOLEV,KPPM,&
 & KLEVB,KSLCT,KSTL,LDBE,LDBL,PZO,&
 & PRXZ,PRXZD,PFLDI,&
 & PFLDO,&
 & PRXZ5,PRXZD5,PFLDI5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVB(KPROMA,KLEVP,KPPM)
INTEGER(KIND=JPIM),INTENT(IN) :: KSLCT
LOGICAL ,INTENT(IN) :: LDBE(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBL(KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: PZO(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZ(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZD(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PFLDI(KPROMA,KSTL:KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFLDO(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZ5(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZD5(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PFLDI5(KPROMA,KSTL:KFLEV)
END SUBROUTINE PPINTZTL
END INTERFACE
