INTERFACE
SUBROUTINE PPINITZ(KPROMA,KSTART,KPROF,KFLEV,KPPM,PRGEOPH,PRGEOPF,PRXP,PRXPD)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
REAL(KIND=JPRB) ,INTENT(IN) :: PRGEOPH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRGEOPF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRXP(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRXPD(KPROMA,0:KFLEV,KPPM)
END SUBROUTINE PPINITZ
END INTERFACE
