INTERFACE
SUBROUTINE PPINITTL(KPROMA,KSTART,KPROF,KFLEV,KPPM,&
 & PRPRESH,PRPRESF,PRXP,PRXPD,&
 & PRPRESH5,PRPRESF5,PRXP5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRXP(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRXPD(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESH5(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESF5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXP5(KPROMA,0:KFLEV,KPPM)
END SUBROUTINE PPINITTL
END INTERFACE
