INTERFACE
SUBROUTINE PPLTETA(KPROMA,KSTART,KPROF,KFLEV,PRPRESF,PTETA,&
 & PXTETA,PRPRES,PRLNPRES) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTETA(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PXTETA
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRPRES(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRLNPRES(KPROMA)
END SUBROUTINE PPLTETA
END INTERFACE
