INTERFACE
SUBROUTINE PPNEW(YDGP5,PRESO,KCOUNT,PXPP,CDPAR,KGRIBCODE,KHORIZ,KSLCT,&
 & LDEXTLI,LDHEIGHT,LDNEUTRAL,LDRELCURR,LDGEMS_PWC,PES5OUT,YDGP_TL,YDGP_AD) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
TYPE(TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(IN) :: PRESO(:,:)
INTEGER(KIND=JPIM) ,INTENT(IN) :: KCOUNT(:)
REAL(KIND=JPRB) ,INTENT(INOUT), TARGET :: PXPP(:,:,:)
INTEGER(KIND=JPIM) ,INTENT(IN) , OPTIONAL :: KGRIBCODE
CHARACTER(LEN=*) ,INTENT(IN) , OPTIONAL :: CDPAR
INTEGER(KIND=JPIM) ,INTENT(IN) , OPTIONAL :: KHORIZ
INTEGER(KIND=JPIM) ,INTENT(IN) , OPTIONAL :: KSLCT
LOGICAL ,INTENT(IN) , OPTIONAL :: LDEXTLI
LOGICAL ,INTENT(IN) , OPTIONAL :: LDHEIGHT
LOGICAL ,INTENT(IN) , OPTIONAL :: LDNEUTRAL, LDRELCURR
LOGICAL ,INTENT(IN) , OPTIONAL :: LDGEMS_PWC
REAL(KIND=JPRB) ,INTENT(OUT) , OPTIONAL, TARGET :: PES5OUT(:)
TYPE(TYPE_GOM_PLUS),INTENT(IN) , OPTIONAL :: YDGP_TL
TYPE(TYPE_GOM_PLUS),INTENT(INOUT), OPTIONAL :: YDGP_AD
END SUBROUTINE PPNEW
END INTERFACE
