INTERFACE
SUBROUTINE PPOBSN(YDGP5,KLEN,KDCOUNT,CDPAR,KCOUNT,KDPP,PXPP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMDB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
TYPE(TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KDCOUNT
CHARACTER(LEN=*) ,INTENT(IN) :: CDPAR
INTEGER(KIND=JPIM),INTENT(IN) :: KCOUNT(KLEN)
INTEGER(KIND=JPIM),INTENT(IN) :: KDPP
REAL(KIND=JPRB) ,INTENT(OUT) :: PXPP(KLEN,KDCOUNT,KDPP)
END SUBROUTINE PPOBSN
END INTERFACE
