INTERFACE
SUBROUTINE PPPMER(KPROMA,KSTART,KPROF,PRPRESS,POROG,PTSTAR,PT0,PMSLPPP,&
 & LDQNH) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTAR(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMSLPPP(KPROMA)
LOGICAL, OPTIONAL ,INTENT(IN) :: LDQNH
END SUBROUTINE PPPMER
END INTERFACE
