INTERFACE
SUBROUTINE PPPMERAD(KPROMA,KSTART,KPROF,PRPRESS,POROG,PTSTAR,PT0,&
 & PMSLPPP,&
 & PRPRESS5,PTSTAR5,PT05) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRPRESS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSTAR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT0(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMSLPPP(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRESS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTAR5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT05(KPROMA)
END SUBROUTINE PPPMERAD
END INTERFACE
