INTERFACE
SUBROUTINE PPPSAD(KPROMA,KSTART,KPROF,KFLEV,KLEVP,KLOLEV,KPPM,KLEVB,&
 & KSLCT,LDEXTLI,PZO,LDBELO,LDBELS,LDBLOW,LDBLES,&
 & LDEXTR,POROG,&
 & PGEOPH,PGEOPF,PRXZ,PRXZD,PRESH,PRESF,PT,&
 & PPPP,&
 & PGEOPH5,PGEOPF5,PRXZ5,PRXZD5,PRESH5,PRESF5,PT5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVB(KPROMA,KLEVP,KPPM)
INTEGER(KIND=JPIM),INTENT(IN) :: KSLCT
LOGICAL ,INTENT(IN) :: LDEXTLI
REAL(KIND=JPRB) ,INTENT(IN) :: PZO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELS(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBLOW(KLEVP)
LOGICAL ,INTENT(IN) :: LDBLES(KLEVP)
LOGICAL ,INTENT(IN) :: LDEXTR
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOPH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOPF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRXZ(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRXZD(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PPPP(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOPH5(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOPF5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZ5(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZD5(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH5(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF5(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA)
END SUBROUTINE PPPSAD
END INTERFACE
