INTERFACE
SUBROUTINE PPPS(KPROMA,KSTART,KPROF,KFLEV,KLEVP,KLOLEV,KPPM,KLEVB,&
 & KSLCT,LDEXTLI,PZO,LDBELO,LDBELS,LDBLOW,LDBLES,&
 & LDEXTR,POROG,&
 & PGEOPH,PGEOPF,PRXZ,PRXZD,PRESH,PRESF,PT,&
 & PPPP) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVB(KPROMA,KLEVP,KPPM)
INTEGER(KIND=JPIM),INTENT(IN) :: KSLCT
LOGICAL ,INTENT(IN) :: LDEXTLI
REAL(KIND=JPRB) ,INTENT(IN) :: PZO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELS(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBLOW(KLEVP)
LOGICAL ,INTENT(IN) :: LDBLES(KLEVP)
LOGICAL ,INTENT(IN) :: LDEXTR
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOPH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOPF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZ(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXZD(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KPROMA,0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPPP(KPROMA,KLEVP)
END SUBROUTINE PPPS
END INTERFACE
