INTERFACE
SUBROUTINE PPRH2MTL(&
 & KPROMA,KIDIA,KFDIA,PRHMAX,PRHMIN,&
 & PAPF5,PQ5,PT5,&
 & PAPF,PQ,PT,&
 & PRH25,PES5,&
 & PRH2) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMIN
REAL(KIND=JPRB) ,INTENT(IN) :: PAPF5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRH25(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PES5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRH2(KPROMA)
END SUBROUTINE PPRH2MTL
END INTERFACE
