INTERFACE
SUBROUTINE PPRH(LDWMORH,KPROMA,KSTART,KPROF,KFLEV,KLEVP,KLOLEV,KPPM,&
 & KLEVB,PRPRES,LDBELO,LDBLOW,LDSONNTAG,PRHMAX,PRHMIN,&
 & PRXP,PRXPD,PQF,PTF,PRHPP) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
LOGICAL ,INTENT(IN) :: LDWMORH
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KPPM
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVB(KPROMA,KLEVP,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRES(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBELO(KPROMA,KLEVP)
LOGICAL ,INTENT(IN) :: LDBLOW(KLEVP)
LOGICAL ,INTENT(IN) :: LDSONNTAG
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMIN
REAL(KIND=JPRB) ,INTENT(IN) :: PRXP(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PRXPD(KPROMA,0:KFLEV,KPPM)
REAL(KIND=JPRB) ,INTENT(IN) :: PQF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRHPP(KPROMA,KLEVP)
END SUBROUTINE PPRH
END INTERFACE
