INTERFACE
SUBROUTINE PPRH2M(&
 & KPROMA,KIDIA,KFDIA,PRHMAX,PRHMIN,&
 & PAPF,PQ,PT,&
 & PES,&
 & PRH2) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMAX
REAL(KIND=JPRB) ,INTENT(IN) :: PRHMIN
REAL(KIND=JPRB) ,INTENT(IN) :: PAPF(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PES(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRH2(KPROMA)
END SUBROUTINE PPRH2M
END INTERFACE
