INTERFACE
SUBROUTINE PPSTAAD(CDATM,KPROMA,KSTART,KPROF,KLEVP,KLOLEV,&
 & PRPRES,PLNPRES,PSTT,PSTFI,&
 & PRPRES5) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVP
CHARACTER(LEN=*) ,INTENT(IN) :: CDATM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KLOLEV
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRPRES(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLNPRES(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTT(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTFI(KPROMA,KLEVP)
REAL(KIND=JPRB) ,INTENT(IN) :: PRPRES5(KPROMA,KLEVP)
END SUBROUTINE PPSTAAD
END INTERFACE
