INTERFACE
SUBROUTINE PPT2MTL(&
 & KPROMA,KIDIA,KFDIA,PINTH,&
 & PQ5,PAPHI5,&
 & PQ,PAPHI,&
 & PCPTGZ5,PCPTS5,&
 & PCPTGZ,PCPTS,&
 & PRI5,PBN5,PBH5,&
 & PBN,PBH,&
 & PT2M) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PINTH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBN5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBH5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBH(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PT2M(KPROMA)
END SUBROUTINE PPT2MTL
END INTERFACE
