INTERFACE
SUBROUTINE PPUV10M(&
 & KPROMA,KIDIA,KFDIA,LDNEUTRAL,LDRELCURR,PINTH,&
 & PUB,PVB,PAPHI,&
 & PRI,PBN,PBM,PU0,PV0,&
 & PU10M,PV10M) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL, INTENT(IN) :: LDNEUTRAL
LOGICAL, INTENT(IN) :: LDRELCURR
REAL(KIND=JPRB) ,INTENT(IN) :: PINTH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUB(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVB(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PU0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PV0(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PU10M(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PV10M(KPROMA)
END SUBROUTINE PPUV10M
END INTERFACE
