INTERFACE
SUBROUTINE PPUV10MAD(&
 & KPROMA,KIDIA,KFDIA,LDNEUTRAL,PINTH,&
 & PUB5,PVB5,PAPHI5,&
 & PUB,PVB,PAPHI,&
 & PRI5,PBN5,PBM5,&
 & PBN,PBM,&
 & PU05,PV05,&
 & PU10M,PV10M) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
LOGICAL, INTENT(IN) :: LDNEUTRAL
REAL(KIND=JPRB) ,INTENT(IN) :: PINTH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUB5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVB5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUB(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVB(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBN5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PBM5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PU05(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PV05(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBN(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBM(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU10M(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10M(KPROMA)
END SUBROUTINE PPUV10MAD
END INTERFACE
