INTERFACE
SUBROUTINE PRE_GRID_BICONSERV(YDGEOMETRY,KGPOUT,KLATS,KLONS,PLATS,&
 & PSPIN,PSPOUT,PSPSP,PGPSP,PGPSPG) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1, ONLY: JPIM, JPRB
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KGPOUT
INTEGER(KIND=JPIM), INTENT(IN) :: KLATS
INTEGER(KIND=JPIM), INTENT(IN) :: KLONS(KLATS)
REAL(KIND=JPRB), INTENT(IN) :: PLATS(KLATS)
REAL(KIND=JPRB), INTENT(OUT) :: PSPIN(YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB), INTENT(OUT) :: PSPOUT(KGPOUT)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSPSP(YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGPSP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGPSPG(YDGEOMETRY%YRGEM%NGPTOTG)
END SUBROUTINE PRE_GRID_BICONSERV
END INTERFACE
