INTERFACE
SUBROUTINE PRECOND (YD_PX,KMAT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE CONTROL_VECTORS_MOD, ONLY : CONTROL_VECTOR, DOT_PRODUCT
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_PX
INTEGER(KIND=JPIM),INTENT(IN) :: KMAT
END SUBROUTINE PRECOND
END INTERFACE
