INTERFACE
SUBROUTINE PRECH(ROBHDR,ROBODY,SATBODY,YDGP5,YDSETINFO)
USE GOM_PLUS, ONLY : TYPE_GOM_PLUS, IH
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY : TYPE_SET_INFO
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY,SATBODY
TYPE(TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
TYPE(TYPE_SET_INFO),INTENT(IN) :: YDSETINFO
END SUBROUTINE PRECH
END INTERFACE
