INTERFACE
SUBROUTINE PREDYNFPOS(YDGEOMETRY,YDMDDH,YDML_GCONF,YDSPEC,YDGMV,YDGFL,LDPACK)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMMDDH , ONLY : TMDDH
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TMDDH) ,INTENT(IN) :: YDMDDH
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
TYPE(SPECTRAL_FIELD) ,INTENT(IN) :: YDSPEC
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
LOGICAL, INTENT(IN) :: LDPACK
END SUBROUTINE PREDYNFPOS
END INTERFACE
