INTERFACE
SUBROUTINE PREDICT_RUNTIME (KITER,KMAXIT,PREDUC,PREQD)
USE PARKIND1 , ONLY : JPRD, JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KITER,KMAXIT
REAL(KIND=JPRB) , INTENT(IN) :: PREDUC,PREQD
END SUBROUTINE PREDICT_RUNTIME
END INTERFACE
