INTERFACE
SUBROUTINE PREGPFPOS(YDGEOMETRY,YDSURF,YDCFU,YDXFU,PXFUBUF,PCFUBUF,LDXFU,LDCFU)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TCFU) ,INTENT(INOUT) :: YDCFU
TYPE(TXFU) ,INTENT(INOUT) :: YDXFU
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS)
LOGICAL ,INTENT(IN) :: LDXFU
LOGICAL ,INTENT(IN) :: LDCFU
END SUBROUTINE PREGPFPOS
END INTERFACE
