INTERFACE
SUBROUTINE PREPPCM(YDGEOMETRY,YDFIELDS,YDGMV5,YDMODEL,YDVARBC,YDTCV,YDTCV_BGC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMGMV , ONLY : TGMV
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_MOD,ONLY : TOVSCV
USE TOVSCV_BGC_MOD,ONLY : TOVSCV_BGC
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CLASS_VARBC),INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(INOUT) :: YDTCV
TYPE(TOVSCV_BGC) ,INTENT(IN) :: YDTCV_BGC
END SUBROUTINE PREPPCM
END INTERFACE
