INTERFACE
SUBROUTINE PREPACKA1_MT (YDFA, KUNTIN, YDFLDSC, PFIELD, YDCPDSC, PVALCO)
USE PARKIND1, ONLY : JPIM, JPRB
USE FA_MOD, ONLY : FA_COM, JPPRCM
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOCPTDESC_MOD, ONLY : IOCPTDESC
TYPE (FA_COM), INTENT (INOUT) :: YDFA
INTEGER (KIND=JPIM), INTENT (IN) :: KUNTIN
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC
REAL (KIND=JPRB), INTENT (IN) :: PFIELD (:)
TYPE (IOCPTDESC), INTENT (INOUT) :: YDCPDSC
REAL (KIND=JPRB), INTENT (OUT) :: PVALCO (:)
END SUBROUTINE PREPACKA1_MT
END INTERFACE
