INTERFACE
SUBROUTINE PREPACKA(YDFACTX, KDOM,YDFLDSC,KFLDS,KMASK,YDCPDSC,&
 & KSTART,KLEN,YDFPOPH,PFIELD,PVALCO) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FAOPH, ONLY : TFAOPH
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOCPTDESC_MOD, ONLY : IOCPTDESC
USE FACTX_MOD, ONLY : FACTX, OPENCPFACTX
TYPE(FACTX), INTENT(INOUT), TARGET :: YDFACTX (:)
INTEGER(KIND=JPIM),INTENT(IN) :: KDOM
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDS
TYPE (IOFLDDESC) ,INTENT(IN) :: YDFLDSC(KFLDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KMASK(KFLDS,KDOM)
TYPE (IOCPTDESC) ,INTENT(INOUT) :: YDCPDSC(KFLDS,KDOM)
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART(KDOM)
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN(KDOM)
TYPE (TFAOPH) ,INTENT(IN) :: YDFPOPH(KDOM)
REAL(KIND=JPRB) ,INTENT(IN), TARGET :: PFIELD(:,:)
REAL (KIND=JPRB), INTENT(INOUT), TARGET :: PVALCO (:,:)
END SUBROUTINE PREPACKA
END INTERFACE
