INTERFACE
SUBROUTINE PRIMDDH (KMA,KDLO,KLOI,KLOF,KLA,CDTIT,KULOUT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDLO
INTEGER(KIND=JPIM),INTENT(IN) :: KLA
INTEGER(KIND=JPIM),INTENT(IN) :: KMA(KDLO,KLA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLOI
INTEGER(KIND=JPIM),INTENT(IN) :: KLOF
CHARACTER(LEN=*) ,INTENT(IN) :: CDTIT
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE PRIMDDH
END INTERFACE
