INTERFACE
SUBROUTINE PRINT_GFP(CDTEXT,CDNAME,YD)
USE TYPE_FPDSPHYS, ONLY : FPDSPHY
CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: CDTEXT
CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: CDNAME
TYPE(FPDSPHY), OPTIONAL, INTENT(IN) :: YD
END SUBROUTINE PRINT_GFP
END INTERFACE
