INTERFACE
SUBROUTINE PRSPL2(YDDIM,KN,PA,PB,PS)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(TDIM) ,INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KN
REAL(KIND=JPRB) ,INTENT(IN) :: PA(KN)
REAL(KIND=JPRB) ,INTENT(IN) :: PB(KN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PS
END SUBROUTINE PRSPL2
END INTERFACE
