INTERFACE
SUBROUTINE PRSTA(ROBHDR,ROBODY,KSLOT,LDLAST,KLEN)
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE MPL_MODULE
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR,ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KSLOT
LOGICAL ,INTENT(IN) :: LDLAST
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
END SUBROUTINE PRSTA
END INTERFACE
