INTERFACE
SUBROUTINE QNEGAT&
 & ( YDECND, KIDIA, KFDIA, KLON, KLEV,&
 & PTSPHY,&
 & PQM, PQE, PRESH,&
 & PFCQNG, PITEND ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECND , ONLY : TECND
TYPE(TECND) ,INTENT(INOUT) :: YDECND
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PQM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRESH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFCQNG(KLON,0:KLEV)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PITEND(KLON,KLEV)
END SUBROUTINE QNEGAT
END INTERFACE
