INTERFACE
SUBROUTINE RADACA ( YDEAERD,YDERAD,KIDIA , KFDIA , KLON , KLEV,&
 & PAPRS , PGELAM, PSIN , PCLON, PSLON , PTH,&
 & PAER , PAERO , POZON , PAERSIG,&
 & PODTO , PODSS , PODDU , PODOM, PODBC , PODSU ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEAERD , ONLY : TEAERD
USE YOERAD , ONLY : TERAD
TYPE(TEAERD) ,INTENT(INOUT) :: YDEAERD
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLON(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLON(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAER(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERO(KLON,KLEV,YDERAD%NMCVAR)
REAL(KIND=JPRB) ,INTENT(OUT) :: POZON(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERSIG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PODTO(KLON), PODSS(KLON), PODDU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PODOM(KLON), PODBC(KLON), PODSU(KLON)
END SUBROUTINE RADACA
END INTERFACE
