INTERFACE
SUBROUTINE RADDIAG(YDGEOMETRY, YDERAD,YDERDI,YDECLD,YDPHY3,KGL1, KGL2, KPROMA, KLEV,&
 & LDLAND,&
 & PALBD , PALBP , PAPRS , PCLFR,&
 & PCC , PCH , PCL , PCM , PCT,&
 & PEMIS , PEMIW , PEMIT,&
 & PMU0 , PSLM,&
 & PT , PTS,&
 & PEMTD , PTRSO,&
 & PLWFC , PLWFT , PSWFC , PSWFT , PTH , PTRSOC , PEMTEC ) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHY3 , ONLY : TPHY3
USE YOERAD , ONLY : TERAD
USE YOECLD , ONLY : TECLD
USE YOERDI , ONLY : TERDI
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TECLD) ,INTENT(INOUT) :: YDECLD
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TERDI) ,INTENT(INOUT) :: YDERDI
TYPE(TPHY3) ,INTENT(INOUT) :: YDPHY3
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KGL1
INTEGER(KIND=JPIM),INTENT(IN) :: KGL2
LOGICAL ,INTENT(IN) :: LDLAND(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(KPROMA,YDERAD%NTSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBP(KPROMA,YDERAD%NTSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLFR(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCC(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIW(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMTD(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSO(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLWFC(KPROMA,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLWFT(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSWFC(KPROMA,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSWFT(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTH(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOC(KPROMA,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMTEC(KPROMA,KLEV+1)
END SUBROUTINE RADDIAG
END INTERFACE
