INTERFACE
SUBROUTINE RADDRV(YDGEOMETRY,YDGMV,YDSURF,YDMODEL,KGPTOT,KFLDS,KBLOCKS,PGMV,PGMVS,PGPIN,PGFL)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KGPTOT
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDS
INTEGER(KIND=JPIM),INTENT(IN) :: KBLOCKS
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV,KBLOCKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,KBLOCKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PGPIN(YDGEOMETRY%YRDIM%NPROMA,KFLDS,KBLOCKS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM,KBLOCKS)
END SUBROUTINE RADDRV
END INTERFACE
