INTERFACE
SUBROUTINE RADFLUX_LAYER(YDSURF,YDERAD,YDERDI,YDPHY2,YDPHY3,&
 & KDIM,PAUX,STATE,PSURF, SURFL, PRAD,AUXL,FLUX,TENDENCY_LOC, PPERT) 
USE YOERAD , ONLY : TERAD
USE YOERDI , ONLY : TERDI
USE YOMPHY2 , ONLY : TPHY2
USE YOMPHY3 , ONLY : TPHY3
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER ,ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_RAD_TYPE, AUX_TYPE,&
 & AUX_DIAG_LOCAL_TYPE, SURF_AND_MORE_TYPE, FLUX_TYPE, PERTURB_TYPE,&
 & SURF_AND_MORE_LOCAL_TYPE 
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TERDI) ,INTENT(INOUT) :: YDERDI
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
TYPE(TPHY3) ,INTENT(INOUT) :: YDPHY3
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (SURF_AND_MORE_TYPE) , INTENT (IN) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT (IN) :: SURFL
TYPE (AUX_RAD_TYPE) , INTENT(INOUT) :: PRAD
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY_LOC
TYPE (PERTURB_TYPE) , INTENT (IN) :: PPERT
END SUBROUTINE RADFLUX_LAYER
END INTERFACE
