INTERFACE
SUBROUTINE RADGHG ( YDERAD,YDRIP,KIDIA, KFDIA, KLON, KLEV,&
 & KDLON,&
 & PPRESSURE_HL, PGEMU,&
 & PCO2 , PCH4 , PN2O , PNO2 , PCFC11 , PCFC12, PO3, PHCFC22, PCCL4 ) 
USE PARKIND1 , ONLY : JPIM , JPRB
USE YOMRIP , ONLY : TRIP
USE YOERAD , ONLY : TERAD
TYPE(TERAD) ,INTENT(IN) :: YDERAD
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PPRESSURE_HL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) ::&
 & PCO2(KLON,KLEV), PCH4(KLON,KLEV), PN2O(KLON,KLEV),&
 & PNO2(KLON,KLEV), PCFC11(KLON,KLEV), PCFC12(KLON,KLEV), PO3(KLON,KLEV),&
 & PHCFC22(KLON,KLEV), PCCL4(KLON,KLEV) 
END SUBROUTINE RADGHG
END INTERFACE
