INTERFACE
SUBROUTINE RADHEATN&
 & ( YDERAD,YDERDI,YDPHY2,YDPHY3,KIDIA , KFDIA , KLON , KLEV, KSPPN2D,&
 & PAPHM1 ,&
 & PEMIS , PSPECTRALEMISS, PEMTD, PMU0, PMU0M,&
 & PQM1,&
 & PTE , PTRSOL , PTRSOD , PTRTHD, PTRSODC, PTRTHDC,PTSM1M ,&
 & PHRSW , PHRLW , PHRSC , PHRLC,&
 & PFRSO , PFRTH , PFRSOD , PFRSODC, PFRTHD, PFRTHDC,&
 & PEMTEC , PTRSOC , PFRSOC , PFRTHC , PINCSR,&
 & PSUDU , PSDUR , PDSRP,&
 & PUVDFI , PPARFI , PPARCFI, PTINCFI, PFDIRI, PCDIRI,&
 & PUVDF , PPARF , PPARCF , PTINCF , PFDIR , PCDIR,&
 & PLWDERIVATIVE,&
 & PNEB , PAP , PGP2DSPP ) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHY2 , ONLY : TPHY2
USE YOMPHY3 , ONLY : TPHY3
USE YOERDI , ONLY : TERDI
USE YOERAD , ONLY : TERAD
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TERDI) ,INTENT(INOUT) :: YDERDI
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
TYPE(TPHY3) ,INTENT(INOUT) :: YDPHY3
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSPPN2D
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSM1M(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0M(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPECTRALEMISS(KLON,YDERAD%NLWOUT)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMTD(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMTEC(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOC(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRTHD(KLON,YDERAD%NLWOUT)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSODC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRTHDC(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHRSW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHRLW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHRSC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHRLC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSO(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOD(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSODC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTHD(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTHDC(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOC(KLON,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTHC(KLON,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PINCSR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSUDU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSDUR(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDSRP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUVDFI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PPARFI(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PPARCFI(KLON), PTINCFI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUVDF(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPARF(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPARCF(KLON), PTINCF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFDIRI(KLON), PCDIRI(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFDIR (KLON), PCDIR (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLWDERIVATIVE(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PNEB(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PGP2DSPP(KLON, KSPPN2D)
END SUBROUTINE RADHEATN
END INTERFACE
