INTERFACE
SUBROUTINE RADHEATAD&
 & ( YDERDI,YDEPHLI,YDPHNC,YDPHY3,KIDIA , KFDIA , KLON , KLEV,&
 & PAPHM15 , PAPM15,&
 & PEMIS , PEMTED5 , PMU0,&
 & PQM15,&
 & PTE5 , PTM15 , PTRSOL5 , PTRSOD5 , PTSM1M5,&
 & PCLFR5 , PQLWP5 , PQIWP5 ,&
 & PFRSO5 , PFRTH5 , PFRSOD5 , PFRTHD5,&
 & PAPHM1 , PAPM1,&
 & PEMTED,&
 & PQM1,&
 & PTE , PTM1 , PTRSOL , PTRSOD , PTSM1M,&
 & PRII0,&
 & PFRSO , PFRTH , PFRSOD , PFRTHD ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMPHY3 , ONLY : TPHY3
USE YOERDI , ONLY : TERDI
USE YOEPHLI , ONLY : TEPHLI
USE YOPHNC , ONLY : TPHNC
TYPE(TEPHLI) ,INTENT(IN) :: YDEPHLI
TYPE(TERDI) ,INTENT(IN) :: YDERDI
TYPE(TPHNC) ,INTENT(IN) :: YDPHNC
TYPE(TPHY3) ,INTENT(IN) :: YDPHY3
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMTED5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOL5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOD5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSM1M5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLFR5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLWP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQIWP5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRII0
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSO5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTH5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOD5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTHD5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEMTED(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRSOL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRSOD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSM1M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFRSO(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFRTH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFRSOD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFRTHD(KLON)
END SUBROUTINE RADHEATAD
END INTERFACE
