INTERFACE
SUBROUTINE RADINTG(YDGEOMETRY, YDMODEL,KLEV , KMODE,&
 & PALBD , PALBP , PCCNL , PCCNO,&
 & PAPRS , PAPRSF, PCCO2 , PCLFR,&
 & PQO3 , PAER , PAERMACCS,PAERMACCL,PAERMACCSJ,PAERMACCLJ,&
 & PAERTGS,PAERTGL, PAERO , PGHG,&
 & PDP , PSPECTRALEMISS,&
 & PMU0 , PQ,&
 & PQS , PQIWP , PQSWP , PQLWP , PFSDP , PQRAIN, PRAINT, PSLM , PT,&
 & PECPO3, PTS,&
 & PEMTD , PEMTU , PTRSO , PTRSC , PEMTC , PNTOP , PNBAS,&
 & PPERTT,&
 & PEMIT , PTH , PFRTED, PTRSOD, PTRSODC, PEMTDC,&
 & PSUDU , PUVDF , PPARF , PPARCF, PTINCF,&
 & PFDIR , PCDIR , PLWDERIVATIVE) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE SPP_MOD , ONLY : YSPP_CONFIG, YSPP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KMODE
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(YDGEOMETRY%YRGEM%NGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBP(YDGEOMETRY%YRGEM%NGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PCCNL(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(IN) :: PCCNO(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCCO2
REAL(KIND=JPRB) ,INTENT(IN) :: PCLFR(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQO3(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAER(YDGEOMETRY%YRGEM%NGPTOT,6,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERMACCS(YDGEOMETRY%YRGEM%NGPTOT,14)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERMACCL(YDGEOMETRY%YRGEM%NGPTOT,16)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERMACCSJ(YDGEOMETRY%YRGEM%NGPTOT,12)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERMACCLJ(YDGEOMETRY%YRGEM%NGPTOT,12)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERTGS(YDGEOMETRY%YRGEM%NGPTOT,KLEV,14)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERTGL(YDGEOMETRY%YRGEM%NGPTOT,KLEV,16)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERO(YDGEOMETRY%YRGEM%NGPTOT,KLEV,YDMODEL%YRML_GCONF%YGFL%NAERO)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGHG(YDGEOMETRY%YRGEM%NGPTOT,8,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDP(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPECTRALEMISS(YDGEOMETRY%YRGEM%NGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NLWEMISS)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQIWP(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSWP(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQLWP(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PFSDP(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQRAIN(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRAINT(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLM(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PECPO3(YDGEOMETRY%YRGEM%NGPTOT,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMTD(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMTU(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRSO(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRSC(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMTC(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PNTOP(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(IN) :: PNBAS(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMIT(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(IN) :: PPERTT(YDGEOMETRY%YRGEM%NGPTOT, YSPP%N2DRAD)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTH(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTED(YDGEOMETRY%YRGEM%NGPTOT, YDMODEL%YRML_PHY_RAD%YRERAD%NLWOUT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRSOD(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRSODC(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMTDC(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSUDU(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUVDF(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPARF(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPARCF(YDGEOMETRY%YRGEM%NGPTOT),PTINCF(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFDIR(YDGEOMETRY%YRGEM%NGPTOT) ,PCDIR(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLWDERIVATIVE(YDGEOMETRY%YRGEM%NGPTOT,KLEV+1)
END SUBROUTINE RADINTG
END INTERFACE
