INTERFACE
SUBROUTINE RADOZCMF ( KIDIA , KFDIA , KLON , KLEV,&
 & PAPRS , PGEMU, POZON ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: POZON(KLON,KLEV)
END SUBROUTINE RADOZCMF
END INTERFACE
