INTERFACE
SUBROUTINE RADTR_ML(KSAT,KSENSOR,KDPROF,KMXCH,KNCH,KTOPLEVELS,&
 & PRCH,LDCLOUD,&
 & PZENANG,PAZIANG,PSOLZENANG,PSOLAZIANG,PLAT,PLON,&
 & YDGP5,PO3F5,&
 & PPSSAT,PTSSAT,PT2SAT,PH2SAT,PCTOP,PCAMT,&
 & PEMIS,PTBCLR,PTBTOT,PTAU,PRADCLDLEV,YDJOT,&
 & PCLDLEV,POBS,PVAROUT,PTAUSFC,LDCO2SLICING) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM),INTENT(IN) :: KDPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSAT
INTEGER(KIND=JPIM),INTENT(IN) :: KSENSOR
INTEGER(KIND=JPIM),INTENT(IN) :: KMXCH
INTEGER(KIND=JPIM),INTENT(IN) :: KNCH(KDPROF)
INTEGER(KIND=JPIM),INTENT(IN) :: KTOPLEVELS
LOGICAL, INTENT(IN) :: LDCLOUD
REAL(KIND=JPRB) ,INTENT(IN) :: PZENANG(KDPROF)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCTOP(KDPROF),PCAMT(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PAZIANG(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOLZENANG(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOLAZIANG(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCH(KDPROF,KMXCH)
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(IN) :: PO3F5(KDPROF,YDGP5%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PPSSAT(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSSAT(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PT2SAT(KDPROF)
REAL(KIND=JPRB) ,INTENT(IN) :: PH2SAT(KDPROF)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEMIS(KDPROF,KMXCH)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTBCLR(KDPROF,KMXCH)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTBTOT(KDPROF,KMXCH)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAU(KDPROF,KMXCH,YDGP5%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRADCLDLEV(KDPROF,KMXCH,YDGP5%NFLEVG+1)
TYPE(JO_TABLE) ,INTENT(IN) :: YDJOT
REAL(KIND=JPRB) ,INTENT(INOUT), OPTIONAL :: PCLDLEV(KDPROF,KMXCH)
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: POBS(KDPROF,KMXCH)
REAL(KIND=JPRB) ,INTENT(INOUT), OPTIONAL :: PVAROUT(KDPROF,KMXCH,4)
REAL(KIND=JPRB) ,INTENT(INOUT), OPTIONAL :: PTAUSFC(KDPROF,KMXCH)
LOGICAL ,INTENT(IN), OPTIONAL :: LDCO2SLICING
END SUBROUTINE RADTR_ML
END INTERFACE
