INTERFACE
SUBROUTINE RADVIS&
 & ( YDERAD,KIDIA , KFDIA , KLON , KLEV ,&
 & PRSF1 , PAP , PQL, PQI, PQR, PQS , PTP , PTSPHY,&
 & PCLAERS, PPRAERS,&
 & PVISICL, PVISIPR, PVISCAE, PVISPAE, PVISCLD&
 & ) 
USE PARKIND1 , ONLY : JPIM , JPRB
USE YOERAD , ONLY : TERAD
TYPE(TERAD) ,INTENT(INOUT):: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB),INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PAP(KLON,KLEV) , PTP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQL(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQI(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQR(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PQS(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCLAERS(KLON) , PPRAERS(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(OUT) :: PVISICL(KLON), PVISIPR(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PVISCAE(KLON), PVISPAE(KLON), PVISCLD(KLON)
END SUBROUTINE RADVIS
END INTERFACE
