INTERFACE
SUBROUTINE RAINGG_OBSOP_AD (ROBHDR, ROBODY, SATHDR, SATBODY,&
 & KOBS, KLEV, YDGP5, YDGP) 
USE PARKIND1, ONLY : JPIM, JPRB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
USE IFS_DBASE_VIEW_MOD, ONLY : IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW) , INTENT (INOUT) :: ROBHDR, ROBODY, SATHDR, SATBODY
INTEGER(KIND=JPIM) , INTENT (IN) :: KOBS, KLEV
TYPE(TYPE_GOM_PLUS) , INTENT (IN) :: YDGP5
TYPE(TYPE_GOM_PLUS) , INTENT (INOUT) :: YDGP
END SUBROUTINE RAINGG_OBSOP_AD
END INTERFACE
