INTERFACE
SUBROUTINE RAINGG_SETUP(YDDIM,YDRIP)
USE YOMDIM , ONLY : TDIM
USE YOMRIP , ONLY : TRIP
TYPE(TDIM), INTENT(IN) :: YDDIM
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE RAINGG_SETUP
END INTERFACE
