INTERFACE
SUBROUTINE RANDOM_CTLVEC(YDGEOMETRY,YDCV,LDINIT,LDENS,LDMERR,LDTOVS,LDLAM,LDPARA,LDPACV,LDTS,KSEED,DELTA)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE RANDOM_NUMBERS_MIX
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(CONTROL_VECTOR), INTENT(INOUT) :: YDCV
LOGICAL, INTENT(IN) :: LDINIT
LOGICAL, INTENT(IN) :: LDENS
LOGICAL, INTENT(IN) :: LDMERR
LOGICAL, INTENT(IN) :: LDTOVS
LOGICAL, INTENT(IN) :: LDLAM
LOGICAL, INTENT(IN) :: LDPARA
LOGICAL, INTENT(IN) :: LDPACV
LOGICAL, INTENT(IN) :: LDTS
INTEGER (KIND=JPIM), INTENT(INOUT) :: KSEED
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: DELTA
END SUBROUTINE RANDOM_CTLVEC
END INTERFACE
