INTERFACE
SUBROUTINE RAO_TL&
 & (KLEVG, KDLEN , KLEN , KMXCOUNT,&
 & YDGP_TL,&
 & YDGP5,&
 & PAEROD_PRIME) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDB
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS, IH
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEVG, KDLEN, KLEN, KMXCOUNT
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP_TL
TYPE (TYPE_GOM_PLUS),INTENT(IN) :: YDGP5
REAL(KIND=JPRB) ,INTENT(OUT) :: PAEROD_PRIME(KDLEN,KMXCOUNT)
END SUBROUTINE RAO_TL
END INTERFACE
