INTERFACE
SUBROUTINE RD801(YDGEOMETRY,YDGFL,YDML_GCONF,YDDYN,YDML_LBC,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN , ONLY : TDYN
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TELBC_MODEL) ,INTENT(INOUT) :: YDML_LBC
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSP
END SUBROUTINE RD801
END INTERFACE
