INTERFACE
SUBROUTINE RDBFLR(ROBHDR,KOBS,KRDBMX,KFRLAT,KFRLON,KFRDAT,KFRTIM,KFRALT)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBHDR
INTEGER(KIND=JPIM),INTENT(IN) :: KOBS
INTEGER(KIND=JPIM),INTENT(OUT) :: KRDBMX
INTEGER(KIND=JPIM),INTENT(OUT) :: KFRLAT
INTEGER(KIND=JPIM),INTENT(OUT) :: KFRLON
INTEGER(KIND=JPIM),INTENT(OUT) :: KFRDAT
INTEGER(KIND=JPIM),INTENT(OUT) :: KFRTIM
INTEGER(KIND=JPIM),INTENT(OUT) :: KFRALT
END SUBROUTINE RDBFLR
END INTERFACE
