INTERFACE
SUBROUTINE RDECCLIMO(YDAFN,CDFILE,KMONTH,YDFPUSERGEO,PFIELD,KGP,KFIELDS,KCOD)
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE YOMAFN, ONLY : TAFN
TYPE(TAFN), INTENT(IN) :: YDAFN
CHARACTER(LEN=*), INTENT(IN) :: CDFILE
INTEGER(KIND=JPIM),INTENT(IN) :: KMONTH
TYPE (TFPUSERGEO) ,INTENT(IN) :: YDFPUSERGEO
INTEGER(KIND=JPIM),INTENT(IN) :: KGP
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
REAL(KIND=JPRB) ,INTENT(OUT) :: PFIELD(KGP,KFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KCOD(KFIELDS)
END SUBROUTINE RDECCLIMO
END INTERFACE
