INTERFACE
SUBROUTINE RDFA2GP (YDGEOMETRY, YDRIP, KFIELDG, PBUF, YDFLDSC, KUNIT, KFILE, YDML_LBC)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
TYPE (GEOMETRY) , INTENT (IN) :: YDGEOMETRY
TYPE (TRIP) , INTENT (IN) :: YDRIP
INTEGER (KIND=JPIM), INTENT (IN) :: KFIELDG
REAL (KIND=JPRB) , INTENT (OUT) :: PBUF (YDGEOMETRY%YRGEM%NGPTOT, KFIELDG, 1)
TYPE (IOFLDDESC) , INTENT (IN) :: YDFLDSC (KFIELDG)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KUNIT
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KFILE
TYPE (TELBC_MODEL), INTENT (IN), OPTIONAL :: YDML_LBC
END SUBROUTINE RDFA2GP
END INTERFACE
