INTERFACE
SUBROUTINE RDFPFILTER(YDGEOMETRY,KREADALL,KFPDOM,KFPCMAX,KFMAX,KGLFI,LDBED,PBED,PLTF,CDMAT,KCMAX,LDFPFIL,PFPMAT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KREADALL
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCMAX
INTEGER(KIND=JPIM), INTENT(IN) :: KFMAX(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KGLFI
LOGICAL, INTENT(IN) :: LDBED
REAL(KIND=JPRB), INTENT(IN) :: PBED
REAL(KIND=JPRB), INTENT(IN) :: PLTF
CHARACTER(LEN=*), INTENT(IN) :: CDMAT(KFPDOM)
INTEGER(KIND=JPIM), INTENT(OUT) :: KCMAX(KFPDOM)
LOGICAL, INTENT(IN) :: LDFPFIL(KFPDOM)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFPMAT(:,:)
END SUBROUTINE RDFPFILTER
END INTERFACE
