INTERFACE
SUBROUTINE RDFUFA(YDGEOMETRY,KUNTIN,CDPREF,CDFIELD,KDEB,KFIN,KINDEX,&
 & PFIELDBUF,KLEV,KLVX,KLVBOT,LDABORT,LDALL) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KUNTIN
CHARACTER ,INTENT(IN) :: CDPREF*(*)
CHARACTER ,INTENT(IN) :: CDFIELD*(*)
INTEGER(KIND=JPIM),INTENT(IN) :: KDEB
INTEGER(KIND=JPIM),INTENT(IN) :: KFIN
INTEGER(KIND=JPIM),INTENT(IN) :: KINDEX
REAL(KIND=JPRB) ,INTENT(OUT) :: PFIELDBUF(YDGEOMETRY%YRGEM%NGPTOTG)
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLVX
INTEGER(KIND=JPIM),INTENT(IN) :: KLVBOT
LOGICAL ,INTENT(IN) :: LDABORT
LOGICAL ,INTENT(IN) :: LDALL
END SUBROUTINE RDFUFA
END INTERFACE
