INTERFACE
SUBROUTINE RDPHTRAJT(YDGEOMETRY,YDPHNC,YDEPHY,YDDPHY,KSTA,KEND,PTRAJ_PHYS_TLAD,&
 & PTENTVD5,PTENQVD5,PTENUVD5,PTENVVD5,&
 & PTENTGW5,PTENUGW5,PTENVGW5,&
 & PTENTCO5,PTENQCO5,PTENUCO5,PTENVCO5,&
 & PTENTCL5,PTENUWM5,PTENVWM5,&
 & PDIFTQ5 ,PDIFTS5 ,PEMTED5 ,PTRSOL5,&
 & PA5 ,PL5 ,PI5,&
 & PLUDE5 , PLU5 ,&
 & PFPLCL5 ,PFPLCN5 ,PUCFL5 ,PVCFL5 ,PTCFL5 ,PQCFL5,&
 & PFRSOTI5,PAHFSTI5,PEVAPTI5,&
 & PEVAPSNW5,PFPLSL5,PFPLSN5 ,PFRTH5) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDPHY , ONLY : TDPHY
USE YOPHNC , ONLY : TPHNC
USE YOEPHY , ONLY : TEPHY
USE YOMTRAJ , ONLY : TRAJ_PHYS_TLAD_TYPE,LPRTTRAJ
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDPHY) ,INTENT(INOUT) :: YDDPHY
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TPHNC) ,INTENT(INOUT) :: YDPHNC
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
TYPE (TRAJ_PHYS_TLAD_TYPE), INTENT(IN) :: PTRAJ_PHYS_TLAD
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENTVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENQVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENUVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENVVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENTGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENUGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENVGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENTCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENQCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENUCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENVCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENTCL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENUWM5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENVWM5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTQ5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEMTED5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRSOL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PA5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PI5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLUDE5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLU5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLCN5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRSOTI5(YDGEOMETRY%YRDIM%NPROMA,YDDPHY%NTILES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAHFSTI5(YDGEOMETRY%YRDIM%NPROMA,YDDPHY%NTILES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEVAPTI5(YDGEOMETRY%YRDIM%NPROMA,YDDPHY%NTILES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEVAPSNW5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLSN5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFRTH5(YDGEOMETRY%YRDIM%NPROMA)
END SUBROUTINE RDPHTRAJT
END INTERFACE
