INTERFACE
SUBROUTINE RDPHTRAJTM_NL(YDGEOMETRY,YDSIMPHL,KSTA,KEND,PTRAJ_PHYS,&
 & PKTROV,PKUROV,&
 & PCDROV,PCHROV,PRAPGWD,&
 & PQL,PQI,PQR,PQS,PLIQCVPPKF,PNEBCVPPKF) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMSIMPHL, ONLY : TSIMPHL
USE YOMTRAJ , ONLY : TRAJ_PHYS_TYPE, LPRTTRAJ
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSIMPHL) ,INTENT(INOUT) :: YDSIMPHL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
TYPE (TRAJ_PHYS_TYPE),INTENT(IN) :: PTRAJ_PHYS
REAL(KIND=JPRB) ,INTENT(OUT) :: PKTROV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKUROV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAPGWD(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQI(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQR(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQS(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLIQCVPPKF(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNEBCVPPKF(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCDROV(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCHROV(YDGEOMETRY%YRDIM%NPROMA)
END SUBROUTINE RDPHTRAJTM_NL
END INTERFACE
