INTERFACE
SUBROUTINE RDRADCOEF(YDGEOMETRY,YDRCOEF,KSTA,KEND,KJUMP,KFIELDSS,&
 & PCOR , PRAB3C, PRAB3N, PRAB4C, PRAB4N, PRAB6C, PRAB6N,&
 & PRAT1C, PRAT1N, PRAT2C, PRAT2N, PRAT3C, PRAT3N, PRAT4C,&
 & PRAT4N, PRAT5C, PRAT5N, PAC) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRCOEF , ONLY : TRCOEF
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRCOEF) ,INTENT(IN) :: YDRCOEF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KJUMP
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDSS
REAL(KIND=JPRB), INTENT(OUT) :: PCOR (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAB3C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAB3N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAB4C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAB4N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAB6C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAB6N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT1C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT1N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT2C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT2N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT3C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT3N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT4C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT4N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT5C (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB), INTENT(OUT) :: PRAT5N (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAC(YDGEOMETRY%YRDIMV%NFLEVG+1,YDGEOMETRY%YRDIMV%NFLEVG+1)
END SUBROUTINE RDRADCOEF
END INTERFACE
