INTERFACE
SUBROUTINE RDSCAW(YDSL,KPROMB,KSTART,KPROF,&
 & KSTABUF,KWIS,KFRSTLOFF,&
 & P4JP,PIS2,PLSDEPI,PLATI,&
 & PIPI,PLON,PLAT,&
 & PDLAT,PCLA,PDLO,PCLO,KL0) 
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(SL_STRUCT), INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMB
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTABUF(YDSL%NDGSAH:YDSL%NDGENH)
INTEGER(KIND=JPIM),INTENT(IN) :: KWIS
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLOFF
REAL(KIND=JPRB) ,INTENT(IN) :: P4JP
REAL(KIND=JPRB) ,INTENT(IN) :: PIS2
REAL(KIND=JPRB) ,INTENT(IN) :: PLSDEPI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATI(YDSL%NDGSAH:YDSL%NDGENH)
REAL(KIND=JPRD) ,INTENT(IN) :: PIPI(YDSL%NDGSAH:YDSL%NDGENH,1:3)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KPROMB)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KPROMB)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLAT(KPROMB)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLA(KPROMB,3)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLO(KPROMB,0:3)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLO(KPROMB,3,2)
INTEGER(KIND=JPIM),INTENT(OUT) :: KL0(KPROMB,0:3)
END SUBROUTINE RDSCAW
END INTERFACE
