INTERFACE
SUBROUTINE RDSLTRAJ2(YDDIM,KSTA,KEND,PTRAJ_SLAG,&
 & PUT95,PVT95,PSPNLT95,PUL95,PVL95,&
 & PSPL95,PUL05,PVL05,PSPL05,&
 & PURL05,PVRL05,PURL5,PVRL5,PUSI5,PVSI5,&
 & PUT15,PVT15) 
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMTRAJ , ONLY : TRAJ_SLAG_TYPE, LPRTTRAJ
TYPE(TDIM) , INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM) , INTENT(IN) :: KSTA
INTEGER(KIND=JPIM) , INTENT(IN) :: KEND
TYPE(TRAJ_SLAG_TYPE), INTENT(IN) :: PTRAJ_SLAG
REAL(KIND=JPRB) , INTENT(OUT) :: PUT95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVT95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PSPNLT95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PUL95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVL95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PSPL95(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PUL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PSPL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PURL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVRL05(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PURL5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVRL5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PUSI5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVSI5(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PUT15(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(OUT) :: PVT15(YDDIM%NPROMA)
END SUBROUTINE RDSLTRAJ2
END INTERFACE
