INTERFACE
SUBROUTINE READ_SURFGRID_TRAJ(YDGEOMETRY,KSTEP,LDLASTRAJ,PTRAJ_BUF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMTRAJ , ONLY : NSTEPTRAJ, MTYPE_SURF_TRAJ, NGP5
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
LOGICAL ,INTENT(IN) :: LDLASTRAJ
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRAJ_BUF(YDGEOMETRY%YRDIM%NPROMA,NGP5,YDGEOMETRY%YRDIM%NGPBLKS)
END SUBROUTINE READ_SURFGRID_TRAJ
END INTERFACE
