INTERFACE
SUBROUTINE READOBA(YDGEOMETRY,YDODB,CD_DBNAME)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCOCTP
USE YOMCMDDR
USE YOMDB
USE MPL_MODULE
USE DBASE_MOD , ONLY : DBASE
USE PARTITION_DBASE_MOD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
CLASS(DBASE), INTENT(INOUT) :: YDODB
CHARACTER(LEN=*),OPTIONAL,INTENT(IN) :: CD_DBNAME
END SUBROUTINE READOBA
END INTERFACE
