INTERFACE
SUBROUTINE READ_SPEC_GRIB(YDMP,CDFILE,YDSPEC)
USE YOMMP , ONLY : TMP
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(TMP) ,INTENT(IN) :: YDMP
CHARACTER(LEN=*) ,INTENT(IN) :: CDFILE
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
END SUBROUTINE READ_SPEC_GRIB
END INTERFACE
