INTERFACE
SUBROUTINE READ_SPEC(YDMP,CD_CFILE, YD_SPEC,KSTEP, LDGRIB, LDBACKGR)
USE YOMMP , ONLY : TMP
USE PARKIND1 , ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD
TYPE(TMP) ,INTENT(IN) :: YDMP
CHARACTER(LEN=*) ,INTENT(IN) :: CD_CFILE
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YD_SPEC
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTEP
LOGICAL ,INTENT(IN), OPTIONAL :: LDGRIB
LOGICAL ,INTENT(IN), OPTIONAL :: LDBACKGR
END SUBROUTINE READ_SPEC
END INTERFACE
