INTERFACE
SUBROUTINE REAST(YDRIP,KDFI,KDIGLST,KDAT,KSSS,KDEC)
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE YOMRIP , ONLY : TRIP
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(INOUT) :: KDFI
INTEGER(KIND=JPIM),INTENT(IN) :: KDIGLST
INTEGER(KIND=JPIM),INTENT(IN) :: KDAT
INTEGER(KIND=JPIM),INTENT(IN) :: KSSS
INTEGER(KIND=JPIM),INTENT(OUT) :: KDEC
END SUBROUTINE REAST
END INTERFACE
