INTERFACE
SUBROUTINE REDUN(YDODB,KTSLOT)
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMOBS
USE DBASE_MOD, ONLY : DBASE
CLASS(DBASE), INTENT(INOUT) :: YDODB
INTEGER(KIND=JPIM),INTENT(IN) :: KTSLOT
END SUBROUTINE REDUN
END INTERFACE
