INTERFACE
SUBROUTINE REFLSIM(KFLEVG,ROBODY,SATHDR,SATBODY,&
 & KDLEN,KDBDY,KLEN,KDCOUNT,KCOUNT,KPNLV,PTF5,PQF5,PCLWF5,&
 & PCIWF5,PCSWF5,PCRWF5,PCGWF5,PGEOPF5,PXPP) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY,SATHDR,SATBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN,KDBDY,KLEN,KDCOUNT
INTEGER(KIND=JPIM),INTENT(IN),DIMENSION(KLEN) :: KCOUNT
INTEGER(KIND=JPIM),INTENT(IN),DIMENSION(KDLEN,KDBDY) :: KPNLV
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG) :: PTF5,PQF5
REAL(KIND=JPRB),INTENT(IN),DIMENSION(KDLEN,KFLEVG) :: PCLWF5,PCIWF5,&
 & PCSWF5,PCRWF5,PCGWF5 
REAL(KIND=JPRB),INTENT(OUT), DIMENSION(KDLEN,KDCOUNT) :: PXPP
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG) :: PGEOPF5
END SUBROUTINE REFLSIM
END INTERFACE
