INTERFACE
SUBROUTINE REFLSIM_2DOP(KFLEVG,ROBODY,SATHDR,SATBODY,&
 & KDLEN,KDBDY,KLEN,KHORIZ,KDCOUNT,KCOUNT,KPNLV,PTF5,PQF5,&
 & PCIWF5,PCSWF5,PCRWF5,PCGWF5,PGEOPF5,PRF5,PPRESF5,PXPP) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY,SATHDR,SATBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KDLEN,KDBDY,KLEN,KDCOUNT,KHORIZ
INTEGER(KIND=JPIM),INTENT(IN),DIMENSION(KLEN) :: KCOUNT
INTEGER(KIND=JPIM),INTENT(IN),DIMENSION(KDLEN,KDBDY) :: KPNLV
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG,KHORIZ) :: PTF5,PQF5
REAL(KIND=JPRB),INTENT(IN),DIMENSION(KDLEN,KFLEVG,KHORIZ) :: PCIWF5,PCSWF5,PCRWF5,PCGWF5
REAL(KIND=JPRB),INTENT(OUT), DIMENSION(KDLEN,KDCOUNT,KHORIZ) :: PXPP
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG,KHORIZ) :: PRF5
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG,KHORIZ) :: PPRESF5
REAL(KIND=JPRB),INTENT(IN), DIMENSION(KDLEN,KFLEVG,KHORIZ) :: PGEOPF5
END SUBROUTINE REFLSIM_2DOP
END INTERFACE
