INTERFACE
SUBROUTINE REFTIM(KDATE, KTIME, KRFTIM)
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(IN) :: KDATE
INTEGER(KIND=JPIM),INTENT(IN) :: KTIME
INTEGER(KIND=JPIM),INTENT(OUT) :: KRFTIM
END SUBROUTINE REFTIM
END INTERFACE
