INTERFACE
SUBROUTINE RELAXGP(YDGEOMETRY,YDGFL,YDGMV,YGFL,YDSPEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE YOMGMV , ONLY : TGMV
USE YOM_YGFL , ONLY : TYPE_GFLD
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE(SPECTRAL_FIELD),INTENT(IN) :: YDSPEC
END SUBROUTINE RELAXGP
END INTERFACE
