INTERFACE
SUBROUTINE RELNEW(YDGEOMETRY,LDLSM,LDFIT,KPDG,PZR,PZM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPDG
LOGICAL ,INTENT(IN) :: LDLSM
LOGICAL ,INTENT(INOUT) :: LDFIT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZR(KPDG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZM(KPDG)
END SUBROUTINE RELNEW
END INTERFACE
