INTERFACE
SUBROUTINE REO3BE (KPOINT ,&
 & KVNM ,KVERC ,PREFV1 ,PREFV2 ,PVAL ,&
 & PVOERR ,PVPERR ,PVFERR ,PVRERR ,&
 & PVFGERR ,PVFGCC1 ,PVFGCC2 ,&
 & PVFGDEP ,PVANDEP ,&
 & KVSTAT ,KVEV1 ,KVEV2 ,KVRDBFL ,KVANFL ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPOINT
INTEGER(KIND=JPIM),INTENT(IN) :: KVNM
INTEGER(KIND=JPIM),INTENT(IN) :: KVERC
REAL(KIND=JPRB) ,INTENT(IN) :: PREFV1
REAL(KIND=JPRB) ,INTENT(IN) :: PREFV2
REAL(KIND=JPRB) ,INTENT(IN) :: PVAL
REAL(KIND=JPRB) ,INTENT(IN) :: PVOERR
REAL(KIND=JPRB) ,INTENT(IN) :: PVPERR
REAL(KIND=JPRB) ,INTENT(IN) :: PVFERR
REAL(KIND=JPRB) ,INTENT(IN) :: PVRERR
REAL(KIND=JPRB) ,INTENT(IN) :: PVFGERR
REAL(KIND=JPRB) ,INTENT(IN) :: PVFGCC1
REAL(KIND=JPRB) ,INTENT(IN) :: PVFGCC2
REAL(KIND=JPRB) ,INTENT(IN) :: PVFGDEP
REAL(KIND=JPRB) ,INTENT(IN) :: PVANDEP
INTEGER(KIND=JPIM),INTENT(IN) :: KVSTAT
INTEGER(KIND=JPIM),INTENT(IN) :: KVEV1
INTEGER(KIND=JPIM),INTENT(IN) :: KVEV2
INTEGER(KIND=JPIM),INTENT(IN) :: KVRDBFL
INTEGER(KIND=JPIM),INTENT(IN) :: KVANFL
END SUBROUTINE REO3BE
END INTERFACE
