INTERFACE
SUBROUTINE RERESF_PART1(YDGEOMETRY,YDFIELDS,YDMODEL,KRSTEP)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT (INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT (INOUT) :: YDFIELDS
TYPE(MODEL), TARGET, INTENT (INOUT) :: YDMODEL
INTEGER(KIND=JPIM), OPTIONAL, INTENT (OUT) :: KRSTEP
END SUBROUTINE RERESF_PART1
END INTERFACE
