INTERFACE
SUBROUTINE RESET_ACCFIE_VAREPS(YDGEOMETRY,YDSURF,YDMCC,YDEPHY,YDRIP,YDDYN,KSTEP)
USE YOEPHY , ONLY : TEPHY
USE YOMDYN , ONLY : TDYN
USE YOMMCC , ONLY : TMCC
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
END SUBROUTINE RESET_ACCFIE_VAREPS
END INTERFACE
