INTERFACE
SUBROUTINE RESET_SPERT(YDGEOMETRY,YDSURF,YDDYN,KSTEP)
USE YOMDYN , ONLY : TDYN
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF, GPOPER
USE PARKIND1 , ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
END SUBROUTINE RESET_SPERT
END INTERFACE
