INTERFACE
SUBROUTINE RESTORE_SURFTSTP(KJ, KJREF, KSTART,KSTEP,&
 & KIDIA,KFDIA,KLON,KLEV,KLEVS,KLEVO,KTILES,KSTGLO,LDOCN_KPP,&
 & PEVAPSNW,PUSTRTI,PVSTRTI,PAHFSTI,PEVAPTI,PFRSOTI,&
 & PWSA,PTSA, PZO,PHO,PHO_INV,PDO,PADVT,PADVS,PTRI0,PTRI1,PSWDK_SAVE,&
 & PUSTRC,PVSTRC,&
 & PUO0,PVO0,PUOC,PVOC,PTO0,PSO0,&
 & PFWRO1,&
 & PSNSE1,PTSNE1,PASNE1,PRSNE1,PTSAE1,PTIAE1,&
 & PWLE1,PWSAE1,&
 & PUOE1,PVOE1,PTOE1,PSOE1) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KJ
INTEGER(KIND=JPIM),INTENT(IN) :: KJREF
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVO
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
LOGICAL ,INTENT(IN) :: LDOCN_KPP(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWSA(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSA(KLON,KLEVS)
REAL(KIND=JPRB), INTENT(INOUT) :: PZO(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PHO(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PHO_INV(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PDO(KLON,0:KLEVO)
REAL(KIND=JPRB), INTENT(INOUT) :: PADVT(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PADVS(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PTRI0(KLON,0:KLEVO)
REAL(KIND=JPRB), INTENT(INOUT) :: PTRI1(KLON,0:KLEVO)
REAL(KIND=JPRB), INTENT(INOUT) :: PSWDK_SAVE(KLON,0:KLEVO)
REAL(KIND=JPRB), INTENT(INOUT) :: PUO0(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PVO0(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PTO0(KLON,KLEVO+1)
REAL(KIND=JPRB), INTENT(INOUT) :: PSO0(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUOC(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOC(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRC(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRC(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFWRO1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSNSE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSNE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PASNE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRSNE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSAE1(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTIAE1(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWLE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWSAE1(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUOE1(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOE1(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTOE1(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSOE1(KLON,KLEVO+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPSNW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFSTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFRSOTI(KLON,KTILES)
END SUBROUTINE RESTORE_SURFTSTP
END INTERFACE
