INTERFACE
SUBROUTINE RESTART_CNT3(YDGEOMETRY,YDFIELDS,YDMODEL,YDJOT)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE JO_TABLE_MOD , ONLY : JO_TABLE
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(JO_TABLE),INTENT(INOUT) :: YDJOT
END SUBROUTINE RESTART_CNT3
END INTERFACE
