INTERFACE
SUBROUTINE RH2Q(PRH,PRHERR,PT,PTERR,PP,PPERR,PQ,PQERRFRH,PQERRFP,PQERRFT )
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PRH
REAL(KIND=JPRB) ,INTENT(IN) :: PRHERR
REAL(KIND=JPRB) ,INTENT(IN) :: PT
REAL(KIND=JPRB) ,INTENT(IN) :: PTERR
REAL(KIND=JPRB) ,INTENT(IN) :: PP
REAL(KIND=JPRB) ,INTENT(IN) :: PPERR
REAL(KIND=JPRB) ,INTENT(OUT) :: PQ
REAL(KIND=JPRB) ,INTENT(OUT) :: PQERRFRH
REAL(KIND=JPRB) ,INTENT(OUT) :: PQERRFP
REAL(KIND=JPRB) ,INTENT(OUT) :: PQERRFT
END SUBROUTINE RH2Q
END INTERFACE
