INTERFACE
SUBROUTINE RRTM_RTRN1A_140GP(YDDIMV,KIDIA,KFDIA,KLEV,K_ISTART,K_IEND,K_ICLDLYR,P_CLDFRAC,P_TAUCLD,P_ABSS1,&
 & P_OD,P_TAUSF1,P_TOTDFLUC,P_TOTDFLUX,P_TOTUFLUC,P_TOTUFLUX,&
 & P_TAVEL,P_TZ,P_TBOUND,PFRAC,P_SEMISS,P_SEMISLW) 
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE PARRRTM , ONLY : JPBAND
USE YOERRTM , ONLY : JPGPT
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: K_ISTART
INTEGER(KIND=JPIM),INTENT(IN) :: K_IEND
INTEGER(KIND=JPIM),INTENT(IN) :: K_ICLDLYR(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDFRAC(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TAUCLD(KIDIA:KFDIA,YDDIMV%NFLEVG,JPBAND)
REAL(KIND=JPRB) ,INTENT(IN) :: P_ABSS1(KIDIA:KFDIA,JPGPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_OD(KIDIA:KFDIA,JPGPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TAUSF1(KIDIA:KFDIA,JPGPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_TOTDFLUC(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_TOTDFLUX(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_TOTUFLUC(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_TOTUFLUX(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TAVEL(KIDIA:KFDIA,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TZ(KIDIA:KFDIA,0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_TBOUND(KIDIA:KFDIA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRAC(KIDIA:KFDIA,JPGPT,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_SEMISS(KIDIA:KFDIA,JPBAND)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_SEMISLW(KIDIA:KFDIA)
END SUBROUTINE RRTM_RTRN1A_140GP
END INTERFACE
