INTERFACE
SUBROUTINE SAT_AVG_STDEV_FILTER(ROBODY,SATBODY,&
 & KLEN,KSENSOR) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY,SATBODY
INTEGER(KIND=JPIM), INTENT(IN) :: KLEN
INTEGER(KIND=JPIM), INTENT(IN) :: KSENSOR
END SUBROUTINE SAT_AVG_STDEV_FILTER
END INTERFACE
