INTERFACE
SUBROUTINE SATEMIS(KINS,KDPT,KSTID,KI3,KI4,KI2I2,KI1,KIS )
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(IN) :: KINS
INTEGER(KIND=JPIM),INTENT(IN) :: KDPT
INTEGER(KIND=JPIM),INTENT(IN) :: KSTID
INTEGER(KIND=JPIM),INTENT(OUT) :: KI3
INTEGER(KIND=JPIM),INTENT(OUT) :: KI4
INTEGER(KIND=JPIM),INTENT(OUT) :: KI2I2
INTEGER(KIND=JPIM),INTENT(OUT) :: KI1
INTEGER(KIND=JPIM),INTENT(OUT) :: KIS
END SUBROUTINE SATEMIS
END INTERFACE
