INTERFACE
SUBROUTINE SATOBIN(KSTBP,&
 & KOBTYP,KCDTYP,KOBSQNO,KCDSQNO,&
 & LDMESAGE,LDTAKEN) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE YOMDB
USE LOCAL_TRAFOS
INTEGER(KIND=JPIM),INTENT(IN) :: KSTBP
INTEGER(KIND=JPIM),INTENT(IN) :: KOBTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KCDTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KOBSQNO
INTEGER(KIND=JPIM),INTENT(IN) :: KCDSQNO
LOGICAL ,INTENT(INOUT) :: LDMESAGE
LOGICAL ,INTENT(OUT) :: LDTAKEN
END SUBROUTINE SATOBIN
END INTERFACE
