INTERFACE
SUBROUTINE SATOB_OB (KTSLOT, KPOOLNO)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMDB
INTEGER(KIND=JPIM),INTENT(IN) :: KTSLOT
INTEGER(KIND=JPIM),INTENT(IN) :: KPOOLNO
END SUBROUTINE SATOB_OB
END INTERFACE
