INTERFACE
SUBROUTINE SATURAD (KIDIA , KFDIA , KLON , KTDIA , KLEV,&
 & PAPRSF5, PT5 , PQSAT5,&
 & PAPRSF , PT , PQSAT ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSAT5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQSAT(KLON,KLEV)
END SUBROUTINE SATURAD
END INTERFACE
