INTERFACE
SUBROUTINE SAVE_EVECS(YDGEOMETRY,YDRIP)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE SAVE_EVECS
END INTERFACE
