INTERFACE
SUBROUTINE SAVMINI2(YDGEOMETRY,YDRIP,YDVAZX,CDFILE,KSTART,KEND)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE CONTROL_VECTORS_MOD, ONLY : CONTROL_VECTOR
USE NETCDF
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTART
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
TYPE(CONTROL_VECTOR),INTENT(IN) :: YDVAZX(KSTART:KEND)
CHARACTER(LEN=*) ,INTENT(IN) :: CDFILE
END SUBROUTINE SAVMINI2
END INTERFACE
