INTERFACE
SUBROUTINE SBSFGS(YDGEOMETRY,YDFIELDS,YDDIMACV,YDGMV5,YDML_GCONF,YDTCV,YDTCV5,YDACV)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMGMV , ONLY : TGMV
USE TOVSCV_MOD , ONLY : TOVSCV
USE TYPE_ACV , ONLY : TACVDIM, ACV_CONTAINER
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(TACVDIM), INTENT(IN) :: YDDIMACV
TYPE(TGMV), INTENT(INOUT) :: YDGMV5
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT) :: YDML_GCONF
TYPE(TOVSCV), INTENT(INOUT) :: YDTCV
TYPE(TOVSCV), INTENT(IN) :: YDTCV5
TYPE(ACV_CONTAINER), INTENT(INOUT) :: YDACV
END SUBROUTINE SBSFGS
END INTERFACE
