INTERFACE
SUBROUTINE SCALEDERAE(YDGEOMETRY,PSCALE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PSCALE
END SUBROUTINE SCALEDERAE
END INTERFACE
