INTERFACE
SUBROUTINE SCAN2M_HPOS(YDRQPHY,YDRQCLI,YDNAMFPSCI,YDAFN,LDCTLCLIM,KSTGLO,KBL,KEND,LDFPOSHOR,YDGEOMETRY,YDSURF,YDCFU,YDXFU,&
 & YDMODEL,PCFUBUF,PXFUBUF,PWSXI,PWDXI,PBUF) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE TYPE_MODEL , ONLY : MODEL
USE YOMAFN , ONLY : TAFN
USE YOMFP4L , ONLY : TRQFP
USE YOMFPC , ONLY : TNAMFPSCI
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
TYPE (TRQFP), INTENT(IN) :: YDRQCLI
TYPE(TNAMFPSCI) ,INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN) ,INTENT(IN) :: YDAFN
LOGICAL ,INTENT(IN) :: LDCTLCLIM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
INTEGER(KIND=JPIM),INTENT(IN) :: KBL
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
LOGICAL ,INTENT(IN) :: LDFPOSHOR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(TCFU) ,INTENT(IN) :: YDCFU
TYPE(TXFU) ,INTENT(IN) :: YDXFU
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
REAL(KIND=JPRB) ,INTENT(IN) :: PCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSXI
REAL(KIND=JPRB) ,INTENT(IN) :: PWDXI
REAL(KIND=JPRB) ,INTENT(OUT) :: PBUF(YDGEOMETRY%YRDIM%NPROMA,YDRQPHY%NFIELDG)
END SUBROUTINE SCAN2M_HPOS
END INTERFACE
