INTERFACE
SUBROUTINE SCAN2M(YDGEOMETRY,YDFIELDS,YDGMV5,YDMODEL,CDCONF,LD_TST_GPGFL,LD_DFISTEP,YDSPEC,PTRAJEC,&
 & YDGOM5,YDFPOS,YDFPDATA,YDODB) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE TYPE_MODEL , ONLY : MODEL
USE YOMGMV , ONLY : TGMV
USE YOMTRAJ , ONLY : MKINDTRAJ,NTRAJ_CST, MSTEPTRAJW, LPRTTRAJ, MTRAJ_GRIB,&
 & NGP5, MIOTRAJSURF, MTYPE_SURF_TRAJ, LTRAJGP, TRAJ_TYPE 
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE FULLPOS , ONLY : TFPOS, TFPDATA
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV5
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
CHARACTER(LEN=9) ,INTENT(IN) :: CDCONF
LOGICAL ,INTENT(IN) :: LD_TST_GPGFL
LOGICAL ,INTENT(IN) :: LD_DFISTEP
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
TYPE(TRAJ_TYPE) ,INTENT(INOUT) :: PTRAJEC
TYPE(CLASS_SUPERGOM), OPTIONAL, INTENT(INOUT) :: YDGOM5
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
TYPE(TFPOS) ,INTENT(IN), OPTIONAL :: YDFPOS
TYPE(TFPDATA) ,INTENT(INOUT), OPTIONAL :: YDFPDATA
END SUBROUTINE SCAN2M
END INTERFACE
