INTERFACE
SUBROUTINE SCAN2M_OOPS(YDGEOMETRY,YDFIELDS,YDGMV5,YDMODEL,CDCONF,LD_TST_GPGFL,LD_DFISTEP,YDSPEC,PTRAJEC_OOPS)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMGMV , ONLY : TGMV
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE YOMTRAJ_OOPS , ONLY : TRAJ_TYPE_OOPS
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) , INTENT(INOUT) :: YDFIELDS
TYPE(TGMV) , INTENT(INOUT) :: YDGMV5
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
CHARACTER(LEN=9) , INTENT(IN) :: CDCONF
LOGICAL , INTENT(IN) :: LD_TST_GPGFL
LOGICAL , INTENT(IN) :: LD_DFISTEP
TYPE(SPECTRAL_FIELD) , INTENT(INOUT) :: YDSPEC
TYPE(TRAJ_TYPE_OOPS) , INTENT(INOUT) :: PTRAJEC_OOPS
END SUBROUTINE SCAN2M_OOPS
END INTERFACE
