INTERFACE
SUBROUTINE SCREEN_TIMESLOT(YDEPHY,YDML_PHY_MF,KNCHEM_ASSIM,YDODB,YDGOM5,KTSLOT,KOBTOT,KOFFTOT,LDPRINT,LD_F_SCR_WORK_TS,YDJOT)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOEPHY , ONLY : TEPHY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE DBASE_MOD , ONLY : DBASE
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_MF_TYPE) ,INTENT(INOUT) :: YDML_PHY_MF
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNCHEM_ASSIM
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
TYPE(CLASS_SUPERGOM) ,INTENT(IN) :: YDGOM5
INTEGER(KIND=JPIM) ,INTENT(IN) :: KTSLOT,KOBTOT,KOFFTOT
LOGICAL ,INTENT(IN) :: LDPRINT,LD_F_SCR_WORK_TS
TYPE(JO_TABLE) ,INTENT(INOUT) :: YDJOT
END SUBROUTINE SCREEN_TIMESLOT
END INTERFACE
