INTERFACE
SUBROUTINE SEKF_PREP_SMOS(YDDIM,YDRIP)
USE YOMDIM , ONLY : TDIM
USE YOMRIP ,ONLY : TRIP
USE YOMDB
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE SEKF_PREP_SMOS
END INTERFACE
