INTERFACE
SUBROUTINE SEKF_BACKGERR(KL,KBLOCK,KVAR,PVARB,PVARG,PVARBT,PVARGT,PBERR,PCANER)
USE PARKIND1 ,ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KL,KBLOCK,KVAR
REAL(KIND=JPRB), INTENT(IN) :: PVARB(KVAR)
REAL(KIND=JPRB), INTENT(IN) :: PVARG(KVAR)
REAL(KIND=JPRB), INTENT(IN) :: PBERR(KVAR)
REAL(KIND=JPRB), INTENT(IN) :: PVARBT(KVAR)
REAL(KIND=JPRB), INTENT(IN) :: PVARGT(KVAR,KVAR)
REAL(KIND=JPRB), INTENT(INOUT) :: PCANER(KVAR,KVAR)
END SUBROUTINE SEKF_BACKGERR
END INTERFACE
