INTERFACE
SUBROUTINE SEKF_MATINV(P_ZMAT,KINFO)
USE PARKIND1 , ONLY : JPRD, JPIM, JPRB
REAL(KIND=JPRB),INTENT(INOUT) :: P_ZMAT(:,:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KINFO
END SUBROUTINE SEKF_MATINV
END INTERFACE
