INTERFACE
SUBROUTINE SEKF_WRITE(YDGEOMETRY,YDRIP,CDWRT)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
CHARACTER(LEN = 5),INTENT(IN) :: CDWRT
END SUBROUTINE SEKF_WRITE
END INTERFACE
