INTERFACE
SUBROUTINE SELECT_CLOSEST_SCATT(ROBODY,SCATTBODY,YDGP5,YDSET,PHOFX)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY : TYPE_SET_INFO
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS,IH
TYPE(IFS_DBASE_VIEW) , INTENT(INOUT) :: ROBODY
TYPE(IFS_DBASE_VIEW) , INTENT(INOUT) :: SCATTBODY
TYPE(TYPE_GOM_PLUS) , INTENT(IN) :: YDGP5
TYPE(TYPE_SET_INFO) , INTENT(IN) :: YDSET
REAL(KIND=JPRB) , INTENT(INOUT) :: PHOFX(YDGP5%NDLEN,YDSET%MXBDY)
END SUBROUTINE SELECT_CLOSEST_SCATT
END INTERFACE
