INTERFACE
SUBROUTINE SET2PE(KPE,KPRGPNS,KPRGPEW,KPRTRW,KPRTRV)
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
INTEGER(KIND=JPIM),INTENT(OUT) :: KPE
INTEGER(KIND=JPIM),INTENT(IN) :: KPRGPNS
INTEGER(KIND=JPIM),INTENT(IN) :: KPRGPEW
INTEGER(KIND=JPIM),INTENT(IN) :: KPRTRW
INTEGER(KIND=JPIM),INTENT(IN) :: KPRTRV
END SUBROUTINE SET2PE
END INTERFACE
