INTERFACE
SUBROUTINE SET_SLHD_SPONGE(YDGEOMETRY,YDDYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
END SUBROUTINE SET_SLHD_SPONGE
END INTERFACE
