INTERFACE
SUBROUTINE SETIMZERO(YDLAP,YDMP,YDCV)
USE YOMLAP , ONLY : TLAP
USE YOMMP , ONLY : TMP
USE CONTROL_VECTORS_MOD
TYPE(TLAP) , INTENT(IN) :: YDLAP
TYPE(TMP) , INTENT(IN) :: YDMP
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDCV
END SUBROUTINE SETIMZERO
END INTERFACE
