INTERFACE
SUBROUTINE SID1 (KDUM,PU,PV)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDUM
REAL(KIND=JPRB),INTENT(IN) :: PU(KDUM)
REAL(KIND=JPRB),INTENT(INOUT) :: PV(KDUM)
END SUBROUTINE SID1
END INTERFACE
