INTERFACE
SUBROUTINE SIGAMAD(YDGEOMETRY,YDDYN,KLEV,KLON,PD,PT,PSP,KNLON,KFLEVG)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNLON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFLEVG
REAL(KIND=JPRB) ,INTENT(INOUT) :: PD(1+(KFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(1+(KFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP(KNLON)
END SUBROUTINE SIGAMAD
END INTERFACE
