INTERFACE
SUBROUTINE SILKAP(LDVERTFE, LDVFE_LAPL_BC, YDCST, YDGEOMETRY,YDDYN,LDNHQE_C2,KLEV,KLON,KNLON,PIN,POUT,PMULFAC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YOMCST , ONLY : TCST
USE PARKIND1 , ONLY : JPIM, JPRB
LOGICAL, INTENT (IN) :: LDVFE_LAPL_BC
LOGICAL, INTENT (IN) :: LDVERTFE
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
LOGICAL ,INTENT(IN) :: LDNHQE_C2
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNLON
REAL(KIND=JPRB) ,INTENT(IN) :: PIN(1+(YDGEOMETRY%YRDIMV%NFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT(1+(YDGEOMETRY%YRDIMV%NFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PMULFAC
END SUBROUTINE SILKAP
END INTERFACE
