INTERFACE
SUBROUTINE SIM4D(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,KINDIC,KDPROB,YDVAZX,PZF,&
 & YDVAZG,KITER,YDJOT,YDVARBC,YDTCV5,YDGOM,YDTCV,YDTCV_BGC,YDGOM5,YDODB) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE PARKIND1 , ONLY : JPIM, JPRB
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_BGC_MOD , ONLY : TOVSCV_BGC
USE TOVSCV_MOD , ONLY : TOVSCV
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE DBASE_MOD , ONLY : DBASE
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDVAZX
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZF
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDVAZG
INTEGER(KIND=JPIM) ,INTENT(IN) :: KITER
TYPE(JO_TABLE) ,INTENT(INOUT) :: YDJOT
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(IN) , OPTIONAL :: YDTCV5
TYPE(CLASS_SUPERGOM),INTENT(INOUT), OPTIONAL :: YDGOM
TYPE(TOVSCV) ,INTENT(INOUT), OPTIONAL :: YDTCV
TYPE(CLASS_SUPERGOM),INTENT(INOUT), OPTIONAL :: YDGOM5
CLASS(DBASE) ,INTENT(INOUT), OPTIONAL :: YDODB
TYPE(TOVSCV_BGC) ,INTENT(IN) , OPTIONAL :: YDTCV_BGC
INTEGER(KIND=JPIM) :: KINDIC
INTEGER(KIND=JPIM) :: KDPROB
END SUBROUTINE SIM4D
END INTERFACE
