INTERFACE
SUBROUTINE SIPC_READ_MODEL(KINDEX,KDIM,CDJOBNAM_R,KINFOS,PINP_FIELD)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KDIM
INTEGER(KIND=JPIM) ,INTENT(IN) :: KINDEX
CHARACTER (LEN = 3),INTENT(OUT) :: CDJOBNAM_R
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KINFOS(3)
REAL(KIND=JPRB) ,INTENT(OUT) :: PINP_FIELD(KDIM)
END SUBROUTINE SIPC_READ_MODEL
END INTERFACE
