INTERFACE
SUBROUTINE SIPC_INIT_MODEL(KMODEL,KINFO)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE PAR_COU
USE PAR_SIPC
USE YOM_INPC
USE YOM_OAS
INTEGER(KIND=JPIM),INTENT(IN) :: KMODEL
INTEGER(KIND=JPIM),INTENT(OUT) :: KINFO
END SUBROUTINE SIPC_INIT_MODEL
END INTERFACE
