INTERFACE
SUBROUTINE SISEVE(LDVERTFE, LDVFE_LAPL_BC, YDDYNA, YDGEOMETRY,YDDYN,KLEV,KLON,PV1,PV2,KNLON,LD_LSTAR)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMDYNA , ONLY : TDYNA
LOGICAL, INTENT (IN) :: LDVFE_LAPL_BC
LOGICAL, INTENT (IN) :: LDVERTFE
TYPE (TDYNA), INTENT (IN) :: YDDYNA
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KNLON
REAL(KIND=JPRB) ,INTENT(IN) :: PV1(1+(YDGEOMETRY%YRDIMV%NFLEVG-1)*KLEV+(KNLON-1)*KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PV2(1+(YDGEOMETRY%YRDIMV%NFLEVG-1)*KLEV+(KNLON-1)*KLON)
LOGICAL,OPTIONAL ,INTENT(IN) :: LD_LSTAR
END SUBROUTINE SISEVE
END INTERFACE
