INTERFACE
SUBROUTINE SLCOMM_OBS(YDSL,KFLDSLB,LDINC,PB1A)
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(SL_STRUCT) ,INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDSLB
LOGICAL ,INTENT(IN) :: LDINC
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1A(KFLDSLB,YDSL%NASLB1)
END SUBROUTINE SLCOMM_OBS
END INTERFACE
