INTERFACE
SUBROUTINE SLCSET(YDGEOMETRY,YDSL,KASET,KBSET,&
 & KDGLG,KDLON,KDGSAG,KDGENG,KDGSAL,KDGENL,KDGSAH,KDGENH,&
 & KDGUXL,KDLUNG,KDLUXG,KDGUNG,KDGUXG,&
 & KDSUR1,KDLSUR,KDGSUR,KGPTOT,&
 & KPTRFLOFF,KFRSTLOFF,KYFRSTACTLAT,KYLSTACTLAT,&
 & KSTA,KONL,KLOENG,KPTRFRSTLAT,KFRSTLAT,KLSTLAT,&
 & PMU,PSQM2,LDCSETONLY,YDSLREP) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMMP0 , ONLY : NPRINTLEV, NPROC, LOUTPUT, LMPDIAG, NSLPAD, LSLDEBUG, N_REGIONS_NS, N_REGIONS_EW, MYPROC
USE YOMSLREP , ONLY : TSLREP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(SL_STRUCT), INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KASET
INTEGER(KIND=JPIM),INTENT(IN) :: KBSET
INTEGER(KIND=JPIM),INTENT(IN) :: KDGLG
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSAG
INTEGER(KIND=JPIM),INTENT(IN) :: KDGENG
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSAL
INTEGER(KIND=JPIM),INTENT(IN) :: KDGENL
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSAH
INTEGER(KIND=JPIM),INTENT(IN) :: KDGENH
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUNG
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUXG
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUNG
INTEGER(KIND=JPIM),INTENT(IN) :: KGPTOT
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUXL
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUXG
INTEGER(KIND=JPIM),INTENT(IN) :: KDSUR1
INTEGER(KIND=JPIM),INTENT(IN) :: KDLSUR
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSUR
INTEGER(KIND=JPIM),INTENT(IN) :: KPTRFLOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KYFRSTACTLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KYLSTACTLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA(KDGSAG:KDGENG+N_REGIONS_NS-1,N_REGIONS_EW)
INTEGER(KIND=JPIM),INTENT(IN) :: KONL(KDGSAG:KDGENG+N_REGIONS_NS-1,N_REGIONS_EW)
INTEGER(KIND=JPIM),INTENT(IN) :: KLOENG(KDGSAG:KDGENG)
INTEGER(KIND=JPIM),INTENT(IN) :: KPTRFRSTLAT(N_REGIONS_NS)
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLAT(N_REGIONS_NS)
INTEGER(KIND=JPIM),INTENT(IN) :: KLSTLAT(N_REGIONS_NS)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU(KDGSAG:KDGENG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSQM2(KDGSAG:KDGENG)
LOGICAL,INTENT(IN),OPTIONAL :: LDCSETONLY
TYPE(TSLREP) ,INTENT(INOUT), OPTIONAL :: YDSLREP
END SUBROUTINE SLCSET
END INTERFACE
