INTERFACE
SUBROUTINE SLEXTPOL_OBS(YDDIM,YDSL,KFLDSLB,PARSLB,PB1A)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(TDIM) ,INTENT(IN) :: YDDIM
TYPE(SL_STRUCT) ,INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDSLB
REAL(KIND=JPRB) ,INTENT(IN) :: PARSLB(KFLDSLB)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1A(KFLDSLB,YDSL%NASLB1)
END SUBROUTINE SLEXTPOL_OBS
END INTERFACE
