INTERFACE
SUBROUTINE SLEXTPOLAD(YDDIM,YDSL,KFLDSLB,PARSLB,PB1A,KMASK1)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(TDIM) ,INTENT(IN) :: YDDIM
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDSLB
REAL(KIND=JPRB) ,INTENT(IN) :: PARSLB(KFLDSLB)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1A(YDSL%NASLB1,KFLDSLB,1)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KMASK1(YDSL%NASLB1+YDDIM%NSTENCILWIDE*2)
END SUBROUTINE SLEXTPOLAD
END INTERFACE
