INTERFACE
SUBROUTINE SLEXTPOL(YDDIM,YDSL,&
 & KFLDSLB,KFIXFLD,KTYP,PARSLB,PB1A,KMASK2) 
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(TDIM) ,INTENT(IN) :: YDDIM
TYPE(SL_STRUCT) ,INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDSLB
INTEGER(KIND=JPIM),INTENT(IN) :: KFIXFLD(2)
INTEGER(KIND=JPIM),INTENT(IN) :: KTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PARSLB(KFLDSLB)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1A(YDSL%NASLB1,KFLDSLB,1)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KMASK2(YDSL%NASLB1+YDDIM%NSTENCILWIDE*2)
END SUBROUTINE SLEXTPOL
END INTERFACE
