INTERFACE
SUBROUTINE SLRSET(YDSL,&
 & KSTA,KONL,KPTRFRSTLAT,KFRSTLAT,KLSTLAT) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE MPL_MODULE
USE YOMMP0 , ONLY : NPROC, LOUTPUT, LMPDIAG, NPRCIDS, MYPROC, NGPSET2PE, N_REGIONS, N_REGIONS_NS, N_REGIONS_EW
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(SL_STRUCT), INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA(YDSL%NDGSAG:YDSL%NDGENG+N_REGIONS_NS-1,N_REGIONS_EW)
INTEGER(KIND=JPIM),INTENT(IN) :: KONL(YDSL%NDGSAG:YDSL%NDGENG+N_REGIONS_NS-1,N_REGIONS_EW)
INTEGER(KIND=JPIM),INTENT(IN) :: KPTRFRSTLAT(N_REGIONS_NS)
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLAT(N_REGIONS_NS)
INTEGER(KIND=JPIM),INTENT(IN) :: KLSTLAT(N_REGIONS_NS)
END SUBROUTINE SLRSET
END INTERFACE
