INTERFACE
SUBROUTINE SLTEND_LAYER(&
 & YDMODEL,KDIM, PAUX, STATE_T0, TENDENCY_DYN, TENDENCY_VDF, TENDENCY_CML, PSLPHY9,&
 & PSAVTEND, PGFLSLP, PSURF,&
 & TENDENCY_LOC) 
USE TYPE_MODEL, ONLY : MODEL
USE PARKIND1 , ONLY : JPRB
USE YOMPHYDER , ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & MODEL_STATE_TYPE, SURF_AND_MORE_TYPE 
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE_T0
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_DYN
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_VDF
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_CML
TYPE (MODEL_STATE_TYPE) , INTENT (IN) :: PSLPHY9
REAL(KIND=JPRB) ,INTENT(OUT) :: PSAVTEND(KDIM%KLON,KDIM%KLEV,YDMODEL%YRML_PHY_G%YRSLPHY%NVTEND)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGFLSLP(KDIM%KLON,KDIM%KLEV,YDMODEL%YRML_GCONF%YGFL%NDIMSLP)
TYPE (SURF_AND_MORE_TYPE) , INTENT (INOUT) :: PSURF
TYPE (STATE_TYPE) , INTENT (INOUT) :: TENDENCY_LOC
END SUBROUTINE SLTEND_LAYER
END INTERFACE
