INTERFACE
SUBROUTINE SM_EKF_MAIN(YDEPHY,KL,KBLOCK,KSEKFCV,KSTART,KSTOP,&
 & KSEKFQ,P_ZINC,P_ZDEBUG,&
 & P_ZKGAIN,P_ZBACK,P_ZCANER,P_ZOCGR,P_ZMOD_ANA) 
USE PARKIND1 ,ONLY : JPIM, JPRB
USE YOMSEKF ,ONLY : NSSA_TSLOT, NANAL, NANATIME,&
 & NOBS_SEKF_MAX, T2M_OBS, TD2M_OBS, VOL_SM_FG, TTB_FG, NSLAY,&
 & T2M_FG, TD2M_FG,&
 & LUSE_T2M, LUSE_RH2M, LUSE_ASCAT, LUSE_SMOS_TB,&
 & NREF_BLOCK, NREF_GP,&
 & YLASCATOBS, NOBS_ASCAT,&
 & LSMOS_SM_OBS,NOBS_ASCAT_MAX,NOBS_ASCAT_TOT,&
 & YLSMOSOBS, NOBS_SMOS_TB,NOBS_SMOS_SM,&
 & NOBS_TSTEP, NANA_TSTEP, SMOS_SM_TST,&
 & MOD_ERR,BACK_ERR, BACK_ERR_L1, BACK_ERR_L2, BACK_ERR_L3,&
 & ANA_ERR,T2M_ERR,RH2M_ERR,ASCAT_ERR,SMOS_TB_COEF_ERR,&
 & SMOS_SM_MIN_VOL_ERR,SMOS_SM_COEF_ERR,&
 & LUSE_EDA_JACOB,COVAR_RH2M_CV_SEKF,COVAR_T2M_CV_SEKF,VAR_CV_SEKF,&
 & COVAR_SSM_CV_SEKF,EDAH_TAPER,&
 & STYPE, LUSE_SMOS_SM, NSMOS_SM_FIL,SMOS_SM_OBS,SMOS_SM_ERR 
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHY) ,INTENT(INOUT):: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KBLOCK, KL, KSEKFCV, KSTART, KSTOP
INTEGER(KIND=JPIM),INTENT(OUT) :: KSEKFQ
REAL(KIND=JPRB),INTENT(OUT) :: P_ZINC(KSEKFCV)
REAL(KIND=JPRB),INTENT(OUT) :: P_ZDEBUG(32)
REAL(KIND=JPRB),INTENT(OUT) :: P_ZKGAIN(KSEKFCV,NOBS_SEKF_MAX)
REAL(KIND=JPRB),INTENT(OUT) :: P_ZOCGR(NOBS_SEKF_MAX,KSEKFCV)
REAL(KIND=JPRB),INTENT(OUT) :: P_ZCANER(KSEKFCV,KSEKFCV)
REAL(KIND=JPRB),INTENT(OUT) :: P_ZBACK(KSEKFCV,KSEKFCV)
REAL(KIND=JPRB),INTENT(OUT) :: P_ZMOD_ANA(NANAL,KSEKFCV)
END SUBROUTINE SM_EKF_MAIN
END INTERFACE
