INTERFACE
SUBROUTINE SMOS_PROCESS(YDGEM,PSMOS_OBS_BUF,KSMOS_BUF,PSMOS_ANGLE,&
 & PSMOS_FARAD,PSMOS_GEOMET) 
 USE YOMGEM , ONLY : TGEM
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE YOMDB
 USE YOMSMOS ,ONLY : NPOL_MAX, NANG_MAX, SMOS_NO_OBS, SMOS_USE, SMOS_OBS_POS,&
 & NSMOS_ANG, DELTA_ANG 
 TYPE(TGEM) ,INTENT(IN) :: YDGEM
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSMOS_OBS_BUF (YDGEM%NGPTOT, 0:NPOL_MAX-1, NANG_MAX)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSMOS_ANGLE (YDGEM%NGPTOT, 0:NPOL_MAX-1, NANG_MAX)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSMOS_FARAD (YDGEM%NGPTOT, 0:NPOL_MAX-1, NANG_MAX)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSMOS_GEOMET (YDGEM%NGPTOT, 0:NPOL_MAX-1, NANG_MAX)
 INTEGER(KIND=JPIM) ,INTENT(INOUT) :: KSMOS_BUF (YDGEM%NGPTOT, 0:NPOL_MAX-1, NANG_MAX)
END SUBROUTINE SMOS_PROCESS
END INTERFACE
