INTERFACE
SUBROUTINE SMPFIL(YDLAP,YDDIM,YDEGEO,YDELAP,PDT,KSTEP,LDWIND,PHW,PHW0)
USE YOMLAP , ONLY : TLAP
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YEMLAP , ONLY : TLEP
USE YEMGEO , ONLY : TEGEO
TYPE(TLAP) ,INTENT(IN) :: YDLAP
TYPE(TDIM) ,INTENT(IN) :: YDDIM
TYPE(TEGEO) ,INTENT(IN) :: YDEGEO
TYPE(TLEP) ,INTENT(IN) :: YDELAP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
LOGICAL ,INTENT(IN) :: LDWIND
REAL(KIND=JPRB) ,INTENT(IN) :: PDT
REAL(KIND=JPRB) ,INTENT(OUT) :: PHW(YDDIM%NSPEC2,2*KSTEP+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PHW0(2*KSTEP+1)
END SUBROUTINE SMPFIL
END INTERFACE
