INTERFACE
SUBROUTINE SONDE_COUNTRY_DB_MATCH(CDSTID,KTYPESOND,KCDTYP,PLAT,PLON,&
 & KSONDE_DB_ENTRY,KCOUNTRY_DB_ENTRY ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRSTRHBIAS
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPESOND
INTEGER(KIND=JPIM),INTENT(IN) :: KCDTYP
INTEGER(KIND=JPIM),INTENT(OUT) :: KSONDE_DB_ENTRY
INTEGER(KIND=JPIM),INTENT(OUT) :: KCOUNTRY_DB_ENTRY
CHARACTER(LEN=*),INTENT(IN) :: CDSTID
REAL(KIND=JPRB),INTENT(IN) :: PLAT
REAL(KIND=JPRB),INTENT(IN) :: PLON
END SUBROUTINE SONDE_COUNTRY_DB_MATCH
END INTERFACE
