INTERFACE
SUBROUTINE SPAREORD(YDDIM,KFLEV,PSPFILE,PSPBUF,LD_FILE_TO_MODEL)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(TDIM) ,INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPFILE(YDDIM%NSEFRE,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPBUF(YDDIM%NSPEC2G,KFLEV)
LOGICAL ,INTENT(IN) :: LD_FILE_TO_MODEL
END SUBROUTINE SPAREORD
END INTERFACE
