INTERFACE
SUBROUTINE SPBSGPUPD(YDDIM,YDML_PHY_STOCH,YDDYN,YDPHY2,KIDIA,KFDIA,KLON,KLEV,PVORTGRADX,PVORTGRADY,PVORT,PTENU,PTENV,&
 & PAPRSF,PT,PMFUDE_RATE,PMFU,PWMEAN,PTP,PQP,PRSF1,PSTREAM,PTEMP,PSTOPHCA,PTOTDISS,PTOTDISS_SMOOTH,&
 & PDISSGW,PDISSCU,PEXTRA,PEXTR2,KLEVX,KFLDX,KFLDX2,PGEMU,PU,PV,PAPRS,KTYPE) 
USE MODEL_PHYSICS_STOCHAST_MOD , ONLY : MODEL_PHYSICS_STOCHAST_TYPE
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMPHY2 , ONLY : TPHY2
USE YOMDYN , ONLY : TDYN
 TYPE(TDIM) ,INTENT(IN) :: YDDIM
 TYPE(TDYN) ,INTENT(IN) :: YDDYN
 TYPE(MODEL_PHYSICS_STOCHAST_TYPE),INTENT(IN) :: YDML_PHY_STOCH
 TYPE(TPHY2) ,INTENT(IN) :: YDPHY2
 INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
 INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
 INTEGER(KIND=JPIM),INTENT(IN) :: KLON
 INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
 INTEGER(KIND=JPIM),INTENT(IN) :: KLEVX
 INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX
 INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX2
 REAL(KIND=JPRB) ,INTENT(IN) :: PVORTGRADX(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PVORTGRADY(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PVORT(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENU(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENV(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PMFUDE_RATE(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PWMEAN(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PTP(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PQP(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PRSF1(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PTOTDISS(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PTOTDISS_SMOOTH(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PDISSGW(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PDISSCU(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTREAM(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PTEMP(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PSTOPHCA(KLON)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PEXTRA(KLON,KLEVX,KFLDX)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PEXTR2(KLON,KFLDX2)
 REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
 REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:KLEV)
 INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
END SUBROUTINE SPBSGPUPD
END INTERFACE
