INTERFACE
SUBROUTINE SPC2M(YDGEOMETRY,YDRIP,YDDYN,CDCONF,YDSPEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMRIP , ONLY : TRIP
USE YOMDYN , ONLY : TDYN
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
END SUBROUTINE SPC2M
END INTERFACE
