INTERFACE
SUBROUTINE SPCHORAD(YDGEOMETRY,YDML_GCONF,YDDYN,KSTA,KEND,PSPVOR,PSPDIV,PSPT,PSPGFL,PSPSP,PSPTALLG)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPVOR(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPDIV(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPGFL(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSP(:)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPTALLG(:,:)
END SUBROUTINE SPCHORAD
END INTERFACE
