INTERFACE
SUBROUTINE SPCHOR(YDGEOMETRY,YDMODEL,KSTA,KEND,&
 & PSPVOR,PSPDIV,PSPT,PSPSPD,PSPSVD,PSPSNHX,PSPGFL,PSPSP,&
 & PSPTNDHD_VOR,PSPTNDHD_DIV,PSPTNDHD_T,&
 & PSPTNDHD_SPD,PSPTNDHD_SVD,PSPTNDHD_SNHX,PSPTNDHD_GFL) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPVOR(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPDIV(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPT(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSPD(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSVD(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSNHX(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPGFL(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSP(:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_VOR(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_DIV(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_T(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_SPD(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_SVD(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_SNHX(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_GFL(:,:,:)
END SUBROUTINE SPCHOR
END INTERFACE
