INTERFACE
SUBROUTINE SPCIMPFSOLVEAD(YDGEOMETRY,YDRIP,YDDYN,LDONEM,PSPDIVP,PSDIVP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(TRIP) ,INTENT(IN) :: YDRIP
LOGICAL ,INTENT(IN) :: LDONEM
REAL(KIND=JPRB) ,INTENT(IN) :: PSPDIVP(:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSDIVP (:,:)
END SUBROUTINE SPCIMPFSOLVEAD
END INTERFACE
