INTERFACE
SUBROUTINE SPCMAD(YDGEOMETRY,YDML_GCONF,YDDYN,CDCONF,YDSP)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) , INTENT(INOUT) :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE), INTENT(INOUT) :: YDML_GCONF
CHARACTER(LEN=1) , INTENT(IN) :: CDCONF
TYPE(SPECTRAL_FIELD) , INTENT(INOUT) :: YDSP
END SUBROUTINE SPCMAD
END INTERFACE
