INTERFACE
SUBROUTINE SPCM(YDGEOMETRY,YDMODEL,CDCONF,YDSP,YDGMV)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE YOMGMV , ONLY : TGMV
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSP
TYPE(TGMV),INTENT(INOUT) :: YDGMV
END SUBROUTINE SPCM
END INTERFACE
