INTERFACE
SUBROUTINE SPCONVERT(YDGEOMETRY,LDMODEL_TO_FILE, YDSPEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
LOGICAL , INTENT(IN) :: LDMODEL_TO_FILE
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSPEC
END SUBROUTINE SPCONVERT
END INTERFACE
