INTERFACE
SUBROUTINE SPECRT(YDGEOMETRY,YDGFL,YGFL,KDIR,YDSP,LDINCR,YDGFL5,PTRAJEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMTRAJ , ONLY : TRAJ_TYPE, LPRTTRAJ
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(TYPE_GFLD), INTENT(IN) :: YGFL
INTEGER(KIND=JPIM), INTENT(IN) :: KDIR
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
LOGICAL, OPTIONAL, INTENT(IN) :: LDINCR
TYPE(TGFL), OPTIONAL, INTENT(INOUT) :: YDGFL5
TYPE(TRAJ_TYPE), OPTIONAL, INTENT(IN) :: PTRAJEC
END SUBROUTINE SPECRT
END INTERFACE
