INTERFACE
SUBROUTINE SPEC2GRIDAD(YDGEOMETRY,YDSP,YDGP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE GRIDPOINT_FIELDS_MIX, ONLY : ASSIGNMENT(=), GRIDPOINT_FIELD
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSP
TYPE(GRIDPOINT_FIELD),INTENT(INOUT) :: YDGP
END SUBROUTINE SPEC2GRIDAD
END INTERFACE
