INTERFACE
SUBROUTINE SPEEEST(PSIGMOY,PINCMOY,PSPEED)
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGMOY
REAL(KIND=JPRB) ,INTENT(IN) :: PINCMOY
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPEED
END SUBROUTINE SPEEEST
END INTERFACE
