INTERFACE
SUBROUTINE SPFILT(YDGEOMETRY,KSTA,KEND,PSPVOR,PSPDIV)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPVOR(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPDIV(:,:)
END SUBROUTINE SPFILT
END INTERFACE
