INTERFACE
SUBROUTINE SPOS(YDQTYPE,YDFPFILTERS,KRESOL,KSPEC2,PSPBFP,LDACTIVE)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMFPFILTERS, ONLY : TFPFILTERS
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(TFPFILTERS), INTENT(IN) :: YDFPFILTERS
INTEGER(KIND=JPIM), INTENT(IN) :: KRESOL
INTEGER(KIND=JPIM), INTENT(IN) :: KSPEC2
REAL(KIND=JPRB), INTENT(INOUT) :: PSPBFP(YDQTYPE%NFPSPB,KSPEC2)
LOGICAL, INTENT(OUT) :: LDACTIVE
END SUBROUTINE SPOS
END INTERFACE
