INTERFACE
SUBROUTINE SPPTEN (YDECLDP,YGFL,KIDIA,KFDIA,KLON,KLEV,KSDTN2D,PTSPHY,&
 & PTSL, PQSL, PA, PAP, PAPH,&
 & PDYN_U, PDYN_V, PDYN_T, PDYN_Q,&
 & PUNP_U ,PUNP_V ,PUNP_T ,PUNP_Q,&
 & PPHY_U ,PPHY_V ,PPHY_T ,PPHY_Q,&
 & PMULNOISE,&
 & PTENU ,PTENV ,PTENT ,PTENQ, PTENGFL, KTRAC, PTENC, PPERT) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECLDP , ONLY : TECLDP
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMPHYDER, ONLY : PERTURB_TYPE
TYPE(TECLDP) ,INTENT (IN) :: YDECLDP
TYPE(TYPE_GFLD) ,INTENT (IN) :: YGFL
TYPE(PERTURB_TYPE) ,INTENT (IN),OPTIONAL :: PPERT
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSDTN2D
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PTSL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PQSL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PDYN_U(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PDYN_V(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PDYN_T(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PDYN_Q(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PUNP_U(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PUNP_V(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PUNP_T(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PUNP_Q(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PPHY_U(KLON,KLEV,KSDTN2D)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PPHY_V(KLON,KLEV,KSDTN2D)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PPHY_T(KLON,KLEV,KSDTN2D)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PPHY_Q(KLON,KLEV,KSDTN2D)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PMULNOISE(KLON,KSDTN2D)
REAL(KIND=JPRB) ,INTENT(OUT),OPTIONAL :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT),OPTIONAL :: PTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT),OPTIONAL :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT),OPTIONAL :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN),OPTIONAL :: PTENGFL(KLON,KLEV,YGFL%NDIM1)
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KTRAC
REAL(KIND=JPRB) ,INTENT(INOUT),OPTIONAL :: PTENC(:,:,:)
END SUBROUTINE SPPTEN
END INTERFACE
