INTERFACE
SUBROUTINE SRGEVENT(CDACT,KEVENTWR,KEVENT,KEVENTVL)
USE PARKIND1 ,ONLY : JPIM ,JPRD
INTEGER(KIND=JPIM) :: KEVENT
INTEGER(KIND=JPIM) :: KEVENTVL
INTEGER(KIND=JPIM) :: KEVENTWR
CHARACTER*(*)CDACT
END SUBROUTINE SRGEVENT
END INTERFACE
