INTERFACE
SUBROUTINE SRTM_SRTM_224GP&
 & (YDDIMV, YDERAD,YDERDI,YDPHY3,KIDIA, KFDIA, KLON , KLEV , KSW , KOVLP ,&
 & PAER , PALBD, PALBP, PAPH , PAP ,&
 & PTS , PTH , PT ,&
 & PQ , PCO2 , PCH4 , PN2O , PNO2 , POZN , PRMU0 ,&
 & PFRCL, PTAUC, PASYC, POMGC,&
 & PFSUX, PFSUC, PFUVF, PSUDU,&
 & PFDIR, PCDIR, PFDIF, PCDIF) 
USE YOERDI , ONLY : TERDI
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOERAD , ONLY : TERAD
USE YOMPHY3 , ONLY : TPHY3
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TERAD) ,INTENT(IN) :: YDERAD
TYPE(TERDI) ,INTENT(IN) :: YDERDI
TYPE(TPHY3) ,INTENT(IN) :: YDPHY3
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KOVLP
REAL(KIND=JPRB) ,INTENT(IN) :: PAER(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(KLON,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBP(KLON,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCO2(KLON,KLEV),PCH4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PN2O(KLON,KLEV),PNO2(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POZN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRCL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUC(KLON,KSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PASYC(KLON,KSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POMGC(KLON,KSW,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSUX(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFSUC(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFUVF(KLON) , PSUDU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFDIF(KLON,KLEV+1), PCDIF(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFDIR(KLON,KLEV+1), PCDIR(KLON,KLEV+1)
END SUBROUTINE SRTM_SRTM_224GP
END INTERFACE
