INTERFACE
SUBROUTINE SRTM_CLDPROP&
 & (YDDIMV, KLEV, K_ICLDATM, K_INFLAG, K_ICEFLAG, K_LIQFLAG, K_NSTR,&
 & P_CLDFRAC, P_CLDDAT1, P_CLDDAT2, P_CLDDAT3, P_CLDDAT4, P_CLDDATMOM,&
 & P_TAUCLDORIG, P_TAUCLOUD, P_SSACLOUD, P_XMOM&
 & ) 
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE PARSRTM , ONLY : JPBAND, JPB1, JPB2
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(OUT) :: K_ICLDATM
INTEGER(KIND=JPIM),INTENT(IN) :: K_INFLAG
INTEGER(KIND=JPIM),INTENT(IN) :: K_ICEFLAG
INTEGER(KIND=JPIM),INTENT(IN) :: K_LIQFLAG
INTEGER(KIND=JPIM),INTENT(IN) :: K_NSTR
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDFRAC(YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDDAT1(YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDDAT2(YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDDAT3(YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDDAT4(YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: P_CLDDATMOM(0:16,YDDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_TAUCLDORIG(YDDIMV%NFLEVG,JPBAND)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P_TAUCLOUD(YDDIMV%NFLEVG,JPBAND)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_SSACLOUD(YDDIMV%NFLEVG,JPBAND)
REAL(KIND=JPRB) ,INTENT(OUT) :: P_XMOM(0:16,YDDIMV%NFLEVG,JPBAND)
END SUBROUTINE SRTM_CLDPROP
END INTERFACE
