INTERFACE
SUBROUTINE STATE_INCREMENT(KDIM,POSTATE, PA_U,PA_V,PA_T,PA_O3,PA_Q,PA_A,PA_QL,PA_QI,PA_QR,PA_QS,&
 & PA_TKE) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMPHYDER , ONLY : STATE_TYPE, MASK_GFL_TYPE, DIMENSION_TYPE
 TYPE (DIMENSION_TYPE) ,INTENT(IN) :: KDIM
 TYPE (STATE_TYPE),INTENT(INOUT) :: POSTATE
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_U(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_V(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_T(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_O3(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_Q(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_A(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_QL(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_QI(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_QR(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_QS(KDIM%KLON,KDIM%KLEV)
 REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(IN) :: PA_TKE(KDIM%KLON,KDIM%KLEV)
END SUBROUTINE STATE_INCREMENT
END INTERFACE
