INTERFACE
SUBROUTINE STATE_UPDATE(YDPHY2,KDIM,PISTATE,PTEND,POSTATE)
USE YOMPHY2 , ONLY : TPHY2
USE YOMPHYDER, ONLY : STATE_TYPE, MASK_GFL_TYPE, DIMENSION_TYPE
TYPE(TPHY2) , INTENT(INOUT):: YDPHY2
TYPE (DIMENSION_TYPE),INTENT(IN) :: KDIM
TYPE (STATE_TYPE), INTENT(IN) :: PISTATE
TYPE (STATE_TYPE), INTENT(IN) :: PTEND
TYPE (STATE_TYPE), INTENT(INOUT):: POSTATE
END SUBROUTINE STATE_UPDATE
END INTERFACE
