INTERFACE
SUBROUTINE STEPO_FPOS_VH(YDQTYPE,YDAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,KFPXFLD,YDFPOS,KFPDOM,YDGEOMETRY,YDGMV,YDGFL,YDSURF,YDXFU,KCUFNR,&
 & PMCUFGP,YDMODEL,CDV,CDH,KPXLEV,PXLEV,LDHPOS,LDEZO,PFPBUF,PSPEC,P2DFIELDS,P3DFIELDS,P3DPHYS,KP3FIELDS) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE YOMGMV , ONLY : TGMV
USE YOMGFL , ONLY : TGFL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMXFU , ONLY : TXFU
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMFPC , ONLY : TNAMFPSCI, TNAMFPINT, LTRACEFP, LALLOFP
USE TYPE_FPRQDYNS , ONLY : TYPE_FPRQDYN
USE FULLPOS , ONLY : TFPOS
USE TYPE_FPOSBUF , ONLY : FPOSBUF
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(FPOSBUF) ,INTENT(IN) :: YDAUX
TYPE(FPOSBUF) ,INTENT(IN) :: YDCLIMO
TYPE(TNAMFPINT) ,INTENT(IN) :: YDNAMFPINT
TYPE(TNAMFPSCI) ,INTENT(IN) :: YDNAMFPSCI
INTEGER(KIND=JPIM),INTENT(IN) :: KFPXFLD
TYPE (TFPOS) ,INTENT(IN) :: YDFPOS
INTEGER(KIND=JPIM),INTENT(IN) :: KFPDOM
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(IN) :: YDGMV
TYPE(TGFL) ,INTENT(IN) :: YDGFL
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(TXFU) ,INTENT(IN) :: YDXFU
INTEGER(KIND=JPIM),INTENT(IN) :: KCUFNR
REAL(KIND=JPRB) ,INTENT(IN) :: PMCUFGP(YDGEOMETRY%YRDIM%NPROMA,KCUFNR,YDGEOMETRY%YRDIM%NGPBLKS)
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
CHARACTER(LEN=1) ,INTENT(IN) :: CDV
CHARACTER(LEN=1) ,INTENT(IN) :: CDH
INTEGER(KIND=JPIM),INTENT(IN) :: KPXLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PXLEV(KPXLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KP3FIELDS
LOGICAL ,INTENT(IN) :: LDHPOS
LOGICAL ,INTENT(IN) :: LDEZO
REAL(KIND=JPRB) ,INTENT(OUT), POINTER :: PFPBUF(:,:,:)
REAL(KIND=JPRB) ,INTENT(OUT), ALLOCATABLE :: PSPEC(:,:)
REAL(KIND=JPRB) ,ALLOCATABLE, TARGET, INTENT(INOUT), OPTIONAL :: P2DFIELDS(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE, TARGET, INTENT(INOUT), OPTIONAL :: P3DFIELDS(:,:,:,:)
REAL(KIND=JPRB) ,TARGET, INTENT(INOUT), OPTIONAL ::&
 & P3DPHYS(YDFPOS%YFPGEOMETRY%YFPGEO%NFPROMA,KPXLEV,KP3FIELDS,YDFPOS%YFPGEOMETRY%YFPGEO%NFPBLOCS) 
END SUBROUTINE STEPO_FPOS_VH
END INTERFACE
