INTERFACE
SUBROUTINE STEPOAD_OOPS(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,PTRAJEC_OOPS,CDCONF,YDVARBC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE YOMTRAJ_OOPS , ONLY : TRAJ_TYPE_OOPS
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(TRAJ_TYPE_OOPS) ,INTENT(IN) :: PTRAJEC_OOPS
CHARACTER(LEN=9) ,INTENT(IN) :: CDCONF
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
END SUBROUTINE STEPOAD_OOPS
END INTERFACE
