INTERFACE
SUBROUTINE STEPO_OOPS(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,PTRAJEC_OOPS,CDCONF)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE YOMTRAJ_OOPS , ONLY : TRAJ_TYPE_OOPS
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
TYPE(TRAJ_TYPE_OOPS), INTENT(INOUT) :: PTRAJEC_OOPS
CHARACTER(LEN=9),INTENT(IN) :: CDCONF
END SUBROUTINE STEPO_OOPS
END INTERFACE
