INTERFACE
SUBROUTINE STEPO(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,CDCONF,YDJOT,YDVARBC,YDTCV5,YDGOM5,YDODB,YDFPOS,YDFPDATA)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_MOD , ONLY : TOVSCV
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE DBASE_MOD , ONLY : DBASE
USE FULLPOS , ONLY : TFPOS, TFPDATA
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) , INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) , INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
CHARACTER(LEN=9) , INTENT(IN) :: CDCONF
TYPE(JO_TABLE) , INTENT(INOUT), OPTIONAL :: YDJOT
TYPE(CLASS_VARBC) , INTENT(INOUT), OPTIONAL :: YDVARBC
TYPE(TOVSCV) , INTENT(IN), OPTIONAL :: YDTCV5
TYPE(CLASS_SUPERGOM), INTENT(INOUT), OPTIONAL :: YDGOM5
CLASS(DBASE) , INTENT(INOUT), OPTIONAL :: YDODB
TYPE(TFPOS) , INTENT(IN), OPTIONAL :: YDFPOS
TYPE(TFPDATA) , INTENT(INOUT), OPTIONAL :: YDFPDATA
END SUBROUTINE STEPO
END INTERFACE
