INTERFACE
SUBROUTINE STOCHPERT_LAYER(&
 & YDECLDP,YGFL,YDPHY2,KDIM, PAUX, STATE, TENDENCY_DYN,&
 & TENDENCY_PHY, PTENGFL,&
 & PPERT, TENDENCY, GEMSL ) 
USE YOECLDP , ONLY : TECLDP
USE PARKIND1 , ONLY : JPIM , JPRB
USE YOMPHYDER, ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & PERTURB_TYPE, GEMS_LOCAL_TYPE 
USE YOMPHY2 , ONLY : TPHY2
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TECLDP) , INTENT(INOUT) :: YDECLDP
TYPE(TPHY2) , INTENT(INOUT) :: YDPHY2
TYPE(TYPE_GFLD) , INTENT(INOUT) :: YGFL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_DYN
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY_PHY(KDIM%K2DSDT)
REAL(KIND=JPRB) , INTENT (IN) :: PTENGFL(KDIM%KLON,KDIM%KLEV,YGFL%NDIM1)
TYPE (PERTURB_TYPE) , INTENT (INOUT):: PPERT
TYPE (GEMS_LOCAL_TYPE) , INTENT (INOUT):: GEMSL
TYPE (STATE_TYPE) , INTENT (INOUT):: TENDENCY
END SUBROUTINE STOCHPERT_LAYER
END INTERFACE
