INTERFACE
SUBROUTINE STORE_SEKF_CV(YDGEOMETRY,KIDIA,KFDIA,KLON,&
 & KSTGLO, KSTEP,&
 & PVSM_ML, PT2M_TEMP, PTD2M_TEMP,&
 & PTB_CMEM,&
 & KSTYPE) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM, JPRB
USE YOMSEKF , ONLY : T2M_FG, TD2M_FG, VOL_SM_FG, TTB_FG, NSLAY, N_SEKF_PT, STYPE
USE YOMSMOS , ONLY : NPOL_MAX, NANG_MAX
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PVSM_ML(YDGEOMETRY%YRDIM%NPROMA,NSLAY)
REAL(KIND=JPRB) ,INTENT(IN) :: PT2M_TEMP(YDGEOMETRY%YRDIM%NPROMA), PTD2M_TEMP(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTB_CMEM(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
INTEGER(KIND=JPIM),INTENT(IN) :: KSTYPE(YDGEOMETRY%YRDIM%NPROMA)
INTEGER(KIND=JPIM),INTENT(IN) :: KLON, KIDIA, KFDIA, KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
END SUBROUTINE STORE_SEKF_CV
END INTERFACE
