INTERFACE
SUBROUTINE STORE_VDFOUT(KJ,KSTART,KSTEP,&
 & KIDIA,KFDIA,KLON,KLEV,KLEVS,KTILES,KSTGLO,&
 & PWSA,PTSA, PAZ0M,PAZ0H,&
 & PTCFL,PDCFL,&
 & PFRSOTI,PEVAPSNW,&
 & PTENT,PTENQ,PTENL,PTENI,PTENA,PTENU,PTENV,&
 & PTLE1, PTL,&
 & PUSTRTI,PVSTRTI,PAHFSTI,PEVAPTI,PTSKTI,&
 & PTOFDU,PTOFDV) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KJ
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PWSA(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSA(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PAZ0M (KLON),PAZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTCFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDCFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSOTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVAPSNW(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENQ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENI(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLE1(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFSTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVAPTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSKTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PTOFDU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTOFDV(KLON)
END SUBROUTINE STORE_VDFOUT
END INTERFACE
