INTERFACE
SUBROUTINE STORE (KN,KFLAG,KREC,PFIELD)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KN
INTEGER(KIND=JPIM),INTENT(IN) :: KFLAG
INTEGER(KIND=JPIM),INTENT(IN) :: KREC
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFIELD(KN)
END SUBROUTINE STORE
END INTERFACE
