INTERFACE
SUBROUTINE STORD(ROBODY,KCURPO,LDLOCAL)
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
TYPE(IFS_DBASE_VIEW), INTENT(INOUT) :: ROBODY
INTEGER(KIND=JPIM),INTENT(IN) :: KCURPO
LOGICAL ,INTENT(IN) :: LDLOCAL
END SUBROUTINE STORD
END INTERFACE
