INTERFACE
SUBROUTINE SU0PHY(YDMODEL,KULOUT)
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM ,JPRB
TYPE(MODEL),TARGET,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE SU0PHY
END INTERFACE
