INTERFACE
SUBROUTINE SU_AEROP(YDEAERATM,YDEAERLID,YDEAERSRC)
USE YOEAERATM , ONLY : TEAERATM
USE YOEAERSRC, ONLY : TEAERSRC
USE YOEAERLID, ONLY : TEAERLID
TYPE(TEAERATM),INTENT(INOUT):: YDEAERATM
TYPE(TEAERLID),INTENT(INOUT):: YDEAERLID
TYPE(TEAERSRC),INTENT(INOUT):: YDEAERSRC
END SUBROUTINE SU_AEROP
END INTERFACE
