INTERFACE
SUBROUTINE SU_AERV&
 & (YDERAD, KLEV , PETAH,&
 & PVDAESS, PVDAEDU, PVDAEOM, PVDAEBC, PVDAESU&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOERAD ,ONLY : TERAD
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PETAH(KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDAESS(KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDAEDU(KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDAEOM(KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDAEBC(KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDAESU(KLEV+1)
END SUBROUTINE SU_AERV
END INTERFACE
