INTERFACE
SUBROUTINE SU_GRIB_API(YDGEOMETRY,YDVAB,LDMCC04,YDGBH,YDFPUSERGEO)
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE GRIB_HANDLES_MOD , ONLY : TYPE_GRIB_HANDLES
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMVERT , ONLY : TVAB
TYPE(GEOMETRY), INTENT(IN),TARGET :: YDGEOMETRY
TYPE(TVAB), INTENT(IN) :: YDVAB
LOGICAL ,INTENT(IN) :: LDMCC04
TYPE(TYPE_GRIB_HANDLES),INTENT(INOUT) :: YDGBH
TYPE (TFPUSERGEO), INTENT(IN), OPTIONAL :: YDFPUSERGEO
END SUBROUTINE SU_GRIB_API
END INTERFACE
