INTERFACE
SUBROUTINE SU_SUBSPACE(YDGEOMETRY,YDDIMF)
USE YOMDIMF , ONLY : TDIMF
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TDIMF) ,INTENT(INOUT):: YDDIMF
END SUBROUTINE SU_SUBSPACE
END INTERFACE
