INTERFACE
SUBROUTINE SU_UVRADI(YDEUVRAD,KUV)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOE_UVRAD, ONLY : TEUVRAD
TYPE(TEUVRAD) ,INTENT(INOUT) :: YDEUVRAD
INTEGER(KIND=JPIM),INTENT(IN) :: KUV
END SUBROUTINE SU_UVRADI
END INTERFACE
