INTERFACE
SUBROUTINE SUALB2SI ( YDEPHY,KIDIA, KFDIA, KLON, KMNTH, KTILES,&
 & KDDN, KMMN, KMON, KSECO, KSW,&
 & LDNH,&
 & PALBF , PALCOEFF,&
 & PASN,&
 & PFRTI , PMU0 ,&
 & PALBD , PALBP&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHY) ,INTENT(INOUT):: YDEPHY
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KMNTH
INTEGER(KIND=JPIM), INTENT(IN) :: KTILES
INTEGER(KIND=JPIM), INTENT(IN) :: KDDN
INTEGER(KIND=JPIM), INTENT(IN) :: KMMN
INTEGER(KIND=JPIM), INTENT(IN) :: KMON(KMNTH)
INTEGER(KIND=JPIM), INTENT(IN) :: KSECO
INTEGER(KIND=JPIM), INTENT(IN) :: KSW
REAL(KIND=JPRB), INTENT(IN) :: PALBF(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PALCOEFF(:,:)
REAL(KIND=JPRB), INTENT(IN) :: PASN(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PFRTI(KLON,KTILES)
REAL(KIND=JPRB), INTENT(IN) :: PMU0(KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PALBD(KLON,KSW)
REAL(KIND=JPRB), INTENT(OUT) :: PALBP(KLON,KSW)
LOGICAL, INTENT(IN) :: LDNH(KLON)
END SUBROUTINE SUALB2SI
END INTERFACE
