INTERFACE
SUBROUTINE SUALTDH(YDDIMV,YDML_DIAG,YDARPHY,YDPHY)
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE YOMDIMV , ONLY : TDIMV
USE YOMPHY , ONLY : TPHY
USE YOMARPHY , ONLY : TARPHY
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TARPHY),INTENT(IN) :: YDARPHY
TYPE(MODEL_DIAGNOSTICS_TYPE),INTENT(INOUT):: YDML_DIAG
TYPE(TPHY) ,INTENT(IN) :: YDPHY
END SUBROUTINE SUALTDH
END INTERFACE
