INTERFACE
SUBROUTINE SUALCTV_ENS(YDGEOMETRY,YDCVA_STRUCT,YDCVA_DATA)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCVA , ONLY : CVA_DATA_TYPE
USE CONTROL_VECTORS_DATA_MIX, ONLY : SETUP_CTLVEC, CONTROL_VECTOR_DATA_STRUCT
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(CONTROL_VECTOR_DATA_STRUCT), POINTER, INTENT(IN) :: YDCVA_STRUCT
TYPE(CVA_DATA_TYPE), POINTER, INTENT(INOUT) :: YDCVA_DATA
END SUBROUTINE SUALCTV_ENS
END INTERFACE
