INTERFACE
SUBROUTINE SUBFPOS(YDFPOS,YDHOSTGEOMETRY,YDMODEL,KFPOS,YDPOSGEOMETRY,YDXPOSGEOMETRY,YDPOSVAB,CDNAM)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FULLPOS , ONLY : TFPOS
USE YOMVERT , ONLY : TVAB
TYPE(TFPOS) ,INTENT(OUT) :: YDFPOS
TYPE(GEOMETRY) ,INTENT(IN) :: YDHOSTGEOMETRY
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KFPOS
TYPE(GEOMETRY) ,INTENT(IN), OPTIONAL :: YDPOSGEOMETRY
TYPE(GEOMETRY) ,INTENT(IN), OPTIONAL :: YDXPOSGEOMETRY(:)
TYPE(TVAB) ,INTENT(IN), OPTIONAL :: YDPOSVAB
CHARACTER(LEN=*) ,INTENT(IN), OPTIONAL :: CDNAM
END SUBROUTINE SUBFPOS
END INTERFACE
