INTERFACE
SUBROUTINE SUBMAT(YDCST,YDGEOMETRY,YDDYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YOMCST , ONLY : TCST
TYPE(TCST), INTENT(IN) :: YDCST
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
END SUBROUTINE SUBMAT
END INTERFACE
