INTERFACE
SUBROUTINE SUCDDH(YDSURF,YDMODEL)
USE TYPE_MODEL , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
END SUBROUTINE SUCDDH
END INTERFACE
