INTERFACE
SUBROUTINE SUCFU(YDGEOMETRY,YDCFU,YDRIP,YDERAD,YDPHY,KULOUT,YDCFUPP)
USE YOMCFU , ONLY : TCFU, TCFU_KEYS
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMPHY , ONLY : TPHY
USE YOERAD , ONLY : TERAD
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(TCFU),TARGET , INTENT(INOUT) :: YDCFU
TYPE(TRIP) , INTENT(IN) :: YDRIP
TYPE(TERAD) , INTENT(INOUT) :: YDERAD
TYPE(TPHY) , INTENT(INOUT) :: YDPHY
INTEGER(KIND=JPIM), INTENT(IN) :: KULOUT
TYPE(TCFU_KEYS) , INTENT(IN), TARGET, OPTIONAL :: YDCFUPP
END SUBROUTINE SUCFU
END INTERFACE
