INTERFACE
SUBROUTINE SUCLOPN(YDERAD,KTSW,KSW,KLEV)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOERAD , ONLY : TERAD
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KTSW
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
END SUBROUTINE SUCLOPN
END INTERFACE
