INTERFACE
SUBROUTINE SUCLD(YDECLD,KLEV,PETA)
USE PARKIND1 ,ONLY : JPIM ,JPRB ,JPRD
USE YOECLD , ONLY : TECLD
TYPE(TECLD) ,INTENT(INOUT) :: YDECLD
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PETA(KLEV)
END SUBROUTINE SUCLD
END INTERFACE
