INTERFACE
SUBROUTINE SUCLDP(YDSTA,YDDIMV,YDECLDP)
USE YOMSTA , ONLY : TSTA
USE YOMDIMV , ONLY : TDIMV
USE YOECLDP , ONLY : TECLDP
TYPE(TSTA) ,INTENT(IN) :: YDSTA
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TECLDP),INTENT(INOUT), TARGET :: YDECLDP
END SUBROUTINE SUCLDP
END INTERFACE
