INTERFACE
SUBROUTINE SUCUMF2(YDSTA,YDDIMV,YDRIP,YDCUMFS,YDECUMF2,KSMAX)
USE YOMSTA , ONLY : TSTA
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
USE YOECUMF2 , ONLY : TECUMF2
USE YOMCUMFS , ONLY : TCUMFS
TYPE(TSTA) , INTENT(IN) :: YDSTA
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
TYPE(TRIP) , INTENT(IN) :: YDRIP
TYPE(TCUMFS) ,TARGET, INTENT(INOUT):: YDCUMFS
TYPE(TECUMF2),TARGET, INTENT(INOUT):: YDECUMF2
INTEGER(KIND=JPIM) , INTENT(IN) :: KSMAX
END SUBROUTINE SUCUMF2
END INTERFACE
