INTERFACE
SUBROUTINE SUCUMF(YDSTA,YDDIMV,YDECUMF)
USE YOMSTA , ONLY : TSTA
USE YOMDIMV , ONLY : TDIMV
USE YOECUMF , ONLY : TECUMF
TYPE(TSTA) ,INTENT(IN) :: YDSTA
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(TECUMF) ,INTENT(INOUT), TARGET :: YDECUMF
END SUBROUTINE SUCUMF
END INTERFACE
