INTERFACE
SUBROUTINE SUCVMNH(YDML_PHY_MF,KULOUT)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT), TARGET :: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE SUCVMNH
END INTERFACE
