INTERFACE
SUBROUTINE SUDEFO_TSTEP(YDDIM,YDRIP)
USE YOMDIM , ONLY : TDIM
USE YOMRIP , ONLY : TRIP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TRIP) , INTENT(INOUT):: YDRIP
END SUBROUTINE SUDEFO_TSTEP
END INTERFACE
