INTERFACE
SUBROUTINE SUDEFO_GFLATTR(YDMODEL,KGFLCONF)
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(MODEL) , INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KGFLCONF
END SUBROUTINE SUDEFO_GFLATTR
END INTERFACE
