INTERFACE
SUBROUTINE SUDFI(YDEPHY,YDRIP,YDPHY)
USE YOMRIP , ONLY : TRIP
USE YOMPHY , ONLY : TPHY
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHY),INTENT(INOUT) :: YDEPHY
TYPE(TPHY),INTENT(INOUT) :: YDPHY
TYPE(TRIP),INTENT(INOUT) :: YDRIP
END SUBROUTINE SUDFI
END INTERFACE
