INTERFACE
SUBROUTINE SUDIMO(YDGEOMETRY,KWINLEN,KULOUT,YDODB,CD_DBNAME)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KWINLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
CLASS(DBASE) ,INTENT(OUT) :: YDODB
CHARACTER(LEN=*),OPTIONAL,INTENT(IN) :: CD_DBNAME
END SUBROUTINE SUDIMO
END INTERFACE
