INTERFACE
SUBROUTINE SUECSO4 ( KINDAT, KMINUT )
 USE PARKIND1 ,ONLY : JPRD, JPIM ,JPRB
 INTEGER(KIND=JPIM),INTENT(IN) :: KINDAT
 INTEGER(KIND=JPIM),INTENT(IN) :: KMINUT
END SUBROUTINE SUECSO4
END INTERFACE
