INTERFACE
SUBROUTINE SUECFNAME(LDINC,CDLEVTYPE,KSTEP,PTSTEP,KSTOP,CDFNGG,CDFNSH)
USE PARKIND1 , ONLY : JPIM, JPRB
LOGICAL, INTENT(IN) :: LDINC
CHARACTER(LEN=1), INTENT(IN) :: CDLEVTYPE
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
INTEGER(KIND=JPIM), INTENT(IN) :: KSTOP
CHARACTER(LEN=*), INTENT(OUT) :: CDFNGG
CHARACTER(LEN=*), INTENT(OUT) :: CDFNSH
END SUBROUTINE SUECFNAME
END INTERFACE
