INTERFACE
SUBROUTINE SUECHK(YDGEOMETRY,YDDIMF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDIMF , ONLY : TDIMF
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TDIMF) ,INTENT(IN) :: YDDIMF
END SUBROUTINE SUECHK
END INTERFACE
