INTERFACE
SUBROUTINE SUEFRAME(CDMCA,LDMAP,KMSMAX,KSMAX,KDGL,KDLON,&
 & LDGARD,LDMRT,PELON0,PELAT0,PELONC,PELATC,PEDELX,PEDELY,&
 & PELON1,PELAT1,PELON2,PELAT2,&
 & PERPK,PELX,PELY,PEXWN,PEYWN,&
 & KDLUN,KDLUX,KDGUN,KDGUX,KBZONL,KBZONG,KFLEV,&
 & PVP00,PVALH,PVBH,KDOM,KS,KBWX,KBWY) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
CHARACTER(LEN=16) ,INTENT(IN) :: CDMCA
LOGICAL ,INTENT(IN) :: LDMAP
INTEGER(KIND=JPIM),INTENT(IN) :: KMSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KDGL
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
LOGICAL ,INTENT(IN) :: LDGARD
LOGICAL ,INTENT(IN) :: LDMRT
REAL(KIND=JPRB) ,INTENT(IN) :: PELON0
REAL(KIND=JPRB) ,INTENT(IN) :: PELAT0
REAL(KIND=JPRB) ,INTENT(IN) :: PELONC
REAL(KIND=JPRB) ,INTENT(IN) :: PELATC
REAL(KIND=JPRB) ,INTENT(IN) :: PEDELX
REAL(KIND=JPRB) ,INTENT(IN) :: PEDELY
REAL(KIND=JPRB) ,INTENT(IN) :: PELON1
REAL(KIND=JPRB) ,INTENT(IN) :: PELAT1
REAL(KIND=JPRB) ,INTENT(IN) :: PELON2
REAL(KIND=JPRB) ,INTENT(IN) :: PELAT2
REAL(KIND=JPRB) ,INTENT(IN) :: PERPK
REAL(KIND=JPRB) ,INTENT(IN) :: PELX
REAL(KIND=JPRB) ,INTENT(IN) :: PELY
REAL(KIND=JPRB) ,INTENT(IN) :: PEXWN
REAL(KIND=JPRB) ,INTENT(IN) :: PEYWN
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUN
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUN
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUX
INTEGER(KIND=JPIM),INTENT(IN) :: KBZONL
INTEGER(KIND=JPIM),INTENT(IN) :: KBZONG
REAL(KIND=JPRB) ,INTENT(IN) :: PVP00
REAL(KIND=JPRB) ,INTENT(IN) :: PVALH(0:KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVBH(0:KFLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KDOM
INTEGER(KIND=JPIM),INTENT(IN) :: KS
INTEGER(KIND=JPIM),INTENT(IN) :: KBWX
INTEGER(KIND=JPIM),INTENT(IN) :: KBWY
END SUBROUTINE SUEFRAME
END INTERFACE
