INTERFACE
SUBROUTINE SUEHOX1(KSLWIDE,KDGSA,KDGEN,KFRSTLOFF,KPROMA,KEND,PLAT,PLON,PDELX,&
 & PDELY,KDLUN,KDLUX,KDGUN,KDGUX,KLA,KLO) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KSLWIDE
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSA
INTEGER(KIND=JPIM),INTENT(IN) :: KDGEN
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELX
REAL(KIND=JPRB) ,INTENT(IN) :: PDELY
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUN
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUN
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUX
INTEGER(KIND=JPIM),INTENT(OUT) :: KLA(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLO(KPROMA,2*KSLWIDE)
END SUBROUTINE SUEHOX1
END INTERFACE
