INTERFACE
SUBROUTINE SUENSCOV(YDGEOMETRY,YDFIELDS,YDMODEL)
 USE TYPE_MODEL , ONLY : MODEL
 USE FIELDS_MOD , ONLY : FIELDS
 USE YOMENSCOV
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
 TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
 TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
END SUBROUTINE SUENSCOV
END INTERFACE
