INTERFACE
SUBROUTINE SUFPCNT(KFRFPOS,KFPOSTS,KFPOSTSMIN,CDIRLST,CDPATH,CDMONIPATH_IN,CDMONIPATH_OUT,CDFPNCF,KFPCONF,YDFPCNT,CDNAM)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMFPCNT , ONLY : TFPCNT
INTEGER(KIND=JPIM), INTENT(IN) :: KFRFPOS
INTEGER(KIND=JPIM), INTENT(IN) :: KFPOSTS(0:)
INTEGER(KIND=JPIM), INTENT(IN) :: KFPOSTSMIN(0:)
CHARACTER(LEN=*), INTENT(IN) :: CDIRLST
CHARACTER(LEN=*), INTENT(IN) :: CDPATH
CHARACTER(LEN=*), INTENT(IN) :: CDMONIPATH_IN
CHARACTER(LEN=*), INTENT(IN) :: CDMONIPATH_OUT
CHARACTER(LEN=*), INTENT(IN) :: CDFPNCF
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCONF
TYPE(TFPCNT), INTENT(OUT) :: YDFPCNT
CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: CDNAM
END SUBROUTINE SUFPCNT
END INTERFACE
