INTERFACE
SUBROUTINE SUFPG2(YDNAMFPINT,YDNAMFPSCI,KFPDOM,YDFPUSERGEO,YDGEOMETRY,KFPRGP,PCO_EZO,LDPOSHOR,PFPLA,PFPLO,PFPGM,PFPNORX,PFPNORY,&
 & KNUMD,PFPMS) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMFPC , ONLY : TNAMFPINT, TNAMFPSCI, LTRACEFP
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
TYPE (TNAMFPINT), INTENT(IN) :: YDNAMFPINT
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
INTEGER(KIND=JPIM),INTENT(IN) :: KFPDOM
TYPE (TFPUSERGEO), INTENT(IN) :: YDFPUSERGEO(KFPDOM)
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRGP
REAL(KIND=JPRB) ,INTENT(IN) :: PCO_EZO
LOGICAL ,INTENT(OUT) :: LDPOSHOR
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLA(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPLO(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPGM(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPNORX(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPNORY(KFPRGP)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNUMD(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPMS(KFPRGP)
END SUBROUTINE SUFPG2
END INTERFACE
