INTERFACE
SUBROUTINE SUFPSUW(YDCLIMO,YDNAMFPINT,YDNAMFPSCI,YDAFN,KFPXFLD,YDFPGEOMETRY,YDFPSUW,YDFPWSTD,YDFPSTRUCT,&
 & YDGEOMETRY,YDSURF,YDMODEL) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMAFN , ONLY : TAFN
USE YOMFPC , ONLY : TNAMFPINT, TNAMFPSCI, LALLOFP, LTRACEFP
USE YOMWFPB , ONLY : TFPWSTD, TFPSUW
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMFPGEOMETRY , ONLY : TFPGEOMETRY
USE TYPE_FPOSBUF , ONLY : FPOSBUF
TYPE(FPOSBUF) , INTENT(IN) :: YDCLIMO
TYPE(TNAMFPINT) , INTENT(IN) :: YDNAMFPINT
TYPE(TNAMFPSCI) , INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN) , INTENT(IN) :: YDAFN
INTEGER(KIND=JPIM) , INTENT(IN) :: KFPXFLD
TYPE(TFPGEOMETRY) , INTENT(IN) :: YDFPGEOMETRY
TYPE(TFPSUW) , INTENT(INOUT) :: YDFPSUW
TYPE(TFPWSTD) , INTENT(IN) :: YDFPWSTD
TYPE(SL_STRUCT) , INTENT(IN) :: YDFPSTRUCT
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) , INTENT(IN) :: YDSURF
TYPE(MODEL) , INTENT(IN) :: YDMODEL
END SUBROUTINE SUFPSUW
END INTERFACE
