INTERFACE
SUBROUTINE SUFPOROG(KFIELDS,KXPHIS,YDFPGEO,KFPDOM,KFPRESOL,KSPEC2,PBUF)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMFPGEO , ONLY : TFPGEO
INTEGER(KIND=JPIM), INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM), INTENT(IN) :: KXPHIS
TYPE(TFPGEO), INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KFPRESOL(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KSPEC2(KFPDOM)
REAL(KIND=JPRB) , INTENT(INOUT) :: PBUF(YDFPGEO%NFPROMA,KFIELDS,YDFPGEO%NFPBLOCS)
END SUBROUTINE SUFPOROG
END INTERFACE
