INTERFACE
SUBROUTINE SUFPFILTERS(YDNAMFPSCI,YDNAMFPF,YDNAMFPL,YDGEOMETRY,KFPDOM,KFPCONF,KSF,CDNAME,YDFPFILTERS)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMFPC , ONLY : LTRACEFP, TNAMFPL, TNAMFPSCI
USE YOMFPF , ONLY : TNAMFPF
USE YOMFPFILTERS, ONLY : TFPFILTERS
TYPE(TNAMFPSCI) , INTENT(IN) :: YDNAMFPSCI
TYPE(TNAMFPF), INTENT(IN) :: YDNAMFPF
TYPE(TNAMFPL), INTENT(IN) :: YDNAMFPL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCONF
INTEGER(KIND=JPIM), INTENT(IN) :: KSF(:)
CHARACTER(LEN=*), INTENT(IN) :: CDNAME(:)
TYPE(TFPFILTERS), INTENT(OUT) :: YDFPFILTERS
END SUBROUTINE SUFPFILTERS
END INTERFACE
