INTERFACE
SUBROUTINE SUFPVSET_DIR(YDQTYPE,KFPTRV,KVSETSC,KVSETVD)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
INTEGER(KIND=JPIM),INTENT(IN) :: KFPTRV
INTEGER(KIND=JPIM),INTENT(OUT) :: KVSETSC(:)
INTEGER(KIND=JPIM),INTENT(OUT) :: KVSETVD(:)
END SUBROUTINE SUFPVSET_DIR
END INTERFACE
