INTERFACE
SUBROUTINE SUFPPHY(YDAFN,LDPHYS,YDFPFIELDS,KFPDOM,CDFPDOM,LDNOFIL,CDYFILE,YGFL,YDEAERATM,LDLAG,LDOCEDELAY,LDOCE,YDRQPHY)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE TYPE_FPFIELDS, ONLY : TFPFIELDS
USE YOMAFN , ONLY : TAFN
USE YOMFP4L, ONLY : TRQFP
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOEAERATM , ONLY : TEAERATM
TYPE (TAFN), INTENT(IN) :: YDAFN
LOGICAL, INTENT(IN) :: LDPHYS
TYPE (TFPFIELDS), INTENT(IN) :: YDFPFIELDS
INTEGER(KIND=JPIM),INTENT(IN) :: KFPDOM
CHARACTER(LEN=*), INTENT(IN) :: CDFPDOM(KFPDOM)
LOGICAL, INTENT(IN) :: LDNOFIL
CHARACTER(LEN=*), INTENT(IN) :: CDYFILE
TYPE(TYPE_GFLD), INTENT(IN) :: YGFL
TYPE(TEAERATM), INTENT(IN) :: YDEAERATM
LOGICAL, INTENT(IN) :: LDLAG
LOGICAL, INTENT(IN) :: LDOCEDELAY
LOGICAL, INTENT(IN) :: LDOCE
TYPE(TRQFP), INTENT(OUT) :: YDRQPHY
END SUBROUTINE SUFPPHY
END INTERFACE
