INTERFACE
SUBROUTINE SUFPSURF(YDFPOS,KPPEDR,KVCLIX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE FULLPOS , ONLY : TFPOS
TYPE(TFPOS), INTENT(IN) :: YDFPOS
INTEGER(KIND=JPIM), INTENT(INOUT) :: KPPEDR
INTEGER(KIND=JPIM), INTENT(INOUT) :: KVCLIX
END SUBROUTINE SUFPSURF
END INTERFACE
