INTERFACE
SUBROUTINE SUFPDISTRIB(YDNAMFPSCI,YDFPGEO_DEP,YDFPGIND,YDFPGEO,YDFPUSERGEO,KNUMPROCFP_DEP,KNUMPROCFP)
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE YOMFPGEO , ONLY : TFPGEO
USE YOMFPGIND, ONLY : TFPGIND
USE YOMFPC , ONLY : TNAMFPSCI, LALLOFP
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO_DEP
TYPE (TFPGIND), INTENT(INOUT) :: YDFPGIND
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO
TYPE (TFPUSERGEO) ,INTENT(IN) :: YDFPUSERGEO(:)
INTEGER(KIND=JPIM),INTENT(IN) :: KNUMPROCFP_DEP(YDFPGEO_DEP%NFPRGPG)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNUMPROCFP(YDFPGEO%NFPRGPG)
END SUBROUTINE SUFPDISTRIB
END INTERFACE
