INTERFACE
SUBROUTINE SUFPFIELDS(YDNAMFPL,KFLEVG,YDFPFIELDS,YDFPVAB,LDPRINT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPFIELDS, ONLY : TFPFIELDS, ALLOC_FPFIELDS, PRINT_FPFIELDS
USE YOMFPC , ONLY : TNAMFPL
USE YOMVERT , ONLY : TVAB
TYPE(TNAMFPL) ,INTENT(IN) :: YDNAMFPL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
TYPE(TFPFIELDS) ,INTENT(OUT) :: YDFPFIELDS
TYPE(TVAB) ,INTENT(IN), OPTIONAL :: YDFPVAB
LOGICAL ,INTENT(IN), OPTIONAL :: LDPRINT
END SUBROUTINE SUFPFIELDS
END INTERFACE
