INTERFACE
SUBROUTINE SUFPGRIB(CDFPCLIFNAME,YDFPGEO,KFPDOM,YDFPUSERGEO,YDFPOFN)
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE YOMFPGEO, ONLY : TFPGEO
USE TYPE_FPOFN, ONLY : TFPOFN
CHARACTER(LEN=*), INTENT(IN) :: CDFPCLIFNAME(:)
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
TYPE (TFPUSERGEO) , INTENT(IN) :: YDFPUSERGEO(KFPDOM)
TYPE (TFPOFN), INTENT(INOUT) :: YDFPOFN(KFPDOM)
END SUBROUTINE SUFPGRIB
END INTERFACE
