INTERFACE
SUBROUTINE SUFPXFU(YDFPOS,YDXFU)
USE YOMXFU , ONLY : TXFU_KEYS
USE FULLPOS , ONLY : TFPOS
TYPE(TFPOS), INTENT(IN) :: YDFPOS
TYPE(TXFU_KEYS),INTENT(INOUT) :: YDXFU
END SUBROUTINE SUFPXFU
END INTERFACE
