INTERFACE
SUBROUTINE SUFPMODELGEO(LDLAM,YDGEOMETRY,CDFPDOM,YDFPUSERGEO,YDHOSTGEOM,KFPCONF,KFPBOYD)
USE PARKIND1 ,ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO, ALLOC_FPUSERGEO, PRINT_FPUSERGEO, CHECK_FPUSERGEO
LOGICAL , INTENT (IN) :: LDLAM
TYPE (GEOMETRY) , INTENT (IN) :: YDGEOMETRY
CHARACTER(LEN=*) , INTENT (IN) :: CDFPDOM
TYPE (TFPUSERGEO), INTENT (INOUT) :: YDFPUSERGEO
TYPE (GEOMETRY) , INTENT (IN) :: YDHOSTGEOM
INTEGER(KIND=JPIM), INTENT (IN) :: KFPCONF
INTEGER(KIND=JPIM), INTENT (IN) :: KFPBOYD
END SUBROUTINE SUFPMODELGEO
END INTERFACE
