INTERFACE
SUBROUTINE SUFPMAPF(KFPDOM,YDFPUSERGEO,KFPRGPG_DEP,PGM)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
TYPE (TFPUSERGEO), INTENT(IN) :: YDFPUSERGEO(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KFPRGPG_DEP
REAL(KIND=JPRB), INTENT(INOUT) :: PGM(KFPRGPG_DEP)
END SUBROUTINE SUFPMAPF
END INTERFACE
