INTERFACE
SUBROUTINE SUFPINIF(YDGEOMETRY,YDMODEL,LDCLI,LDRESET,LDREADCFU,LDREADXFU,YDFIELDS,KINITMONTH)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE FIELDS_MOD , ONLY : FIELDS
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
LOGICAL , INTENT(IN) :: LDCLI
LOGICAL , INTENT(IN) :: LDRESET
LOGICAL , INTENT(IN) :: LDREADCFU
LOGICAL , INTENT(IN) :: LDREADXFU
TYPE(FIELDS) , INTENT(INOUT) :: YDFIELDS
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KINITMONTH
END SUBROUTINE SUFPINIF
END INTERFACE
