INTERFACE
SUBROUTINE SUFPTR2(YDRQPHY,YDRQAUX,KFPINPHY,YDNAMFPSCI,YDAFN,LDPHYS,LDHPOS,LDFPOSHOR,YDRQDYN)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMAFN , ONLY : TAFN
USE YOMFPC , ONLY : TNAMFPSCI, LTRACEFP, LALLOFP
USE YOMFP4L , ONLY : TRQFP, IFPSEARCH
USE YOM4FPOS, ONLY : TRQFPDYN
TYPE(TRQFP), INTENT(IN) :: YDRQPHY
TYPE(TRQFP), INTENT(OUT) :: YDRQAUX
INTEGER(KIND=JPIM), INTENT(IN) :: KFPINPHY
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE (TAFN), INTENT(IN) :: YDAFN
LOGICAL , INTENT(IN) :: LDPHYS
LOGICAL , INTENT(IN) :: LDHPOS
LOGICAL , INTENT(IN) :: LDFPOSHOR
TYPE(TRQFPDYN), INTENT(IN), OPTIONAL :: YDRQDYN
END SUBROUTINE SUFPTR2
END INTERFACE
