INTERFACE
SUBROUTINE SUFPDATA(YDFPOS,YDGEOMETRY,YDSURF,YDMODEL,KMMCLI,KITER,YDFPDATA,LDUPDSUW)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE FULLPOS , ONLY : TFPOS, TFPDATA
TYPE(TFPOS) ,INTENT(IN), TARGET :: YDFPOS
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
INTEGER(KINd=JPIM),INTENT(IN) :: KMMCLI
INTEGER(KIND=JPIM),INTENT(IN) :: KITER
TYPE(TFPDATA) ,INTENT(INOUT) :: YDFPDATA
LOGICAL ,INTENT(IN), OPTIONAL :: LDUPDSUW
END SUBROUTINE SUFPDATA
END INTERFACE
