INTERFACE
SUBROUTINE SUFPDOM(CDOM,KXDOM,KFPDOM,CDSTRIN,KDIM,KSTRIN,KNDOM,KDOM)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KXDOM
INTEGER(KIND=JPIM),INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KSTRIN
CHARACTER(LEN=*) ,INTENT(IN) :: CDOM(KXDOM)
CHARACTER(LEN=*) ,INTENT(IN) :: CDSTRIN(KDIM)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNDOM(KSTRIN)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDOM(KFPDOM,KSTRIN)
END SUBROUTINE SUFPDOM
END INTERFACE
