INTERFACE
SUBROUTINE SUFW(YDLAP,YDDIM,YDEGEO,YDELAP)
USE YOMLAP , ONLY : TLAP
USE YOMDIM , ONLY : TDIM
USE YEMGEO , ONLY : TEGEO
USE YEMLAP , ONLY : TLEP
TYPE(TLAP) , INTENT(IN) :: YDLAP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TEGEO) , INTENT(IN) :: YDEGEO
TYPE(TLEP) , INTENT(IN) :: YDELAP
END SUBROUTINE SUFW
END INTERFACE
