INTERFACE
SUBROUTINE SUGEM_NAML(YDGEOMETRY,KSUPERSEDE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT),TARGET :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSUPERSEDE
END SUBROUTINE SUGEM_NAML
END INTERFACE
