INTERFACE
SUBROUTINE SUGEOMETRY(YDGEOMETRY,KSUPERSEDE)
USE TYPE_GEOMETRY , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM,JPRB
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSUPERSEDE
END SUBROUTINE SUGEOMETRY
END INTERFACE
