INTERFACE
SUBROUTINE SUGENORD(KSTTYP,KFPRGP,PSTRET,PMUCEN,PLOCEN,&
 & PSINLAT,PSINLAM,PCOSLAM,PFPNORX,PFPNORY) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRGP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTTYP
REAL(KIND=JPRB) ,INTENT(IN) :: PSTRET
REAL(KIND=JPRB) ,INTENT(IN) :: PMUCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PLOCEN
REAL(KIND=JPRB) ,INTENT(IN) :: PSINLAT(KFPRGP)
REAL(KIND=JPRB) ,INTENT(IN) :: PSINLAM(KFPRGP)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOSLAM(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPNORX(KFPRGP)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFPNORY(KFPRGP)
END SUBROUTINE SUGENORD
END INTERFACE
