INTERFACE
SUBROUTINE SUGEM1A(YDGEOMETRY,KSUPERSEDE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSUPERSEDE
END SUBROUTINE SUGEM1A
END INTERFACE
