INTERFACE
SUBROUTINE SUGFL1(YDMODEL,KGFLCONF)
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
USE ARPCLIM_CHEM_MODULE
TYPE(MODEL),INTENT(INOUT), TARGET :: YDMODEL
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KGFLCONF
END SUBROUTINE SUGFL1
END INTERFACE
