INTERFACE
SUBROUTINE SUGFL(YDDIMV,YDMODEL,KGFLCONF)
USE TYPE_MODEL , ONLY : MODEL
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KGFLCONF
END SUBROUTINE SUGFL
END INTERFACE
