INTERFACE
SUBROUTINE SUGOMS(YDGEOMETRY,YDSURF,YDDPHY,YDML_GCONF,YDSLREP,YDPHY,YDOBSLOCS,YDGOM,LDOBSTL,LDCASIG)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMSLREP , ONLY : TSLREP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMDPHY , ONLY : TDPHY
USE YOMPHY , ONLY : TPHY
USE YOMDB
USE GOM_MOD , ONLY : GID, GINTERP, GOM_INITIALISE, TYPE_GOM, NGOMVAR,&
 & GOM_SET_INTERPOLATED, GOM_IS_INTERPOLATED, GOM_SET_INTERP_TYPE,&
 & GOM_SUBVAR_CODES_SET 
USE YOMLOCS , ONLY : TOBSLOCS
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TDPHY) ,INTENT(INOUT) :: YDDPHY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TPHY) ,INTENT(INOUT) :: YDPHY
TYPE(TSLREP) ,INTENT(INOUT) :: YDSLREP
TYPE(TOBSLOCS),INTENT(IN) :: YDOBSLOCS
TYPE(TYPE_GOM),INTENT(INOUT) :: YDGOM
LOGICAL ,INTENT(IN) :: LDOBSTL
LOGICAL, OPTIONAL, INTENT(IN) :: LDCASIG
END SUBROUTINE SUGOMS
END INTERFACE
