INTERFACE
SUBROUTINE SUGRIDUA_MAP_PART1(YDGEOMETRY,YDGFL,YDML_GCONF,YDSUGACTX,PIOPROC1A,PIOPROC2A,PTIME,KFILE)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
USE IOGRIDUA_MOD , ONLY : IOGRIDUA_COUNT,&
 & IOGRIDUA_SELECTD,&
 & NIOGRIDUACT_READ,&
 & SUGRIDUA_MAP_CTX 
TYPE (GEOMETRY) , INTENT (IN) :: YDGEOMETRY
TYPE (TGFL) , INTENT (INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE), INTENT (INOUT) :: YDML_GCONF
TYPE (SUGRIDUA_MAP_CTX) , INTENT (INOUT) :: YDSUGACTX
REAL (KIND=JPRB) , INTENT (IN) :: PIOPROC1A
REAL (KIND=JPRB) , INTENT (IN) :: PIOPROC2A
REAL (KIND=JPRB) , INTENT (IN) :: PTIME
INTEGER (KIND=JPIM) , INTENT (IN), OPTIONAL :: KFILE
END SUBROUTINE SUGRIDUA_MAP_PART1
END INTERFACE
