INTERFACE
SUBROUTINE SUGRIDG(YDGEOMETRY,YDSURF,YDEPHY,YDMCC,YDDYN,KFILE,LDSPOR,PBLH,PFIELD)
USE YOEPHY , ONLY : TEPHY
USE YOMDYN , ONLY : TDYN
USE YOMMCC , ONLY : TMCC
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF, GPOPER, TYPE_SFL_COMM
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
INTEGER(KIND=JPIM),INTENT(IN) :: KFILE
LOGICAL ,INTENT(OUT) :: LDSPOR
REAL(KIND=JPRB) ,OPTIONAL,INTENT(INOUT) :: PBLH(:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(INOUT) :: PFIELD(:,:)
END SUBROUTINE SUGRIDG
END INTERFACE
