INTERFACE
SUBROUTINE SUGRIDA(YDGEOMETRY,YDSURF,YDMODEL,KFILE)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM), INTENT(IN) :: KFILE
END SUBROUTINE SUGRIDA
END INTERFACE
