INTERFACE
SUBROUTINE SUGRIDUG2(YDGEOMETRY,YDML_GCONF,YDSPEC,YDGFL)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
TYPE(TGFL), INTENT(INOUT) :: YDGFL
END SUBROUTINE SUGRIDUG2
END INTERFACE
