INTERFACE
SUBROUTINE SUGRIDUA(YDGEOMETRY,YDGFL,YDML_GCONF,YDML_LBC,KFILE)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
TYPE (GEOMETRY) , INTENT (IN) :: YDGEOMETRY
TYPE (TGFL) , INTENT (INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE (TELBC_MODEL) , INTENT (IN) :: YDML_LBC
INTEGER (KIND=JPIM), INTENT (IN) :: KFILE
END SUBROUTINE SUGRIDUA
END INTERFACE
