INTERFACE
SUBROUTINE SUGRCLIA(YDGEOMETRY,YDSURF,YDMCC,YDRIP,YDML_LBC,LDINT,KLI,KINITMONTH)
USE YOMMCC , ONLY : TMCC
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMRIP , ONLY : TRIP
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
TYPE(TELBC_MODEL) ,INTENT(IN) :: YDML_LBC
LOGICAL ,INTENT(IN) :: LDINT
INTEGER(KIND=JPIM),INTENT(OUT) :: KLI
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KINITMONTH
END SUBROUTINE SUGRCLIA
END INTERFACE
