INTERFACE
SUBROUTINE SUGRIDU(YDGEOMETRY,YDEPHLI,YDML_GCONF,YDML_LBC,YDSPEC,YDGFL,KFILE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOEPHLI , ONLY : TEPHLI
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM ,JPRB
USE SPECTRAL_FIELDS_MOD , ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TEPHLI) , INTENT(INOUT) :: YDEPHLI
TYPE(MODEL_GENERAL_CONF_TYPE), INTENT(INOUT) :: YDML_GCONF
TYPE(TELBC_MODEL) , INTENT(IN) :: YDML_LBC
TYPE(SPECTRAL_FIELD) , INTENT(INOUT) :: YDSPEC
TYPE(TGFL) , INTENT(INOUT) :: YDGFL
INTEGER(KIND=JPIM) , INTENT(IN) :: KFILE
END SUBROUTINE SUGRIDU
END INTERFACE
