INTERFACE
SUBROUTINE SUGRIDO(YDGEOMETRY,YDSURF,YDEPHY,KFILE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM , JPRB
USE YOEPHY , ONLY : TEPHY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TEPHY) ,INTENT(INOUT):: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KFILE
END SUBROUTINE SUGRIDO
END INTERFACE
