INTERFACE
SUBROUTINE SUGRCFU(YDGEOMETRY,YDCFU,YDRIP,YDML_LBC,KFILE)
USE YOMCFU , ONLY : TCFU
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TCFU) , INTENT(INOUT) :: YDCFU
TYPE(TRIP) , INTENT(INOUT) :: YDRIP
TYPE(TELBC_MODEL) , INTENT(IN) :: YDML_LBC
INTEGER (KIND=JPIM), INTENT(IN) :: KFILE
END SUBROUTINE SUGRCFU
END INTERFACE
