INTERFACE
SUBROUTINE SUGRIDUA_MAP_PART2(YDGEOMETRY,YDGFL,YGFL,KREP,YDSUGACTX)
USE YOM_YGFL , ONLY : TYPE_GFLD
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
USE IOGRIDUA_MOD, ONLY : IOGRIDUA_COUNT,&
 & IOGRIDUA_SELECTD,&
 & NIOGRIDUACT_READ,&
 & SUGRIDUA_MAP_CTX 
TYPE(GEOMETRY) , INTENT (IN) :: YDGEOMETRY
TYPE(TGFL) , INTENT (INOUT) :: YDGFL
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
INTEGER (KIND=JPIM) , INTENT (OUT) :: KREP
TYPE (SUGRIDUA_MAP_CTX), INTENT (INOUT) :: YDSUGACTX
END SUBROUTINE SUGRIDUA_MAP_PART2
END INTERFACE
