INTERFACE
SUBROUTINE SUGWD(YDSTA,YDEGWD,YDEPHY,KULOUT,KLEV,PVAH,PVBH)
USE YOMSTA , ONLY : TSTA
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOEGWD , ONLY : TEGWD
TYPE(TSTA) ,INTENT(IN) :: YDSTA
TYPE(TEGWD),TARGET,INTENT(INOUT):: YDEGWD
TYPE(TEPHY) ,INTENT(INOUT):: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
REAL(KIND=JPRB) ,INTENT(IN) :: PVAH(KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PVBH(KLEV+1)
END SUBROUTINE SUGWD
END INTERFACE
