INTERFACE
SUBROUTINE SUHDVP(YDGEOMETRY,YDDYN,PDILEV,PDILEV_SLD,PDILEVS,LDMESO,KSTDV2)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
REAL(KIND=JPRB),INTENT(OUT) :: PDILEV(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),INTENT(OUT) :: PDILEV_SLD(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),INTENT(OUT) :: PDILEVS(YDGEOMETRY%YRDIMV%NFLEVG)
LOGICAL,INTENT(OUT) :: LDMESO
INTEGER(KIND=JPIM),INTENT(OUT) :: KSTDV2
END SUBROUTINE SUHDVP
END INTERFACE
