INTERFACE
SUBROUTINE SUHDIR(YDGEOMETRY,YDDYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
END SUBROUTINE SUHDIR
END INTERFACE
