INTERFACE
SUBROUTINE SUHESS(YDGEOMETRY,KMUPD,YD_PDIAG,YDYBAR,YDSBAR,KTBMIN,&
 & KLM,KILM,PSIZE,LDWARM) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE CONTROL_VECTORS_COMM_MOD
USE CONTROL_VECTORS_MOD
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KMUPD
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_PDIAG
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDYBAR(KMUPD)
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YDSBAR(KMUPD)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KTBMIN(5)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KLM(KMUPD+3)
INTEGER(KIND=JPIM) ,INTENT(OUT) :: KILM
REAL(KIND=JPRB) ,INTENT(OUT) :: PSIZE
LOGICAL ,INTENT(IN) :: LDWARM
END SUBROUTINE SUHESS
END INTERFACE
