INTERFACE
SUBROUTINE SUHEG(YDGEOMETRY,YDRIP,YDDYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT):: YDDYN
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE SUHEG
END INTERFACE
