INTERFACE
SUBROUTINE SUHOX1(KSLWIDE,KDGSA,KDGEN,KFRSTLOFF,KPROMA,KEND,P4JP,&
 & PI,KLOEN,PLATIN,PLAT,PLON,KLA,KLO) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KSLWIDE
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSA
INTEGER(KIND=JPIM),INTENT(IN) :: KDGEN
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: P4JP
REAL(KIND=JPRB) ,INTENT(IN) :: PI
INTEGER(KIND=JPIM),INTENT(IN) :: KLOEN(KDGSA+KFRSTLOFF:KDGEN+KFRSTLOFF)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATIN(KDGSA+KFRSTLOFF:KDGEN+KFRSTLOFF)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KEND)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLA(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLO(KPROMA,2*KSLWIDE)
END SUBROUTINE SUHOX1
END INTERFACE
