INTERFACE
SUBROUTINE SUHOWLSM(KDGSA,KDGEN,KFRSTLOFF,KPROMA,KEND,KAFPB,PCR,PLATIN,PRGMSD,PGMSF,&
 & KLSIM,KBINL,LDML,KLA,KL0,PDLAT,PDLO,PWXX,PWXY,&
 & PTMERGL,PTSIN,PLSMIN,PTSOUT,PLSMOUT,LDPSL) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE PARFPOS , ONLY : JPROW
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSA
INTEGER(KIND=JPIM),INTENT(IN) :: KDGEN
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KAFPB
REAL(KIND=JPRB) ,INTENT(IN) :: PCR(2)
REAL(KIND=JPRB) ,INTENT(IN) :: PLATIN(KDGSA+KFRSTLOFF:KDGEN+KFRSTLOFF)
REAL(KIND=JPRB) ,INTENT(IN) :: PRGMSD(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMSF(KEND)
INTEGER(KIND=JPIM),INTENT(IN) :: KLSIM
INTEGER(KIND=JPIM),INTENT(IN) :: KBINL
LOGICAL ,INTENT(IN) :: LDML
INTEGER(KIND=JPIM),INTENT(IN) :: KLA(KEND)
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMA,2*JPROW)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLAT(4,KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO(0:3,4,KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWXX(KPROMA,KBINL)
REAL(KIND=JPRB), OPTIONAL ,INTENT(OUT) :: PWXY(KPROMA,5:16)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PTMERGL
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PTSIN(KAFPB)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PLSMIN(KAFPB)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PTSOUT(KPROMA)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PLSMOUT(KPROMA)
LOGICAL, OPTIONAL ,INTENT(IN) :: LDPSL (4)
END SUBROUTINE SUHOWLSM
END INTERFACE
