INTERFACE
SUBROUTINE SUIAUINIF(YDGEOMETRY,YDGFL,YDEPHLI,YDML_GCONF,YDML_LBC,YDDYN,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOEPHLI , ONLY : TEPHLI
USE YOMDYN , ONLY : TDYN
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL) , INTENT(INOUT) :: YDGFL
TYPE(TDYN) , INTENT(INOUT) :: YDDYN
TYPE(TEPHLI) , INTENT(INOUT) :: YDEPHLI
TYPE(MODEL_GENERAL_CONF_TYPE), INTENT(INOUT) :: YDML_GCONF
TYPE(TELBC_MODEL) , INTENT(IN) :: YDML_LBC
TYPE(SPECTRAL_FIELD) , INTENT(INOUT) :: YDSP
END SUBROUTINE SUIAUINIF
END INTERFACE
