INTERFACE
SUBROUTINE SUINFCE(YDGEOMETRY,YDML_GCONF,YDBG,YD_JB_STRUCT)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE FIELDS_MOD , ONLY : FIELDS
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(FIELDS) , INTENT(IN) :: YDBG
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUINFCE
END INTERFACE
