INTERFACE
SUBROUTINE SUINIF_FP(YDFPS,YDGEOMETRY,YDSPEC,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,KSTEP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL , ONLY : TGFL
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE PARKIND1 , ONLY : JPRB, JPRD, JPIM
USE YOMFP_SERV , ONLY : FP_SERV
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE (FP_SERV) , INTENT (INOUT) :: YDFPS
TYPE (GEOMETRY) , INTENT (INOUT) :: YDGEOMETRY
TYPE(SPECTRAL_FIELD), INTENT (INOUT) :: YDSPEC
TYPE (TGFL) , INTENT (INOUT) :: YDGFL
TYPE (TSURF) , INTENT (INOUT) :: YDSURF
TYPE (TCFU) , INTENT (INOUT) :: YDCFU
TYPE (TXFU) , INTENT (INOUT) :: YDXFU
TYPE(MODEL) , INTENT (INOUT) :: YDMODEL
INTEGER (KIND=JPIM) , INTENT (INOUT) :: KSTEP
END SUBROUTINE SUINIF_FP
END INTERFACE
