INTERFACE
SUBROUTINE SUINTFLEX(YGFL,YDARPHY,YDPHY)
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMARPHY , ONLY : TARPHY
USE YOMPHY , ONLY : TPHY
TYPE(TARPHY),INTENT(INOUT):: YDARPHY
TYPE(TPHY),INTENT(INOUT):: YDPHY
TYPE(TYPE_GFLD),INTENT(INOUT):: YGFL
END SUBROUTINE SUINTFLEX
END INTERFACE
