INTERFACE
SUBROUTINE SUJBWAVELET0(YDDIM,YD_JB_STRUCT,CDFILE)
USE YOMDIM , ONLY : TDIM
USE YOMJG, ONLY : TYPE_JB_STRUCT
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
CHARACTER(LEN=*) , INTENT(IN) :: CDFILE
END SUBROUTINE SUJBWAVELET0
END INTERFACE
