INTERFACE
SUBROUTINE SUJBCOV(YDGEOMETRY,YDFIELDS,YDDIMF,YDDYN,YD_TRAJ,YD_JB_STRUCT)
USE YOMDIMF , ONLY : TDIMF
USE YOMDYN , ONLY : TDYN
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(TDIMF) ,INTENT(INOUT) :: YDDIMF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(FIELDS) ,INTENT(INOUT) :: YD_TRAJ
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUJBCOV
END INTERFACE
