INTERFACE
SUBROUTINE SUJBGPTOMAT(YDDIM,KSCALE,KNUMB,YD_PVC,PLON,PLAT,KGPTOMAT)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMWAVELET,ONLY : TYPE_WAVELETJB_VCOR_STRUCT
TYPE(TDIM) , INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM), INTENT(IN) :: KSCALE
INTEGER(KIND=JPIM), INTENT(IN) :: KNUMB
TYPE (TYPE_WAVELETJB_VCOR_STRUCT), INTENT(IN) :: YD_PVC
REAL(KIND=JPRB) , INTENT(IN) :: PLON(YDDIM%NPROMA)
REAL(KIND=JPRB) , INTENT(IN) :: PLAT(YDDIM%NPROMA)
INTEGER(KIND=JPIM), INTENT(OUT) :: KGPTOMAT(KNUMB)
END SUBROUTINE SUJBGPTOMAT
END INTERFACE
