INTERFACE
SUBROUTINE SUJBWAVALLO (YD_PVC, KSCALE, KCUTOFF, KLEVS,&
 & YD_IOSTREAM,YD_IOREQUEST,KJBW_INV,YD_JB_STRUCT) 
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMWAVELET, ONLY : TYPE_WAVELETJB_VCOR_STRUCT
USE YOMJG, ONLY : TYPE_JB_STRUCT
USE IOSTREAM_MIX, ONLY : IO_GET, TYPE_IOSTREAM, TYPE_IOREQUEST
USE MPL_MODULE
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
TYPE(TYPE_WAVELETJB_VCOR_STRUCT),INTENT(INOUT) :: YD_PVC
INTEGER(KIND=JPIM),INTENT(IN) :: KSCALE
INTEGER(KIND=JPIM),INTENT(IN) :: KCUTOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
TYPE(TYPE_IOSTREAM), INTENT(INOUT) :: YD_IOSTREAM
TYPE(TYPE_IOREQUEST), INTENT(INOUT) :: YD_IOREQUEST
INTEGER (KIND=JPIM),INTENT(IN) :: KJBW_INV
END SUBROUTINE SUJBWAVALLO
END INTERFACE
