INTERFACE
SUBROUTINE SUJBBAL(YDGEOMETRY,CDJBTYPE,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=10) ,INTENT(IN) :: CDJBTYPE
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUJBBAL
END INTERFACE
