INTERFACE
SUBROUTINE SUJBCHVAR(YDVAB,YDDIMV,YD_JB_STRUCT)
USE YOMVERT , ONLY : TVAB, VP00
USE YOMDIMV , ONLY : TDIMV
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(TVAB) , INTENT(IN) :: YDVAB
TYPE(TDIMV) , INTENT(IN) :: YDDIMV
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUJBCHVAR
END INTERFACE
