INTERFACE
SUBROUTINE SUJBCOR(YDGEOMETRY,CDJBTYPE,KPRT,PCOVTPS,PCOVP,PCOVU,PCOVD,PCOVQ,&
 & PCOVO3,KLEV,KNUMB,YD_JB_STRUCT) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNUMB
CHARACTER(LEN=10) ,INTENT(IN) :: CDJBTYPE
INTEGER(KIND=JPIM) ,INTENT(IN) :: KPRT
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVTPS(KLEV+1,KLEV+1,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVP(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVU(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVD(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVQ(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVO3(KLEV,KLEV,0:KNUMB-1)
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUJBCOR
END INTERFACE
