INTERFACE
SUBROUTINE SUJBWAVTRANS(YDDIM,YD_JB_STRUCT)
USE YOMDIM , ONLY : TDIM
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUJBWAVTRANS
END INTERFACE
