INTERFACE
SUBROUTINE SUJB(YDGEOMETRY,YDDIMACV,YGFL,YDJBS,YDCVA_DATA)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE YOMCVA , ONLY : CVA_DATA_TYPE
USE YOM_YGFL , ONLY : TYPE_GFLD
USE TYPE_ACV , ONLY : TACVDIM
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TACVDIM) ,INTENT(IN) :: YDDIMACV
TYPE(TYPE_GFLD) ,INTENT(INOUT) :: YGFL
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YDJBS
TYPE(CVA_DATA_TYPE) ,INTENT(INOUT) :: YDCVA_DATA
END SUBROUTINE SUJB
END INTERFACE
