INTERFACE
SUBROUTINE SUJQ(YDGEOMETRY,YDRIP)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE SUJQ
END INTERFACE
