INTERFACE
SUBROUTINE SUJQCOR(YDLAP,KLEV,KSMAX,PCOV,PVCORIN,PVCOR,PHCOR,CDVAR)
USE YOMLAP , ONLY : TLAP
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TLAP) , INTENT(IN) :: YDLAP
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV, KSMAX
REAL(KIND=JPRB) , INTENT(IN) :: PCOV (KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB) , INTENT(OUT) :: PVCORIN(KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB) , INTENT(OUT) :: PVCOR (KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB) , INTENT(OUT) :: PHCOR(KLEV,0:KSMAX)
CHARACTER(LEN=*) , INTENT(IN), OPTIONAL :: CDVAR
END SUBROUTINE SUJQCOR
END INTERFACE
