INTERFACE
SUBROUTINE SUJQDATA(KLEV,KSMAX,PCOVT,PCOVV,PCOVD,K3D,PCOV3)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV,KSMAX,K3D
REAL(KIND=JPRB), INTENT(OUT) :: PCOVT(KLEV+1,KLEV+1,0:KSMAX)
REAL(KIND=JPRB), INTENT(OUT) :: PCOVV(KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB), INTENT(OUT) :: PCOVD(KLEV,KLEV,0:KSMAX)
REAL(KIND=JPRB), INTENT(OUT) :: PCOV3(KLEV,KLEV,0:KSMAX,K3D)
END SUBROUTINE SUJQDATA
END INTERFACE
