INTERFACE
SUBROUTINE SUJQSTD(YDGEOMETRY,YDRIP,PCOVT,PCOVV,PCOVD,K3D,PCOV3,YDERRMN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMRIP , ONLY : TRIP
USE YOMJQ , ONLY : ERRMODMN_STRUCT, NLEVERR1, NLEVERR0
USE YOMMODERR, ONLY : ALPHAQ, NVE3D, NSERR, TSTEP_ERR, LSCALERR,&
 & ALPHAQ_T,ALPHAQ_D,ALPHAQ_V,ALPHAQ_Q,ALPHAQ_O 
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVT(YDGEOMETRY%YRDIMV%NFLEVG+1,YDGEOMETRY%YRDIMV%NFLEVG+1,0:NSERR)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVV(YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLEVG,0:NSERR)
REAL(KIND=JPRB) ,INTENT(IN) :: PCOVD(YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLEVG,0:NSERR)
INTEGER(KIND=JPIM) ,INTENT(IN) :: K3D
REAL(KIND=JPRB) ,INTENT(IN) :: PCOV3(YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLEVG,0:NSERR,K3D)
TYPE(ERRMODMN_STRUCT),INTENT(INOUT) :: YDERRMN
END SUBROUTINE SUJQSTD
END INTERFACE
