INTERFACE
SUBROUTINE SULSFORC(YDML_GCONF,KULOUT)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMLSFORC
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE SULSFORC
END INTERFACE
