INTERFACE
SUBROUTINE SUMETRIC(YDLAP,YDDIM,KSMAX,PMET,PMETDER,PMETKE)
USE YOMLAP , ONLY : TLAP
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TLAP) ,INTENT(IN) :: YDLAP
TYPE(TDIM) ,INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM),INTENT(OUT) :: KSMAX
REAL(KIND=JPRB) ,INTENT(OUT) :: PMET(0:YDDIM%NSMAX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMETDER(0:YDDIM%NSMAX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMETKE(0:YDDIM%NSMAX)
END SUBROUTINE SUMETRIC
END INTERFACE
