INTERFACE
SUBROUTINE SUMODERR(YDGEOMETRY,YDGMV,YDML_GCONF)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
END SUBROUTINE SUMODERR
END INTERFACE
