INTERFACE
SUBROUTINE SUMPIOH(KPROC,KPRIO,KFLG,KFLD,KFLDOFF,LDISIO,KMYPROC,KAVOID,KSHIFT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROC
INTEGER(KIND=JPIM),INTENT(IN) :: KPRIO
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KFLG
INTEGER(KIND=JPIM),INTENT(OUT), OPTIONAL :: KFLD(KPROC)
INTEGER(KIND=JPIM),INTENT(OUT), OPTIONAL :: KFLDOFF(KPROC)
LOGICAL, INTENT(OUT), OPTIONAL :: LDISIO
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KMYPROC
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KAVOID
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KSHIFT
END SUBROUTINE SUMPIOH
END INTERFACE
