INTERFACE
SUBROUTINE SUMTS(YDML_GCONF,YDFPOS)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE FULLPOS , ONLY : TFPOS
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
TYPE(TFPOS), INTENT(IN) :: YDFPOS
END SUBROUTINE SUMTS
END INTERFACE
