INTERFACE
SUBROUTINE SUNDISTCORR(KMONTH,KDAY,PDISTFAC)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) ::KDAY,KMONTH
REAL(KIND=JPRB), INTENT(OUT) ::PDISTFAC
END SUBROUTINE SUNDISTCORR
END INTERFACE
