INTERFACE
SUBROUTINE SUNHSI_TESTCONV(YDCST, YDGEOMETRY,YDRIP,YDDYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YOMRIP , ONLY : TRIP
USE YOMCST , ONLY : TCST
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
END SUBROUTINE SUNHSI_TESTCONV
END INTERFACE
