INTERFACE
SUBROUTINE SUOBS(YDGEOMETRY,YDODB,YDJOT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE YOMDB
USE DBASE_MOD, ONLY : DBASE
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
CLASS(DBASE) , INTENT(INOUT) :: YDODB
TYPE(JO_TABLE), INTENT(INOUT) :: YDJOT
END SUBROUTINE SUOBS
END INTERFACE
