INTERFACE
SUBROUTINE SUOBSCOR_RESOL(YDLAP,KSMAX)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMLAP
USE YOMLAP , ONLY : TLAP
TYPE(TLAP) , INTENT(IN) :: YDLAP
INTEGER(KIND=JPIM), INTENT(IN) :: KSMAX
INTEGER(KIND=JPIM), PARAMETER :: JPKS=KIND(YDLAP%RLAPDI)
INTEGER(KIND=JPIM), PARAMETER :: JPKD=KIND(1.0_JPRB)
END SUBROUTINE SUOBSCOR_RESOL
END INTERFACE
