INTERFACE
SUBROUTINE SUOFNAME(KSTEP,PTSTEP,KDIGITS,CDPATH,CDLABEL,CDOFNAME,CDINC)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KSTEP
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PTSTEP
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KDIGITS
CHARACTER(LEN=*) ,INTENT(IN), OPTIONAL :: CDPATH
CHARACTER(LEN=*) ,INTENT(IN) :: CDLABEL
CHARACTER(LEN=*) ,INTENT(OUT) :: CDOFNAME
CHARACTER(LEN=*) ,INTENT(OUT), OPTIONAL :: CDINC
END SUBROUTINE SUOFNAME
END INTERFACE
