INTERFACE
SUBROUTINE SUOROG (YDGEOMETRY, PSPOR)
USE PARKIND1 , ONLY : JPIM, JPRB
USE TYPE_GEOMETRY , ONLY : GEOMETRY
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
REAL(KIND=JPRB) , INTENT(INOUT) :: PSPOR(YDGEOMETRY%YRDIM%NSPEC2)
END SUBROUTINE SUOROG
END INTERFACE
