INTERFACE
SUBROUTINE SUPHYGR(YDGEOMETRY,YDGR)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(SL_STRUCT) ,INTENT(INOUT) :: YDGR
END SUBROUTINE SUPHYGR
END INTERFACE
