INTERFACE
SUBROUTINE SUPHEC(YDGEOMETRY,YDMODEL,KULOUT)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE SUPHEC
END INTERFACE
