INTERFACE
SUBROUTINE SUPHMSE(YDGEOMETRY,YDMODEL,KULOUT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL, ONLY : MODEL
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE (MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE SUPHMSE
END INTERFACE
