INTERFACE
SUBROUTINE SUPHLI(YDSTA,YDDIMV,YDMODEL)
USE TYPE_MODEL , ONLY : MODEL
USE YOMSTA , ONLY : TSTA
USE YOMDIMV , ONLY : TDIMV
TYPE(TSTA) ,INTENT(IN) :: YDSTA
TYPE(TDIMV) ,INTENT(IN) :: YDDIMV
TYPE(MODEL) ,INTENT(INOUT),TARGET:: YDMODEL
END SUBROUTINE SUPHLI
END INTERFACE
