INTERFACE
SUBROUTINE SUPPDATE(YDRIP,KSTEP,KDTIME,KEVENTTS,KEVENTTSMIN,KDIME,KFREVENT,K1EVENT,KPPDATE)
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMRIP , ONLY : TRIP
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KDIME
INTEGER(KIND=JPIM),INTENT(IN) :: KDTIME
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KEVENTTS(0:KDIME)
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KEVENTTSMIN(0:KDIME)
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KFREVENT
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: K1EVENT
INTEGER(KIND=JPIM),INTENT(OUT) :: KPPDATE(:)
END SUBROUTINE SUPPDATE
END INTERFACE
