INTERFACE
SUBROUTINE SUPROCFP_DEP(YDGEOMETRY,KGP,PLA,PLO,KPROCFP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KGP
REAL(KIND=JPRB) ,INTENT(IN) :: PLA(KGP)
REAL(KIND=JPRB) ,INTENT(IN) :: PLO(KGP)
INTEGER(KIND=JPIM),INTENT(OUT) :: KPROCFP(KGP)
END SUBROUTINE SUPROCFP_DEP
END INTERFACE
