INTERFACE
SUBROUTINE SUPROCGP(YDGEOMETRY,KPROCGP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(INOUT) :: KPROCGP(YDGEOMETRY%YRGEM%NGPTOTG)
END SUBROUTINE SUPROCGP
END INTERFACE
