INTERFACE
SUBROUTINE SUQNORM(YDGEOMETRY,YDML_GCONF,YDDYN,PQNORM1,PQNORM2,PQNORM3,&
 & PQNORM_ADJUST_VOR,&
 & PQNORM_ADJUST_DIV,&
 & PQNORM_ADJUST_T,&
 & PQNORM_ADJUST_Q,&
 & PQNORM_ADJUST_LNSP) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
REAL(KIND=JPRB) ,INTENT(OUT) :: PQNORM1(YDGEOMETRY%YRDIMV%NFLEVL,2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQNORM2(0:YDGEOMETRY%YRDIM%NSMAX,YDML_GCONF%YRDIMF%NFD2D)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQNORM3(YDGEOMETRY%YRDIMV%NFLSUR,0:YDGEOMETRY%YRDIM%NSMAX,YDML_GCONF%YRDIMF%NS3D)
REAL(KIND=JPRB) ,INTENT(IN) :: PQNORM_ADJUST_VOR
REAL(KIND=JPRB) ,INTENT(IN) :: PQNORM_ADJUST_DIV
REAL(KIND=JPRB) ,INTENT(IN) :: PQNORM_ADJUST_T
REAL(KIND=JPRB) ,INTENT(IN) :: PQNORM_ADJUST_Q
REAL(KIND=JPRB) ,INTENT(IN) :: PQNORM_ADJUST_LNSP
END SUBROUTINE SUQNORM
END INTERFACE
