INTERFACE
SUBROUTINE SURAYFRIC(YDVAB,YDDIMV,YDDYN)
USE YOMVERT , ONLY : TVAB, VP00
USE YOMDIMV , ONLY : TDIMV
USE YOMDYN , ONLY : TDYN
TYPE(TVAB) , INTENT(IN) :: YDVAB
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TDYN) , INTENT(INOUT) :: YDDYN
END SUBROUTINE SURAYFRIC
END INTERFACE
