INTERFACE
SUBROUTINE SURAND2(YDGEOMETRY,YDECUCONVCA,YDML_PHY_STOCH,KSTEP)
USE MODEL_PHYSICS_STOCHAST_MOD , ONLY : MODEL_PHYSICS_STOCHAST_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOE_CUCONVCA, ONLY : TECUCONVCA
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TECUCONVCA) ,INTENT(INOUT):: YDECUCONVCA
TYPE(MODEL_PHYSICS_STOCHAST_TYPE),INTENT(INOUT):: YDML_PHY_STOCH
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
END SUBROUTINE SURAND2
END INTERFACE
