INTERFACE
SUBROUTINE SURBOUNDTL(&
 & YDEPHY,YDPHY1,KPROMA,KIDIA,KFDIA,&
 & PQ5,PT5,PTS5,PAPH5,&
 & PQ,PT,PTS,PAPH,PAPHI,&
 & PWS5,PVGRAT5,PWL5,PSN5,PSLM5,&
 & PWS,PVGRAT,PWL,PSN,&
 & PES5,PWET5,PQS5,&
 & PWET,PQS,&
 & PCPTGZ,PCPTS) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMPHY1 , ONLY : TPHY1
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TPHY1) ,INTENT(INOUT) :: YDPHY1
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PQ5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVGRAT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWL5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSN5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLM5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWS(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVGRAT(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSN(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PES5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PWET5(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWET(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCPTGZ(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCPTS(KPROMA)
END SUBROUTINE SURBOUNDTL
END INTERFACE
