INTERFACE
SUBROUTINE SURFTSTP_S_LAYER(YDSURF,YDEPHY,YDPHY2,KDIM,PSURF,SURFL,LLKEYS,FLUX)
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER, ONLY : DIMENSION_TYPE, SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE,&
 & KEYS_LOCAL_TYPE, FLUX_TYPE 
USE YOMPHY2 , ONLY : TPHY2
USE YOEPHY , ONLY : TEPHY
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: SURFL
TYPE (KEYS_LOCAL_TYPE) , INTENT(INOUT) :: LLKEYS
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
END SUBROUTINE SURFTSTP_S_LAYER
END INTERFACE
