INTERFACE
SUBROUTINE SURFBC_LAYER(YDSURF, YDEPHY,KDIM, PAUX,&
 & LLKEYS,PSURF,SURFL) 
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOEPHY , ONLY : TEPHY
USE YOMPHYDER , ONLY : DIMENSION_TYPE, AUX_TYPE, KEYS_LOCAL_TYPE,&
 & SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE 
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(TEPHY) , INTENT(INOUT) :: YDEPHY
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (KEYS_LOCAL_TYPE) , INTENT(INOUT) :: LLKEYS
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: SURFL
END SUBROUTINE SURFBC_LAYER
END INTERFACE
