INTERFACE
SUBROUTINE SURF_IDEAL_FLUX(YDRIP,YDPHY0,YDPHYDS,LDAROME,KIDIA, KFDIA, KLON, PZ, PRHOA, PSFORC,&
 & PTN,PTS, PLSM, PQS, PU, PV, PTHETAS, PSFTH, PSFTQ, PSFU, PSFV) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRIP , ONLY : TRIP
USE YOMPHYDS , ONLY : TPHYDS
USE YOMPHY0 ,ONLY : TPHY0
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
TYPE(TPHYDS) ,INTENT(IN) :: YDPHYDS
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PSFORC(KLON,YDPHYDS%NSFORC)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHOA (KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PZ(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PQS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTN(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTHETAS(KLON)
LOGICAL ,INTENT(IN) :: LDAROME
REAL(KIND=JPRB) ,INTENT(OUT) :: PSFU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSFV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSFTH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSFTQ(KLON)
END SUBROUTINE SURF_IDEAL_FLUX
END INTERFACE
