INTERFACE
SUBROUTINE SURFRAD_LAYER(YDSURF, YDMCC,YDERAD,YDEPHY,YDRIP,KDIM, PAUX, STATE, LLKEYS,&
 & AUXL,PSURF,SURFL) 
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER, ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE, KEYS_LOCAL_TYPE,&
 & AUX_DIAG_LOCAL_TYPE, SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE 
USE YOMRIP , ONLY : TRIP
USE YOERAD , ONLY : TERAD
USE YOEPHY , ONLY : TEPHY
USE YOMMCC , ONLY : TMCC
TYPE(TSURF) , INTENT(INOUT) :: YDSURF
TYPE(TEPHY) , INTENT(INOUT) :: YDEPHY
TYPE(TERAD) , INTENT(INOUT) :: YDERAD
TYPE(TMCC) , INTENT(INOUT) :: YDMCC
TYPE(TRIP) , INTENT(INOUT) :: YDRIP
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (KEYS_LOCAL_TYPE) , INTENT (IN) :: LLKEYS
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: SURFL
END SUBROUTINE SURFRAD_LAYER
END INTERFACE
