INTERFACE
SUBROUTINE SURIP(YDDIM,YDRIP)
USE YOMDIM , ONLY : TDIM
USE YOMRIP , ONLY : TRIP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TRIP) , INTENT(INOUT), TARGET :: YDRIP
END SUBROUTINE SURIP
END INTERFACE
