INTERFACE
SUBROUTINE SUSCAL(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,STRUCT,YDVARBC,YD_JB_STRUCT)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS, FIELDS_CREATE, FIELDS_DELETE
USE MTRAJ_MOD , ONLY : MTRAJ
USE YOMCVA , ONLY : CVA_DATA, SCALP_STRUCT_TYPE
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE VARBC_CLASS,ONLY: CLASS_VARBC
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
TYPE(SCALP_STRUCT_TYPE), POINTER :: STRUCT
END SUBROUTINE SUSCAL
END INTERFACE
