INTERFACE
SUBROUTINE SUSCALMERR(YDMP,YDSCALP)
USE YOMMP , ONLY : TMP
USE CONTROL_VECTORS_MOD
TYPE(TMP) , INTENT(IN) :: YDMP
TYPE(CONTROL_VECTOR), INTENT(INOUT) :: YDSCALP
END SUBROUTINE SUSCALMERR
END INTERFACE
