INTERFACE
SUBROUTINE SUSCAL_JB(YDGEOMETRY,YDJBCTLVEC,YD_JB_STRUCT,YDCVA_DATA)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCVA , ONLY : CVA_DATA_TYPE
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE JB_CONTROL_VECTORS_BASE_MOD, ONLY: JB_CONTROL_VECTOR
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
TYPE(CVA_DATA_TYPE) ,INTENT(IN) :: YDCVA_DATA
TYPE(JB_CONTROL_VECTOR), POINTER :: YDJBCTLVEC
END SUBROUTINE SUSCAL_JB
END INTERFACE
