INTERFACE
SUBROUTINE SUSEPRENORMFCE(YDGEOMETRY,KNUMB,KSTGLO,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KNUMB
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUSEPRENORMFCE
END INTERFACE
