INTERFACE
SUBROUTINE SUSEKF(YDGEOMETRY,YDSURF,YDDPHY,YDRIP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMRIP , ONLY : TRIP
USE YOMDPHY , ONLY : TDPHY
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TDPHY) ,INTENT(INOUT) :: YDDPHY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
END SUBROUTINE SUSEKF
END INTERFACE
