INTERFACE
SUBROUTINE SUSHFCE(YDGEOMETRY,YDSURF,KNUMB,KSTGLO,PTT0,PQT0,PSPT0,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNUMB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PTT0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PQT0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPT0(YDGEOMETRY%YRDIM%NPROMA)
TYPE(TYPE_JB_STRUCT),INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUSHFCE
END INTERFACE
