INTERFACE
SUBROUTINE SUSIMPR(YDGEOMETRY,YDMDDH)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMMDDH , ONLY : TMDDH
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TMDDH) ,INTENT(INOUT) :: YDMDDH
END SUBROUTINE SUSIMPR
END INTERFACE
