INTERFACE
SUBROUTINE SUSI(YDCST, YDGEOMETRY,YDRIP,YDDYN,YDEDYN,KULOUT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YEMDYN , ONLY : TEDYN
USE YOMCST , ONLY : TCST
USE YOMRIP , ONLY : TRIP
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TEDYN) ,INTENT(INOUT) :: YDEDYN
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE SUSI
END INTERFACE
