INTERFACE
SUBROUTINE SUSLB(YDDIMV,YDMODEL)
USE TYPE_MODEL , ONLY : MODEL
USE YOMDIMV , ONLY : TDIMV
TYPE(TDIMV), INTENT(IN) :: YDDIMV
 TYPE(MODEL),INTENT(INOUT):: YDMODEL
END SUBROUTINE SUSLB
END INTERFACE
