INTERFACE
SUBROUTINE SUSPQLIM_PART2(YDGEOMETRY,YDPHY,KLEVIG,KLEVIG1,KLEVIL1,LDEVIL1,PSQOLD,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMPHY, ONLY : TPHY
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) ,INTENT (IN) :: YDGEOMETRY
TYPE(TPHY) ,INTENT(INOUT) :: YDPHY
INTEGER (KIND=JPIM) ,INTENT (IN) :: KLEVIG
INTEGER (KIND=JPIM) ,INTENT (IN) :: KLEVIG1
INTEGER (KIND=JPIM) ,INTENT (IN) :: KLEVIL1
LOGICAL ,INTENT (IN) :: LDEVIL1
TYPE(SPECTRAL_FIELD),INTENT (IN) :: YDSP
REAL (KIND=JPRB) ,POINTER :: PSQOLD (:,:)
END SUBROUTINE SUSPQLIM_PART2
END INTERFACE
