INTERFACE
SUBROUTINE SUSPE0(YDGEOMETRY,YDDIMF,YDSPEC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDIMF , ONLY : TDIMF
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TDIMF) ,INTENT(INOUT) :: YDDIMF
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSPEC
END SUBROUTINE SUSPE0
END INTERFACE
