INTERFACE
SUBROUTINE SUSPECA_FIXUP(YDGEOMETRY,YGFL,KFILE,PSPGFL,PSPSP)
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE (TYPE_GFLD), INTENT (IN) :: YGFL
INTEGER (KIND=JPIM), INTENT (IN) :: KFILE
REAL (KIND=JPRB), INTENT (OUT) :: PSPGFL(:,:,:)
REAL (KIND=JPRB), INTENT (INOUT) :: PSPSP(:)
END SUBROUTINE SUSPECA_FIXUP
END INTERFACE
