INTERFACE
SUBROUTINE SUSPEC(YDGEOMETRY,YDGFL,YDML_GCONF,YDDYN,YDML_LBC,&
 & YDSP,CDPATH,KFILE,LDRDGRIDSP,LDINOR,LDSPOR,YDMCUF) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN , ONLY : TDYN
USE YEMLBC_MODEL , ONLY : TELBC_MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD , ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE YOMMCUF , ONLY : TMCUF
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL) ,INTENT(INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(TELBC_MODEL) ,INTENT(IN) :: YDML_LBC
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSP
CHARACTER(LEN=*) ,OPTIONAL,INTENT(IN) :: CDPATH
INTEGER(KIND=JPIM) ,OPTIONAL,INTENT(IN) :: KFILE
LOGICAL ,OPTIONAL,INTENT(IN) :: LDRDGRIDSP
LOGICAL ,OPTIONAL,INTENT(IN) :: LDINOR
LOGICAL ,OPTIONAL,INTENT(INOUT) :: LDSPOR
TYPE(TMCUF) ,OPTIONAL,INTENT(INOUT) :: YDMCUF
END SUBROUTINE SUSPEC
END INTERFACE
