INTERFACE
SUBROUTINE SUSPSDT(YDGEOMETRY,YDRIP,YDCONF,YDSPPT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMSPSDT , ONLY : TSPPT_CONFIG, TSPPT_DATA, NMAXSCALES_SDT, NMAXINDPAT_SDT, NWRMAX_SDT
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(TRIP) , INTENT(INOUT) :: YDRIP
TYPE(TSPPT_CONFIG) , INTENT(OUT) :: YDCONF
TYPE(TSPPT_DATA) , INTENT(OUT) :: YDSPPT
END SUBROUTINE SUSPSDT
END INTERFACE
