INTERFACE
SUBROUTINE SUSPECG2(YDGEOMETRY,YDGFL,YDML_GCONF,PSPA3,PSPA2)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
REAL(KIND=JPRB),TARGET, INTENT(OUT) :: PSPA3(:,:,:)
REAL(KIND=JPRB), INTENT(OUT) :: PSPA2(:,:)
END SUBROUTINE SUSPECG2
END INTERFACE
