INTERFACE
SUBROUTINE SUSPECB(YDGEOMETRY,YDML_GCONF,YDDYN,KFILE,YDSP)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMDYN , ONLY : TDYN
USE SPECTRAL_FIELDS_MOD , ONLY: SPECTRAL_FIELD, ASSIGNMENT(=)
USE MPL_MODULE
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFILE
TYPE(SPECTRAL_FIELD) ,INTENT(INOUT) :: YDSP
END SUBROUTINE SUSPECB
END INTERFACE
