INTERFACE
SUBROUTINE SUTIMINCLI(KDAY,KMONTH,KYEAR,KMMCLI,KULOUT,LDFILE,PALFA)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDAY
INTEGER(KIND=JPIM),INTENT(IN) :: KMONTH
INTEGER(KIND=JPIM),INTENT(IN) :: KYEAR
INTEGER(KIND=JPIM),INTENT(IN) :: KMMCLI(2)
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
LOGICAL ,INTENT(INOUT) :: LDFILE(2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PALFA
END SUBROUTINE SUTIMINCLI
END INTERFACE
