INTERFACE
SUBROUTINE SUVAZX(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YD_CVA_STRUCT,YDVARBC,YD_JB_STRUCT,YDTCV,YDTCV_BGC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_MOD,ONLY : TOVSCV
USE TOVSCV_BGC_MOD,ONLY : TOVSCV_BGC
USE YOMCVA , ONLY : CVA_DATA, CVA_STRUCT_TYPE
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) , INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) , INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) , INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CVA_STRUCT_TYPE), INTENT(INOUT), POINTER :: YD_CVA_STRUCT
TYPE(CLASS_VARBC) , INTENT(INOUT) :: YDVARBC
TYPE(TYPE_JB_STRUCT) , INTENT(INOUT) :: YD_JB_STRUCT
TYPE(TOVSCV),OPTIONAL , INTENT(INOUT) :: YDTCV
TYPE(TOVSCV_BGC),OPTIONAL, INTENT(IN) :: YDTCV_BGC
END SUBROUTINE SUVAZX
END INTERFACE
