INTERFACE
SUBROUTINE SUVFE_OPER_SETUP(&
 & KTBC, KBBC, KFLEV_IN,&
 & KORDER, KBASIS, KINTERNALS, KOFF, KKNOTS ) 
USE PARKIND1, ONLY : JPRB, JPIM
INTEGER(KIND=JPIM), INTENT(IN) :: KTBC(2)
INTEGER(KIND=JPIM), INTENT(IN) :: KBBC(2)
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV_IN
INTEGER(KIND=JPIM), INTENT(OUT) :: KORDER
INTEGER(KIND=JPIM), INTENT(OUT) :: KBASIS
INTEGER(KIND=JPIM), INTENT(OUT) :: KINTERNALS
INTEGER(KIND=JPIM), INTENT(OUT) :: KOFF
INTEGER(KIND=JPIM), INTENT(OUT) :: KKNOTS
END SUBROUTINE SUVFE_OPER_SETUP
END INTERFACE
