INTERFACE
SUBROUTINE SUVFE_IMPLICITBC(&
 & KTBC, KBBC, KORDER, KBASIS, PB ) 
USE PARKIND1, ONLY : JPRB, JPIM
INTEGER(KIND=JPIM), INTENT(IN) :: KTBC(2)
INTEGER(KIND=JPIM), INTENT(IN) :: KBBC(2)
INTEGER(KIND=JPIM), INTENT(IN) :: KORDER
INTEGER(KIND=JPIM), INTENT(IN) :: KBASIS
REAL(KIND=JPRB), INTENT(INOUT) :: PB(KBASIS, KORDER, KORDER)
END SUBROUTINE SUVFE_IMPLICITBC
END INTERFACE
