INTERFACE
SUBROUTINE SUVFE_KNOT(YDVFE, KTBC, KBBC, KBASIS, KORDER,&
 & KFLEV, PETA, PKNOT) 
USE PARKIND1 , ONLY : JPRB, JPIM
USE YOMVERT , ONLY : TVFE
TYPE(TVFE) , INTENT(INOUT) :: YDVFE
INTEGER(KIND=JPIM), INTENT(IN) :: KTBC(2), KBBC(2)
INTEGER(KIND=JPIM), INTENT(IN) :: KBASIS
INTEGER(KIND=JPIM), INTENT(IN) :: KORDER
INTEGER(KIND=JPIM), INTENT(IN) :: KFLEV
REAL (KIND=JPRB), INTENT(IN) :: PETA(KFLEV)
REAL (KIND=JPRB), INTENT(OUT) :: PKNOT(KBASIS+KORDER)
END SUBROUTINE SUVFE_KNOT
END INTERFACE
