INTERFACE
SUBROUTINE SUVFPOSL(YDQTYPE,YDRQSP,YDRQGP,KGRIB,LDSURF,CDNAME,KFPDOM,KPXLEV,PXLEV,KFPCONF,CDCONF)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
USE YOMFP4L , ONLY : TRQFP
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE (TRQFP), INTENT(INOUT) :: YDRQSP
TYPE (TRQFP), INTENT(INOUT) :: YDRQGP
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIB(:)
LOGICAL, INTENT(IN) :: LDSURF(:)
CHARACTER(LEN=*), INTENT(IN) :: CDNAME(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KPXLEV
REAL(KIND=JPRB), INTENT(IN) :: PXLEV(KPXLEV)
INTEGER(KIND=JPIM), INTENT(IN),OPTIONAL :: KFPCONF
CHARACTER(LEN=1),INTENT(IN),OPTIONAL :: CDCONF
END SUBROUTINE SUVFPOSL
END INTERFACE
