INTERFACE
SUBROUTINE SUVFE_BASIS(KORDER,PVAL,KBASIS,PKNOT,PSPLINE)
USE PARKIND1,ONLY : JPRB, JPIM
INTEGER(KIND=JPIM),INTENT(IN) :: KORDER
INTEGER(KIND=JPIM),INTENT(IN) :: KBASIS
REAL(KIND=JPRB),INTENT(IN) :: PVAL
REAL(KIND=JPRB),INTENT(IN) :: PKNOT(KBASIS+KORDER)
REAL(KIND=JPRB),INTENT(OUT) :: PSPLINE(KBASIS)
END SUBROUTINE SUVFE_BASIS
END INTERFACE
