INTERFACE
SUBROUTINE SUVFE_CPSPLINES(KORDER,KBASIS,PTM,PKNOT,PSPLINE,PETAMAX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KORDER
INTEGER(KIND=JPIM),INTENT(IN) :: KBASIS
REAL(KIND=JPRB),INTENT(IN) :: PTM (KORDER,KORDER)
REAL(KIND=JPRB),INTENT(IN) :: PKNOT (KBASIS + KORDER)
REAL(KIND=JPRB),INTENT(OUT) :: PSPLINE(KBASIS,KORDER,KORDER)
REAL(KIND=JPRB),INTENT(OUT) :: PETAMAX(KBASIS)
END SUBROUTINE SUVFE_CPSPLINES
END INTERFACE
