INTERFACE
SUBROUTINE SUVSLETA(YDGEOMETRY,LDVERBOSE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY),INTENT(INOUT) :: YDGEOMETRY
LOGICAL ,INTENT(IN) :: LDVERBOSE
END SUBROUTINE SUVSLETA
END INTERFACE
