INTERFACE
SUBROUTINE SUVV1(YDGEOMETRY,KSUPERSEDE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT), TARGET :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSUPERSEDE
INTEGER(KIND=JPIM), PARAMETER :: JPKS=KIND(ZVALH)
END SUBROUTINE SUVV1
END INTERFACE
