INTERFACE
SUBROUTINE SUWCOU(YDRIP,YDEWCOU)
USE YOEWCOU , ONLY : TEWCOU
USE YOMRIP , ONLY : TRIP
TYPE(TEWCOU),INTENT(INOUT):: YDEWCOU
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE SUWCOU
END INTERFACE
