INTERFACE
SUBROUTINE SUWINDFARMINIF(YDGEOMETRY,YDFIELDS,YDMODEL,YDSURF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE FIELDS_MOD , ONLY : FIELDS
USE TYPE_MODEL , ONLY : MODEL
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL),INTENT(INOUT) :: YDMODEL
END SUBROUTINE SUWINDFARMINIF
END INTERFACE
