INTERFACE
SUBROUTINE SVPAR1DACV(YDGEOMETRY,YDDIMACV,PCVPARPHY,PGPARPHY,KNPARPHY)
USE parkind1, ONLY : JPIM, JPRB
USE TYPE_ACV , ONLY : TACVDIM, ACV_CONTAINER
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TACVDIM) ,INTENT(IN) :: YDDIMACV
INTEGER(KIND=JPIM),INTENT(IN) :: knparphy
REAL(KIND=JPRB) ,INTENT(IN) :: pcvparphy(knparphy)
REAL(KIND=JPRB) ,INTENT(IN) :: PGPARPHY(knparphy)
END SUBROUTINE SVPAR1DACV
END INTERFACE
