INTERFACE
SUBROUTINE SWAP53(YDGEOMETRY,YDDIMF,YDSP3)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDIMF , ONLY : TDIMF
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TDIMF) ,INTENT(INOUT) :: YDDIMF
TYPE(SPECTRAL_FIELD) , INTENT(INOUT) :: YDSP3
END SUBROUTINE SWAP53
END INTERFACE
