INTERFACE
SUBROUTINE SWCLRAD&
 & ( YDERAD,YDERDI,KIDIA , KFDIA , KLON , KLEV , KAER , KNU,&
 & PAER5 , PALBP5 , PDSIG5 , PRAYL5 , PSEC5,&
 & PCGAZ5 , PPIZAZ5, PRAY15 , PRAY25 , PREFZ5 , PRJ05,&
 & PRK05 , PRMU05 , PTAUAZ5, PTRA15 , PTRA25,&
 & PAER , PALBP , PDSIG , PRAYL , PSEC,&
 & PCGAZ , PPIZAZ , PRAY1 , PRAY2 , PREFZ , PRJ0,&
 & PRK0 , PRMU0 , PTAUAZ , PTRA1 , PTRA2&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOERAD , ONLY : TERAD
USE YOERDI , ONLY : TERDI
TYPE(TERAD) ,INTENT(IN) :: YDERAD
TYPE(TERDI) ,INTENT(IN) :: YDERDI
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KAER
INTEGER(KIND=JPIM),INTENT(IN) :: KNU
REAL(KIND=JPRB) ,INTENT(IN) :: PAER5(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBP5(KLON,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PDSIG5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRAYL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEC5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCGAZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPIZAZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY25(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PREFZ5(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRJ05(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRK05(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRMU05(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAUAZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA25(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAER(KLON,6,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PALBP(KLON,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSIG(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRAYL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSEC(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCGAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPIZAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRAY1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRAY2(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PREFZ(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRJ0(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRK0(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRMU0(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAUAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRA1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTRA2(KLON,KLEV+1)
END SUBROUTINE SWCLRAD
END INTERFACE
