INTERFACE
SUBROUTINE SWITCH_VWIND(ROBODY,YDGP5,YDSET,PHOFX,PBIAS)
USE PARKIND1 , ONLY : JPIM, JPRB
USE IFS_DBASE_VIEW_MOD, ONLY: IFS_DBASE_VIEW
USE OBSOP_SETS, ONLY : TYPE_SET_INFO
USE GOM_PLUS , ONLY : TYPE_GOM_PLUS,IH
TYPE(IFS_DBASE_VIEW) , INTENT(INOUT) :: ROBODY
TYPE(TYPE_GOM_PLUS) , INTENT(IN) :: YDGP5
TYPE(TYPE_SET_INFO) , INTENT(IN) :: YDSET
REAL(KIND=JPRB) , INTENT(IN) :: PHOFX(YDGP5%NDLEN,YDSET%MXBDY)
REAL(KIND=JPRB) , INTENT(INOUT) :: PBIAS(YDGP5%NDLEN,YDSET%MXBDY)
END SUBROUTINE SWITCH_VWIND
END INTERFACE
