INTERFACE
SUBROUTINE SWRTL&
 & ( YDEOVLP,YDERAD,YDECLD,KIDIA , KFDIA , KLON , KLEV , KNU,&
 & PALBD5 , PCG5 , PCLD5 , POMEGA5, PSEC5 , PTAU5,&
 & PCGAZ5 , PPIZAZ5, PRAY15, PRAY25 , PREFZ5, PRJ5 , PRK5,&
 & PRMUE5 , PTAUAZ5, PTRA15, PTRA25,&
 & PALBD , PCG , PCLD , POMEGA , PSEC , PTAU,&
 & PCGAZ , PPIZAZ , PRAY1 , PRAY2 , PREFZ , PRJ , PRK,&
 & PRMUE , PTAUAZ , PTRA1 , PTRA2&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOERAD , ONLY : TERAD
USE YOECLD , ONLY : TECLD
USE YOEOVLP , ONLY : TEOVLP
TYPE(TECLD) ,INTENT(IN) :: YDECLD
TYPE(TEOVLP) ,INTENT(IN) :: YDEOVLP
TYPE(TERAD) ,INTENT(IN) :: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KNU
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD5(KLON,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PCG5(KLON,YDERAD%NSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POMEGA5(KLON,YDERAD%NSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEC5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAU5(KLON,YDERAD%NSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCGAZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPIZAZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY25(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PREFZ5(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRJ5(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRK5(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRMUE5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUAZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA25(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(KLON,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PCG(KLON,YDERAD%NSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POMEGA(KLON,YDERAD%NSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAU(KLON,YDERAD%NSW,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCGAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPIZAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY2(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PREFZ(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRJ(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRK(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRMUE(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA2(KLON,KLEV+1)
END SUBROUTINE SWRTL
END INTERFACE
