INTERFACE
SUBROUTINE SWTTAD ( KIDIA, KFDIA, KLON, KNU, KA , PU5, PTR5, PU, PTR)
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KNU
INTEGER(KIND=JPIM),INTENT(IN) :: KA
REAL(KIND=JPRB) ,INTENT(IN) :: PU5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTR5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTR(KLON)
END SUBROUTINE SWTTAD
END INTERFACE
