INTERFACE
SUBROUTINE SWUAD&
 & ( YDEOVLP,YDERAD,YDECLD,KIDIA , KFDIA , KLON , KLEV,&
 & PSCT5 , PCARDI5, PCLDSW5, PPMB5 , PPSOL5,&
 & PRMU05, PTAVE5 , PWV5,&
 & PAKI5 , PCLD5 , PCLEAR5, PDSIG5, PFACT5, PRMU5,&
 & PSEC5 , PUD5,&
 & PSCT , PCARDI , PCLDSW , PPMB , PPSOL,&
 & PRMU0 , PTAVE , PWV,&
 & PAKI , PCLD , PCLEAR , PDSIG , PFACT , PRMU,&
 & PSEC , PUD&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOECLD , ONLY : TECLD
USE YOERAD , ONLY : TERAD
USE YOEOVLP , ONLY : TEOVLP
TYPE(TECLD) ,INTENT(IN) :: YDECLD
TYPE(TEOVLP) ,INTENT(IN) :: YDEOVLP
TYPE(TERAD) ,INTENT(IN) :: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PSCT5
REAL(KIND=JPRB) ,INTENT(IN) :: PCARDI5
REAL(KIND=JPRB) ,INTENT(IN) :: PCLDSW5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPMB5(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PPSOL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRMU05(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAVE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PWV5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAKI5(KLON,2,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLD5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLEAR5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDSIG5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFACT5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRMU5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSEC5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUD5(KLON,5,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSCT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCARDI
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCLDSW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPMB(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PPSOL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRMU0(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTAVE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAKI(KLON,2,YDERAD%NSW)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCLD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCLEAR(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDSIG(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFACT(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PRMU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSEC(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUD(KLON,5,KLEV+1)
END SUBROUTINE SWUAD
END INTERFACE
