INTERFACE
SUBROUTINE TASKOBAD(YDEPHY,YDML_PHY_MF,YDOBSET,YDJOT,YDVARBC,YDTCV5,YDGOM5,YDGOM,YDTCV,YDODB)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOEPHY , ONLY : TEPHY
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE SUPERGOM_CLASS, ONLY : CLASS_SUPERGOM
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_MOD ,ONLY: TOVSCV
USE OBSOP_SETS, ONLY : CLASS_OBSOP_SETS
USE DBASE_MOD, ONLY : DBASE
TYPE(TEPHY), INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_MF_TYPE), INTENT(INOUT) :: YDML_PHY_MF
TYPE(CLASS_OBSOP_SETS), INTENT(IN) :: YDOBSET
TYPE(JO_TABLE), INTENT(IN) :: YDJOT
TYPE(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) , INTENT(IN) :: YDTCV5
TYPE(CLASS_SUPERGOM), INTENT(IN) :: YDGOM5
TYPE(CLASS_SUPERGOM), INTENT(INOUT) :: YDGOM
TYPE(TOVSCV) , INTENT(INOUT) :: YDTCV
CLASS(DBASE), INTENT(INOUT) :: YDODB
END SUBROUTINE TASKOBAD
END INTERFACE
