INTERFACE
SUBROUTINE TASKOBTL_THREAD(YDEPHY,YDML_PHY_MF,YDODB,YDOBSET,YDJOT,YDVARBC,YDTCV5,YDGOM5,YDGOM,YDTCV,KSET,YDHOP_RESULTS)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOEPHY , ONLY : TEPHY
USE PARKIND1 , ONLY : JPIM, JPRB
USE SUPERGOM_CLASS , ONLY : CLASS_SUPERGOM
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE TOVSCV_MOD , ONLY : TOVSCV
USE OBSOP_SETS , ONLY : CLASS_OBSOP_SETS, TYPE_SET_INFO, LEN_SET_NAME
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE YOMHOP_RESULTS , ONLY : THOP_RESULTS
USE DBASE_MOD , ONLY : DBASE
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT) :: YDML_PHY_MF
CLASS(DBASE) ,INTENT(INOUT) :: YDODB
TYPE(CLASS_OBSOP_SETS) ,INTENT(IN) :: YDOBSET
TYPE(JO_TABLE) ,INTENT(INOUT) :: YDJOT
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(IN) :: YDTCV5
TYPE(CLASS_SUPERGOM) ,INTENT(IN) :: YDGOM5
TYPE(CLASS_SUPERGOM) ,INTENT(IN) :: YDGOM
TYPE(TOVSCV) ,INTENT(IN) :: YDTCV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSET
TYPE(THOP_RESULTS) ,INTENT(INOUT), OPTIONAL :: YDHOP_RESULTS
END SUBROUTINE TASKOBTL_THREAD
END INTERFACE
