INTERFACE
SUBROUTINE TEST_SDP_VARIANCES(YDGEOMETRY,K3D,K2D,KGRB3,KGRB2,PGP3,PGP2)
USE PARKIND1 , ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: K3D
INTEGER(KIND=JPIM),INTENT(IN) :: K2D
INTEGER(KIND=JPIM),INTENT(IN) :: KGRB3(K3D)
INTEGER(KIND=JPIM),INTENT(IN) :: KGRB2(K2D)
REAL(KIND=JPRB) , INTENT(IN) :: PGP3(:,:,:,:)
REAL(KIND=JPRB) , INTENT(IN) :: PGP2(:,:,:)
END SUBROUTINE TEST_SDP_VARIANCES
END INTERFACE
