INTERFACE
SUBROUTINE TIMDIF(KDATE,KTIME,PTIM)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDATE
INTEGER(KIND=JPIM),INTENT(IN) :: KTIME
REAL(KIND=JPRB) ,INTENT(OUT) :: PTIM
END SUBROUTINE TIMDIF
END INTERFACE
