INTERFACE
SUBROUTINE TJCUBI (PX1,PY1,PX2,PY2,PX3,PY3,PX4,PY4,PXM,PYM,PXN,PYN,PENT,PEPS)
USE PARKIND1 ,ONLY : JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PX1
REAL(KIND=JPRB) ,INTENT(IN) :: PY1
REAL(KIND=JPRB) ,INTENT(IN) :: PX2
REAL(KIND=JPRB) ,INTENT(IN) :: PY2
REAL(KIND=JPRB) ,INTENT(IN) :: PX3
REAL(KIND=JPRB) ,INTENT(IN) :: PY3
REAL(KIND=JPRB) ,INTENT(IN) :: PX4
REAL(KIND=JPRB) ,INTENT(IN) :: PY4
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PYM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PXN
REAL(KIND=JPRB) ,INTENT(INOUT) :: PYN
REAL(KIND=JPRB) ,INTENT(IN) :: PENT
REAL(KIND=JPRB) ,INTENT(IN) :: PEPS
END SUBROUTINE TJCUBI
END INTERFACE
