INTERFACE
SUBROUTINE TJQUD (PX1,PY1,PX2,PY2,PX3,PY3,PXM,PYM,PENT,PEPS)
USE PARKIND1 ,ONLY : JPRB
REAL(KIND=JPRB) ,INTENT(IN) :: PX1
REAL(KIND=JPRB) ,INTENT(IN) :: PY1
REAL(KIND=JPRB) ,INTENT(IN) :: PX2
REAL(KIND=JPRB) ,INTENT(IN) :: PY2
REAL(KIND=JPRB) ,INTENT(IN) :: PX3
REAL(KIND=JPRB) ,INTENT(IN) :: PY3
REAL(KIND=JPRB) ,INTENT(OUT) :: PXM
REAL(KIND=JPRB) ,INTENT(OUT) :: PYM
REAL(KIND=JPRB) ,INTENT(IN) :: PENT
REAL(KIND=JPRB) ,INTENT(IN) :: PEPS
END SUBROUTINE TJQUD
END INTERFACE
