INTERFACE
SUBROUTINE TM5_BOUNDARY_HNO3(YGFL,KIDIA,KFDIA,KLON,KMONTH,PGELAT,PHNO3,PO3,PTENHNO3)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA , KFDIA , KLON,KMONTH
REAL(KIND=JPRB),INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PO3(KLON)
REAL(KIND=JPRB),INTENT(IN) :: PHNO3(KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PTENHNO3(KLON)
END SUBROUTINE TM5_BOUNDARY_HNO3
END INTERFACE
