INTERFACE
SUBROUTINE TM5_STRATOLOSS(YGFL,PY0,PY,PDT)
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
REAL(KIND=JPRB),INTENT(IN) :: PDT
REAL(KIND=JPRB),INTENT(IN) :: PY0(YGFL%NCHEM)
REAL(KIND=JPRB),INTENT(INOUT) :: PY(YGFL%NCHEM)
END SUBROUTINE TM5_STRATOLOSS
END INTERFACE
