INTERFACE
SUBROUTINE TM5_CALRATES(YDCHEM,YDCOMPO,YDEAERSNK,YDEAERSRC,YDEAERATM,YGFL,KIDIA, KFDIA, KLON, KL, KLEV, KTRACER,&
 & KAEROC, KMODES, PTP, PRSF1,&
 & PQP, PAP, PIP, PLP, PRJ, PCLOUD_REFF, PO3, PHO2,&
 & PNH4,PNO3_A, PSO4, PWETDIAM, PWETVOL,PND,&
 & PAEROP,PSAD_AER,PSAD_CLD,PSAD_ICE,&
 & PRR) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE TM5_CHEM_MODULE , ONLY :&
 & KNOO3, KHO2NO, KMO2NO, KNO2OH, KOHHNO3, KNO2O3, KNONO3, KNO2NO3,&
 & KN2O5, KHNO4OH, KNO2HO2, KHNO4M, KODM, KH2OOD, KO3HO2, KCOOH,&
 & KO3OH, KHPOH, KFRMOH, KCH4OH, KOHMPER, KOHROOH, KMO2HO2, KMO2MO2,&
 & KHO2OH, KHO2HO2, KN2O5AQ, KN2O5L, KH2OH, KC41,&
 & KC43, KC44, KC46, KC47, KC48, KC49, KC50A, KC50B, KC52,&
 & KC53, KC54, KC57, KC58, KC59, KC61, KC62, KC73,&
 & KC76, KC77, KC78, KC79, KC80, KC81, KC82, KC83,&
 & KC84, KC85, KDMSOHA, KDMSOHB, KDMSNO3, KSO2OH, KNH3SO4, KNH3OH,&
 & KNH2NO, KNH2NO2,KNH2HO2, KNH2O2, KNH2O3, KRN222, KO3PO3,KO3PO2, KNO2OHA,&
 & KNO2OHB, KOHHNO3A,KOHHNO3B, KOHHNO3C, KNO2NO3A, KNO2NO3B, KNO2HO2A, KNO2HO2B,&
 & KHO2HO2A, KHO2HO2B, KHO2HO2C, KC47A, KC47B, KC48A, KC48B, KC61A,&
 & KC61B, KSO2OHA, KSO2OHB, KDMSOHC, KCOOHA, KCOOHB, KCOOHC, KCOOHD,&
 & KOHMCHO, KOHMCH2CHO, KNO3MCHO, KNO3MCH2CHO, KOHMVK,&
 & KOHOLE, KOHMACR, KO3MVK, KO3OLE, KO3MACR, KNO3OLE,&
 & KOHC3H8, KO3C3H6, KNO3C3H6, KOHETHOH,&
 & KOHTERP, KO3TERP, KNO3TERP, KOHHCOOH, KOHCH3OH,&
 & KNO3HO2, KOHC3H6A, KOHC3H6B, KOHC3H6, KNO3MO2, KOHC2H6,&
 & KNO3C2O3, KNO3XO2, KOHMCOOH, KOHISPD, KO3ISPD,KNO3ISPD,&
 & KOHACET,KOHACETA,KOHACETB,KACO2HO2,KACO2MO2,KACO2NO,KACO2XO2,&
 & KXO2XO2N,KXO2N,&
 & KNOIC3H7O2,KHO2IC3H7O2,KNOHYPROPO2,KHO2HYPROPO2,&
 & KISOPO2NO, KISOPO2NO3, KISOPO2HO2, KISOPO2CH3O2, KISOPO2C2O3, KISOPOOHOH,&
 & KHO2L, KHO2_AER , KN2O5_AER, KNO3_AER,&
 & KSO2O3G, KSO3H2O,KOCSOH,&
 & RATES_LUT, NTLOW, NTEMP,&
 & XMH2O, XMAIR, NREAC 
USE TM5_PHOTOLYSIS_NEW, ONLY : NPHOTO, JO2, JO3D, JISOPOOH
USE YOEAERATM, ONLY : TEAERATM
USE YOEAERSRC, ONLY : TEAERSRC
USE YOEAERSNK ,ONLY : TEAERSNK
USE YOMCHEM , ONLY : TCHEM
USE YOMCOMPO , ONLY : TCOMPO
TYPE(TCHEM), INTENT(INOUT) :: YDCHEM
TYPE(TCOMPO), INTENT(IN) :: YDCOMPO
TYPE(TEAERSNK), INTENT(INOUT) :: YDEAERSNK
TYPE(TEAERSRC), INTENT(INOUT) :: YDEAERSRC
TYPE(TEAERATM), INTENT(INOUT) :: YDEAERATM
TYPE(TYPE_GFLD), INTENT(INOUT) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KL, KLEV, KAEROC, KMODES
INTEGER(KIND=JPIM),INTENT(IN) :: KTRACER(2)
REAL(KIND=JPRB), INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PAP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PIP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PLP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCLOUD_REFF(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PO3(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PHO2(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PNH4(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PNO3_A(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PSO4(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PWETDIAM(KLON,KLEV,KMODES)
REAL(KIND=JPRB), INTENT(IN) :: PWETVOL(KLON,KLEV,KMODES)
REAL(KIND=JPRB), INTENT(IN) :: PND(KLON,KLEV,KMODES)
REAL(KIND=JPRB), INTENT(INOUT) :: PRJ(KLON,NPHOTO)
REAL(KIND=JPRB), INTENT(IN) :: PAEROP(KLON,KLEV,KAEROC)
REAL(KIND=JPRB), INTENT(INOUT) :: PSAD_AER(KLON,KLEV), PSAD_CLD(KLON,KLEV), PSAD_ICE(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PRR(KLON,NREAC)
END SUBROUTINE TM5_CALRATES
END INTERFACE
