INTERFACE
SUBROUTINE TM5_CHEM_INI(YGFL,YDCHEM)
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMCHEM , ONLY : TCHEM
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
TYPE(TCHEM), INTENT(IN) :: YDCHEM
END SUBROUTINE TM5_CHEM_INI
END INTERFACE
