INTERFACE
SUBROUTINE TM5_AEROSOL_INFO ( KIDIA,KFDIA,KLON,KLEV,&
 & PGEOH,PTP, PLSM,PRS1 ,PRSF1, PCC, PQP, PGELAT,&
 & PTAUS_AER,PTAUA_AER, PMAER ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE TM5_PHOTOLYSIS_NEW , ONLY : PN_REF, NGRID,NBANDS_TROP,&
 & LMID, LMID_GRIDA, SCA, ABS_EFF, GFAC 
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
REAL(KIND=JPRB), INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PRS1(KLON,0:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PCC(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQP(KLON,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB), INTENT(OUT) :: PTAUS_AER(KLON,KLEV,NBANDS_TROP,NGRID)
REAL(KIND=JPRB), INTENT(OUT) :: PTAUA_AER(KLON,KLEV,NBANDS_TROP,NGRID)
REAL(KIND=JPRB), INTENT(OUT) :: PMAER(KLON,KLEV,NBANDS_TROP,NGRID)
END SUBROUTINE TM5_AEROSOL_INFO
END INTERFACE
