INTERFACE
SUBROUTINE TM5_KPP_JACOBIAN ( PV, PF, PRCT, PJVS )
 USE PARKIND1, ONLY : JPIM, JPRB
 USE TM5_KPP_PARAMETERS, ONLY : NVAR, NREACT, NFIX, LU_NONZERO
 REAL(KIND=JPRB), INTENT(IN) :: PV(NVAR)
 REAL(KIND=JPRB), INTENT(IN) :: PF(NFIX)
 REAL(KIND=JPRB), INTENT(IN) :: PRCT(NREACT)
 REAL(KIND=JPRB), INTENT(OUT) :: PJVS(LU_NONZERO)
END SUBROUTINE TM5_KPP_JACOBIAN
END INTERFACE
