INTERFACE
SUBROUTINE TM5_MACC_AEROSOL ( KIDIA,KFDIA,KLON,KLEV, KACTAERO,&
 & PAPH , PAEROK , PRHCL ,&
 & PTAUS_AER,PTAUA_AER, PMAER ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE TM5_PHOTOLYSIS_NEW , ONLY : NBANDS_TROP, NGRID, WL_EFF, WL_AER
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KACTAERO
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAEROK(KLON,KLEV,KACTAERO)
REAL(KIND=JPRB) ,INTENT(IN) :: PRHCL(KLON,KLEV)
REAL(KIND=JPRB), INTENT(OUT) :: PTAUS_AER(KLON,KLEV,NBANDS_TROP,NGRID)
REAL(KIND=JPRB), INTENT(OUT) :: PTAUA_AER(KLON,KLEV,NBANDS_TROP,NGRID)
REAL(KIND=JPRB), INTENT(OUT) :: PMAER(KLON,KLEV,NBANDS_TROP,NGRID)
END SUBROUTINE TM5_MACC_AEROSOL
END INTERFACE
