INTERFACE
SUBROUTINE TM5_WETCHEM_POINT(YGFL,PDT,PTEMP,PAP,PRS,PLP,PHPLUS,PY)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
REAL(KIND=JPRB),INTENT(IN) :: PDT
REAL(KIND=JPRB), INTENT(IN) :: PTEMP
REAL(KIND=JPRB), INTENT(IN) :: PRS
REAL(KIND=JPRB), INTENT(IN) :: PLP
REAL(KIND=JPRB), INTENT(IN) :: PAP
REAL(KIND=JPRB), INTENT(OUT) :: PHPLUS
REAL(KIND=JPRB), INTENT(INOUT) :: PY(YGFL%NCHEM)
END SUBROUTINE TM5_WETCHEM_POINT
END INTERFACE
