INTERFACE
SUBROUTINE TM5_DIRECTFLUX(KLEV, PANGLE,PT,PV2_COL,PV3_COL,PCST_O3_COL,&
 & PFDIR,PDV2_COL,PDV3_COL,PTAUA_CLD,&
 & PTAUA_AER,PGPH_DAT) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE TM5_PHOTOLYSIS_NEW , ONLY : MAXWAV, MAXW, FLUX, LFIN, SZA_LIMIT,&
 & NBANDS_TROP,NGRID, CROSS_O2 
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB),INTENT(IN) :: PANGLE
REAL(KIND=JPRB),INTENT(IN) :: PV2_COL(0:KLEV),PV3_COL(0:KLEV), PT(KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PCST_O3_COL(KLEV,MAXWAV)
REAL(KIND=JPRB),INTENT(OUT) :: PFDIR(KLEV,MAXW)
REAL(KIND=JPRB),INTENT(OUT) :: PDV2_COL(KLEV),PDV3_COL(KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTAUA_CLD(KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PTAUA_AER(KLEV,NBANDS_TROP,NGRID)
REAL(KIND=JPRB),INTENT(IN) :: PGPH_DAT(0:KLEV)
END SUBROUTINE TM5_DIRECTFLUX
END INTERFACE
