INTERFACE
SUBROUTINE TOVSLRIS(KBCDTYP,KINS,KDPT,KA,KB,KC,KV,KW,KX,KY,KZ )
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
INTEGER(KIND=JPIM),INTENT(IN) :: KBCDTYP
INTEGER(KIND=JPIM),INTENT(IN) :: KINS
INTEGER(KIND=JPIM),INTENT(IN) :: KDPT
INTEGER(KIND=JPIM),INTENT(OUT) :: KA
INTEGER(KIND=JPIM),INTENT(OUT) :: KB
INTEGER(KIND=JPIM),INTENT(OUT) :: KC
INTEGER(KIND=JPIM),INTENT(OUT) :: KV
INTEGER(KIND=JPIM),INTENT(OUT) :: KW
INTEGER(KIND=JPIM),INTENT(OUT) :: KX
INTEGER(KIND=JPIM),INTENT(OUT) :: KY
INTEGER(KIND=JPIM),INTENT(OUT) :: KZ
END SUBROUTINE TOVSLRIS
END INTERFACE
