INTERFACE
SUBROUTINE TRACE_GAS_DETECT(&
 & K__SENSOR,&
 & K__NCHANS,&
 & K__CHANID,&
 & P__OBSBTS,&
 & K__TRACE_GAS_FLAG ) 
USE PARKIND1, ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: K__Sensor
INTEGER(KIND=JPIM),INTENT(IN) :: K__Nchans
INTEGER(KIND=JPIM),INTENT(IN) :: K__Chanid(K__Nchans)
REAL(KIND=JPRB) ,INTENT(IN) :: P__ObsBTs(K__Nchans)
INTEGER(KIND=JPIM),INTENT(OUT) :: K__Trace_Gas_Flag(K__Nchans)
END SUBROUTINE TRACE_GAS_DETECT
END INTERFACE
