INTERFACE
SUBROUTINE TRANSINV_JBTOMODELAD(YDGEOMETRY,PSPEC,PREEL)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPEC(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(IN) :: PREEL(:,:,:)
END SUBROUTINE TRANSINV_JBTOMODELAD
END INTERFACE
