INTERFACE
SUBROUTINE TRANSINV_MDLAD(YDGEOMETRY,YDGMV,YDML_GCONF,PSPVOR,PSPDIV,PSPSP,PSPHV,PSPGFL,&
 & PGMV,PGMVS,PGFL,LDERR,LDVOR,LDFSCOMP,PSPVOR_FLT,PSPDIV_FLT) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) ,INTENT(INOUT) :: YDGMV
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPVOR(:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPDIV(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSP(:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPHV(:,:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPGFL(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGMV(:,:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMVS(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PGFL(:,:,:,:)
LOGICAL ,INTENT(IN) :: LDERR
LOGICAL ,INTENT(IN) :: LDVOR
LOGICAL ,INTENT(IN) :: LDFSCOMP
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT) :: PSPVOR_FLT(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(OUT) :: PSPDIV_FLT(:,:)
END SUBROUTINE TRANSINV_MDLAD
END INTERFACE
