INTERFACE
SUBROUTINE TRANSINV_FP(YDQTYPE,KRESOL,PSCA,PVOR,PDIV,PUMEAN,PVMEAN,PGP)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
INTEGER(KIND=JPIM),INTENT(IN) :: KRESOL
REAL(KIND=JPRB),INTENT(IN) :: PSCA(:,:)
REAL(KIND=JPRB),INTENT(IN) :: PVOR(:,:)
REAL(KIND=JPRB),INTENT(IN) :: PDIV(:,:)
REAL(KIND=JPRB),INTENT(IN),OPTIONAL :: PUMEAN(:)
REAL(KIND=JPRB),INTENT(IN),OPTIONAL :: PVMEAN(:)
REAL(KIND=JPRB),INTENT(OUT) :: PGP(:,:,:)
END SUBROUTINE TRANSINV_FP
END INTERFACE
