INTERFACE
SUBROUTINE TRARECA (PSLAC,PSLOC,PCLOC,PSLAR,PSLOR,PCLOR,KLEN,&
 & PSLAP,PCLAP,PSLOP,PCLOP,PFACDI,KTYP) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLAC(KLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLOC(KLEN)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLOC(KLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLAR(KLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLOR(KLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLOR(KLEN)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLAP
REAL(KIND=JPRB) ,INTENT(IN) :: PCLAP
REAL(KIND=JPRB) ,INTENT(IN) :: PSLOP
REAL(KIND=JPRB) ,INTENT(IN) :: PCLOP
REAL(KIND=JPRB) ,INTENT(IN) :: PFACDI
INTEGER(KIND=JPIM),INTENT(IN) :: KTYP
END SUBROUTINE TRARECA
END INTERFACE
