INTERFACE
SUBROUTINE TRMTOS_SPEC(YDSPEC,YDCOLS)
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
USE SPECTRAL_COLUMNS_MIX
USE MPL_MODULE
TYPE(SPECTRAL_FIELD), INTENT(IN) :: YDSPEC
TYPE(SPECTRAL_COLS) , INTENT(INOUT) :: YDCOLS
END SUBROUTINE TRMTOS_SPEC
END INTERFACE
