INTERFACE
SUBROUTINE TRWVTOF(KRESOL,PSPECG,KFGATHG,KTO,KVSET,PSPEC)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM) ,INTENT(IN) :: KRESOL
REAL(KIND=JPRB) ,INTENT(IN) :: PSPEC(:,:)
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFGATHG
INTEGER(KIND=JPIM) ,INTENT(IN) :: KTO(:)
INTEGER(KIND=JPIM) ,INTENT(IN) :: KVSET(:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPECG(:,:)
END SUBROUTINE TRWVTOF
END INTERFACE
