INTERFACE
SUBROUTINE TURBULENCE_LAYER(YDSURF,&
 & YDMODEL, KDIM, PAUX, STATE, TENDENCY, PRAD, PPERT,&
 & AUXL, GEMSL, PSURF, SURFL, FLUX, PDIAG, PERTL, LLKEYS, PDDHS,&
 & TENDENCY_LOC) 
USE TYPE_MODEL , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMPHYDER , ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & AUX_DIAG_LOCAL_TYPE, SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE,&
 & FLUX_TYPE, GEMS_LOCAL_TYPE, AUX_DIAG_TYPE,PERTURB_LOCAL_TYPE,&
 & KEYS_LOCAL_TYPE, DDH_SURF_TYPE, AUX_RAD_TYPE, PERTURB_TYPE 
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (STATE_TYPE) , INTENT (IN) :: TENDENCY
TYPE (AUX_RAD_TYPE) , INTENT (IN) :: PRAD
TYPE (PERTURB_TYPE) , INTENT (IN) :: PPERT
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT(INOUT) :: AUXL
TYPE (GEMS_LOCAL_TYPE) , INTENT(INOUT) :: GEMSL
TYPE (SURF_AND_MORE_TYPE) , INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: SURFL
TYPE (FLUX_TYPE) , INTENT(INOUT) :: FLUX
TYPE (AUX_DIAG_TYPE) , INTENT(INOUT) :: PDIAG
TYPE (PERTURB_LOCAL_TYPE) , INTENT(INOUT) :: PERTL
TYPE (KEYS_LOCAL_TYPE) , INTENT(INOUT) :: LLKEYS
TYPE (DDH_SURF_TYPE) , INTENT(INOUT) :: PDDHS
TYPE (STATE_TYPE) , INTENT(INOUT) :: TENDENCY_LOC
END SUBROUTINE TURBULENCE_LAYER
END INTERFACE
