INTERFACE
 SUBROUTINE UKCA_MODE_EMS(YDGEOMETRY,YDMODEL,KIDIA,KFDIA,KBOX,KLEV,KTILES,KSTGLO,PDLONARR,PDLATARR,PSMG,PLAND_FRAC,&
 & PSURTPG,PNOTG,PSEAICE,PAIRDG,PRHOAG,PUSTR,PUS10M,PSST, PSNOWICE,&
 & PEMANSO2G,PEMBIOMSO2G,PEMVOLCONSO2G,PEMVOLEXPSO2G,&
 & PEMCARG,PEMCARBMG,PSOA,&
 & KSO2EMS, KSSEMS,&
 & KPRIMSU_ON,KPRIMSOA_ON, KPRIMBCOC_ON,KPRIMSS_ON,KPRIMDU_ON,KPRODNI_ON,KVERBOSE,&
 & KSW, PALB, PALBD, PWIND, PAERGUST,PHSDFOR,&
 & PWS1, PSNS, PFRTI,PAERLTS,PAERSCC,PZ0M,PDSF,&
 & PSO4, PNH4, PNH3, PHNO3, PNO3,&
 & PT,PDP,PRHO,PRHCL,PTSPHY,&
 & PBUD_AER_MAS_PRIMSU,PBUD_AER_MAS_PRIMSOA, PBUD_AER_MAS_PRIMBC,&
 & PBUD_AER_MAS_PRIMOC, PBUD_AER_MAS_PRIMBCBB, PBUD_AER_MAS_PRIMOCBB,&
 & PBUD_AER_MAS_PRIMSS,PBUD_AER_MAS_PRIMDU,&
 & PBUD_AER_MAS_PRODNI, PBUD_AER_MAS_PRODAM,&
 & PBUD_AER_NUM_PRIMSU,PBUD_AER_NUM_PRIMSOA, PBUD_AER_NUM_PRIMCAR,PBUD_AER_NUM_PRIMCARBB,&
 & PBUD_AER_NUM_PRIMSS,PBUD_AER_NUM_PRIMDU,&
 & PBUD_AER_NUM_PRODNI, PBUD_AER_NUM_PRODAM, PTHNO3, PTNH3) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE UKCA_MODE_SETUP, ONLY: NMODES
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM), INTENT(IN) :: KBOX,KIDIA, KFDIA,KLEV,KTILES,KSW,KSTGLO
REAL(KIND=JPRB), INTENT(IN) :: PDLONARR(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PDLATARR(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PSMG(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PLAND_FRAC(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PSURTPG(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PNOTG(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PSEAICE(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PAIRDG(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PRHOAG(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PUSTR(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PUS10M(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PSST(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PEMANSO2G(KBOX,6)
REAL(KIND=JPRB), INTENT(IN) :: PEMBIOMSO2G(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PEMVOLCONSO2G(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PEMVOLEXPSO2G(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PEMCARG(KBOX,4)
REAL(KIND=JPRB), INTENT(IN) :: PSOA(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PEMCARBMG(KBOX,2)
REAL(KIND=JPRB), INTENT(IN) :: PSNOWICE(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PSO4(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PNH3(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PNH4(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PHNO3(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PNO3(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PDP(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRHO(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PT(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PRHCL(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PTSPHY
REAL(KIND=JPRB), INTENT(IN) :: PALB(KBOX) , PALBD(KBOX,KSW)
REAL(KIND=JPRB), INTENT(IN) :: PAERGUST(KBOX) , PWIND(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PHSDFOR(KBOX) ,PWS1(KBOX),PSNS(KBOX)
REAL(KIND=JPRB), INTENT(IN) :: PFRTI(KBOX,KTILES)
REAL(KIND=JPRB), INTENT(IN) :: PAERLTS(KBOX),PAERSCC(KBOX),PZ0M(KBOX),PDSF(KBOX)
INTEGER(KIND=JPIM), INTENT(IN) :: KSO2EMS
INTEGER(KIND=JPIM), INTENT(IN) :: KSSEMS
INTEGER(KIND=JPIM), INTENT(IN) :: KPRIMSU_ON
INTEGER(KIND=JPIM), INTENT(IN) :: KPRIMSOA_ON
INTEGER(KIND=JPIM), INTENT(IN) :: KPRIMBCOC_ON
INTEGER(KIND=JPIM), INTENT(IN) :: KPRIMSS_ON
INTEGER(KIND=JPIM), INTENT(IN) :: KPRIMDU_ON
INTEGER(KIND=JPIM), INTENT(IN) :: KPRODNI_ON
INTEGER(KIND=JPIM), INTENT(IN) :: KVERBOSE
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMSU(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMSOA(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMBC(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMOC(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMBCBB(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMOCBB(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMSS(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMDU(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRODNI(KBOX,KLEV,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRODAM(KBOX,KLEV,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMSU(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMSOA(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMCAR(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMCARBB(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMSS(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMDU(KBOX,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRODNI(KBOX,KLEV,NMODES)
REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRODAM(KBOX,KLEV,NMODES)
REAL(KIND=JPRB), INTENT(INOUT) :: PTHNO3(KBOX,KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PTNH3(KBOX,KLEV)
END SUBROUTINE UKCA_MODE_EMS
END INTERFACE
