INTERFACE
 SUBROUTINE UKCA_COAG_COFF_V(KV,LDMASK,PRI,PRJ,PVI,PVJ,PRHOI,PRHOJ,&
 & PMFPA,PDVISC,PT,PMID,PKIJ,KCOAG_ON,KCOAG) 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KV
 INTEGER(KIND=JPIM), INTENT(IN) :: KCOAG_ON
 INTEGER(KIND=JPIM), INTENT(IN) :: KCOAG
 REAL(KIND=JPRB), INTENT(IN) :: PRI(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PRJ(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PVI(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PVJ(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PRHOI(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PRHOJ(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PMFPA(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PDVISC(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PT(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KV)
 LOGICAL, INTENT(IN) :: LDMASK(KV)
 REAL(KIND=JPRB), INTENT(OUT) :: PKIJ(KV)
 END SUBROUTINE UKCA_COAG_COFF_V
END INTERFACE
