INTERFACE
 SUBROUTINE UKCA_COND_COFF_V(KV,LDMASK,PRP,PTSQRT,PAIRDM3,PRHOA,&
 & PMMCG,PSE,PDMOL,KFUCHS,PCC,PSINKARR,PMID,PT,PDIFVOL,KDCMFP) 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KV
 INTEGER(KIND=JPIM), INTENT(IN) :: KFUCHS
 INTEGER(KIND=JPIM), INTENT(IN) :: KDCMFP
 LOGICAL, INTENT(IN) :: LDMASK(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PRP(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PTSQRT(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PAIRDM3(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PRHOA(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PMMCG
 REAL(KIND=JPRB), INTENT(IN) :: PSE
 REAL(KIND=JPRB), INTENT(IN) :: PDMOL
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PT(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PDIFVOL
 REAL(KIND=JPRB), INTENT(OUT) :: PCC(KV)
 REAL(KIND=JPRB), INTENT(OUT) :: PSINKARR(KV)
 END SUBROUTINE UKCA_COND_COFF_V
END INTERFACE
