INTERFACE
 SUBROUTINE UKCA_PRIM_CAR(KIDIA,KFDIA,KBOX,&
 & PEMC,PEMCBM,PSURTP,KSO2EMS,PBUD_AER_MAS_PRIMBC,&
 & PBUD_AER_MAS_PRIMOC,PBUD_AER_MAS_PRIMBCBB, PBUD_AER_MAS_PRIMOCBB,&
 & PBUD_AER_NUM_PRIMCAR,PBUD_AER_NUM_PRIMCARBB) 
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, CP_BC, CP_OC, MODE,&
 & FRACOCEM, FRACBCEM, COMPONENT, MM, RHOCOMP 
 INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KSO2EMS
 REAL(KIND=JPRB), INTENT(IN) :: PSURTP(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PEMC(KBOX,4)
 REAL(KIND=JPRB), INTENT(IN) :: PEMCBM(KBOX,2)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMBC (KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMOC (KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMCAR(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMBCBB (KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMOCBB (KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMCARBB(KBOX,NMODES)
 END SUBROUTINE UKCA_PRIM_CAR
END INTERFACE
