INTERFACE
 SUBROUTINE UKCA_CLOUDPROC(KBOX,PND,PMD,PMDT,PDRYDP,&
 & PLOWCLOUD,PVFAC,PACT,KVERBOSE,KACTMETHOD,PBUD_AER_MAS) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, MODE, COMPONENT,&
 & SIGMAG, MFRAC_0, MMID,&
 & NUM_EPS, CP_SU, CP_BC, CP_OC, CP_SO 
 USE UKCA_SETUP_INDICES, ONLY: NBUDAER,&
 & NMASPROCSUINTR23, NMASPROCBCINTR23,&
 & NMASPROCOCINTR23, NMASPROCSOINTR23 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KVERBOSE
 INTEGER(KIND=JPIM), INTENT(IN) :: KACTMETHOD
 REAL(KIND=JPRB), INTENT(IN) :: PDRYDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PLOWCLOUD(KBOX),PVFAC(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PACT
 REAL(KIND=JPRB), INTENT(INOUT) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMDT(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMD(KBOX,NMODES,NCP)
 REAL(KIND=JPRB), INTENT(INOUT) :: PBUD_AER_MAS(KBOX,0:NBUDAER)
 END SUBROUTINE UKCA_CLOUDPROC
END INTERFACE
