INTERFACE
 SUBROUTINE UKCA_CALCMINMAXGC(CDSTR_AT,KBOX,PGC,KMYPROC)
 USE UKCA_SETUP_INDICES, ONLY: NCHEMG, CONDENSABLE
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KMYPROC
 REAL(KIND=JPRB), INTENT(IN) :: PGC(KBOX,NCHEMG)
 CHARACTER(LEN=30), INTENT(IN) :: CDSTR_AT
 END SUBROUTINE UKCA_CALCMINMAXGC
END INTERFACE
