INTERFACE
SUBROUTINE UKCA_CHEM_IFS(&
 & YDMODEL, KIDIA, KFDIA, KLON, KLEV, KTRAC, KACTAERO, KAERO,&
 & PAEROP, PGELAT, PGELAM, PTSPHY,&
 & PL, PI, PA,&
 & PAREA, PDELP,&
 & PT, PQ,PAPRSF, PCHEM2AER, KIFSCHEM,&
 & KWETOX_ON, KSO2WETOXBYO3, KDRYOX_IN_AER, KWETOX_IN_AER,&
 & PDELSO2_DRY_OH, PDELSO2_WET_O3, PDELSO2_WET_H2O2,&
 & PTENC&
 & ) 
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM ,JPRB
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KACTAERO
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO(KACTAERO)
INTEGER(KIND=JPIM),INTENT(IN) :: KIFSCHEM
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,KACTAERO),INTENT(IN) :: PAEROP
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PGELAT
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PGELAM
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(IN) :: PL
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(IN) :: PI
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(IN) :: PA
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PAREA
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(IN) :: PDELP
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PQ
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PAPRSF
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,4 ),INTENT(IN) :: PCHEM2AER
INTEGER(KIND=JPIM),INTENT(OUT) :: KWETOX_ON
INTEGER(KIND=JPIM),INTENT(OUT) :: KSO2WETOXBYO3
INTEGER(KIND=JPIM),INTENT(OUT) :: KDRYOX_IN_AER
INTEGER(KIND=JPIM),INTENT(OUT) :: KWETOX_IN_AER
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(OUT) :: PDELSO2_DRY_OH
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(OUT) :: PDELSO2_WET_O3
REAL(KIND=JPRB),DIMENSION(KLON,KLEV),INTENT(OUT) :: PDELSO2_WET_H2O2
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,KTRAC),INTENT(INOUT) :: PTENC
END SUBROUTINE UKCA_CHEM_IFS
END INTERFACE
