INTERFACE
 SUBROUTINE UKCA_CALCNUCRATE(KBOX,PDTZ,PT,PS,PRH,PAIRD,PH2SO4,&
 & PDELH2SO4_NUCL,PSEC_ORG,PRATE,KBLN_ON,KBLN,K_NUC_METHOD,&
 & PHEIGHT,PHTPBLG,PS_COND_S, LDMASK_EVAP) 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KBLN_ON
 INTEGER(KIND=JPIM), INTENT(IN) :: KBLN
 INTEGER(KIND=JPIM), INTENT(IN) :: K_NUC_METHOD
 REAL(KIND=JPRB), INTENT(IN) :: PSEC_ORG(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PDTZ
 REAL(KIND=JPRB), INTENT(IN) :: PT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PS(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PRH(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PAIRD(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PHEIGHT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PHTPBLG(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PS_COND_S(KBOX)
 REAL(KIND=JPRB), INTENT(INOUT) :: PH2SO4(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PRATE(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PDELH2SO4_NUCL(KBOX)
 LOGICAL, INTENT(IN) :: LDMASK_EVAP(KBOX)
 END SUBROUTINE UKCA_CALCNUCRATE
END INTERFACE
