INTERFACE
 SUBROUTINE UKCA_INGRIDG(KBINS,PMBSMALL,PMBLARGE,PMBMID,PMBLO,PMBHI)
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBINS
 REAL(KIND=JPRB), INTENT(IN) :: PMBSMALL
 REAL(KIND=JPRB), INTENT(IN) :: PMBLARGE
 REAL(KIND=JPRB), INTENT(OUT) :: PMBMID(KBINS)
 REAL(KIND=JPRB), INTENT(OUT) :: PMBLO(KBINS)
 REAL(KIND=JPRB), INTENT(OUT) :: PMBHI(KBINS)
 END SUBROUTINE UKCA_INGRIDG
END INTERFACE
