INTERFACE
 SUBROUTINE UKCA_VAPOUR(KBOX,PT,PMID,PS,PRP,PVPKEL,PWTS,PRHOSOL_STRAT)
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 REAL(KIND=JPRB), INTENT(IN) :: PT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PS(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PRP(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PWTS(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PVPKEL(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PRHOSOL_STRAT(KBOX)
 END SUBROUTINE UKCA_VAPOUR
END INTERFACE
