INTERFACE
 SUBROUTINE UKCA_VGRAV(KBOX,K,PDP,PSIGMA,PDVISC,PMFPA,PRHOP,LDMASK,PVGRAV_AV)
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: K
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 REAL(KIND=JPRB), INTENT(IN) :: PDP(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PSIGMA
 REAL(KIND=JPRB), INTENT(IN) :: PDVISC(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PMFPA(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PRHOP(KBOX)
 LOGICAL, INTENT(IN) :: LDMASK(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PVGRAV_AV(KBOX)
 END SUBROUTINE UKCA_VGRAV
END INTERFACE
