INTERFACE
SUBROUTINE UKCA_NO3NH4&
 & ( KIDIA, KFDIA , KLON , KLEV ,&
 & PSO4 , PNH4, PNO3_1, PNH3,PHNO3,&
 & PRHO, PRHCL, PT, PDP, PTSPHY, PTNO3_1, PTNH4,PTHNO3,PTNH3) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PSO4(KLON,KLEV), PDP(KLON, KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNH4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNO3_1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNH3(KLON,KLEV), PHNO3 (KLON, KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV),PRHO(KLON,KLEV),PRHCL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(OUT) :: PTNO3_1(KLON,KLEV), PTNH4(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTHNO3(KLON,KLEV), PTNH3(KLON,KLEV)
END SUBROUTINE UKCA_NO3NH4
END INTERFACE
