INTERFACE
 SUBROUTINE UKCA_IMPC_SCAV(KBOX,PND,PMD,&
 & PCRAIN,PDRAIN,PCSNOW,PDSNOW,PCLF,PWETDP,PDTC,PBUD_AER_MAS) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, MODE, NUM_EPS,&
 & COMPONENT, CP_SU, CP_BC, CP_OC, CP_CL, CP_SO, CP_DU,&
 & RADDROP, COLLEFF4 
 USE UKCA_SETUP_INDICES, ONLY: NBUDAER,&
 & NMASIMSCBCACCSOL, NMASIMSCBCAITINS,&
 & NMASIMSCBCAITSOL, NMASIMSCBCCORSOL,&
 & NMASIMSCDUACCINS, NMASIMSCDUACCSOL,&
 & NMASIMSCDUCORINS, NMASIMSCDUCORSOL,&
 & NMASIMSCOCACCSOL, NMASIMSCOCAITINS, NMASIMSCOCAITSOL,&
 & NMASIMSCOCCORSOL, NMASIMSCOCNUCSOL,&
 & NMASIMSCSOACCSOL, NMASIMSCSOAITSOL,&
 & NMASIMSCSOCORSOL, NMASIMSCSONUCSOL,&
 & NMASIMSCSSACCSOL, NMASIMSCSSCORSOL,&
 & NMASIMSCSUACCSOL, NMASIMSCSUAITSOL,&
 & NMASIMSCSUCORSOL, NMASIMSCSUNUCSOL,&
 & NMASMERGOCINTR34 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 REAL(KIND=JPRB), INTENT(IN) :: PMD(KBOX,NMODES,NCP)
 REAL(KIND=JPRB), INTENT(IN) :: PWETDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PDTC
 REAL(KIND=JPRB), INTENT(IN) :: PCRAIN(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PDRAIN(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PCSNOW(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PDSNOW(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PCLF(KBOX)
 REAL(KIND=JPRB), INTENT(INOUT) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PBUD_AER_MAS(KBOX,0:NBUDAER)
 END SUBROUTINE UKCA_IMPC_SCAV
END INTERFACE
