INTERFACE
 SUBROUTINE UKCA_CALC_COAG_KERNEL(KBOX,PND,PKII_ARR,PKIJ_ARR,&
 & PDRYDP,PDVOL,PWETDP,PWVOL,PRHOPAR,PMFPA,PDVISC,PT,PMID,&
 & KCOAG_ON,KCOAG) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, MODE, NUM_EPS, MODESOL
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KCOAG_ON
 INTEGER(KIND=JPIM), INTENT(IN) :: KCOAG
 REAL(KIND=JPRB), INTENT(IN) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PDRYDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PDVOL(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PWETDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PWVOL(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PRHOPAR(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PMFPA(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PDVISC(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PKII_ARR(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PKIJ_ARR(KBOX,NMODES,NMODES)
 END SUBROUTINE UKCA_CALC_COAG_KERNEL
END INTERFACE
