INTERFACE
 SUBROUTINE UKCA_CHECK_MD_ND(KBOX,CDPROCESS,PND,PMD,PMDT,KMYPROC)
 USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, MODE, COMPONENT, MLO
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KMYPROC
 REAL(KIND=JPRB), INTENT(IN) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PMDT(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PMD(KBOX,NMODES,NCP)
 CHARACTER(LEN=30), INTENT(IN) :: CDPROCESS
 END SUBROUTINE UKCA_CHECK_MD_ND
END INTERFACE
