INTERFACE
 SUBROUTINE UKCA_CONDEN(KBOX,PGC,PND,PMD,PMDT,&
 & PDTZ,PDRYDP,PWETDP,PTSQRT,PRHOA,PAIRDM3,PDELGC_COND,KMO6_COND_ON,&
 & KFUCHS,PAGETERM1,PBUD_AER_MAS,PS_COND_S,PMID,PT,PS,PAIRD,&
 & KDCMFP,KCONDIAM,LDMASK_EVAP) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, MODE,&
 & SIGMAG, MODESOL, NUM_EPS,&
 & CP_SU, CP_OC, CP_SO 
 USE UKCA_SETUP_INDICES, ONLY: NCHEMG, NBUDAER, MH2SO4, MSEC_ORG,&
 & CONDENSABLE, CONDENSABLE_CHOICE, DIMEN, MM_GAS,&
 & NMASCONDOCACCINS, NMASCONDOCACCSOL, NMASCONDOCAITINS,&
 & NMASCONDOCAITSOL, NMASCONDOCCORINS, NMASCONDOCCORSOL,&
 & NMASCONDOCNUCSOL,&
 & NMASCONDSOACCINS, NMASCONDSOACCSOL, NMASCONDSOAITINS,&
 & NMASCONDSOAITSOL, NMASCONDSOCORINS, NMASCONDSOCORSOL,&
 & NMASCONDSONUCSOL,&
 & NMASCONDSUACCINS, NMASCONDSUACCSOL, NMASCONDSUAITINS,&
 & NMASCONDSUAITSOL, NMASCONDSUCORINS, NMASCONDSUCORSOL,&
 & NMASCONDSUNUCSOL 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KFUCHS
 INTEGER(KIND=JPIM), INTENT(IN) :: KDCMFP
 INTEGER(KIND=JPIM), INTENT(IN) :: KCONDIAM
 INTEGER(KIND=JPIM), INTENT(IN) :: KMO6_COND_ON
 REAL(KIND=JPRB), INTENT(INOUT) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PTSQRT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PRHOA(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PAIRDM3(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PDTZ
 REAL(KIND=JPRB), INTENT(IN) :: PWETDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PDRYDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PS(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PAIRD(KBOX)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMD(KBOX,NMODES,NCP)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMDT(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PGC(KBOX,NCHEMG)
 REAL(KIND=JPRB), INTENT(INOUT) :: PBUD_AER_MAS(KBOX,0:NBUDAER)
 REAL(KIND=JPRB), INTENT(OUT) :: PDELGC_COND(KBOX,NCHEMG)
 REAL(KIND=JPRB), INTENT(OUT) :: PAGETERM1(KBOX,3,NCHEMG)
 REAL(KIND=JPRB), INTENT(OUT) :: PS_COND_S(KBOX)
 LOGICAL, INTENT(OUT) :: LDMASK_EVAP(KBOX)
 END SUBROUTINE UKCA_CONDEN
END INTERFACE
