INTERFACE
SUBROUTINE UKCA_AERO_STEP_IFS&
 & ( YDMODEL, KIDIA, KFDIA, KLON, KLEV, KAERO, KTRAC, KFLDX,KLEVX,&
 & PAREA , PTSPHY ,&
 & PGELAT , PAPRSF , PAPRS , PT , PAPHI,&
 & PAERUST, PAZ0M, PA, PL, PI, PLSM , PCI , PQ , PQSAT , PSNS,&
 & PFPLCL , PFPLCN , PFPLSL, PFPLSN, PLU, PBLH ,&
 & KWETOX_ON, KSO2WETOXBYO3, KDRYOX_IN_AER, KWETOX_IN_AER,&
 & PDELSO2_DRY_OH, PDELSO2_WET_O3, PDELSO2_WET_H2O2, PAEROP,&
 & PND, PMD, PMDT,&
 & PSURF,&
 & PTENC, PCEN,&
 & PGLOMAP_DIAGS, PEXTRA) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL ,ONLY : YGFL
USE YOMPHYDER ,ONLY : SURF_AND_MORE_TYPE
USE TYPE_MODEL,ONLY : MODEL
USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, CP_BC, CP_CL, CP_DU, CP_OC, CP_SU,&
 & COMPONENT, NUM_EPS, MM, MODE, MODESOL 
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),DIMENSION(YGFL%NAERO),INTENT(IN) :: KAERO
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDX,KLEVX
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PAREA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PGELAT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PAPRSF
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV),INTENT(IN) :: PAPRS
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PT
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV) ,INTENT(IN) :: PAPHI
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PAERUST
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PAZ0M
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PA
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PL
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PI
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PLSM
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PCI
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PQ
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PQSAT
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PSNS
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV),INTENT(IN) :: PFPLCL
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV),INTENT(IN) :: PFPLCN
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV),INTENT(IN) :: PFPLSL
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV),INTENT(IN) :: PFPLSN
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PLU
REAL(KIND=JPRB),DIMENSION(KLON) ,INTENT(IN) :: PBLH
INTEGER(KIND=JPIM) ,INTENT(IN) :: KWETOX_ON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSO2WETOXBYO3
INTEGER(KIND=JPIM) ,INTENT(IN) :: KDRYOX_IN_AER
INTEGER(KIND=JPIM) ,INTENT(IN) :: KWETOX_IN_AER
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PDELSO2_DRY_OH
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PDELSO2_WET_O3
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PDELSO2_WET_H2O2
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,YDMODEL%YRML_GCONF%YGFL%NAERO),INTENT(IN) :: PAEROP
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES),INTENT(IN) :: PND
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES,NCP),INTENT(IN) :: PMD
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES),INTENT(IN) :: PMDT
TYPE (SURF_AND_MORE_TYPE) ,INTENT(INOUT) :: PSURF
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,KTRAC) ,INTENT(INOUT) :: PTENC
REAL(KIND=JPRB),DIMENSION(KLON,MAX(KLEV,60),60),INTENT(OUT) :: PGLOMAP_DIAGS
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,KTRAC) ,INTENT(INOUT) :: PCEN
REAL(KIND=JPRB),INTENT(INOUT) :: PEXTRA(KLON,KLEVX,KFLDX)
END SUBROUTINE UKCA_AERO_STEP_IFS
END INTERFACE
