INTERFACE
SUBROUTINE UKCA_AERO_DIAG_IFS&
 & ( KIDIA, KFDIA, KLON, KLEV, KAERO, KTRAC, PTSPHY,&
 & PAPRSF , PAPRS, PT , PQ, PQSAT,&
 & PTENC, PCEN, PDRYDIAM, PWETDIAM, PDRYVOL, PWETVOL,&
 & PVOL_WAT, PRHOPAR, PAERAOT, PAERAAOT, PAERASY, PND, PMD, PMDT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL ,ONLY : YGFL
USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, CP_CL, CP_OC, CP_SU,&
 & COMPONENT, NUM_EPS, MM, MFRAC_0, MMID, MODE, MLO,&
 & MHI, MODESOL 
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),DIMENSION(YGFL%NAERO),INTENT(IN) :: KAERO
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PAPRSF
REAL(KIND=JPRB),DIMENSION(KLON,0:KLEV) ,INTENT(IN) :: PAPRS
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PQ
REAL(KIND=JPRB),DIMENSION(KLON,KLEV) ,INTENT(IN) :: PQSAT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,KTRAC) ,INTENT(IN) :: PTENC
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,KTRAC) ,INTENT(IN) :: PCEN
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES) ,INTENT(OUT) :: PDRYDIAM
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES) ,INTENT(OUT) :: PWETDIAM
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES) ,INTENT(OUT) :: PDRYVOL
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES) ,INTENT(OUT) :: PWETVOL
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES) ,INTENT(OUT) :: PVOL_WAT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES) ,INTENT(OUT) :: PRHOPAR
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,6) ,INTENT(OUT) :: PAERAOT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,6) ,INTENT(OUT) :: PAERAAOT
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,6) ,INTENT(OUT) :: PAERASY
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES),INTENT(OUT) :: PND
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES,NCP),INTENT(OUT) :: PMD
REAL(KIND=JPRB),DIMENSION(KLON,KLEV,NMODES),INTENT(OUT) :: PMDT
END SUBROUTINE UKCA_AERO_DIAG_IFS
END INTERFACE
