INTERFACE
 SUBROUTINE UKCA_AGEING(KBOX,PND,PMD,PMDT,&
 & PAGETERM1,PAGETERM2,PWETDP,KVERBOSE,PBUD_AER_MAS) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, MODE, NUM_EPS, MM, COMPONENT,&
 & CP_BC, CP_OC, CP_SU, CP_SO, CP_DU, NCP 
 USE UKCA_SETUP_INDICES, ONLY: NCHEMG, NBUDAER, CONDENSABLE,&
 & CONDENSABLE_CHOICE, MM_GAS, DIMEN,&
 & NMASAGEDBCINTR52,&
 & NMASAGEDDUINTR63, NMASAGEDDUINTR74,&
 & NMASAGEDOCINTR52, NMASAGEDOCINTR63, NMASAGEDOCINTR74,&
 & NMASAGEDSOINTR52, NMASAGEDSOINTR63, NMASAGEDSOINTR74,&
 & NMASAGEDSUINTR52, NMASAGEDSUINTR63, NMASAGEDSUINTR74 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KVERBOSE
 REAL(KIND=JPRB), INTENT(IN) :: PAGETERM1(KBOX,3,NCHEMG)
 REAL(KIND=JPRB), INTENT(IN) :: PAGETERM2(KBOX,4,3,NCP)
 REAL(KIND=JPRB), INTENT(IN) :: PWETDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMD(KBOX,NMODES,NCP)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMDT(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PBUD_AER_MAS(KBOX,0:NBUDAER)
 END SUBROUTINE UKCA_AGEING
END INTERFACE
