INTERFACE
 SUBROUTINE UKCA_PRIM_SOA(KIDIA,KFDIA,KBOX,&
 & PSOA,PBUD_AER_MAS_PRIMSOA, PBUD_AER_NUM_PRIMSOA) 
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE UKCA_MODE_SETUP, ONLY: NMODES, CP_OC, NCP, MODE, COMPONENT,&
 & MM, RHOCOMP 
 INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA, KFDIA, KBOX
 REAL(KIND=JPRB), INTENT(IN) :: PSOA(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_MAS_PRIMSOA (KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(OUT) :: PBUD_AER_NUM_PRIMSOA(KBOX,NMODES)
 END SUBROUTINE UKCA_PRIM_SOA
END INTERFACE
