INTERFACE
 SUBROUTINE UKCA_SOLVECOAGNUCL_V(KV,LDMASK,PA,PB,PC,PND,PDTZ,PDELN)
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KV
 REAL(KIND=JPRB), INTENT(IN) :: PA(KV)
 REAL(KIND=JPRB), INTENT(INOUT) :: PB(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PC(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PND(KV)
 REAL(KIND=JPRB), INTENT(IN) :: PDTZ
 LOGICAL, INTENT(IN) :: LDMASK(KV)
 REAL(KIND=JPRB), INTENT(INOUT) :: PDELN(KV)
 END SUBROUTINE UKCA_SOLVECOAGNUCL_V
END INTERFACE
