INTERFACE
SUBROUTINE UKCA_MODE_EMS_IFS&
 & ( YDGEOMETRY, YDMODEL, KDIM,&
 & KSTEP, KSTART, KTRAC, KAERO,&
 & PAREA, PGELAM, PGELAT, PCI, PLSM, PAZ0M,&
 & PAERUST, PGAW,&
 & PBCBF, PBCFF, PBCGF, POMBF, POMFF, POMGF,&
 & PSO2L, PSO2H, PSOGF, PVOLC, PVOLE, PSOA, PDMS,&
 & PVOLCALTI, PLAIL, PLAIH, PFRTI, PWS1,&
 & PT, PQ, PRS1, PAPRSF, PAPHI,&
 & PTS, PTSPHY, PSST, PINJF, PBLH,&
 & KSW, PALB, PALBD, PWIND, PAERGUST,PHSDFOR, PSNS,&
 & PAERLTS,PAERSCC, PZ0M, PDSF, PSO2DD, PCEN,&
 & PSO4, PNH4, PNH3, PHNO3, PNO3,&
 & PCFLX, PTENC, PEXTRA,&
 & PGLO_MASS_EMS, PGLO_NUM_EMS,&
 & PAERSRC, PAERDDP,&
 & PDMSO, PLDAY, PLISS, PSO2, PTDMS,&
 & PDMSI, PODMS, PTHNO3, PTNH3 ) 
USE PARKIND1 ,ONLY : JPIM, JPRB, JPRD
USE YOMPHYDER ,ONLY : DIMENSION_TYPE
USE UKCA_MODE_SETUP, ONLY: NMODES, CP_BC, CP_CL, CP_DU, CP_OC, CP_SU, CP_NI, CP_AM, NCP, MODE, COMPONENT, MM
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC, KSTEP, KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KAERO(YDMODEL%YRML_GCONF%YGFL%NAERO)
INTEGER(KIND=JPIM),INTENT(IN) :: KSW
REAL(KIND=JPRB) ,INTENT(IN) :: PALB(KDIM%KLON) , PALBD(KDIM%KLON,KSW)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERGUST(KDIM%KLON) , PWIND(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHSDFOR(KDIM%KLON) , PWS1(KDIM%KLON),PSNS(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAREA(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCI(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOLCALTI(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAZ0M(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAERUST(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGAW(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PBCBF(KDIM%KLON), PBCFF(KDIM%KLON), PBCGF(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: POMBF(KDIM%KLON), POMFF(KDIM%KLON), POMGF(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSO2L(KDIM%KLON), PSO2H(KDIM%KLON), PSOGF(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PINJF(KDIM%KLON), PBLH(KDIM%KLON), PSST(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOLC(KDIM%KLON), PVOLE(KDIM%KLON), PSOA(KDIM%KLON) , PDMS(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAIL(KDIM%KLON), PLAIH(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTI(KDIM%KLON,KDIM%KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRS1(KDIM%KLON,0:KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAERLTS(KDIM%KLON),PAERSCC(KDIM%KLON),PZ0M(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PDSF(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSO2DD(KDIM%KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCEN(KDIM%KLON,KDIM%KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PSO4(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNH3(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNH4(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PHNO3(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PNO3(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCFLX(KDIM%KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KDIM%KLON,KDIM%KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEXTRA(KDIM%KLON,KDIM%KLEVX,KDIM%KFLDX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGLO_MASS_EMS(KDIM%KLON,NMODES+35), PGLO_NUM_EMS(KDIM%KLON,NMODES+21)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERSRC(KDIM%KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAERDDP(KDIM%KLON,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB),INTENT(OUT) :: PDMSO(KDIM%KLON), PLDAY(KDIM%KLON), PLISS(KDIM%KLON), PSO2(KDIM%KLON), PTDMS(KDIM%KLON)
REAL(KIND=JPRB),INTENT(OUT) :: PDMSI(KDIM%KLON), PODMS(KDIM%KLON)
REAL(KIND=JPRB), INTENT(INOUT) :: PTHNO3(KDIM%KLON,KDIM%KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PTNH3(KDIM%KLON,KDIM%KLEV)
END SUBROUTINE UKCA_MODE_EMS_IFS
END INTERFACE
