INTERFACE
SUBROUTINE UKCA_OFFL_OX(&
 & KIDIA, KFDIA, KLON, KLEV, KTRAC,&
 & KIFSCHEM, KDO_DMS_CHEM, KDO_SO2_CHEM, KDO_SEC_ORG_CHEM,&
 & PAREA, PDELP,&
 & PCEN, PT, PAPRSF,&
 & PTSPHY,&
 & PDELSO2_DRY_OH&
 & ) 
USE PARKIND1 , ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA, KFDIA, KLON, KLEV, KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KIFSCHEM, KDO_DMS_CHEM, KDO_SO2_CHEM, KDO_SEC_ORG_CHEM
REAL(KIND=JPRB),INTENT(IN) :: PAREA(KLON), PDELP(KLON,KLEV)
REAL(KIND=JPRB),INTENT(IN) :: PT(KLON,KLEV), PAPRSF(KLON,KLEV)
REAL(KIND=JPRB),INTENT(INOUT) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB),INTENT(IN) :: PTSPHY
REAL(KIND=JPRB),INTENT(OUT) :: PDELSO2_DRY_OH(KLON,KLEV)
END SUBROUTINE UKCA_OFFL_OX
END INTERFACE
