INTERFACE
 SUBROUTINE UKCA_REMODE(KBOX,KLEVTROP,PND,PMD,PMDT,PDRYDP,PWETDP,KVERBOSE,&
 & KMERGE,PBUD_AER_MAS,K_MERGE_1D,PMID) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, NCP, MODE, DDPMID, DDPLIM0,&
 & NUM_EPS, SIGMAG, COMPONENT, MFRAC_0, MMID,&
 & CP_SU, CP_BC, CP_OC, CP_CL, CP_SO 
 USE UKCA_SETUP_INDICES, ONLY: NBUDAER,&
 & NMASMERGBCINTR23, NMASMERGBCINTR34,&
 & NMASMERGOCINTR12, NMASMERGOCINTR23, NMASMERGOCINTR34,&
 & NMASMERGSOINTR12, NMASMERGSOINTR23, NMASMERGSOINTR34,&
 & NMASMERGSSINTR34,&
 & NMASMERGSUINTR12, NMASMERGSUINTR23, NMASMERGSUINTR34 
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KLEVTROP
 INTEGER(KIND=JPIM), INTENT(IN) :: KVERBOSE
 INTEGER(KIND=JPIM), INTENT(IN) :: KMERGE
 REAL(KIND=JPRB), INTENT(IN) :: PDRYDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PWETDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KBOX)
 INTEGER(KIND=JPIM), INTENT(INOUT) :: K_MERGE_1D(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMD(KBOX,NMODES,NCP)
 REAL(KIND=JPRB), INTENT(INOUT) :: PMDT(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(INOUT) :: PBUD_AER_MAS(KBOX,0:NBUDAER)
 END SUBROUTINE UKCA_REMODE
END INTERFACE
