INTERFACE
 SUBROUTINE UKCA_WETOX(KBOX,PND,PDRYDP,PDELSO2,PDELSO2_2,&
 & PDELH2O2,PLOWCLOUD,PVFAC,PSO2VMR,PH2O2,PZH2O2,PZO3,PZHO2,PMID,&
 & PT,PAIRD,PS,PDTC,KLDAY,PLWC,KSO2WETOXBYO3) 
 USE UKCA_MODE_SETUP, ONLY: NMODES, MODE, NUM_EPS
 USE PARKIND1, ONLY: JPRB, JPIM
 INTEGER(KIND=JPIM), INTENT(IN) :: KBOX
 INTEGER(KIND=JPIM), INTENT(IN) :: KLDAY(KBOX)
 INTEGER(KIND=JPIM), INTENT(IN) :: KSO2WETOXBYO3
 REAL(KIND=JPRB), INTENT(IN) :: PND(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PDRYDP(KBOX,NMODES)
 REAL(KIND=JPRB), INTENT(IN) :: PLOWCLOUD(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PVFAC(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PSO2VMR(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PZO3(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PZH2O2(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PZHO2(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PMID(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PT(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PAIRD(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PS(KBOX)
 REAL(KIND=JPRB), INTENT(IN) :: PDTC
 REAL(KIND=JPRB), INTENT(IN) :: PLWC(KBOX)
 REAL(KIND=JPRB), INTENT(INOUT) :: PH2O2(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PDELSO2(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PDELSO2_2(KBOX)
 REAL(KIND=JPRB), INTENT(OUT) :: PDELH2O2(KBOX)
 END SUBROUTINE UKCA_WETOX
END INTERFACE
