INTERFACE
SUBROUTINE UPDATE_FIELDS (YDPHY2,KONFIG, KIDIA, KFDIA, KLON, KLEV,&
 & PI1, PI2, PI3, PI4, PI5, PI6, PI7, PI8, PI9, PI10,&
 & PI11,PI12,PI13,&
 & PS1, PS2, PS3, PS4, PS5, PS6, PS7, PS8, PS9, PS10,&
 & PS11,PS12,PS13,&
 & PA1, PA2, PA3, PA4, PA5, PA6, PA7, PA8, PA9, PA10,&
 & PA11,PA12,PA13,&
 & LDV1, LDV2, LDV3, LDV4, LDV5, LDV6, LDV7, LDV8, LDV9, LDV10,&
 & LDV11,LDV12,LDV13,&
 & PTA1, PTA2, PTA3, PTA4, PTA5, PTA6, PTA7, PTA8, PTA9, PTA10,&
 & PTA11,PTA12,PTA13,&
 & PTS1, PTS2, PTS3, PTS4, PTS5, PTS6, PTS7, PTS8, PTS9, PTS10,&
 & PTS11,PTS12,PTS13,&
 & PO1, PO2, PO3, PO4, PO5, PO6, PO7, PO8, PO9, PO10,&
 & PO11,PO12,PO13) 
USE PARKIND1 , ONLY : JPIM ,JPRB
USE YOMPHY2 , ONLY : TPHY2
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN) :: KONFIG
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA13(KLON,KLEV)
LOGICAL, OPTIONAL, INTENT(IN) :: LDV1
LOGICAL, OPTIONAL, INTENT(IN) :: LDV2
LOGICAL, OPTIONAL, INTENT(IN) :: LDV3
LOGICAL, OPTIONAL, INTENT(IN) :: LDV4
LOGICAL, OPTIONAL, INTENT(IN) :: LDV5
LOGICAL, OPTIONAL, INTENT(IN) :: LDV6
LOGICAL, OPTIONAL, INTENT(IN) :: LDV7
LOGICAL, OPTIONAL, INTENT(IN) :: LDV8
LOGICAL, OPTIONAL, INTENT(IN) :: LDV9
LOGICAL, OPTIONAL, INTENT(IN) :: LDV10
LOGICAL, OPTIONAL, INTENT(IN) :: LDV11
LOGICAL, OPTIONAL, INTENT(IN) :: LDV12
LOGICAL, OPTIONAL, INTENT(IN) :: LDV13
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTA13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PTS13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(INOUT) :: PO13(KLON,KLEV)
END SUBROUTINE UPDATE_FIELDS
END INTERFACE
