INTERFACE
SUBROUTINE UPDATE_OBSDB(YDODB,YDGEOMETRY,KLOG_IO, CDBNAME_IN, CDBNAME_OUT, LDTRANSFORM,&
 & LDFORCE_WRITABLE, LDFORCE_SWAPOUT,&
 & KANDAT, KANTIM, KNMXUPD, KNUMTSL, LDFEEDBACK, LDIFS) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRD
USE YOMDB
USE ODB_MODULE
USE YOMCMDDR
USE YOMCOCTP
USE DBASE_MOD , ONLY : DBASE
CLASS(DBASE), INTENT(INOUT) :: YDODB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=*), INTENT(IN) :: CDBNAME_IN, CDBNAME_OUT
LOGICAL, INTENT(OUT) :: LDTRANSFORM
INTEGER(KIND=JPIM), INTENT(INOUT) :: KANDAT, KANTIM, KNUMTSL
INTEGER(KIND=JPIM), INTENT(IN) :: KLOG_IO, KNMXUPD
LOGICAL, INTENT(IN) :: LDFORCE_WRITABLE, LDFORCE_SWAPOUT, LDFEEDBACK, LDIFS
END SUBROUTINE UPDATE_OBSDB
END INTERFACE
