INTERFACE
SUBROUTINE UPDCLIE_OASIS(YDGEOMETRY,YDSURF,YDMCC,YDRIP,YDERAD,PTSTEP)
 USE PARKIND1, ONLY: JPRB, JPIM
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 USE SURFACE_FIELDS_MIX , ONLY : TSURF
 USE YOMMCC , ONLY : TMCC
 USE YOMRIP , ONLY : TRIP
 USE YOERAD , ONLY : TERAD
 TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
 TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
 TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
 TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
 TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
 REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
END SUBROUTINE UPDCLIE_OASIS
END INTERFACE
