INTERFACE
SUBROUTINE UPDCLIE_COMPO(YDGEOMETRY,YDSURF,YDCOMPO,YDMCC,YDERAD,YDML_GCONF,PTSTEP)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOERAD , ONLY : TERAD
USE YOMMCC , ONLY : TMCC
USE YOMCOMPO , ONLY : TCOMPO
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TCOMPO) ,INTENT(INOUT) :: YDCOMPO
TYPE(TERAD) ,INTENT(INOUT) :: YDERAD
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
END SUBROUTINE UPDCLIE_COMPO
END INTERFACE
