INTERFACE
SUBROUTINE UPDCELAUT(YDML_PHY_STOCH,KCELL,PWGHT,KIIP,KJJP)
USE MODEL_PHYSICS_STOCHAST_MOD , ONLY : MODEL_PHYSICS_STOCHAST_TYPE
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(MODEL_PHYSICS_STOCHAST_TYPE),INTENT(INOUT):: YDML_PHY_STOCH
INTEGER(KIND=JPIM),INTENT(IN) :: KIIP
INTEGER(KIND=JPIM),INTENT(IN) :: KJJP
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCELL(KIIP*4,KJJP*4)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWGHT(KIIP,KJJP)
END SUBROUTINE UPDCELAUT
END INTERFACE
