INTERFACE
SUBROUTINE UPDICETEMP(YDGEOMETRY,YDSURF,YDMCC,YDEPHY)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOEPHY , ONLY : TEPHY
USE YOMMCC , ONLY : TMCC
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
END SUBROUTINE UPDICETEMP
END INTERFACE
