INTERFACE
SUBROUTINE UPDNEMOOCEAN(YDMCC,YDEPHY,YDRIP,KPROMA,KGPTOT,KSTEP,PTSTEP,YDSURF,YDGEOMETRY)
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1, ONLY : JPRD, JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMRIP , ONLY : TRIP
USE YOMMCC , ONLY : TMCC
USE GEOMETRY_MOD, ONLY : GEOMETRY
TYPE(TEPHY) ,INTENT(INOUT):: YDEPHY
TYPE(TMCC) ,INTENT(INOUT):: YDMCC
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
END SUBROUTINE UPDNEMOOCEAN
END INTERFACE
