INTERFACE
SUBROUTINE UPDRGAS(YDERAD,YDERDI,YDRIP,PSOLINC)
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE YOMRIP , ONLY : TRIP
USE YOERAD , ONLY : TERAD
USE YOERDI , ONLY : TERDI
TYPE(TERAD), INTENT(IN) :: YDERAD
TYPE(TERDI), INTENT(INOUT) :: YDERDI
TYPE(TRIP), INTENT(IN) :: YDRIP
REAL(KIND=JPRB), INTENT(IN), OPTIONAL :: PSOLINC
END SUBROUTINE UPDRGAS
END INTERFACE
