INTERFACE
SUBROUTINE UPDTIM(YDGEOMETRY,YDSURF,YDMODEL,KSTEP,PTDT,PTSTEP,LDCLUPD,PI05)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PTDT
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
LOGICAL ,INTENT(IN) :: LDCLUPD
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PI05
END SUBROUTINE UPDTIM
END INTERFACE
