INTERFACE
SUBROUTINE UPDTIER(YDML_PHY_RAD,YDRIP,KSTEP,KRADFR,PTSTEP)
USE MODEL_PHYSICS_RADIATION_MOD , ONLY : MODEL_PHYSICS_RADIATION_TYPE
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMRIP , ONLY : TRIP
TYPE(MODEL_PHYSICS_RADIATION_TYPE),INTENT(INOUT):: YDML_PHY_RAD
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KRADFR
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
END SUBROUTINE UPDTIER
END INTERFACE
