INTERFACE
SUBROUTINE UVR&
 & ( YDEOVLP,YDERAD,YDECLD,KIDIA , KFDIA , KLON , KLEV ,&
 & PALBD , PCG , PCLD , POMEGA, PSEC , PTAU,&
 & PCGAZ , PPIZAZ, PRAY1, PRAY2 , PREFZ, PRJ , PRK , PRMUE,&
 & PTAUAZ, PTRA1 , PTRA2, PTRCLD&
 & ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOERAD , ONLY : TERAD
USE YOECLD , ONLY : TECLD
USE YOEOVLP , ONLY : TEOVLP
TYPE(TECLD) ,INTENT(INOUT):: YDECLD
TYPE(TEOVLP) ,INTENT(INOUT):: YDEOVLP
TYPE(TERAD) ,INTENT(INOUT):: YDERAD
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PALBD(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCG(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: POMEGA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSEC(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCGAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PPIZAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTAUAZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRAY2(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PREFZ(KLON,2,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRJ(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRK(KLON,6,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRMUE(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRA2(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTRCLD(KLON)
END SUBROUTINE UVR
END INTERFACE
