INTERFACE
SUBROUTINE UVRADI_LAYER(YDSURF,&
 & YDMODEL,KDIM, PAUX, AUXL, GEMSL, SURFL, STATE, PDIAG, PSURF, UVP1, CHEM) 
USE TYPE_MODEL , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE VARIABLE_MODULE , ONLY : VARIABLE_3D
USE YOMPHYDER , ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE,&
 & SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE, AUX_DIAG_LOCAL_TYPE,&
 & GEMS_LOCAL_TYPE, AUX_DIAG_TYPE 
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE (DIMENSION_TYPE) , INTENT (IN) :: KDIM
TYPE (AUX_TYPE) , INTENT (IN) :: PAUX
TYPE (AUX_DIAG_LOCAL_TYPE) , INTENT (IN) :: AUXL
TYPE (GEMS_LOCAL_TYPE) , INTENT (IN) :: GEMSL
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT (IN) :: SURFL
TYPE (STATE_TYPE) , INTENT (IN) :: STATE
TYPE (AUX_DIAG_TYPE) , INTENT (IN) :: PDIAG
TYPE (SURF_AND_MORE_TYPE) , INTENT (INOUT):: PSURF
TYPE(VARIABLE_3D) , INTENT(INOUT) :: UVP1
TYPE(VARIABLE_3D) , INTENT(INOUT) :: CHEM(:)
END SUBROUTINE UVRADI_LAYER
END INTERFACE
