INTERFACE
SUBROUTINE UVSPE(YDGEOMETRY,PETPSI,PDIKHI,PU,PV,KFLSUR,KFIELD,KOUTP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFLSUR
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELD
REAL(KIND=JPRB) ,INTENT(OUT) :: PETPSI(KFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIKHI(KFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(YDGEOMETRY%YRGEM%NGPTOT,KFIELD)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(YDGEOMETRY%YRGEM%NGPTOT,KFIELD)
INTEGER(KIND=JPIM),INTENT(IN) :: KOUTP
END SUBROUTINE UVSPE
END INTERFACE
