INTERFACE
SUBROUTINE VARCALC(YDGEOMETRY,YDMODEL,YDSP,K3D,K2D,PSP3MEAN,PGP3MEAN,PGP2MEAN,PGP3VAR,PGP2VAR,PGP3M4,PGP2M4)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSP
INTEGER(KIND=JPIM) ,INTENT(IN) :: K3D
INTEGER(KIND=JPIM) ,INTENT(IN) :: K2D
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP3MEAN(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP3MEAN(:,:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2MEAN(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP3VAR(:,:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2VAR(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP3M4(:,:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2M4(:,:,:)
END SUBROUTINE VARCALC
END INTERFACE
