INTERFACE
SUBROUTINE VARFPOS(YDRQDYN,YDFPDATA,YDRQPHY,LDCFU,LDXFU,YDGEOMETRY,YDGMV,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,&
 & PWSXI,PWDXI,PCFUBUF,PXFUBUF,KCUFNR,PMCUFGP,P2DFIELDS,PGMVS,P3DFIELDS,P3DGFL,KP3LEVS,KP3FIELDS) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE YOMGFL , ONLY : TGFL
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE TYPE_MODEL , ONLY : MODEL
USE FULLPOS , ONLY : TFPDATA
USE YOM4FPOS , ONLY : TRQFPDYN
USE YOMFP4L , ONLY : TRQFP, IFPSEARCH
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(TRQFPDYN) , INTENT(IN) :: YDRQDYN
TYPE(TFPDATA) , INTENT(IN) :: YDFPDATA
TYPE(TRQFP) , INTENT(IN) :: YDRQPHY
LOGICAL , INTENT(IN) :: LDCFU
LOGICAL , INTENT(IN) :: LDXFU
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) , INTENT(IN) :: YDGMV
TYPE(TGFL) , INTENT(IN) :: YDGFL
TYPE(TSURF) , INTENT(IN) :: YDSURF
TYPE(TCFU) , INTENT(IN) :: YDCFU
TYPE(TXFU) , INTENT(IN) :: YDXFU
TYPE(MODEL) , INTENT(IN) :: YDMODEL
REAL(KIND=JPRB) , INTENT(IN) :: PWSXI
REAL(KIND=JPRB) , INTENT(IN) :: PWDXI
REAL(KIND=JPRB) , INTENT(IN), TARGET :: PCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) , INTENT(IN), TARGET :: PXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KCUFNR
REAL(KIND=JPRB) , INTENT(IN) :: PMCUFGP(YDGEOMETRY%YRDIM%NPROMA,KCUFNR,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KP3LEVS
INTEGER(KIND=JPIM), INTENT(IN) :: KP3FIELDS
REAL(KIND=JPRB) , INTENT(INOUT), OPTIONAL :: P2DFIELDS(YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPROMA,YDRQPHY%NFIELDG,YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPBLOCS)
REAL(KIND=JPRB) , ALLOCATABLE, INTENT(INOUT), OPTIONAL :: PGMVS(:,:,:)
REAL(KIND=JPRB) , INTENT(INOUT), OPTIONAL :: P3DFIELDS(YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPROMA,KP3LEVS,KP3FIELDS,YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPBLOCS)
REAL(KIND=JPRB) , ALLOCATABLE, INTENT(INOUT), OPTIONAL :: P3DGFL(:,:,:,:)
END SUBROUTINE VARFPOS
END INTERFACE
