INTERFACE
SUBROUTINE VDFDIFM(KIDIA,KFDIA,KLON,KLEV,KTOP,&
 & PTMST,PUM1,PVM1,PAPHM1,PCFM,PTODC,&
 & PSOTEU,PSOTEV,PSOC,&
 & PVOM,PVOL,PUCURR,PVCURR,&
 & PUDIF,PVDIF,PDTUTOFD,PDTVTOFD,PDTUSO,PDTVSO,PDTUVDF,PDTVVDF) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOP
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTODC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOTEU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOTEV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUCURR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCURR(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTUTOFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTVTOFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTUSO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTVSO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTUVDF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDTVVDF(KLON,KLEV)
END SUBROUTINE VDFDIFM
END INTERFACE
