INTERFACE
SUBROUTINE VDFDIFMSAD (KIDIA, KFDIA, KLON, KLEV, KTOP,&
 & PTMST ,PVDIFTS,PUM15 ,PVM15 ,PAPHM15 , PCFM5, PTOFDC5,&
 & PVOM5 ,PVOL5 ,PUDIF5 ,PVDIF5 ,&
 & PUM1 ,PVM1 ,PAPHM1 ,PCFM , PTOFDC,&
 & PVOM ,PVOL ,PUDIF ,PVDIF) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOP
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PUM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PCFM5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTOFDC5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOM5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUDIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHM1(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTOFDC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDIF(KLON,KLEV)
END SUBROUTINE VDFDIFMSAD
END INTERFACE
