INTERFACE
SUBROUTINE VDFEXCUS (YDEPHLI,YDEPHY,KIDIA , KFDIA, KLON, KLEV, PTMST,PVDIFTS,&
 & PZ0MM , PUM1 , PVM1 , PTM1 , PQM1 ,&
 & PAPHM1 , PGEOM1 , PGEOH , PCPTGZ,&
 & PKMFL , PKHFL , PKQFL , PZINV , PCFM , PCFH) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHLI , ONLY : TEPHLI
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PZ0MM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKMFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKHFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKQFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PZINV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCFH(KLON,KLEV)
END SUBROUTINE VDFEXCUS
END INTERFACE
