INTERFACE
SUBROUTINE VDFEXCU(YDEGWD,YDEPHY,KIDIA , KFDIA , KLON , KLEV , KSPPN2D, PLAM,PZ0MM ,&
 & PHRLW , PHRSW , PUM1 , PVM1 , PTM1 , PQM1 ,&
 & PAPHM1 , PGEOM1 , PGEOH , PGELAT , PCPTGZ ,&
 & PKMFL , PKHFL , PKQFL , PKHVFL , PGP2DSPP,PCFM , PCFH ,&
 & PZINV , PKH , PZCLDBASE , KPBLTYPE ) 
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOEGWD , ONLY : TEGWD
USE YOEPHY , ONLY : TEPHY
TYPE(TEGWD) ,INTENT(INOUT) :: YDEGWD
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSPPN2D
REAL(KIND=JPRB) ,INTENT(IN) :: PLAM
REAL(KIND=JPRB) ,INTENT(IN) :: PZ0MM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHRLW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PHRSW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2DSPP(KLON,KSPPN2D)
REAL(KIND=JPRB) ,INTENT(IN) :: PKMFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKHFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKQFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKHVFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PZINV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PZCLDBASE(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KPBLTYPE(KLON)
END SUBROUTINE VDFEXCU
END INTERFACE
