INTERFACE
SUBROUTINE VDFEXCUSAD (YDEPHLI,YDPHNC,YDEPHY,KIDIA, KFDIA, KLON, KLEV, PTMST,PVDIFTS,&
 & PZ0MM5 ,&
 & PUM15 ,PVM15 ,PTM15 ,PQM15 ,&
 & PAPHM15,PGEOM15,PGEOH5 ,PCPTGZ5,&
 & PKMFL5 ,PKHFL5 ,PKQFL5 ,PZINV5,&
 & PCFM5 ,PCFH5,&
 & PZ0MM ,&
 & PUM1 ,PVM1 ,PTM1 ,PQM1 ,&
 & PAPHM1 ,PGEOM1 ,PGEOH ,PCPTGZ ,PCFM ,PCFH) 
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHLI , ONLY : TEPHLI
USE YOEPHY , ONLY : TEPHY
USE YOPHNC , ONLY : TPHNC
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TPHNC) ,INTENT(INOUT) :: YDPHNC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PZ0MM5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKMFL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKHFL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKQFL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PZINV5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCFM5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCFH5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0MM(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPTGZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFH(KLON,KLEV)
END SUBROUTINE VDFEXCUSAD
END INTERFACE
