INTERFACE
SUBROUTINE VDFHGHTHL (YDVDF,YDEPHLI,YDECUMF,YDEPHY,YDPARAR,KSTEP, KIDIA , KFDIA , KLON , KLEV , KDRAFT, PTMST,&
 & PUM1, PVM1, PTM1 , PQM1 , PLM1 , PIM1 , PAM1,&
 & PAPHM1 , PAPM1 , PGEOM1 , PGEOH , PEXNF,&
 & PKHFL , PKQFL , PKUFL , PKVFL,&
 & PMFLX ,&
 & PTHLUH , PQTUH , PTHTVUH,&
 & PQCUH, PQIUH, PUUH, PVUH,&
 & YSPP_CLDDPTH,YSPP_CLDDPTHDP,&
 & YSPP_RFAC_TWOC,YSPP_RZC_H,YSPP_RZL_INF,&
 & PTENDQVUP, PTENDTUP, PSURFPREP, PSURFSNOW,&
 & PUPGENL, PUPGENN, PCLFR,&
 & ZLENGTH_M,&
 & ZLENGTH_H, PTKE) 
USE YOECUMF , ONLY : TECUMF
USE YOEPHLI , ONLY : TEPHLI
USE YOEPHY , ONLY : TEPHY
USE YOMPARAR , ONLY : TPARAR
USE YOEVDF , ONLY : TVDF
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE SPP_MOD_TYPE, ONLY : TSPP_CONFIG_TYPE
TYPE(TVDF) ,INTENT(IN) :: YDVDF
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
TYPE(TEPHLI) ,INTENT(IN) :: YDEPHLI
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(TPARAR) ,INTENT(IN) :: YDPARAR
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KDRAFT
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PEXNF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKHFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKQFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKUFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKVFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMFLX(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTHLUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQTUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTHTVUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQCUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQIUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVUH(KLON,0:KLEV,KDRAFT)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCLFR(KLON)
TYPE(TSPP_CONFIG_TYPE),INTENT(INOUT) :: YSPP_CLDDPTH,YSPP_CLDDPTHDP,&
 & YSPP_RFAC_TWOC,YSPP_RZC_H,YSPP_RZL_INF 
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDQVUP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSURFPREP(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSURFSNOW(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUPGENL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUPGENN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDTUP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: ZLENGTH_M(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: ZLENGTH_H(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTKE(KLON,KLEV)
END SUBROUTINE VDFHGHTHL
END INTERFACE
