INTERFACE
SUBROUTINE VDFHGHTN (YDEPHLI , YDEPHY , KIDIA , KFDIA , KLON , KLEV , KHPBL , PTMST,&
 & PTM1 , PQM1 , PLM1 , PIM1 , PAM1,&
 & PAPHM1 , PAPM1 , PGEOM1 , PGEOH,&
 & PKMFL , PKHFL , PKQFL , PKHVFL , PMFLX,&
 & PSLGUH , PQTUH , PZINV , PWUAVG , PZCLDBASE,&
 & PBIR , LDNODECP, LDRUNDRY, KPBLTYPE) 
USE YOEPHLI , ONLY : TEPHLI
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOEPHY , ONLY : TEPHY
TYPE(TEPHLI) ,INTENT(INOUT) :: YDEPHLI
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(OUT) :: KHPBL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PKMFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKHFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PKQFL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKHVFL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMFLX(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSLGUH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQTUH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZINV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWUAVG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZCLDBASE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PBIR(KLON)
LOGICAL ,INTENT(IN) :: LDNODECP(KLON)
LOGICAL ,INTENT(IN) :: LDRUNDRY(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KPBLTYPE(KLON)
END SUBROUTINE VDFHGHTN
END INTERFACE
