INTERFACE
SUBROUTINE VDFINCRSAD (KIDIA,KFDIA,KLON,KLEV,KTOP,PTMST,PVDIFTS,&
 & PUM15 ,PVM15 ,PTM15 ,PQM15 , PAPHM15,&
 & PGEOM15 ,PCFM5 ,PTOFDC5,PCPTGZ5,&
 & PUDIF5 ,PVDIF5,PTDIF5 ,PQDIF5 ,&
 & PVOM5 ,PVOL5 ,PTE5 ,PQE5 ,&
 & PTEWODIS5,PVDIS5,PSTRTU5,PSTRTV5,&
 & PUM1 ,PVM1 ,PTM1 ,PQM1 ,PAPHM1,&
 & PGEOM1 ,PCFM ,PTOFDC ,PCPTGZ ,&
 & PUDIF ,PVDIF ,PTDIF ,PQDIF ,&
 & PVOM ,PVOL ,PTE ,PQE ,&
 & PTEWODIS ,PVDIS ,PSTRTU ,PSTRTV) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOP
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PUM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCFM5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTOFDC5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUDIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTDIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQDIF5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTEWODIS5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIS5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRTU5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRTV5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTOFDC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCPTGZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTEWODIS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVDIS(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTV(KLON,0:KLEV)
END SUBROUTINE VDFINCRSAD
END INTERFACE
