INTERFACE
SUBROUTINE VDFINCRS (KIDIA,KFDIA,KLON,KLEV,KTOP,PTMST,PVDIFTS,&
 & PUM1 ,PVM1 ,PTM1 ,PQM1 , PAPHM1,&
 & PGEOM1 ,PCFM ,PTOFDC ,PCPTGZ ,&
 & PUDIF ,PVDIF ,PTDIF ,PQDIF ,&
 & PVOM ,PVOL ,PTE ,PQE ,&
 & PTEWODIS,PVDIS ,PSTRTU ,PSTRTV) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTOP
REAL(KIND=JPRB) ,INTENT(IN) :: PTMST
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTOFDC(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCPTGZ(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQDIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTEWODIS(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRTU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRTV(KLON,0:KLEV)
END SUBROUTINE VDFINCRS
END INTERFACE
