INTERFACE
SUBROUTINE VDFMAIN ( YDMODEL,CDCONF,&
 & KIDIA , KFDIA , KLON , KLEV , KLEVS , KSTEP , KTILES , KVTYPES, KDIAG,&
 & KTRAC , KLEVSN , KLEVI , KDHVTLS, KDHFTLS, KDHVTSS, KDHFTSS,&
 & KDHVTTS, KDHFTTS, KDHVTIS, KDHFTIS,&
 & KDHVCO2S,KDHFCO2S,KDHVVEGS,KDHFVEGS,KSPPN2D,&
 & PTSPHY , KTVL , KTVH , KCNT , PCVL , PCVH,&
 & PLAIL , PLAIH , PSNM , PRSN , PMU0 , PSIGFLT,&
 & PUM1 , PVM1 , PTM1 , PQM1 , PLM1 , PIM1 , PAM1 , PCM1 ,&
 & PAPHM1 , PAPM1 , PGEOM1 , PGEOH , PGELAT , PTSKM1M, PTSAM1M, PWSAM1M,&
 & PSSRFL , PSLRFL , PEMIS , PHRLW , PHRSW ,&
 & PTSN , PTICE ,&
 & PHLICE , PTLICE , PTLWML ,&
 & PSST , KSOTY , PFRTI , PALBTI , PWLMX ,&
 & PCHAR , PUCURR , PVCURR ,PUSTOKES,PVSTOKES,&
 & PTSKRAD, PCFLX , PDDVLC , PSOTEU , PSOTEV , PSOBETA,&
 & PTHKICE, PSNTICE, PGP2DSPP,&
 & LSICOUP,&
 & PZ0M , PZ0H ,&
 & PVDIS , PVDISG , PDISGW3D, PAHFLEV, PAHFLSB, PFWSB , PVAR,&
 & PU10M , PV10M , PT2M , PD2M , PQ2M , PZINV , PBLH ,&
 & P10NU , P10NV , PUST ,&
 & PSSRFLTI,PEVAPSNW,PEVAPMU,PEXDIAG,PGUST , PI10FGCV, KPBLTYPE,&
 & PTE , PQE , PLE , PIE , PAE , PVOM , PVOL ,&
 & PTENC , PTSKE1 ,&
 & PUSTRTI, PVSTRTI, PAHFSTI, PEVAPTI, PTSKTI ,&
 & PFLTRTI,&
 & PANDAYVT,PANFMVT,&
 & PDIFTS , PDIFTQ , PDIFTL , PDIFTI , PSTRTU , PSTRTV , PTOFDU , PTOFDV,&
 & PSTRSOU, PSTRSOV, PKH ,&
 & PAN , PAG , PRD , PRSOIL_STR,PRECO, PCO2FLUX, PCFLXO,&
 & PDHTLS , PDHTSS , PDHTTS , PDHTIS,&
 & PDHCO2S, PDHVEGS,&
 & PCGPP , PCREC ) 
USE TYPE_MODEL , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KVTYPES
INTEGER(KIND=JPIM),INTENT(IN) :: KDIAG
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVSN
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVI
INTEGER(KIND=JPIM),INTENT(IN) :: KDHVTLS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHFTLS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHVTSS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHFTSS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHVTTS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHFTTS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHVTIS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHFTIS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHVCO2S
INTEGER(KIND=JPIM),INTENT(IN) :: KDHFCO2S
INTEGER(KIND=JPIM),INTENT(IN) :: KDHVVEGS
INTEGER(KIND=JPIM),INTENT(IN) :: KDHFVEGS
INTEGER(KIND=JPIM),INTENT(IN) :: KSPPN2D
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
INTEGER(KIND=JPIM),INTENT(IN) :: KTVL(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTVH(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KSOTY(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCNT
REAL(KIND=JPRB) ,INTENT(IN) :: PCVL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCVH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAIL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAIH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNM(KLON,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSN(KLON,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU0(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGFLT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM1(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSKM1M(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSAM1M(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSAM1M(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PSSRFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLRFL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHRLW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PHRSW(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSN(KLON,KLEVSN)
REAL(KIND=JPRB) ,INTENT(IN) :: PTICE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PHLICE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLICE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLWML(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSST(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PWLMX(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCHAR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUCURR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCURR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUSTOKES(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PVSTOKES(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSKRAD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFLX(KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDDVLC(KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOTEU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOTEV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSOBETA(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTHKICE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNTICE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2DSPP(KLON,KSPPN2D)
LOGICAL ,INTENT(IN) :: LSICOUP
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDIS(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVDISG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDISGW3D(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAHFLEV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAHFLSB(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PFWSB(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVAR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PU10M(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PV10M(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: P10NU(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: P10NV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUST(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PT2M(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PD2M(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQ2M(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZINV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBLH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSSRFLTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEVAPSNW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPMU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEXDIAG(KLON,KDIAG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGUST(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PI10FGCV(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KPBLTYPE(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PIE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFSTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PANDAYVT(KLON,KVTYPES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PANFMVT(KLON,KVTYPES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTL(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTOFDU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTOFDV(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRSOU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSTRSOV(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PKH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAG(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRD(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRSOIL_STR(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRECO(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCO2FLUX(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCFLXO(KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDHTLS(KLON,KTILES,KDHVTLS+KDHFTLS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDHTSS(KLON,KLEVSN,KDHVTSS+KDHFTSS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDHTTS(KLON,KLEVS,KDHVTTS+KDHFTTS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDHTIS(KLON,KLEVI,KDHVTIS+KDHFTIS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDHVEGS(KLON,KVTYPES,KDHVVEGS+KDHFVEGS)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDHCO2S(KLON,KVTYPES,KDHVCO2S+KDHFCO2S)
REAL(KIND=JPRB) ,INTENT(IN) :: PCGPP(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCREC(KLON)
END SUBROUTINE VDFMAIN
END INTERFACE
