INTERFACE
SUBROUTINE VDFMAINSAD (YDVDF,YDMCC,YDML_PHY_SLIN,YDEPHY,YDRIP,KIDIA,KFDIA,KLON,KLEV,KLEVS,KTILES,&
 & KTRAC,PTSPHY,PVDIFTS,KTVL,KTVH,PCVL,PCVH,&
 & PLAIL, PLAIH, PSNS5, PRSN5, PSIGFLT,&
 & PUM15 ,PVM15 ,PTM15 ,PQM15 ,PCM15 ,PAPHM15 ,PGEOM15, PGEOH5,&
 & PTSKM1M5,PTSAM1M5,PWSAM1M5,&
 & PSSRFL5,PSLRFL5 ,PEMIS5 ,&
 & PTHKICE5, PSNTICE5,&
 & PTSNOW5, PTICE5,&
 & PSST , KSOTY , PFRTI ,PALBTI5 ,PWLMX5 ,&
 & PCHAR ,PTSKRAD5 ,PCFLX5,&
 & PZ0M5 ,PZ0H5 ,&
 & PU10M5 , PV10M5 , PT2M5 , PD2M5 , PQ2M5 ,&
 & P10NU5 , P10NV5 ,&
 & PSSRFLTI5,PEVAPSNW5,&
 & PTE05 ,PQE05 ,PVOM05 ,PVOL05,&
 & PTE5 ,PQE5 ,PVOM5 ,PVOL5 ,PTENC5 ,PTSKE15,&
 & PUSTRTI5,PVSTRTI5,PAHFSTI5,PEVAPTI5,PTSKTI5,&
 & PDIFTS5,PDIFTQ5,PSTRTU5,PSTRTV5,&
 & PUM1 ,PVM1 ,PTM1 ,PQM1 ,PCM1 ,PAPHM1 ,PGEOM1, PGEOH,&
 & PTSKM1M,PTSAM1M,PWSAM1M,&
 & PSSRFL,PSLRFL,&
 & PTSNOW,PTICE ,&
 & PALBTI,PTSKRAD,PCFLX,&
 & PZ0M ,PZ0H ,&
 & PU10M , PV10M , PT2M , PD2M , PQ2M ,&
 & P10NU , P10NV ,&
 & PSSRFLTI,PEVAPSNW,&
 & PTE0 ,PQE0 ,PVOM0 ,PVOL0 ,&
 & PTE ,PQE ,PVOM ,PVOL ,PTENC ,PTSKE1,&
 & PUSTRTI,PVSTRTI,PAHFSTI,PEVAPTI,PTSKTI,&
 & PDIFTS ,PDIFTQ ,PSTRTU ,PSTRTV) 
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOMMCC , ONLY : TMCC
USE YOMRIP , ONLY : TRIP
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEVDF , ONLY : TVDF
USE YOEPHY , ONLY : TEPHY
TYPE(TVDF) ,INTENT(IN) :: YDVDF
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TMCC) ,INTENT(INOUT) :: YDMCC
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE),INTENT(INOUT):: YDML_PHY_SLIN
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVS
INTEGER(KIND=JPIM),INTENT(IN) :: KTILES
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PVDIFTS
INTEGER(KIND=JPIM),INTENT(IN) :: KTVL(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTVH(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KSOTY(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCVL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCVH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAIL(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PLAIH(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGFLT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCM15(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM15(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM15(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSKM1M5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSAM1M5(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSAM1M5(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(IN) :: PSSRFL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLRFL5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMIS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTHKICE5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNTICE5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSNOW5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSNS5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PRSN5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTICE5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PSST(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PALBTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PWLMX5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCHAR(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSKRAD5(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PCFLX5(KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0M5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0H5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU10M5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10M5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P10NU5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P10NV5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT2M5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PD2M5(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ2M5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSSRFLTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEVAPSNW5(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQE5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVOM5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVOL5(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTE05(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQE05(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOM05(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOL05(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC5(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKE15(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFSTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKTI5(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTS5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDIFTQ5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTU5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTV5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCM1(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKM1M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSAM1M(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PWSAM1M(KLON,KLEVS)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSSRFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSLRFL(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSNOW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTICE(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PALBTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKRAD(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFLX(KLON,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0H(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PU10M (KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PV10M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P10NU(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: P10NV(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT2M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PD2M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQ2M(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSSRFLTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPSNW(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTE0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQE0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOM0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOL0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKE1(KLON)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVSTRTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAHFSTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PEVAPTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTSKTI(KLON,KTILES)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFTS(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIFTQ(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTU(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSTRTV(KLON,0:KLEV)
END SUBROUTINE VDFMAINSAD
END INTERFACE
