INTERFACE
SUBROUTINE VDFSTCUCRITHL (KIDIA , KFDIA , KLON , KLEV , KDRAFT ,&
 & PTM1 , PSLGM1 , PQTM1 , PAPM1 ,&
 & PSTABTHRESH, PCLDDEPTH, PBIRTHRESH, PDZCLOUD,&
 & KPTOP , KPBLTYPE , LDNODECP) 
USE PARKIND1 ,ONLY : JPIM , JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KDRAFT
INTEGER(KIND=JPIM),INTENT(IN) :: KPTOP(KLON,KDRAFT)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KPBLTYPE(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLGM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSTABTHRESH
REAL(KIND=JPRB) ,INTENT(IN) :: PCLDDEPTH
REAL(KIND=JPRB) ,INTENT(IN) :: PBIRTHRESH
REAL(KIND=JPRB) ,INTENT(IN) :: PDZCLOUD(KLON)
LOGICAL ,INTENT(IN) :: LDNODECP(KLON)
END SUBROUTINE VDFSTCUCRITHL
END INTERFACE
