INTERFACE
SUBROUTINE VDFTKE( YDCST, YDLDDH,YDMDDH,YDML_PHY_MF, YDECUMF,&
 & KIDIA , KFDIA , KLON , KLEV , PTSPHY , PZ0MM ,&
 & PTSKM1M,&
 & PUM1 , PVM1 , PTM1 , PQM1 , PLM1, PIM1, PTKE,&
 & PAPM1, PAPHM1 , PGEOM1 , PGEOH ,&
 & PCFM , PCFH ,&
 & PKH ,PKM, PTENDTKE, PEDR, PBLH) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMCST , ONLY : TCST
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOMMDDH , ONLY : TMDDH
USE YOMLDDH , ONLY : TLDDH
USE YOECUMF , ONLY : TECUMF
TYPE (TCST), INTENT (IN) :: YDCST
TYPE(TLDDH) ,INTENT(INOUT) :: YDLDDH
TYPE(TMDDH) ,INTENT(INOUT) :: YDMDDH
TYPE(TECUMF) ,INTENT(IN) :: YDECUMF
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PZ0MM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSKM1M(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PIM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PLM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHM1(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTKE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCFH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PKM(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PTENDTKE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PEDR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBLH(KLON)
END SUBROUTINE VDFTKE
END INTERFACE
