INTERFACE
SUBROUTINE VDFTOFDC(KIDIA,KFDIA,KLON,KLEV,&
 & PUM1,PVM1,PGEOM1,PSIGFLT,&
 & PTOFDC, RTOFDALPHA) 
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PUM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOM1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIGFLT(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: RTOFDALPHA
REAL(KIND=JPRB) ,INTENT(OUT) :: PTOFDC(KLON,KLEV)
END SUBROUTINE VDFTOFDC
END INTERFACE
