INTERFACE
SUBROUTINE VDIFLCZ(YDCST,YDVDF,YDVAB,YDPHLC,KIDIA, KFDIA, KLON, KLEV,&
 & PTSTEP,&
 & PLSM,&
 & PAPHI,&
 & PAPHIF, PCP, PR, PRDELP,&
 & PU0, PV0, PT0, PAPH0,&
 & PU9, PV9, PT9,&
 & PUT1,PVT1,PTT1) 
USE YOMVERT , ONLY : TVAB, VP00
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEVDF , ONLY : TVDF
USE YOMCST , ONLY : TCST
USE YOPHLC , ONLY : TPHLC
TYPE(TCST) ,INTENT(IN) :: YDCST
TYPE(TVDF) ,INTENT(IN) :: YDVDF
TYPE(TVAB) ,INTENT(IN) :: YDVAB
TYPE(TPHLC) ,INTENT(IN) :: YDPHLC
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLON
INTEGER(KIND=JPIM) ,INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) ,INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PR(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PRDELP(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT0(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH0(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PU9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT1(KLON,KLEV)
END SUBROUTINE VDIFLCZ
END INTERFACE
