INTERFACE
SUBROUTINE VDIFLCZTL(YDVDF,YDVAB,YDPHLC,KIDIA, KFDIA, KLON, KLEV,&
 & PTSTEP,&
 & PLSM,&
 & PAPHI5,&
 & PAPHI,PAPHIF,&
 & PU9, PV9, PT9,&
 & PUT1,PVT1,PTT1) 
USE YOMVERT , ONLY : TVAB, VP00
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEVDF , ONLY : TVDF
USE YOPHLC , ONLY : TPHLC
TYPE(TVDF), INTENT(IN) :: YDVDF
TYPE(TVAB), INTENT(INOUT) :: YDVAB
TYPE(TPHLC), INTENT(INOUT) :: YDPHLC
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PLSM(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI5(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT9(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUT1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVT1(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTT1(KLON,KLEV)
END SUBROUTINE VDIFLCZTL
END INTERFACE
