INTERFACE
SUBROUTINE VEC2GPFE(YDGEOMETRY,KNUMB,KSTGLO,PGP3JB,PGP2JB)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMCVA , ONLY : CVA_DATA
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KNUMB
INTEGER(KIND=JPIM),INTENT(IN) :: KSTGLO
REAL(KIND=JPRB) ,INTENT(IN) :: PGP3JB(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,CVA_DATA%NVA3D)
REAL(KIND=JPRB) ,INTENT(IN) :: PGP2JB(YDGEOMETRY%YRDIM%NPROMA,CVA_DATA%NVA2D)
END SUBROUTINE VEC2GPFE
END INTERFACE
