INTERFACE
SUBROUTINE VERTDISC_TL(PWL, PTRAY550_VERTIN, PTAER_VERTIN, PTAER_VERTIND,&
 & PHASEL_IN, PHASEL_IND, PIZ_IN, PIZ_IND, PTAER_VERT, PTAER_VERTD,&
 & PTRAY_VERT, PHASEL, PHASELD, PIZ, PIZD) 
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE RT6SVALUES, ONLY: KNBMU, KNT, KWL, IDIV, PWL550, KLEV, KLON
 REAL(KIND=JPRB), INTENT(IN) :: PWL(KWL)
 REAL(KIND=JPRB), INTENT(IN) :: PTRAY550_VERTIN(KLON, 0:KLEV),&
 & PTAER_VERTIN(KLON, 0:KLEV, KWL) 
 REAL(KIND=JPRB), INTENT(IN) :: PTAER_VERTIND(KLON, 0:KLEV, KWL)
 REAL(KIND=JPRB), INTENT(IN) :: PHASEL_IN(KLON, 0:KLEV, KWL, KNBMU),&
 & PIZ_IN(KLON, 0:KLEV, KWL) 
 REAL(KIND=JPRB), INTENT(IN) :: PHASEL_IND(KLON, 0:KLEV, KWL, KNBMU),&
 & PIZ_IND(KLON, 0:KLEV, KWL) 
 REAL(KIND=JPRB), INTENT(OUT) :: PTAER_VERT(KLON, 0:KNT, KWL),&
 & PTRAY_VERT(KLON, 0:KNT, KWL) 
 REAL(KIND=JPRB), INTENT(OUT) :: PTAER_VERTD(KLON, 0:KNT, KWL)
 REAL(KIND=JPRB), INTENT(OUT) :: PHASEL(KLON, 0:KNT, KWL, KNBMU), PIZ(&
 & KLON, 0:KNT, KWL) 
 REAL(KIND=JPRB), INTENT(OUT) :: PHASELD(KLON, 0:KNT, KWL, KNBMU),&
 & PIZD(KLON, 0:KNT, KWL) 
END SUBROUTINE VERTDISC_TL
END INTERFACE
