INTERFACE
SUBROUTINE VERT_LOC_SP(YDGEOMETRY,SPLOC, PSP3D, PSP2D, KSPSTA, KSPEND, LSQRT)
 USE PARKIND1 , ONLY : JPIM, JPRB
 USE MPL_MODULE
 USE YOMENSCOV , ONLY : TYPE_SPLOC
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
 TYPE(TYPE_SPLOC) ,INTENT(IN) :: SPLOC
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP3D(:,:,:)
 REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP2D(:,:)
 INTEGER(KIND=JPIM),INTENT(IN) :: KSPSTA
 INTEGER(KIND=JPIM),INTENT(IN) :: KSPEND
 LOGICAL, OPTIONAL ,INTENT(IN) :: LSQRT
END SUBROUTINE VERT_LOC_SP
END INTERFACE
