INTERFACE
SUBROUTINE VERTDISC (PWL, PTRAY550_VERTIN , PTAER_VERTIN , PHASEL_IN, PIZ_IN,&
 & PTAER_VERT, PTRAY_VERT, PHASEL, PIZ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE RT6SVALUES, ONLY: KNBMU, KNT, KWL, IDIV, PWL550, KLEV, KLON
REAL(KIND=JPRB),INTENT(IN) :: PWL(KWL)
REAL(KIND=JPRB),INTENT(IN) :: PTRAY550_VERTIN(KLON,0:KLEV), PTAER_VERTIN(KLON,0:KLEV,KWL)
REAL(KIND=JPRB),INTENT(IN) :: PHASEL_IN(KLON,0:KLEV,KWL,KNBMU), PIZ_IN(KLON,0:KLEV,KWL)
REAL(KIND=JPRB),INTENT(OUT) :: PTAER_VERT(KLON,0:KNT,KWL), PTRAY_VERT(KLON,0:KNT,KWL)
REAL(KIND=JPRB),INTENT(OUT) :: PHASEL(KLON,0:KNT,KWL,KNBMU), PIZ(KLON,0:KNT,KWL)
END SUBROUTINE VERTDISC
END INTERFACE
