INTERFACE
SUBROUTINE VPOS_PREP(YDGMV,YGFL,YDIN_GFL,YDGFL,YDIN_GMV)
USE YOMGMV , ONLY : TGMV
USE YOM_YGFL , ONLY : TYPE_GFLD
USE TYPE_GFLFLDS, ONLY: TYPE_IGFLFLDD,TYPE_LGFLFLDD
USE TYPE_GMVS, ONLY: TYPE_T0
TYPE(TGMV) , INTENT(IN) :: YDGMV
TYPE(TYPE_GFLD),INTENT(IN) :: YGFL
TYPE(TYPE_IGFLFLDD),INTENT(OUT) :: YDIN_GFL
TYPE(TYPE_LGFLFLDD),INTENT(OUT) :: YDGFL
TYPE(TYPE_T0) ,INTENT(OUT) :: YDIN_GMV
END SUBROUTINE VPOS_PREP
END INTERFACE
