INTERFACE
SUBROUTINE WAVXFORM(YDGEOMETRY,KSCALE,PSPA3,PSPA2,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSCALE
TYPE(TYPE_JB_STRUCT),INTENT(IN) :: YD_JB_STRUCT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPA3(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2,YD_JB_STRUCT%CONFIG%SPVARS%NS3D)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPA2(YDGEOMETRY%YRDIM%NSPEC2,YD_JB_STRUCT%CONFIG%SPVARS%NS2D)
END SUBROUTINE WAVXFORM
END INTERFACE
