INTERFACE
SUBROUTINE WRCHRES(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YD_BG,YD_TRAJEC,YDVARBC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE FIELDS_MOD, ONLY : FIELDS
USE MTRAJ_MOD, ONLY : MTRAJ
USE VARBC_CLASS, ONLY : CLASS_VARBC
USE YOMTRAJ , ONLY : TRAJ_TYPE
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(TRAJ_TYPE), INTENT(INOUT) :: YD_BG
TYPE(TRAJ_TYPE), INTENT(IN) :: YD_TRAJEC
TYPE(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
END SUBROUTINE WRCHRES
END INTERFACE
