INTERFACE
SUBROUTINE WRCOE(YDGEOMETRY,YDML_AOC,YDRIP)
USE MODEL_ATMOS_OCEAN_COUPLING_MOD , ONLY : MODEL_ATMOS_OCEAN_COUPLING_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_ATMOS_OCEAN_COUPLING_TYPE),INTENT(INOUT):: YDML_AOC
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
END SUBROUTINE WRCOE
END INTERFACE
