INTERFACE
SUBROUTINE WREVECS (KNITS,KMAXIT,PEVALS,PBNDS,PBLIM,PMINEVAL,&
 & PV,YD_PLANCV,KNGOOD,PTHETA) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE CONTROL_VECTORS_MOD, ONLY : CONTROL_VECTOR, ALLOCATE_CTLVEC, DEALLOCATE_CTLVEC,&
 & DOT_PRODUCT, ASSIGNMENT(=) 
INTEGER(KIND=JPIM),INTENT(IN) :: KNITS
INTEGER(KIND=JPIM),INTENT(IN) :: KMAXIT
REAL(KIND=JPRB) ,INTENT(IN) :: PEVALS(KNITS)
REAL(KIND=JPRB) ,INTENT(IN) :: PBNDS(KNITS)
REAL(KIND=JPRB) ,INTENT(IN) :: PBLIM
REAL(KIND=JPRB) ,INTENT(IN) :: PMINEVAL
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KMAXIT+1,KNITS)
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_PLANCV(KMAXIT+1)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNGOOD
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTHETA(KMAXIT)
END SUBROUTINE WREVECS
END INTERFACE
