INTERFACE
SUBROUTINE WRFLD_FP(YDFPS,YDGEOMETRY,PTSTEP,KTAG,KMVSET,YDFLDPTR,YDIOS_CL,YD_DISTR)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMFP_SERV, ONLY : FP_SERV, FP_SERV_DISTR
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMIO_SERV, ONLY : IO_SERV
USE IOFLDPTR_MOD, ONLY : IOFLDPTR
TYPE (FP_SERV), INTENT (INOUT) :: YDFPS
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
INTEGER (KIND=JPIM), INTENT (IN) :: KTAG
INTEGER (KIND=JPIM), INTENT (IN) :: KMVSET
TYPE (IOFLDPTR), INTENT (IN) :: YDFLDPTR (:)
TYPE (IO_SERV), INTENT (INOUT) :: YDIOS_CL (:,:)
TYPE (FP_SERV_DISTR),INTENT (IN) :: YD_DISTR
END SUBROUTINE WRFLD_FP
END INTERFACE
