INTERFACE
SUBROUTINE WRFPFILTER(YDGEOMETRY,KFPDOM,KDIMAT,KFPCMAX,KFMAX,KGLFI,LDBED,PBED,PLTF,CDMAT,LDFPFIL,PFPMAT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KDIMAT
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCMAX(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KFMAX(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KGLFI
LOGICAL, INTENT(IN) :: LDBED
REAL(KIND=JPRB), INTENT(IN) :: PBED
REAL(KIND=JPRB), INTENT(IN) :: PLTF
CHARACTER(LEN=*), INTENT(IN) :: CDMAT(KFPDOM)
LOGICAL, INTENT(IN) :: LDFPFIL(KFPDOM)
REAL(KIND=JPRB), INTENT(IN) :: PFPMAT(KDIMAT,KFPDOM)
END SUBROUTINE WRFPFILTER
END INTERFACE
