INTERFACE
SUBROUTINE WRFU(YDGEOMETRY,YDCFU,YDXFU,YDRIP,YDFACTX,CDFIC)
USE YOMCFU , ONLY : TCFU
USE YOMRIP , ONLY : TRIP
USE YOMXFU , ONLY : TXFU
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FACTX_MOD, ONLY : FACTX
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE(TCFU) ,INTENT(INOUT) :: YDCFU
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
TYPE(TXFU) ,INTENT(INOUT) :: YDXFU
TYPE (FACTX), INTENT (INOUT) :: YDFACTX
CHARACTER(LEN=*),INTENT(IN) :: CDFIC
END SUBROUTINE WRFU
END INTERFACE
