INTERFACE
SUBROUTINE WRGATHFLNM (YDVAB, KDOM, KNFL, KDIMGVAL, KNFD, KFLDOFF, PVALCO, YDCPDSC, YDFPOPH, CDFPFN,&
 & KPTR, KMASK, LDNORM, YDFACTX, YDFACTXS, CDNORMTITLE, KTAG, CDDOMNAMES,&
 & YDGEOMETRY,YDFPUSERGEO) 
USE TYPE_FAOPH, ONLY : TFAOPH
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMVERT , ONLY : TVAB
USE PARKIND1 , ONLY : JPRB, JPIM
USE IOCPTDESC_MOD , ONLY : IOCPTDESC,&
 & NIOCPTDESC_SIZE 
USE YOMMP0 , ONLY : MYPROC, NPROC
USE FACTX_MOD, ONLY : FACTX, OPENWRFACTX, WRITEFLD
TYPE(TVAB), INTENT (IN) :: YDVAB
INTEGER (KIND=JPIM) ,INTENT (IN) :: KDOM
INTEGER (KIND=JPIM) ,INTENT (IN) :: KNFL
INTEGER (KIND=JPIM) ,INTENT (IN) :: KDIMGVAL
INTEGER (KIND=JPIM) ,INTENT (IN) :: KNFD (NPROC)
INTEGER (KIND=JPIM) ,INTENT (IN) :: KFLDOFF (NPROC)
REAL (KIND=JPRB) ,INTENT (INOUT) :: PVALCO (KDIMGVAL,KNFL)
TYPE (IOCPTDESC) ,INTENT (IN) :: YDCPDSC (KNFL,KDOM)
TYPE (TFAOPH) , INTENT (IN) :: YDFPOPH(:)
CHARACTER (LEN=*), INTENT (IN) :: CDFPFN(:)
INTEGER (KIND=JPIM) ,INTENT (INOUT), OPTIONAL :: KPTR (KDOM)
INTEGER (KIND=JPIM) ,INTENT (IN), OPTIONAL :: KMASK (KNFL,KDOM)
LOGICAL ,INTENT (IN) , OPTIONAL :: LDNORM
TYPE (FACTX) ,INTENT (INOUT), OPTIONAL :: YDFACTX
TYPE (FACTX) ,INTENT (INOUT), OPTIONAL :: YDFACTXS (KDOM)
CHARACTER (LEN=*) ,INTENT (IN), OPTIONAL :: CDNORMTITLE
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KTAG
TYPE (GEOMETRY), INTENT (IN), OPTIONAL :: YDGEOMETRY
TYPE (TFPUSERGEO) ,INTENT (IN), OPTIONAL :: YDFPUSERGEO(:)
CHARACTER (LEN=*) ,INTENT (IN), OPTIONAL :: CDDOMNAMES (KDOM)
END SUBROUTINE WRGATHFLNM
END INTERFACE
