INTERFACE
SUBROUTINE WRGP2FA(YDGEOMETRY,YDRIP,KFIELDS,PBUF,YDFLDSC,YDFACTX,CDFIC,KTAG)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE IOFLDDESC_MOD , ONLY : IOFLDDESC
USE FACTX_MOD , ONLY : FACTX, COMPACTFLD
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE (TRIP), INTENT (IN) :: YDRIP
INTEGER (KIND=JPIM), INTENT (IN) :: KFIELDS
REAL (KIND=JPRB), INTENT (IN) :: PBUF (YDGEOMETRY%YRGEM%NGPTOT,KFIELDS,1)
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC (:)
TYPE (FACTX), INTENT (INOUT) :: YDFACTX
CHARACTER(LEN=*), INTENT (IN) :: CDFIC
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KTAG
END SUBROUTINE WRGP2FA
END INTERFACE
