INTERFACE
SUBROUTINE WRGP_SURF(YDGEOMETRY,PBUF,PGPG,KYPROC,KCOUNTW)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(INOUT) :: PBUF(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGPG(YDGEOMETRY%YRGEM%NGPTOTG)
INTEGER(KIND=JPIM),INTENT(OUT) :: KYPROC
INTEGER(KIND=JPIM),INTENT(IN) :: KCOUNTW
END SUBROUTINE WRGP_SURF
END INTERFACE
