INTERFACE
SUBROUTINE WRGRIDA(YDGEOMETRY,YDSURF,YDXFU,YDMODEL,YDFACTX,CDFIC)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMXFU , ONLY : TXFU
USE TYPE_MODEL , ONLY : MODEL
USE FACTX_MOD , ONLY : FACTX
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE(TSURF) , INTENT (INOUT) :: YDSURF
TYPE(TXFU) , INTENT (INOUT) :: YDXFU
TYPE(MODEL) , INTENT (INOUT) :: YDMODEL
TYPE (FACTX) , INTENT (INOUT) :: YDFACTX
CHARACTER(LEN=*),INTENT (IN) :: CDFIC
END SUBROUTINE WRGRIDA
END INTERFACE
