INTERFACE
SUBROUTINE WRGRIDALL_MAP(YDGEOMETRY,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,LDWRFU,LDWRGRIDA,LDWRGRIDUA,LDWRXFU,PIOPROC1A,PIOPROC2A)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE PARKIND1 , ONLY : JPRB, JPIM
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE (TGFL), INTENT (INOUT) :: YDGFL
TYPE (TSURF), INTENT (INOUT) :: YDSURF
TYPE (TCFU), INTENT (INOUT) :: YDCFU
TYPE (TXFU), INTENT (INOUT) :: YDXFU
TYPE (MODEL), INTENT (INOUT) :: YDMODEL
LOGICAL, INTENT (IN) :: LDWRFU
LOGICAL, INTENT (IN) :: LDWRGRIDA
LOGICAL, INTENT (IN) :: LDWRGRIDUA
LOGICAL, INTENT (IN) :: LDWRXFU
REAL (KIND=JPRB), INTENT (IN) :: PIOPROC1A
REAL (KIND=JPRB), INTENT (IN) :: PIOPROC2A
END SUBROUTINE WRGRIDALL_MAP
END INTERFACE
