INTERFACE
SUBROUTINE WRGRIDALL(YDGEOMETRY,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,YDFACTX,YDFLAG,CDFIC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL , ONLY : TGFL
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE MFIOOPTS_MOD , ONLY : MFIOFLAG
USE FACTX_MOD , ONLY : FACTX
TYPE (GEOMETRY) ,INTENT (IN) :: YDGEOMETRY
TYPE (TGFL) ,INTENT (INOUT) :: YDGFL
TYPE (TSURF) ,INTENT (INOUT) :: YDSURF
TYPE(TCFU) ,INTENT (INOUT) :: YDCFU
TYPE(TXFU) ,INTENT (INOUT) :: YDXFU
TYPE(MODEL) ,INTENT (INOUT) :: YDMODEL
TYPE (FACTX) ,INTENT (INOUT) :: YDFACTX
TYPE (MFIOFLAG) ,INTENT (IN) :: YDFLAG
CHARACTER(LEN=*),INTENT(IN) :: CDFIC
END SUBROUTINE WRGRIDALL
END INTERFACE
