INTERFACE
SUBROUTINE WRGRIDALL_FP(YDFPS,YDGEOMETRY,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,YDFLAG)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL , ONLY : TGFL
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE YOMFP_SERV , ONLY : FP_SERV
USE MFIOOPTS_MOD , ONLY : MFIOFLAG
TYPE (FP_SERV) ,INTENT (INOUT) :: YDFPS
TYPE (GEOMETRY) ,INTENT (IN) :: YDGEOMETRY
TYPE (TGFL) ,INTENT (INOUT) :: YDGFL
TYPE (TSURF) ,INTENT (INOUT) :: YDSURF
TYPE (TCFU) ,INTENT (INOUT) :: YDCFU
TYPE (TXFU) ,INTENT (INOUT) :: YDXFU
TYPE (MODEL) ,INTENT (INOUT) :: YDMODEL
TYPE (MFIOFLAG) ,INTENT (IN) :: YDFLAG
END SUBROUTINE WRGRIDALL_FP
END INTERFACE
