INTERFACE
SUBROUTINE WRGRIDUA(YDGEOMETRY,YDGFL,YDXFU,YDML_GCONF,YDFACTX,CDFIC)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMXFU , ONLY : TXFU
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE FACTX_MOD, ONLY : FACTX
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE (TGFL) , INTENT (INOUT) :: YDGFL
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TXFU) ,INTENT(INOUT) :: YDXFU
TYPE (FACTX), INTENT (INOUT) :: YDFACTX
CHARACTER(LEN=*),INTENT(IN) :: CDFIC
END SUBROUTINE WRGRIDUA
END INTERFACE
