INTERFACE
SUBROUTINE WRIFDH(YDDIMV,YDLDDH,PDAT_TOT,KLEN_TOT,KPODDH,CDNOMA,PDAT,KLEN)
USE YOMDIMV , ONLY : TDIMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMLDDH , ONLY : TLDDH
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TLDDH) ,INTENT(INOUT):: YDLDDH
INTEGER(KIND=JPIM), INTENT(IN) :: KLEN
INTEGER(KIND=JPIM), INTENT(IN) :: KLEN_TOT
INTEGER(KIND=JPIM), INTENT(IN) :: KPODDH
CHARACTER(LEN=16), INTENT(IN) :: CDNOMA
REAL(KIND=JPRB), INTENT(IN) :: PDAT(KLEN)
REAL(KIND=JPRB), INTENT(IN) :: PDAT_TOT(KLEN_TOT)
END SUBROUTINE WRIFDH
END INTERFACE
