INTERFACE
SUBROUTINE WRITETMP(YDGEOMETRY,YDRIP,KFL,YDSP)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ALLOCATE_SPEC, DEALLOCATE_SPEC
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM) ,INTENT(IN) :: KFL
TYPE(SPECTRAL_FIELD),INTENT(IN) :: YDSP
END SUBROUTINE WRITETMP
END INTERFACE
