INTERFACE
SUBROUTINE WRITEPROFILE(YDGEOMETRY,&
 & YDCPG_MISC,YDMF_PHYS,PRDG_CVGQ, PRDG_LCVQ, PRDG_MU0,YDCPG_DYN0,YDMF_PHYS_SURF,YDVARS,&
 & YDSURF,YDDPHY,YDRIP,YDML_PHY_MF,CDNAME,&
 & KLON, PLAT_MODELE, PLON_MODELE, PD, PGELAM, PGEMU,&
 & PGM, POROG, PRCORI, PRATATH, PRATATX,&
 & PPFL_FPLCH, PPFL_FPLSH) 
USE MF_PHYS_TYPE_MOD , ONLY : MF_PHYS_TYPE
USE CPG_TYPE_MOD , ONLY : CPG_DYN_TYPE, CPG_PHY_TYPE,&
 & CPG_MISC_TYPE 
USE MF_PHYS_SURFACE_TYPE_MOD,ONLY : MF_PHYS_SURF_TYPE
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRIP , ONLY : TRIP
USE YOMDPHY , ONLY : TDPHY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(CPG_MISC_TYPE),INTENT(IN) :: YDCPG_MISC
TYPE(MF_PHYS_TYPE),INTENT(IN) :: YDMF_PHYS
REAL (KIND=JPRB), INTENT(IN) :: PRDG_CVGQ (KLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT(IN) :: PRDG_LCVQ (KLON, 1:YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT(IN) :: PRDG_MU0 (KLON)
TYPE(CPG_DYN_TYPE),INTENT(IN) :: YDCPG_DYN0
TYPE(MF_PHYS_SURF_TYPE),INTENT(IN):: YDMF_PHYS_SURF
TYPE(FIELD_VARIABLES),INTENT(IN) :: YDVARS
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(TDPHY) ,INTENT(IN) :: YDDPHY
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
TYPE(TRIP) ,INTENT(IN) :: YDRIP
CHARACTER(LEN=*) ,INTENT(IN) :: CDNAME
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT_MODELE
REAL(KIND=JPRB) ,INTENT(IN) :: PLON_MODELE
REAL(KIND=JPRB) ,INTENT(IN) :: PD
REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: POROG(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRCORI(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRATATH(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PRATATX(YDGEOMETRY%YRDIM%NPROMA)
REAL (KIND=JPRB) ,INTENT(IN), OPTIONAL :: PPFL_FPLCH (YDGEOMETRY%YRDIM%NPROMA, 0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB) ,INTENT(IN), OPTIONAL :: PPFL_FPLSH (YDGEOMETRY%YRDIM%NPROMA, 0:YDGEOMETRY%YRDIMV%NFLEVG)
END SUBROUTINE WRITEPROFILE
END INTERFACE
