INTERFACE
SUBROUTINE WRITE_GRID_GRIB(YDGEOMETRY,YDRIP,CDFILE,YDGRID,KGRIB_HANDLE,KTYPE_INTERP,CDMODE,PGPSP)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE GRIDPOINT_FIELDS_MIX, ONLY : ASSIGNMENT(=), GRIDPOINT_FIELD
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) , INTENT(IN) :: YDRIP
CHARACTER(LEN=*) , INTENT(IN) :: CDFILE
TYPE(GRIDPOINT_FIELD), INTENT(IN) :: YDGRID
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KGRIB_HANDLE
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KTYPE_INTERP
CHARACTER(LEN=1) , OPTIONAL, INTENT(IN) :: CDMODE
REAL(KIND=JPRB) , OPTIONAL, INTENT(IN) :: PGPSP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
END SUBROUTINE WRITE_GRID_GRIB
END INTERFACE
