INTERFACE
SUBROUTINE WRITESD(YDGEOMETRY,YDRIP,CDFILE,CDTYPE)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
CHARACTER(LEN=*) ,INTENT(IN) :: CDFILE
CHARACTER(LEN=2) ,INTENT(IN) :: CDTYPE
END SUBROUTINE WRITESD
END INTERFACE
