INTERFACE
SUBROUTINE WRITE_CTLVEC_GRIB(YDGEOMETRY,YDRIP,CDFILE,YDCV)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE CONTROL_VECTORS_MOD
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(IN) :: YDRIP
CHARACTER(LEN=*) , INTENT(IN) :: CDFILE
TYPE(CONTROL_VECTOR), INTENT(IN) :: YDCV
END SUBROUTINE WRITE_CTLVEC_GRIB
END INTERFACE
