INTERFACE
SUBROUTINE WRITE_SPEC_GRIB(YDGEOMETRY,YDRIP,CDFILE,YDSPEC,CDMODE,KSECLOC)
USE YOMRIP , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TRIP) ,INTENT(IN) :: YDRIP
CHARACTER(LEN=*) ,INTENT(IN) :: CDFILE
TYPE(SPECTRAL_FIELD),INTENT(IN) :: YDSPEC
CHARACTER(LEN=1) , OPTIONAL, INTENT(IN) :: CDMODE
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN) :: KSECLOC(:)
END SUBROUTINE WRITE_SPEC_GRIB
END INTERFACE
