INTERFACE
SUBROUTINE WRMLFP_IO_SERV(YDRQSP,YDRQGP,YDGEOMETRY,YDSURF,YDECLDP,YDEPHY,YDRQPHY,KFPRGPL,KFPRGPG,&
 & KFPROMA,KSPEC2,KSPEC2G,CDCONF,&
 & LDLAG,LDOCE,PFPBUF,PTSTEP,PSPEC) 
USE YOECLDP , ONLY : TECLDP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEPHY , ONLY : TEPHY
USE YOMFP4L , ONLY : TRQFP
TYPE (TRQFP), INTENT(IN) :: YDRQSP
TYPE (TRQFP), INTENT(IN) :: YDRQGP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(TECLDP) ,INTENT(IN) :: YDECLDP
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
INTEGER (KIND=JPIM),INTENT(IN) :: KFPRGPL
INTEGER (KIND=JPIM),INTENT(IN) :: KFPRGPG
INTEGER (KIND=JPIM),INTENT(IN) :: KFPROMA
INTEGER (KIND=JPIM),INTENT(IN) :: KSPEC2
INTEGER (KIND=JPIM),INTENT(IN) :: KSPEC2G
CHARACTER(LEN=1),INTENT(IN) :: CDCONF
LOGICAL ,INTENT(IN) :: LDLAG
LOGICAL ,INTENT(IN) :: LDOCE
REAL(KIND=JPRB) ,INTENT(IN) :: PFPBUF(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PSPEC(:,:)
END SUBROUTINE WRMLFP_IO_SERV
END INTERFACE
