INTERFACE
SUBROUTINE WRMLFP(YDRQSP,YDRQGP,KFPRESOL,KSPEC2,KSPEC2G,KFPRGPL,KFPRGPG,&
 & KFPROMA,YDGEOMETRY,YDSURF,YDECLDP,YDEPHY,YDRQPHY,CDCONF,&
 & LDLAG,LDOCE,YDOFN,KSTEP,PFPBUF,PTSTEP,PSPEC) 
USE YOECLDP , ONLY : TECLDP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOEPHY , ONLY : TEPHY
USE YOMFP4L, ONLY : TRQFP
USE TYPE_FPOFN, ONLY : TFPOFN
TYPE (TRQFP), INTENT(IN) :: YDRQSP
TYPE (TRQFP), INTENT(IN) :: YDRQGP
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRESOL
INTEGER(KIND=JPIM),INTENT(IN) :: KSPEC2
INTEGER(KIND=JPIM),INTENT(IN) :: KSPEC2G
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRGPL
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRGPG
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TSURF) ,INTENT(IN) :: YDSURF
TYPE(TECLDP) ,INTENT(IN) :: YDECLDP
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
CHARACTER(LEN=1),INTENT(IN) :: CDCONF
LOGICAL ,INTENT(IN) :: LDLAG
LOGICAL ,INTENT(IN) :: LDOCE
TYPE (TFPOFN) ,INTENT(IN) :: YDOFN
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
REAL(KIND=JPRB) ,INTENT(IN) :: PFPBUF(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PSPEC(:,:)
END SUBROUTINE WRMLFP
END INTERFACE
