INTERFACE
SUBROUTINE WROUTSPGB(YDDIM,PSPFLD,KSHMAX,KGRIBIO,CDLEVTYPE,KRESOL,CDFNSH,PTSTEP)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(TDIM) , INTENT(IN) :: YDDIM
INTEGER(KIND=JPIM), INTENT(IN) :: KSHMAX
REAL(KIND=JPRB) , INTENT(IN) :: PSPFLD(:,:)
INTEGER(KIND=JPIM), INTENT(IN) :: KGRIBIO(4,KSHMAX)
CHARACTER(LEN=1) , INTENT(IN) :: CDLEVTYPE
INTEGER(KIND=JPIM), INTENT(IN) :: KRESOL
CHARACTER(LEN=210), INTENT(IN) :: CDFNSH
REAL(KIND=JPRB) , INTENT(IN), OPTIONAL :: PTSTEP
END SUBROUTINE WROUTSPGB
END INTERFACE
