INTERFACE
SUBROUTINE WROUTGPGB(PGGFLD,KGPTOT,KGGMAX,KGRIBIO,CDLEVTYPE,CDMODE,KRESOL,CDFN,PTSTEP)
USE PARKIND1 , ONLY : JPIM, JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KGGMAX
REAL(KIND=JPRB) , INTENT(IN) :: PGGFLD(KGPTOT,KGGMAX)
INTEGER(KIND=JPIM), INTENT(IN) :: KGRIBIO(2,KGGMAX)
CHARACTER(LEN=1) , INTENT(IN) :: CDLEVTYPE
CHARACTER(LEN=1) , INTENT(IN) :: CDMODE
INTEGER(KIND=JPIM), INTENT(IN) :: KRESOL
CHARACTER(LEN=*) , INTENT(IN) :: CDFN
REAL(KIND=JPRB) , INTENT(IN), OPTIONAL :: PTSTEP
END SUBROUTINE WROUTGPGB
END INTERFACE
