INTERFACE
SUBROUTINE WRPGR(CDFNAM,KYEAR,KMONTH,KDAY,KHOUR,KMIN,KSTEP)
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
use, intrinsic :: ieee_exceptions
CHARACTER(LEN=14) ,INTENT(IN) :: CDFNAM
INTEGER(KIND=JPIM),INTENT(IN) :: KYEAR
INTEGER(KIND=JPIM),INTENT(IN) :: KMONTH
INTEGER(KIND=JPIM),INTENT(IN) :: KDAY
INTEGER(KIND=JPIM),INTENT(IN) :: KHOUR
INTEGER(KIND=JPIM),INTENT(IN) :: KMIN
INTEGER(KIND=JPIM),INTENT(IN) :: KSTEP
END SUBROUTINE WRPGR
END INTERFACE
