INTERFACE
SUBROUTINE WRPHTRAJT(YDGEOMETRY,YDPHNC,YDEPHY,YDDPHY,KSTA,KEND,PTRAJ_PHYS_TLAD,&
 & PTENTVD5,PTENQVD5,PTENUVD5,PTENVVD5,&
 & PTENTGW5,PTENUGW5,PTENVGW5,&
 & PTENTCO5,PTENQCO5,PTENUCO5,PTENVCO5,&
 & PTENTCL5,PTENUWM5,PTENVWM5,&
 & PDIFTQ5 ,PDIFTS5 ,PEMTED5 ,PTRSOL5,&
 & PA5 ,PL5 ,PI5,&
 & PLUDE5 ,PLU5 ,&
 & PFPLCL5 ,PFPLCN5 ,PUCFL5 ,PVCFL5 ,PTCFL5 ,PQCFL5,&
 & PFRSOTI5,PAHFSTI5,PEVAPTI5,&
 & PEVAPSNW5,PFPLSL5,PFPLSN5 ,PFRTH5) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOPHNC , ONLY : TPHNC
USE YOEPHY , ONLY : TEPHY
USE YOMTRAJ , ONLY : TRAJ_PHYS_TLAD_TYPE, LPRTTRAJ
USE YOMDPHY , ONLY : TDPHY
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDPHY) ,INTENT(IN) :: YDDPHY
TYPE(TEPHY) ,INTENT(IN) :: YDEPHY
TYPE(TPHNC) ,INTENT(IN) :: YDPHNC
INTEGER(KIND=JPIM) ,INTENT(IN) :: KSTA
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEND
TYPE (TRAJ_PHYS_TLAD_TYPE),INTENT(INOUT) :: PTRAJ_PHYS_TLAD
REAL(KIND=JPRB) ,INTENT(IN) :: PTENTVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENQVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENUVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENVVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENTGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENUGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENVGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENTCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENQCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENUCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENVCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENTCL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENUWM5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENVWM5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTQ5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIFTS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PEMTED5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PTRSOL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PA5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PI5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PLUDE5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PLU5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLCN5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PUCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PTCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PQCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRSOTI5(YDGEOMETRY%YRDIM%NPROMA,YDDPHY%NTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFSTI5(YDGEOMETRY%YRDIM%NPROMA,YDDPHY%NTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVAPTI5(YDGEOMETRY%YRDIM%NPROMA,YDDPHY%NTILES)
REAL(KIND=JPRB) ,INTENT(IN) :: PEVAPSNW5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLSN5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PFRTH5(YDGEOMETRY%YRDIM%NPROMA)
END SUBROUTINE WRPHTRAJT
END INTERFACE
