INTERFACE
SUBROUTINE WRPLFP(YDRQSP,YDRQGP,KFPRESOL,KSPEC2,KSPEC2G,KFPRGPL,KFPROMA,YDGEOMETRY,YDOFN,PFPBUF,PSPEC,CDPREF,PTSTEP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB, JPRD
USE YOMFP4L , ONLY : TRQFP
USE TYPE_FPOFN, ONLY : TFPOFN
TYPE (TRQFP), INTENT(IN) :: YDRQSP
TYPE (TRQFP), INTENT(IN) :: YDRQGP
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRESOL
INTEGER(KIND=JPIM),INTENT(IN) :: KSPEC2
INTEGER(KIND=JPIM),INTENT(IN) :: KSPEC2G
INTEGER(KIND=JPIM),INTENT(IN) :: KFPRGPL
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE (TFPOFN) ,INTENT(IN) :: YDOFN
REAL(KIND=JPRB), INTENT(IN) :: PFPBUF(:,:,:)
REAL(KIND=JPRB), INTENT(IN) :: PSPEC(:,:)
CHARACTER(LEN=1),INTENT (IN) :: CDPREF
REAL(KIND=JPRB), INTENT(IN), OPTIONAL :: PTSTEP
END SUBROUTINE WRPLFP
END INTERFACE
