INTERFACE
SUBROUTINE WRRESF_TIME (YDRIP, CDTIME, CDFN, CD_CMYPROC)
USE YOMRIP , ONLY : TRIP
TYPE (TRIP), INTENT (IN) :: YDRIP
CHARACTER (LEN=*), INTENT (OUT) :: CDTIME
CHARACTER (LEN=*), INTENT (OUT) :: CDFN
CHARACTER (LEN=*), INTENT (OUT) :: CD_CMYPROC
END SUBROUTINE WRRESF_TIME
END INTERFACE
