INTERFACE
SUBROUTINE WRRESF(YDGEOMETRY,YDFIELDS,YDMODEL)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) , INTENT(INOUT) :: YDFIELDS
TYPE(MODEL) ,INTENT(INOUT), TARGET :: YDMODEL
END SUBROUTINE WRRESF
END INTERFACE
