INTERFACE
SUBROUTINE WRSCMR(KUNIT,CDNOM,PIN,KLON,KLEN)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEN
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KUNIT
REAL(KIND=JPRB) ,INTENT(IN) :: PIN(KLON,KLEN)
CHARACTER(LEN=*) ,INTENT(IN) :: CDNOM
END SUBROUTINE WRSCMR
END INTERFACE
