INTERFACE
SUBROUTINE WRSPECA_MAP(YDGEOMETRY,YDGFL,YDML_GCONF,YDDYN,YDSPEC,PIOPROC1A,PIOPROC2A,YDMCUF)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN , ONLY : TDYN
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1, ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD
USE YOMMCUF , ONLY : TMCUF
TYPE (GEOMETRY), INTENT (IN) :: YDGEOMETRY
TYPE (TGFL), INTENT (INOUT) :: YDGFL
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE (SPECTRAL_FIELD), INTENT (INOUT) :: YDSPEC
REAL (KIND=JPRB), INTENT (IN) :: PIOPROC1A
REAL (KIND=JPRB), INTENT (IN) :: PIOPROC2A
TYPE(TMCUF) , INTENT(INOUT), OPTIONAL :: YDMCUF
END SUBROUTINE WRSPECA_MAP
END INTERFACE
