INTERFACE
SUBROUTINE WRTSV(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YD_PVEIG,KEIG)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE PARKIND1 , ONLY : JPIM ,JPRB
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CONTROL_VECTOR),INTENT(INOUT) :: YD_PVEIG
INTEGER(KIND=JPIM) ,INTENT(IN) :: KEIG
END SUBROUTINE WRTSV
END INTERFACE
