INTERFACE
SUBROUTINE WVCOUPLE_UPDATE_GRIB_HANDLES(LDWINIT, KSTPW, PTSTEP, KSTEP, LDPPSTEPS, KGRIB_HANDLE_FOR_WAM)
USE PARKIND1, ONLY : JPIM, JPRB
LOGICAL, INTENT(IN) :: LDWINIT
INTEGER(KIND=JPIM), INTENT(IN) :: KSTPW
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
LOGICAL, INTENT(IN) :: LDPPSTEPS
INTEGER(KIND=JPIM), INTENT(INOUT) :: KGRIB_HANDLE_FOR_WAM
END SUBROUTINE WVCOUPLE_UPDATE_GRIB_HANDLES
END INTERFACE
