INTERFACE
SUBROUTINE WVCOUPLE_INIT_EARLY(YREWCOU, YDGEOMETRY, PTSTEP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEWCOU , ONLY : TEWCOU
TYPE(TEWCOU), INTENT(INOUT) :: YREWCOU
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB), INTENT(IN) :: PTSTEP
END SUBROUTINE WVCOUPLE_INIT_EARLY
END INTERFACE
