INTERFACE
SUBROUTINE WVWG2RG(YDGEOMETRY,YDEWCOU,PIN,K_NWVFIELDS,KLORG,KLARG,PDXNS,K_IQGAUSS,&
 & POUT,KLAGG,KBIG,KPROMA) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOEWCOU , ONLY : TEWCOU
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TEWCOU) ,INTENT(INOUT) :: YDEWCOU
INTEGER(KIND=JPIM),INTENT(IN) :: K_NWVFIELDS
INTEGER(KIND=JPIM),INTENT(IN) :: KLORG
INTEGER(KIND=JPIM),INTENT(IN) :: KLARG
INTEGER(KIND=JPIM),INTENT(IN) :: KBIG
REAL(KIND=JPRB) ,INTENT(IN) :: PIN(KLORG,KLARG,K_NWVFIELDS)
REAL(KIND=JPRB) ,INTENT(IN) :: PDXNS(KLARG)
INTEGER(KIND=JPIM),INTENT(IN) :: K_IQGAUSS
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT(KBIG,K_NWVFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KLAGG
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
END SUBROUTINE WVWG2RG
END INTERFACE
