INTERFACE
SUBROUTINE XFORMEV(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,KMXVEC,LDANERR, YD_BACKGROUND,&
 & YD_TRAJEC,YDVARBC,YDTCV5,YDTCV_BGC,YD_JB_STRUCT,YDJOT,YDGOM,YDGOM5) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE PARKIND1 , ONLY : JPIM, JPRB
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE YOMTRAJ , ONLY : TRAJ_TYPE
USE CONTROL_VECTORS_MOD
USE VARBC_CLASS,ONLY: CLASS_VARBC
USE TOVSCV_MOD,ONLY : TOVSCV,CREATE_TOVSCV
USE TOVSCV_BGC_MOD,ONLY : TOVSCV_BGC
USE SUPERGOM_CLASS, ONLY : CLASS_SUPERGOM
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ) ,INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) ,INTENT(IN) :: KMXVEC
LOGICAL ,INTENT(IN) :: LDANERR
TYPE(TRAJ_TYPE) ,INTENT(IN) :: YD_BACKGROUND
TYPE(TRAJ_TYPE) ,INTENT(IN) :: YD_TRAJEC
TYPE(CLASS_VARBC) ,INTENT(INOUT) :: YDVARBC
TYPE(TOVSCV) ,INTENT(INOUT) :: YDTCV5
TYPE(TOVSCV_BGC) ,INTENT(IN) :: YDTCV_BGC
TYPE(TYPE_JB_STRUCT) ,INTENT(INOUT) :: YD_JB_STRUCT
TYPE(JO_TABLE) ,OPTIONAL, INTENT(INOUT) :: YDJOT
TYPE(CLASS_SUPERGOM) ,OPTIONAL, INTENT(INOUT) :: YDGOM
TYPE(CLASS_SUPERGOM) ,OPTIONAL, INTENT(INOUT) :: YDGOM5
END SUBROUTINE XFORMEV
END INTERFACE
