INTERFACE
SUBROUTINE XUTRII(KS,PS,KND)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KS
REAL(KIND=JPRB) ,INTENT(IN) :: PS(KS)
INTEGER(KIND=JPIM),INTENT(OUT) :: KND(KS)
END SUBROUTINE XUTRII
END INTERFACE
