INTERFACE
SUBROUTINE Z0SEA(KPROMA,KIDIA,KFDIA,PAPHI,PUB,PVB,PSLM,PCHAR,PAZO)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PUB(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PVB(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PSLM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PCHAR(KPROMA)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PAZO(KPROMA)
END SUBROUTINE Z0SEA
END INTERFACE
