INTERFACE
SUBROUTINE ZEROACU(YDGEOMETRY,YDML_GCONF,PSPA3,PSPD2D,PSPA1,PGFLGPQ)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPA3(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2,YDML_GCONF%YRDIMF%NS3D)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPD2D(YDGEOMETRY%YRDIM%NSPEC2,YDML_GCONF%YRDIMF%NFD2D)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPA1(YDGEOMETRY%YRDIMV%NFLEVL,2)
REAL(KIND=JPRB),OPTIONAL,INTENT(OUT) :: PGFLGPQ(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
END SUBROUTINE ZEROACU
END INTERFACE
