INTERFACE
SUBROUTINE ZERODDH(YDDIMV,YDML_DIAG)
USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE YOMDIMV , ONLY : TDIMV
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(MODEL_DIAGNOSTICS_TYPE),INTENT(INOUT):: YDML_DIAG
END SUBROUTINE ZERODDH
END INTERFACE
