INTERFACE
SUBROUTINE CCHIEN(YDGEOMETRY,CDNOMA,KFILE,KINF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=*), INTENT(IN) :: CDNOMA
INTEGER(KIND=JPIM), INTENT(IN) :: KFILE
INTEGER(KIND=JPIM), INTENT(INOUT) :: KINF
END SUBROUTINE CCHIEN
END INTERFACE
