INTERFACE
SUBROUTINE CREATE_PERT(YDGEOMETRY,YDMODEL,YDMTRAJ,YDGFL,YDDYN,YDML_GCONF,YD_JB_STRUCT,YDSP)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN , ONLY : TDYN
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE YOMGFL , ONLY : TGFL
USE YOMJG ,ONLY : TYPE_JB_STRUCT
USE MTRAJ_MOD, ONLY : MTRAJ
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=),&
 & ALLOCATE_SPEC, DEALLOCATE_SPEC 
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL) , INTENT(INOUT) :: YDMODEL
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
END SUBROUTINE CREATE_PERT
END INTERFACE
