INTERFACE
SUBROUTINE DEELLO(YDGMV,YDEDYN, YDML_LBC, YDELBC_FIELDS)
USE YOMGMV , ONLY : TGMV
USE YEMDYN, ONLY : TEDYN
USE YEMLBC_MODEL, ONLY : TELBC_MODEL, DEALLOCATE_ELBC0B
USE YEMLBC_FIELDS, ONLY : TELBC_FIELDS, DEALLOCATE_ELBC0C
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
TYPE(TEDYN) ,INTENT(INOUT) :: YDEDYN
TYPE(TELBC_MODEL) ,INTENT(INOUT) :: YDML_LBC
TYPE(TELBC_FIELDS) ,INTENT(INOUT) :: YDELBC_FIELDS
END SUBROUTINE DEELLO
END INTERFACE
