INTERFACE
SUBROUTINE EAPPLY_PLL_RECF(YDGEOMETRY,PGP,PALPHAH)
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 USE PARKIND1 , ONLY : JPIM, JPRB
 USE YOM_PLL_RECF, ONLY : MPI2D,INORDER,INPASSES
 USE MPL_MODULE
 TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
 REAL(KIND=JPRB), INTENT(INOUT) :: PGP(YDGEOMETRY%YRGEM%NGPTOT)
 REAL(KIND=JPRB), INTENT(IN) :: PALPHAH(INORDER)
END SUBROUTINE EAPPLY_PLL_RECF
END INTERFACE
