INTERFACE
SUBROUTINE EBALBETA(YDGEOMETRY,YDLAP,YDLEP,PVOR,PZZP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TLEP) ,INTENT(IN) :: YDLEP
TYPE(TLAP) ,INTENT(IN) :: YDLAP
REAL(KIND=JPRB) ,INTENT(IN) :: PVOR(:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZZP(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
END SUBROUTINE EBALBETA
END INTERFACE
