INTERFACE
SUBROUTINE EBALOMEGAAD(YDGEOMETRY,YDLAP,YDLEP,PVOR,PT,PVOR7,PT7,PDIV)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PT(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(IN) :: PVOR7(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(IN) :: PT7(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PDIV(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
TYPE(TLAP) ,INTENT(IN) :: YDLAP
TYPE(TLEP) ,INTENT(IN) :: YDLEP
END SUBROUTINE EBALOMEGAAD
END INTERFACE
