INTERFACE
SUBROUTINE EBALNONLIN(YDGEOMETRY,YDLAP,YDLEP,PVOR,PZZP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMLAP , ONLY : TLEP
USE YOMLAP , ONLY : TLAP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOR(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZZP(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
TYPE(TLAP) ,INTENT(IN) :: YDLAP
TYPE(TLEP) ,INTENT(IN) :: YDLEP
END SUBROUTINE EBALNONLIN
END INTERFACE
