INTERFACE
SUBROUTINE EBALVERT(YDGEOMETRY,YD_JB_STRUCT,YDLAP,YDLEP,PSPZZP,YDSPEC,LDJBBAL,PSPDIV,PSPT,PSPSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE SPECTRAL_FIELDS_MOD , ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
TYPE(TLEP) ,INTENT(IN) :: YDLEP
TYPE(TLAP) ,INTENT(IN) :: YDLAP
REAL(KIND=JPRB) ,INTENT(IN) :: PSPZZP(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
TYPE(SPECTRAL_FIELD),OPTIONAL, INTENT(INOUT) :: YDSPEC
LOGICAL ,OPTIONAL, INTENT(IN) :: LDJBBAL
REAL(KIND=JPRB) ,OPTIONAL, INTENT(OUT) :: PSPDIV(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,OPTIONAL, INTENT(OUT) :: PSPT(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,OPTIONAL, INTENT(OUT) :: PSPSP(YDGEOMETRY%YRDIM%NSPEC2)
END SUBROUTINE EBALVERT
END INTERFACE
