INTERFACE
SUBROUTINE EBALBETAAD(YDGEOMETRY,YDLAP,YDLEP,PVOR,PZZP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TLEP) ,INTENT(IN) :: YDLEP
TYPE(TLAP) ,INTENT(IN) :: YDLAP
REAL(KIND=JPRB) ,INTENT(IN) :: PZZP(YDGEOMETRY%YRDIMV%NFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVOR(:,:)
END SUBROUTINE EBALBETAAD
END INTERFACE
