INTERFACE
SUBROUTINE EBICLI(YDGEOMETRY,YDGFL,YDEPHY,YDML_PHY_MF,KFLD,KNIV,CDPREF,CDSUFF,KNUM,PFLD,LDBIP,LDWRI,LDPAC)
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOEPHY , ONLY : TEPHY
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TYPE_GFLD) ,INTENT(INOUT):: YDGFL
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(INOUT):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KFLD
INTEGER(KIND=JPIM),INTENT(IN) :: KNIV(KFLD)
CHARACTER(LEN=*) ,INTENT(IN) :: CDPREF(KFLD)
CHARACTER(LEN=*) ,INTENT(IN) :: CDSUFF(KFLD)
INTEGER(KIND=JPIM),INTENT(IN) :: KNUM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PFLD(YDGEOMETRY%YRGEM%NGPTOTG,KFLD)
LOGICAL ,INTENT(IN) :: LDBIP(KFLD)
LOGICAL ,INTENT(IN) :: LDWRI(KFLD)
LOGICAL ,INTENT(IN) :: LDPAC(KFLD)
END SUBROUTINE EBICLI
END INTERFACE
