INTERFACE
SUBROUTINE EBIPOS(YDQTYPE,YDGEOMETRY,KFIELDS,LDBIP,PGPP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
TYPE (TYPE_FPRQDYN), INTENT(IN) :: YDQTYPE
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KFIELDS
LOGICAL, INTENT(IN) :: LDBIP(:)
REAL(KIND=JPRB),INTENT(INOUT) :: PGPP(YDGEOMETRY%YRDIM%NPROMA,KFIELDS,YDGEOMETRY%YRDIM%NGPBLKS)
END SUBROUTINE EBIPOS
END INTERFACE
