INTERFACE
SUBROUTINE EBNDGP(YDGEOMETRY, ZEBNDGP,LEBNDGP,&
 & KBZONVAR_EW,KBZONVAR_NS,&
 & ZEXPVAR,ZEVAREPSILON) 
USE PARKIND1 ,ONLY : JPRB, JPIM
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KBZONVAR_EW, KBZONVAR_NS
REAL(KIND=JPRB), INTENT(OUT) :: ZEBNDGP(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB), INTENT(IN) :: ZEXPVAR,ZEVAREPSILON
LOGICAL , INTENT(IN) :: LEBNDGP
END SUBROUTINE EBNDGP
END INTERFACE
