INTERFACE
SUBROUTINE ECHK923(YDDIM,KNUM)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(TDIM) , INTENT(INOUT) :: YDDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KNUM
END SUBROUTINE ECHK923
END INTERFACE
