INTERFACE
SUBROUTINE ECHNORM(YDGEOMETRY,YDFIELDS,YDML_GCONF,YDDYN,YD_PVIN,YD_PVOUT)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE YOMDYN , ONLY : TDYN
USE CONTROL_VECTORS_MOD
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_PVIN
TYPE(CONTROL_VECTOR),INTENT(OUT) :: YD_PVOUT
END SUBROUTINE ECHNORM
END INTERFACE
