INTERFACE
SUBROUTINE ECOMMSPNORM(YDGEOMETRY,KIOMASTER,PMEAN,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
USE MPL_MODULE
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KIOMASTER
REAL(KIND=JPRB) ,INTENT(OUT) :: PMEAN(YDGEOMETRY%YRDIMV%NFLEVG)
TYPE(SPECTRAL_FIELD), INTENT(IN) :: YDSP
END SUBROUTINE ECOMMSPNORM
END INTERFACE
