INTERFACE
SUBROUTINE ECOPTRA(YDDIMV,YDRIP,CDCONF,YDSP)
USE YOMDIMV , ONLY : TDIMV
USE YOMRIP , ONLY : TRIP
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
TYPE(TDIMV), INTENT(INOUT) :: YDDIMV
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
TYPE(SPECTRAL_FIELD), INTENT(IN) :: YDSP
END SUBROUTINE ECOPTRA
END INTERFACE
