INTERFACE
SUBROUTINE ECOUPL1(YDGEOMETRY,YDMODEL,YDFIELDS,LD_DFISTEP)
USE FIELDS_MOD, ONLY : FIELDS
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL), INTENT(INOUT) :: YDMODEL
TYPE(FIELDS), INTENT(INOUT):: YDFIELDS
LOGICAL ,INTENT(IN) :: LD_DFISTEP
END SUBROUTINE ECOUPL1
END INTERFACE
