INTERFACE
SUBROUTINE ECOUPL2(YDGEOMETRY,YDMODEL,YDFIELDS,LD_DFISTEP)
USE TYPE_MODEL, ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD, ONLY: FIELDS
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(IN) :: YDMODEL
TYPE(FIELDS) ,INTENT(INOUT) :: YDFIELDS
LOGICAL ,INTENT(IN) :: LD_DFISTEP
END SUBROUTINE ECOUPL2
END INTERFACE
