INTERFACE
SUBROUTINE ECOUPL1AD(YDGEOMETRY,YDMODEL,YDFIELDS)
USE FIELDS_MOD, ONLY: FIELDS
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL),INTENT(INOUT):: YDMODEL
TYPE(FIELDS),INTENT(INOUT)::YDFIELDS
END SUBROUTINE ECOUPL1AD
END INTERFACE
