INTERFACE
SUBROUTINE ECVARGPAD(YDGEOMETRY,YDSPEC,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG, ONLY : TYPE_JB_STRUCT
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD, ALLOCATE_SPEC, DEALLOCATE_SPEC
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSPEC
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE ECVARGPAD
END INTERFACE
