INTERFACE
SUBROUTINE EDIR_TRANS_PX(PSPVOR,PSPDIV,PSPSCALAR,PSPSC3A,PSPSC3B,PSPSC2,&
 & KPROMA,KVSETUV,KVSETSC,KRESOL,KVSETSC3A,KVSETSC3B,KVSETSC2,&
 & PGP,PGPUV,PGP3A,PGP3B,PGP2,PMEANU,PMEANV,AUX_PROC) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PSPVOR(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PSPDIV(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PSPSCALAR(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PSPSC3A(:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PSPSC3B(:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PSPSC2(:,:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KVSETUV(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KVSETSC(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KRESOL
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KVSETSC3A(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KVSETSC3B(:)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KVSETSC2(:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PGP(:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PGPUV(:,:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PGP3A(:,:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PGP3B(:,:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PGP2(:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PMEANU(:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PMEANV(:)
EXTERNAL AUX_PROC
OPTIONAL AUX_PROC
END SUBROUTINE EDIR_TRANS_PX
END INTERFACE
