INTERFACE
SUBROUTINE EDOG(YDGEOMETRY,PLON0,PLAT0,PLON1,PLAT1,PLON2,PLAT2,&
 & KDGL,KDLON,KDGUX,KDLUX,KSMAX,KMSMAX,KLEVG,LDABORT) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PLON0
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT0
REAL(KIND=JPRB) ,INTENT(IN) :: PLON1
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT1
REAL(KIND=JPRB) ,INTENT(IN) :: PLON2
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT2
INTEGER(KIND=JPIM),INTENT(IN) :: KDGL
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUX
INTEGER(KIND=JPIM),INTENT(IN) :: KSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KMSMAX
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVG
LOGICAL, OPTIONAL, INTENT(IN) :: LDABORT
END SUBROUTINE EDOG
END INTERFACE
