INTERFACE
SUBROUTINE EFILL_ISOTROPIC(YDGEOMETRY,KVALUE,KMVALUE,KFLEV,KSTART,KEND,KSPEC,P1DG,P2DL,CDSPACE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KSPEC
REAL(KIND=JPRB) ,INTENT(IN) :: P1DG(KFLEV,KSTART:KEND)
REAL(KIND=JPRB) ,INTENT(OUT) :: P2DL(KFLEV,KSPEC)
CHARACTER(LEN=2) ,INTENT(IN) :: CDSPACE
INTEGER(KIND=JPIM),INTENT(IN) :: KVALUE(YDGEOMETRY%YRDIM%NMSMAX)
INTEGER(KIND=JPIM),INTENT(IN) :: KMVALUE(YDGEOMETRY%YRDIM%NSPEC2G)
END SUBROUTINE EFILL_ISOTROPIC
END INTERFACE
