INTERFACE
SUBROUTINE EGATHEREIGMD(YDDIM,YDEMP,YD_JB_STRUCT,PFGEGVNS,PFGEDVNS,PFGEGVND,PFGEDVND,&
 & PFGEGVNQ,PFGEDVNQ,PFGEGVNU,PFGEDVNU) 
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE YEMMP , ONLY : TEMMP
USE MPL_MODULE
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TEMMP) , INTENT(IN) :: YDEMP
TYPE(TYPE_JB_STRUCT) , INTENT(INOUT) :: YD_JB_STRUCT
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEGVNS(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEDVNS(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEGVND(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEDVND(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEGVNQ(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEDVNQ(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEGVNU(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PFGEDVNU(:,:,:)
END SUBROUTINE EGATHEREIGMD
END INTERFACE
