INTERFACE
SUBROUTINE EINFLCALC(YDGEOMETRY,YDGFL,YDGFL5,YDSURF,YDMODEL,YDSP,YDCFU,YDXFU)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL , ONLY : TGFL
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(TGFL), INTENT(INOUT) :: YDGFL5
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
TYPE(TCFU), INTENT(INOUT) :: YDCFU
TYPE(TXFU), INTENT(INOUT) :: YDXFU
END SUBROUTINE EINFLCALC
END INTERFACE
