INTERFACE
SUBROUTINE EINFLATION_MEAN(YDGEOMETRY,YDGFL,YDGFL5,YDGMV,YDGMV5,YDSURF,YDSP,&
 & YDCFU, YDXFU, YDMODEL) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL , ONLY : TGFL
USE YOMGMV , ONLY : TGMV
USE YOMCFU , ONLY : TCFU
USE YOMXFU , ONLY : TXFU
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(TGFL), INTENT(INOUT) :: YDGFL5
TYPE(TGMV), INTENT(INOUT) :: YDGMV
TYPE(TGMV), INTENT(INOUT) :: YDGMV5
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
TYPE(TCFU) , INTENT(INOUT) :: YDCFU
TYPE(TXFU) , INTENT(INOUT) :: YDXFU
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
END SUBROUTINE EINFLATION_MEAN
END INTERFACE
