INTERFACE
SUBROUTINE EINTER8(YDEGEO,PZ0,KLAT0,KLON0,KNCH,PZI,KLAT,KLON,KNPT,&
 & PDELX,PDELY,KPP,KNCO,KULOUT) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMGEO , ONLY : TEGEO
TYPE(TEGEO) ,INTENT(IN) :: YDEGEO
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT0
INTEGER(KIND=JPIM),INTENT(IN) :: KLON0
INTEGER(KIND=JPIM),INTENT(IN) :: KNCH
INTEGER(KIND=JPIM),INTENT(IN) :: KNPT
REAL(KIND=JPRB) ,INTENT(INOUT) :: PZ0(KLON0,KLAT0,KNCH)
REAL(KIND=JPRB) ,INTENT(OUT) :: PZI(KNPT,KNCH)
INTEGER(KIND=JPIM),INTENT(IN) :: KLAT
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
REAL(KIND=JPRB) ,INTENT(IN) :: PDELX
REAL(KIND=JPRB) ,INTENT(IN) :: PDELY
INTEGER(KIND=JPIM),INTENT(IN) :: KPP
INTEGER(KIND=JPIM),INTENT(IN) :: KNCO
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
END SUBROUTINE EINTER8
END INTERFACE
