INTERFACE
SUBROUTINE EJBWAV_GP2WAV(YDGEOMETRY,PGP2,PGP3)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGP2(:,:,:),PGP3(:,:,:)
END SUBROUTINE EJBWAV_GP2WAV
END INTERFACE
