INTERFACE
SUBROUTINE EJGHCORI(YDGEOMETRY,LDTOUQ,PSP3D,PSP2D,KSPSTA,KSPEND,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMJG, ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
LOGICAL ,INTENT(IN) :: LDTOUQ
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP3D(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSP2D(:,:)
INTEGER(KIND=JPIM),INTENT(IN) :: KSPSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KSPEND
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
END SUBROUTINE EJGHCORI
END INTERFACE
