INTERFACE
SUBROUTINE ELARCHE(YDML_DYN,KPROMA,KSTART,KPROF,KFLEV,YDSL,YDEGSL,YDEGEO,YDGSGEOM,PSCO,PCCO)
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMGEO , ONLY : TEGEO
USE YEMGSL , ONLY : TEGSL
USE YOMGSGEOM, ONLY : TGSGEOM
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
TYPE(SL_STRUCT), INTENT(IN) :: YDSL
TYPE(TEGSL) ,INTENT(IN) :: YDEGSL
TYPE(TEGEO) ,INTENT(IN) :: YDEGEO
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
REAL(KIND=JPRB) ,INTENT(IN) :: PSCO(KPROMA,KFLEV,YDML_DYN%YYTSCO%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCCO(KPROMA,KFLEV,YDML_DYN%YYTCCO%NDIM)
END SUBROUTINE ELARCHE
END INTERFACE
