INTERFACE
SUBROUTINE ELARCHE5(YDTCCO,YDTSCO,KPROMA,KSTART,KPROF ,KFLEV ,KLEV,&
 & LDCOMPUTE_OMVAK_O,YDSL,YDEGSL,YDEGEO,YDGSGEOM,&
 & PSCO5,PCCO5,&
 & PXX5, PYY5, PRR25, PRR5, PAA5, PSINLAT5, PCOSLAT5,&
 & PSINLATS5, PCOSLATS5, PSINLATP5, PCOSLATP5,&
 & PSINLON5, PCOSLON5, PSINLONS5, PCOSLONS5, PSINLONP5, PCOSLONP5,&
 & PSS15, PCC15, PSS25, PCC25, PSS35, PCC35, PSSS5, PCCC5,&
 & PNORDX5, PNORDY5, PCOSCI5, PSINSI5,&
 & PCODLAM5, PSIDLAM5, PCOPHI5, PPP5, PQQ5) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMGEO , ONLY : TEGEO
USE YEMGSL , ONLY : TEGSL
USE INTDYNSL_MOD,ONLY : TCCO,TSCO
USE YOMGSGEOM, ONLY : TGSGEOM
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(TCCO) ,INTENT(IN) :: YDTCCO
TYPE(TSCO) ,INTENT(IN) :: YDTSCO
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KPROF
LOGICAL ,INTENT(IN) :: LDCOMPUTE_OMVAK_O
TYPE(SL_STRUCT) ,INTENT(IN) :: YDSL
TYPE(TEGSL) ,INTENT(IN) :: YDEGSL
TYPE(TEGEO) ,INTENT(IN) :: YDEGEO
TYPE(TGSGEOM) ,INTENT(IN) :: YDGSGEOM
REAL(KIND=JPRB) ,INTENT(IN) :: PSCO5(KPROMA,KFLEV,YDTSCO%NDIM)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PCCO5(KPROMA,KFLEV,YDTCCO%NDIM)
REAL(KIND=JPRB) ,INTENT(OUT) :: PXX5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PYY5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRR25(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRR5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAA5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINLAT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLAT5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINLATS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLATS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINLATP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLATP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINLON5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLON5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINLONS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLONS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINLONP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSLONP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSS15(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCC15(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSS25(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCC25(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSS35(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCC35(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSSS5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCCC5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNORDX5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNORDY5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOSCI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSINSI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCODLAM5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSIDLAM5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOPHI5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PPP5(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQQ5(KPROMA)
END SUBROUTINE ELARCHE5
END INTERFACE
