INTERFACE
SUBROUTINE ELISLAP(YDEGEO,P,KLATG,KLONG,KPDG,POCE,PGM,PSPCM,PORTEE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMGEO , ONLY : TEGEO
TYPE(TEGEO) ,INTENT(IN) :: YDEGEO
INTEGER(KIND=JPIM),INTENT(IN) :: KPDG
REAL(KIND=JPRB) ,INTENT(INOUT) :: P(KPDG)
INTEGER(KIND=JPIM),INTENT(IN) :: KLATG
INTEGER(KIND=JPIM),INTENT(IN) :: KLONG
REAL(KIND=JPRB) ,INTENT(IN) :: POCE(KPDG)
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(KPDG)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPCM
REAL(KIND=JPRB) ,INTENT(IN) :: PORTEE
END SUBROUTINE ELISLAP
END INTERFACE
