INTERFACE
SUBROUTINE ELOC_SETUP_SPHORZ(YDGEOMETRY, SPLOC)
 USE YOMENSCOV , ONLY : TYPE_SPLOC,HORZ_LOC
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
 TYPE(TYPE_SPLOC), INTENT(INOUT) :: SPLOC
END SUBROUTINE ELOC_SETUP_SPHORZ
END INTERFACE
