INTERFACE
SUBROUTINE ELSAC_RDBC (LDSKFR, YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDVARBC,KRSTEP)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE VARBC_CLASS , ONLY : CLASS_VARBC
USE PARKIND1 ,ONLY : JPIM ,JPRB
LOGICAL, INTENT (IN) :: LDSKFR
TYPE(GEOMETRY), INTENT (INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT (INOUT) :: YDFIELDS
TYPE(MTRAJ), INTENT (INOUT) :: YDMTRAJ
TYPE(MODEL), INTENT (INOUT) :: YDMODEL
TYPE(CLASS_VARBC), INTENT (INOUT) :: YDVARBC
INTEGER(KIND=JPIM), INTENT (IN) :: KRSTEP
END SUBROUTINE ELSAC_RDBC
END INTERFACE
