INTERFACE
SUBROUTINE ELSAC(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDVARBC,KINITMONTH)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE VARBC_CLASS, ONLY : CLASS_VARBC
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL), INTENT(INOUT) :: YDMODEL
TYPE(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KINITMONTH
END SUBROUTINE ELSAC
END INTERFACE
