INTERFACE
SUBROUTINE ELSWA3(YDGEOMETRY,YDMODEL,YDFIELDS,YDMTRAJ,KDD01)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL , ONLY : MODEL
USE MTRAJ_MOD , ONLY : MTRAJ
USE FIELDS_MOD, ONLY : FIELDS
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL), INTENT(INOUT) :: YDMODEL
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
INTEGER(KIND=JPIM),INTENT(IN) :: KDD01
END SUBROUTINE ELSWA3
END INTERFACE
