INTERFACE
SUBROUTINE EREADSTD(YDGEOMETRY,K3D,K2D,KGRB3,KGRB2,PGP3,PGP2,CDFILE)
USE PARKIND1 , ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
TYPE(GEOMETRY),INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: K3D
INTEGER(KIND=JPIM),INTENT(IN) :: K2D
INTEGER(KIND=JPIM),INTENT(IN) :: KGRB3(K3D)
INTEGER(KIND=JPIM),INTENT(IN) :: KGRB2(K2D)
REAL(KIND=JPRB), INTENT(INOUT) :: PGP3(:,:,:,:)
REAL(KIND=JPRB), INTENT(INOUT) :: PGP2(:,:,:)
CHARACTER(LEN=*), INTENT(IN) :: CDFILE
END SUBROUTINE EREADSTD
END INTERFACE
