INTERFACE
SUBROUTINE EREADSIGMAB(YDGEOMETRY,K3D,K2D,KGRB3,KGRB2,PGP3,PGP2,CDFILE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE GRIB_API
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: K3D
INTEGER(KIND=JPIM),INTENT(IN) :: K2D
INTEGER(KIND=JPIM),INTENT(IN) :: KGRB3(K3D)
INTEGER(KIND=JPIM),INTENT(IN) :: KGRB2(K2D)
REAL(KIND=JPRB), INTENT(OUT), ALLOCATABLE :: PGP3(:,:,:,:)
REAL(KIND=JPRB), INTENT(OUT), ALLOCATABLE :: PGP2(:,:,:)
CHARACTER(LEN=*), INTENT(IN) :: CDFILE
END SUBROUTINE EREADSIGMAB
END INTERFACE
