INTERFACE
SUBROUTINE ERLBC_POST_REQ(YDGEOMETRY,YDGFL,YDGFL5,YDML_GCONF,YDML_LBC,YDSPEC)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE YEMLBC_MODEL, ONLY : TELBC_MODEL
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(TGFL), INTENT(INOUT) :: YDGFL5
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TELBC_MODEL),INTENT(INOUT):: YDML_LBC
TYPE(SPECTRAL_FIELD), INTENT (INOUT) :: YDSPEC
END SUBROUTINE ERLBC_POST_REQ
END INTERFACE
