INTERFACE
SUBROUTINE ESETUP_PLL_RECF(YDGEOMETRY,MPI,KFLEVG)
 USE PARKIND1 , ONLY : JPIM, JPRB
 USE YOM_PLL_RECF, ONLY : TYPE_DOMAIN_DECOMPOSITION
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
 TYPE(TYPE_DOMAIN_DECOMPOSITION), INTENT(INOUT) :: MPI
 INTEGER(KIND=JPIM), INTENT(IN) :: KFLEVG
END SUBROUTINE ESETUP_PLL_RECF
END INTERFACE
