INTERFACE
SUBROUTINE ESLEXTPOL(YDGEOMETRY,YDSL,KFLDSLB,KFIXFLD,KTYP,PB1A,KMASK2)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(SL_STRUCT), INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDSLB
INTEGER(KIND=JPIM),INTENT(IN) :: KFIXFLD(2)
INTEGER(KIND=JPIM),INTENT(IN) :: KTYP
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1A(YDSL%NASLB1,KFLDSLB,1)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(OUT) :: KMASK2(YDSL%NASLB1+YDGEOMETRY%YRDIM%NSTENCILWIDE*2)
END SUBROUTINE ESLEXTPOL
END INTERFACE
