INTERFACE
SUBROUTINE ESLEXTPOLAD_OBS(YDGEOMETRY,YDSL,KFLDSLB,PB1A)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE EINT_MOD , ONLY : SL_STRUCT
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(SL_STRUCT), INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLDSLB
REAL(KIND=JPRB) ,INTENT(INOUT) :: PB1A(KFLDSLB,YDSL%NASLB1)
END SUBROUTINE ESLEXTPOLAD_OBS
END INTERFACE
