INTERFACE
SUBROUTINE ESPAREORD(YDDIM,YDEDIM,YDLEP,KFLEV,PSPFILE,PSPBUF,LD_FILE_TO_MODEL)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMDIM , ONLY : TEDIM
USE YEMLAP , ONLY : TLEP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TEDIM), INTENT(IN) :: YDEDIM
TYPE(TLEP), INTENT(IN) :: YDLEP
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPFILE(YDDIM%NSEFRE,KFLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPBUF(YDDIM%NSPEC2G,KFLEV)
LOGICAL ,INTENT(IN) :: LD_FILE_TO_MODEL
END SUBROUTINE ESPAREORD
END INTERFACE
