INTERFACE
SUBROUTINE ESPCHOR(YDGEOMETRY,YDMODEL,KSTA,KEND,KOFF,&
 & PSPVORG,PSPDIVG,PSPTG,PSPSPDG,PSPSVDG,PSPSNHXG,PSPGFL,PSPSPG,&
 & PSPTNDHD_VOR,PSPTNDHD_DIV,PSPTNDHD_T,&
 & PSPTNDHD_SPD,PSPTNDHD_SVD,PSPTNDHD_SNHX,PSPTNDHD_GFL) 
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KOFF
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPVORG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPDIVG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSPDG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSVDG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSNHXG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPGFL(:,:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSPG(:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_VOR(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_DIV(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_T(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_SPD(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_SVD(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_SNHX(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDHD_GFL(:,:,:)
END SUBROUTINE ESPCHOR
END INTERFACE
