INTERFACE
SUBROUTINE ESPCONVERT(YDGEOMETRY,LDMODEL_TO_FILE,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
LOGICAL ,INTENT(IN) :: LDMODEL_TO_FILE
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
END SUBROUTINE ESPCONVERT
END INTERFACE
