INTERFACE
SUBROUTINE ESPCM(YDGEOMETRY,YDMODEL,YDFIELDS,CDCONF,LDESPCL,LDIAU,KCPLSPEC2,KCPLSPEC2V)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL, ONLY : MODEL
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE FIELDS_MOD, ONLY: FIELDS
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(MODEL),INTENT(INOUT):: YDMODEL
TYPE(FIELDS),INTENT(INOUT):: YDFIELDS
CHARACTER(LEN=1), INTENT(IN) :: CDCONF
LOGICAL, INTENT(IN) :: LDESPCL
LOGICAL, INTENT(IN) :: LDIAU
INTEGER(KIND=JPIM), INTENT(IN) :: KCPLSPEC2
INTEGER(KIND=JPIM), INTENT(IN) :: KCPLSPEC2V
END SUBROUTINE ESPCM
END INTERFACE
