INTERFACE
SUBROUTINE ESPECRT(YDGEOMETRY,YDGFL,YGFL,KDIR,YDSP,LDINCR,YDGFL5,LDBCKGR,PSP7Q,PSP7I,PSP7L,&
 & PGP7Q,PGP7I,PGP7L,PTRAJEC) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMTRAJ , ONLY : TRAJ_TYPE, LPRTTRAJ
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGFL), INTENT(INOUT) :: YDGFL
TYPE(TYPE_GFLD),INTENT(IN):: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KDIR
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
LOGICAL, OPTIONAL ,INTENT(IN) :: LDINCR
TYPE(TGFL), OPTIONAL, INTENT(INOUT) :: YDGFL5
LOGICAL, OPTIONAL ,INTENT(IN) :: LDBCKGR
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSP7Q(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSP7I(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PSP7L(:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGP7Q(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGP7I(:,:,:)
REAL(KIND=JPRB), OPTIONAL, INTENT(IN) :: PGP7L(:,:,:)
TYPE(TRAJ_TYPE), OPTIONAL, INTENT(IN) :: PTRAJEC
END SUBROUTINE ESPECRT
END INTERFACE
