INTERFACE
SUBROUTINE ESPEUV(YDGEOMETRY,PETPSI,PDIKHI,PSPUB,PSPVB,PU,PV,KFLSUR,KFIELD,KINP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFLSUR
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELD
REAL(KIND=JPRB) ,INTENT(IN) :: PETPSI(KFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIKHI(KFLSUR,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPUB(KFIELD)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPVB(KFIELD)
REAL(KIND=JPRB) ,INTENT(OUT) :: PU(YDGEOMETRY%YRGEM%NGPTOT,KFIELD)
REAL(KIND=JPRB) ,INTENT(OUT) :: PV(YDGEOMETRY%YRGEM%NGPTOT,KFIELD)
INTEGER(KIND=JPIM),INTENT(IN) :: KINP
END SUBROUTINE ESPEUV
END INTERFACE
