INTERFACE
SUBROUTINE ESPNORMAVE(KLEVXG,PNORM,PMEAN,PAVE)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVXG
REAL(KIND=JPRB) ,INTENT(INOUT) :: PNORM(KLEVXG)
REAL(KIND=JPRB) ,INTENT(IN) :: PMEAN(KLEVXG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PAVE
END SUBROUTINE ESPNORMAVE
END INTERFACE
