INTERFACE
SUBROUTINE ESPNORMB(YDLAP,YDLEP,YDDIM,YDEDIM,PX,KLEV,PSN,PSM,PMET,KFLEV,KFLSUR,LDNWAVE)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
USE YEMDIM , ONLY : TEDIM
TYPE(TLAP) , INTENT(IN) :: YDLAP
TYPE(TLEP) , INTENT(IN) :: YDLEP
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TEDIM), INTENT(IN) :: YDEDIM
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KFLSUR
REAL(KIND=JPRB) ,INTENT(IN) :: PX(KFLSUR,YDDIM%NSPEC2)
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
REAL(KIND=JPRB) ,INTENT(OUT) :: PSM(KFLEV,YDDIM%NUMP)
REAL(KIND=JPRB) ,INTENT(IN) :: PMET(YDDIM%NSPECG)
LOGICAL ,INTENT(IN) :: LDNWAVE
REAL(KIND=JPRB) :: PSN(KFLEV,YDDIM%NUMP)
END SUBROUTINE ESPNORMB
END INTERFACE
