INTERFACE
SUBROUTINE ESPNHQESI_PRODSKAP(LDONEM,YDGEOMETRY,YDGMV,KDIMV,KDIMH,KSPEC2V,PSPDIVG,PSPPROD)
USE PARKIND1 , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
LOGICAL, INTENT(IN) :: LDONEM
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGMV), INTENT(INOUT) :: YDGMV
INTEGER(KIND=JPIM), INTENT(IN) :: KDIMV
INTEGER(KIND=JPIM), INTENT(IN) :: KDIMH
INTEGER(KIND=JPIM), INTENT(IN) :: KSPEC2V
REAL(KIND=JPRB), INTENT(IN) :: PSPDIVG(YDGEOMETRY%YRDIMV%NFLEVG,KSPEC2V)
REAL(KIND=JPRB), INTENT(OUT) :: PSPPROD(YDGEOMETRY%YRDIMV%NFLEVG,KSPEC2V)
END SUBROUTINE ESPNHQESI_PRODSKAP
END INTERFACE
