INTERFACE
SUBROUTINE ETRANSINV_MDLAD(YDGEOMETRY,YDGMV,YDML_GCONF,PSPVOR,PSPDIV,PSPSP,PSPHV,PSPGFL,&
 & PGMV,PGMVS,PGFL,LDERR,PSPMEANU,PSPMEANV) 
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
REAL(KIND=JPRB),INTENT(OUT) :: PSPVOR(:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PSPDIV(:,:)
REAL(KIND=JPRB),INTENT(INOUT) :: PSPSP(:)
REAL(KIND=JPRB),INTENT(OUT) :: PSPHV(:,:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PSPGFL(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGMV(:,:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGMVS(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PGFL(:,:,:,:)
LOGICAL ,INTENT(IN) :: LDERR
REAL(KIND=JPRB),INTENT(OUT) :: PSPMEANU(:)
REAL(KIND=JPRB),INTENT(OUT) :: PSPMEANV(:)
END SUBROUTINE ETRANSINV_MDLAD
END INTERFACE
