INTERFACE
SUBROUTINE ETRANSCUB(PFPLA,PFPLO,KDLUX,KDGUX,PTLON,PTLA,KN,PRESLA,PRESLO)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUX
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLA(KDLUX,KDGUX)
REAL(KIND=JPRB) ,INTENT(IN) :: PFPLO(KDLUX,KDGUX)
REAL(KIND=JPRB) ,INTENT(IN) :: PTLON
REAL(KIND=JPRB) ,INTENT(IN) :: PTLA
INTEGER(KIND=JPIM),INTENT(IN) :: KN
REAL(KIND=JPRB) ,INTENT(OUT) :: PRESLA(KDLUX,KDGUX)
REAL(KIND=JPRB) ,INTENT(OUT) :: PRESLO(KDLUX,KDGUX)
END SUBROUTINE ETRANSCUB
END INTERFACE
