INTERFACE
SUBROUTINE ETRANSDIRH_FROM_T0(YDGEOMETRY,YDGFL,YDGMV,CDCONF,KNFTHER,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
USE YOMGMV , ONLY : TGMV
USE PARKIND1 ,ONLY : JPRB, JPIM
USE SPECTRAL_FIELDS_MOD
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGFL) , INTENT(INOUT) :: YDGFL
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
CHARACTER(LEN=1),INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM) ,INTENT(IN) :: KNFTHER
TYPE(SPECTRAL_FIELD), INTENT(INOUT) :: YDSP
END SUBROUTINE ETRANSDIRH_FROM_T0
END INTERFACE
