INTERFACE
SUBROUTINE EVARJK(YDGEOMETRY,YDDIMF,YDSP)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDIMF , ONLY : TDIMF
USE SPECTRAL_FIELDS_DATA, ONLY: SPECTRAL_FIELD
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDIMF) ,INTENT(INOUT) :: YDDIMF
TYPE(SPECTRAL_FIELD), INTENT(IN) :: YDSP
END SUBROUTINE EVARJK
END INTERFACE
