INTERFACE
SUBROUTINE EVDUVGEO(YDGEOMETRY,PVOR,PDIV,PMU,PMV,PSPU,PSPV)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PVOR(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PDIV(:,:)
REAL(KIND=JPRB) ,INTENT(IN) :: PMU(:)
REAL(KIND=JPRB) ,INTENT(IN) :: PMV(:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPU(:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PSPV(:,:)
END SUBROUTINE EVDUVGEO
END INTERFACE
