INTERFACE
SUBROUTINE EWREINI(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,SIMUL,YD_PX,YD_PG,PDX,YDVARBC)
USE TYPE_MODEL , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE MTRAJ_MOD , ONLY : MTRAJ
USE PARKIND1 ,ONLY : JPRB
USE CONTROL_VECTORS_MOD
USE VARBC_CLASS,ONLY: CLASS_VARBC
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(FIELDS), INTENT(INOUT) :: YDFIELDS
TYPE(MTRAJ), INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_PX
TYPE(CONTROL_VECTOR),INTENT(IN) :: YD_PG
TYPE(CLASS_VARBC), INTENT(INOUT) :: YDVARBC
REAL(KIND=JPRB) ,INTENT(IN) :: PDX
EXTERNAL SIMUL
END SUBROUTINE EWREINI
END INTERFACE
