INTERFACE
SUBROUTINE EWRLSGRAD(YDGEOMETRY,YDML_GCONF,YDML_LBC,YDELBC_FIELDS)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MPL_MODULE
USE YEMLBC_MODEL,ONLY : TELBC_MODEL
USE YEMLBC_FIELDS,ONLY : TELBC_FIELDS
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE(TELBC_MODEL),INTENT(INOUT):: YDML_LBC
TYPE(TELBC_FIELDS),INTENT(INOUT):: YDELBC_FIELDS
END SUBROUTINE EWRLSGRAD
END INTERFACE
