INTERFACE
SUBROUTINE FPBOYD(PFPBSCAL,KFPXFLD,YDFPGEO_DEP,YDFPGIND,YDFPGEO,YDFPUSERGEO,PBUF_DEP,PBUF)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE YOMFPGEO, ONLY : TFPGEO
USE YOMFPGIND, ONLY : TFPGIND
REAL(KIND=JPRB) ,INTENT(IN) :: PFPBSCAL
INTEGER(KIND=JPIM), INTENT(IN) :: KFPXFLD
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO_DEP
TYPE (TFPGIND), INTENT(IN) :: YDFPGIND
TYPE (TFPGEO), INTENT(IN) :: YDFPGEO
TYPE (TFPUSERGEO) ,INTENT(IN) :: YDFPUSERGEO(:)
REAL(KIND=JPRB) ,INTENT(IN) :: PBUF_DEP(:,:,:)
REAL(KIND=JPRB) ,INTENT(OUT) :: PBUF(:,:,:)
END SUBROUTINE FPBOYD
END INTERFACE
