INTERFACE
SUBROUTINE FPFILLB(YDRQCLI,YDNAMFPSCI,YDAFN,YDML_PHY_MF,KST,KND,KFPROMA,LDFPOSHOR,LDMPHYS,PGIN,KCOD,PCLI,PWSXI,PWDXI,CDCONF,&
 & KFIELDS,POUT,KAUX,YDRQAUX,PAUX) 
USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMAFN , ONLY : TAFN
USE YOMFPC , ONLY : TNAMFPSCI
USE YOMFP4L, ONLY : TRQFP, IFPSEARCH
TYPE (TRQFP), INTENT(IN) :: YDRQCLI
TYPE (TNAMFPSCI), INTENT(IN) :: YDNAMFPSCI
TYPE (TAFN), INTENT(IN) :: YDAFN
TYPE(MODEL_PHYSICS_MF_TYPE),INTENT(IN):: YDML_PHY_MF
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KND
INTEGER(KIND=JPIM),INTENT(IN) :: KFPROMA
LOGICAL ,INTENT(IN) :: LDFPOSHOR
LOGICAL ,INTENT(IN) :: LDMPHYS
REAL(KIND=JPRB) ,INTENT(IN) :: PGIN(KFPROMA,KFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KCOD(KFIELDS)
REAL(KIND=JPRB) ,INTENT(IN) :: PCLI(KFPROMA,0:YDRQCLI%NFIELDG)
REAL(KIND=JPRB) ,INTENT(IN) :: PWSXI
REAL(KIND=JPRB) ,INTENT(IN) :: PWDXI
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
REAL(KIND=JPRB) ,INTENT(OUT) :: POUT(KFPROMA,KFIELDS)
INTEGER(KIND=JPIM),INTENT(IN) :: KAUX
TYPE (TRQFP), INTENT(IN), OPTIONAL :: YDRQAUX
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PAUX(KFPROMA,KAUX)
END SUBROUTINE FPFILLB
END INTERFACE
