INTERFACE
SUBROUTINE GP_HORIZ_FLT(YDGEOMETRY,PTRUNC,PGP)
USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
REAL(KIND=JPRB),INTENT(IN) :: PTRUNC
REAL(KIND=JPRB),INTENT(INOUT) :: PGP(:)
END SUBROUTINE GP_HORIZ_FLT
END INTERFACE
