INTERFACE
SUBROUTINE MOEVAR(YDRIP,KLSGTS)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMRIP , ONLY : TRIP
USE YEMLBC_INIT,ONLY : NFRLSG ,NLSGTS ,N1LSG
TYPE(TRIP) ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(OUT) :: KLSGTS(0:YDRIP%NSTOP/NFRLSG)
END SUBROUTINE MOEVAR
END INTERFACE
