INTERFACE
SUBROUTINE NUDGLH(KGPTOT,KPROMA,KGPBLKS,KIDIA,KFDIA,KLON,KLEV,PACPRR,PACPRS,PACPRG,&
 & PTENDT,KLHSTEP,KBL,PEXNF,LDTAUNUDGLH,LDLH,PABSM,PDT,PZI_THM,&
 & PZI_RM,PQDM,PTENDR,KRR,LNUDGLHNREAD) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KGPTOT
INTEGER(KIND=JPIM), INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM), INTENT(IN) :: KGPBLKS
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLHSTEP
INTEGER(KIND=JPIM), INTENT(IN) :: KBL
INTEGER(KIND=JPIM), INTENT(IN) :: KRR
REAL(KIND=JPRB), INTENT(IN) :: PACPRR(KIDIA:KFDIA)
REAL(KIND=JPRB), INTENT(IN) :: PACPRS(KIDIA:KFDIA)
REAL(KIND=JPRB), INTENT(IN) :: PACPRG(KIDIA:KFDIA)
REAL(KIND=JPRB), INTENT(IN) :: PEXNF(KIDIA:KFDIA,1:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PABSM(KIDIA:KFDIA,1:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PZI_THM(KIDIA:KFDIA,1:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PQDM(KIDIA:KFDIA,1:KLEV)
REAL(KIND=JPRB), INTENT(IN) :: PZI_RM(KIDIA:KFDIA,1:KLEV,KRR)
REAL(KIND=JPRB), INTENT(IN) :: PDT
LOGICAL,INTENT(IN) :: LDTAUNUDGLH
LOGICAL,INTENT(IN) :: LNUDGLHNREAD
REAL(KIND=JPRB), INTENT(INOUT) :: PTENDT(KIDIA:KFDIA,1:KLEV)
REAL(KIND=JPRB), INTENT(INOUT) :: PTENDR(KIDIA:KFDIA,1:KLEV,1:KRR)
LOGICAL, INTENT(INOUT) :: LDLH(KIDIA:KFDIA,1:KLEV)
END SUBROUTINE NUDGLH
END INTERFACE
