INTERFACE
SUBROUTINE NUDGLHCLIMPROF(KLEV,LDREADLHNCLIM)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
LOGICAL,INTENT(OUT) :: LDREADLHNCLIM
END SUBROUTINE NUDGLHCLIMPROF
END INTERFACE
