INTERFACE
SUBROUTINE NUDGLHPRECIP(KIDIA,KFDIA,KLON,PRR,PRS,PRG,KBL)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KBL
REAL(KIND=JPRB), INTENT(IN) :: PRR(KLON),PRS(KLON),PRG(KLON)
END SUBROUTINE NUDGLHPRECIP
END INTERFACE
