INTERFACE
SUBROUTINE NUDGLHPREP(KIDIA,KFDIA,KLON,KLEV,PTENDT,KBL)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KBL
REAL(KIND=JPRB), INTENT(INOUT) :: PTENDT(KLON,KLEV)
END SUBROUTINE NUDGLHPREP
END INTERFACE
