INTERFACE
SUBROUTINE NUDGLHPROFILE2(KLON,KLEV,PTENDT,KLHSTEP,KBL,PFACTOR,PRR,&
 & PRROBS,LDLFOUND,PLIMITA,PLIMITB,PCPRR,&
 & PCPRS,PCPRG,KIDIA,KFDIA) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA,KFDIA
REAL(KIND=JPRB), INTENT(IN) :: PCPRR(KIDIA:KFDIA)
REAL(KIND=JPRB), INTENT(IN) :: PCPRS(KIDIA:KFDIA)
REAL(KIND=JPRB), INTENT(IN) :: PCPRG(KIDIA:KFDIA)
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLHSTEP
INTEGER(KIND=JPIM), INTENT(IN) :: KBL
REAL(KIND=JPRB), INTENT(IN) :: PRR
REAL(KIND=JPRB), INTENT(IN) :: PRROBS
REAL(KIND=JPRB), INTENT(IN) :: PLIMITA
REAL(KIND=JPRB), INTENT(IN) :: PLIMITB
REAL(KIND=JPRB), INTENT(INOUT) :: PFACTOR
REAL(KIND=JPRB), INTENT(INOUT) :: PTENDT(KLEV)
LOGICAL,INTENT(OUT) :: LDLFOUND
END SUBROUTINE NUDGLHPROFILE2
END INTERFACE
