INTERFACE
SUBROUTINE READJBDAT96_NC(YDGEOMETRY,YD_JB_STRUCT,CDFILE,KSMAX,KMSMAX,KFLEVG,PFCOVTPS,PFCOVP,PFCOVD,PFCOVQ,KPRT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE NETCDF
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
CHARACTER(LEN=*) ,INTENT(IN) :: CDFILE
INTEGER(KIND=JPIM), INTENT(INOUT) :: KSMAX
INTEGER(KIND=JPIM), INTENT(INOUT) :: KMSMAX
INTEGER(KIND=JPIM), INTENT(INOUT) :: KFLEVG
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFCOVTPS(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFCOVP(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFCOVD(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFCOVQ(:,:,:)
INTEGER(KIND=JPIM),INTENT(IN), OPTIONAL :: KPRT
END SUBROUTINE READJBDAT96_NC
END INTERFACE
