INTERFACE
SUBROUTINE READJBBAL(YDGEOMETRY,CDFILE,KSMAX,KMSMAX,KFLEVG,PBFACT,PSDIV,PSTPS,PSHUM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
CHARACTER(LEN=*) , INTENT(IN) :: CDFILE
INTEGER(KIND=JPIM), INTENT(INOUT):: KSMAX
INTEGER(KIND=JPIM), INTENT(INOUT):: KMSMAX
INTEGER(KIND=JPIM), INTENT(INOUT):: KFLEVG
REAL(KIND=JPRB) ,ALLOCATABLE , INTENT(OUT) :: PBFACT(:)
REAL(KIND=JPRB) ,ALLOCATABLE , INTENT(OUT) :: PSDIV(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE , INTENT(OUT) :: PSTPS(:,:,:)
REAL(KIND=JPRB) ,ALLOCATABLE , INTENT(OUT) :: PSHUM(:,:,:)
END SUBROUTINE READJBBAL
END INTERFACE
