INTERFACE
SUBROUTINE SUEFPBIP(YDCLIMO,KFPCLI,YDAFN,KFIELDS,KCOD,CDCONF,LDBIP,YDRQAUX)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_FPOSBUF, ONLY : FPOSBUF
USE YOMFP4L, ONLY : TRQFP
USE YOMAFN, ONLY : TAFN
TYPE (FPOSBUF), INTENT(IN) :: YDCLIMO
INTEGER(KIND=JPIM),INTENT(IN) :: KFPCLI
TYPE (TAFN), INTENT(IN) :: YDAFN
INTEGER(KIND=JPIM),INTENT(IN) :: KFIELDS
INTEGER(KIND=JPIM),INTENT(IN) :: KCOD(KFIELDS)
CHARACTER(LEN=1) ,INTENT(IN) :: CDCONF
LOGICAL ,INTENT(OUT) :: LDBIP(KFIELDS)
TYPE(TRQFP), INTENT(IN), OPTIONAL :: YDRQAUX
END SUBROUTINE SUEFPBIP
END INTERFACE
