INTERFACE
SUBROUTINE SUEGEM_NAML(YDGEOMETRY,PGM,PGNORX,PGNORY,PGELAM,PGELAT,KSUPERSEDE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT),TARGET :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(OUT) :: PGM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGNORX(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGNORY(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGELAM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGELAT(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSUPERSEDE
END SUBROUTINE SUEGEM_NAML
END INTERFACE
