INTERFACE
SUBROUTINE SUEGEM2(YDGEOMETRY,PGM,PGNORX,PGNORY,PGELAM,PGELAT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGNORX(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGNORY(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGELAM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGELAT(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
END SUBROUTINE SUEGEM2
END INTERFACE
