INTERFACE
SUBROUTINE SUEHDF(YDGEOMETRY,YDDYN,YDEDYN,YDML_GCONF)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YEMDYN , ONLY : TEDYN
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TEDYN) ,INTENT(INOUT) :: YDEDYN
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
END SUBROUTINE SUEHDF
END INTERFACE
