INTERFACE
SUBROUTINE SUEHDVPN(YDGEOMETRY,YDDYN,PREXPDH,PSLEVDH1,PSLEVDH2,KNSHD,KNMSHD)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
REAL(KIND=JPRB),INTENT(IN) :: PREXPDH
REAL(KIND=JPRB),INTENT(IN) :: PSLEVDH1
REAL(KIND=JPRB),INTENT(IN) :: PSLEVDH2
INTEGER(KIND=JPIM),INTENT(OUT) :: KNSHD(YDGEOMETRY%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM),INTENT(OUT) :: KNMSHD(YDGEOMETRY%YRDIMV%NFLEVG)
END SUBROUTINE SUEHDVPN
END INTERFACE
