INTERFACE
SUBROUTINE SUEJBDAT96(YDGEOMETRY,CDJBTYPE,KPRT,PCOVTPS,PCOVP,PCOVD,&
 & PCOVQ,KLEV,KNUMB,YD_JB_STRUCT) 
USE PARKIND1 ,ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG , ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TYPE_JB_STRUCT), INTENT(IN) :: YD_JB_STRUCT
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KNUMB
CHARACTER(LEN=10) ,INTENT(IN) :: CDJBTYPE
INTEGER(KIND=JPIM),INTENT(IN) :: KPRT
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOVTPS(KLEV+1,KLEV+1,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOVP(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOVD(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCOVQ(KLEV,KLEV,0:KNUMB-1)
END SUBROUTINE SUEJBDAT96
END INTERFACE
