INTERFACE
SUBROUTINE SUEJBBAL(YDGEOMETRY,CDJBTYPE,YD_JB_STRUCT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMJG, ONLY : TYPE_JB_STRUCT
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
CHARACTER(LEN=10) ,INTENT(IN) :: CDJBTYPE
TYPE(TYPE_JB_STRUCT), INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUEJBBAL
END INTERFACE
