INTERFACE
SUBROUTINE SUEJBSTD(YDGEOMETRY,YDFIELDS,YD_TRAJ,CDJBTYPE,PCOVTPS,PCOVP,PCOVD,PCOVQ,&
 & KLEV,KNUMB,YD_JB_STRUCT) 
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD , ONLY : FIELDS
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMJG , ONLY : TYPE_JB_STRUCT
USE MPL_MODULE
TYPE(GEOMETRY) , INTENT(IN) :: YDGEOMETRY
TYPE(FIELDS) , INTENT(INOUT) :: YDFIELDS
TYPE(FIELDS) , INTENT(INOUT) :: YD_TRAJ
INTEGER(KIND=JPIM) , INTENT(IN) :: KLEV
INTEGER(KIND=JPIM) , INTENT(IN) :: KNUMB
CHARACTER(LEN=10) , INTENT(IN) :: CDJBTYPE
REAL(KIND=JPRB) , INTENT(IN) :: PCOVTPS(KLEV+1,KLEV+1,0:KNUMB-1)
REAL(KIND=JPRB) , INTENT(IN) :: PCOVP(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) , INTENT(IN) :: PCOVD(KLEV,KLEV,0:KNUMB-1)
REAL(KIND=JPRB) , INTENT(IN) :: PCOVQ(KLEV,KLEV,0:KNUMB-1)
TYPE(TYPE_JB_STRUCT) , INTENT(INOUT) :: YD_JB_STRUCT
END SUBROUTINE SUEJBSTD
END INTERFACE
