INTERFACE
SUBROUTINE SUELAP(YDDIM,YDEDIM,YDLAP,YDLEP,YDEGEO)
USE YOMDIM , ONLY : TDIM
USE YEMGEO , ONLY : TEGEO
USE YOMLAP , ONLY : TLAP
USE YEMLAP , ONLY : TLEP
USE YEMDIM , ONLY : TEDIM
TYPE(TDIM) , INTENT(INOUT) :: YDDIM
TYPE(TEDIM), INTENT(INOUT) :: YDEDIM
TYPE(TLAP), INTENT(INOUT) :: YDLAP
TYPE(TLEP), INTENT(INOUT) :: YDLEP
TYPE(TEGEO), INTENT(INOUT) :: YDEGEO
END SUBROUTINE SUELAP
END INTERFACE
