INTERFACE
SUBROUTINE SUELDYNB(YDGEOMETRY,YDDYN,YDEDYN,YGFL)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YEMDYN , ONLY : TEDYN
USE YOMDYN , ONLY : TDYN
USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
TYPE(TEDYN) ,INTENT(INOUT) :: YDEDYN
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
END SUBROUTINE SUELDYNB
END INTERFACE
