INTERFACE
SUBROUTINE SUEMPVAR(YDEMP,YDDIM)
USE YOMDIM , ONLY : TDIM
USE YEMMP , ONLY : TEMMP
TYPE(TEMMP) , INTENT(INOUT) :: YDEMP
TYPE(TDIM) , INTENT(INOUT) :: YDDIM
END SUBROUTINE SUEMPVAR
END INTERFACE
