INTERFACE
SUBROUTINE SUEMETRIC(YDDIM,YDEDIM,YDLEP,KSMAX,PMET,PMETDER,PMETKE)
USE YOMDIM , ONLY : TDIM
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YEMLAP , ONLY : TLEP
USE YEMDIM , ONLY : TEDIM
TYPE(TDIM) , INTENT(IN) :: YDDIM
TYPE(TEDIM), INTENT(IN) :: YDEDIM
TYPE(TLEP), INTENT(IN) :: YDLEP
INTEGER(KIND=JPIM),INTENT(OUT) :: KSMAX
REAL(KIND=JPRB) ,INTENT(OUT) :: PMET(YDDIM%NSPECG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMETDER(YDDIM%NSPECG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PMETKE(YDDIM%NSPECG)
END SUBROUTINE SUEMETRIC
END INTERFACE
