INTERFACE
SUBROUTINE SUENHHEG(YDGEOMETRY,YDDYN,YDEDYN)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
USE YEMDYN , ONLY : TEDYN
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT):: YDDYN
TYPE(TEDYN) ,INTENT(INOUT):: YDEDYN
END SUBROUTINE SUENHHEG
END INTERFACE
