INTERFACE
SUBROUTINE SUEOROG(YDGEOMETRY,PSPOR,POROG,POROGL,POROGM,POROGLL,POROGLM,POROGMM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
TYPE(GEOMETRY) ,INTENT(INOUT) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PSPOR(YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROG (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGL (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGM (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGLL(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGMM(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRB) ,INTENT(OUT) :: POROGLM(YDGEOMETRY%YRGEM%NGPTOT)
END SUBROUTINE SUEOROG
END INTERFACE
