INTERFACE
SUBROUTINE SUGPLOC(YDGEOMETRY,KNMEMBERS)
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE GEOMETRY_MOD , ONLY : GEOMETRY
 TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
 INTEGER(KIND=JPIM), INTENT(IN) :: KNMEMBERS
END SUBROUTINE SUGPLOC
END INTERFACE
