INTERFACE
 SUBROUTINE ARO_GROUND_DIAG( KBL, KGPCOMP, KLON, KST, KEND,&
 & KLEV, KORDER, KDGUNG, KDGUXG,KDLUNG, KDLUXG,OSURFEX_KFROM,&
 & PZS, PFEV, PUM, PVM, PHEIGHT, PLWNET, PSWNET,PINDX, PINDY,&
 & PQS, PGZ0, PGZ0H, PT2M, PQ2M, PRH2M, PU10M, PV10M, PU10N, PV10N, &
 & PFCLL, PFCLN,PFEVL, PFEVN, PSSO_STDEV, PTWSNOW , PBUDLW, PBUDSW, &
 & PLE, PTOWN, PCD, PSIC) 
 USE PARKIND1, ONLY : JPRB, JPIM
INTEGER(KIND=JPIM), INTENT(IN) :: KBL
INTEGER(KIND=JPIM), INTENT(IN) :: KGPCOMP
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KST
INTEGER(KIND=JPIM), INTENT(IN) :: KEND
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM), INTENT(IN) :: KORDER
INTEGER(KIND=JPIM), INTENT(IN) :: KDGUNG, KDGUXG,KDLUNG, KDLUXG
LOGICAL, INTENT(IN) :: OSURFEX_KFROM
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PZS
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PFEV
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PUM
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PVM
REAL(KIND=JPRB), DIMENSION(KLON,KLEV), INTENT(IN) :: PHEIGHT
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PLWNET
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PSWNET
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PINDX
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(IN) :: PINDY
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PQS
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PGZ0
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PGZ0H
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PT2M
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PQ2M
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PRH2M
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PU10M
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PV10M
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PU10N
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PV10N
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PFCLL
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PFCLN
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PFEVL
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PFEVN
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PSSO_STDEV
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PTWSNOW
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PSIC
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PBUDLW
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PBUDSW
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PLE
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PTOWN
REAL(KIND=JPRB), DIMENSION(KLON), INTENT(OUT) :: PCD
END SUBROUTINE ARO_GROUND_DIAG
END INTERFACE
