INTERFACE
SUBROUTINE ARO_SURF_RESTART(YDGEOMETRY,YDMODEL,KULOUT, CDCONFSFX, KPROMA)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE TYPE_MODEL       , ONLY : MODEL
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE (MODEL),   INTENT (INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
CHARACTER(LEN=*), INTENT(IN) :: CDCONFSFX
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
END SUBROUTINE ARO_SURF_RESTART
END INTERFACE
