INTERFACE
 SUBROUTINE ARO_PUT_ZS(HPROGRAM,KI,PZS)
 USE PARKIND1, ONLY : JPRB, JPIM
CHARACTER(LEN=6), INTENT(IN) :: HPROGRAM
INTEGER(KIND=JPIM), INTENT(IN) :: KI
REAL(KIND=JPRB), DIMENSION(KI), INTENT(IN) :: PZS
END SUBROUTINE ARO_PUT_ZS
END INTERFACE
