INTERFACE
SUBROUTINE ARO_SURF_DIAG (LDMPA, LDPGDFWR, LDHISFWR, KSTOP, KSTEP, &
                        & KFREQFS, KYPROC, KLON, PINRAIN, PINSNOW, &
                        & CDFILE)
USE PARKIND1, ONLY : JPRB, JPIM
IMPLICIT NONE
LOGICAL,             INTENT(IN), OPTIONAL :: LDMPA                 ! value of LMPA
LOGICAL,             INTENT(IN), OPTIONAL :: LDPGDFWR              ! LPGDFWR from yommse; write PGD fields
LOGICAL,             INTENT(IN), OPTIONAL :: LDHISFWR              ! LHISFWR from yommse; write historic & diagnostic data
INTEGER(KIND=JPIM),  INTENT(IN), OPTIONAL :: KSTOP
INTEGER(KIND=JPIM),  INTENT(IN), OPTIONAL :: KSTEP
INTEGER(KIND=JPIM),  INTENT(IN), OPTIONAL :: KFREQFS
INTEGER(KIND=JPIM),  INTENT(IN), OPTIONAL :: KYPROC
INTEGER(KIND=JPIM),  INTENT(IN), OPTIONAL :: KLON
REAL(KIND=JPRB),     INTENT(IN), OPTIONAL :: PINRAIN (:) ! (KLON)  ! liquid precipitation (kg/m2/s)
REAL(KIND=JPRB),     INTENT(IN), OPTIONAL :: PINSNOW (:) ! (KLON)  ! solid precipitation (kg/m2/s)
CHARACTER (LEN=*),   INTENT(IN), OPTIONAL :: CDFILE
END SUBROUTINE
END INTERFACE
