INTERFACE
SUBROUTINE AROINI_SURFB(KYEAR, KMONTH, KDAY, KSSSSS)
USE PARKIND1, ONLY : JPRB, JPIM
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KYEAR
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KMONTH
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KDAY
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSSSSS
END SUBROUTINE AROINI_SURFB
END INTERFACE
