INTERFACE
 SUBROUTINE ATM2SX_FIELD(PFIELD,HNAME)
 USE PARKIND1, ONLY : JPRB
CHARACTER(LEN=*), INTENT(IN) :: HNAME
REAL(KIND=JPRB), DIMENSION(:), INTENT(IN) :: PFIELD
END SUBROUTINE ATM2SX_FIELD
END INTERFACE
