INTERFACE
SUBROUTINE CANARI_SFX(YDGEOMETRY,YDMODEL,YDGFL,YDSURF,YDSPEC,YDCFU,YDXFU,PUNDEF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL   , ONLY : TGFL
USE PARKIND1,  ONLY : JPIM, JPRB
USE TYPE_MODEL   , ONLY : MODEL
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD
USE YOMCFU   , ONLY : TCFU
USE YOMXFU   , ONLY : TXFU
IMPLICIT NONE
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL), INTENT(INOUT)  :: YDMODEL
TYPE(TGFL) , INTENT(INOUT) :: YDGFL
TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
TYPE(TCFU), INTENT(INOUT) :: YDCFU
TYPE(TXFU), INTENT(INOUT) :: YDXFU
REAL(KIND=JPRB), INTENT(IN) :: PUNDEF
END SUBROUTINE CANARI_SFX
END INTERFACE
