INTERFACE
SUBROUTINE DISGRID_SURF_EXT2(KTAG,PFIELD,KGPTOT,PREAL)
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE MODD_IO_SURF_ARO    , ONLY : NPRCIDS  ,MYPROC   ,NSTA     ,NONL     ,&
                    & NPTRFRSTLAT,NFRSTLAT ,NLSTLAT ,NGPSET2PE,NLOENG   ,&
                    & NGPTOT   ,NGPTOTMX, N_REGIONS ,N_REGIONS_NS

USE MPL_SEND_MOD, ONLY : MPL_SEND
USE MPL_RECV_MOD, ONLY : MPL_RECV

IMPLICIT NONE

INTEGER,INTENT(IN)    :: KTAG
REAL   ,INTENT(OUT)   :: PFIELD(NGPTOT)
INTEGER,INTENT(IN), OPTIONAL :: KGPTOT
REAL   ,INTENT(IN), OPTIONAL :: PREAL(:)
END SUBROUTINE DISGRID_SURF_EXT2
END INTERFACE
