INTERFACE
 SUBROUTINE GET_BUFN0(HNAME,KFIELD,KRET)
 USE PARKIND1, ONLY : JPIM, JPRB
CHARACTER(LEN=6), INTENT(IN) :: HNAME
INTEGER(KIND=JPIM), INTENT(OUT) :: KFIELD
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
END SUBROUTINE GET_BUFN0
END INTERFACE
