INTERFACE
 SUBROUTINE GET_BUFX1(HNAME,KDIM,PFIELD,KRET)
 USE PARKIND1, ONLY : JPRB, JPIM
CHARACTER(LEN=*), INTENT(IN) :: HNAME
INTEGER(KIND=JPIM), INTENT(IN) :: KDIM
REAL(KIND=JPRB), DIMENSION(KDIM), INTENT(OUT) :: PFIELD
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
END SUBROUTINE GET_BUFX1
END INTERFACE
