INTERFACE
SUBROUTINE HPOSSFX(KPROMA,KNUMB, KSTGLO, KPREP, PFPBUF1)
USE PARKIND1, ONLY : JPRB, JPIM
INTEGER (KIND=JPIM), INTENT (IN)    :: KPROMA
INTEGER (KIND=JPIM), INTENT (IN)    :: KNUMB
INTEGER (KIND=JPIM), INTENT (IN)    :: KSTGLO
INTEGER (KIND=JPIM), INTENT (IN)    :: KPREP
REAL (KIND=JPRB),    INTENT (INOUT) :: PFPBUF1(KPROMA)
END SUBROUTINE HPOSSFX
END INTERFACE
