
INTERFACE

SUBROUTINE LFI2XXYY (PFIELD, PWORK1D, HREC, NIB, NIE, NIU, NJB, NJE, NJU, NMASDEV)

USE YOMHOOK, ONLY : DR_HOOK, LHOOK
USE PARKIND1, ONLY : JPRB

IMPLICIT NONE

REAL,              INTENT (OUT) :: PFIELD (NIU-NIB,NJU-NJB)
REAL,              INTENT (IN)  :: PWORK1D (:)
CHARACTER*(*),     INTENT (IN)  :: HREC
INTEGER,           INTENT (IN)  :: NIB
INTEGER,           INTENT (IN)  :: NIE
INTEGER,           INTENT (IN)  :: NIU
INTEGER,           INTENT (IN)  :: NJB
INTEGER,           INTENT (IN)  :: NJE
INTEGER,           INTENT (IN)  :: NJU
INTEGER,           INTENT (IN)  :: NMASDEV

END SUBROUTINE LFI2XXYY

END INTERFACE
