INTERFACE
SUBROUTINE PREP_SURF_ARO (YDCTL, LDPGDFWR, LDHISFWR, CDHOST, LDDOPREP, CDTYPE)
USE MODD_PREP_CTL
TYPE (PREP_CTL),   INTENT (INOUT)        :: YDCTL
LOGICAL,           INTENT (IN)           :: LDPGDFWR
LOGICAL,           INTENT (IN)           :: LDHISFWR
CHARACTER (LEN=*), INTENT (IN), OPTIONAL :: CDHOST
LOGICAL,           INTENT (IN), OPTIONAL :: LDDOPREP
CHARACTER (LEN=*), INTENT (IN), OPTIONAL :: CDTYPE
END SUBROUTINE PREP_SURF_ARO
END INTERFACE
