INTERFACE
 SUBROUTINE PUT_BUFX0(HNAME,PFIELD,KRET)
 USE PARKIND1, ONLY : JPIM, JPRB
CHARACTER(LEN=6), INTENT(IN) :: HNAME
REAL(KIND=JPRB), INTENT(IN) :: PFIELD
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
END SUBROUTINE PUT_BUFX0
END INTERFACE
