INTERFACE
 SUBROUTINE PUT_BUFN0(HNAME,KFIELD,KRET)
 USE PARKIND1, ONLY : JPIM, JPRB
CHARACTER(LEN=6), INTENT(IN) :: HNAME
INTEGER(KIND=JPIM), INTENT(IN) :: KFIELD
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
END SUBROUTINE PUT_BUFN0
END INTERFACE
