INTERFACE
 SUBROUTINE PUT_BUFX1(HNAME,KDIM,PFIELD,KRET)
 USE PARKIND1, ONLY : JPIM, JPRB
CHARACTER(LEN=*), INTENT(IN) :: HNAME
INTEGER(KIND=JPIM), INTENT(IN) :: KDIM
REAL(KIND=JPRB), DIMENSION(KDIM), INTENT(IN) :: PFIELD
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
END SUBROUTINE PUT_BUFX1
END INTERFACE
