INTERFACE
 SUBROUTINE PUT_BUFC0(HNAME,CFIELD,KLEN,KRET)
 USE PARKIND1, ONLY : JPIM, JPRB
CHARACTER(LEN=6), INTENT(IN) :: HNAME
CHARACTER(LEN=KLEN), INTENT(IN) :: CFIELD
INTEGER(KIND=JPIM), INTENT(IN) :: KLEN
INTEGER(KIND=JPIM), INTENT(OUT) :: KRET
END SUBROUTINE PUT_BUFC0
END INTERFACE
