INTERFACE
SUBROUTINE RDCLIMOSFX (YDFPGEO, YDFPUSERGEO, YDSC, CDFILE, KMERGE, CDONLY)

USE PARKIND1, ONLY : JPIM
USE YOMFPGEO, ONLY : TFPGEO
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO

USE MODD_IO_SURF_ARO, ONLY : SURFEX_FIELD_BUF_CACHE

IMPLICIT NONE

TYPE (TFPGEO)    ,  INTENT(IN) :: YDFPGEO
TYPE (TFPUSERGEO),  INTENT(IN) :: YDFPUSERGEO(:)
TYPE (SURFEX_FIELD_BUF_CACHE), INTENT (INOUT) :: YDSC
CHARACTER(LEN=*), INTENT(IN)                  :: CDFILE(:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN)    :: KMERGE
CHARACTER (LEN=*),   OPTIONAL, INTENT (IN)    :: CDONLY (:)

END SUBROUTINE RDCLIMOSFX
END INTERFACE
