INTERFACE
SUBROUTINE RERESF_SFX (YDSC, YDGEOMETRY, YDMODEL)

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE MODD_IO_SURF_ARO, ONLY : SURFEX_FIELD_BUF_CACHE

IMPLICIT NONE

TYPE (SURFEX_FIELD_BUF_CACHE), INTENT (INOUT) :: YDSC
TYPE (GEOMETRY),               INTENT (IN)    :: YDGEOMETRY
TYPE (MODEL),                  INTENT (IN)    :: YDMODEL

END SUBROUTINE
END INTERFACE
