INTERFACE
SUBROUTINE WRSFX(YDRIP,YDGEOMETRY,YDFACTX,CDFIC)
USE PARKIND1, ONLY : JPRB
USE FACTX_MOD, ONLY : FACTX, FREEFACTX, FAON, FAOFF, OPENWRFACTX
USE YOMRIP       , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY), INTENT(IN)   :: YDGEOMETRY
TYPE (FACTX), INTENT (INOUT) :: YDFACTX
TYPE (TRIP),    INTENT (INOUT) :: YDRIP
CHARACTER(LEN=*),INTENT(IN)     :: CDFIC
END SUBROUTINE WRSFX
END INTERFACE
